# TPC-C Collector Demo

# Missing
* connection data beyond loading
* join to connection data
* join to monitoring_single
* connection and configuration also in monitoring and connection df

## Naming
* There is an experiment having a code, say `1775855486`.
* The experiment inspects a SUT, say `PostgreSQL-A`. This is called a `configuration`.
* The experiment is run several times, say twice. The indicator of the run is called `experiment_run`.
* Each run can have several phases as a sequence. The number of the phase is called `client`. The state of the configuration in a phase is called a `connection`.
* Each client can have several `pods`, that are run in parallel. A pod represents a driver.
* Performance metrics are collected per driver pod.  
    The naming of an instance is `<sut>-<experiment_run>-<client>-<pod>`. It is unique per experiment.
* Monitoring metrics are collected per phase. They are automatically aggregated across parallel pods.  
    The naming of an instance is `<sut>-<experiment_run>-<client>`. It is unique per experiment.

## Aggregation
* Aggregation is complicated. Some metrics are aggregated via count, sum, max or average. Others cannot be aggregated sensibly, like experiment code or latency percentiles.
* There are helper functions to aggregated pods that are certainly run in parallel.  
  So `<sut>-<experiment_run>-<client>-<pod>` are aggregated to `<sut>-<experiment_run>-<client>`.
* An exception is multi-tenancy.

## Class `collector`
* constructor `collectors.benchbase(path, codes)`
* evaluator object `evaluate = collect.get_evaluator()`
* dataframe of connection infos `collect.get_connections()`
  * index is name of client
* **monitoring metrics**
  * dataframe of available metrics `collect.df_metrics`
    * index is key of metric
  * dataframe of monitored components `collect.get_monitored_phases()`
    * index is key of component
  * dataframe of aggregated metrics per connection `collect.get_monitoring_single_all()`
    * index is name of client
    * metrics aggregated per code, experiment_run and client
  * dataframe of aggregated metrics per connection and across tenants `collect.get_monitoring_all()`
    * index just enumerates
    * metrics aggregated per code, experiment_run and client and across tenants
  * dataframe of time series for a metric of a connection in an experiment `collect.get_monitoring_timeseries_single(code, metric)`
    * index is name of connection
    * unstacked (wide format)
  * dataframe of time series for a metric in all experiments `collect.get_monitoring_timeseries_all(metric)`
    * index just enumerates
    * stacked (long format)
* **performance metrics**
  * dataframe of loading metrics `collect.get_loading_time_max_all()`
    * index is name of client
  * dataframe of performance aggregated per parallel client `collect.get_performance_all()`
    * index just enumerates
    * performance aggregated per code, experiment_run and client
  * dataframe of performance for one experiment `collect.get_performance_single()`
    * performance of each single client (driver)
    * index is name of client pod
  * dataframe of performance for all experiments `collect.get_performance_all_single()`
    * performance of each single client (driver)
    * index is name of client pod


[1] [Benchmarking Multi-Tenant Architectures in PostgreSQL](https://doi.org/10.48786/edbt.2026.46)
> Erdelt, P.K., and Rabl T. (2026)
> In: Proceedings 29th International Conference on Extending Database Technology, EDBT 2026
> OpenProceedings.org
> https://doi.org/10.48786/edbt.2026.46

In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option('display.max_colwidth', None)
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.float_format = '{:.2f}'.format

from bexhoma import collectors

%matplotlib inline

# Functions for Nice Plots

In [2]:
from notebookutils import *

# Collect Results

In [3]:
#path = r"D:\data\benchmarks"
path = r"/data/benchmarks"
filename_prefix = "demo_"
b_plot_save = False
b_skip_plots = True

In [4]:
codes = [
    "1776678767",
    "1776682364"
]

codes

['1776678767', '1776682364']

In [5]:
collect = collectors.ycsb(path, codes)

# Get all Metrics Metadata

## Metrics Names and Types

Metrics that are derived from monitoring

In [6]:
collect.df_metrics

,title,active,type,metric
total_cpu_memory,Memory Usage [MiB],True,cluster,gauge
total_cpu_memory_cached,Memory Usage Cached [MiB],True,cluster,gauge
total_cpu_util,CPU Utilization,True,cluster,gauge
total_cpu_throttled,CPU Throttle,True,cluster,gauge
total_cpu_throttled_s,CPU Throttled Time [s],True,cluster,counter
total_cpu_util_others,CPU Utilization Others,False,cluster,gauge
total_cpu_util_s,CPU Utilization Time [s],True,cluster,counter
total_cpu_util_user_s,CPU User Time [s],True,cluster,counter
total_cpu_util_sys_s,CPU System Time [s],True,cluster,counter
total_cpu_util_others_s,CPU Utilization Time Others [s],False,cluster,counter
total_network_rx,Network Rx Total [MiB],True,cluster,counter
total_network_tx,Network Tx Total [MiB],True,cluster,counter
total_fs_read,Filesystem Read Total [MiB],True,cluster,counter
total_fs_write,Filesystem Write Total [MiB],True,cluster,counter
total_gpu_util,GPU Utilization [%],False,cluster,gauge
total_gpu_power,GPU Power Usage [W],False,cluster,gauge
total_gpu_memory,GPU Memory Usage [MiB],False,cluster,gauge
core_variance,Core Utilization Variance [%],True,cluster,ratio
max_core_util,Max Core Utilization [%],True,cluster,ratio
io_wait_pct,I/O Wait [%],True,cluster,ratio
io_wait_total,Total I/O Wait Time [s],True,cluster,counter

## Names of Monitored Components

Names of components and their phases

In [7]:
collect.get_monitored_components()

                                        description
loading               Loading phase: SUT deployment
loader              Loading phase: component loader
stream              Execution phase: SUT deployment
benchmarker  Execution phase: component benchmarker

# Get Connection Infos

List of states of SUTs, containing loading infos.

In [8]:
df=collect.get_connections()

In [9]:
df.T

,1776678767-PostgreSQL-64-8-65536-1-1,1776678767-PostgreSQL-64-8-65536-2-1,1776678767-PostgreSQL-64-8-65536-2-2,1776678767-PostgreSQL-64-8-65536-2-3,1776678767-PostgreSQL-64-8-65536-2-4,1776678767-PostgreSQL-64-8-65536-2-5,1776678767-PostgreSQL-64-8-65536-2-6,1776678767-PostgreSQL-64-8-65536-2-7,1776678767-PostgreSQL-64-8-65536-2-8,1776682364-PostgreSQL-64-8-65536-1-1,1776682364-PostgreSQL-64-8-65536-2-1,1776682364-PostgreSQL-64-8-65536-2-2,1776682364-PostgreSQL-64-8-65536-2-3,1776682364-PostgreSQL-64-8-65536-2-4,1776682364-PostgreSQL-64-8-65536-2-5,1776682364-PostgreSQL-64-8-65536-2-6,1776682364-PostgreSQL-64-8-65536-2-7,1776682364-PostgreSQL-64-8-65536-2-8
code,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364
connection,1776678767-PostgreSQL-64-8-65536-1-1,1776678767-PostgreSQL-64-8-65536-2-1,1776678767-PostgreSQL-64-8-65536-2-2,1776678767-PostgreSQL-64-8-65536-2-3,1776678767-PostgreSQL-64-8-65536-2-4,1776678767-PostgreSQL-64-8-65536-2-5,1776678767-PostgreSQL-64-8-65536-2-6,1776678767-PostgreSQL-64-8-65536-2-7,1776678767-PostgreSQL-64-8-65536-2-8,1776682364-PostgreSQL-64-8-65536-1-1,1776682364-PostgreSQL-64-8-65536-2-1,1776682364-PostgreSQL-64-8-65536-2-2,1776682364-PostgreSQL-64-8-65536-2-3,1776682364-PostgreSQL-64-8-65536-2-4,1776682364-PostgreSQL-64-8-65536-2-5,1776682364-PostgreSQL-64-8-65536-2-6,1776682364-PostgreSQL-64-8-65536-2-7,1776682364-PostgreSQL-64-8-65536-2-8
configuration,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536
phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2
experiment_run,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
client,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00
time_ingest,886.00,886.00,886.00,886.00,886.00,886.00,886.00,886.00,886.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00
time_check,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,8,8,8,8,8,8,8,8,1,8,8,8,8,8,8,8,8
tenant,,,,,,,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,7091,8548,8548,8548,8548,8548,8548,8548,8548,7091,8546,8546,8546,8546,8546,8546,8546,8546
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,,,,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,158125,159582,159582,159582,159582,159582,159582,159582,159582,158125,159581,159581,159581,159581,159581,159581,159581,159581
host_datadisk,7091,8548,8548,8548,8548,8548,8548,8548,8548,7091,8546,8546,8546,8546,8546,8546,8546,8546
host_volume_size,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_YCSB_THREADCOUNT,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_YCSB_TARGET,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192
loading_parameters_YCSB_STATUS,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_YCSB_WORKLOAD,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
loading_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000
loading_parameters_YCSB_OPERATIONS,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000
loading_parameters_YCSB_BATCHSIZE,,,,,,,,,,,,,,,,,,
loading_parameters_YCSB_STATUS_INTERVAL,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
loading_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc
loading_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
loading_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed
benchmarking_parameters_PARALLEL,1,8,8,8,8,8,8,8,8,1,8,8,8,8,8,8,8,8
benchmarking_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
benchmarking_parameters_YCSB_THREADCOUNT,64,8,8,8,8,8,8,8,8,64,8,8,8,8,8,8,8,8
benchmarking_parameters_YCSB_TARGET,32768,4096,4096,4096,4096,4096,4096,4096,4096,49152,6144,6144,6144,6144,6144,6144,6144,6144
benchmarking_parameters_YCSB_STATUS,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
benchmarking_parameters_YCSB_WORKLOAD,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
benchmarking_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000
benchmarking_parameters_YCSB_OPERATIONS,3000000,375000,375000,375000,375000,375000,375000,375000,375000,3000000,375000,375000,375000,375000,375000,375000,375000,375000
benchmarking_parameters_YCSB_BATCHSIZE,,,,,,,,,,,,,,,,,,
benchmarking_parameters_YCSB_STATUS_INTERVAL,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
benchmarking_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc
benchmarking_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
benchmarking_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [10]:
df[['phase', 'code', 'connection', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']]

,phase,code,connection,configuration,experiment_run,client,type_tenants,num_tenants,vol_tenants
1776678767-PostgreSQL-64-8-65536-1-1,1776678767-PostgreSQL-64-8-65536-1,1776678767,1776678767-PostgreSQL-64-8-65536-1-1,PostgreSQL-64-8-65536,1,1,None,0,False
1776678767-PostgreSQL-64-8-65536-2-1,1776678767-PostgreSQL-64-8-65536-2,1776678767,1776678767-PostgreSQL-64-8-65536-2-1,PostgreSQL-64-8-65536,1,2,None,0,False
1776678767-PostgreSQL-64-8-65536-2-2,1776678767-PostgreSQL-64-8-65536-2,1776678767,1776678767-PostgreSQL-64-8-65536-2-2,PostgreSQL-64-8-65536,1,2,None,0,False
1776678767-PostgreSQL-64-8-65536-2-3,1776678767-PostgreSQL-64-8-65536-2,1776678767,1776678767-PostgreSQL-64-8-65536-2-3,PostgreSQL-64-8-65536,1,2,None,0,False
1776678767-PostgreSQL-64-8-65536-2-4,1776678767-PostgreSQL-64-8-65536-2,1776678767,1776678767-PostgreSQL-64-8-65536-2-4,PostgreSQL-64-8-65536,1,2,None,0,False
1776678767-PostgreSQL-64-8-65536-2-5,1776678767-PostgreSQL-64-8-65536-2,1776678767,1776678767-PostgreSQL-64-8-65536-2-5,PostgreSQL-64-8-65536,1,2,None,0,False
1776678767-PostgreSQL-64-8-65536-2-6,1776678767-PostgreSQL-64-8-65536-2,1776678767,1776678767-PostgreSQL-64-8-65536-2-6,PostgreSQL-64-8-65536,1,2,None,0,False
1776678767-PostgreSQL-64-8-65536-2-7,1776678767-PostgreSQL-64-8-65536-2,1776678767,1776678767-PostgreSQL-64-8-65536-2-7,PostgreSQL-64-8-65536,1,2,None,0,False
1776678767-PostgreSQL-64-8-65536-2-8,1776678767-PostgreSQL-64-8-65536-2,1776678767,1776678767-PostgreSQL-64-8-65536-2-8,PostgreSQL-64-8-65536,1,2,None,0,False
1776682364-PostgreSQL-64-8-65536-1-1,1776682364-PostgreSQL-64-8-65536-1,1776682364,1776682364-PostgreSQL-64-8-65536-1-1,PostgreSQL-64-8-65536,1,1,None,0,False
1776682364-PostgreSQL-64-8-65536-2-1,1776682364-PostgreSQL-64-8-65536-2,1776682364,1776682364-PostgreSQL-64-8-65536-2-1,PostgreSQL-64-8-65536,1,2,None,0,False
1776682364-PostgreSQL-64-8-65536-2-2,1776682364-PostgreSQL-64-8-65536-2,1776682364,1776682364-PostgreSQL-64-8-65536-2-2,PostgreSQL-64-8-65536,1,2,None,0,False
1776682364-PostgreSQL-64-8-65536-2-3,1776682364-PostgreSQL-64-8-65536-2,1776682364,1776682364-PostgreSQL-64-8-65536-2-3,PostgreSQL-64-8-65536,1,2,None,0,False
1776682364-PostgreSQL-64-8-65536-2-4,1776682364-PostgreSQL-64-8-65536-2,1776682364,1776682364-PostgreSQL-64-8-65536-2-4,PostgreSQL-64-8-65536,1,2,None,0,False
1776682364-PostgreSQL-64-8-65536-2-5,1776682364-PostgreSQL-64-8-65536-2,1776682364,1776682364-PostgreSQL-64-8-65536-2-5,PostgreSQL-64-8-65536,1,2,None,0,False
1776682364-PostgreSQL-64-8-65536-2-6,1776682364-PostgreSQL-64-8-65536-2,1776682364,1776682364-PostgreSQL-64-8-65536-2-6,PostgreSQL-64-8-65536,1,2,None,0,False
1776682364-PostgreSQL-64-8-65536-2-7,1776682364-PostgreSQL-64-8-65536-2,1776682364,1776682364-PostgreSQL-64-8-65536-2-7,PostgreSQL-64-8-65536,1,2,None,0,False
1776682364-PostgreSQL-64-8-65536-2-8,1776682364-PostgreSQL-64-8-65536-2,1776682364,1776682364-PostgreSQL-64-8-65536-2-8,PostgreSQL-64-8-65536,1,2,None,0,False

In [11]:
collectors.get_non_constant(df).T

,1776678767-PostgreSQL-64-8-65536-1-1,1776678767-PostgreSQL-64-8-65536-2-1,1776678767-PostgreSQL-64-8-65536-2-2,1776678767-PostgreSQL-64-8-65536-2-3,1776678767-PostgreSQL-64-8-65536-2-4,1776678767-PostgreSQL-64-8-65536-2-5,1776678767-PostgreSQL-64-8-65536-2-6,1776678767-PostgreSQL-64-8-65536-2-7,1776678767-PostgreSQL-64-8-65536-2-8,1776682364-PostgreSQL-64-8-65536-1-1,1776682364-PostgreSQL-64-8-65536-2-1,1776682364-PostgreSQL-64-8-65536-2-2,1776682364-PostgreSQL-64-8-65536-2-3,1776682364-PostgreSQL-64-8-65536-2-4,1776682364-PostgreSQL-64-8-65536-2-5,1776682364-PostgreSQL-64-8-65536-2-6,1776682364-PostgreSQL-64-8-65536-2-7,1776682364-PostgreSQL-64-8-65536-2-8
code,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364
connection,1776678767-PostgreSQL-64-8-65536-1-1,1776678767-PostgreSQL-64-8-65536-2-1,1776678767-PostgreSQL-64-8-65536-2-2,1776678767-PostgreSQL-64-8-65536-2-3,1776678767-PostgreSQL-64-8-65536-2-4,1776678767-PostgreSQL-64-8-65536-2-5,1776678767-PostgreSQL-64-8-65536-2-6,1776678767-PostgreSQL-64-8-65536-2-7,1776678767-PostgreSQL-64-8-65536-2-8,1776682364-PostgreSQL-64-8-65536-1-1,1776682364-PostgreSQL-64-8-65536-2-1,1776682364-PostgreSQL-64-8-65536-2-2,1776682364-PostgreSQL-64-8-65536-2-3,1776682364-PostgreSQL-64-8-65536-2-4,1776682364-PostgreSQL-64-8-65536-2-5,1776682364-PostgreSQL-64-8-65536-2-6,1776682364-PostgreSQL-64-8-65536-2-7,1776682364-PostgreSQL-64-8-65536-2-8
phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2
client,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2
time_load,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00
time_ingest,886.00,886.00,886.00,886.00,886.00,886.00,886.00,886.00,886.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00
time_check,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00
pods,1,8,8,8,8,8,8,8,8,1,8,8,8,8,8,8,8,8
datadisk,7091,8548,8548,8548,8548,8548,8548,8548,8548,7091,8546,8546,8546,8546,8546,8546,8546,8546
host_disk,158125,159582,159582,159582,159582,159582,159582,159582,159582,158125,159581,159581,159581,159581,159581,159581,159581,159581
host_datadisk,7091,8548,8548,8548,8548,8548,8548,8548,8548,7091,8546,8546,8546,8546,8546,8546,8546,8546
benchmarking_parameters_PARALLEL,1,8,8,8,8,8,8,8,8,1,8,8,8,8,8,8,8,8
benchmarking_parameters_YCSB_THREADCOUNT,64,8,8,8,8,8,8,8,8,64,8,8,8,8,8,8,8,8
benchmarking_parameters_YCSB_TARGET,32768,4096,4096,4096,4096,4096,4096,4096,4096,49152,6144,6144,6144,6144,6144,6144,6144,6144
benchmarking_parameters_YCSB_OPERATIONS,3000000,375000,375000,375000,375000,375000,375000,375000,375000,3000000,375000,375000,375000,375000,375000,375000,375000,375000
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364

# Monitoring Aggregated per Phase

In [12]:
df = collect.get_monitoring_aggregated_per_phase("stream")
df.T

,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2
Memory Usage [MiB],10777.55,11361.35,10771.38,11360.51
Memory Usage Cached [MiB],14783.39,15917.04,14779.38,15918.08
CPU Utilization,0.90,0.85,0.91,0.86
CPU Throttle,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00
CPU Utilization Time [s],951.91,901.84,959.41,920.40
CPU User Time [s],482.45,441.85,494.89,450.35
CPU System Time [s],469.46,459.98,464.52,470.05
Network Rx Total [MiB],2058.80,1879.22,2203.71,1839.69
Network Tx Total [MiB],3198.48,1875.98,3322.41,1867.74
Filesystem Read Total [MiB],0.05,0.38,0.04,0.43
Filesystem Write Total [MiB],3360.94,2414.06,3329.30,2428.45
Core Utilization Variance [%],0.19,0.16,0.19,0.17
Max Core Utilization [%],4.00,2.39,4.07,2.41
I/O Wait [%],39.44,42.18,39.66,41.85
Total I/O Wait Time [s],1073.58,988.92,1023.04,986.12

### With Metadata

In [13]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2
Memory Usage [MiB],10777.55,11361.35,10771.38,11360.51
Memory Usage Cached [MiB],14783.39,15917.04,14779.38,15918.08
CPU Utilization,0.90,0.85,0.91,0.86
CPU Throttle,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00
CPU Utilization Time [s],951.91,901.84,959.41,920.40
CPU User Time [s],482.45,441.85,494.89,450.35
CPU System Time [s],469.46,459.98,464.52,470.05
Network Rx Total [MiB],2058.80,1879.22,2203.71,1839.69
Network Tx Total [MiB],3198.48,1875.98,3322.41,1867.74
Filesystem Read Total [MiB],0.05,0.38,0.04,0.43
Filesystem Write Total [MiB],3360.94,2414.06,3329.30,2428.45
Core Utilization Variance [%],0.19,0.16,0.19,0.17
Max Core Utilization [%],4.00,2.39,4.07,2.41
I/O Wait [%],39.44,42.18,39.66,41.85
Total I/O Wait Time [s],1073.58,988.92,1023.04,986.12
code,1776678767,1776678767,1776682364,1776682364
configuration,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536
experiment_run,1,1,1,1
client,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1927.00,1927.00,1992.00,1992.00
time_ingest,886.00,886.00,905.00,905.00
time_check,1040.00,1040.00,1086.00,1086.00
terminals,0,0,0,0
pods,1,8,1,8
tenant,,,,
num_worker,0,0,0,0
type_tenants,None,None,None,None
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,7091,8548,7091,8546
host_RAM,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,
host_Cores,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,158125,159582,158125,159581
host_datadisk,7091,8548,7091,8546
host_volume_size,0,0,0,0
host_volume_used,0,0,0,0
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0
host_limits_memory,0,0,0,0
loading_parameters_PARALLEL,8,8,8,8
loading_parameters_SF,3,3,3,3
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
loading_parameters_YCSB_THREADCOUNT,8,8,8,8
loading_parameters_YCSB_TARGET,8192,8192,8192,8192
loading_parameters_YCSB_STATUS,1,1,1,1
loading_parameters_YCSB_WORKLOAD,a,a,a,a
loading_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000
loading_parameters_YCSB_OPERATIONS,375000,375000,375000,375000
loading_parameters_YCSB_BATCHSIZE,,,,
loading_parameters_YCSB_STATUS_INTERVAL,10,10,10,10
loading_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc
loading_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
loading_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed
benchmarking_parameters_PARALLEL,1,8,1,8
benchmarking_parameters_SF,3,3,3,3
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
benchmarking_parameters_YCSB_THREADCOUNT,64,8,64,8
benchmarking_parameters_YCSB_TARGET,32768,4096,49152,6144
benchmarking_parameters_YCSB_STATUS,1,1,1,1
benchmarking_parameters_YCSB_WORKLOAD,a,a,a,a
benchmarking_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000
benchmarking_parameters_YCSB_OPERATIONS,3000000,375000,3000000,375000
benchmarking_parameters_YCSB_BATCHSIZE,,,,
benchmarking_parameters_YCSB_STATUS_INTERVAL,10,10,10,10
benchmarking_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc
benchmarking_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
benchmarking_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2

In [14]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2
phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2
code,1776678767,1776678767,1776682364,1776682364
configuration,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536
experiment_run,1,1,1,1
client,1,2,1,2
type_tenants,None,None,None,None
num_tenants,0,0,0,0
vol_tenants,False,False,False,False

# Time Series of a Single Metric for a Single Experiment

In [15]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_per_phase(code, metric=metric, component='stream')
df.T

      1776678767-PostgreSQL-64-8-65536-1  1776678767-PostgreSQL-64-8-65536-2
0                                9579.14                            10350.32
1                                9579.14                            10350.32
2                                9579.14                            10350.32
3                                9579.14                            10350.32
4                                9790.00                            10350.32
5                                9790.00                            10350.32
6                                9790.00                            10350.32
7                                9790.00                            10350.32
8                                9790.00                            10350.32
9                                9790.00                            10350.32
10                               9790.00                            10350.32
11                               9790.00                            10350.32
12                               9790.00                            10350.32
13                               9790.00                            10350.32
14                               9790.00                            10350.32
15                               9790.00                            10350.32
16                               9790.00                            10350.32
17                               9790.00                            10828.79
18                               9790.00                            10828.79
19                               9790.00                            10828.79
20                               9790.00                            10828.79
21                               9790.00                            10828.79
22                               9790.00                            10828.79
23                               9790.00                            10828.79
24                               9790.00                            10828.79
25                               9790.00                            10828.79
26                               9790.00                            10828.79
27                               9790.00                            10828.79
28                              10092.41                            10828.79
29                              10092.41                            10828.79
30                              10092.41                            10828.79
31                              10092.41                            10828.79
32                              10092.41                            10946.05
33                              10092.41                            10946.05
34                              10092.41                            10946.05
35                              10092.41                            10946.05
36                              10092.41                            10946.05
37                              10092.41                            10946.05
38                              10092.41                            10946.05
39                              10092.41                            10946.05
40                              10092.41                            10946.05
41                              10092.41                            10946.05
42                              10092.41                            10946.05
43                              10092.41                            10946.05
44                              10092.41                            10946.05
45                              10092.41                            10946.05
46                              10092.41                            10946.05
47                              10092.41                            10946.05
48                              10092.41                            10946.05
49                              10092.41                            10946.05
50                              10092.41                            10946.05
51                              10092.41                            10946.05
52                              10092.41                            10946.05
53                              10092.41                            10946.05
54                              10092.41                            10946.05
55                              10092.41                            10946.05
56                              10092.41                            10946.05
57                              10092.41                            10946.05
58                              10092.41                            10946.05
59                              10092.41                            11064.57
60                              10092.41                            11064.57
61                              10092.41                            11064.57
62                              10092.41                            11064.57
63                              10092.41                            11064.57
64                              10092.41                            11064.57
65                              10092.41                            11064.57
66                              10092.41                            11064.57
67                              10092.41                            11064.57
68                              10092.41                            11064.57
69                              10092.41                            11064.57
70                              10270.28                            11064.57
71                              10270.28                            11064.57
72                              10270.28                            11064.57
73                              10270.28                            11064.57
74                              10270.28                            11064.57
75                              10270.28                            11064.57
76                              10270.28                            11064.57
77                              10270.28                            11064.57
78                              10270.28                            11064.57
79                              10270.28                            11064.57
80                              10270.28                            11064.57
81                              10270.28                            11064.57
82                              10270.28                            11064.57
83                              10270.28                            11064.57
84                              10270.28                            11064.57
85                              10270.28                            11064.57
86                              10270.28                            11064.57
87                              10270.28                            11064.57
88                              10270.28                            11064.57
89                              10270.28                            11064.57
90                              10270.28                            11064.57
91                              10270.28                            11064.57
92                              10270.28                            11064.57
93                              10270.28                            11064.57
94                              10270.28                            11064.57
95                              10270.28                            11064.57
96                              10270.28                            11064.57
97                              10270.28                            11064.57
98                              10270.28                            11064.57
99                              10270.28                            11064.57
100                             10270.28                            11064.57
101                             10270.28                            11064.57
102                             10348.59                            11064.57
103                             10348.59                            11064.57
104                             10348.59                            11064.57
105                             10348.59                            11064.57
106                             10348.59                            11064.57
107                             10348.59                            11153.88
108                             10348.59                            11153.88
109                             10348.59                            11153.88
110                             10348.59                            11153.88
111                             10348.59                            11153.88
112                             10348.59                            11153.88
113                             10348.59                            11153.88
114                             10348.59                            11153.88
115                             10348.59                            11153.88
116                             10348.59                            11153.88
117                             10348.59                            11153.88
118                             10348.59                            11153.88
119                             10348.59                            11153.88
120                             10348.59                            11153.88
121                             10348.59                            11153.88
122                             10348.59                            11153.88
123                             10348.59                            11168.64
124                             10348.59                            11168.64
125                             10348.59                            11168.64
126                             10348.59                            11168.64
127                             10348.59                            11168.64
128                             10395.31                            11168.64
129                             10395.31                            11168.64
130                             10395.31                            11168.64
131                             10395.31                            11168.64
132                             10395.31                            11168.64
133                             10395.31                            11168.64
134                             10395.31                            11168.64
135                             10395.31                            11168.64
136                             10395.31                            11168.64
137                             10395.31                            11168.64
138                             10395.31                            11168.64
139                             10395.31                            11168.64
140                             10395.31                            11168.64
141                             10395.31                            11168.64
142                             10395.31                            11168.64
143                             10395.31                            11168.64
144                             10395.31                            11168.64
145                             10395.31                            11168.64
146                             10395.31                            11168.64
147                             10395.31                            11168.64
148                             10395.31                            11168.64
149                             10395.31                            11168.64
150                             10395.31                            11168.64
151                             10395.31                            11168.64
152                             10395.31                            11168.64
153                             10395.31                            11168.64
154                             10395.31                            11197.30
155                             10395.31                            11197.30
156                             10395.31                            11197.30
157                             10395.31                            11197.30
158                             10395.31                            11197.30
159                             10446.87                            11197.30
160                             10446.87                            11197.30
161                             10446.87                            11197.30
162                             10446.87                            11197.30
163                             10446.87                            11197.30
164                             10446.87                            11197.30
165                             10446.87                            11197.30
166                             10446.87                            11197.30
167                             10446.87                            11197.30
168                             10446.87                            11197.30
169                             10446.87                            11197.30
170                             10446.87                            11197.30
171                             10446.87                            11197.30
172                             10446.87                            11197.30
173                             10446.87                            11197.30
174                             10446.87                            11197.30
175                             10446.87                            11197.30
176                             10446.87                            11197.30
177                             10446.87                            11197.30
178                             10446.87                            11197.30
179                             10446.87                            11197.30
180                             10446.87                            11197.30
181                             10446.87                            11197.30
182                             10446.87                            11197.30
183                             10446.87                            11197.30
184                             10446.87                            11197.30
185                             10446.87                            11197.30
186                             10446.87                            11197.30
187                             10446.87                            11197.30
188                             10446.87                            11197.30
189                             10446.87                            11221.06
190                             10446.87                            11221.06
191                             10446.87                            11221.06
192                             10446.87                            11221.06
193                             10446.87                            11221.06
194                             10494.77                            11221.06
195                             10494.77                            11221.06
196                             10494.77                            11221.06
197                             10494.77                            11221.06
198                             10494.77                            11221.06
199                             10494.77                            11221.06
200                             10494.77                            11221.06
201                             10494.77                            11221.06
202                             10494.77                            11221.06
203                             10494.77                            11221.06
204                             10494.77                            11221.06
205                             10494.77                            11221.06
206                             10494.77                            11221.06
207                             10494.77                            11221.06
208                             10494.77                            11221.06
209                             10516.95                            11221.06
210                             10516.95                            11221.06
211                             10516.95                            11221.06
212                             10516.95                            11221.06
213                             10516.95                            11221.06
214                             10516.95                            11221.06
215                             10516.95                            11221.06
216                             10516.95                            11221.06
217                             10516.95                            11221.06
218                             10516.95                            11240.78
219                             10516.95                            11240.78
220                             10516.95                            11240.78
221                             10516.95                            11240.78
222                             10516.95                            11240.78
223                             10516.95                            11240.78
224                             10516.95                            11240.78
225                             10516.95                            11240.78
226                             10516.95                            11240.78
227                             10516.95                            11240.78
228                             10516.95                            11240.78
229                             10516.95                            11240.78
230                             10516.95                            11240.78
231                             10516.95                            11240.78
232                             10516.95                            11240.78
233                             10516.95                            11240.78
234                             10516.95                            11240.78
235                             10516.95                            11240.78
236                             10516.95                            11240.78
237                             10516.95                            11240.78
238                             10516.95                            11240.78
239                             10516.95                            11240.78
240                             10556.27                            11240.78
241                             10556.27                            11240.78
242                             10556.27                            11240.78
243                             10556.27                            11240.78
244                             10556.27                            11240.78
245                             10556.27                            11240.78
246                             10556.27                            11240.78
247                             10556.27                            11240.78
248                             10556.27                            11240.78
249                             10556.27                            11240.78
250                             10556.27                            11240.78
251                             10556.27                            11240.78
252                             10556.27                            11240.78
253                             10556.27                            11240.78
254                             10556.27                            11240.78
255                             10556.27                            11240.78
256                             10556.27                            11240.78
257                             10556.27                            11263.95

### With Metadata

In [16]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2
0,9579.14,10350.32
1,9579.14,10350.32
2,9579.14,10350.32
3,9579.14,10350.32
4,9790.00,10350.32
5,9790.00,10350.32
6,9790.00,10350.32
7,9790.00,10350.32
8,9790.00,10350.32
9,9790.00,10350.32
10,9790.00,10350.32
11,9790.00,10350.32
12,9790.00,10350.32
13,9790.00,10350.32
14,9790.00,10350.32
15,9790.00,10350.32
16,9790.00,10350.32
17,9790.00,10828.79
18,9790.00,10828.79
19,9790.00,10828.79
20,9790.00,10828.79
21,9790.00,10828.79
22,9790.00,10828.79
23,9790.00,10828.79
24,9790.00,10828.79
25,9790.00,10828.79
26,9790.00,10828.79
27,9790.00,10828.79
28,10092.41,10828.79
29,10092.41,10828.79
30,10092.41,10828.79
31,10092.41,10828.79
32,10092.41,10946.05
33,10092.41,10946.05
34,10092.41,10946.05
35,10092.41,10946.05
36,10092.41,10946.05
37,10092.41,10946.05
38,10092.41,10946.05
39,10092.41,10946.05
40,10092.41,10946.05
41,10092.41,10946.05
42,10092.41,10946.05
43,10092.41,10946.05
44,10092.41,10946.05
45,10092.41,10946.05
46,10092.41,10946.05
47,10092.41,10946.05
48,10092.41,10946.05
49,10092.41,10946.05
50,10092.41,10946.05
51,10092.41,10946.05
52,10092.41,10946.05
53,10092.41,10946.05
54,10092.41,10946.05
55,10092.41,10946.05
56,10092.41,10946.05
57,10092.41,10946.05
58,10092.41,10946.05
59,10092.41,11064.57
60,10092.41,11064.57
61,10092.41,11064.57
62,10092.41,11064.57
63,10092.41,11064.57
64,10092.41,11064.57
65,10092.41,11064.57
66,10092.41,11064.57
67,10092.41,11064.57
68,10092.41,11064.57
69,10092.41,11064.57
70,10270.28,11064.57
71,10270.28,11064.57
72,10270.28,11064.57
73,10270.28,11064.57
74,10270.28,11064.57
75,10270.28,11064.57
76,10270.28,11064.57
77,10270.28,11064.57
78,10270.28,11064.57
79,10270.28,11064.57
80,10270.28,11064.57
81,10270.28,11064.57
82,10270.28,11064.57
83,10270.28,11064.57
84,10270.28,11064.57
85,10270.28,11064.57
86,10270.28,11064.57
87,10270.28,11064.57
88,10270.28,11064.57
89,10270.28,11064.57
90,10270.28,11064.57
91,10270.28,11064.57
92,10270.28,11064.57
93,10270.28,11064.57
94,10270.28,11064.57
95,10270.28,11064.57
96,10270.28,11064.57
97,10270.28,11064.57
98,10270.28,11064.57
99,10270.28,11064.57
100,10270.28,11064.57
101,10270.28,11064.57
102,10348.59,11064.57
103,10348.59,11064.57
104,10348.59,11064.57
105,10348.59,11064.57
106,10348.59,11064.57
107,10348.59,11153.88
108,10348.59,11153.88
109,10348.59,11153.88
110,10348.59,11153.88
111,10348.59,11153.88
112,10348.59,11153.88
113,10348.59,11153.88
114,10348.59,11153.88
115,10348.59,11153.88
116,10348.59,11153.88
117,10348.59,11153.88
118,10348.59,11153.88
119,10348.59,11153.88
120,10348.59,11153.88
121,10348.59,11153.88
122,10348.59,11153.88
123,10348.59,11168.64
124,10348.59,11168.64
125,10348.59,11168.64
126,10348.59,11168.64
127,10348.59,11168.64
128,10395.31,11168.64
129,10395.31,11168.64
130,10395.31,11168.64
131,10395.31,11168.64
132,10395.31,11168.64
133,10395.31,11168.64
134,10395.31,11168.64
135,10395.31,11168.64
136,10395.31,11168.64
137,10395.31,11168.64
138,10395.31,11168.64
139,10395.31,11168.64
140,10395.31,11168.64
141,10395.31,11168.64
142,10395.31,11168.64
143,10395.31,11168.64
144,10395.31,11168.64
145,10395.31,11168.64
146,10395.31,11168.64
147,10395.31,11168.64
148,10395.31,11168.64
149,10395.31,11168.64
150,10395.31,11168.64
151,10395.31,11168.64
152,10395.31,11168.64
153,10395.31,11168.64
154,10395.31,11197.30
155,10395.31,11197.30
156,10395.31,11197.30
157,10395.31,11197.30
158,10395.31,11197.30
159,10446.87,11197.30
160,10446.87,11197.30
161,10446.87,11197.30
162,10446.87,11197.30
163,10446.87,11197.30
164,10446.87,11197.30
165,10446.87,11197.30
166,10446.87,11197.30
167,10446.87,11197.30
168,10446.87,11197.30
169,10446.87,11197.30
170,10446.87,11197.30
171,10446.87,11197.30
172,10446.87,11197.30
173,10446.87,11197.30
174,10446.87,11197.30
175,10446.87,11197.30
176,10446.87,11197.30
177,10446.87,11197.30
178,10446.87,11197.30
179,10446.87,11197.30
180,10446.87,11197.30
181,10446.87,11197.30
182,10446.87,11197.30
183,10446.87,11197.30
184,10446.87,11197.30
185,10446.87,11197.30
186,10446.87,11197.30
187,10446.87,11197.30
188,10446.87,11197.30
189,10446.87,11221.06
190,10446.87,11221.06
191,10446.87,11221.06
192,10446.87,11221.06
193,10446.87,11221.06
194,10494.77,11221.06
195,10494.77,11221.06
196,10494.77,11221.06
197,10494.77,11221.06
198,10494.77,11221.06
199,10494.77,11221.06
200,10494.77,11221.06
201,10494.77,11221.06
202,10494.77,11221.06
203,10494.77,11221.06
204,10494.77,11221.06
205,10494.77,11221.06
206,10494.77,11221.06
207,10494.77,11221.06
208,10494.77,11221.06
209,10516.95,11221.06
210,10516.95,11221.06
211,10516.95,11221.06
212,10516.95,11221.06
213,10516.95,11221.06
214,10516.95,11221.06
215,10516.95,11221.06
216,10516.95,11221.06
217,10516.95,11221.06
218,10516.95,11240.78
219,10516.95,11240.78
220,10516.95,11240.78
221,10516.95,11240.78
222,10516.95,11240.78
223,10516.95,11240.78
224,10516.95,11240.78
225,10516.95,11240.78
226,10516.95,11240.78
227,10516.95,11240.78
228,10516.95,11240.78
229,10516.95,11240.78
230,10516.95,11240.78
231,10516.95,11240.78
232,10516.95,11240.78
233,10516.95,11240.78
234,10516.95,11240.78
235,10516.95,11240.78
236,10516.95,11240.78
237,10516.95,11240.78
238,10516.95,11240.78
239,10516.95,11240.78
240,10556.27,11240.78
241,10556.27,11240.78
242,10556.27,11240.78
243,10556.27,11240.78
244,10556.27,11240.78
245,10556.27,11240.78
246,10556.27,11240.78
247,10556.27,11240.78
248,10556.27,11240.78
249,10556.27,11240.78
250,10556.27,11240.78
251,10556.27,11240.78
252,10556.27,11240.78
253,10556.27,11240.78
254,10556.27,11240.78
255,10556.27,11240.78
256,10556.27,11240.78
257,10556.27,11263.95
258,10556.27,11263.95
259,10556.27,11263.95
260,10556.27,11263.95
261,10556.27,11263.95
262,10556.27,11263.95
263,10556.27,11263.95
264,10556.27,11263.95
265,10556.27,11263.95
266,10556.27,11263.95
267,10556.27,11263.95
268,10556.27,11263.95
269,10556.27,11263.95
270,10556.27,11263.95
271,10556.27,11263.95
272,10556.27,11263.95
273,10556.27,11263.95
274,10556.27,11263.95
275,10556.27,11263.95
276,10556.27,11263.95
277,10556.27,11263.95
278,10556.27,11263.95
279,10556.27,11263.95
280,10556.27,11263.95
281,10556.27,11263.95
282,10610.66,11263.95
283,10610.66,11263.95
284,10610.66,11263.95
285,10610.66,11263.95
286,10610.66,11280.95
287,10610.66,11280.95
288,10610.66,11280.95
289,10610.66,11280.95
290,10610.66,11280.95
291,10610.66,11280.95
292,10610.66,11280.95
293,10610.66,11280.95
294,10610.66,11280.95
295,10610.66,11280.95
296,10610.66,11280.95
297,10610.66,11280.95
298,10610.66,11280.95
299,10610.66,11280.95
300,10610.66,11280.95
301,10610.66,11280.95
302,10610.66,11280.95
303,10610.66,11280.95
304,10610.66,11280.95
305,10610.66,11280.95
306,10610.66,11280.95
307,10610.66,11280.95
308,10610.66,11280.95
309,10610.66,11280.95
310,10610.66,11280.95
311,10644.07,11280.95
312,10644.07,11280.95
313,10644.07,11280.95
314,10644.07,11298.58
315,10644.07,11298.58
316,10644.07,11298.58
317,10644.07,11298.58
318,10644.07,11298.58
319,10644.07,11298.58
320,10644.07,11298.58
321,10644.07,11298.58
322,10644.07,11298.58
323,10644.07,11298.58
324,10644.07,11298.58
325,10644.07,11298.58
326,10644.07,11298.58
327,10644.07,11298.58
328,10644.07,11298.58
329,10644.07,11298.58
330,10644.07,11298.58
331,10644.07,11298.58
332,10644.07,11298.58
333,10644.07,11309.23
334,10644.07,11309.23
335,10644.07,11309.23
336,10644.07,11309.23
337,10644.07,11309.23
338,10644.07,11309.23
339,10675.76,11309.23
340,10675.76,11309.23
341,10675.76,11309.23
342,10675.76,11309.23
343,10675.76,11309.23
344,10675.76,11309.23
345,10675.76,11309.23
346,10675.76,11309.23
347,10675.76,11309.23
348,10675.76,11309.23
349,10675.76,11309.23
350,10675.76,11309.23
351,10675.76,11309.23
352,10675.76,11309.23
353,10675.76,11309.23
354,10675.76,11309.23
355,10675.76,11309.23
356,10675.76,11309.23
357,10675.76,11309.23
358,10675.76,11309.23
359,10675.76,11309.23
360,10675.76,11309.23
361,10675.76,11309.23
362,10675.76,11309.23
363,10675.76,11309.23
364,10675.76,11309.23
365,10675.76,11309.23
366,10675.76,11309.23
367,10675.76,11309.23
368,10675.76,11309.23
369,10675.76,11309.23
370,10675.76,11326.14
371,10711.84,11326.14
372,10711.84,11326.14
373,10711.84,11326.14
374,10711.84,11326.14
375,10711.84,11326.14
376,10711.84,11326.14
377,10711.84,11326.14
378,10711.84,11326.14
379,10711.84,11326.14
380,10711.84,11326.14
381,10711.84,11326.14
382,10711.84,11326.14
383,10711.84,11326.14
384,10711.84,11326.14
385,10711.84,11326.14
386,10711.84,11326.14
387,10711.84,11326.14
388,10711.84,11326.14
389,10711.84,11326.14
390,10711.84,11326.14
391,10711.84,11326.14
392,10711.84,11326.14
393,10711.84,11326.14
394,10711.84,11326.14
395,10711.84,11326.14
396,10711.84,11326.14
397,10711.84,11326.14
398,10711.84,11326.14
399,10711.84,11326.14
400,10739.51,11326.14
401,10739.51,11326.14
402,10739.51,11326.14
403,10739.51,11347.02
404,10739.51,11347.02
405,10739.51,11347.02
406,10739.51,11347.02
407,10739.51,11347.02
408,10739.51,11347.02
409,10739.51,11347.02
410,10739.51,11347.02
411,10739.51,11347.02
412,10739.51,11347.02
413,10739.51,11347.02
414,10739.51,11347.02
415,10739.51,11347.02
416,10739.51,11347.02
417,10739.51,11347.02
418,10739.51,11347.02
419,10739.51,11347.02
420,10739.51,11347.02
421,10739.51,11347.02
422,10739.51,11347.02
423,10739.51,11347.02
424,10739.51,11347.02
425,10765.96,11347.02
426,10765.96,11347.02
427,10765.96,11347.02
428,10765.96,11347.02
429,10765.96,11347.02
430,10765.96,11347.02
431,10765.96,11363.67
432,10765.96,11363.67
433,10765.96,11363.67
434,10765.96,11363.67
435,10765.96,11363.67
436,10765.96,11363.67
437,10765.96,11363.67
438,10765.96,11363.67
439,10765.96,11363.67
440,10765.96,11363.67
441,10765.96,11363.67
442,10765.96,11363.67
443,10765.96,11363.67
444,10765.96,11363.67
445,10765.96,11363.67
446,10765.96,11363.67
447,10765.96,11363.67
448,10765.96,11363.67
449,10765.96,11363.67
450,10765.96,11363.67
451,10765.96,11363.67
452,10765.96,11363.67
453,10765.96,11363.67
454,10765.96,11363.67
455,10765.96,11363.67
456,10765.96,11363.67
457,10765.96,11363.67
458,10796.47,11363.67
459,10796.47,11363.67
460,10796.47,11363.67
461,10796.47,11363.67
462,10796.47,11363.67
463,10796.47,11363.67
464,10796.47,11363.67
465,10796.47,11363.67
466,10796.47,11363.67
467,10796.47,11382.28
468,10796.47,11382.28
469,10796.47,11382.28
470,10796.47,11382.28
471,10796.47,11382.28
472,10796.47,11382.28
473,10796.47,11382.28
474,10796.47,11382.28
475,10796.47,11382.28
476,10796.47,11382.28
477,10796.47,11382.28
478,10796.47,11382.28
479,10796.47,11382.28
480,10796.47,11382.28
481,10821.36,11382.28
482,10821.36,11382.28
483,10821.36,11382.28
484,10821.36,11382.28
485,10821.36,11382.28
486,10821.36,11382.28
487,10821.36,11382.28
488,10821.36,11382.28
489,10821.36,11382.28
490,10821.36,11382.28
491,10821.36,11382.28
492,10821.36,11382.28
493,10821.36,11382.28
494,10821.36,11382.28
495,10821.36,11394.87
496,10821.36,11394.87
497,10821.36,11394.87
498,10821.36,11394.87
499,10821.36,11394.87
500,10821.36,11394.87
501,10821.36,11394.87
502,10821.36,11394.87
503,10821.36,11394.87
504,10821.36,11394.87
505,10821.36,11394.87
506,10821.36,11394.87
507,10821.36,11394.87
508,10821.36,11394.87
509,10821.36,11394.87
510,10821.36,11394.87
511,10821.36,11394.87
512,10821.36,11394.87
513,10821.36,11394.87
514,10821.36,11394.87
515,10850.97,11394.87
516,10850.97,11394.87
517,10850.97,11394.87
518,10850.97,11394.87
519,10850.97,11394.87
520,10850.97,11394.87
521,10850.97,11394.87
522,10850.97,11394.87
523,10850.97,11394.87
524,10850.97,11394.87
525,10850.97,11394.87
526,10850.97,11415.14
527,10850.97,11415.14
528,10850.97,11415.14
529,10850.97,11415.14
530,10850.97,11415.14
531,10850.97,11415.14
532,10850.97,11415.14
533,10850.97,11415.14
534,10850.97,11415.14
535,10850.97,11415.14
536,10850.97,11415.14
537,10850.97,11415.14
538,10850.97,11415.14
539,10850.97,11415.14
540,10850.97,11415.14
541,10850.97,11415.14
542,10850.97,11415.14
543,10850.97,11415.14
544,10882.11,11415.14
545,10882.11,11415.14
546,10882.11,11415.14
547,10882.11,11415.14
548,10882.11,11415.14
549,10882.11,11415.14
550,10882.11,11415.14
551,10882.11,11415.14
552,10882.11,11415.14
553,10882.11,11415.14
554,10882.11,11415.14
555,10882.11,11415.14
556,10882.11,11430.60
557,10882.11,11430.60
558,10882.11,11430.60
559,10882.11,11430.60
560,10882.11,11430.60
561,10882.11,11430.60
562,10882.11,11430.60
563,10882.11,11430.60
564,10882.11,11430.60
565,10882.11,11430.60
566,10882.11,11430.60
567,10882.11,11430.60
568,10882.11,11430.60
569,10882.11,11430.60
570,10882.11,11430.60
571,10882.11,11430.60
572,10882.11,11430.60
573,10882.11,11430.60
574,10906.45,11430.60
575,10906.45,11440.47
576,10906.45,11440.47
577,10906.45,11440.47
578,10906.45,11440.47
579,10906.45,11440.47
580,10906.45,11440.47
581,10906.45,11440.47
582,10906.45,11440.47
583,10906.45,11440.47
584,10906.45,11440.47
585,10906.45,11440.47
586,10906.45,11440.47
587,10906.45,11440.47
588,10906.45,11440.47
589,10906.45,11440.47
590,10906.45,11440.47
591,10906.45,11440.47
592,10906.45,11440.47
593,10906.45,11440.47
594,10906.45,11440.47
595,10906.45,11440.47
596,10906.45,11440.47
597,10906.45,11440.47
598,10906.45,11440.47
599,10906.45,11440.47
600,10906.45,11440.47
601,10906.45,11440.47
602,10906.45,11440.47
603,10906.45,11440.47
604,10906.45,11440.47
605,10934.06,11456.97
606,10934.06,11456.97
607,10934.06,11456.97
608,10934.06,11456.97
609,10934.06,11456.97
610,10934.06,11456.97
611,10934.06,11456.97
612,10934.06,11456.97
613,10934.06,11456.97
614,10934.06,11456.97
615,10934.06,11456.97
616,10934.06,11456.97
617,10934.06,11456.97
618,10934.06,11456.97
619,10934.06,11456.97
620,10934.06,11456.97
621,10934.06,11456.97
622,10934.06,11456.97
623,10934.06,11456.97
624,10934.06,11456.97
625,10934.06,11456.97
626,10934.06,11456.97
627,10934.06,11456.97
628,10934.06,11456.97
629,10934.06,11456.97
630,10934.06,11456.97
631,10934.06,11456.97
632,10934.06,11456.97
633,10934.06,11456.97
634,10934.06,11456.97
635,10934.06,11456.97
636,10934.06,11456.97
637,10934.06,11456.97
638,10934.06,11456.97
639,10934.06,11456.97
640,10934.06,11456.97
641,10934.06,11456.97
642,10966.72,11456.97
643,10966.72,11456.97
644,10966.72,11475.00
645,10966.72,11475.00
646,10966.72,11475.00
647,10966.72,11475.00
648,10966.72,11475.00
649,10966.72,11475.00
650,10966.72,11475.00
651,10966.72,11475.00
652,10966.72,11475.00
653,10966.72,11475.00
654,10966.72,11475.00
655,10966.72,11475.00
656,10966.72,11475.00
657,10966.72,11475.00
658,10966.72,11475.00
659,10966.72,11475.00
660,10966.72,11475.00
661,10982.47,11475.00
662,10982.47,11475.00
663,10982.47,11475.00
664,10982.47,11475.00
665,10982.47,11475.00
666,10982.47,11475.00
667,10982.47,11475.00
668,10982.47,11475.00
669,10982.47,11475.00
670,10982.47,11475.00
671,10982.47,11475.00
672,10982.47,11475.00
673,10982.47,11475.00
674,10982.47,11490.95
675,10982.47,11490.95
676,10982.47,11490.95
677,10982.47,11490.95
678,10982.47,11490.95
679,10982.47,11490.95
680,10982.47,11490.95
681,10982.47,11490.95
682,10982.47,11490.95
683,10982.47,11490.95
684,10982.47,11490.95
685,10982.47,11490.95
686,10982.47,11490.95
687,10982.47,11490.95
688,10982.47,11490.95
689,10982.47,11490.95
690,10982.47,11490.95
691,10982.47,11490.95
692,10982.47,11490.95
693,11005.74,11490.95
694,11005.74,11490.95
695,11005.74,11490.95
696,11005.74,11490.95
697,11005.74,11490.95
698,11005.74,11490.95
699,11005.74,11490.95
700,11005.74,11490.95
701,11005.74,11490.95
702,11005.74,11490.95
703,11005.74,11490.95
704,11005.74,11490.95
705,11005.74,11490.95
706,11005.74,11506.93
707,11005.74,11506.93
708,11005.74,11506.93
709,11005.74,11506.93
710,11005.74,11506.93
711,11005.74,11506.93
712,11005.74,11506.93
713,11005.74,11506.93
714,11005.74,11506.93
715,11005.74,11506.93
716,11005.74,11506.93
717,11005.74,11506.93
718,11005.74,11506.93
719,11005.74,11506.93
720,11005.74,11506.93
721,11005.74,11506.93
722,11005.74,11506.93
723,11005.74,11506.93
724,11005.74,11506.93
725,11005.74,11506.93
726,11005.74,11506.93
727,11005.74,11506.93
728,11005.74,11506.93
729,11005.74,11506.93
730,11035.78,11506.93
731,11035.78,11518.07
732,11035.78,11518.07
733,11035.78,11518.07
734,11035.78,11518.07
735,11035.78,11518.07
736,11035.78,11518.07
737,11035.78,11518.07
738,11035.78,11518.07
739,11035.78,11518.07
740,11035.78,11518.07
741,11035.78,11518.07
742,11035.78,11518.07
743,11035.78,11518.07
744,11035.78,11518.07
745,11035.78,11518.07
746,11035.78,11518.07
747,11048.96,11518.07
748,11048.96,11518.07
749,11048.96,11518.07
750,11048.96,11518.07
751,11048.96,11518.07
752,11048.96,11518.07
753,11048.96,11518.07
754,11048.96,11518.07
755,11048.96,11518.07
756,11048.96,11518.07
757,11048.96,11518.07
758,11048.96,11518.07
759,11048.96,11518.07
760,11048.96,11518.07
761,11048.96,11518.07
762,11048.96,11518.07
763,11048.96,11537.40
764,11048.96,11537.40
765,11048.96,11537.40
766,11048.96,11537.40
767,11048.96,11537.40
768,11048.96,11537.40
769,11048.96,11537.40
770,11048.96,11537.40
771,11048.96,11537.40
772,11048.96,11537.40
773,11048.96,11537.40
774,11048.96,11537.40
775,11048.96,11537.40
776,11048.96,11537.40
777,11048.96,11537.40
778,11048.96,11537.40
779,11048.96,11537.40
780,11048.96,11537.40
781,11048.96,11537.40
782,11048.96,11537.40
783,11048.96,11537.40
784,11074.79,11537.40
785,11074.79,11537.40
786,11074.79,11537.40
787,11074.79,11537.40
788,11074.79,11537.40
789,11074.79,11537.40
790,11074.79,11537.40
791,11074.79,11537.40
792,11074.79,11537.40
793,11074.79,11537.40
794,11074.79,11553.50
795,11074.79,11553.50
796,11074.79,11553.50
797,11074.79,11553.50
798,11074.79,11553.50
799,11074.79,11553.50
800,11074.79,11553.50
801,11074.79,11553.50
802,11074.79,11553.50
803,11074.79,11553.50
804,11074.79,11553.50
805,11074.79,11553.50
806,11074.79,11553.50
807,11074.79,11553.50
808,11074.79,11553.50
809,11074.79,11553.50
810,11074.79,11553.50
811,11074.79,11553.50
812,11074.79,11553.50
813,11074.79,11553.50
814,11074.79,11553.50
815,11074.79,11553.50
816,11074.79,11553.50
817,11074.79,11553.50
818,11074.79,11553.50
819,11074.79,11553.50
820,11074.79,11553.50
821,11103.39,11553.50
822,11103.39,11553.50
823,11103.39,11553.50
824,11103.39,11553.50
825,11103.39,11566.62
826,11103.39,11566.62
827,11103.39,11566.62
828,11103.39,11566.62
829,11103.39,11566.62
830,11103.39,11566.62
831,11103.39,11566.62
832,11103.39,11566.62
833,11103.39,11566.62
834,11103.39,11566.62
835,11103.39,11566.62
836,11103.39,11566.62
837,11103.39,11566.62
838,11103.39,11566.62
839,11103.39,11566.62
840,11103.39,11566.62
841,11118.32,11566.62
842,11118.32,11566.62
843,11118.32,11566.62
844,11118.32,11566.62
845,11118.32,11566.62
846,11118.32,11566.62
847,11118.32,11566.62
848,11118.32,11566.62
849,11118.32,11566.62
850,11118.32,11566.62
851,11118.32,11566.62
852,11118.32,11566.62
853,11118.32,11566.62
854,11118.32,11566.62
855,11118.32,11566.62
856,11118.32,11566.62
857,11118.32,11583.29
858,11118.32,11583.29
859,11118.32,11583.29
860,11118.32,11583.29
861,11118.32,11583.29
862,11118.32,11583.29
863,11118.32,11583.29
864,11118.32,11583.29
865,11118.32,11583.29
866,11118.32,11583.29
867,11118.32,11583.29
868,11118.32,11583.29
869,11118.32,11583.29
870,11118.32,11583.29
871,11118.32,11583.29
872,11118.32,11583.29
873,11118.32,11583.29
874,11118.32,11583.29
875,11118.32,11583.29
876,11118.32,11583.29
877,11118.32,11583.29
878,11143.84,11583.29
879,11143.84,11583.29
880,11143.84,11583.29
881,11143.84,11583.29
882,11143.84,11583.29
883,11143.84,11595.11
884,11143.84,11595.11
885,11143.84,11595.11
886,11143.84,11595.11
887,11143.84,11595.11
888,11143.84,11595.11
889,11143.84,11595.11
890,11143.84,11595.11
891,11143.84,11595.11
892,11143.84,11595.11
893,11143.84,11595.11
894,11143.84,11595.11
895,11143.84,11595.11
896,11143.84,11595.11
897,11143.84,11595.11
898,11143.84,11595.11
899,11143.84,11595.11
900,11143.84,11595.11
901,11143.84,11595.11
902,11143.84,11595.11
903,11143.84,11595.11
904,11143.84,11595.11
905,11143.84,11595.11
906,11143.84,11595.11
907,11143.84,11595.11
908,11143.84,11595.11
909,11143.84,11608.00
910,11143.84,11608.00

In [17]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head()

,phase,code,configuration,experiment_run,client,type_tenants,num_tenants,vol_tenants
phase,,,,,,,,
1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-1,1776678767,PostgreSQL-64-8-65536,1,1,None,0,False
1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767,PostgreSQL-64-8-65536,1,2,None,0,False

# Time Series of a Single Metric for All Experiments

In [18]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_all(metric=metric)
df.head()

,timestamp,code,phase,experiment_run,client,type_tenants,vol_tenants,num_tenants,metric,component,value
0,0,1776678767,1776678767-PostgreSQL-64-8-65536-1,1,1,None,False,0,total_cpu_memory,stream,9579.14
1,0,1776678767,1776678767-PostgreSQL-64-8-65536-2,1,2,None,False,0,total_cpu_memory,stream,82802.53
2,0,1776682364,1776682364-PostgreSQL-64-8-65536-1,1,1,None,False,0,total_cpu_memory,stream,9506.29
3,0,1776682364,1776682364-PostgreSQL-64-8-65536-2,1,2,None,False,0,total_cpu_memory,stream,82789.47
4,1,1776678767,1776678767-PostgreSQL-64-8-65536-1,1,1,None,False,0,total_cpu_memory,stream,9579.14

In [19]:
df[['timestamp', 'phase', 'value']].head(8)

   timestamp                               phase    value
0          0  1776678767-PostgreSQL-64-8-65536-1  9579.14
1          0  1776678767-PostgreSQL-64-8-65536-2 82802.53
2          0  1776682364-PostgreSQL-64-8-65536-1  9506.29
3          0  1776682364-PostgreSQL-64-8-65536-2 82789.47
4          1  1776678767-PostgreSQL-64-8-65536-1  9579.14
5          1  1776678767-PostgreSQL-64-8-65536-2 82802.53
6          1  1776682364-PostgreSQL-64-8-65536-1  9506.33
7          1  1776682364-PostgreSQL-64-8-65536-2 82789.47

In [20]:
df=collect.add_metadata(df)
df = df.sort_values(['timestamp', 'phase'])
df[['timestamp', 'phase', 'value']].head(8)

combine on columns phase

,timestamp,phase,value
1776678767-PostgreSQL-64-8-65536-1,0,1776678767-PostgreSQL-64-8-65536-1,9579.14
1776678767-PostgreSQL-64-8-65536-2,0,1776678767-PostgreSQL-64-8-65536-2,82802.53
1776682364-PostgreSQL-64-8-65536-1,0,1776682364-PostgreSQL-64-8-65536-1,9506.29
1776682364-PostgreSQL-64-8-65536-2,0,1776682364-PostgreSQL-64-8-65536-2,82789.47
1776678767-PostgreSQL-64-8-65536-1,1,1776678767-PostgreSQL-64-8-65536-1,9579.14
1776678767-PostgreSQL-64-8-65536-2,1,1776678767-PostgreSQL-64-8-65536-2,82802.53
1776682364-PostgreSQL-64-8-65536-1,1,1776682364-PostgreSQL-64-8-65536-1,9506.33
1776682364-PostgreSQL-64-8-65536-2,1,1776682364-PostgreSQL-64-8-65536-2,82789.47

In [21]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head()

,phase,code,configuration,experiment_run,client,type_tenants,num_tenants,vol_tenants
1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-1,1776678767,PostgreSQL-64-8-65536,1,1,None,0,False
1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767,PostgreSQL-64-8-65536,1,2,None,0,False
1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-1,1776682364,PostgreSQL-64-8-65536,1,1,None,0,False
1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364,PostgreSQL-64-8-65536,1,2,None,0,False
1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-1,1776678767,PostgreSQL-64-8-65536,1,1,None,0,False

## Custom Aggregation and Scale

In [22]:
metric = 'total_cpu_util'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["code", "experiment_run", "client", "type_tenants", "num_tenants"])["value"]
      .max()
      .reset_index()
)
#plot_bars(df_agg, y='value', title='Max CPU Utilization [%]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)
df_agg.index.name = 'Max ' + collect.df_metrics.loc[metric]['title']
df_agg

,code,experiment_run,client,type_tenants,num_tenants,value
Max CPU Utilization,,,,,,
0,1776678767,1,1,None,0,1.26
1,1776678767,1,2,None,0,7.53
2,1776682364,1,1,None,0,1.36
3,1776682364,1,2,None,0,7.56

# Performance Results per Connection

In [23]:
df_performance = collect.get_performance_per_connection()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

connection_pod,1776678767-PostgreSQL-64-8-65536-1-1-1,1776678767-PostgreSQL-64-8-65536-2-4-1,1776678767-PostgreSQL-64-8-65536-2-2-1,1776678767-PostgreSQL-64-8-65536-2-8-1,1776678767-PostgreSQL-64-8-65536-2-1-1,1776678767-PostgreSQL-64-8-65536-2-7-1,1776678767-PostgreSQL-64-8-65536-2-5-1,1776678767-PostgreSQL-64-8-65536-2-6-1,1776678767-PostgreSQL-64-8-65536-2-3-1,1776682364-PostgreSQL-64-8-65536-1-1-1,1776682364-PostgreSQL-64-8-65536-2-5-1,1776682364-PostgreSQL-64-8-65536-2-8-1,1776682364-PostgreSQL-64-8-65536-2-1-1,1776682364-PostgreSQL-64-8-65536-2-3-1,1776682364-PostgreSQL-64-8-65536-2-7-1,1776682364-PostgreSQL-64-8-65536-2-6-1,1776682364-PostgreSQL-64-8-65536-2-2-1,1776682364-PostgreSQL-64-8-65536-2-4-1
code,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364
phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2
connection,1776678767-PostgreSQL-64-8-65536-1-1,1776678767-PostgreSQL-64-8-65536-2-4,1776678767-PostgreSQL-64-8-65536-2-2,1776678767-PostgreSQL-64-8-65536-2-8,1776678767-PostgreSQL-64-8-65536-2-1,1776678767-PostgreSQL-64-8-65536-2-7,1776678767-PostgreSQL-64-8-65536-2-5,1776678767-PostgreSQL-64-8-65536-2-6,1776678767-PostgreSQL-64-8-65536-2-3,1776682364-PostgreSQL-64-8-65536-1-1,1776682364-PostgreSQL-64-8-65536-2-5,1776682364-PostgreSQL-64-8-65536-2-8,1776682364-PostgreSQL-64-8-65536-2-1,1776682364-PostgreSQL-64-8-65536-2-3,1776682364-PostgreSQL-64-8-65536-2-7,1776682364-PostgreSQL-64-8-65536-2-6,1776682364-PostgreSQL-64-8-65536-2-2,1776682364-PostgreSQL-64-8-65536-2-4
configuration,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536
experiment_run,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
client,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2
pod,g7bjq.dbmsbenchmarker,qf4pk.dbmsbenchmarker,khrjg.dbmsbenchmarker,tn66p.dbmsbenchmarker,rjcxw.dbmsbenchmarker,pr5fr.dbmsbenchmarker,97hvx.dbmsbenchmarker,944k6.dbmsbenchmarker,t9mf8.dbmsbenchmarker,jqtfk.dbmsbenchmarker,66kwz.dbmsbenchmarker,vmhc7.dbmsbenchmarker,8q8zp.dbmsbenchmarker,pctgl.dbmsbenchmarker,tp8ct.dbmsbenchmarker,kc9n2.dbmsbenchmarker,fzkn7.dbmsbenchmarker,w4cn7.dbmsbenchmarker
pod_count,1,8,8,8,8,8,8,8,8,1,8,8,8,8,8,8,8,8
threads,64,8,8,8,8,8,8,8,8,64,8,8,8,8,8,8,8,8
target,32768,4096,4096,4096,4096,4096,4096,4096,4096,49152,6144,6144,6144,6144,6144,6144,6144,6144
sf,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
workload,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
operations,3000000,375000,375000,375000,375000,375000,375000,375000,375000,3000000,375000,375000,375000,375000,375000,375000,375000,375000
batchsize,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
exceptions,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
child,1,4,2,8,1,7,5,6,3,1,5,8,1,3,7,6,2,4
[OVERALL].RunTime(ms),1069952,1038833,1052642,1048170,1046264,1045798,1041416,1049947,1046079,1052107,1038787,1047871,1047093,1050100,1042666,1034069,1055137,1043813
[OVERALL].Throughput(ops/sec),2803.8640985763845,360.9819865175635,356.2464731599157,357.76639285612066,358.418143030822,358.5778515545067,360.08665125175725,357.1608852637324,358.481529597669,2851.4210056581696,360.9979716727298,357.86847808556587,358.13437774868135,357.1088467764975,359.6549614162157,362.6450459302039,355.4040849671654,359.2597524652404
[TOTAL_GCS_Copy].Count,102,13,13,13,13,13,13,13,13,101,13,13,13,13,13,13,13,13
[TOTAL_GC_TIME_Copy].Time(ms),391,40,36,44,37,41,40,41,41,293,41,38,43,43,36,40,39,40
[TOTAL_GC_TIME_%_Copy].Time(%),0.03654369541811221,0.00385047452285401,0.003419966142335191,0.004197792342845149,0.0035363923445707775,0.00392045117699594,0.0038409242800187438,0.003904959012216807,0.0039193980569345145,0.027848878488594794,0.003946911156955179,0.003626400577933734,0.004106607531518213,0.004094848109703838,0.003452687629595671,0.003868213823255508,0.0036962024836585203,0.0038321040262958976
[TOTAL_GCS_MarkSweepCompact].Count,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
[TOTAL_GC_TIME_MarkSweepCompact].Time(ms),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
[TOTAL_GC_TIME_%_MarkSweepCompact].Time(%),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
[TOTAL_GCs].Count,102,13,13,13,13,13,13,13,13,101,13,13,13,13,13,13,13,13
[TOTAL_GC_TIME].Time(ms),391,40,36,44,37,41,40,41,41,293,41,38,43,43,36,40,39,40
[TOTAL_GC_TIME_%].Time(%),0.03654369541811221,0.00385047452285401,0.003419966142335191,0.004197792342845149,0.0035363923445707775,0.00392045117699594,0.0038409242800187438,0.003904959012216807,0.0039193980569345145,0.027848878488594794,0.003946911156955179,0.003626400577933734,0.004106607531518213,0.004094848109703838,0.003452687629595671,0.003868213823255508,0.0036962024836585203,0.0038321040262958976
[READ].Operations,1499615,187381,187071,187633,186711,187097,187242,187728,188057,1500841,187458,187944,187503,188207,187364,187409,187292,187019
[READ].AverageLatency(us),368.78382518179666,359.44760674774926,360.61057031822145,361.2789967649614,358.4562130779654,361.3536775041823,358.4056995759498,360.15843667433734,356.60390200843364,373.2462945775069,366.52769153623746,360.345124079513,361.02484760243834,362.61142252944893,362.86724771033926,362.47010015527536,357.98650769920766,363.74658189809594
[READ].MinLatency(us),156,159,162,156,157,157,159,156,159,157,160,157,158,158,162,160,155,160
[READ].MaxLatency(us),43295,27791,26751,27391,29103,27439,25631,28351,26799,36287,27663,26079,26799,27647,26591,27727,27711,27599
[READ].95thPercentileLatency(us),609,573,573,586,575,583,569,579,573,626,602,583,582,589,588,588,574,592
[READ].99thPercentileLatency(us),810,721,723,734,724,734,719,726,726,871,764,737,743,751,752,752,729,756
[READ].Return=OK,1499615,187381,187071,187633,186711,187097,187242,187728,188057,1500841,187458,187944,187503,188207,187364,187409,187292,187019
[CLEANUP].Operations,64,8,8,8,8,8,8,8,8,64,8,8,8,8,8,8,8,8
[CLEANUP].AverageLatency(us),185.9375,286.375,284.5,247.875,272.125,287.375,241.25,261.0,327.25,181.234375,264.75,237.875,288.25,227.125,250.875,284.0,279.5,332.5
[CLEANUP].MinLatency(us),97,149,146,144,138,155,131,139,153,102,131,130,135,127,127,134,155,119
[CLEANUP].MaxLatency(us),737,940,972,681,741,933,870,735,1308,734,887,810,1105,656,711,1129,938,1317
[CLEANUP].95thPercentileLatency(us),261,940,972,681,741,933,870,735,1308,238,887,810,1105,656,711,1129,938,1317
[CLEANUP].99thPercentileLatency(us),276,940,972,681,741,933,870,735,1308,343,887,810,1105,656,711,1129,938,1317
[UPDATE].Operations,1500385,187619,187929,187367,188289,187903,187758,187272,186943,1499159,187542,187056,187497,186793,187636,187591,187708,187981
[UPDATE].AverageLatency(us),44013.8379855837,43310.39972497455,43729.70502689845,43062.18044799778,43132.65398403518,43381.48509603359,43501.54095165053,43223.93366867444,43433.01357098153,43306.37344404429,43314.7201373559,43852.22058634847,43622.612020459,43436.792021114285,43495.31808394977,43339.60638836618,43480.91882072155,43325.18848181465
[UPDATE].MinLatency(us),6204,7964,5944,8200,8188,8180,7748,8172,8224,6940,8256,7380,8032,7972,8224,8144,5032,8224
[UPDATE].MaxLatency(us),8413183,4919295,6770687,6275071,7708671,6115327,7110655,6418431,7794687,7602175,7299071,6844415,6946815,7139327,6033407,6303743,6119423,5226495
[UPDATE].95thPercentileLatency(us),50175,50079,50079,50047,50079,50047,50079,50079,50079,50143,50047,50047,50047,50047,50047,50079,50015,50047
[UPDATE].99thPercentileLatency(us),900095,886271,918527,869887,878591,902143,895999,869887,904191,887295,895487,919039,895487,912383,894975,895487,903679,887295
[UPDATE].Return=OK,1500385,187619,187929,187367,188289,187903,187758,187272,186943,1499159,187542,187056,187497,186793,187636,187591,187708,187981

### Add Metadata

In [24]:
df = collect.add_metadata(df_performance)
df.T

combine on columns phase

connection_pod,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2
code,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364
phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2
connection,1776678767-PostgreSQL-64-8-65536-1-1,1776678767-PostgreSQL-64-8-65536-2-4,1776678767-PostgreSQL-64-8-65536-2-2,1776678767-PostgreSQL-64-8-65536-2-8,1776678767-PostgreSQL-64-8-65536-2-1,1776678767-PostgreSQL-64-8-65536-2-7,1776678767-PostgreSQL-64-8-65536-2-5,1776678767-PostgreSQL-64-8-65536-2-6,1776678767-PostgreSQL-64-8-65536-2-3,1776682364-PostgreSQL-64-8-65536-1-1,1776682364-PostgreSQL-64-8-65536-2-5,1776682364-PostgreSQL-64-8-65536-2-8,1776682364-PostgreSQL-64-8-65536-2-1,1776682364-PostgreSQL-64-8-65536-2-3,1776682364-PostgreSQL-64-8-65536-2-7,1776682364-PostgreSQL-64-8-65536-2-6,1776682364-PostgreSQL-64-8-65536-2-2,1776682364-PostgreSQL-64-8-65536-2-4
configuration,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536
experiment_run,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
client,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2
pod,g7bjq.dbmsbenchmarker,qf4pk.dbmsbenchmarker,khrjg.dbmsbenchmarker,tn66p.dbmsbenchmarker,rjcxw.dbmsbenchmarker,pr5fr.dbmsbenchmarker,97hvx.dbmsbenchmarker,944k6.dbmsbenchmarker,t9mf8.dbmsbenchmarker,jqtfk.dbmsbenchmarker,66kwz.dbmsbenchmarker,vmhc7.dbmsbenchmarker,8q8zp.dbmsbenchmarker,pctgl.dbmsbenchmarker,tp8ct.dbmsbenchmarker,kc9n2.dbmsbenchmarker,fzkn7.dbmsbenchmarker,w4cn7.dbmsbenchmarker
pod_count,1,8,8,8,8,8,8,8,8,1,8,8,8,8,8,8,8,8
threads,64,8,8,8,8,8,8,8,8,64,8,8,8,8,8,8,8,8
target,32768,4096,4096,4096,4096,4096,4096,4096,4096,49152,6144,6144,6144,6144,6144,6144,6144,6144
sf,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
workload,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
operations,3000000,375000,375000,375000,375000,375000,375000,375000,375000,3000000,375000,375000,375000,375000,375000,375000,375000,375000
batchsize,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
exceptions,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
child,1,4,2,8,1,7,5,6,3,1,5,8,1,3,7,6,2,4
[OVERALL].RunTime(ms),1069952,1038833,1052642,1048170,1046264,1045798,1041416,1049947,1046079,1052107,1038787,1047871,1047093,1050100,1042666,1034069,1055137,1043813
[OVERALL].Throughput(ops/sec),2803.8640985763845,360.9819865175635,356.2464731599157,357.76639285612066,358.418143030822,358.5778515545067,360.08665125175725,357.1608852637324,358.481529597669,2851.4210056581696,360.9979716727298,357.86847808556587,358.13437774868135,357.1088467764975,359.6549614162157,362.6450459302039,355.4040849671654,359.2597524652404
[TOTAL_GCS_Copy].Count,102,13,13,13,13,13,13,13,13,101,13,13,13,13,13,13,13,13
[TOTAL_GC_TIME_Copy].Time(ms),391,40,36,44,37,41,40,41,41,293,41,38,43,43,36,40,39,40
[TOTAL_GC_TIME_%_Copy].Time(%),0.03654369541811221,0.00385047452285401,0.003419966142335191,0.004197792342845149,0.0035363923445707775,0.00392045117699594,0.0038409242800187438,0.003904959012216807,0.0039193980569345145,0.027848878488594794,0.003946911156955179,0.003626400577933734,0.004106607531518213,0.004094848109703838,0.003452687629595671,0.003868213823255508,0.0036962024836585203,0.0038321040262958976
[TOTAL_GCS_MarkSweepCompact].Count,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
[TOTAL_GC_TIME_MarkSweepCompact].Time(ms),0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
[TOTAL_GC_TIME_%_MarkSweepCompact].Time(%),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
[TOTAL_GCs].Count,102,13,13,13,13,13,13,13,13,101,13,13,13,13,13,13,13,13
[TOTAL_GC_TIME].Time(ms),391,40,36,44,37,41,40,41,41,293,41,38,43,43,36,40,39,40
[TOTAL_GC_TIME_%].Time(%),0.03654369541811221,0.00385047452285401,0.003419966142335191,0.004197792342845149,0.0035363923445707775,0.00392045117699594,0.0038409242800187438,0.003904959012216807,0.0039193980569345145,0.027848878488594794,0.003946911156955179,0.003626400577933734,0.004106607531518213,0.004094848109703838,0.003452687629595671,0.003868213823255508,0.0036962024836585203,0.0038321040262958976
[READ].Operations,1499615,187381,187071,187633,186711,187097,187242,187728,188057,1500841,187458,187944,187503,188207,187364,187409,187292,187019
[READ].AverageLatency(us),368.78382518179666,359.44760674774926,360.61057031822145,361.2789967649614,358.4562130779654,361.3536775041823,358.4056995759498,360.15843667433734,356.60390200843364,373.2462945775069,366.52769153623746,360.345124079513,361.02484760243834,362.61142252944893,362.86724771033926,362.47010015527536,357.98650769920766,363.74658189809594
[READ].MinLatency(us),156,159,162,156,157,157,159,156,159,157,160,157,158,158,162,160,155,160
[READ].MaxLatency(us),43295,27791,26751,27391,29103,27439,25631,28351,26799,36287,27663,26079,26799,27647,26591,27727,27711,27599
[READ].95thPercentileLatency(us),609,573,573,586,575,583,569,579,573,626,602,583,582,589,588,588,574,592
[READ].99thPercentileLatency(us),810,721,723,734,724,734,719,726,726,871,764,737,743,751,752,752,729,756
[READ].Return=OK,1499615,187381,187071,187633,186711,187097,187242,187728,188057,1500841,187458,187944,187503,188207,187364,187409,187292,187019
[CLEANUP].Operations,64,8,8,8,8,8,8,8,8,64,8,8,8,8,8,8,8,8
[CLEANUP].AverageLatency(us),185.9375,286.375,284.5,247.875,272.125,287.375,241.25,261.0,327.25,181.234375,264.75,237.875,288.25,227.125,250.875,284.0,279.5,332.5
[CLEANUP].MinLatency(us),97,149,146,144,138,155,131,139,153,102,131,130,135,127,127,134,155,119
[CLEANUP].MaxLatency(us),737,940,972,681,741,933,870,735,1308,734,887,810,1105,656,711,1129,938,1317
[CLEANUP].95thPercentileLatency(us),261,940,972,681,741,933,870,735,1308,238,887,810,1105,656,711,1129,938,1317
[CLEANUP].99thPercentileLatency(us),276,940,972,681,741,933,870,735,1308,343,887,810,1105,656,711,1129,938,1317
[UPDATE].Operations,1500385,187619,187929,187367,188289,187903,187758,187272,186943,1499159,187542,187056,187497,186793,187636,187591,187708,187981
[UPDATE].AverageLatency(us),44013.8379855837,43310.39972497455,43729.70502689845,43062.18044799778,43132.65398403518,43381.48509603359,43501.54095165053,43223.93366867444,43433.01357098153,43306.37344404429,43314.7201373559,43852.22058634847,43622.612020459,43436.792021114285,43495.31808394977,43339.60638836618,43480.91882072155,43325.18848181465
[UPDATE].MinLatency(us),6204,7964,5944,8200,8188,8180,7748,8172,8224,6940,8256,7380,8032,7972,8224,8144,5032,8224
[UPDATE].MaxLatency(us),8413183,4919295,6770687,6275071,7708671,6115327,7110655,6418431,7794687,7602175,7299071,6844415,6946815,7139327,6033407,6303743,6119423,5226495
[UPDATE].95thPercentileLatency(us),50175,50079,50079,50047,50079,50047,50079,50079,50079,50143,50047,50047,50047,50047,50047,50079,50015,50047
[UPDATE].99thPercentileLatency(us),900095,886271,918527,869887,878591,902143,895999,869887,904191,887295,895487,919039,895487,912383,894975,895487,903679,887295
[UPDATE].Return=OK,1500385,187619,187929,187367,188289,187903,187758,187272,186943,1499159,187542,187056,187497,186793,187636,187591,187708,187981
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00
time_ingest,886.00,886.00,886.00,886.00,886.00,886.00,886.00,886.00,886.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00
time_check,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,8,8,8,8,8,8,8,8,1,8,8,8,8,8,8,8,8
tenant,,,,,,,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,7091,8548,8548,8548,8548,8548,8548,8548,8548,7091,8546,8546,8546,8546,8546,8546,8546,8546
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,,,,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,158125,159582,159582,159582,159582,159582,159582,159582,159582,158125,159581,159581,159581,159581,159581,159581,159581,159581
host_datadisk,7091,8548,8548,8548,8548,8548,8548,8548,8548,7091,8546,8546,8546,8546,8546,8546,8546,8546
host_volume_size,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_YCSB_THREADCOUNT,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_YCSB_TARGET,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192
loading_parameters_YCSB_STATUS,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_YCSB_WORKLOAD,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
loading_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000
loading_parameters_YCSB_OPERATIONS,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000
loading_parameters_YCSB_BATCHSIZE,,,,,,,,,,,,,,,,,,
loading_parameters_YCSB_STATUS_INTERVAL,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
loading_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc
loading_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
loading_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed
benchmarking_parameters_PARALLEL,1,8,8,8,8,8,8,8,8,1,8,8,8,8,8,8,8,8
benchmarking_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
benchmarking_parameters_YCSB_THREADCOUNT,64,8,8,8,8,8,8,8,8,64,8,8,8,8,8,8,8,8
benchmarking_parameters_YCSB_TARGET,32768,4096,4096,4096,4096,4096,4096,4096,4096,49152,6144,6144,6144,6144,6144,6144,6144,6144
benchmarking_parameters_YCSB_STATUS,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
benchmarking_parameters_YCSB_WORKLOAD,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
benchmarking_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000
benchmarking_parameters_YCSB_OPERATIONS,3000000,375000,375000,375000,375000,375000,375000,375000,375000,3000000,375000,375000,375000,375000,375000,375000,375000,375000
benchmarking_parameters_YCSB_BATCHSIZE,,,,,,,,,,,,,,,,,,
benchmarking_parameters_YCSB_STATUS_INTERVAL,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
benchmarking_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc
benchmarking_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
benchmarking_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Performance Results per Total

In [25]:
df_performance = collect.get_performance_aggregated_per_phase()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)

In [26]:
df_performance.T

,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2
phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2
configuration,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536
experiment_run,1,1,1,1
code,1776678767,1776678767,1776682364,1776682364
client,1,2,1,2
pod_count,1,8,1,8
threads,64,64,64,64
target,32768,32768,49152,49152
sf,3,3,3,3
workload,a,a,a,a
operations,3000000,3000000,3000000,3000000
exceptions,0,0,0,0
[OVERALL].RunTime(ms),1069952.00,1052642.00,1052107.00,1055137.00
[OVERALL].Throughput(ops/sec),2803.86,2867.72,2851.42,2871.07
[CLEANUP].Operations,64,64,64,64
[CLEANUP].AverageLatency(us),185.94,275.97,181.23,270.61
[CLEANUP].MinLatency(us),97.00,131.00,102.00,119.00
[CLEANUP].MaxLatency(us),737.00,1308.00,734.00,1317.00
[CLEANUP].95thPercentileLatency(us),261.00,1308.00,238.00,1317.00
[CLEANUP].99thPercentileLatency(us),276.00,1308.00,343.00,1317.00
[READ].Operations,1499615,1498920,1500841,1500196
[READ].AverageLatency(us),368.78,359.54,373.25,362.20
[READ].MinLatency(us),156.00,156.00,157.00,155.00
[READ].MaxLatency(us),43295.00,29103.00,36287.00,27727.00
[READ].95thPercentileLatency(us),609.00,586.00,626.00,602.00
[READ].99thPercentileLatency(us),810.00,734.00,871.00,764.00
[READ].Return=OK,1499615,1498920,1500841,1500196
[UPDATE].Operations,1500385,1501080,1499159,1499804
[UPDATE].AverageLatency(us),44013.84,43346.86,43306.37,43483.42
[UPDATE].MinLatency(us),6204.00,5944.00,6940.00,5032.00
[UPDATE].MaxLatency(us),8413183.00,7794687.00,7602175.00,7299071.00
[UPDATE].95thPercentileLatency(us),50175.00,50079.00,50143.00,50079.00
[UPDATE].99thPercentileLatency(us),900095.00,918527.00,887295.00,919039.00
[UPDATE].Return=OK,1500385,1501080,1499159,1499804

### With Metadata

In [27]:
df = collect.add_metadata(df_performance)
df.T

combine on index and column 'phase'

phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2
configuration,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536
experiment_run,1,1,1,1
code,1776678767,1776678767,1776682364,1776682364
client,1,2,1,2
pod_count,1,8,1,8
threads,64,64,64,64
target,32768,32768,49152,49152
sf,3,3,3,3
workload,a,a,a,a
operations,3000000,3000000,3000000,3000000
exceptions,0,0,0,0
[OVERALL].RunTime(ms),1069952.00,1052642.00,1052107.00,1055137.00
[OVERALL].Throughput(ops/sec),2803.86,2867.72,2851.42,2871.07
[CLEANUP].Operations,64,64,64,64
[CLEANUP].AverageLatency(us),185.94,275.97,181.23,270.61
[CLEANUP].MinLatency(us),97.00,131.00,102.00,119.00
[CLEANUP].MaxLatency(us),737.00,1308.00,734.00,1317.00
[CLEANUP].95thPercentileLatency(us),261.00,1308.00,238.00,1317.00
[CLEANUP].99thPercentileLatency(us),276.00,1308.00,343.00,1317.00
[READ].Operations,1499615,1498920,1500841,1500196
[READ].AverageLatency(us),368.78,359.54,373.25,362.20
[READ].MinLatency(us),156.00,156.00,157.00,155.00
[READ].MaxLatency(us),43295.00,29103.00,36287.00,27727.00
[READ].95thPercentileLatency(us),609.00,586.00,626.00,602.00
[READ].99thPercentileLatency(us),810.00,734.00,871.00,764.00
[READ].Return=OK,1499615,1498920,1500841,1500196
[UPDATE].Operations,1500385,1501080,1499159,1499804
[UPDATE].AverageLatency(us),44013.84,43346.86,43306.37,43483.42
[UPDATE].MinLatency(us),6204.00,5944.00,6940.00,5032.00
[UPDATE].MaxLatency(us),8413183.00,7794687.00,7602175.00,7299071.00
[UPDATE].95thPercentileLatency(us),50175.00,50079.00,50143.00,50079.00
[UPDATE].99thPercentileLatency(us),900095.00,918527.00,887295.00,919039.00
[UPDATE].Return=OK,1500385,1501080,1499159,1499804
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1927.00,1927.00,1992.00,1992.00
time_ingest,886.00,886.00,905.00,905.00
time_check,1040.00,1040.00,1086.00,1086.00
terminals,0,0,0,0
pods,1,8,1,8
tenant,,,,
num_worker,0,0,0,0
type_tenants,None,None,None,None
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,7091,8548,7091,8546
host_RAM,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,
host_Cores,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,158125,159582,158125,159581
host_datadisk,7091,8548,7091,8546
host_volume_size,0,0,0,0
host_volume_used,0,0,0,0
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0
host_limits_memory,0,0,0,0
loading_parameters_PARALLEL,8,8,8,8
loading_parameters_SF,3,3,3,3
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
loading_parameters_YCSB_THREADCOUNT,8,8,8,8
loading_parameters_YCSB_TARGET,8192,8192,8192,8192
loading_parameters_YCSB_STATUS,1,1,1,1
loading_parameters_YCSB_WORKLOAD,a,a,a,a
loading_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000
loading_parameters_YCSB_OPERATIONS,375000,375000,375000,375000
loading_parameters_YCSB_BATCHSIZE,,,,
loading_parameters_YCSB_STATUS_INTERVAL,10,10,10,10
loading_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc
loading_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
loading_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed
benchmarking_parameters_PARALLEL,1,8,1,8
benchmarking_parameters_SF,3,3,3,3
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
benchmarking_parameters_YCSB_THREADCOUNT,64,8,64,8
benchmarking_parameters_YCSB_TARGET,32768,4096,49152,6144
benchmarking_parameters_YCSB_STATUS,1,1,1,1
benchmarking_parameters_YCSB_WORKLOAD,a,a,a,a
benchmarking_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000
benchmarking_parameters_YCSB_OPERATIONS,3000000,375000,3000000,375000
benchmarking_parameters_YCSB_BATCHSIZE,,,,
benchmarking_parameters_YCSB_STATUS_INTERVAL,10,10,10,10
benchmarking_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc
benchmarking_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
benchmarking_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2

In [28]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']]

,phase,code,configuration,experiment_run,client,type_tenants,num_tenants,vol_tenants
phase,,,,,,,,
1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-1,1776678767,1776678767-PostgreSQL-64-8-65536,1,1,None,0,False
1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767,1776678767-PostgreSQL-64-8-65536,1,2,None,0,False
1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-1,1776682364,1776682364-PostgreSQL-64-8-65536,1,1,None,0,False
1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364,1776682364-PostgreSQL-64-8-65536,1,2,None,0,False

In [29]:
collectors.get_non_constant(df).T

phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2
configuration,1776678767-PostgreSQL-64-8-65536,1776678767-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536,1776682364-PostgreSQL-64-8-65536
code,1776678767,1776678767,1776682364,1776682364
client,1,2,1,2
pod_count,1,8,1,8
target,32768,32768,49152,49152
[OVERALL].RunTime(ms),1069952.00,1052642.00,1052107.00,1055137.00
[OVERALL].Throughput(ops/sec),2803.86,2867.72,2851.42,2871.07
[CLEANUP].AverageLatency(us),185.94,275.97,181.23,270.61
[CLEANUP].MinLatency(us),97.00,131.00,102.00,119.00
[CLEANUP].MaxLatency(us),737.00,1308.00,734.00,1317.00
[CLEANUP].95thPercentileLatency(us),261.00,1308.00,238.00,1317.00
[CLEANUP].99thPercentileLatency(us),276.00,1308.00,343.00,1317.00
[READ].Operations,1499615,1498920,1500841,1500196
[READ].AverageLatency(us),368.78,359.54,373.25,362.20
[READ].MinLatency(us),156.00,156.00,157.00,155.00
[READ].MaxLatency(us),43295.00,29103.00,36287.00,27727.00
[READ].95thPercentileLatency(us),609.00,586.00,626.00,602.00
[READ].99thPercentileLatency(us),810.00,734.00,871.00,764.00
[READ].Return=OK,1499615,1498920,1500841,1500196
[UPDATE].Operations,1500385,1501080,1499159,1499804
[UPDATE].AverageLatency(us),44013.84,43346.86,43306.37,43483.42
[UPDATE].MinLatency(us),6204.00,5944.00,6940.00,5032.00
[UPDATE].MaxLatency(us),8413183.00,7794687.00,7602175.00,7299071.00
[UPDATE].95thPercentileLatency(us),50175.00,50079.00,50143.00,50079.00
[UPDATE].99thPercentileLatency(us),900095.00,918527.00,887295.00,919039.00
[UPDATE].Return=OK,1500385,1501080,1499159,1499804
time_load,1927.00,1927.00,1992.00,1992.00
time_ingest,886.00,886.00,905.00,905.00
time_check,1040.00,1040.00,1086.00,1086.00
pods,1,8,1,8
datadisk,7091,8548,7091,8546
host_disk,158125,159582,158125,159581
host_datadisk,7091,8548,7091,8546
benchmarking_parameters_PARALLEL,1,8,1,8
benchmarking_parameters_YCSB_THREADCOUNT,64,8,64,8
benchmarking_parameters_YCSB_TARGET,32768,4096,49152,6144
benchmarking_parameters_YCSB_OPERATIONS,3000000,375000,3000000,375000
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364
phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2

# Performance at Ingestion

In [30]:
df_performance = collect.get_connections()
#df_performance = collect.get_loading_time_max_all()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

,1776678767-PostgreSQL-64-8-65536-1-1,1776678767-PostgreSQL-64-8-65536-2-1,1776678767-PostgreSQL-64-8-65536-2-2,1776678767-PostgreSQL-64-8-65536-2-3,1776678767-PostgreSQL-64-8-65536-2-4,1776678767-PostgreSQL-64-8-65536-2-5,1776678767-PostgreSQL-64-8-65536-2-6,1776678767-PostgreSQL-64-8-65536-2-7,1776678767-PostgreSQL-64-8-65536-2-8,1776682364-PostgreSQL-64-8-65536-1-1,1776682364-PostgreSQL-64-8-65536-2-1,1776682364-PostgreSQL-64-8-65536-2-2,1776682364-PostgreSQL-64-8-65536-2-3,1776682364-PostgreSQL-64-8-65536-2-4,1776682364-PostgreSQL-64-8-65536-2-5,1776682364-PostgreSQL-64-8-65536-2-6,1776682364-PostgreSQL-64-8-65536-2-7,1776682364-PostgreSQL-64-8-65536-2-8
code,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776678767,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364,1776682364
connection,1776678767-PostgreSQL-64-8-65536-1-1,1776678767-PostgreSQL-64-8-65536-2-1,1776678767-PostgreSQL-64-8-65536-2-2,1776678767-PostgreSQL-64-8-65536-2-3,1776678767-PostgreSQL-64-8-65536-2-4,1776678767-PostgreSQL-64-8-65536-2-5,1776678767-PostgreSQL-64-8-65536-2-6,1776678767-PostgreSQL-64-8-65536-2-7,1776678767-PostgreSQL-64-8-65536-2-8,1776682364-PostgreSQL-64-8-65536-1-1,1776682364-PostgreSQL-64-8-65536-2-1,1776682364-PostgreSQL-64-8-65536-2-2,1776682364-PostgreSQL-64-8-65536-2-3,1776682364-PostgreSQL-64-8-65536-2-4,1776682364-PostgreSQL-64-8-65536-2-5,1776682364-PostgreSQL-64-8-65536-2-6,1776682364-PostgreSQL-64-8-65536-2-7,1776682364-PostgreSQL-64-8-65536-2-8
configuration,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536
phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-2
experiment_run,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
client,1,2,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1927.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00,1992.00
time_ingest,886.00,886.00,886.00,886.00,886.00,886.00,886.00,886.00,886.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00,905.00
time_check,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1040.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00,1086.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,8,8,8,8,8,8,8,8,1,8,8,8,8,8,8,8,8
tenant,,,,,,,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,7091,8548,8548,8548,8548,8548,8548,8548,8548,7091,8546,8546,8546,8546,8546,8546,8546,8546
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,,,,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,158125,159582,159582,159582,159582,159582,159582,159582,159582,158125,159581,159581,159581,159581,159581,159581,159581,159581
host_datadisk,7091,8548,8548,8548,8548,8548,8548,8548,8548,7091,8546,8546,8546,8546,8546,8546,8546,8546
host_volume_size,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_YCSB_THREADCOUNT,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_YCSB_TARGET,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192,8192
loading_parameters_YCSB_STATUS,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_YCSB_WORKLOAD,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
loading_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000
loading_parameters_YCSB_OPERATIONS,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000,375000
loading_parameters_YCSB_BATCHSIZE,,,,,,,,,,,,,,,,,,
loading_parameters_YCSB_STATUS_INTERVAL,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
loading_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc
loading_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
loading_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed
benchmarking_parameters_PARALLEL,1,8,8,8,8,8,8,8,8,1,8,8,8,8,8,8,8,8
benchmarking_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
benchmarking_parameters_YCSB_THREADCOUNT,64,8,8,8,8,8,8,8,8,64,8,8,8,8,8,8,8,8
benchmarking_parameters_YCSB_TARGET,32768,4096,4096,4096,4096,4096,4096,4096,4096,49152,6144,6144,6144,6144,6144,6144,6144,6144
benchmarking_parameters_YCSB_STATUS,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
benchmarking_parameters_YCSB_WORKLOAD,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
benchmarking_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000,3000000
benchmarking_parameters_YCSB_OPERATIONS,3000000,375000,375000,375000,375000,375000,375000,375000,375000,3000000,375000,375000,375000,375000,375000,375000,375000,375000
benchmarking_parameters_YCSB_BATCHSIZE,,,,,,,,,,,,,,,,,,
benchmarking_parameters_YCSB_STATUS_INTERVAL,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10,10
benchmarking_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc,jdbc
benchmarking_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
benchmarking_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed,hashed
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Hardware Monitoring for Loading Phase

In [31]:
df_performance = collect.get_monitoring_aggregated_per_phase("loading")
df_performance = collect.add_metadata(df_performance)
#df_performance_first = df_performance[df_performance['client']==1]
#df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

combine on index and column 'phase'

phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2
Memory Usage [MiB],8293.92,8293.92,8319.30,8319.30
Memory Usage Cached [MiB],9549.27,9549.27,9581.76,9581.76
CPU Utilization,1.06,1.06,0.99,0.99
CPU Throttle,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0,0,0,0
CPU Utilization Time [s],1181.18,1181.18,1085.64,1085.64
CPU User Time [s],528.34,528.34,518.97,518.97
CPU System Time [s],652.84,652.84,566.66,566.66
Network Rx Total [MiB],3654.11,3654.11,3657.70,3657.70
Network Tx Total [MiB],3543.61,3543.61,3592.75,3592.75
Filesystem Read Total [MiB],0.20,0.20,0.18,0.18
Filesystem Write Total [MiB],16514.83,16514.83,15675.07,15675.07
Core Utilization Variance [%],0.08,0.08,0.08,0.08
Max Core Utilization [%],1.40,1.40,1.44,1.44
I/O Wait [%],34.28,34.28,35.81,35.81
Total I/O Wait Time [s],880.12,880.12,925.65,925.65
code,1776678767,1776678767,1776682364,1776682364
configuration,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536,PostgreSQL-64-8-65536
experiment_run,1,1,1,1
client,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1927.00,1927.00,1992.00,1992.00
time_ingest,886.00,886.00,905.00,905.00
time_check,1040.00,1040.00,1086.00,1086.00
terminals,0,0,0,0
pods,1,8,1,8
tenant,,,,
num_worker,0,0,0,0
type_tenants,None,None,None,None
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,7091,8548,7091,8546
host_RAM,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,
host_Cores,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,158125,159582,158125,159581
host_datadisk,7091,8548,7091,8546
host_volume_size,0,0,0,0
host_volume_used,0,0,0,0
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0
host_limits_memory,0,0,0,0
loading_parameters_PARALLEL,8,8,8,8
loading_parameters_SF,3,3,3,3
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
loading_parameters_YCSB_THREADCOUNT,8,8,8,8
loading_parameters_YCSB_TARGET,8192,8192,8192,8192
loading_parameters_YCSB_STATUS,1,1,1,1
loading_parameters_YCSB_WORKLOAD,a,a,a,a
loading_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000
loading_parameters_YCSB_OPERATIONS,375000,375000,375000,375000
loading_parameters_YCSB_BATCHSIZE,,,,
loading_parameters_YCSB_STATUS_INTERVAL,10,10,10,10
loading_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc
loading_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
loading_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed
benchmarking_parameters_PARALLEL,1,8,1,8
benchmarking_parameters_SF,3,3,3,3
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
benchmarking_parameters_YCSB_THREADCOUNT,64,8,64,8
benchmarking_parameters_YCSB_TARGET,32768,4096,49152,6144
benchmarking_parameters_YCSB_STATUS,1,1,1,1
benchmarking_parameters_YCSB_WORKLOAD,a,a,a,a
benchmarking_parameters_YCSB_ROWS,3000000,3000000,3000000,3000000
benchmarking_parameters_YCSB_OPERATIONS,3000000,375000,3000000,375000
benchmarking_parameters_YCSB_BATCHSIZE,,,,
benchmarking_parameters_YCSB_STATUS_INTERVAL,10,10,10,10
benchmarking_parameters_BEXHOMA_DBMS_TYPE,jdbc,jdbc,jdbc,jdbc
benchmarking_parameters_YCSB_MEASUREMENT_TYPE,hdrhistogram,hdrhistogram,hdrhistogram,hdrhistogram
benchmarking_parameters_YCSB_INSERTORDER,hashed,hashed,hashed,hashed
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3,bexhoma-worker-postgresql-ycsb-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776678767,bexhoma-sut-postgresql-64-8-65536-1776682364,bexhoma-sut-postgresql-64-8-65536-1776682364
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1776678767-PostgreSQL-64-8-65536-1,1776678767-PostgreSQL-64-8-65536-2,1776682364-PostgreSQL-64-8-65536-1,1776682364-PostgreSQL-64-8-65536-2

In [32]:
#plot_bars(df_performance, y='CPU Utilization Time [s]', title='CPU [CPUs]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [33]:
#plot_bars(df_performance, y='Memory Usage [MiB]', title='Memory Usage [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [34]:
#plot_bars(df_performance, y='Memory Usage Cached [MiB]', title='Memory Usage Cached [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Efficiency

In [35]:
client = 1

df_performance_monitoring = collect.get_monitoring_aggregated_per_phase(type="stream")
#df_performance_monitoring = df_performance_monitoring[df_performance_monitoring['client'] == client]
df_performance = collect.get_performance_aggregated_per_phase()
#df_performance = df_performance[df_performance['client'] == client]
merged_df = pd.merge(df_performance, df_performance_monitoring, left_index=True, right_index=True, how='left')
#merged_df = pd.merge(df_performance, df_performance_monitoring, on=['phase'], how='inner')
#merged_df['I_Lat'] = 1./merged_df['E_Lat']
merged_df = merged_df[merged_df['client'] == client]
merged_df['E_Tpx'] = merged_df['Goodput (requests/second)'] / merged_df['CPU Utilization Time [s]'] * 600.
merged_df['E_Lat'] = 1./np.sqrt(merged_df['Latency Distribution.Average Latency (microseconds)']*merged_df['CPU Utilization Time [s]']/1E6)
merged_df['E_RAM'] = (merged_df['Goodput (requests/second)']) / merged_df['Memory Usage [MiB]']
merged_df.T

KeyError: 'Goodput (requests/second)'

In [ ]:
df = collect.add_metadata(merged_df)
df.T

In [ ]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']]