# TPC-C Collector Demo

In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option('display.max_colwidth', None)
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.float_format = '{:.2f}'.format

from bexhoma import collectors

%matplotlib inline

## Functions for Nice Plots

In [2]:
from notebookutils import *

# Collect Results

In [3]:
path = r"D:\data\benchmarks"
#path = r"/data/benchmarks"
filename_prefix = "demo_"
b_plot_save = False
b_skip_plots = True

In [4]:
codes = [
    "1776751747",
    "1776754749"
]

codes

['1776751747', '1776754749']

In [5]:
collect = collectors.benchbase(path, codes)

# Get all Metrics Metadata

## Metrics Names and Types

Metrics that are derived from monitoring

In [6]:
collect.get_metrics_metadata()

,title,active,type,metric
total_cpu_memory,Memory Usage [MiB],True,cluster,gauge
total_cpu_memory_cached,Memory Usage Cached [MiB],True,cluster,gauge
total_cpu_util,CPU Utilization,True,cluster,gauge
total_cpu_throttled,CPU Throttle,True,cluster,gauge
total_cpu_throttled_s,CPU Throttled Time [s],True,cluster,counter
total_cpu_util_others,CPU Utilization Others,False,cluster,gauge
total_cpu_util_s,CPU Utilization Time [s],True,cluster,counter
total_cpu_util_user_s,CPU User Time [s],True,cluster,counter
total_cpu_util_sys_s,CPU System Time [s],True,cluster,counter
total_cpu_util_others_s,CPU Utilization Time Others [s],False,cluster,counter
total_network_rx,Network Rx Total [MiB],True,cluster,counter
total_network_tx,Network Tx Total [MiB],True,cluster,counter
total_fs_read,Filesystem Read Total [MiB],True,cluster,counter
total_fs_write,Filesystem Write Total [MiB],True,cluster,counter
total_gpu_util,GPU Utilization [%],False,cluster,gauge
total_gpu_power,GPU Power Usage [W],False,cluster,gauge
total_gpu_memory,GPU Memory Usage [MiB],False,cluster,gauge
core_variance,Core Utilization Variance [%],True,cluster,ratio
max_core_util,Max Core Utilization [%],True,cluster,ratio
io_wait_pct,I/O Wait [%],True,cluster,ratio
io_wait_total,Total I/O Wait Time [s],True,cluster,counter
pg_stat_activity_count_idle,Number of Idle Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction,Number of Idle-in-transaction Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction_aborted,Number of Idle-in-transaction Aborted Sessions,True,application,gauge
pg_stat_activity_count_active,Number of Active Sessions,True,application,counter
pg_stat_activity_count_active_app,Number of Active Application Sessions,True,application,counter
pg_stat_activity_max_tx_duration_active,Longest Active Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle,Longest Idle Session (no transaction),True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx,Longest Idle-in-Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx_aborted,Longest Idle-in-Transaction (Aborted),True,application,ratio
pg_stat_activity_count_io,Active Backends Waiting on I/O,True,application,gauge
pg_stat_activity_count_wal,Active Backends Waiting on WAL,True,application,gauge
pg_stat_activity_count_lock,Active Backends Waiting on Locks,True,application,gauge
pg_stat_activity_max_tx_duration_io,Max Transaction Duration (I/O Wait),True,application,ratio
pg_stat_activity_max_tx_duration_wal,Max Transaction Duration (WAL Wait),True,application,ratio
pg_stat_activity_max_tx_duration_lock,Max Transaction Duration (Lock Wait),True,application,ratio
pg_stat_database_blks_read,Disk Blocks Read Count,True,application,counter
pg_stat_database_blks_hit,Buffer Cache Hit Count,True,application,counter
cache_hit_ratio,Buffer Cache Hit Ratio,True,application,ratio
pg_stat_user_tables_idx_scan,Index Scan Count,True,application,counter
pg_stat_user_tables_idx_tup_fetch,Index Tuple Fetch Count,True,application,counter
pg_statio_user_tables_idx_cache_hit_ratio,Index Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_heap_blocks_hit,Table Buffer Hit Count,True,application,counter
pg_statio_user_tables_heap_blocks_read,Table Blocks Read Count,True,application,counter
pg_statio_user_tables_heap_cache_hit_ratio,Table Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_total_cache_hit_ratio,Total Cache Hit Ratio,True,application,ratio
pg_stat_bgwriter_efficiency_ratio,BGWriter Efficiency Ratio (Cleaned / Allocated),True,application,ratio
pg_stat_bgwriter_maxwritten_clean_total,BGWriter Stopped Due to Max Pages,True,application,counter
pg_stat_bgwriter_checkpoint_sync_time_total,Checkpoint Sync Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_total,Checkpoint Write Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_per_sync_time,Time spent writing vs syncing during checkpoints [ratio],False,application,ratio
pg_locks_count,Total Locks Current,True,application,gauge
pg_locks_count_accessexclusivelock,AccessExclusiveLocks Current,True,application,gauge
pg_locks_count_accesssharelock,AccessShareLocks Current,True,application,gauge
pg_locks_count_exclusivelock,ExclusiveLocks Current,True,application,gauge
pg_locks_count_rowexclusivelock,RowExclusiveLocks Current,True,application,gauge
pg_locks_count_rowsharelock,RowShareLocks Current,True,application,gauge
pg_locks_count_sharelock,ShareLocks Current,True,application,gauge
pg_locks_count_sharerowexclusivelock,ShareRowExclusiveLocks Current,True,application,gauge
pg_locks_count_shareupdateexclusivelock,ShareUpdateExclusiveLocks Current,True,application,gauge
pg_locks_count_sireadlock,SIReadLocks Current,True,application,gauge
pg_stat_user_tables_autoanalyze_count,Autoanalyze Run Count,True,application,counter
pg_stat_user_tables_autovacuum_count,Autovacuum Run Count,True,application,counter
pg_stat_bgwriter_checkpoints_timed_per_req,Frequency of checkpoints (timed vs requested) [ratio],False,application,gauge
pg_stat_wal_volume_bytes_sec,Volume of WAL generated [bytes/sec],False,application,counter
pg_stat_bgwriter_buffers_backend_fsync,Backends forced to flush WAL (I/O contention) [fsync/sec],False,application,counter
pg_stat_activity_wait_event_count,Active sessions waiting on any event [count],False,application,gauge
pg_stat_user_tables_dead_tuples_per_vacuum,Dead tuples per vacuum operation [tuples/vacuum],True,application,ratio
pg_wal_segments,Number of WAL Segments,True,application,gauge
pg_wal_size_bytes,Total WAL Size [GiB],True,application,gauge
pg_wal_segments_rate,WAL Segments Growth Rate [segments/s],True,application,gauge
pg_wal_size_rate,WAL Growth Rate [MiB/s],True,application,gauge
pg_wal_avg_segment_size,Average WAL Segment Size [MiB],True,application,gauge
pg_wal_size_per_checkpoint,WAL Size per Checkpoint [bytes/checkpoint],False,application,gauge

## Names of Monitored Components

Names of components and their phases

In [7]:
collect.get_monitored_components()

                                        description
loading               Loading phase: SUT deployment
loader              Loading phase: component loader
stream              Execution phase: SUT deployment
benchmarker  Execution phase: component benchmarker

# Get Connection Infos

List of states of SUTs, containing loading infos.

In [8]:
df=collect.get_connections()

In [9]:
df.T

,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-8
code,1776751747,1776751747,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749
connection,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-8
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2
experiment_run,1,1,1,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2
client,1,2,2,1,2,2,1,1,1,1,2,2,2,2,2,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1398.00,1398.00,1398.00,1398.00,1398.00,1398.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00
time_ingest,663.00,663.00,663.00,663.00,663.00,663.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00
time_check,735.00,735.00,735.00,735.00,735.00,735.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00
terminals,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
pods,1,2,2,1,2,2,4,4,4,4,8,8,8,8,8,8,8,8,4,4,4,4,8,8,8,8,8,8,8,8
tenant,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,4307,4533,4533,4705,4805,4805,4307,4307,4307,4307,4525,4525,4525,4525,4525,4525,4525,4525,4686,4686,4686,4686,4794,4794,4794,4794,4794,4794,4794,4794
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247605,247606,247606,247607,247607,247607,247609,247609,247609,247609,247610,247610,247610,247610,247610,247610,247610,247610,247611,247611,247611,247611,247611,247611,247611,247611,247611,247611,247611,247611
host_datadisk,4307,4533,4533,4705,4805,4805,4307,4307,4307,4307,4525,4525,4525,4525,4525,4525,4525,4525,4686,4686,4686,4686,4794,4794,4794,4794,4794,4794,4794,4794
host_volume_size,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G
host_volume_used,4.3G,4.3G,4.3G,4.6G,4.6G,4.6G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G
host_cuda,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
loading_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
loading_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
loading_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
loading_parameters_BENCHBASE_TERMINALS,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BENCHBASE_TIME,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300
loading_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
loading_parameters_BENCHBASE_BATCHSIZE,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
loading_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false
loading_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false
loading_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
benchmarking_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
benchmarking_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
benchmarking_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
benchmarking_parameters_BENCHBASE_TARGET,16384,8192,8192,16384,8192,8192,5120,5120,5120,5120,2560,2560,2560,2560,2560,2560,2560,2560,5120,5120,5120,5120,2560,2560,2560,2560,2560,2560,2560,2560
benchmarking_parameters_BENCHBASE_TERMINALS,160,80,80,160,80,80,40,40,40,40,20,20,20,20,20,20,20,20,40,40,40,40,20,20,20,20,20,20,20,20
benchmarking_parameters_BENCHBASE_TIME,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300
benchmarking_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
benchmarking_parameters_BENCHBASE_BATCHSIZE,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
benchmarking_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false
benchmarking_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false
benchmarking_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16

# Performance at Ingestion

In [10]:
df = collect.get_loading_per_connection()
df.T

,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-8
code,1776751747,1776751747,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749
SF,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
connection,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-8
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2
experiment_run,1,1,1,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2
client,1,2,2,1,2,2,1,1,1,1,2,2,2,2,2,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2
time_load,1398.00,1398.00,1398.00,1398.00,1398.00,1398.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00
time_ingest,663.00,663.00,663.00,663.00,663.00,663.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00
time_check,735.00,735.00,735.00,735.00,735.00,735.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00
pods,1,2,2,1,2,2,4,4,4,4,8,8,8,8,8,8,8,8,4,4,4,4,8,8,8,8,8,8,8,8
type_tenants,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Throughput [SF/h],41.20,41.20,41.20,41.20,41.20,41.20,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89

## With Metadata

Connection infos are added.

In [11]:
df = collect.add_metadata(df)
df.T

combine on index

,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-8
code,1776751747,1776751747,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749
SF,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
connection,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-8
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2
experiment_run,1,1,1,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2
client,1,2,2,1,2,2,1,1,1,1,2,2,2,2,2,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2
time_load,1398.00,1398.00,1398.00,1398.00,1398.00,1398.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00
time_ingest,663.00,663.00,663.00,663.00,663.00,663.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00
time_check,735.00,735.00,735.00,735.00,735.00,735.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00
pods,1,2,2,1,2,2,4,4,4,4,8,8,8,8,8,8,8,8,4,4,4,4,8,8,8,8,8,8,8,8
type_tenants,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Throughput [SF/h],41.20,41.20,41.20,41.20,41.20,41.20,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89,38.89
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
terminals,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
tenant,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
datadisk,4307,4533,4533,4705,4805,4805,4307,4307,4307,4307,4525,4525,4525,4525,4525,4525,4525,4525,4686,4686,4686,4686,4794,4794,4794,4794,4794,4794,4794,4794
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247605,247606,247606,247607,247607,247607,247609,247609,247609,247609,247610,247610,247610,247610,247610,247610,247610,247610,247611,247611,247611,247611,247611,247611,247611,247611,247611,247611,247611,247611
host_datadisk,4307,4533,4533,4705,4805,4805,4307,4307,4307,4307,4525,4525,4525,4525,4525,4525,4525,4525,4686,4686,4686,4686,4794,4794,4794,4794,4794,4794,4794,4794
host_volume_size,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G,100G
host_volume_used,4.3G,4.3G,4.3G,4.6G,4.6G,4.6G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.3G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G,4.6G
host_cuda,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
loading_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
loading_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
loading_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
loading_parameters_BENCHBASE_TERMINALS,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BENCHBASE_TIME,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300
loading_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
loading_parameters_BENCHBASE_BATCHSIZE,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
loading_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false
loading_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false
loading_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
benchmarking_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
benchmarking_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
benchmarking_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
benchmarking_parameters_BENCHBASE_TARGET,16384,8192,8192,16384,8192,8192,5120,5120,5120,5120,2560,2560,2560,2560,2560,2560,2560,2560,5120,5120,5120,5120,2560,2560,2560,2560,2560,2560,2560,2560
benchmarking_parameters_BENCHBASE_TERMINALS,160,80,80,160,80,80,40,40,40,40,20,20,20,20,20,20,20,20,40,40,40,40,20,20,20,20,20,20,20,20
benchmarking_parameters_BENCHBASE_TIME,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300
benchmarking_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
benchmarking_parameters_BENCHBASE_BATCHSIZE,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
benchmarking_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false
benchmarking_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false
benchmarking_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a,a
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [12]:
df[['phase', 'code', 'connection', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-8
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2
code,1776751747,1776751747,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749
connection,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-8
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
experiment_run,1,1,1,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2
client,1,2,2,1,2,2,1,1,1,1,2,2,2,2,2,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2
type_tenants,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

# Performance at Ingestion per Run

In [13]:
df = collect.get_loading_per_run()
df.T

,1776751747-PostgreSQL-1-1-1024-1,1776751747-PostgreSQL-1-1-1024-2,1776754749-PostgreSQL-1-1-1024-1,1776754749-PostgreSQL-1-1-1024-2
code,1776751747,1776751747,1776754749,1776754749
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
experiment_run,1,2,1,2
SF,16,16,16,16
time_load,1398.00,1398.00,1481.00,1481.00
time_ingest,663.00,663.00,716.00,716.00
time_check,735.00,735.00,765.00,765.00
pods,2,2,8,8
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
Throughput [SF/h],41.20,41.20,38.89,38.89

## Get Non-Constant Attributes

These attributes are (most probably) used to analyze performance.

In [14]:
collectors.get_non_constant(df)

,code,experiment_run,time_load,time_ingest,time_check,pods,Throughput [SF/h]
1776751747-PostgreSQL-1-1-1024-1,1776751747,1,1398.00,663.00,735.00,2,41.20
1776751747-PostgreSQL-1-1-1024-2,1776751747,2,1398.00,663.00,735.00,2,41.20
1776754749-PostgreSQL-1-1-1024-1,1776754749,1,1481.00,716.00,765.00,8,38.89
1776754749-PostgreSQL-1-1-1024-2,1776754749,2,1481.00,716.00,765.00,8,38.89

# Monitoring Aggregated per Phase

In [15]:
df = collect.get_monitoring_aggregated_per_phase("stream")
df.T

,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2
Memory Usage [MiB],8768.13,8960.49,7701.75,8292.44,8717.99,8991.46,7714.02,8311.03
Memory Usage Cached [MiB],10557.51,10937.89,9697.59,10453.01,10494.15,10970.49,9724.02,10481.40
CPU Utilization,2.04,2.01,1.61,1.75,1.65,1.54,1.54,1.96
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],643.95,618.28,1915.46,523.59,554.00,486.08,1679.78,631.07
CPU User Time [s],384.40,362.83,1277.49,309.86,329.65,285.47,1142.31,375.49
CPU System Time [s],259.55,255.45,637.98,213.72,224.35,200.62,537.47,255.58
Network Rx Total [MiB],956.21,718.51,2739.48,557.19,879.98,663.16,2572.74,628.28
Network Tx Total [MiB],1736.34,724.69,1229.08,557.73,1754.29,665.22,1009.67,703.83
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.00,0.02,0.00,0.00,0.00,0.02,0.00
Core Utilization Variance [%],0.03,0.02,0.02,0.02,0.02,0.02,0.02,0.02
Max Core Utilization [%],0.51,0.53,0.37,0.57,0.53,0.49,0.47,0.52
I/O Wait [%],18.29,16.96,21.35,18.84,20.86,17.15,21.95,17.10
Total I/O Wait Time [s],280.82,266.37,388.73,278.21,295.61,267.89,356.21,269.93
Number of Idle Sessions,0.33,0.22,0.26,1.54,0.50,0.36,0.26,0.72
Number of Idle-in-transaction Sessions,2.78,0.36,0.59,2.85,1.62,2.79,0.56,0.62
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,160.00,161.00,160.00,161.00,160.00,160.00,160.00,161.00
Number of Active Application Sessions,160.00,160.00,160.00,160.00,160.00,160.00,160.00,160.00
Longest Active Transaction,5.13,6.43,5.51,5.77,6.87,9.70,6.55,7.34
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.06,0.00,0.05,0.31,0.03,0.27,0.08,0.01
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.97,0.97,4.43,1.00,0.99,0.98,1.03,0.96
Active Backends Waiting on WAL,32.33,34.66,34.52,28.70,33.93,31.91,32.41,29.96
Active Backends Waiting on Locks,118.56,120.67,118.07,115.56,120.33,120.87,120.12,120.76
Max Transaction Duration (I/O Wait),0.46,0.67,0.44,0.41,0.26,0.43,0.57,0.41
Max Transaction Duration (WAL Wait),3.29,3.82,3.83,3.55,4.40,4.56,4.10,3.52
Max Transaction Duration (Lock Wait),4.92,6.30,5.45,5.72,6.70,9.62,6.39,7.34
Disk Blocks Read Count,5.00,0.00,131189.00,22612.00,5.00,0.00,131920.00,28877.00
Buffer Cache Hit Count,39124427.00,39360485.00,25220288.00,32405498.00,36083065.00,31584144.00,25394830.00,39603625.00
Buffer Cache Hit Ratio,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Index Scan Count,5486896.00,5702002.00,3709287.00,4664427.00,5030030.00,4341170.00,3644843.00,5340787.00
Index Tuple Fetch Count,7309126.00,7646553.00,4930017.00,6239036.00,6808882.00,6019647.00,4907631.00,7414673.00
Index Cache Hit Ratio,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Table Buffer Hit Count,19533848.00,19559008.00,12388976.00,16215544.00,17794069.00,15828986.00,12570806.00,20423654.00
Table Blocks Read Count,0.00,0.00,111337.00,18994.00,0.00,0.00,112121.00,24223.00
Table Cache Hit Ratio,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Total Cache Hit Ratio,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,971.23,974.03,1040.79,949.29,988.14,977.98,947.56,913.60
AccessExclusiveLocks Current,0.18,1.80,0.33,1.70,2.71,2.50,1.89,2.31
AccessShareLocks Current,221.72,222.67,245.51,218.37,230.38,228.32,216.51,206.44
ExclusiveLocks Current,51.91,51.61,49.57,50.32,55.51,53.49,52.09,52.96
RowExclusiveLocks Current,486.62,487.18,499.51,472.03,482.75,482.29,473.75,464.60
RowShareLocks Current,210.79,210.78,245.87,206.87,216.79,211.38,203.32,187.30
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],inf,inf,inf,inf,inf,inf,inf,inf
Number of WAL Segments,165.00,165.00,165.00,165.00,165.00,165.00,165.00,165.00
Total WAL Size [GiB],2.58,2.58,2.58,2.58,2.58,2.58,2.58,2.58
WAL Segments Growth Rate [segments/s],0.05,0.00,0.00,0.00,0.05,0.00,0.00,0.00
WAL Growth Rate [MiB/s],0.76,0.00,0.00,0.00,0.80,0.00,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00

## With Metadata

Connection infos are added.

In [16]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2
Memory Usage [MiB],8768.13,8960.49,7701.75,8292.44,8717.99,8991.46,7714.02,8311.03
Memory Usage Cached [MiB],10557.51,10937.89,9697.59,10453.01,10494.15,10970.49,9724.02,10481.40
CPU Utilization,2.04,2.01,1.61,1.75,1.65,1.54,1.54,1.96
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],643.95,618.28,1915.46,523.59,554.00,486.08,1679.78,631.07
CPU User Time [s],384.40,362.83,1277.49,309.86,329.65,285.47,1142.31,375.49
CPU System Time [s],259.55,255.45,637.98,213.72,224.35,200.62,537.47,255.58
Network Rx Total [MiB],956.21,718.51,2739.48,557.19,879.98,663.16,2572.74,628.28
Network Tx Total [MiB],1736.34,724.69,1229.08,557.73,1754.29,665.22,1009.67,703.83
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.00,0.02,0.00,0.00,0.00,0.02,0.00
Core Utilization Variance [%],0.03,0.02,0.02,0.02,0.02,0.02,0.02,0.02
Max Core Utilization [%],0.51,0.53,0.37,0.57,0.53,0.49,0.47,0.52
I/O Wait [%],18.29,16.96,21.35,18.84,20.86,17.15,21.95,17.10
Total I/O Wait Time [s],280.82,266.37,388.73,278.21,295.61,267.89,356.21,269.93
Number of Idle Sessions,0.33,0.22,0.26,1.54,0.50,0.36,0.26,0.72
Number of Idle-in-transaction Sessions,2.78,0.36,0.59,2.85,1.62,2.79,0.56,0.62
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,160.00,161.00,160.00,161.00,160.00,160.00,160.00,161.00
Number of Active Application Sessions,160.00,160.00,160.00,160.00,160.00,160.00,160.00,160.00
Longest Active Transaction,5.13,6.43,5.51,5.77,6.87,9.70,6.55,7.34
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.06,0.00,0.05,0.31,0.03,0.27,0.08,0.01
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.97,0.97,4.43,1.00,0.99,0.98,1.03,0.96
Active Backends Waiting on WAL,32.33,34.66,34.52,28.70,33.93,31.91,32.41,29.96
Active Backends Waiting on Locks,118.56,120.67,118.07,115.56,120.33,120.87,120.12,120.76
Max Transaction Duration (I/O Wait),0.46,0.67,0.44,0.41,0.26,0.43,0.57,0.41
Max Transaction Duration (WAL Wait),3.29,3.82,3.83,3.55,4.40,4.56,4.10,3.52
Max Transaction Duration (Lock Wait),4.92,6.30,5.45,5.72,6.70,9.62,6.39,7.34
Disk Blocks Read Count,5.00,0.00,131189.00,22612.00,5.00,0.00,131920.00,28877.00
Buffer Cache Hit Count,39124427.00,39360485.00,25220288.00,32405498.00,36083065.00,31584144.00,25394830.00,39603625.00
Buffer Cache Hit Ratio,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Index Scan Count,5486896.00,5702002.00,3709287.00,4664427.00,5030030.00,4341170.00,3644843.00,5340787.00
Index Tuple Fetch Count,7309126.00,7646553.00,4930017.00,6239036.00,6808882.00,6019647.00,4907631.00,7414673.00
Index Cache Hit Ratio,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Table Buffer Hit Count,19533848.00,19559008.00,12388976.00,16215544.00,17794069.00,15828986.00,12570806.00,20423654.00
Table Blocks Read Count,0.00,0.00,111337.00,18994.00,0.00,0.00,112121.00,24223.00
Table Cache Hit Ratio,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Total Cache Hit Ratio,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,971.23,974.03,1040.79,949.29,988.14,977.98,947.56,913.60
AccessExclusiveLocks Current,0.18,1.80,0.33,1.70,2.71,2.50,1.89,2.31
AccessShareLocks Current,221.72,222.67,245.51,218.37,230.38,228.32,216.51,206.44
ExclusiveLocks Current,51.91,51.61,49.57,50.32,55.51,53.49,52.09,52.96
RowExclusiveLocks Current,486.62,487.18,499.51,472.03,482.75,482.29,473.75,464.60
RowShareLocks Current,210.79,210.78,245.87,206.87,216.79,211.38,203.32,187.30
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],inf,inf,inf,inf,inf,inf,inf,inf
Number of WAL Segments,165.00,165.00,165.00,165.00,165.00,165.00,165.00,165.00
Total WAL Size [GiB],2.58,2.58,2.58,2.58,2.58,2.58,2.58,2.58
WAL Segments Growth Rate [segments/s],0.05,0.00,0.00,0.00,0.05,0.00,0.00,0.00
WAL Growth Rate [MiB/s],0.76,0.00,0.00,0.00,0.80,0.00,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00
code,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1398.00,1398.00,1398.00,1398.00,1481.00,1481.00,1481.00,1481.00
time_ingest,663.00,663.00,663.00,663.00,716.00,716.00,716.00,716.00
time_check,735.00,735.00,735.00,735.00,765.00,765.00,765.00,765.00
terminals,1,1,1,1,1,1,1,1
pods,1,2,1,2,4,8,4,8
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,4307,4533,4705,4805,4307,4525,4686,4794
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247605,247606,247607,247607,247609,247610,247611,247611
host_datadisk,4307,4533,4705,4805,4307,4525,4686,4794
host_volume_size,100G,100G,100G,100G,100G,100G,100G,100G
host_volume_used,4.3G,4.3G,4.6G,4.6G,4.3G,4.3G,4.6G,4.6G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,16,16,16,16,16,16,16,16
loading_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
loading_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
loading_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
loading_parameters_BENCHBASE_TERMINALS,1,1,1,1,1,1,1,1
loading_parameters_BENCHBASE_TIME,300,300,300,300,300,300,300,300
loading_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
loading_parameters_BENCHBASE_BATCHSIZE,128,128,128,128,128,128,128,128
loading_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0,0,0,0,0
loading_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false,false,false,false,false
loading_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false,false,false,false,false
loading_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a,a,a,a,a
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,16,16,16,16,16,16,16,16
benchmarking_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
benchmarking_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
benchmarking_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
benchmarking_parameters_BENCHBASE_TARGET,16384,8192,16384,8192,5120,2560,5120,2560
benchmarking_parameters_BENCHBASE_TERMINALS,160,80,160,80,40,20,40,20
benchmarking_parameters_BENCHBASE_TIME,300,300,300,300,300,300,300,300
benchmarking_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
benchmarking_parameters_BENCHBASE_BATCHSIZE,128,128,128,128,128,128,128,128
benchmarking_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0,0,0,0,0
benchmarking_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false,false,false,false,false
benchmarking_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false,false,false,false,false
benchmarking_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a,a,a,a,a
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776754749,bexhoma-sut-postgresql-1-1-1024-1776754749,bexhoma-sut-postgresql-1-1-1024-1776754749,bexhoma-sut-postgresql-1-1-1024-1776754749
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [17]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2
code,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False

# Time Series of a Single Metric for a Single Experiment

This is particularly important if you require a customized aggregation or wish to monitor a component over time.

In [18]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_per_phase(code, metric=metric, component='stream')
df.T

,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2
0,7537.76,7749.48,7922.79,6995.77
1,7537.76,7749.48,7922.79,6995.77
2,7537.76,7749.48,7922.79,6995.77
3,7537.76,7749.48,7922.79,6995.77
4,7537.76,7749.48,7922.79,6995.77
5,8173.61,7749.48,7922.79,6995.77
6,8173.61,7749.48,5852.46,6995.77
7,8173.61,7749.48,5852.46,6995.77
8,8173.61,7749.48,6544.12,6995.77
9,8173.61,7749.48,6544.12,6995.77
10,8173.61,7749.48,6544.12,6995.77
11,8173.61,7749.48,6544.12,6995.77
12,8173.61,7749.48,6544.12,7961.09
13,8173.61,7749.48,6544.12,7961.09
14,8173.61,7749.48,6544.12,7961.09
15,8173.61,7749.48,6544.12,7961.09
16,8173.61,7749.48,6544.12,7961.09
17,8173.61,7749.48,6544.12,7961.09
18,8173.61,7749.48,6544.12,7961.09
19,8173.61,7749.48,6544.12,7961.09
20,8173.61,7749.48,6544.12,7961.09
21,8173.61,7749.48,6544.12,7961.09
22,8173.61,7749.48,6544.12,7961.09
23,8173.61,7749.48,6544.12,7961.09
24,8173.61,7749.48,6544.12,7961.09
25,8173.61,8851.65,6544.12,7961.09
26,8173.61,8851.65,6544.12,7961.09
27,8173.61,8851.65,6544.12,7961.09
28,8173.61,8851.65,6544.12,7961.09
29,8173.61,8851.65,6544.12,7961.09
30,8173.61,8851.65,6544.12,7961.09
31,8542.69,8851.65,6544.12,7961.09
32,8542.69,8851.65,6544.12,7961.09
33,8542.69,8851.65,6544.12,7961.09
34,8542.69,8851.65,6544.12,7961.09
35,8542.69,8851.65,6544.12,7961.09
36,8542.69,8851.65,6544.12,7961.09
37,8542.69,8851.65,6544.12,7961.09
38,8542.69,8851.65,6544.12,7961.09
39,8542.69,8851.65,6544.12,7961.09
40,8542.69,8851.65,7184.40,7961.09
41,8542.69,8851.65,7184.40,7961.09
42,8542.69,8851.65,7184.40,7961.09
43,8542.69,8851.65,7184.40,7961.09
44,8542.69,8851.65,7184.40,7961.09
45,8542.69,8851.65,7184.40,7961.09
46,8542.69,8851.65,7184.40,7961.09
47,8542.69,8851.65,7184.40,7961.09
48,8542.69,8851.65,7184.40,7961.09
49,8542.69,8851.65,7184.40,7961.09
50,8542.69,8851.65,7184.40,7961.09
51,8542.69,8851.65,7184.40,7961.09
52,8542.69,8893.27,7184.40,7961.09
53,8542.69,8893.27,7184.40,7961.09
54,8542.69,8893.27,7184.40,7961.09
55,8542.69,8893.27,7184.40,7961.09
56,8542.69,8893.27,7184.40,7961.09
57,8542.69,8893.27,7184.40,7961.09
58,8542.69,8893.27,7184.40,7961.09
59,8542.69,8893.27,7184.40,8190.44
60,8542.69,8893.27,7184.40,8190.44
61,8542.69,8893.27,7184.40,8190.44
62,8542.69,8893.27,7184.40,8190.44
63,8680.74,8893.27,7184.40,8190.44
64,8680.74,8893.27,7184.40,8190.44
65,8680.74,8934.64,7184.40,8190.44
66,8680.74,8934.64,7184.40,8190.44
67,8680.74,8934.64,7184.40,8190.44
68,8680.74,8934.64,7452.49,8190.44
69,8680.74,8934.64,7452.49,8190.44
70,8680.74,8934.64,7452.49,8190.44
71,8680.74,8934.64,7452.49,8190.44
72,8680.74,8934.64,7452.49,8190.44
73,8680.74,8934.64,7452.49,8190.44
74,8680.74,8934.64,7452.49,8190.44
75,8680.74,8934.64,7452.49,8190.44
76,8680.74,8934.64,7452.49,8190.44
77,8680.74,8934.64,7452.49,8190.44
78,8680.74,8934.64,7452.49,8190.44
79,8680.74,8934.64,7452.49,8190.44
80,8680.74,8934.64,7452.49,8190.44
81,8680.74,8934.64,7452.49,8190.44
82,8680.74,8934.64,7452.49,8190.44
83,8680.74,8934.64,7452.49,8190.44
84,8680.74,8934.64,7452.49,8190.44
85,8680.74,8934.64,7452.49,8190.44
86,8680.74,8934.64,7452.49,8190.44
87,8680.74,8934.64,7452.49,8272.52
88,8680.74,8934.64,7452.49,8272.52
89,8680.74,8934.64,7452.49,8272.52
90,8680.74,8934.64,7452.49,8272.52
91,8680.74,8934.64,7452.49,8272.52
92,8680.74,8934.64,7452.49,8272.52
93,8680.74,8934.64,7452.49,8272.52
94,8680.74,8934.64,7452.49,8272.52
95,8680.74,8934.64,7452.49,8272.52
96,8680.74,8934.64,7452.49,8272.52
97,8680.74,8934.64,7452.49,8272.52
98,8680.74,8934.64,7452.49,8272.52
99,8680.74,8934.64,7452.49,8272.52
100,8680.74,8934.64,7668.31,8272.52
101,8789.89,8934.64,7668.31,8272.52
102,8789.89,8934.64,7668.31,8272.52
103,8789.89,8934.64,7668.31,8272.52
104,8789.89,8934.64,7668.31,8272.52
105,8789.89,8934.64,7668.31,8272.52
106,8789.89,8934.64,7668.31,8272.52
107,8789.89,8934.64,7668.31,8272.52
108,8789.89,8934.64,7668.31,8272.52
109,8789.89,8934.64,7668.31,8272.52
110,8789.89,8934.64,7668.31,8272.52
111,8789.89,8934.64,7668.31,8272.52
112,8789.89,8934.64,7668.31,8272.52
113,8789.89,8996.62,7668.31,8272.52
114,8789.89,8996.62,7668.31,8272.52
115,8789.89,8996.62,7668.31,8325.48
116,8789.89,8996.62,7668.31,8325.48
117,8789.89,8996.62,7668.31,8325.48
118,8789.89,8996.62,7668.31,8325.48
119,8789.89,8996.62,7668.31,8325.48
120,8789.89,8996.62,7668.31,8325.48
121,8789.89,8996.62,7668.31,8325.48
122,8789.89,8996.62,7668.31,8325.48
123,8789.89,8996.62,7668.31,8325.48
124,8789.89,8996.62,7668.31,8325.48
125,8789.89,8996.62,7668.31,8325.48
126,8789.89,8996.62,7668.31,8325.48
127,8789.89,8996.62,7668.31,8325.48
128,8789.89,8996.62,7668.31,8325.48
129,8789.89,8996.62,7835.16,8325.48
130,8789.89,8996.62,7835.16,8325.48
131,8789.89,8996.62,7835.16,8325.48
132,8789.89,8996.62,7835.16,8325.48
133,8789.89,8996.62,7835.16,8325.48
134,8831.99,8996.62,7835.16,8325.48
135,8831.99,8996.62,7835.16,8325.48
136,8831.99,8996.62,7835.16,8325.48
137,8831.99,8996.62,7835.16,8325.48
138,8831.99,8996.62,7835.16,8325.48
139,8831.99,8996.62,7835.16,8325.48
140,8831.99,8996.62,7835.16,8325.48
141,8831.99,8996.62,7835.16,8325.48
142,8831.99,9037.64,7835.16,8325.48
143,8831.99,9037.64,7835.16,8391.95
144,8831.99,9037.64,7835.16,8391.95
145,8831.99,9037.64,7835.16,8391.95
146,8831.99,9037.64,7835.16,8391.95
147,8831.99,9037.64,7835.16,8391.95
148,8831.99,9037.64,7835.16,8391.95
149,8831.99,9037.64,7835.16,8391.95
150,8831.99,9037.64,7835.16,8391.95
151,8831.99,9037.64,7835.16,8391.95
152,8831.99,9037.64,7835.16,8391.95
153,8831.99,9037.64,7835.16,8391.95
154,8831.99,9037.64,7835.16,8391.95
155,8831.99,9037.64,7835.16,8391.95
156,8831.99,9037.64,7835.16,8391.95
157,8831.99,9037.64,7835.16,8391.95
158,8831.99,9037.64,7835.16,8391.95
159,8831.99,9037.64,7955.27,8391.95
160,8831.99,9037.64,7955.27,8391.95
161,8883.22,9037.64,7955.27,8391.95
162,8883.22,9037.64,7955.27,8391.95
163,8883.22,9037.64,7955.27,8391.95
164,8883.22,9037.64,7955.27,8391.95
165,8883.22,9037.64,7955.27,8391.95
166,8883.22,9037.64,7955.27,8391.95
167,8883.22,9037.64,7955.27,8391.95
168,8883.22,9037.64,7955.27,8391.95
169,8883.22,9120.65,7955.27,8391.95
170,8883.22,9120.65,7955.27,8391.95
171,8883.22,9120.65,7955.27,8435.11
172,8883.22,9120.65,7955.27,8435.11
173,8883.22,9120.65,7955.27,8435.11
174,8883.22,9120.65,7955.27,8435.11
175,8883.22,9120.65,7955.27,8435.11
176,8883.22,9120.65,7955.27,8435.11
177,8883.22,9120.65,7955.27,8435.11
178,8883.22,9120.65,7955.27,8435.11
179,8883.22,9120.65,7955.27,8435.11
180,8883.22,9120.65,7955.27,8435.11
181,8883.22,9120.65,7955.27,8435.11
182,8883.22,9120.65,7955.27,8435.11
183,8883.22,9120.65,7955.27,8435.11
184,8883.22,9120.65,7955.27,8435.11
185,8883.22,9120.65,7955.27,8435.11
186,8883.22,9120.65,7955.27,8435.11
187,8883.22,9120.65,7955.27,8435.11
188,8883.22,9120.65,8042.63,8435.11
189,8883.22,9120.65,8042.63,8435.11
190,8883.22,9120.65,8042.63,8435.11
191,8931.86,9120.65,8042.63,8435.11
192,8931.86,9120.65,8042.63,8435.11
193,8931.86,9120.65,8042.63,8435.11
194,8931.86,9120.65,8042.63,8435.11
195,8931.86,9120.65,8042.63,8435.11
196,8931.86,9120.65,8042.63,8435.11
197,8931.86,9120.65,8042.63,8435.11
198,8931.86,9120.65,8042.63,8435.11
199,8931.86,9120.65,8042.63,8435.11
200,8931.86,9120.65,8042.63,8435.11
201,8931.86,9120.65,8042.63,8476.10
202,8931.86,9120.65,8042.63,8476.10
203,8931.86,9191.12,8042.63,8476.10
204,8931.86,9191.12,8042.63,8476.10
205,8931.86,9191.12,8042.63,8476.10
206,8931.86,9191.12,8042.63,8476.10
207,8931.86,9191.12,8042.63,8476.10
208,8966.49,9191.12,8042.63,8476.10
209,8966.49,9191.12,8042.63,8476.10
210,8966.49,9191.12,8042.63,8476.10
211,8966.49,9191.12,8042.63,8476.10
212,8966.49,9191.12,8042.63,8476.10
213,8966.49,9191.12,8042.63,8476.10
214,8966.49,9191.12,8042.63,8476.10
215,8966.49,9191.12,8113.54,8476.10
216,8966.49,9191.12,8113.54,8476.10
217,8966.49,9191.12,8113.54,8476.10
218,8966.49,9191.12,8113.54,8476.10
219,8966.49,9191.12,8113.54,8476.10
220,8966.49,9191.12,8113.54,8476.10
221,8966.49,9191.12,8113.54,8476.10
222,8966.49,9191.12,8113.54,8476.10
223,8966.49,9191.12,8113.54,8476.10
224,8966.49,9191.12,8113.54,8476.10
225,8966.49,9191.12,8113.54,8476.10
226,8966.49,9191.12,8113.54,8476.10
227,8966.49,9191.12,8113.54,8523.05
228,8966.49,9191.12,8113.54,8523.05
229,8966.49,9191.12,8113.54,8523.05
230,8966.49,9211.88,8113.54,8523.05
231,8966.49,9211.88,8113.54,8523.05
232,8966.49,9211.88,8113.54,8523.05
233,8966.49,9211.88,8113.54,8523.05
234,8966.49,9211.88,8113.54,8523.05
235,8966.49,9211.88,8113.54,8523.05
236,8966.49,9211.88,8113.54,8523.05
237,8966.49,9211.88,8113.54,8523.05
238,8966.49,9211.88,8113.54,8523.05
239,8966.49,9211.88,8113.54,8523.05
240,8966.49,9211.88,8113.54,8523.05
241,8966.49,9211.88,8113.54,8523.05
242,8966.49,9211.88,8113.54,8523.05
243,8966.49,9211.88,8113.54,8523.05
244,9010.30,9211.88,8113.54,8523.05
245,9010.30,9211.88,8189.94,8523.05
246,9010.30,9211.88,8189.94,8523.05
247,9010.30,9211.88,8189.94,8523.05
248,9010.30,9211.88,8189.94,8523.05
249,9010.30,9211.88,8189.94,8523.05
250,9010.30,9211.88,8189.94,8523.05
251,9010.30,9211.88,8189.94,8523.05
252,9010.30,9211.88,8189.94,8523.05
253,9010.30,9211.88,8189.94,8523.05
254,9010.30,9211.88,8189.94,8523.05
255,9010.30,9211.88,8189.94,8523.05
256,9010.30,9211.88,8189.94,8523.05
257,9010.30,9211.88,8189.94,8586.28
258,9010.30,9211.88,8189.94,8586.28
259,9010.30,9242.23,8189.94,8586.28
260,9010.30,9242.23,8189.94,8586.28
261,9010.30,9242.23,8189.94,8586.28
262,9010.30,9242.23,8189.94,8586.28
263,9010.30,9242.23,8189.94,8586.28
264,9010.30,9242.23,8189.94,8586.28
265,9010.30,9242.23,8189.94,8586.28
266,9010.30,9242.23,8189.94,8586.28
267,9046.55,9242.23,8189.94,8586.28
268,9046.55,9242.23,8189.94,8586.28
269,9046.55,9242.23,8189.94,8586.28
270,9046.55,9242.23,8189.94,8586.28
271,9046.55,9242.23,8189.94,8586.28
272,9046.55,9242.23,8189.94,8586.28
273,9046.55,9242.23,8245.21,8586.28
274,9046.55,9242.23,8245.21,8586.28
275,9046.55,9242.23,8245.21,8586.28
276,9046.55,9242.23,8245.21,8586.28
277,9046.55,9242.23,8245.21,8586.28
278,9046.55,9242.23,8245.21,8586.28
279,9046.55,9242.23,8245.21,8586.28
280,9046.55,9242.23,8245.21,8586.28
281,9046.55,9242.23,8245.21,8586.28
282,9046.55,9242.23,8245.21,8586.28
283,9046.55,9242.23,8245.21,8586.28
284,9046.55,9242.23,8245.21,8586.28
285,9046.55,9242.23,8245.21,8586.28
286,9046.55,9242.23,8245.21,8586.28
287,9046.55,9242.23,8245.21,8586.28
288,9046.55,9276.96,8245.21,8586.28
289,9046.55,9276.96,8245.21,8586.28
290,9046.55,9276.96,8245.21,8636.79
291,9046.55,9276.96,8245.21,8636.79
292,9046.55,9276.96,8245.21,8636.79
293,9046.55,9276.96,8245.21,8636.79
294,9046.55,9276.96,8245.21,8636.79
295,9046.55,9276.96,8245.21,8636.79
296,9046.55,9276.96,8245.21,8636.79
297,9046.55,9276.96,8245.21,8636.79
298,9046.55,9276.96,8245.21,8636.79
299,9046.55,9276.96,8245.21,8636.79
300,9046.55,9276.96,8245.21,8636.79
301,9089.99,9276.96,8245.21,8636.79
302,9089.99,9276.96,8245.21,8636.79
303,9089.99,9276.96,8245.21,8636.79
304,9089.99,NaN,7121.30,8636.79

## With Metadata

Connection infos are added.

In [19]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2
0,7537.76,7749.48,7922.79,6995.77
1,7537.76,7749.48,7922.79,6995.77
2,7537.76,7749.48,7922.79,6995.77
3,7537.76,7749.48,7922.79,6995.77
4,7537.76,7749.48,7922.79,6995.77
5,8173.61,7749.48,7922.79,6995.77
6,8173.61,7749.48,5852.46,6995.77
7,8173.61,7749.48,5852.46,6995.77
8,8173.61,7749.48,6544.12,6995.77
9,8173.61,7749.48,6544.12,6995.77
10,8173.61,7749.48,6544.12,6995.77
11,8173.61,7749.48,6544.12,6995.77
12,8173.61,7749.48,6544.12,7961.09
13,8173.61,7749.48,6544.12,7961.09
14,8173.61,7749.48,6544.12,7961.09
15,8173.61,7749.48,6544.12,7961.09
16,8173.61,7749.48,6544.12,7961.09
17,8173.61,7749.48,6544.12,7961.09
18,8173.61,7749.48,6544.12,7961.09
19,8173.61,7749.48,6544.12,7961.09
20,8173.61,7749.48,6544.12,7961.09
21,8173.61,7749.48,6544.12,7961.09
22,8173.61,7749.48,6544.12,7961.09
23,8173.61,7749.48,6544.12,7961.09
24,8173.61,7749.48,6544.12,7961.09
25,8173.61,8851.65,6544.12,7961.09
26,8173.61,8851.65,6544.12,7961.09
27,8173.61,8851.65,6544.12,7961.09
28,8173.61,8851.65,6544.12,7961.09
29,8173.61,8851.65,6544.12,7961.09
30,8173.61,8851.65,6544.12,7961.09
31,8542.69,8851.65,6544.12,7961.09
32,8542.69,8851.65,6544.12,7961.09
33,8542.69,8851.65,6544.12,7961.09
34,8542.69,8851.65,6544.12,7961.09
35,8542.69,8851.65,6544.12,7961.09
36,8542.69,8851.65,6544.12,7961.09
37,8542.69,8851.65,6544.12,7961.09
38,8542.69,8851.65,6544.12,7961.09
39,8542.69,8851.65,6544.12,7961.09
40,8542.69,8851.65,7184.40,7961.09
41,8542.69,8851.65,7184.40,7961.09
42,8542.69,8851.65,7184.40,7961.09
43,8542.69,8851.65,7184.40,7961.09
44,8542.69,8851.65,7184.40,7961.09
45,8542.69,8851.65,7184.40,7961.09
46,8542.69,8851.65,7184.40,7961.09
47,8542.69,8851.65,7184.40,7961.09
48,8542.69,8851.65,7184.40,7961.09
49,8542.69,8851.65,7184.40,7961.09
50,8542.69,8851.65,7184.40,7961.09
51,8542.69,8851.65,7184.40,7961.09
52,8542.69,8893.27,7184.40,7961.09
53,8542.69,8893.27,7184.40,7961.09
54,8542.69,8893.27,7184.40,7961.09
55,8542.69,8893.27,7184.40,7961.09
56,8542.69,8893.27,7184.40,7961.09
57,8542.69,8893.27,7184.40,7961.09
58,8542.69,8893.27,7184.40,7961.09
59,8542.69,8893.27,7184.40,8190.44
60,8542.69,8893.27,7184.40,8190.44
61,8542.69,8893.27,7184.40,8190.44
62,8542.69,8893.27,7184.40,8190.44
63,8680.74,8893.27,7184.40,8190.44
64,8680.74,8893.27,7184.40,8190.44
65,8680.74,8934.64,7184.40,8190.44
66,8680.74,8934.64,7184.40,8190.44
67,8680.74,8934.64,7184.40,8190.44
68,8680.74,8934.64,7452.49,8190.44
69,8680.74,8934.64,7452.49,8190.44
70,8680.74,8934.64,7452.49,8190.44
71,8680.74,8934.64,7452.49,8190.44
72,8680.74,8934.64,7452.49,8190.44
73,8680.74,8934.64,7452.49,8190.44
74,8680.74,8934.64,7452.49,8190.44
75,8680.74,8934.64,7452.49,8190.44
76,8680.74,8934.64,7452.49,8190.44
77,8680.74,8934.64,7452.49,8190.44
78,8680.74,8934.64,7452.49,8190.44
79,8680.74,8934.64,7452.49,8190.44
80,8680.74,8934.64,7452.49,8190.44
81,8680.74,8934.64,7452.49,8190.44
82,8680.74,8934.64,7452.49,8190.44
83,8680.74,8934.64,7452.49,8190.44
84,8680.74,8934.64,7452.49,8190.44
85,8680.74,8934.64,7452.49,8190.44
86,8680.74,8934.64,7452.49,8190.44
87,8680.74,8934.64,7452.49,8272.52
88,8680.74,8934.64,7452.49,8272.52
89,8680.74,8934.64,7452.49,8272.52
90,8680.74,8934.64,7452.49,8272.52
91,8680.74,8934.64,7452.49,8272.52
92,8680.74,8934.64,7452.49,8272.52
93,8680.74,8934.64,7452.49,8272.52
94,8680.74,8934.64,7452.49,8272.52
95,8680.74,8934.64,7452.49,8272.52
96,8680.74,8934.64,7452.49,8272.52
97,8680.74,8934.64,7452.49,8272.52
98,8680.74,8934.64,7452.49,8272.52
99,8680.74,8934.64,7452.49,8272.52
100,8680.74,8934.64,7668.31,8272.52
101,8789.89,8934.64,7668.31,8272.52
102,8789.89,8934.64,7668.31,8272.52
103,8789.89,8934.64,7668.31,8272.52
104,8789.89,8934.64,7668.31,8272.52
105,8789.89,8934.64,7668.31,8272.52
106,8789.89,8934.64,7668.31,8272.52
107,8789.89,8934.64,7668.31,8272.52
108,8789.89,8934.64,7668.31,8272.52
109,8789.89,8934.64,7668.31,8272.52
110,8789.89,8934.64,7668.31,8272.52
111,8789.89,8934.64,7668.31,8272.52
112,8789.89,8934.64,7668.31,8272.52
113,8789.89,8996.62,7668.31,8272.52
114,8789.89,8996.62,7668.31,8272.52
115,8789.89,8996.62,7668.31,8325.48
116,8789.89,8996.62,7668.31,8325.48
117,8789.89,8996.62,7668.31,8325.48
118,8789.89,8996.62,7668.31,8325.48
119,8789.89,8996.62,7668.31,8325.48
120,8789.89,8996.62,7668.31,8325.48
121,8789.89,8996.62,7668.31,8325.48
122,8789.89,8996.62,7668.31,8325.48
123,8789.89,8996.62,7668.31,8325.48
124,8789.89,8996.62,7668.31,8325.48
125,8789.89,8996.62,7668.31,8325.48
126,8789.89,8996.62,7668.31,8325.48
127,8789.89,8996.62,7668.31,8325.48
128,8789.89,8996.62,7668.31,8325.48
129,8789.89,8996.62,7835.16,8325.48
130,8789.89,8996.62,7835.16,8325.48
131,8789.89,8996.62,7835.16,8325.48
132,8789.89,8996.62,7835.16,8325.48
133,8789.89,8996.62,7835.16,8325.48
134,8831.99,8996.62,7835.16,8325.48
135,8831.99,8996.62,7835.16,8325.48
136,8831.99,8996.62,7835.16,8325.48
137,8831.99,8996.62,7835.16,8325.48
138,8831.99,8996.62,7835.16,8325.48
139,8831.99,8996.62,7835.16,8325.48
140,8831.99,8996.62,7835.16,8325.48
141,8831.99,8996.62,7835.16,8325.48
142,8831.99,9037.64,7835.16,8325.48
143,8831.99,9037.64,7835.16,8391.95
144,8831.99,9037.64,7835.16,8391.95
145,8831.99,9037.64,7835.16,8391.95
146,8831.99,9037.64,7835.16,8391.95
147,8831.99,9037.64,7835.16,8391.95
148,8831.99,9037.64,7835.16,8391.95
149,8831.99,9037.64,7835.16,8391.95
150,8831.99,9037.64,7835.16,8391.95
151,8831.99,9037.64,7835.16,8391.95
152,8831.99,9037.64,7835.16,8391.95
153,8831.99,9037.64,7835.16,8391.95
154,8831.99,9037.64,7835.16,8391.95
155,8831.99,9037.64,7835.16,8391.95
156,8831.99,9037.64,7835.16,8391.95
157,8831.99,9037.64,7835.16,8391.95
158,8831.99,9037.64,7835.16,8391.95
159,8831.99,9037.64,7955.27,8391.95
160,8831.99,9037.64,7955.27,8391.95
161,8883.22,9037.64,7955.27,8391.95
162,8883.22,9037.64,7955.27,8391.95
163,8883.22,9037.64,7955.27,8391.95
164,8883.22,9037.64,7955.27,8391.95
165,8883.22,9037.64,7955.27,8391.95
166,8883.22,9037.64,7955.27,8391.95
167,8883.22,9037.64,7955.27,8391.95
168,8883.22,9037.64,7955.27,8391.95
169,8883.22,9120.65,7955.27,8391.95
170,8883.22,9120.65,7955.27,8391.95
171,8883.22,9120.65,7955.27,8435.11
172,8883.22,9120.65,7955.27,8435.11
173,8883.22,9120.65,7955.27,8435.11
174,8883.22,9120.65,7955.27,8435.11
175,8883.22,9120.65,7955.27,8435.11
176,8883.22,9120.65,7955.27,8435.11
177,8883.22,9120.65,7955.27,8435.11
178,8883.22,9120.65,7955.27,8435.11
179,8883.22,9120.65,7955.27,8435.11
180,8883.22,9120.65,7955.27,8435.11
181,8883.22,9120.65,7955.27,8435.11
182,8883.22,9120.65,7955.27,8435.11
183,8883.22,9120.65,7955.27,8435.11
184,8883.22,9120.65,7955.27,8435.11
185,8883.22,9120.65,7955.27,8435.11
186,8883.22,9120.65,7955.27,8435.11
187,8883.22,9120.65,7955.27,8435.11
188,8883.22,9120.65,8042.63,8435.11
189,8883.22,9120.65,8042.63,8435.11
190,8883.22,9120.65,8042.63,8435.11
191,8931.86,9120.65,8042.63,8435.11
192,8931.86,9120.65,8042.63,8435.11
193,8931.86,9120.65,8042.63,8435.11
194,8931.86,9120.65,8042.63,8435.11
195,8931.86,9120.65,8042.63,8435.11
196,8931.86,9120.65,8042.63,8435.11
197,8931.86,9120.65,8042.63,8435.11
198,8931.86,9120.65,8042.63,8435.11
199,8931.86,9120.65,8042.63,8435.11
200,8931.86,9120.65,8042.63,8435.11
201,8931.86,9120.65,8042.63,8476.10
202,8931.86,9120.65,8042.63,8476.10
203,8931.86,9191.12,8042.63,8476.10
204,8931.86,9191.12,8042.63,8476.10
205,8931.86,9191.12,8042.63,8476.10
206,8931.86,9191.12,8042.63,8476.10
207,8931.86,9191.12,8042.63,8476.10
208,8966.49,9191.12,8042.63,8476.10
209,8966.49,9191.12,8042.63,8476.10
210,8966.49,9191.12,8042.63,8476.10
211,8966.49,9191.12,8042.63,8476.10
212,8966.49,9191.12,8042.63,8476.10
213,8966.49,9191.12,8042.63,8476.10
214,8966.49,9191.12,8042.63,8476.10
215,8966.49,9191.12,8113.54,8476.10
216,8966.49,9191.12,8113.54,8476.10
217,8966.49,9191.12,8113.54,8476.10
218,8966.49,9191.12,8113.54,8476.10
219,8966.49,9191.12,8113.54,8476.10
220,8966.49,9191.12,8113.54,8476.10
221,8966.49,9191.12,8113.54,8476.10
222,8966.49,9191.12,8113.54,8476.10
223,8966.49,9191.12,8113.54,8476.10
224,8966.49,9191.12,8113.54,8476.10
225,8966.49,9191.12,8113.54,8476.10
226,8966.49,9191.12,8113.54,8476.10
227,8966.49,9191.12,8113.54,8523.05
228,8966.49,9191.12,8113.54,8523.05
229,8966.49,9191.12,8113.54,8523.05
230,8966.49,9211.88,8113.54,8523.05
231,8966.49,9211.88,8113.54,8523.05
232,8966.49,9211.88,8113.54,8523.05
233,8966.49,9211.88,8113.54,8523.05
234,8966.49,9211.88,8113.54,8523.05
235,8966.49,9211.88,8113.54,8523.05
236,8966.49,9211.88,8113.54,8523.05
237,8966.49,9211.88,8113.54,8523.05
238,8966.49,9211.88,8113.54,8523.05
239,8966.49,9211.88,8113.54,8523.05
240,8966.49,9211.88,8113.54,8523.05
241,8966.49,9211.88,8113.54,8523.05
242,8966.49,9211.88,8113.54,8523.05
243,8966.49,9211.88,8113.54,8523.05
244,9010.30,9211.88,8113.54,8523.05
245,9010.30,9211.88,8189.94,8523.05
246,9010.30,9211.88,8189.94,8523.05
247,9010.30,9211.88,8189.94,8523.05
248,9010.30,9211.88,8189.94,8523.05
249,9010.30,9211.88,8189.94,8523.05
250,9010.30,9211.88,8189.94,8523.05
251,9010.30,9211.88,8189.94,8523.05
252,9010.30,9211.88,8189.94,8523.05
253,9010.30,9211.88,8189.94,8523.05
254,9010.30,9211.88,8189.94,8523.05
255,9010.30,9211.88,8189.94,8523.05
256,9010.30,9211.88,8189.94,8523.05
257,9010.30,9211.88,8189.94,8586.28
258,9010.30,9211.88,8189.94,8586.28
259,9010.30,9242.23,8189.94,8586.28
260,9010.30,9242.23,8189.94,8586.28
261,9010.30,9242.23,8189.94,8586.28
262,9010.30,9242.23,8189.94,8586.28
263,9010.30,9242.23,8189.94,8586.28
264,9010.30,9242.23,8189.94,8586.28
265,9010.30,9242.23,8189.94,8586.28
266,9010.30,9242.23,8189.94,8586.28
267,9046.55,9242.23,8189.94,8586.28
268,9046.55,9242.23,8189.94,8586.28
269,9046.55,9242.23,8189.94,8586.28
270,9046.55,9242.23,8189.94,8586.28
271,9046.55,9242.23,8189.94,8586.28
272,9046.55,9242.23,8189.94,8586.28
273,9046.55,9242.23,8245.21,8586.28
274,9046.55,9242.23,8245.21,8586.28
275,9046.55,9242.23,8245.21,8586.28
276,9046.55,9242.23,8245.21,8586.28
277,9046.55,9242.23,8245.21,8586.28
278,9046.55,9242.23,8245.21,8586.28
279,9046.55,9242.23,8245.21,8586.28
280,9046.55,9242.23,8245.21,8586.28
281,9046.55,9242.23,8245.21,8586.28
282,9046.55,9242.23,8245.21,8586.28
283,9046.55,9242.23,8245.21,8586.28
284,9046.55,9242.23,8245.21,8586.28
285,9046.55,9242.23,8245.21,8586.28
286,9046.55,9242.23,8245.21,8586.28
287,9046.55,9242.23,8245.21,8586.28
288,9046.55,9276.96,8245.21,8586.28
289,9046.55,9276.96,8245.21,8586.28
290,9046.55,9276.96,8245.21,8636.79
291,9046.55,9276.96,8245.21,8636.79
292,9046.55,9276.96,8245.21,8636.79
293,9046.55,9276.96,8245.21,8636.79
294,9046.55,9276.96,8245.21,8636.79
295,9046.55,9276.96,8245.21,8636.79
296,9046.55,9276.96,8245.21,8636.79
297,9046.55,9276.96,8245.21,8636.79
298,9046.55,9276.96,8245.21,8636.79
299,9046.55,9276.96,8245.21,8636.79
300,9046.55,9276.96,8245.21,8636.79
301,9089.99,9276.96,8245.21,8636.79
302,9089.99,9276.96,8245.21,8636.79
303,9089.99,9276.96,8245.21,8636.79
304,9089.99,NaN,7121.30,8636.79
code,1776751747,1776751747,1776751747,1776751747
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
experiment_run,1,1,2,2
client,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1398.00,1398.00,1398.00,1398.00
time_ingest,663.00,663.00,663.00,663.00
time_check,735.00,735.00,735.00,735.00
terminals,1,1,1,1
pods,1,2,1,2
tenant,,,,
num_worker,0,0,0,0
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,4307,4533,4705,4805
host_RAM,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,
host_Cores,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247605,247606,247607,247607
host_datadisk,4307,4533,4705,4805
host_volume_size,100G,100G,100G,100G
host_volume_used,4.3G,4.3G,4.6G,4.6G
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,16,16,16,16
loading_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc
loading_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres
loading_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres
loading_parameters_BENCHBASE_TERMINALS,1,1,1,1
loading_parameters_BENCHBASE_TIME,300,300,300,300
loading_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
loading_parameters_BENCHBASE_BATCHSIZE,128,128,128,128
loading_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0
loading_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false
loading_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false
loading_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a
loading_parameters_BEXHOMA_TENANT_BY,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
benchmarking_parameters_SF,16,16,16,16
benchmarking_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc
benchmarking_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres
benchmarking_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres
benchmarking_parameters_BENCHBASE_TARGET,16384,8192,16384,8192
benchmarking_parameters_BENCHBASE_TERMINALS,160,80,160,80
benchmarking_parameters_BENCHBASE_TIME,300,300,300,300
benchmarking_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
benchmarking_parameters_BENCHBASE_BATCHSIZE,128,128,128,128
benchmarking_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0
benchmarking_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false
benchmarking_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false
benchmarking_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [20]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head().T

phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2
code,1776751747,1776751747,1776751747,1776751747
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
experiment_run,1,1,2,2
client,1,2,1,2
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False

# Time Series of a Single Metric for All Experiments

This is particularly important if you require a customized aggregation or wish to monitor a component over time.
Data is stacked here (long format).

In [21]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_all(metric=metric)
df.head()

,timestamp,code,phase,experiment_run,client,type_tenants,vol_tenants,num_tenants,metric,component,value
0,0,1776751747,1776751747-PostgreSQL-1-1-1024-1-1,1,1,,False,0,total_cpu_memory,stream,7537.76
1,0,1776751747,1776751747-PostgreSQL-1-1-1024-1-2,1,2,,False,0,total_cpu_memory,stream,15498.96
2,0,1776751747,1776751747-PostgreSQL-1-1-1024-2-1,2,1,,False,0,total_cpu_memory,stream,7922.79
3,0,1776751747,1776751747-PostgreSQL-1-1-1024-2-2,2,2,,False,0,total_cpu_memory,stream,13991.53
4,0,1776754749,1776754749-PostgreSQL-1-1-1024-1-1,1,1,,False,0,total_cpu_memory,stream,30088.42

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [22]:
df[['timestamp', 'phase', 'value']].head(8)

   timestamp                               phase    value
0          0  1776751747-PostgreSQL-1-1-1024-1-1  7537.76
1          0  1776751747-PostgreSQL-1-1-1024-1-2 15498.96
2          0  1776751747-PostgreSQL-1-1-1024-2-1  7922.79
3          0  1776751747-PostgreSQL-1-1-1024-2-2 13991.53
4          0  1776754749-PostgreSQL-1-1-1024-1-1 30088.42
5          0  1776754749-PostgreSQL-1-1-1024-1-2 61934.56
6          0  1776754749-PostgreSQL-1-1-1024-2-1 31616.09
7          0  1776754749-PostgreSQL-1-1-1024-2-2 56050.78

## With Metadata

Connection infos are added.

In [23]:
df=collect.add_metadata(df)
df = df.sort_values(['timestamp', 'phase'])
df[['timestamp', 'phase', 'value']].head(8)

combine on columns phase

,timestamp,phase,value
1776751747-PostgreSQL-1-1-1024-1-1,0,1776751747-PostgreSQL-1-1-1024-1-1,7537.76
1776751747-PostgreSQL-1-1-1024-1-2,0,1776751747-PostgreSQL-1-1-1024-1-2,15498.96
1776751747-PostgreSQL-1-1-1024-2-1,0,1776751747-PostgreSQL-1-1-1024-2-1,7922.79
1776751747-PostgreSQL-1-1-1024-2-2,0,1776751747-PostgreSQL-1-1-1024-2-2,13991.53
1776754749-PostgreSQL-1-1-1024-1-1,0,1776754749-PostgreSQL-1-1-1024-1-1,30088.42
1776754749-PostgreSQL-1-1-1024-1-2,0,1776754749-PostgreSQL-1-1-1024-1-2,61934.56
1776754749-PostgreSQL-1-1-1024-2-1,0,1776754749-PostgreSQL-1-1-1024-2-1,31616.09
1776754749-PostgreSQL-1-1-1024-2-2,0,1776754749-PostgreSQL-1-1-1024-2-2,56050.78

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [24]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head().T

,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1
code,1776751747,1776751747,1776751747,1776751747,1776754749
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
experiment_run,1,1,2,2,1
client,1,2,1,2,1
type_tenants,,,,,
num_tenants,0,0,0,0,0
vol_tenants,False,False,False,False,False

## Custom Aggregation and Scale

We here aggregate CPU utilization by max per phase.

In [25]:
metric = 'total_cpu_util'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["code", "experiment_run", "client", "type_tenants", "num_tenants"])["value"]
      .max()
      .reset_index()
)
df_agg.index.name = 'Max ' + collect.df_metrics.loc[metric]['title']
df_agg

,code,experiment_run,client,type_tenants,num_tenants,value
Max CPU Utilization,,,,,,
0,1776751747,1,1,,0,2.82
1,1776751747,1,2,,0,7.68
2,1776751747,2,1,,0,2.12
3,1776751747,2,2,,0,4.48
4,1776754749,1,1,,0,10.81
5,1776754749,1,2,,0,20.32
6,1776754749,2,1,,0,8.04
7,1776754749,2,2,,0,22.14

# Performance Results per Connection

In [26]:
df_performance = collect.get_performance_per_connection()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

connection,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-8,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-2
connection,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-8,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-2
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2
configuration,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024
experiment_run,1,1,1,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2
code,1776751747,1776751747,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749
client,1,2,2,1,2,2,1,1,1,1,2,2,2,2,2,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2
pod,zmmgn.dbmsbenchmarker,pncb9.dbmsbenchmarker,6zrm4.dbmsbenchmarker,5vn87.dbmsbenchmarker,qb2f9.dbmsbenchmarker,wjjml.dbmsbenchmarker,8zz68.dbmsbenchmarker,f7tks.dbmsbenchmarker,bcrbc.dbmsbenchmarker,xbnnt.dbmsbenchmarker,qv746.dbmsbenchmarker,d4sdz.dbmsbenchmarker,qsftx.dbmsbenchmarker,j9nx4.dbmsbenchmarker,4szv9.dbmsbenchmarker,465hm.dbmsbenchmarker,z2np2.dbmsbenchmarker,wv7j8.dbmsbenchmarker,bsnqp.dbmsbenchmarker,nfzqs.dbmsbenchmarker,2l4c2.dbmsbenchmarker,vhzpd.dbmsbenchmarker,k87wj.dbmsbenchmarker,79l8s.dbmsbenchmarker,ctmvn.dbmsbenchmarker,s27nk.dbmsbenchmarker,n98xv.dbmsbenchmarker,mzss8.dbmsbenchmarker,569h7.dbmsbenchmarker,sf8bd.dbmsbenchmarker
pod_count,1,2,2,1,2,2,4,4,4,4,8,8,8,8,8,8,8,8,4,4,4,4,8,8,8,8,8,8,8,8
bench,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
profile,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
target,16384,8192,8192,16384,8192,8192,5120,5120,5120,5120,2560,2560,2560,2560,2560,2560,2560,2560,5120,5120,5120,5120,2560,2560,2560,2560,2560,2560,2560,2560
time,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300
batchsize,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
sf,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
num_errors,3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
duration,304,303,304,304,305,303,307,309,309,308,306,308,304,306,308,307,304,307,303,304,305,303,307,306,307,305,304,304,306,308
efficiency,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
child,1,2,1,1,1,2,4,1,2,3,5,1,8,6,2,4,7,3,4,2,1,3,1,4,3,6,8,7,5,2
Start timestamp (milliseconds),1776752912589,1776753292833,1776753293242,1776753934116,1776754307372,1776754307031,1776755750319,1776755750399,1776755751125,1776755750709,1776756138348,1776756138836,1776756138201,1776756139042,1776756138424,1776756138747,1776756138632,1776756139173,1776756771602,1776756771743,1776756771617,1776756771603,1776757152451,1776757152323,1776757152711,1776757152721,1776757151897,1776757152292,1776757151930,1776757152024
Current Timestamp (milliseconds),1776753214394,1776753594085,1776753594039,1776754235688,1776754608812,1776754608701,1776756055977,1776756056025,1776756055950,1776756056032,1776756440960,1776756440195,1776756441732,1776756441686,1776756440977,1776756441424,1776756440316,1776756440408,1776757072540,1776757072500,1776757072429,1776757072426,1776757453592,1776757454618,1776757454443,1776757454314,1776757454434,1776757453952,1776757454465,1776757454100
Elapsed Time (nanoseconds),300000084462,300000098761,300000084273,300000000050,300000095208,300000098177,300000044409,300000059452,300000124099,300000017465,300000015614,300000366913,300000210988,300000264511,300000215878,300000041094,300000057946,300000201801,300000081107,300000031724,300000161663,300000058805,300000326874,300000012848,300000052997,300000049542,300000009449,300000356635,300000356093,300000094543
DBMS Type,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES
DBMS Version,"PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit"
Benchmark Type,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
Final State,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT
Measured Requests,146396,76744,76619,98751,61644,61378,32674,32608,32690,31993,14651,14460,14434,14021,14561,14523,14388,14283,23759,23889,24050,23928,17359,17263,17033,16923,17195,16985,17415,16978
isolation,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
scalefactor,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
terminals,160,80,80,160,80,80,40,40,40,40,20,20,20,20,20,20,20,20,40,40,40,40,20,20,20,20,20,20,20,20
Throughput (requests/second),487.99,255.81,255.40,329.17,205.48,204.59,108.91,108.69,108.97,106.64,48.84,48.20,48.11,46.74,48.54,48.41,47.96,47.61,79.20,79.63,80.17,79.76,57.86,57.54,56.78,56.41,57.32,56.62,58.05,56.59
Goodput (requests/second),484.77,254.08,253.68,327.30,204.10,203.30,108.25,107.97,108.13,105.98,48.51,47.92,47.82,46.41,48.17,48.11,47.67,47.32,78.76,79.16,79.81,79.32,57.49,57.09,56.48,56.00,56.92,56.24,57.65,56.14
Latency Distribution.95th Percentile Latency (microseconds),1525016,1410180,1399302,2213256,1769770,1767073,1687690,1744733,1663818,1745407,1850373,1817576,1890551,1938737,1889149,1881100,1895723,1916724,2311261,2281057,2299240,2301616,1546193,1514894,1581547,1520573,1547466,1541436,1532749,1538641
Latency Distribution.Maximum Latency (microseconds),12658448,20924125,17716931,16704195,16955683,16873933,22946799,21015010,17460033,19491246,18383649,25171236,23257254,25004249,32359012,20704272,28256913,22560733,13873133,15093002,16937122,13080539,16884120,26271676,19424046,18160957,16642128,15613199,17725900,14833227
Latency Distribution.Median Latency (microseconds),87888,77947,79487,146452,107383,108624,83503,83578,83417,83214,94951,91894,98213,96841,93101,91744,98316,93075,150691,150613,150507,155320,100101,100206,100238,103002,99942,100704,99915,103187
Latency Distribution.Minimum Latency (microseconds),620,588,641,686,591,624,683,606,719,655,687,726,621,677,809,708,675,722,609,693,771,635,772,778,685,842,758,747,766,812
Latency Distribution.25th Percentile Latency (microseconds),20601,18079,18439,38987,24048,24429,19709,20122,19497,19692,21976,21684,21887,21827,21820,22125,21930,22014,44185,44991,44131,45035,27396,27399,28043,27319,27357,27434,27507,27938
Latency Distribution.90th Percentile Latency (microseconds),884978,757162,782058,1300505,1002223,1011431,886756,873776,882716,908741,974029,974578,1006388,1025968,996686,974958,1017138,981110,1363231,1391606,1327206,1374022,826020,808413,850151,843926,842239,863463,847324,846470
Latency Distribution.99th Percentile Latency (microseconds),3425072,3669430,3635790,4862448,4195339,4193729,4395322,4368371,4545985,4609206,5074990,5353240,5001030,5242641,5007377,5077944,4814424,5120596,4764407,4687582,4780131,4726130,3876979,4064254,4018849,4119629,3793690,3975885,3820294,3990272
Latency Distribution.75th Percentile Latency (microseconds),289952,258583,259652,456532,353113,360779,298358,291496,292339,287137,333401,321922,335189,335676,324631,331742,336650,341667,488669,485162,483828,488852,292701,292791,297053,301651,296359,300317,292599,315419
Latency Distribution.Average Latency (microseconds),327420,312391,313005,484163,388228,390500,365861,366002,365574,372692,409045,414014,414449,426981,410942,412434,416147,419198,503800,501793,498261,500717,344360,346056,350617,353591,347151,351194,343332,351765

## With Metadata

Connection infos are added.

In [27]:
df = collect.add_metadata(df_performance)
df.T

combine on index

,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-8,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-2
connection,1776751747-PostgreSQL-1-1-1024-1-1-1,1776751747-PostgreSQL-1-1-1024-1-2-2,1776751747-PostgreSQL-1-1-1024-1-2-1,1776751747-PostgreSQL-1-1-1024-2-1-1,1776751747-PostgreSQL-1-1-1024-2-2-1,1776751747-PostgreSQL-1-1-1024-2-2-2,1776754749-PostgreSQL-1-1-1024-1-1-4,1776754749-PostgreSQL-1-1-1024-1-1-1,1776754749-PostgreSQL-1-1-1024-1-1-2,1776754749-PostgreSQL-1-1-1024-1-1-3,1776754749-PostgreSQL-1-1-1024-1-2-5,1776754749-PostgreSQL-1-1-1024-1-2-1,1776754749-PostgreSQL-1-1-1024-1-2-8,1776754749-PostgreSQL-1-1-1024-1-2-6,1776754749-PostgreSQL-1-1-1024-1-2-2,1776754749-PostgreSQL-1-1-1024-1-2-4,1776754749-PostgreSQL-1-1-1024-1-2-7,1776754749-PostgreSQL-1-1-1024-1-2-3,1776754749-PostgreSQL-1-1-1024-2-1-4,1776754749-PostgreSQL-1-1-1024-2-1-2,1776754749-PostgreSQL-1-1-1024-2-1-1,1776754749-PostgreSQL-1-1-1024-2-1-3,1776754749-PostgreSQL-1-1-1024-2-2-1,1776754749-PostgreSQL-1-1-1024-2-2-4,1776754749-PostgreSQL-1-1-1024-2-2-3,1776754749-PostgreSQL-1-1-1024-2-2-6,1776754749-PostgreSQL-1-1-1024-2-2-8,1776754749-PostgreSQL-1-1-1024-2-2-7,1776754749-PostgreSQL-1-1-1024-2-2-5,1776754749-PostgreSQL-1-1-1024-2-2-2
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-2-2
configuration,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024
experiment_run,1,1,1,2,2,2,1,1,1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2
code,1776751747,1776751747,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749,1776754749
client,1,2,2,1,2,2,1,1,1,1,2,2,2,2,2,2,2,2,1,1,1,1,2,2,2,2,2,2,2,2
pod,zmmgn.dbmsbenchmarker,pncb9.dbmsbenchmarker,6zrm4.dbmsbenchmarker,5vn87.dbmsbenchmarker,qb2f9.dbmsbenchmarker,wjjml.dbmsbenchmarker,8zz68.dbmsbenchmarker,f7tks.dbmsbenchmarker,bcrbc.dbmsbenchmarker,xbnnt.dbmsbenchmarker,qv746.dbmsbenchmarker,d4sdz.dbmsbenchmarker,qsftx.dbmsbenchmarker,j9nx4.dbmsbenchmarker,4szv9.dbmsbenchmarker,465hm.dbmsbenchmarker,z2np2.dbmsbenchmarker,wv7j8.dbmsbenchmarker,bsnqp.dbmsbenchmarker,nfzqs.dbmsbenchmarker,2l4c2.dbmsbenchmarker,vhzpd.dbmsbenchmarker,k87wj.dbmsbenchmarker,79l8s.dbmsbenchmarker,ctmvn.dbmsbenchmarker,s27nk.dbmsbenchmarker,n98xv.dbmsbenchmarker,mzss8.dbmsbenchmarker,569h7.dbmsbenchmarker,sf8bd.dbmsbenchmarker
pod_count,1,2,2,1,2,2,4,4,4,4,8,8,8,8,8,8,8,8,4,4,4,4,8,8,8,8,8,8,8,8
bench,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
profile,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
target,16384,8192,8192,16384,8192,8192,5120,5120,5120,5120,2560,2560,2560,2560,2560,2560,2560,2560,5120,5120,5120,5120,2560,2560,2560,2560,2560,2560,2560,2560
time,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300,300
batchsize,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
sf,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
num_errors,3,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
duration,304,303,304,304,305,303,307,309,309,308,306,308,304,306,308,307,304,307,303,304,305,303,307,306,307,305,304,304,306,308
efficiency,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
child,1,2,1,1,1,2,4,1,2,3,5,1,8,6,2,4,7,3,4,2,1,3,1,4,3,6,8,7,5,2
Start timestamp (milliseconds),1776752912589,1776753292833,1776753293242,1776753934116,1776754307372,1776754307031,1776755750319,1776755750399,1776755751125,1776755750709,1776756138348,1776756138836,1776756138201,1776756139042,1776756138424,1776756138747,1776756138632,1776756139173,1776756771602,1776756771743,1776756771617,1776756771603,1776757152451,1776757152323,1776757152711,1776757152721,1776757151897,1776757152292,1776757151930,1776757152024
Current Timestamp (milliseconds),1776753214394,1776753594085,1776753594039,1776754235688,1776754608812,1776754608701,1776756055977,1776756056025,1776756055950,1776756056032,1776756440960,1776756440195,1776756441732,1776756441686,1776756440977,1776756441424,1776756440316,1776756440408,1776757072540,1776757072500,1776757072429,1776757072426,1776757453592,1776757454618,1776757454443,1776757454314,1776757454434,1776757453952,1776757454465,1776757454100
Elapsed Time (nanoseconds),300000084462,300000098761,300000084273,300000000050,300000095208,300000098177,300000044409,300000059452,300000124099,300000017465,300000015614,300000366913,300000210988,300000264511,300000215878,300000041094,300000057946,300000201801,300000081107,300000031724,300000161663,300000058805,300000326874,300000012848,300000052997,300000049542,300000009449,300000356635,300000356093,300000094543
DBMS Type,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES
DBMS Version,"PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit"
Benchmark Type,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
Final State,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT,EXIT
Measured Requests,146396,76744,76619,98751,61644,61378,32674,32608,32690,31993,14651,14460,14434,14021,14561,14523,14388,14283,23759,23889,24050,23928,17359,17263,17033,16923,17195,16985,17415,16978
isolation,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
scalefactor,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
terminals,160,80,80,160,80,80,40,40,40,40,20,20,20,20,20,20,20,20,40,40,40,40,20,20,20,20,20,20,20,20
Throughput (requests/second),487.99,255.81,255.40,329.17,205.48,204.59,108.91,108.69,108.97,106.64,48.84,48.20,48.11,46.74,48.54,48.41,47.96,47.61,79.20,79.63,80.17,79.76,57.86,57.54,56.78,56.41,57.32,56.62,58.05,56.59
Goodput (requests/second),484.77,254.08,253.68,327.30,204.10,203.30,108.25,107.97,108.13,105.98,48.51,47.92,47.82,46.41,48.17,48.11,47.67,47.32,78.76,79.16,79.81,79.32,57.49,57.09,56.48,56.00,56.92,56.24,57.65,56.14
Latency Distribution.95th Percentile Latency (microseconds),1525016,1410180,1399302,2213256,1769770,1767073,1687690,1744733,1663818,1745407,1850373,1817576,1890551,1938737,1889149,1881100,1895723,1916724,2311261,2281057,2299240,2301616,1546193,1514894,1581547,1520573,1547466,1541436,1532749,1538641
Latency Distribution.Maximum Latency (microseconds),12658448,20924125,17716931,16704195,16955683,16873933,22946799,21015010,17460033,19491246,18383649,25171236,23257254,25004249,32359012,20704272,28256913,22560733,13873133,15093002,16937122,13080539,16884120,26271676,19424046,18160957,16642128,15613199,17725900,14833227
Latency Distribution.Median Latency (microseconds),87888,77947,79487,146452,107383,108624,83503,83578,83417,83214,94951,91894,98213,96841,93101,91744,98316,93075,150691,150613,150507,155320,100101,100206,100238,103002,99942,100704,99915,103187
Latency Distribution.Minimum Latency (microseconds),620,588,641,686,591,624,683,606,719,655,687,726,621,677,809,708,675,722,609,693,771,635,772,778,685,842,758,747,766,812
Latency Distribution.25th Percentile Latency (microseconds),20601,18079,18439,38987,24048,24429,19709,20122,19497,19692,21976,21684,21887,21827,21820,22125,21930,22014,44185,44991,44131,45035,27396,27399,28043,27319,27357,27434,27507,27938
Latency Distribution.90th Percentile Latency (microseconds),884978,757162,782058,1300505,1002223,1011431,886756,873776,882716,908741,974029,974578,1006388,1025968,996686,974958,1017138,981110,1363231,1391606,1327206,1374022,826020,808413,850151,843926,842239,863463,847324,846470
Latency Distribution.99th Percentile Latency (microseconds),3425072,3669430,3635790,4862448,4195339,4193729,4395322,4368371,4545985,4609206,5074990,5353240,5001030,5242641,5007377,5077944,4814424,5120596,4764407,4687582,4780131,4726130,3876979,4064254,4018849,4119629,3793690,3975885,3820294,3990272
Latency Distribution.75th Percentile Latency (microseconds),289952,258583,259652,456532,353113,360779,298358,291496,292339,287137,333401,321922,335189,335676,324631,331742,336650,341667,488669,485162,483828,488852,292701,292791,297053,301651,296359,300317,292599,315419
Latency Distribution.Average Latency (microseconds),327420,312391,313005,484163,388228,390500,365861,366002,365574,372692,409045,414014,414449,426981,410942,412434,416147,419198,503800,501793,498261,500717,344360,346056,350617,353591,347151,351194,343332,351765
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1398.00,1398.00,1398.00,1398.00,1398.00,1398.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00,1481.00
time_ingest,663.00,663.00,663.00,663.00,663.00,663.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00,716.00
time_check,735.00,735.00,735.00,735.00,735.00,735.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00,765.00
pods,1,2,2,1,2,2,4,4,4,4,8,8,8,8,8,8,8,8,4,4,4,4,8,8,8,8,8,8,8,8
tenant,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,4307,4533,4533,4705,4805,4805,4307,4307,4307,4307,4525,4525,4525,4525,4525,4525,4525,4525,4686,4686,4686,4686,4794,4794,4794,4794,4794,4794,4794,4794
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128

# Performance Results per Phase

In [28]:
df_performance = collect.get_performance_aggregated_per_phase()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)

In [29]:
df_performance.T

,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2
configuration,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
code,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749
pod_count,1,2,1,2,4,8,4,8
duration,304,304,304,305,309,308,305,308
bench,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
profile,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
target,16384,16384,16384,16384,20480,20480,20480,20480
time,300.00,300.00,300.00,300.00,300.00,300.00,300.00,300.00
batchsize,128.00,128.00,128.00,128.00,128.00,128.00,128.00,128.00
sf,16,16,16,16,16,16,16,16
num_errors,3,0,0,0,1,0,0,0
scalefactor,16,16,16,16,16,16,16,16
Current Timestamp (milliseconds),1776753214394,1776753594085,1776754235688,1776754608812,1776756056032,1776756441732,1776757072540,1776757454618
Benchmark Type,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
isolation,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
DBMS Version,"PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit"
Goodput (requests/second),484.77,507.76,327.30,407.39,430.34,381.94,317.05,454.01
terminals,160,160,160,160,160,160,160,160
DBMS Type,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES
Throughput (requests/second),487.99,511.21,329.17,410.07,433.22,384.40,318.75,457.17
Latency Distribution.95th Percentile Latency (microseconds),1525016.00,1410180.00,2213256.00,1769770.00,1745407.00,1938737.00,2311261.00,1581547.00
Latency Distribution.Maximum Latency (microseconds),12658448.00,20924125.00,16704195.00,16955683.00,22946799.00,32359012.00,16937122.00,26271676.00
Latency Distribution.Median Latency (microseconds),87888.00,79487.00,146452.00,108624.00,83578.00,98316.00,155320.00,103187.00
Latency Distribution.Minimum Latency (microseconds),620.00,588.00,686.00,591.00,606.00,621.00,609.00,685.00
Latency Distribution.25th Percentile Latency (microseconds),20601.00,18439.00,38987.00,24429.00,20122.00,22125.00,45035.00,28043.00
Latency Distribution.90th Percentile Latency (microseconds),884978.00,782058.00,1300505.00,1011431.00,908741.00,1025968.00,1391606.00,863463.00
Latency Distribution.99th Percentile Latency (microseconds),3425072.00,3669430.00,4862448.00,4195339.00,4609206.00,5353240.00,4780131.00,4119629.00
Latency Distribution.75th Percentile Latency (microseconds),289952.00,259652.00,456532.00,360779.00,298358.00,341667.00,488852.00,315419.00
Latency Distribution.Average Latency (microseconds),327420.00,312698.00,484163.00,389364.00,367532.25,415401.25,501142.75,348508.25
efficiency,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
child,1,2,1,2,4,8,4,8

## With Metadata

Connection infos are added.

In [30]:
df = collect.add_metadata(df_performance)
df.T

combine on index and column 'phase'

phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2
configuration,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
code,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749
pod_count,1,2,1,2,4,8,4,8
duration,304,304,304,305,309,308,305,308
bench,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
profile,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
target,16384,16384,16384,16384,20480,20480,20480,20480
time,300.00,300.00,300.00,300.00,300.00,300.00,300.00,300.00
batchsize,128.00,128.00,128.00,128.00,128.00,128.00,128.00,128.00
sf,16,16,16,16,16,16,16,16
num_errors,3,0,0,0,1,0,0,0
scalefactor,16,16,16,16,16,16,16,16
Current Timestamp (milliseconds),1776753214394,1776753594085,1776754235688,1776754608812,1776756056032,1776756441732,1776757072540,1776757454618
Benchmark Type,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
isolation,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
DBMS Version,"PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit"
Goodput (requests/second),484.77,507.76,327.30,407.39,430.34,381.94,317.05,454.01
terminals,160,160,160,160,160,160,160,160
DBMS Type,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES,POSTGRES
Throughput (requests/second),487.99,511.21,329.17,410.07,433.22,384.40,318.75,457.17
Latency Distribution.95th Percentile Latency (microseconds),1525016.00,1410180.00,2213256.00,1769770.00,1745407.00,1938737.00,2311261.00,1581547.00
Latency Distribution.Maximum Latency (microseconds),12658448.00,20924125.00,16704195.00,16955683.00,22946799.00,32359012.00,16937122.00,26271676.00
Latency Distribution.Median Latency (microseconds),87888.00,79487.00,146452.00,108624.00,83578.00,98316.00,155320.00,103187.00
Latency Distribution.Minimum Latency (microseconds),620.00,588.00,686.00,591.00,606.00,621.00,609.00,685.00
Latency Distribution.25th Percentile Latency (microseconds),20601.00,18439.00,38987.00,24429.00,20122.00,22125.00,45035.00,28043.00
Latency Distribution.90th Percentile Latency (microseconds),884978.00,782058.00,1300505.00,1011431.00,908741.00,1025968.00,1391606.00,863463.00
Latency Distribution.99th Percentile Latency (microseconds),3425072.00,3669430.00,4862448.00,4195339.00,4609206.00,5353240.00,4780131.00,4119629.00
Latency Distribution.75th Percentile Latency (microseconds),289952.00,259652.00,456532.00,360779.00,298358.00,341667.00,488852.00,315419.00
Latency Distribution.Average Latency (microseconds),327420.00,312698.00,484163.00,389364.00,367532.25,415401.25,501142.75,348508.25
efficiency,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
child,1,2,1,2,4,8,4,8
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1398.00,1398.00,1398.00,1398.00,1481.00,1481.00,1481.00,1481.00
time_ingest,663.00,663.00,663.00,663.00,716.00,716.00,716.00,716.00
time_check,735.00,735.00,735.00,735.00,765.00,765.00,765.00,765.00
pods,1,2,1,2,4,8,4,8
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,4307,4533,4705,4805,4307,4525,4686,4794
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247605,247606,247607,247607,247609,247610,247611,247611
host_datadisk,4307,4533,4705,4805,4307,4525,4686,4794
host_volume_size,100G,100G,100G,100G,100G,100G,100G,100G
host_volume_used,4.3G,4.3G,4.6G,4.6G,4.3G,4.3G,4.6G,4.6G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,16,16,16,16,16,16,16,16
loading_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
loading_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
loading_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
loading_parameters_BENCHBASE_TERMINALS,1,1,1,1,1,1,1,1
loading_parameters_BENCHBASE_TIME,300,300,300,300,300,300,300,300
loading_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
loading_parameters_BENCHBASE_BATCHSIZE,128,128,128,128,128,128,128,128
loading_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0,0,0,0,0
loading_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false,false,false,false,false
loading_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false,false,false,false,false
loading_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a,a,a,a,a
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,16,16,16,16,16,16,16,16
benchmarking_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc,tpcc
benchmarking_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
benchmarking_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres,postgres,postgres,postgres,postgres
benchmarking_parameters_BENCHBASE_TARGET,16384,8192,16384,8192,5120,2560,5120,2560
benchmarking_parameters_BENCHBASE_TERMINALS,160,80,160,80,40,20,40,20
benchmarking_parameters_BENCHBASE_TIME,300,300,300,300,300,300,300,300
benchmarking_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
benchmarking_parameters_BENCHBASE_BATCHSIZE,128,128,128,128,128,128,128,128
benchmarking_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0,0,0,0,0
benchmarking_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false,false,false,false,false
benchmarking_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false,false,false,false,false
benchmarking_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a,a,a,a,a
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776754749,bexhoma-sut-postgresql-1-1-1024-1776754749,bexhoma-sut-postgresql-1-1-1024-1776754749,bexhoma-sut-postgresql-1-1-1024-1776754749
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [31]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2
code,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749
configuration,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False

## Get Non-Constant Attributes

These attributes are (most probably) used to analyze performance.

In [32]:
collectors.get_non_constant(df).T

phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2
configuration,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
code,1776751747,1776751747,1776751747,1776751747,1776754749,1776754749,1776754749,1776754749
pod_count,1,2,1,2,4,8,4,8
duration,304,304,304,305,309,308,305,308
target,16384,16384,16384,16384,20480,20480,20480,20480
num_errors,3,0,0,0,1,0,0,0
Current Timestamp (milliseconds),1776753214394,1776753594085,1776754235688,1776754608812,1776756056032,1776756441732,1776757072540,1776757454618
Goodput (requests/second),484.77,507.76,327.30,407.39,430.34,381.94,317.05,454.01
Throughput (requests/second),487.99,511.21,329.17,410.07,433.22,384.40,318.75,457.17
Latency Distribution.95th Percentile Latency (microseconds),1525016.00,1410180.00,2213256.00,1769770.00,1745407.00,1938737.00,2311261.00,1581547.00
Latency Distribution.Maximum Latency (microseconds),12658448.00,20924125.00,16704195.00,16955683.00,22946799.00,32359012.00,16937122.00,26271676.00
Latency Distribution.Median Latency (microseconds),87888.00,79487.00,146452.00,108624.00,83578.00,98316.00,155320.00,103187.00
Latency Distribution.Minimum Latency (microseconds),620.00,588.00,686.00,591.00,606.00,621.00,609.00,685.00
Latency Distribution.25th Percentile Latency (microseconds),20601.00,18439.00,38987.00,24429.00,20122.00,22125.00,45035.00,28043.00
Latency Distribution.90th Percentile Latency (microseconds),884978.00,782058.00,1300505.00,1011431.00,908741.00,1025968.00,1391606.00,863463.00
Latency Distribution.99th Percentile Latency (microseconds),3425072.00,3669430.00,4862448.00,4195339.00,4609206.00,5353240.00,4780131.00,4119629.00
Latency Distribution.75th Percentile Latency (microseconds),289952.00,259652.00,456532.00,360779.00,298358.00,341667.00,488852.00,315419.00
Latency Distribution.Average Latency (microseconds),327420.00,312698.00,484163.00,389364.00,367532.25,415401.25,501142.75,348508.25
child,1,2,1,2,4,8,4,8
time_load,1398.00,1398.00,1398.00,1398.00,1481.00,1481.00,1481.00,1481.00
time_ingest,663.00,663.00,663.00,663.00,716.00,716.00,716.00,716.00
time_check,735.00,735.00,735.00,735.00,765.00,765.00,765.00,765.00
pods,1,2,1,2,4,8,4,8
datadisk,4307,4533,4705,4805,4307,4525,4686,4794
host_disk,247605,247606,247607,247607,247609,247610,247611,247611
host_datadisk,4307,4533,4705,4805,4307,4525,4686,4794
host_volume_used,4.3G,4.3G,4.6G,4.6G,4.3G,4.3G,4.6G,4.6G
benchmarking_parameters_BENCHBASE_TARGET,16384,8192,16384,8192,5120,2560,5120,2560
benchmarking_parameters_BENCHBASE_TERMINALS,160,80,160,80,40,20,40,20
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776754749,bexhoma-sut-postgresql-1-1-1024-1776754749,bexhoma-sut-postgresql-1-1-1024-1776754749,bexhoma-sut-postgresql-1-1-1024-1776754749
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-1-2,1776751747-PostgreSQL-1-1-1024-2-1,1776751747-PostgreSQL-1-1-1024-2-2,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-1-2,1776754749-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-2-2

# Performance at Ingestion per Run

This shows loading performance per experiment run.

In [33]:
df = collect.get_loading_per_run()
df.T

,1776751747-PostgreSQL-1-1-1024-1,1776751747-PostgreSQL-1-1-1024-2,1776754749-PostgreSQL-1-1-1024-1,1776754749-PostgreSQL-1-1-1024-2
code,1776751747,1776751747,1776754749,1776754749
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
experiment_run,1,2,1,2
SF,16,16,16,16
time_load,1398.00,1398.00,1481.00,1481.00
time_ingest,663.00,663.00,716.00,716.00
time_check,735.00,735.00,765.00,765.00
pods,2,2,8,8
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
Throughput [SF/h],41.20,41.20,38.89,38.89

## With Metadata

Connection infos are added.

In [34]:
df = collect.add_metadata(df)
df.T

combine on columns code configuration experiment_run

,1776751747-PostgreSQL-1-1-1024-1,1776751747-PostgreSQL-1-1-1024-2,1776754749-PostgreSQL-1-1-1024-1,1776754749-PostgreSQL-1-1-1024-2
SF,16,16,16,16
Throughput [SF/h],41.20,41.20,38.89,38.89
arg_autovacuum,off,off,off,off
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
arg_checkpoint_timeout,12h,12h,12h,12h
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_effective_io_concurrency,64,64,64,64
arg_fsync,on,on,on,on
arg_io_method,worker,worker,worker,worker
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_max_connections,3000,3000,3000,3000
arg_max_parallel_maintenance_workers,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_wal_senders,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_max_worker_processes,64,64,64,64
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_synchronous_commit,on,on,on,on
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_wal_compression,on,on,on,on
arg_wal_level,minimal,minimal,minimal,minimal
arg_work_mem,32GB,32GB,32GB,32GB
benchmarking_parameters_BENCHBASE_BATCHSIZE,128,128,128,128
benchmarking_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc
benchmarking_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
benchmarking_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false
benchmarking_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false
benchmarking_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres
benchmarking_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0
benchmarking_parameters_BENCHBASE_TARGET,16384,16384,5120,5120
benchmarking_parameters_BENCHBASE_TERMINALS,160,160,40,40
benchmarking_parameters_BENCHBASE_TIME,300,300,300,300
benchmarking_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a
benchmarking_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
benchmarking_parameters_SF,16,16,16,16
client,1,1,1,1
code,1776751747,1776751747,1776754749,1776754749
configuration,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024,PostgreSQL-1-1-1024
datadisk,4307,4705,4307,4686
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
experiment_run,1,2,1,2
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_Cores,128,128,128,128
host_GPU,,,,
host_RAM,540493398016,540493398016,540493398016,540493398016
host_cpu_list,0-127,0-127,0-127,0-127
host_cuda,,,,
host_datadisk,4307,4705,4307,4686
host_disk,247605,247607,247609,247611
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_hugepages_free,0,0,0,0
host_hugepages_total,0,0,0,0
host_limits_cpu,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_requests_cpu,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi
host_volume_size,100G,100G,100G,100G
host_volume_used,4.3G,4.6G,4.3G,4.6G
loading_parameters_BENCHBASE_BATCHSIZE,128,128,128,128
loading_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc
loading_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
loading_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false
loading_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false
loading_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres
loading_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0
loading_parameters_BENCHBASE_TERMINALS,1,1,1,1
loading_parameters_BENCHBASE_TIME,300,300,300,300
loading_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a
loading_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres
loading_parameters_BEXHOMA_TENANT_BY,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
loading_parameters_SF,16,16,16,16
num_tenants,0,0,0,0
num_worker,0,0,0,0
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-2-1
pods,2,2,8,8
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776754749,bexhoma-sut-postgresql-1-1-1024-1776754749
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
tenant,,,,
terminals,1,1,1,1
time_check,735.00,735.00,765.00,765.00
time_ingest,663.00,663.00,716.00,716.00
time_load,1398.00,1398.00,1481.00,1481.00
type_tenants,,,,
vol_tenants,False,False,False,False

# Combine Performance and Monitoring

This includes filtering for the first client and incorporating efficiency metrics to track performance relative to resource usage.

In [35]:
client = 1

df_performance_monitoring = collect.get_monitoring_aggregated_per_phase(type="stream")
df_performance = collect.get_performance_aggregated_per_phase()
merged_df = pd.merge(df_performance, df_performance_monitoring, left_index=True, right_index=True, how='left')

merged_df = merged_df[merged_df['client'] == client]

merged_df['E_Tpx'] = merged_df['Goodput (requests/second)'] / merged_df['CPU Utilization Time [s]'] * 600.
merged_df['E_Lat'] = 1./np.sqrt(merged_df['Latency Distribution.Average Latency (microseconds)']*merged_df['CPU Utilization Time [s]']/1E6)
merged_df['E_RAM'] = (merged_df['Goodput (requests/second)']) / merged_df['Memory Usage [MiB]']
merged_df.T

,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-2-1
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-2-1
configuration,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024
experiment_run,1,2,1,2
client,1,1,1,1
code,1776751747,1776751747,1776754749,1776754749
pod_count,1,1,4,4
duration,304,304,309,305
bench,tpcc,tpcc,tpcc,tpcc
profile,postgres,postgres,postgres,postgres
target,16384,16384,20480,20480
time,300.00,300.00,300.00,300.00
batchsize,128.00,128.00,128.00,128.00
sf,16,16,16,16
num_errors,3,0,1,0
scalefactor,16,16,16,16
Current Timestamp (milliseconds),1776753214394,1776754235688,1776756056032,1776757072540
Benchmark Type,tpcc,tpcc,tpcc,tpcc
isolation,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
DBMS Version,"PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit"
Goodput (requests/second),484.77,327.30,430.34,317.05
terminals,160,160,160,160
DBMS Type,POSTGRES,POSTGRES,POSTGRES,POSTGRES
Throughput (requests/second),487.99,329.17,433.22,318.75
Latency Distribution.95th Percentile Latency (microseconds),1525016.00,2213256.00,1745407.00,2311261.00
Latency Distribution.Maximum Latency (microseconds),12658448.00,16704195.00,22946799.00,16937122.00
Latency Distribution.Median Latency (microseconds),87888.00,146452.00,83578.00,155320.00
Latency Distribution.Minimum Latency (microseconds),620.00,686.00,606.00,609.00
Latency Distribution.25th Percentile Latency (microseconds),20601.00,38987.00,20122.00,45035.00
Latency Distribution.90th Percentile Latency (microseconds),884978.00,1300505.00,908741.00,1391606.00
Latency Distribution.99th Percentile Latency (microseconds),3425072.00,4862448.00,4609206.00,4780131.00
Latency Distribution.75th Percentile Latency (microseconds),289952.00,456532.00,298358.00,488852.00
Latency Distribution.Average Latency (microseconds),327420.00,484163.00,367532.25,501142.75
efficiency,0.00,0.00,0.00,0.00
child,1,1,4,4
Memory Usage [MiB],8768.13,7701.75,8717.99,7714.02
Memory Usage Cached [MiB],10557.51,9697.59,10494.15,9724.02
CPU Utilization,2.04,1.61,1.65,1.54
CPU Throttle,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00
CPU Utilization Time [s],643.95,1915.46,554.00,1679.78
CPU User Time [s],384.40,1277.49,329.65,1142.31
CPU System Time [s],259.55,637.98,224.35,537.47
Network Rx Total [MiB],956.21,2739.48,879.98,2572.74
Network Tx Total [MiB],1736.34,1229.08,1754.29,1009.67
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.02,0.00,0.02
Core Utilization Variance [%],0.03,0.02,0.02,0.02
Max Core Utilization [%],0.51,0.37,0.53,0.47
I/O Wait [%],18.29,21.35,20.86,21.95
Total I/O Wait Time [s],280.82,388.73,295.61,356.21
Number of Idle Sessions,0.33,0.26,0.50,0.26
Number of Idle-in-transaction Sessions,2.78,0.59,1.62,0.56
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00
Number of Active Sessions,160.00,160.00,160.00,160.00
Number of Active Application Sessions,160.00,160.00,160.00,160.00
Longest Active Transaction,5.13,5.51,6.87,6.55
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.06,0.05,0.03,0.08
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.97,4.43,0.99,1.03
Active Backends Waiting on WAL,32.33,34.52,33.93,32.41
Active Backends Waiting on Locks,118.56,118.07,120.33,120.12
Max Transaction Duration (I/O Wait),0.46,0.44,0.26,0.57
Max Transaction Duration (WAL Wait),3.29,3.83,4.40,4.10
Max Transaction Duration (Lock Wait),4.92,5.45,6.70,6.39
Disk Blocks Read Count,5.00,131189.00,5.00,131920.00
Buffer Cache Hit Count,39124427.00,25220288.00,36083065.00,25394830.00
Buffer Cache Hit Ratio,1.00,1.00,1.00,1.00
Index Scan Count,5486896.00,3709287.00,5030030.00,3644843.00
Index Tuple Fetch Count,7309126.00,4930017.00,6808882.00,4907631.00
Index Cache Hit Ratio,1.00,1.00,1.00,1.00
Table Buffer Hit Count,19533848.00,12388976.00,17794069.00,12570806.00
Table Blocks Read Count,0.00,111337.00,0.00,112121.00
Table Cache Hit Ratio,1.00,1.00,1.00,1.00
Total Cache Hit Ratio,1.00,1.00,1.00,1.00
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00
Total Locks Current,971.23,1040.79,988.14,947.56
AccessExclusiveLocks Current,0.18,0.33,2.71,1.89
AccessShareLocks Current,221.72,245.51,230.38,216.51
ExclusiveLocks Current,51.91,49.57,55.51,52.09
RowExclusiveLocks Current,486.62,499.51,482.75,473.75
RowShareLocks Current,210.79,245.87,216.79,203.32
ShareLocks Current,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],inf,inf,inf,inf
Number of WAL Segments,165.00,165.00,165.00,165.00
Total WAL Size [GiB],2.58,2.58,2.58,2.58
WAL Segments Growth Rate [segments/s],0.05,0.00,0.05,0.00
WAL Growth Rate [MiB/s],0.76,0.00,0.80,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00
E_Tpx,451.68,102.52,466.07,113.25
E_Lat,0.07,0.03,0.07,0.03
E_RAM,0.06,0.04,0.05,0.04

## With Metadata

Connection infos are added.

In [36]:
df = collect.add_metadata(merged_df)
df.T

combine on index and column 'phase'

phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-2-1
configuration,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024
experiment_run,1,2,1,2
client,1,1,1,1
code,1776751747,1776751747,1776754749,1776754749
pod_count,1,1,4,4
duration,304,304,309,305
bench,tpcc,tpcc,tpcc,tpcc
profile,postgres,postgres,postgres,postgres
target,16384,16384,20480,20480
time,300.00,300.00,300.00,300.00
batchsize,128.00,128.00,128.00,128.00
sf,16,16,16,16
num_errors,3,0,1,0
scalefactor,16,16,16,16
Current Timestamp (milliseconds),1776753214394,1776754235688,1776756056032,1776757072540
Benchmark Type,tpcc,tpcc,tpcc,tpcc
isolation,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
DBMS Version,"PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit","PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit"
Goodput (requests/second),484.77,327.30,430.34,317.05
terminals,160,160,160,160
DBMS Type,POSTGRES,POSTGRES,POSTGRES,POSTGRES
Throughput (requests/second),487.99,329.17,433.22,318.75
Latency Distribution.95th Percentile Latency (microseconds),1525016.00,2213256.00,1745407.00,2311261.00
Latency Distribution.Maximum Latency (microseconds),12658448.00,16704195.00,22946799.00,16937122.00
Latency Distribution.Median Latency (microseconds),87888.00,146452.00,83578.00,155320.00
Latency Distribution.Minimum Latency (microseconds),620.00,686.00,606.00,609.00
Latency Distribution.25th Percentile Latency (microseconds),20601.00,38987.00,20122.00,45035.00
Latency Distribution.90th Percentile Latency (microseconds),884978.00,1300505.00,908741.00,1391606.00
Latency Distribution.99th Percentile Latency (microseconds),3425072.00,4862448.00,4609206.00,4780131.00
Latency Distribution.75th Percentile Latency (microseconds),289952.00,456532.00,298358.00,488852.00
Latency Distribution.Average Latency (microseconds),327420.00,484163.00,367532.25,501142.75
efficiency,0.00,0.00,0.00,0.00
child,1,1,4,4
Memory Usage [MiB],8768.13,7701.75,8717.99,7714.02
Memory Usage Cached [MiB],10557.51,9697.59,10494.15,9724.02
CPU Utilization,2.04,1.61,1.65,1.54
CPU Throttle,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00
CPU Utilization Time [s],643.95,1915.46,554.00,1679.78
CPU User Time [s],384.40,1277.49,329.65,1142.31
CPU System Time [s],259.55,637.98,224.35,537.47
Network Rx Total [MiB],956.21,2739.48,879.98,2572.74
Network Tx Total [MiB],1736.34,1229.08,1754.29,1009.67
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.02,0.00,0.02
Core Utilization Variance [%],0.03,0.02,0.02,0.02
Max Core Utilization [%],0.51,0.37,0.53,0.47
I/O Wait [%],18.29,21.35,20.86,21.95
Total I/O Wait Time [s],280.82,388.73,295.61,356.21
Number of Idle Sessions,0.33,0.26,0.50,0.26
Number of Idle-in-transaction Sessions,2.78,0.59,1.62,0.56
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00
Number of Active Sessions,160.00,160.00,160.00,160.00
Number of Active Application Sessions,160.00,160.00,160.00,160.00
Longest Active Transaction,5.13,5.51,6.87,6.55
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.06,0.05,0.03,0.08
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.97,4.43,0.99,1.03
Active Backends Waiting on WAL,32.33,34.52,33.93,32.41
Active Backends Waiting on Locks,118.56,118.07,120.33,120.12
Max Transaction Duration (I/O Wait),0.46,0.44,0.26,0.57
Max Transaction Duration (WAL Wait),3.29,3.83,4.40,4.10
Max Transaction Duration (Lock Wait),4.92,5.45,6.70,6.39
Disk Blocks Read Count,5.00,131189.00,5.00,131920.00
Buffer Cache Hit Count,39124427.00,25220288.00,36083065.00,25394830.00
Buffer Cache Hit Ratio,1.00,1.00,1.00,1.00
Index Scan Count,5486896.00,3709287.00,5030030.00,3644843.00
Index Tuple Fetch Count,7309126.00,4930017.00,6808882.00,4907631.00
Index Cache Hit Ratio,1.00,1.00,1.00,1.00
Table Buffer Hit Count,19533848.00,12388976.00,17794069.00,12570806.00
Table Blocks Read Count,0.00,111337.00,0.00,112121.00
Table Cache Hit Ratio,1.00,1.00,1.00,1.00
Total Cache Hit Ratio,1.00,1.00,1.00,1.00
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00
Total Locks Current,971.23,1040.79,988.14,947.56
AccessExclusiveLocks Current,0.18,0.33,2.71,1.89
AccessShareLocks Current,221.72,245.51,230.38,216.51
ExclusiveLocks Current,51.91,49.57,55.51,52.09
RowExclusiveLocks Current,486.62,499.51,482.75,473.75
RowShareLocks Current,210.79,245.87,216.79,203.32
ShareLocks Current,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],inf,inf,inf,inf
Number of WAL Segments,165.00,165.00,165.00,165.00
Total WAL Size [GiB],2.58,2.58,2.58,2.58
WAL Segments Growth Rate [segments/s],0.05,0.00,0.05,0.00
WAL Growth Rate [MiB/s],0.76,0.00,0.80,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00
E_Tpx,451.68,102.52,466.07,113.25
E_Lat,0.07,0.03,0.07,0.03
E_RAM,0.06,0.04,0.05,0.04
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,1398.00,1398.00,1481.00,1481.00
time_ingest,663.00,663.00,716.00,716.00
time_check,735.00,735.00,765.00,765.00
pods,1,1,4,4
tenant,,,,
num_worker,0,0,0,0
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,4307,4705,4307,4686
host_RAM,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,
host_Cores,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247605,247607,247609,247611
host_datadisk,4307,4705,4307,4686
host_volume_size,100G,100G,100G,100G
host_volume_used,4.3G,4.6G,4.3G,4.6G
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,16,16,16,16
loading_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc
loading_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres
loading_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres
loading_parameters_BENCHBASE_TERMINALS,1,1,1,1
loading_parameters_BENCHBASE_TIME,300,300,300,300
loading_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
loading_parameters_BENCHBASE_BATCHSIZE,128,128,128,128
loading_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0
loading_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false
loading_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false
loading_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a
loading_parameters_BEXHOMA_TENANT_BY,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
benchmarking_parameters_SF,16,16,16,16
benchmarking_parameters_BENCHBASE_BENCH,tpcc,tpcc,tpcc,tpcc
benchmarking_parameters_BENCHBASE_PROFILE,postgres,postgres,postgres,postgres
benchmarking_parameters_BEXHOMA_DATABASE,postgres,postgres,postgres,postgres
benchmarking_parameters_BENCHBASE_TARGET,16384,16384,5120,5120
benchmarking_parameters_BENCHBASE_TERMINALS,160,160,40,40
benchmarking_parameters_BENCHBASE_TIME,300,300,300,300
benchmarking_parameters_BENCHBASE_ISOLATION,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED,TRANSACTION_READ_COMMITTED
benchmarking_parameters_BENCHBASE_BATCHSIZE,128,128,128,128
benchmarking_parameters_BENCHBASE_STATUS_INTERVAL,0,0,0,0
benchmarking_parameters_BENCHBASE_KEY_AND_THINK,false,false,false,false
benchmarking_parameters_BENCHBASE_NEWCONNPERTXN,false,false,false,false
benchmarking_parameters_BENCHBASE_YCSB_WORKLOAD,a,a,a,a
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16,bexhoma-worker-postgresql-benchbase-tpcc-16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776751747,bexhoma-sut-postgresql-1-1-1024-1776754749,bexhoma-sut-postgresql-1-1-1024-1776754749
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-2-1

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [37]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-2-1
phase,1776751747-PostgreSQL-1-1-1024-1-1,1776751747-PostgreSQL-1-1-1024-2-1,1776754749-PostgreSQL-1-1-1024-1-1,1776754749-PostgreSQL-1-1-1024-2-1
code,1776751747,1776751747,1776754749,1776754749
configuration,1776751747-PostgreSQL-1-1-1024,1776751747-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024,1776754749-PostgreSQL-1-1-1024
experiment_run,1,2,1,2
client,1,1,1,1
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False

In [38]:
zip_all_results(path, codes)

Zipping D:\data\benchmarks\1776751747 to D:\data\benchmarks\1776751747.zip...
Zipping D:\data\benchmarks\1776754749 to D:\data\benchmarks\1776754749.zip...
✅ Done zipping all folders.