# TPC-H Collector Demo

# Missing
* connection data beyond loading
* join to connection data
* join to monitoring_single
* connection and configuration also in monitoring and connection df

## Naming
* There is an experiment having a code, say `1775855486`.
* The experiment inspects a SUT, say `PostgreSQL-A`. This is called a `configuration`.
* The experiment is run several times, say twice. The indicator of the run is called `experiment_run`.
* Each run can have several phases as a sequence. The number of the phase is called `client`. The state of the configuration in a phase is called a `connection`.
* Each client can have several `pods`, that are run in parallel. A pod represents a driver.
* Performance metrics are collected per driver pod.  
    The naming of an instance is `<sut>-<experiment_run>-<client>-<pod>`. It is unique per experiment.
* Monitoring metrics are collected per phase. They are automatically aggregated across parallel pods.  
    The naming of an instance is `<sut>-<experiment_run>-<client>`. It is unique per experiment.

## Aggregation
* Aggregation is complicated. Some metrics are aggregated via count, sum, max or average. Others cannot be aggregated sensibly, like experiment code or latency percentiles.
* There are helper functions to aggregated pods that are certainly run in parallel.  
  So `<sut>-<experiment_run>-<client>-<pod>` are aggregated to `<sut>-<experiment_run>-<client>`.
* An exception is multi-tenancy.

## Class `collector`
* constructor `collectors.benchbase(path, codes)`
* evaluator object `evaluate = collect.get_evaluator()`
* dataframe of connection infos `collect.get_connections()`
  * index is name of client
* **monitoring metrics**
  * dataframe of available metrics `collect.df_metrics`
    * index is key of metric
  * dataframe of monitored components `collect.get_monitored_phases()`
    * index is key of component
  * dataframe of aggregated metrics per connection `collect.get_monitoring_single_all()`
    * index is name of client
    * metrics aggregated per code, experiment_run and client
  * dataframe of aggregated metrics per connection and across tenants `collect.get_monitoring_all()`
    * index just enumerates
    * metrics aggregated per code, experiment_run and client and across tenants
  * dataframe of time series for a metric of a connection in an experiment `collect.get_monitoring_timeseries_single(code, metric)`
    * index is name of connection
    * unstacked (wide format)
  * dataframe of time series for a metric in all experiments `collect.get_monitoring_timeseries_all(metric)`
    * index just enumerates
    * stacked (long format)
* **performance metrics**
  * dataframe of loading metrics `collect.get_loading_time_max_all()`
    * index is name of client
  * dataframe of performance aggregated per parallel client `collect.get_performance_all()`
    * index just enumerates
    * performance aggregated per code, experiment_run and client
  * dataframe of performance for one experiment `collect.get_performance_single()`
    * performance of each single client (driver)
    * index is name of client pod
  * dataframe of performance for all experiments `collect.get_performance_all_single()`
    * performance of each single client (driver)
    * index is name of client pod


[1] [Benchmarking Multi-Tenant Architectures in PostgreSQL](https://doi.org/10.48786/edbt.2026.46)
> Erdelt, P.K., and Rabl T. (2026)
> In: Proceedings 29th International Conference on Extending Database Technology, EDBT 2026
> OpenProceedings.org
> https://doi.org/10.48786/edbt.2026.46

In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option('display.max_colwidth', None)
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.float_format = '{:.2f}'.format

from bexhoma import collectors

%matplotlib inline

# Functions for Nice Plots

In [2]:
from notebookutils import *

# Collect Results

In [3]:
#path = r"D:\data\benchmarks"
path = r"/data/benchmarks"
filename_prefix = "demo_"
b_plot_save = False
b_skip_plots = True

In [4]:
codes = [
    "1776418956",
    "1776420958"
]

codes

['1776418956', '1776420958']

In [5]:
collect = collectors.default(path, codes)

# Get all Metrics Metadata

## Metrics Names and Types

Metrics that are derived from monitoring

In [6]:
collect.df_metrics

,title,active,type,metric
total_cpu_memory,Memory Usage [MiB],True,cluster,gauge
total_cpu_memory_cached,Memory Usage Cached [MiB],True,cluster,gauge
total_cpu_util,CPU Utilization,True,cluster,gauge
total_cpu_throttled,CPU Throttle,True,cluster,gauge
total_cpu_throttled_s,CPU Throttled Time [s],True,cluster,counter
total_cpu_util_others,CPU Utilization Others,False,cluster,gauge
total_cpu_util_s,CPU Utilization Time [s],True,cluster,counter
total_cpu_util_user_s,CPU User Time [s],True,cluster,counter
total_cpu_util_sys_s,CPU System Time [s],True,cluster,counter
total_cpu_util_others_s,CPU Utilization Time Others [s],False,cluster,counter
total_network_rx,Network Rx Total [MiB],True,cluster,counter
total_network_tx,Network Tx Total [MiB],True,cluster,counter
total_fs_read,Filesystem Read Total [MiB],True,cluster,counter
total_fs_write,Filesystem Write Total [MiB],True,cluster,counter
total_gpu_util,GPU Utilization [%],False,cluster,gauge
total_gpu_power,GPU Power Usage [W],False,cluster,gauge
total_gpu_memory,GPU Memory Usage [MiB],False,cluster,gauge
core_variance,Core Utilization Variance [%],True,cluster,ratio
max_core_util,Max Core Utilization [%],True,cluster,ratio
io_wait_pct,I/O Wait [%],True,cluster,ratio
io_wait_total,Total I/O Wait Time [s],True,cluster,counter
pg_stat_activity_count_idle,Number of Idle Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction,Number of Idle-in-transaction Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction_aborted,Number of Idle-in-transaction Aborted Sessions,True,application,gauge
pg_stat_activity_count_active,Number of Active Sessions,True,application,counter
pg_stat_activity_count_active_app,Number of Active Application Sessions,True,application,counter
pg_stat_activity_max_tx_duration_active,Longest Active Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle,Longest Idle Session (no transaction),True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx,Longest Idle-in-Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx_aborted,Longest Idle-in-Transaction (Aborted),True,application,ratio
pg_stat_activity_count_io,Active Backends Waiting on I/O,True,application,gauge
pg_stat_activity_count_wal,Active Backends Waiting on WAL,True,application,gauge
pg_stat_activity_count_lock,Active Backends Waiting on Locks,True,application,gauge
pg_stat_activity_max_tx_duration_io,Max Transaction Duration (I/O Wait),True,application,ratio
pg_stat_activity_max_tx_duration_wal,Max Transaction Duration (WAL Wait),True,application,ratio
pg_stat_activity_max_tx_duration_lock,Max Transaction Duration (Lock Wait),True,application,ratio
pg_stat_database_blks_read,Disk Blocks Read Count,True,application,counter
pg_stat_database_blks_hit,Buffer Cache Hit Count,True,application,counter
cache_hit_ratio,Buffer Cache Hit Ratio,True,application,ratio
pg_stat_user_tables_idx_scan,Index Scan Count,True,application,counter
pg_stat_user_tables_idx_tup_fetch,Index Tuple Fetch Count,True,application,counter
pg_statio_user_tables_idx_cache_hit_ratio,Index Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_heap_blocks_hit,Table Buffer Hit Count,True,application,counter
pg_statio_user_tables_heap_blocks_read,Table Blocks Read Count,True,application,counter
pg_statio_user_tables_heap_cache_hit_ratio,Table Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_total_cache_hit_ratio,Total Cache Hit Ratio,True,application,ratio
pg_stat_bgwriter_efficiency_ratio,BGWriter Efficiency Ratio (Cleaned / Allocated),True,application,ratio
pg_stat_bgwriter_maxwritten_clean_total,BGWriter Stopped Due to Max Pages,True,application,counter
pg_stat_bgwriter_checkpoint_sync_time_total,Checkpoint Sync Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_total,Checkpoint Write Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_per_sync_time,Time spent writing vs syncing during checkpoints [ratio],False,application,ratio
pg_locks_count,Total Locks Current,True,application,gauge
pg_locks_count_accessexclusivelock,AccessExclusiveLocks Current,True,application,gauge
pg_locks_count_accesssharelock,AccessShareLocks Current,True,application,gauge
pg_locks_count_exclusivelock,ExclusiveLocks Current,True,application,gauge
pg_locks_count_rowexclusivelock,RowExclusiveLocks Current,True,application,gauge
pg_locks_count_rowsharelock,RowShareLocks Current,True,application,gauge
pg_locks_count_sharelock,ShareLocks Current,True,application,gauge
pg_locks_count_sharerowexclusivelock,ShareRowExclusiveLocks Current,True,application,gauge
pg_locks_count_shareupdateexclusivelock,ShareUpdateExclusiveLocks Current,True,application,gauge
pg_locks_count_sireadlock,SIReadLocks Current,True,application,gauge
pg_stat_user_tables_autoanalyze_count,Autoanalyze Run Count,True,application,counter
pg_stat_user_tables_autovacuum_count,Autovacuum Run Count,True,application,counter
pg_stat_bgwriter_checkpoints_timed_per_req,Frequency of checkpoints (timed vs requested) [ratio],False,application,gauge
pg_stat_wal_volume_bytes_sec,Volume of WAL generated [bytes/sec],False,application,counter
pg_stat_bgwriter_buffers_backend_fsync,Backends forced to flush WAL (I/O contention) [fsync/sec],False,application,counter
pg_stat_activity_wait_event_count,Active sessions waiting on any event [count],False,application,gauge
pg_stat_user_tables_dead_tuples_per_vacuum,Dead tuples per vacuum operation [tuples/vacuum],True,application,ratio
pg_wal_segments,Number of WAL Segments,True,application,gauge
pg_wal_size_bytes,Total WAL Size [GiB],True,application,gauge
pg_wal_segments_rate,WAL Segments Growth Rate [segments/s],True,application,gauge
pg_wal_size_rate,WAL Growth Rate [MiB/s],True,application,gauge
pg_wal_avg_segment_size,Average WAL Segment Size [MiB],True,application,gauge
pg_wal_size_per_checkpoint,WAL Size per Checkpoint [bytes/checkpoint],False,application,gauge

## Names of Monitored Components

Names of components and their phases

In [7]:
collect.get_monitored_components()

                                           description
loading                  Loading phase: SUT deployment
datagenerator  Loading phase: component data generator
loader                 Loading phase: component loader
stream                 Execution phase: SUT deployment
benchmarker     Execution phase: component benchmarker

# Get Connection Infos

List of states of SUTs, containing loading infos.

In [8]:
df=collect.get_connections()

In [9]:
df.T

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
code,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958
connection,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2
configuration,,,,,,,,
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,455.00,455.00,455.00,455.00,1256.00,1256.00,1256.00,1256.00
time_ingest,141.00,141.00,141.00,141.00,350.00,350.00,350.00,350.00
time_check,291.00,291.00,291.00,291.00,843.00,843.00,843.00,843.00
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151015,151015,151015,151015,151015,151015,151015,151015
host_datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [10]:
df[['phase', 'code', 'connection', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']]

,phase,code,connection,configuration,experiment_run,client,type_tenants,num_tenants,vol_tenants
1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-1,1776418956,PostgreSQL-BHT-8-1-1-1,,1,1,,0,False
1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956,PostgreSQL-BHT-8-1-2-2,,1,2,,0,False
1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-1,1776418956,PostgreSQL-BHT-8-2-1-1,,2,1,,0,False
1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776418956,PostgreSQL-BHT-8-2-2-2,,2,2,,0,False
1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-1,1776420958,PostgreSQL-BHT-8-1-1-1,,1,1,,0,False
1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958,PostgreSQL-BHT-8-1-2-2,,1,2,,0,False
1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-1,1776420958,PostgreSQL-BHT-8-2-1-1,,2,1,,0,False
1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2,1776420958,PostgreSQL-BHT-8-2-2-2,,2,2,,0,False

In [11]:
collectors.get_non_constant(df).T

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
code,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958
connection,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
time_load,455.00,455.00,455.00,455.00,1256.00,1256.00,1256.00,1256.00
time_ingest,141.00,141.00,141.00,141.00,350.00,350.00,350.00,350.00
time_check,291.00,291.00,291.00,291.00,843.00,843.00,843.00,843.00
pods,1,2,1,2,1,2,1,2
datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G
loading_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958

# Monitoring Aggregated per Phase

In [12]:
df = collect.get_monitoring_aggregated_per_phase("stream")
df.T

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
Memory Usage [MiB],10919.47,12131.24,10392.28,11955.10,17504.07,19192.60,14054.22,16993.59
Memory Usage Cached [MiB],15835.40,17047.17,15288.83,16789.84,27302.43,28990.96,22555.50,26276.44
CPU Utilization,1.66,3.29,0.96,3.39,2.91,5.70,1.60,5.64
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],180.14,320.88,998.63,395.04,381.59,869.22,2263.06,877.07
CPU User Time [s],156.36,281.35,826.53,344.83,331.65,767.27,1928.57,768.57
CPU System Time [s],23.78,39.53,172.10,50.21,49.94,101.95,334.50,108.51
Network Rx Total [MiB],1.72,7.30,3307.36,1.87,1.91,3.74,6644.39,3.68
Network Tx Total [MiB],0.20,1320.29,21.81,3.35,1.96,3.78,39.78,3.66
Filesystem Read Total [MiB],0.00,0.00,0.05,0.00,0.00,0.00,0.04,0.00
Filesystem Write Total [MiB],0.00,0.00,0.03,0.00,0.00,0.00,0.03,0.00
Core Utilization Variance [%],0.05,0.07,0.06,0.13,0.90,0.18,0.11,0.27
Max Core Utilization [%],2.37,1.92,1.02,2.80,58.98,4.78,2.34,5.37
I/O Wait [%],16.96,1.42,45.06,45.14,0.62,0.22,51.57,27.13
Total I/O Wait Time [s],0.17,0.01,378.85,0.01,0.03,2.03,567.05,0.07
Number of Idle Sessions,0.51,0.00,0.50,0.41,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,1.00,6.00,6.00,14.00,6.00,12.00,7.00,9.00
Number of Active Application Sessions,1.00,6.00,7.00,14.00,6.00,12.00,7.00,9.00
Longest Active Transaction,1.39,1.52,3.00,1.05,4.50,3.82,6.29,5.18
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,0.00,1.49,0.00,0.00,0.00,1.24,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,0.00,2.70,0.00,0.00,0.00,3.83,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,68816.00,0.00,561331.00,0.00,141677.00,0.00,1126572.00,0.00
Buffer Cache Hit Count,12007592.00,27863012.00,11519332.00,23979758.00,29738918.00,54165762.00,25971705.00,56259630.00
Buffer Cache Hit Ratio,0.94,0.98,0.99,0.99,0.99,1.00,0.99,0.99
Index Scan Count,1655068.00,3347073.00,1655068.00,3310128.00,3787019.00,7573926.00,3786963.00,7573968.00
Index Tuple Fetch Count,7285353.00,15714468.00,7285353.00,14570698.00,17452007.00,34903566.00,17451783.00,34903734.00
Index Cache Hit Ratio,0.83,0.99,1.00,1.00,1.00,1.00,1.00,1.00
Table Buffer Hit Count,7129428.00,17860713.00,6637087.00,14097214.00,18580301.00,31581658.00,14806307.00,33673975.00
Table Blocks Read Count,0.00,0.00,492339.00,0.00,0.00,0.00,984522.00,0.00
Table Cache Hit Ratio,0.94,0.98,0.98,0.98,0.98,0.99,0.99,0.99
Total Cache Hit Ratio,0.94,0.98,0.99,0.99,0.99,1.00,0.99,0.99
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,4.27,10.39,9.21,27.23,17.79,47.79,15.57,29.68
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,4.27,10.39,9.21,27.23,17.79,47.79,15.57,29.68
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN
Number of WAL Segments,205.00,205.00,205.00,205.00,410.00,410.00,410.00,410.00
Total WAL Size [GiB],3.20,3.20,3.20,3.20,6.41,6.41,6.41,6.41
WAL Segments Growth Rate [segments/s],0.64,0.01,0.00,0.00,0.00,0.00,0.00,0.00
WAL Growth Rate [MiB/s],10.21,0.08,0.00,0.00,0.00,0.00,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00

### With Metadata

In [13]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
Memory Usage [MiB],10919.47,12131.24,10392.28,11955.10,17504.07,19192.60,14054.22,16993.59
Memory Usage Cached [MiB],15835.40,17047.17,15288.83,16789.84,27302.43,28990.96,22555.50,26276.44
CPU Utilization,1.66,3.29,0.96,3.39,2.91,5.70,1.60,5.64
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],180.14,320.88,998.63,395.04,381.59,869.22,2263.06,877.07
CPU User Time [s],156.36,281.35,826.53,344.83,331.65,767.27,1928.57,768.57
CPU System Time [s],23.78,39.53,172.10,50.21,49.94,101.95,334.50,108.51
Network Rx Total [MiB],1.72,7.30,3307.36,1.87,1.91,3.74,6644.39,3.68
Network Tx Total [MiB],0.20,1320.29,21.81,3.35,1.96,3.78,39.78,3.66
Filesystem Read Total [MiB],0.00,0.00,0.05,0.00,0.00,0.00,0.04,0.00
Filesystem Write Total [MiB],0.00,0.00,0.03,0.00,0.00,0.00,0.03,0.00
Core Utilization Variance [%],0.05,0.07,0.06,0.13,0.90,0.18,0.11,0.27
Max Core Utilization [%],2.37,1.92,1.02,2.80,58.98,4.78,2.34,5.37
I/O Wait [%],16.96,1.42,45.06,45.14,0.62,0.22,51.57,27.13
Total I/O Wait Time [s],0.17,0.01,378.85,0.01,0.03,2.03,567.05,0.07
Number of Idle Sessions,0.51,0.00,0.50,0.41,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,1.00,6.00,6.00,14.00,6.00,12.00,7.00,9.00
Number of Active Application Sessions,1.00,6.00,7.00,14.00,6.00,12.00,7.00,9.00
Longest Active Transaction,1.39,1.52,3.00,1.05,4.50,3.82,6.29,5.18
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,0.00,1.49,0.00,0.00,0.00,1.24,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,0.00,2.70,0.00,0.00,0.00,3.83,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,68816.00,0.00,561331.00,0.00,141677.00,0.00,1126572.00,0.00
Buffer Cache Hit Count,12007592.00,27863012.00,11519332.00,23979758.00,29738918.00,54165762.00,25971705.00,56259630.00
Buffer Cache Hit Ratio,0.94,0.98,0.99,0.99,0.99,1.00,0.99,0.99
Index Scan Count,1655068.00,3347073.00,1655068.00,3310128.00,3787019.00,7573926.00,3786963.00,7573968.00
Index Tuple Fetch Count,7285353.00,15714468.00,7285353.00,14570698.00,17452007.00,34903566.00,17451783.00,34903734.00
Index Cache Hit Ratio,0.83,0.99,1.00,1.00,1.00,1.00,1.00,1.00
Table Buffer Hit Count,7129428.00,17860713.00,6637087.00,14097214.00,18580301.00,31581658.00,14806307.00,33673975.00
Table Blocks Read Count,0.00,0.00,492339.00,0.00,0.00,0.00,984522.00,0.00
Table Cache Hit Ratio,0.94,0.98,0.98,0.98,0.98,0.99,0.99,0.99
Total Cache Hit Ratio,0.94,0.98,0.99,0.99,0.99,1.00,0.99,0.99
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,4.27,10.39,9.21,27.23,17.79,47.79,15.57,29.68
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,4.27,10.39,9.21,27.23,17.79,47.79,15.57,29.68
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN
Number of WAL Segments,205.00,205.00,205.00,205.00,410.00,410.00,410.00,410.00
Total WAL Size [GiB],3.20,3.20,3.20,3.20,6.41,6.41,6.41,6.41
WAL Segments Growth Rate [segments/s],0.64,0.01,0.00,0.00,0.00,0.00,0.00,0.00
WAL Growth Rate [MiB/s],10.21,0.08,0.00,0.00,0.00,0.00,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00
code,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958
configuration,,,,,,,,
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,455.00,455.00,455.00,455.00,1256.00,1256.00,1256.00,1256.00
time_ingest,141.00,141.00,141.00,141.00,350.00,350.00,350.00,350.00
time_check,291.00,291.00,291.00,291.00,843.00,843.00,843.00,843.00
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151015,151015,151015,151015,151015,151015,151015,151015
host_datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2

In [14]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
code,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958
configuration,,,,,,,,
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False

# Time Series of a Single Metric for a Single Experiment

In [15]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_per_phase(code, metric=metric, component='stream')
df.T

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2
0,9770.97,10315.59,10315.64,10300.51
1,9770.97,10315.59,10315.64,10300.51
2,9770.97,10315.59,10315.64,10300.51
3,9770.97,10315.59,10315.64,10300.51
4,9770.97,10315.59,10315.64,10300.51
5,9838.88,10315.59,10315.64,10300.51
6,9838.88,10315.59,10315.64,10300.51
7,9838.88,10315.59,10315.64,10300.51
8,9838.88,10315.59,10315.64,10300.51
9,9838.88,10315.59,10315.64,10300.51
10,9838.88,10315.59,10315.64,10300.51
11,9838.88,10315.59,10315.64,10300.51
12,9838.88,10315.59,10315.64,10300.51
13,9838.88,10315.59,10315.64,10300.51
14,9838.88,10315.59,10315.64,10300.51
15,9838.88,10315.59,10315.64,10300.51
16,9838.88,10496.98,10315.64,10300.51
17,9838.88,10496.98,10315.64,10300.51
18,9838.88,10496.98,10315.64,10300.51
19,9838.88,10496.98,10315.64,10300.51
20,9838.88,10496.98,10315.64,10300.51
21,9838.88,10496.98,10315.64,10300.51
22,9838.88,10496.98,10315.64,10300.51
23,9838.88,10496.98,10315.64,10300.51
24,9838.88,10496.98,10315.64,10300.51
25,9838.88,10496.98,10315.64,10300.51
26,9838.88,10496.98,10315.64,10300.51
27,9838.88,10496.98,10315.64,10300.51
28,9838.88,10496.98,10315.64,10300.51
29,9838.88,10496.98,10315.64,10300.51
30,9838.88,10496.98,10315.64,10300.51
31,9838.88,10496.98,10315.64,10459.21
32,9838.88,10496.98,10315.64,10459.21
33,9838.88,10496.98,10315.64,10459.21
34,9838.88,10496.98,10315.64,10459.21
35,9838.88,10496.98,10315.64,10459.21
36,10386.68,10496.98,10315.64,10459.21
37,10386.68,10496.98,10315.64,10459.21
38,10386.68,10496.98,10315.64,10459.21
39,10386.68,10496.98,10315.64,10459.21
40,10386.68,10496.98,10315.64,10459.21
41,10386.68,10496.98,10315.64,10459.21
42,10386.68,10496.98,10315.64,10459.21
43,10386.68,10496.98,10315.64,10459.21
44,10386.68,10496.98,10315.64,10459.21
45,10386.68,10496.98,10315.64,10459.21
46,10386.68,10496.98,10315.64,10459.21
47,10386.68,10496.98,10315.64,10459.21
48,10386.68,18388.65,10315.64,10459.21
49,10386.68,18388.65,10315.64,10459.21
50,10386.68,18388.65,10315.64,10459.21
51,16823.52,18388.65,10315.64,10459.21
52,16823.52,18388.65,10315.64,10459.21
53,16823.52,18388.65,10315.64,10459.21
54,16823.52,18388.65,10315.64,10459.21
55,16823.52,18388.65,10315.64,26487.36
56,16823.52,18388.65,10315.64,26487.36
57,16823.52,18388.65,10315.64,26487.36
58,16823.52,18388.65,10315.64,26487.36
59,NaN,18388.65,10315.64,26487.36
60,NaN,18388.65,10315.64,26487.36
61,NaN,NaN,10315.64,NaN
62,NaN,NaN,10315.64,NaN
63,NaN,NaN,10315.64,NaN
64,NaN,NaN,10315.64,NaN
65,NaN,NaN,10315.64,NaN
66,NaN,NaN,10315.64,NaN
67,NaN,NaN,10315.64,NaN
68,NaN,NaN,10315.64,NaN
69,NaN,NaN,10315.64,NaN
70,NaN,NaN,10315.64,NaN
71,NaN,NaN,10315.64,NaN
72,NaN,NaN,10315.64,NaN
73,NaN,NaN,10315.64,NaN
74,NaN,NaN,10315.64,NaN
75,NaN,NaN,10315.64,NaN
76,NaN,NaN,10315.64,NaN
77,NaN,NaN,10315.64,NaN
78,NaN,NaN,10315.64,NaN
79,NaN,NaN,10315.64,NaN
80,NaN,NaN,10315.64,NaN
81,NaN,NaN,10315.64,NaN
82,NaN,NaN,10315.64,NaN
83,NaN,NaN,10315.64,NaN
84,NaN,NaN,10315.64,NaN
85,NaN,NaN,10315.64,NaN
86,NaN,NaN,10315.64,NaN
87,NaN,NaN,10315.64,NaN
88,NaN,NaN,10315.64,NaN
89,NaN,NaN,10354.88,NaN
90,NaN,NaN,10354.88,NaN
91,NaN,NaN,10354.88,NaN
92,NaN,NaN,10354.88,NaN
93,NaN,NaN,10354.88,NaN
94,NaN,NaN,10354.88,NaN
95,NaN,NaN,10354.88,NaN
96,NaN,NaN,10354.88,NaN
97,NaN,NaN,10354.88,NaN
98,NaN,NaN,10354.88,NaN
99,NaN,NaN,10354.88,NaN
100,NaN,NaN,10354.88,NaN
101,NaN,NaN,10354.88,NaN
102,NaN,NaN,10354.88,NaN
103,NaN,NaN,10354.88,NaN
104,NaN,NaN,10354.88,NaN
105,NaN,NaN,10354.88,NaN
106,NaN,NaN,10354.88,NaN
107,NaN,NaN,10354.88,NaN
108,NaN,NaN,10354.88,NaN
109,NaN,NaN,10354.88,NaN
110,NaN,NaN,10354.88,NaN
111,NaN,NaN,10354.88,NaN
112,NaN,NaN,10354.88,NaN
113,NaN,NaN,10354.88,NaN
114,NaN,NaN,10354.88,NaN
115,NaN,NaN,10354.88,NaN
116,NaN,NaN,10354.88,NaN
117,NaN,NaN,10354.88,NaN
118,NaN,NaN,10354.88,NaN
119,NaN,NaN,10354.88,NaN
120,NaN,NaN,18372.53,NaN

### With Metadata

In [16]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2
0,9770.97,10315.59,10315.64,10300.51
1,9770.97,10315.59,10315.64,10300.51
2,9770.97,10315.59,10315.64,10300.51
3,9770.97,10315.59,10315.64,10300.51
4,9770.97,10315.59,10315.64,10300.51
5,9838.88,10315.59,10315.64,10300.51
6,9838.88,10315.59,10315.64,10300.51
7,9838.88,10315.59,10315.64,10300.51
8,9838.88,10315.59,10315.64,10300.51
9,9838.88,10315.59,10315.64,10300.51
10,9838.88,10315.59,10315.64,10300.51
11,9838.88,10315.59,10315.64,10300.51
12,9838.88,10315.59,10315.64,10300.51
13,9838.88,10315.59,10315.64,10300.51
14,9838.88,10315.59,10315.64,10300.51
15,9838.88,10315.59,10315.64,10300.51
16,9838.88,10496.98,10315.64,10300.51
17,9838.88,10496.98,10315.64,10300.51
18,9838.88,10496.98,10315.64,10300.51
19,9838.88,10496.98,10315.64,10300.51
20,9838.88,10496.98,10315.64,10300.51
21,9838.88,10496.98,10315.64,10300.51
22,9838.88,10496.98,10315.64,10300.51
23,9838.88,10496.98,10315.64,10300.51
24,9838.88,10496.98,10315.64,10300.51
25,9838.88,10496.98,10315.64,10300.51
26,9838.88,10496.98,10315.64,10300.51
27,9838.88,10496.98,10315.64,10300.51
28,9838.88,10496.98,10315.64,10300.51
29,9838.88,10496.98,10315.64,10300.51
30,9838.88,10496.98,10315.64,10300.51
31,9838.88,10496.98,10315.64,10459.21
32,9838.88,10496.98,10315.64,10459.21
33,9838.88,10496.98,10315.64,10459.21
34,9838.88,10496.98,10315.64,10459.21
35,9838.88,10496.98,10315.64,10459.21
36,10386.68,10496.98,10315.64,10459.21
37,10386.68,10496.98,10315.64,10459.21
38,10386.68,10496.98,10315.64,10459.21
39,10386.68,10496.98,10315.64,10459.21
40,10386.68,10496.98,10315.64,10459.21
41,10386.68,10496.98,10315.64,10459.21
42,10386.68,10496.98,10315.64,10459.21
43,10386.68,10496.98,10315.64,10459.21
44,10386.68,10496.98,10315.64,10459.21
45,10386.68,10496.98,10315.64,10459.21
46,10386.68,10496.98,10315.64,10459.21
47,10386.68,10496.98,10315.64,10459.21
48,10386.68,18388.65,10315.64,10459.21
49,10386.68,18388.65,10315.64,10459.21
50,10386.68,18388.65,10315.64,10459.21
51,16823.52,18388.65,10315.64,10459.21
52,16823.52,18388.65,10315.64,10459.21
53,16823.52,18388.65,10315.64,10459.21
54,16823.52,18388.65,10315.64,10459.21
55,16823.52,18388.65,10315.64,26487.36
56,16823.52,18388.65,10315.64,26487.36
57,16823.52,18388.65,10315.64,26487.36
58,16823.52,18388.65,10315.64,26487.36
59,NaN,18388.65,10315.64,26487.36
60,NaN,18388.65,10315.64,26487.36
61,NaN,NaN,10315.64,NaN
62,NaN,NaN,10315.64,NaN
63,NaN,NaN,10315.64,NaN
64,NaN,NaN,10315.64,NaN
65,NaN,NaN,10315.64,NaN
66,NaN,NaN,10315.64,NaN
67,NaN,NaN,10315.64,NaN
68,NaN,NaN,10315.64,NaN
69,NaN,NaN,10315.64,NaN
70,NaN,NaN,10315.64,NaN
71,NaN,NaN,10315.64,NaN
72,NaN,NaN,10315.64,NaN
73,NaN,NaN,10315.64,NaN
74,NaN,NaN,10315.64,NaN
75,NaN,NaN,10315.64,NaN
76,NaN,NaN,10315.64,NaN
77,NaN,NaN,10315.64,NaN
78,NaN,NaN,10315.64,NaN
79,NaN,NaN,10315.64,NaN
80,NaN,NaN,10315.64,NaN
81,NaN,NaN,10315.64,NaN
82,NaN,NaN,10315.64,NaN
83,NaN,NaN,10315.64,NaN
84,NaN,NaN,10315.64,NaN
85,NaN,NaN,10315.64,NaN
86,NaN,NaN,10315.64,NaN
87,NaN,NaN,10315.64,NaN
88,NaN,NaN,10315.64,NaN
89,NaN,NaN,10354.88,NaN
90,NaN,NaN,10354.88,NaN
91,NaN,NaN,10354.88,NaN
92,NaN,NaN,10354.88,NaN
93,NaN,NaN,10354.88,NaN
94,NaN,NaN,10354.88,NaN
95,NaN,NaN,10354.88,NaN
96,NaN,NaN,10354.88,NaN
97,NaN,NaN,10354.88,NaN
98,NaN,NaN,10354.88,NaN
99,NaN,NaN,10354.88,NaN
100,NaN,NaN,10354.88,NaN
101,NaN,NaN,10354.88,NaN
102,NaN,NaN,10354.88,NaN
103,NaN,NaN,10354.88,NaN
104,NaN,NaN,10354.88,NaN
105,NaN,NaN,10354.88,NaN
106,NaN,NaN,10354.88,NaN
107,NaN,NaN,10354.88,NaN
108,NaN,NaN,10354.88,NaN
109,NaN,NaN,10354.88,NaN
110,NaN,NaN,10354.88,NaN
111,NaN,NaN,10354.88,NaN
112,NaN,NaN,10354.88,NaN
113,NaN,NaN,10354.88,NaN
114,NaN,NaN,10354.88,NaN
115,NaN,NaN,10354.88,NaN
116,NaN,NaN,10354.88,NaN
117,NaN,NaN,10354.88,NaN
118,NaN,NaN,10354.88,NaN
119,NaN,NaN,10354.88,NaN
120,NaN,NaN,18372.53,NaN
code,1776418956,1776418956,1776418956,1776418956
configuration,,,,
experiment_run,1,1,2,2
client,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,455.00,455.00,455.00,455.00
time_ingest,141.00,141.00,141.00,141.00
time_check,291.00,291.00,291.00,291.00
terminals,0,0,0,0
pods,1,2,1,2
tenant,,,,
num_worker,0,0,0,0
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,8187,8187,8187,8187
host_RAM,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,
host_Cores,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151015,151015,151015,151015
host_datadisk,8187,8187,8187,8187
host_volume_size,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3
loading_parameters_PODS_TOTAL,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1
loading_parameters_TPCH_TABLE,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
benchmarking_parameters_SF,3,3,3,3
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2

In [17]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head()

,phase,code,configuration,experiment_run,client,type_tenants,num_tenants,vol_tenants
phase,,,,,,,,
1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-1,1776418956,,1,1,,0,False
1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956,,1,2,,0,False
1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-1,1776418956,,2,1,,0,False
1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776418956,,2,2,,0,False

# Time Series of a Single Metric for All Experiments

In [18]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_all(metric=metric)
df.head()

,timestamp,code,phase,experiment_run,client,type_tenants,vol_tenants,num_tenants,metric,component,value
0,0,1776418956,1776418956-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9770.97
1,0,1776418956,1776418956-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10315.59
2,0,1776418956,1776418956-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,10315.64
3,0,1776418956,1776418956-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10300.51
4,0,1776420958,1776420958-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13877.75

In [19]:
df[['timestamp', 'phase', 'value']].head(8)

   timestamp                            phase    value
0          0  1776418956-PostgreSQL-BHT-8-1-1  9770.97
1          0  1776418956-PostgreSQL-BHT-8-1-2 10315.59
2          0  1776418956-PostgreSQL-BHT-8-2-1 10315.64
3          0  1776418956-PostgreSQL-BHT-8-2-2 10300.51
4          0  1776420958-PostgreSQL-BHT-8-1-1 13877.75
5          0  1776420958-PostgreSQL-BHT-8-1-2 14874.78
6          0  1776420958-PostgreSQL-BHT-8-2-1 14904.29
7          0  1776420958-PostgreSQL-BHT-8-2-2 14743.28

In [20]:
df=collect.add_metadata(df)
df = df.sort_values(['timestamp', 'phase'])
df[['timestamp', 'phase', 'value']].head(8)

combine on columns phase

,timestamp,phase,value
1776418956-PostgreSQL-BHT-8-1-1,0,1776418956-PostgreSQL-BHT-8-1-1,9770.97
1776418956-PostgreSQL-BHT-8-1-2,0,1776418956-PostgreSQL-BHT-8-1-2,10315.59
1776418956-PostgreSQL-BHT-8-2-1,0,1776418956-PostgreSQL-BHT-8-2-1,10315.64
1776418956-PostgreSQL-BHT-8-2-2,0,1776418956-PostgreSQL-BHT-8-2-2,10300.51
1776420958-PostgreSQL-BHT-8-1-1,0,1776420958-PostgreSQL-BHT-8-1-1,13877.75
1776420958-PostgreSQL-BHT-8-1-2,0,1776420958-PostgreSQL-BHT-8-1-2,14874.78
1776420958-PostgreSQL-BHT-8-2-1,0,1776420958-PostgreSQL-BHT-8-2-1,14904.29
1776420958-PostgreSQL-BHT-8-2-2,0,1776420958-PostgreSQL-BHT-8-2-2,14743.28

In [21]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head()

,phase,code,configuration,experiment_run,client,type_tenants,num_tenants,vol_tenants
1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-1,1776418956,,1,1,,0,False
1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956,,1,2,,0,False
1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-1,1776418956,,2,1,,0,False
1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776418956,,2,2,,0,False
1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-1,1776420958,,1,1,,0,False

## Custom Aggregation and Scale

In [22]:
metric = 'total_cpu_util'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["code", "experiment_run", "client", "type_tenants", "num_tenants"])["value"]
      .max()
      .reset_index()
)
#plot_bars(df_agg, y='value', title='Max CPU Utilization [%]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)
df_agg.index.name = 'Max ' + collect.df_metrics.loc[metric]['title']
df_agg

,code,experiment_run,client,type_tenants,num_tenants,value
Max CPU Utilization,,,,,,
0,1776418956,1,1,,0,3.89
1,1776418956,1,2,,0,6.29
2,1776418956,2,1,,0,3.42
3,1776418956,2,2,,0,7.55
4,1776420958,1,1,,0,4.60
5,1776420958,1,2,,0,11.47
6,1776420958,2,1,,0,5.81
7,1776420958,2,2,,0,11.64

# Performance Results per Connection

In [23]:
df_performance = collect.get_performance_per_connection()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

,1776418956-PostgreSQL-BHT-8-1-1-1,1776418956-PostgreSQL-BHT-8-1-2-1,1776418956-PostgreSQL-BHT-8-1-2-2,1776418956-PostgreSQL-BHT-8-2-1-1,1776418956-PostgreSQL-BHT-8-2-2-1,1776418956-PostgreSQL-BHT-8-2-2-2,1776420958-PostgreSQL-BHT-8-1-1-1,1776420958-PostgreSQL-BHT-8-1-2-1,1776420958-PostgreSQL-BHT-8-1-2-2,1776420958-PostgreSQL-BHT-8-2-1-1,1776420958-PostgreSQL-BHT-8-2-2-1,1776420958-PostgreSQL-BHT-8-2-2-2
total_timer_execution,1.57,1.60,1.55,2.35,1.59,1.59,2.91,2.93,2.91,4.24,2.99,2.92
Power@Size [~Q/h],6894.44,6762.32,6966.21,4604.28,6799.26,6798.92,7413.94,7359.71,7429.68,5088.76,7231.64,7401.62
Geo Times [s],1.57,1.60,1.55,2.35,1.59,1.59,2.91,2.93,2.91,4.24,2.99,2.92
configuration,1776418956--,1776418956--,1776418956--,1776418956--,1776418956--,1776418956--,1776420958--,1776420958--,1776420958--,1776420958--,1776420958--,1776420958--
connection,1776418956-PostgreSQL-BHT-8-1-1-1,1776418956-PostgreSQL-BHT-8-1-2-1,1776418956-PostgreSQL-BHT-8-1-2-2,1776418956-PostgreSQL-BHT-8-2-1-1,1776418956-PostgreSQL-BHT-8-2-2-1,1776418956-PostgreSQL-BHT-8-2-2-2,1776420958-PostgreSQL-BHT-8-1-1-1,1776420958-PostgreSQL-BHT-8-1-2-1,1776420958-PostgreSQL-BHT-8-1-2-2,1776420958-PostgreSQL-BHT-8-2-1-1,1776420958-PostgreSQL-BHT-8-2-2-1,1776420958-PostgreSQL-BHT-8-2-2-2
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2
SF,3.00,3.00,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
time [s],58,60,57,120,59,60,113,110,110,210,119,116
pod_count,1,1,1,1,1,1,1,1,1,1,1,1
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22
Throughput@Size,4096.55,3960.00,4168.42,1980.00,4027.12,3960.00,4205.31,4320.00,4320.00,2262.86,3993.28,4096.55
code,1776418956,1776418956,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958,1776420958,1776420958

### Add Metadata

In [24]:
df = collect.add_metadata(df_performance)
df.T

combine on columns phase

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2
total_timer_execution,1.57,1.60,1.55,2.35,1.59,1.59,2.91,2.93,2.91,4.24,2.99,2.92
Power@Size [~Q/h],6894.44,6762.32,6966.21,4604.28,6799.26,6798.92,7413.94,7359.71,7429.68,5088.76,7231.64,7401.62
Geo Times [s],1.57,1.60,1.55,2.35,1.59,1.59,2.91,2.93,2.91,4.24,2.99,2.92
configuration,1776418956--,1776418956--,1776418956--,1776418956--,1776418956--,1776418956--,1776420958--,1776420958--,1776420958--,1776420958--,1776420958--,1776420958--
connection,1776418956-PostgreSQL-BHT-8-1-1-1,1776418956-PostgreSQL-BHT-8-1-2-1,1776418956-PostgreSQL-BHT-8-1-2-2,1776418956-PostgreSQL-BHT-8-2-1-1,1776418956-PostgreSQL-BHT-8-2-2-1,1776418956-PostgreSQL-BHT-8-2-2-2,1776420958-PostgreSQL-BHT-8-1-1-1,1776420958-PostgreSQL-BHT-8-1-2-1,1776420958-PostgreSQL-BHT-8-1-2-2,1776420958-PostgreSQL-BHT-8-2-1-1,1776420958-PostgreSQL-BHT-8-2-2-1,1776420958-PostgreSQL-BHT-8-2-2-2
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2
SF,3.00,3.00,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
time [s],58,60,57,120,59,60,113,110,110,210,119,116
pod_count,1,1,1,1,1,1,1,1,1,1,1,1
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22
Throughput@Size,4096.55,3960.00,4168.42,1980.00,4027.12,3960.00,4205.31,4320.00,4320.00,2262.86,3993.28,4096.55
code,1776418956,1776418956,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958,1776420958,1776420958
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,455.00,455.00,455.00,455.00,455.00,455.00,1256.00,1256.00,1256.00,1256.00,1256.00,1256.00
time_ingest,141.00,141.00,141.00,141.00,141.00,141.00,350.00,350.00,350.00,350.00,350.00,350.00
time_check,291.00,291.00,291.00,291.00,291.00,291.00,843.00,843.00,843.00,843.00,843.00,843.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,2,1,2,2,1,2,2,1,2,2
tenant,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151015,151015,151015,151015,151015,151015,151015,151015,151015,151015,151015,151015
host_datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G
host_cuda,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Performance Results per Total

In [25]:
df_performance = collect.get_performance_aggregated_per_phase()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)

In [26]:
df_performance.T

,1776418956-PostgreSQL-BHT-8-1-1-1,1776418956-PostgreSQL-BHT-8-1-2-1,1776418956-PostgreSQL-BHT-8-1-2-2,1776418956-PostgreSQL-BHT-8-2-1-1,1776418956-PostgreSQL-BHT-8-2-2-1,1776418956-PostgreSQL-BHT-8-2-2-2,1776420958-PostgreSQL-BHT-8-1-1-1,1776420958-PostgreSQL-BHT-8-1-2-1,1776420958-PostgreSQL-BHT-8-1-2-2,1776420958-PostgreSQL-BHT-8-2-1-1,1776420958-PostgreSQL-BHT-8-2-2-1,1776420958-PostgreSQL-BHT-8-2-2-2
configuration,1776418956--,1776418956--,1776418956--,1776418956--,1776418956--,1776418956--,1776420958--,1776420958--,1776420958--,1776420958--,1776420958--,1776420958--
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2
total_timer_execution,1.57,1.60,1.55,2.35,1.59,1.59,2.91,2.93,2.91,4.24,2.99,2.92
Power@Size [~Q/h],6894.44,6762.32,6966.21,4604.28,6799.26,6798.92,7413.94,7359.71,7429.68,5088.76,7231.64,7401.62
code,1776418956,1776418956,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958,1776420958,1776420958
pod_count,1,1,1,1,1,1,1,1,1,1,1,1
SF,3.00,3.00,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00
time [s],58,60,57,120,59,60,113,110,110,210,119,116
client,1,2,2,1,2,2,1,2,2,1,2,2
Throughput@Size,4096.55,3960.00,4168.42,1980.00,4027.12,3960.00,4205.31,4320.00,4320.00,2262.86,3993.28,4096.55
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22

### With Metadata

In [27]:
df = collect.add_metadata(df_performance)
df.T

combine on columns phase

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2
configuration,1776418956--,1776418956--,1776418956--,1776418956--,1776418956--,1776418956--,1776420958--,1776420958--,1776420958--,1776420958--,1776420958--,1776420958--
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2
total_timer_execution,1.57,1.60,1.55,2.35,1.59,1.59,2.91,2.93,2.91,4.24,2.99,2.92
Power@Size [~Q/h],6894.44,6762.32,6966.21,4604.28,6799.26,6798.92,7413.94,7359.71,7429.68,5088.76,7231.64,7401.62
code,1776418956,1776418956,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958,1776420958,1776420958
pod_count,1,1,1,1,1,1,1,1,1,1,1,1
SF,3.00,3.00,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00
time [s],58,60,57,120,59,60,113,110,110,210,119,116
client,1,2,2,1,2,2,1,2,2,1,2,2
Throughput@Size,4096.55,3960.00,4168.42,1980.00,4027.12,3960.00,4205.31,4320.00,4320.00,2262.86,3993.28,4096.55
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,455.00,455.00,455.00,455.00,455.00,455.00,1256.00,1256.00,1256.00,1256.00,1256.00,1256.00
time_ingest,141.00,141.00,141.00,141.00,141.00,141.00,350.00,350.00,350.00,350.00,350.00,350.00
time_check,291.00,291.00,291.00,291.00,291.00,291.00,843.00,843.00,843.00,843.00,843.00,843.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,2,1,2,2,1,2,2,1,2,2
tenant,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151015,151015,151015,151015,151015,151015,151015,151015,151015,151015,151015,151015
host_datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G
host_cuda,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [28]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']]

,phase,code,configuration,experiment_run,client,type_tenants,num_tenants,vol_tenants
1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-1,1776418956,1776418956--,1,1,,0,False
1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956,1776418956--,1,2,,0,False
1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956,1776418956--,1,2,,0,False
1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-1,1776418956,1776418956--,2,1,,0,False
1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776418956,1776418956--,2,2,,0,False
1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776418956,1776418956--,2,2,,0,False
1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-1,1776420958,1776420958--,1,1,,0,False
1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958,1776420958--,1,2,,0,False
1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958,1776420958--,1,2,,0,False
1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-1,1776420958,1776420958--,2,1,,0,False
1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2,1776420958,1776420958--,2,2,,0,False
1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2,1776420958,1776420958--,2,2,,0,False

In [29]:
collectors.get_non_constant(df).T

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2
configuration,1776418956--,1776418956--,1776418956--,1776418956--,1776418956--,1776418956--,1776420958--,1776420958--,1776420958--,1776420958--,1776420958--,1776420958--
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2
total_timer_execution,1.57,1.60,1.55,2.35,1.59,1.59,2.91,2.93,2.91,4.24,2.99,2.92
Power@Size [~Q/h],6894.44,6762.32,6966.21,4604.28,6799.26,6798.92,7413.94,7359.71,7429.68,5088.76,7231.64,7401.62
code,1776418956,1776418956,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958,1776420958,1776420958
SF,3.00,3.00,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00
time [s],58,60,57,120,59,60,113,110,110,210,119,116
client,1,2,2,1,2,2,1,2,2,1,2,2
Throughput@Size,4096.55,3960.00,4168.42,1980.00,4027.12,3960.00,4205.31,4320.00,4320.00,2262.86,3993.28,4096.55
time_load,455.00,455.00,455.00,455.00,455.00,455.00,1256.00,1256.00,1256.00,1256.00,1256.00,1256.00
time_ingest,141.00,141.00,141.00,141.00,141.00,141.00,350.00,350.00,350.00,350.00,350.00,350.00
time_check,291.00,291.00,291.00,291.00,291.00,291.00,843.00,843.00,843.00,843.00,843.00,843.00
pods,1,2,2,1,2,2,1,2,2,1,2,2
datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G
loading_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
benchmarking_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958

# Performance at Ingestion

In [30]:
df_performance = collect.get_connections()
#df_performance = collect.get_loading_time_max_all()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
code,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958
connection,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2
configuration,,,,,,,,
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,455.00,455.00,455.00,455.00,1256.00,1256.00,1256.00,1256.00
time_ingest,141.00,141.00,141.00,141.00,350.00,350.00,350.00,350.00
time_check,291.00,291.00,291.00,291.00,843.00,843.00,843.00,843.00
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151015,151015,151015,151015,151015,151015,151015,151015
host_datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Hardware Monitoring for Loading Phase

In [31]:
df_performance = collect.get_monitoring_aggregated_per_phase("loading")
df_performance = collect.add_metadata(df_performance)
#df_performance_first = df_performance[df_performance['client']==1]
#df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

combine on index and column 'phase'

phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2
Memory Usage [MiB],7122.96,7122.96,9493.28,9493.28
Memory Usage Cached [MiB],9772.04,9772.04,15577.73,15577.73
CPU Utilization,1.08,1.08,0.95,0.95
CPU Throttle,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0,0,0,0
CPU Utilization Time [s],303.26,303.26,819.77,819.77
CPU User Time [s],236.03,236.03,686.43,686.43
CPU System Time [s],67.23,67.23,133.34,133.34
Network Rx Total [MiB],3319.50,3319.50,6675.75,6675.75
Network Tx Total [MiB],2624.35,2624.35,6061.46,6061.46
Filesystem Read Total [MiB],0.02,0.02,0.03,0.03
Filesystem Write Total [MiB],0.02,0.02,0.02,0.02
Core Utilization Variance [%],0.01,0.01,0.23,0.23
Max Core Utilization [%],0.36,0.36,14.17,14.17
I/O Wait [%],18.43,18.43,19.70,19.70
Total I/O Wait Time [s],116.48,116.48,293.22,293.22
Number of Idle Sessions,0.10,0.10,0.18,0.18
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00
Number of Active Sessions,9,9,9,9
Number of Active Application Sessions,8,8,8,8
Longest Active Transaction,16.21,16.21,77.34,77.34
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.41,0.41,0.68,0.68
Active Backends Waiting on WAL,2.47,2.47,2.49,2.49
Active Backends Waiting on Locks,0.21,0.21,0.04,0.04
Max Transaction Duration (I/O Wait),2.80,2.80,28.78,28.78
Max Transaction Duration (WAL Wait),11.34,11.34,39.40,39.40
Max Transaction Duration (Lock Wait),0.46,0.46,0.00,0.00
Disk Blocks Read Count,419853,419853,901747,901747
Buffer Cache Hit Count,3561934,3561934,7755676,7755676
Buffer Cache Hit Ratio,0.89,0.89,0.93,0.93
Index Scan Count,0,0,0,0
Index Tuple Fetch Count,0,0,0,0
Index Cache Hit Ratio,0.15,0.15,0.26,0.26
Table Buffer Hit Count,3512829,3512829,7648587,7648587
Table Blocks Read Count,419375,419375,901269,901269
Table Cache Hit Ratio,0.88,0.88,0.93,0.93
Total Cache Hit Ratio,0.88,0.88,0.93,0.93
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0,0,0,0
Total Locks Current,7.60,7.60,9.16,9.16
AccessExclusiveLocks Current,0.21,0.21,0.14,0.14
AccessShareLocks Current,2.77,2.77,4.66,4.66
ExclusiveLocks Current,0.31,0.31,0.14,0.14
RowExclusiveLocks Current,3.90,3.90,3.06,3.06
RowShareLocks Current,0.10,0.10,0.35,0.35
ShareLocks Current,0.10,0.10,0.11,0.11
ShareRowExclusiveLocks Current,0.21,0.21,0.70,0.70
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0,0,0,0
Autovacuum Run Count,0,0,0,0
Dead tuples per vacuum operation [tuples/vacuum],0.00,0.00,0.00,0.00
Number of WAL Segments,119.49,119.49,272.17,272.17
Total WAL Size [GiB],1.87,1.87,4.25,4.25
WAL Segments Growth Rate [segments/s],0.44,0.44,0.48,0.48
WAL Growth Rate [MiB/s],7.08,7.08,7.64,7.64
Average WAL Segment Size [MiB],14.79,14.79,15.81,15.81
code,1776418956,1776418956,1776420958,1776420958
configuration,,,,
experiment_run,1,1,1,1
client,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,455.00,455.00,1256.00,1256.00
time_ingest,141.00,141.00,350.00,350.00
time_check,291.00,291.00,843.00,843.00
terminals,0,0,0,0
pods,1,2,1,2
tenant,,,,
num_worker,0,0,0,0
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,8187,8187,16350,16350
host_RAM,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,
host_Cores,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151015,151015,151015,151015
host_datadisk,8187,8187,16350,16350
host_volume_size,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,16G,16G
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,6,6
loading_parameters_PODS_TOTAL,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1
loading_parameters_TPCH_TABLE,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
benchmarking_parameters_SF,3,3,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2

In [32]:
#plot_bars(df_performance, y='CPU Utilization Time [s]', title='CPU [CPUs]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [33]:
#plot_bars(df_performance, y='Memory Usage [MiB]', title='Memory Usage [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [34]:
#plot_bars(df_performance, y='Memory Usage Cached [MiB]', title='Memory Usage Cached [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Efficiency

In [35]:
client = 1

df_performance_monitoring = collect.get_monitoring_aggregated_per_phase(type="stream")
#df_performance_monitoring = df_performance_monitoring[df_performance_monitoring['client'] == client]
df_performance = collect.get_performance_aggregated_per_phase()
#df_performance = df_performance[df_performance['client'] == client]
merged_df = pd.merge(df_performance, df_performance_monitoring, left_index=True, right_index=True, how='left')
#merged_df = pd.merge(df_performance, df_performance_monitoring, on=['phase'], how='inner')
#merged_df['I_Lat'] = 1./merged_df['E_Lat']
merged_df = merged_df[merged_df['client'] == client]
#merged_df['E_Tpx'] = merged_df['Goodput (requests/second)'] / merged_df['CPU Utilization Time [s]'] * 600.
#merged_df['E_Lat'] = 1./np.sqrt(merged_df['Latency Distribution.Average Latency (microseconds)']*merged_df['CPU Utilization Time [s]']/1E6)
#merged_df['E_RAM'] = (merged_df['Goodput (requests/second)']) / merged_df['Memory Usage [MiB]']
merged_df.T

,1776418956-PostgreSQL-BHT-8-1-1-1,1776418956-PostgreSQL-BHT-8-2-1-1,1776420958-PostgreSQL-BHT-8-1-1-1,1776420958-PostgreSQL-BHT-8-2-1-1
configuration,1776418956--,1776418956--,1776420958--,1776420958--
experiment_run,1,2,1,2
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-2-1
total_timer_execution,1.57,2.35,2.91,4.24
Power@Size [~Q/h],6894.44,4604.28,7413.94,5088.76
code,1776418956,1776418956,1776420958,1776420958
pod_count,1,1,1,1
SF,3.00,3.00,6.00,6.00
time [s],58,120,113,210
client,1,1,1,1
Throughput@Size,4096.55,1980.00,4205.31,2262.86
num_of_queries,22,22,22,22
Memory Usage [MiB],NaN,NaN,NaN,NaN
Memory Usage Cached [MiB],NaN,NaN,NaN,NaN
CPU Utilization,NaN,NaN,NaN,NaN
CPU Throttle,NaN,NaN,NaN,NaN
CPU Throttled Time [s],NaN,NaN,NaN,NaN
CPU Utilization Time [s],NaN,NaN,NaN,NaN
CPU User Time [s],NaN,NaN,NaN,NaN
CPU System Time [s],NaN,NaN,NaN,NaN
Network Rx Total [MiB],NaN,NaN,NaN,NaN
Network Tx Total [MiB],NaN,NaN,NaN,NaN
Filesystem Read Total [MiB],NaN,NaN,NaN,NaN
Filesystem Write Total [MiB],NaN,NaN,NaN,NaN
Core Utilization Variance [%],NaN,NaN,NaN,NaN
Max Core Utilization [%],NaN,NaN,NaN,NaN
I/O Wait [%],NaN,NaN,NaN,NaN
Total I/O Wait Time [s],NaN,NaN,NaN,NaN
Number of Idle Sessions,NaN,NaN,NaN,NaN
Number of Idle-in-transaction Sessions,NaN,NaN,NaN,NaN
Number of Idle-in-transaction Aborted Sessions,NaN,NaN,NaN,NaN
Number of Active Sessions,NaN,NaN,NaN,NaN
Number of Active Application Sessions,NaN,NaN,NaN,NaN
Longest Active Transaction,NaN,NaN,NaN,NaN
Longest Idle Session (no transaction),NaN,NaN,NaN,NaN
Longest Idle-in-Transaction,NaN,NaN,NaN,NaN
Longest Idle-in-Transaction (Aborted),NaN,NaN,NaN,NaN
Active Backends Waiting on I/O,NaN,NaN,NaN,NaN
Active Backends Waiting on WAL,NaN,NaN,NaN,NaN
Active Backends Waiting on Locks,NaN,NaN,NaN,NaN
Max Transaction Duration (I/O Wait),NaN,NaN,NaN,NaN
Max Transaction Duration (WAL Wait),NaN,NaN,NaN,NaN
Max Transaction Duration (Lock Wait),NaN,NaN,NaN,NaN
Disk Blocks Read Count,NaN,NaN,NaN,NaN
Buffer Cache Hit Count,NaN,NaN,NaN,NaN
Buffer Cache Hit Ratio,NaN,NaN,NaN,NaN
Index Scan Count,NaN,NaN,NaN,NaN
Index Tuple Fetch Count,NaN,NaN,NaN,NaN
Index Cache Hit Ratio,NaN,NaN,NaN,NaN
Table Buffer Hit Count,NaN,NaN,NaN,NaN
Table Blocks Read Count,NaN,NaN,NaN,NaN
Table Cache Hit Ratio,NaN,NaN,NaN,NaN
Total Cache Hit Ratio,NaN,NaN,NaN,NaN
BGWriter Efficiency Ratio (Cleaned / Allocated),NaN,NaN,NaN,NaN
BGWriter Stopped Due to Max Pages,NaN,NaN,NaN,NaN
Total Locks Current,NaN,NaN,NaN,NaN
AccessExclusiveLocks Current,NaN,NaN,NaN,NaN
AccessShareLocks Current,NaN,NaN,NaN,NaN
ExclusiveLocks Current,NaN,NaN,NaN,NaN
RowExclusiveLocks Current,NaN,NaN,NaN,NaN
RowShareLocks Current,NaN,NaN,NaN,NaN
ShareLocks Current,NaN,NaN,NaN,NaN
ShareRowExclusiveLocks Current,NaN,NaN,NaN,NaN
ShareUpdateExclusiveLocks Current,NaN,NaN,NaN,NaN
SIReadLocks Current,NaN,NaN,NaN,NaN
Autoanalyze Run Count,NaN,NaN,NaN,NaN
Autovacuum Run Count,NaN,NaN,NaN,NaN
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,NaN,NaN
Number of WAL Segments,NaN,NaN,NaN,NaN
Total WAL Size [GiB],NaN,NaN,NaN,NaN
WAL Segments Growth Rate [segments/s],NaN,NaN,NaN,NaN
WAL Growth Rate [MiB/s],NaN,NaN,NaN,NaN
Average WAL Segment Size [MiB],NaN,NaN,NaN,NaN

In [36]:
df = collect.add_metadata(merged_df)
df.T

combine on columns phase

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
configuration,1776418956--,,1776418956--,,1776420958--,,1776420958--,
experiment_run,1.00,1,2.00,2,1.00,1,2.00,2
phase,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
total_timer_execution,1.57,NaN,2.35,NaN,2.91,NaN,4.24,NaN
Power@Size [~Q/h],6894.44,NaN,4604.28,NaN,7413.94,NaN,5088.76,NaN
code,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958
pod_count,1.00,NaN,1.00,NaN,1.00,NaN,1.00,NaN
SF,3.00,NaN,3.00,NaN,6.00,NaN,6.00,NaN
time [s],58.00,NaN,120.00,NaN,113.00,NaN,210.00,NaN
client,1.00,2,1.00,2,1.00,2,1.00,2
Throughput@Size,4096.55,NaN,1980.00,NaN,4205.31,NaN,2262.86,NaN
num_of_queries,22.00,NaN,22.00,NaN,22.00,NaN,22.00,NaN
Memory Usage [MiB],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Memory Usage Cached [MiB],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CPU Utilization,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CPU Throttle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CPU Throttled Time [s],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CPU Utilization Time [s],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CPU User Time [s],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CPU System Time [s],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Network Rx Total [MiB],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Network Tx Total [MiB],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Filesystem Read Total [MiB],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Filesystem Write Total [MiB],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Core Utilization Variance [%],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Max Core Utilization [%],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
I/O Wait [%],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total I/O Wait Time [s],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number of Idle Sessions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number of Idle-in-transaction Sessions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number of Idle-in-transaction Aborted Sessions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number of Active Sessions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number of Active Application Sessions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Longest Active Transaction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Longest Idle Session (no transaction),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Longest Idle-in-Transaction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Longest Idle-in-Transaction (Aborted),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Active Backends Waiting on I/O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Active Backends Waiting on WAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Active Backends Waiting on Locks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Max Transaction Duration (I/O Wait),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Max Transaction Duration (WAL Wait),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Max Transaction Duration (Lock Wait),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Disk Blocks Read Count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Buffer Cache Hit Count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Buffer Cache Hit Ratio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Index Scan Count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Index Tuple Fetch Count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Index Cache Hit Ratio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Table Buffer Hit Count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Table Blocks Read Count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Table Cache Hit Ratio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Cache Hit Ratio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BGWriter Efficiency Ratio (Cleaned / Allocated),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BGWriter Stopped Due to Max Pages,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total Locks Current,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AccessExclusiveLocks Current,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AccessShareLocks Current,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ExclusiveLocks Current,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RowExclusiveLocks Current,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RowShareLocks Current,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ShareLocks Current,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ShareRowExclusiveLocks Current,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ShareUpdateExclusiveLocks Current,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SIReadLocks Current,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Autoanalyze Run Count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Autovacuum Run Count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number of WAL Segments,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total WAL Size [GiB],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WAL Segments Growth Rate [segments/s],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WAL Growth Rate [MiB/s],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Average WAL Segment Size [MiB],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,455.00,455.00,455.00,455.00,1256.00,1256.00,1256.00,1256.00
time_ingest,141.00,141.00,141.00,141.00,350.00,350.00,350.00,350.00
time_check,291.00,291.00,291.00,291.00,843.00,843.00,843.00,843.00
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151015,151015,151015,151015,151015,151015,151015,151015
host_datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [37]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']]

,phase,code,configuration,experiment_run,client,type_tenants,num_tenants,vol_tenants
1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-1,1776418956,1776418956--,1.00,1.00,,0,False
1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-1-2,1776418956,,1,2,,0,False
1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-1,1776418956,1776418956--,2.00,1.00,,0,False
1776418956-PostgreSQL-BHT-8-2-2,1776418956-PostgreSQL-BHT-8-2-2,1776418956,,2,2,,0,False
1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-1,1776420958,1776420958--,1.00,1.00,,0,False
1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-1-2,1776420958,,1,2,,0,False
1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-1,1776420958,1776420958--,2.00,1.00,,0,False
1776420958-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-2-2,1776420958,,2,2,,0,False