# TPC-H Collector Demo

# Missing
* connection data beyond loading
* join to connection data
* join to monitoring_single
* connection and configuration also in monitoring and connection df

## Naming
* There is an experiment having a code, say `1775855486`.
* The experiment inspects a SUT, say `PostgreSQL-A`. This is called a `configuration`.
* The experiment is run several times, say twice. The indicator of the run is called `experiment_run`.
* Each run can have several phases as a sequence. The number of the phase is called `client`. The state of the configuration in a phase is called a `connection`.
* Each client can have several `pods`, that are run in parallel. A pod represents a driver.
* Performance metrics are collected per driver pod.  
    The naming of an instance is `<sut>-<experiment_run>-<client>-<pod>`. It is unique per experiment.
* Monitoring metrics are collected per phase. They are automatically aggregated across parallel pods.  
    The naming of an instance is `<sut>-<experiment_run>-<client>`. It is unique per experiment.

## Aggregation
* Aggregation is complicated. Some metrics are aggregated via count, sum, max or average. Others cannot be aggregated sensibly, like experiment code or latency percentiles.
* There are helper functions to aggregated pods that are certainly run in parallel.  
  So `<sut>-<experiment_run>-<client>-<pod>` are aggregated to `<sut>-<experiment_run>-<client>`.
* An exception is multi-tenancy.

## Class `collector`
* constructor `collectors.benchbase(path, codes)`
* evaluator object `evaluate = collect.get_evaluator()`
* dataframe of connection infos `collect.get_connections()`
  * index is name of client
* **monitoring metrics**
  * dataframe of available metrics `collect.df_metrics`
    * index is key of metric
  * dataframe of monitored components `collect.get_monitored_phases()`
    * index is key of component
  * dataframe of aggregated metrics per connection `collect.get_monitoring_single_all()`
    * index is name of client
    * metrics aggregated per code, experiment_run and client
  * dataframe of aggregated metrics per connection and across tenants `collect.get_monitoring_all()`
    * index just enumerates
    * metrics aggregated per code, experiment_run and client and across tenants
  * dataframe of time series for a metric of a connection in an experiment `collect.get_monitoring_timeseries_single(code, metric)`
    * index is name of connection
    * unstacked (wide format)
  * dataframe of time series for a metric in all experiments `collect.get_monitoring_timeseries_all(metric)`
    * index just enumerates
    * stacked (long format)
* **performance metrics**
  * dataframe of loading metrics `collect.get_loading_time_max_all()`
    * index is name of client
  * dataframe of performance aggregated per parallel client `collect.get_performance_all()`
    * index just enumerates
    * performance aggregated per code, experiment_run and client
  * dataframe of performance for one experiment `collect.get_performance_single()`
    * performance of each single client (driver)
    * index is name of client pod
  * dataframe of performance for all experiments `collect.get_performance_all_single()`
    * performance of each single client (driver)
    * index is name of client pod


[1] [Benchmarking Multi-Tenant Architectures in PostgreSQL](https://doi.org/10.48786/edbt.2026.46)
> Erdelt, P.K., and Rabl T. (2026)
> In: Proceedings 29th International Conference on Extending Database Technology, EDBT 2026
> OpenProceedings.org
> https://doi.org/10.48786/edbt.2026.46

In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option('display.max_colwidth', None)
pd.options.display.max_columns = None
pd.options.display.max_rows = None

from bexhoma import collectors

%matplotlib inline

# Functions for Nice Plots

In [2]:
from notebookutils import *

# Collect Results

In [3]:
path = r"D:\data\benchmarks"
#path = r"/data/benchmarks"
filename_prefix = "demo_"
b_plot_save = False
b_skip_plots = True

In [4]:
codes = [
    "1776508434",
    "1776550283"
]

codes

['1776508434', '1776550283']

In [5]:
collect = collectors.default(path, codes)

# Get all Metrics Metadata

## Metrics Names and Types

Metrics that are derived from monitoring

In [6]:
collect.df_metrics

,title,active,type,metric
total_cpu_memory,Memory Usage [MiB],True,cluster,gauge
total_cpu_memory_cached,Memory Usage Cached [MiB],True,cluster,gauge
total_cpu_util,CPU Utilization,True,cluster,gauge
total_cpu_throttled,CPU Throttle,True,cluster,gauge
total_cpu_throttled_s,CPU Throttled Time [s],True,cluster,counter
total_cpu_util_others,CPU Utilization Others,False,cluster,gauge
total_cpu_util_s,CPU Utilization Time [s],True,cluster,counter
total_cpu_util_user_s,CPU User Time [s],True,cluster,counter
total_cpu_util_sys_s,CPU System Time [s],True,cluster,counter
total_cpu_util_others_s,CPU Utilization Time Others [s],False,cluster,counter
total_network_rx,Network Rx Total [MiB],True,cluster,counter
total_network_tx,Network Tx Total [MiB],True,cluster,counter
total_fs_read,Filesystem Read Total [MiB],True,cluster,counter
total_fs_write,Filesystem Write Total [MiB],True,cluster,counter
total_gpu_util,GPU Utilization [%],False,cluster,gauge
total_gpu_power,GPU Power Usage [W],False,cluster,gauge
total_gpu_memory,GPU Memory Usage [MiB],False,cluster,gauge
core_variance,Core Utilization Variance [%],True,cluster,ratio
max_core_util,Max Core Utilization [%],True,cluster,ratio
io_wait_pct,I/O Wait [%],True,cluster,ratio
io_wait_total,Total I/O Wait Time [s],True,cluster,counter
pg_stat_activity_count_idle,Number of Idle Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction,Number of Idle-in-transaction Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction_aborted,Number of Idle-in-transaction Aborted Sessions,True,application,gauge
pg_stat_activity_count_active,Number of Active Sessions,True,application,counter
pg_stat_activity_count_active_app,Number of Active Application Sessions,True,application,counter
pg_stat_activity_max_tx_duration_active,Longest Active Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle,Longest Idle Session (no transaction),True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx,Longest Idle-in-Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx_aborted,Longest Idle-in-Transaction (Aborted),True,application,ratio
pg_stat_activity_count_io,Active Backends Waiting on I/O,True,application,gauge
pg_stat_activity_count_wal,Active Backends Waiting on WAL,True,application,gauge
pg_stat_activity_count_lock,Active Backends Waiting on Locks,True,application,gauge
pg_stat_activity_max_tx_duration_io,Max Transaction Duration (I/O Wait),True,application,ratio
pg_stat_activity_max_tx_duration_wal,Max Transaction Duration (WAL Wait),True,application,ratio
pg_stat_activity_max_tx_duration_lock,Max Transaction Duration (Lock Wait),True,application,ratio
pg_stat_database_blks_read,Disk Blocks Read Count,True,application,counter
pg_stat_database_blks_hit,Buffer Cache Hit Count,True,application,counter
cache_hit_ratio,Buffer Cache Hit Ratio,True,application,ratio
pg_stat_user_tables_idx_scan,Index Scan Count,True,application,counter
pg_stat_user_tables_idx_tup_fetch,Index Tuple Fetch Count,True,application,counter
pg_statio_user_tables_idx_cache_hit_ratio,Index Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_heap_blocks_hit,Table Buffer Hit Count,True,application,counter
pg_statio_user_tables_heap_blocks_read,Table Blocks Read Count,True,application,counter
pg_statio_user_tables_heap_cache_hit_ratio,Table Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_total_cache_hit_ratio,Total Cache Hit Ratio,True,application,ratio
pg_stat_bgwriter_efficiency_ratio,BGWriter Efficiency Ratio (Cleaned / Allocated),True,application,ratio
pg_stat_bgwriter_maxwritten_clean_total,BGWriter Stopped Due to Max Pages,True,application,counter
pg_stat_bgwriter_checkpoint_sync_time_total,Checkpoint Sync Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_total,Checkpoint Write Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_per_sync_time,Time spent writing vs syncing during checkpoints [ratio],False,application,ratio
pg_locks_count,Total Locks Current,True,application,gauge
pg_locks_count_accessexclusivelock,AccessExclusiveLocks Current,True,application,gauge
pg_locks_count_accesssharelock,AccessShareLocks Current,True,application,gauge
pg_locks_count_exclusivelock,ExclusiveLocks Current,True,application,gauge
pg_locks_count_rowexclusivelock,RowExclusiveLocks Current,True,application,gauge
pg_locks_count_rowsharelock,RowShareLocks Current,True,application,gauge
pg_locks_count_sharelock,ShareLocks Current,True,application,gauge
pg_locks_count_sharerowexclusivelock,ShareRowExclusiveLocks Current,True,application,gauge
pg_locks_count_shareupdateexclusivelock,ShareUpdateExclusiveLocks Current,True,application,gauge
pg_locks_count_sireadlock,SIReadLocks Current,True,application,gauge
pg_stat_user_tables_autoanalyze_count,Autoanalyze Run Count,True,application,counter
pg_stat_user_tables_autovacuum_count,Autovacuum Run Count,True,application,counter
pg_stat_bgwriter_checkpoints_timed_per_req,Frequency of checkpoints (timed vs requested) [ratio],False,application,gauge
pg_stat_wal_volume_bytes_sec,Volume of WAL generated [bytes/sec],False,application,counter
pg_stat_bgwriter_buffers_backend_fsync,Backends forced to flush WAL (I/O contention) [fsync/sec],False,application,counter
pg_stat_activity_wait_event_count,Active sessions waiting on any event [count],False,application,gauge
pg_stat_user_tables_dead_tuples_per_vacuum,Dead tuples per vacuum operation [tuples/vacuum],True,application,ratio
pg_wal_segments,Number of WAL Segments,True,application,gauge
pg_wal_size_bytes,Total WAL Size [GiB],True,application,gauge
pg_wal_segments_rate,WAL Segments Growth Rate [segments/s],True,application,gauge
pg_wal_size_rate,WAL Growth Rate [MiB/s],True,application,gauge
pg_wal_avg_segment_size,Average WAL Segment Size [MiB],True,application,gauge
pg_wal_size_per_checkpoint,WAL Size per Checkpoint [bytes/checkpoint],False,application,gauge

## Names of Monitored Phases

Names of components and their phases

In [7]:
collect.get_monitored_components()

                                           description
loading                  Loading phase: SUT deployment
datagenerator  Loading phase: component data generator
loader                 Loading phase: component loader
stream                 Execution phase: SUT deployment
benchmarker     Execution phase: component benchmarker

# Get Connection Infos

List of states of SUTs, containing loading infos.

In [8]:
df = collect.get_connections()
df.T

,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-1-1,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-2-1,1776550283-PostgreSQL-BHT-8-2-2
code,1776508434,1776508434,1776508434,1776508434,1776550283,1776550283,1776550283,1776550283
connection,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2
configuration,,,,,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8
phase,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-1-1,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-2-1,1776550283-PostgreSQL-BHT-8-2-2
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,49824.0,49824.0,49824.0,49824.0,114757.0,114757.0,114757.0,114757.0
time_ingest,22553.0,22553.0,22553.0,22553.0,52684.0,52684.0,52684.0,52684.0
time_check,27246.0,27246.0,27246.0,27246.0,62049.0,62049.0,62049.0,62049.0
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,0,0,0,0,0,0,0,0
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151024,151024,151025,151025,151030,151030,151031,151031
host_datadisk,0,0,0,0,0,0,0,0
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.1G,8.1G,16G,16G,16G,16G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776550283,bexhoma-sut-postgresql-bht-8-1776550283,bexhoma-sut-postgresql-bht-8-1776550283,bexhoma-sut-postgresql-bht-8-1776550283
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Get Aggregated Metrics per SUT and per Experiment

In [9]:
df_performance = collect.get_monitoring_aggregated_per_phase("stream")
df_performance.T

,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-1-1,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-2-1,1776550283-PostgreSQL-BHT-8-2-2
Memory Usage [MiB],10126.29,11046.67,10436.84,10392.82,16778.00,20248.53,13184.61,17880.38
Memory Usage Cached [MiB],15043.22,15963.60,17300.41,16850.84,26572.73,30043.26,25182.63,29738.30
CPU Utilization,1.60,3.12,2.26,3.05,2.34,4.57,2.68,6.16
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],134.77,284.83,329.93,204.73,402.12,749.50,692.74,874.70
CPU User Time [s],118.61,251.22,304.68,182.47,354.00,665.73,624.44,774.79
CPU System Time [s],16.16,33.61,25.25,22.26,48.12,83.77,68.30,99.92
Network Rx Total [MiB],1.86,0.51,1.74,1.88,2.21,4.07,1.92,3.74
Network Tx Total [MiB],2.85,4.49,1.72,3.35,7.95,9.88,1.91,3.73
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Core Utilization Variance [%],0.20,0.06,0.07,0.17,0.51,0.16,0.15,0.16
Max Core Utilization [%],6.57,1.54,3.23,9.61,33.33,5.14,4.51,4.55
I/O Wait [%],40.08,0.30,24.69,8.11,0.69,0.24,11.77,3.28
Total I/O Wait Time [s],0.08,1.83,50.38,0.03,2.13,0.01,84.34,2.20
Number of Idle Sessions,0.00,0.05,0.00,0.00,0.00,0.48,0.29,0.47
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,5.00,9.00,7.00,10.00,6.00,14.00,7.00,13.00
Number of Active Application Sessions,5.00,10.00,7.00,10.00,6.00,14.00,7.00,12.00
Longest Active Transaction,1.86,1.37,8.33,1.52,5.14,5.88,13.93,4.19
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,68955.00,0.00,69318.00,0.00,137809.00,0.00,1122706.00,0.00
Buffer Cache Hit Count,13036506.00,26204748.00,13042317.00,26204748.00,34291082.00,68845434.00,33315485.00,77405025.00
Buffer Cache Hit Ratio,0.96,0.99,0.98,1.00,0.99,1.00,0.77,0.98
Index Scan Count,1686496.00,3372992.00,1686496.00,3372992.00,5650695.00,11301390.00,5650695.00,11304819.00
Index Tuple Fetch Count,7893339.00,15786678.00,7893339.00,15786678.00,19034757.00,38069514.00,19034757.00,38167280.00
Index Cache Hit Ratio,0.76,0.99,0.53,0.99,1.00,1.00,0.76,1.00
Table Buffer Hit Count,8064868.00,16129736.00,8064528.00,16129736.00,17538340.00,35076680.00,16553654.00,43618554.00
Table Blocks Read Count,0.00,0.00,340.00,0.00,0.00,0.00,984686.00,0.00
Table Cache Hit Ratio,0.94,0.98,1.00,1.00,0.98,0.99,0.63,0.97
Total Cache Hit Ratio,0.95,0.98,1.00,1.00,0.99,1.00,0.66,0.98
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,16.78,19.00,11.40,11.00,10.10,31.83,22.47,31.25
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,16.78,19.00,11.40,11.00,10.10,31.83,22.47,31.25
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number of WAL Segments,205.00,205.00,206.00,206.00,378.00,378.00,378.00,378.00
Total WAL Size [GiB],3.20,3.20,3.22,3.22,5.91,5.91,5.91,5.91
WAL Segments Growth Rate [segments/s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
WAL Growth Rate [MiB/s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00

In [10]:
df_performance = collect.add_metadata(df_performance)
df_performance.T

combine on index and column 'phase'

phase,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-1-1,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-2-1,1776550283-PostgreSQL-BHT-8-2-2
Memory Usage [MiB],10126.29,11046.67,10436.84,10392.82,16778.0,20248.53,13184.61,17880.38
Memory Usage Cached [MiB],15043.22,15963.6,17300.41,16850.84,26572.73,30043.26,25182.63,29738.3
CPU Utilization,1.6,3.12,2.26,3.05,2.34,4.57,2.68,6.16
CPU Throttle,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CPU Throttled Time [s],0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CPU Utilization Time [s],134.77,284.83,329.93,204.73,402.12,749.5,692.74,874.7
CPU User Time [s],118.61,251.22,304.68,182.47,354.0,665.73,624.44,774.79
CPU System Time [s],16.16,33.61,25.25,22.26,48.12,83.77,68.3,99.92
Network Rx Total [MiB],1.86,0.51,1.74,1.88,2.21,4.07,1.92,3.74
Network Tx Total [MiB],2.85,4.49,1.72,3.35,7.95,9.88,1.91,3.73
Filesystem Read Total [MiB],0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Filesystem Write Total [MiB],0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Core Utilization Variance [%],0.2,0.06,0.07,0.17,0.51,0.16,0.15,0.16
Max Core Utilization [%],6.57,1.54,3.23,9.61,33.33,5.14,4.51,4.55
I/O Wait [%],40.08,0.3,24.69,8.11,0.69,0.24,11.77,3.28
Total I/O Wait Time [s],0.08,1.83,50.38,0.03,2.13,0.01,84.34,2.2
Number of Idle Sessions,0.0,0.05,0.0,0.0,0.0,0.48,0.29,0.47
Number of Idle-in-transaction Sessions,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Number of Idle-in-transaction Aborted Sessions,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Number of Active Sessions,5.0,9.0,7.0,10.0,6.0,14.0,7.0,13.0
Number of Active Application Sessions,5.0,10.0,7.0,10.0,6.0,14.0,7.0,12.0
Longest Active Transaction,1.86,1.37,8.33,1.52,5.14,5.88,13.93,4.19
Longest Idle Session (no transaction),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Longest Idle-in-Transaction,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Longest Idle-in-Transaction (Aborted),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Active Backends Waiting on I/O,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Active Backends Waiting on WAL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Active Backends Waiting on Locks,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Max Transaction Duration (I/O Wait),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Max Transaction Duration (WAL Wait),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Max Transaction Duration (Lock Wait),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Disk Blocks Read Count,68955.0,0.0,69318.0,0.0,137809.0,0.0,1122706.0,0.0
Buffer Cache Hit Count,13036506.0,26204748.0,13042317.0,26204748.0,34291082.0,68845434.0,33315485.0,77405025.0
Buffer Cache Hit Ratio,0.96,0.99,0.98,1.0,0.99,1.0,0.77,0.98
Index Scan Count,1686496.0,3372992.0,1686496.0,3372992.0,5650695.0,11301390.0,5650695.0,11304819.0
Index Tuple Fetch Count,7893339.0,15786678.0,7893339.0,15786678.0,19034757.0,38069514.0,19034757.0,38167280.0
Index Cache Hit Ratio,0.76,0.99,0.53,0.99,1.0,1.0,0.76,1.0
Table Buffer Hit Count,8064868.0,16129736.0,8064528.0,16129736.0,17538340.0,35076680.0,16553654.0,43618554.0
Table Blocks Read Count,0.0,0.0,340.0,0.0,0.0,0.0,984686.0,0.0
Table Cache Hit Ratio,0.94,0.98,1.0,1.0,0.98,0.99,0.63,0.97
Total Cache Hit Ratio,0.95,0.98,1.0,1.0,0.99,1.0,0.66,0.98
BGWriter Efficiency Ratio (Cleaned / Allocated),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BGWriter Stopped Due to Max Pages,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Total Locks Current,16.78,19.0,11.4,11.0,10.1,31.83,22.47,31.25
AccessExclusiveLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AccessShareLocks Current,16.78,19.0,11.4,11.0,10.1,31.83,22.47,31.25
ExclusiveLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RowExclusiveLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RowShareLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ShareLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ShareRowExclusiveLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ShareUpdateExclusiveLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SIReadLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Autoanalyze Run Count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Autovacuum Run Count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Number of WAL Segments,205.0,205.0,206.0,206.0,378.0,378.0,378.0,378.0
Total WAL Size [GiB],3.2,3.2,3.22,3.22,5.91,5.91,5.91,5.91
WAL Segments Growth Rate [segments/s],0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
WAL Growth Rate [MiB/s],0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Average WAL Segment Size [MiB],16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0
code,1776508434,1776508434,1776508434,1776508434,1776550283,1776550283,1776550283,1776550283
configuration,,,,,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,49824.0,49824.0,49824.0,49824.0,114757.0,114757.0,114757.0,114757.0
time_ingest,22553.0,22553.0,22553.0,22553.0,52684.0,52684.0,52684.0,52684.0
time_check,27246.0,27246.0,27246.0,27246.0,62049.0,62049.0,62049.0,62049.0
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,0,0,0,0,0,0,0,0
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151024,151024,151025,151025,151030,151030,151031,151031
host_datadisk,0,0,0,0,0,0,0,0
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.1G,8.1G,16G,16G,16G,16G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776550283,bexhoma-sut-postgresql-bht-8-1776550283,bexhoma-sut-postgresql-bht-8-1776550283,bexhoma-sut-postgresql-bht-8-1776550283
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
phase,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-1-1,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-2-1,1776550283-PostgreSQL-BHT-8-2-2

# Bar Plots of Aggregated Values per Metric

In [11]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_per_phase(code, metric=metric)
df.T

,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2
0,9757.070312,10318.062500,9749.792969,10312.445312
1,9757.070312,10318.062500,9749.792969,10312.445312
2,9757.070312,10318.062500,9749.792969,10312.445312
3,9757.070312,10318.062500,9749.792969,10312.445312
4,9757.070312,10318.062500,9749.792969,10312.445312
5,9757.070312,10318.062500,9749.792969,10312.445312
6,9757.070312,10318.062500,9749.792969,10312.445312
7,9757.070312,10318.062500,9838.878906,10312.445312
8,9757.070312,10318.062500,9838.878906,10312.445312
9,9757.070312,10318.062500,9838.878906,10312.445312
10,9757.070312,10318.062500,9838.878906,10312.445312
11,9757.070312,10318.062500,9838.878906,10312.445312
12,9757.070312,10318.062500,9838.878906,10312.445312
13,9757.070312,10318.062500,9838.878906,10312.445312
14,10072.847656,10318.062500,9838.878906,10312.445312
15,10072.847656,10318.062500,9838.878906,10312.445312
16,10072.847656,10318.062500,9838.878906,10312.445312
17,10072.847656,10318.062500,9838.878906,10312.445312
18,10072.847656,10318.062500,9838.878906,10312.445312
19,10072.847656,10318.062500,9838.878906,10312.445312
20,10072.847656,10318.062500,9838.878906,10312.445312
21,10072.847656,10318.062500,9838.878906,10312.445312
22,10072.847656,10532.214844,9838.878906,10312.445312
23,10072.847656,10532.214844,9838.878906,10312.445312
24,10072.847656,10532.214844,9838.878906,10312.445312
25,10072.847656,10532.214844,9838.878906,10312.445312
26,10072.847656,10532.214844,9838.878906,10312.445312
27,10072.847656,10532.214844,9838.878906,10312.445312
28,10072.847656,10532.214844,9838.878906,10312.445312
29,10072.847656,10532.214844,9838.878906,10312.445312
30,10072.847656,10532.214844,9838.878906,10312.445312
31,10072.847656,10532.214844,9838.878906,10470.691406
32,10072.847656,10532.214844,9838.878906,10470.691406
33,10072.847656,10532.214844,9838.878906,10470.691406
34,10072.847656,10532.214844,9838.878906,10470.691406
35,10072.847656,10532.214844,9838.878906,10470.691406
36,10072.847656,10532.214844,9838.878906,10470.691406
37,10072.847656,10532.214844,9838.878906,10470.691406
38,10072.847656,10532.214844,9838.878906,10470.691406
39,10072.847656,10532.214844,9838.878906,10470.691406
40,10072.847656,10532.214844,9838.878906,10470.691406
41,10072.847656,10532.214844,9838.878906,10470.691406
42,10072.847656,10532.214844,9838.878906,10470.691406
43,10072.847656,10532.214844,9838.878906,10470.691406
44,10072.847656,10532.214844,9838.878906,10470.691406
45,10072.847656,10532.214844,9838.878906,10470.691406
46,10072.847656,10532.214844,9838.878906,10470.691406
47,10534.085938,12972.710938,9798.250000,10470.691406
48,10534.085938,12972.710938,9798.250000,10470.691406
49,10534.085938,12972.710938,9798.250000,10470.691406
50,10534.085938,12972.710938,9798.250000,10470.691406
51,10534.085938,12972.710938,9798.250000,10470.691406
52,10534.085938,12972.710938,9798.250000,10470.691406
53,10534.085938,12972.710938,9798.250000,10470.691406
54,10534.085938,12972.710938,9798.250000,10470.691406
55,10534.085938,12972.710938,9798.250000,10470.691406
56,10534.085938,12972.710938,9798.250000,10470.691406
57,10534.085938,12972.710938,9798.250000,10470.691406
58,10534.085938,12972.710938,9798.250000,10470.691406
59,10534.085938,12972.710938,9798.250000,10470.691406
60,10534.085938,12972.710938,9798.250000,10470.691406
61,10534.085938,12972.710938,9798.250000,10470.691406
62,10534.085938,NaN,9798.250000,10470.691406
63,10534.085938,NaN,9798.250000,NaN
64,NaN,NaN,9798.250000,NaN
65,NaN,NaN,9798.250000,NaN
66,NaN,NaN,9798.250000,NaN
67,NaN,NaN,9798.250000,NaN
68,NaN,NaN,9798.250000,NaN
69,NaN,NaN,9798.250000,NaN
70,NaN,NaN,9798.250000,NaN
71,NaN,NaN,9798.250000,NaN
72,NaN,NaN,9798.250000,NaN
73,NaN,NaN,10369.902344,NaN
74,NaN,NaN,10369.902344,NaN
75,NaN,NaN,10369.902344,NaN
76,NaN,NaN,10369.902344,NaN
77,NaN,NaN,10369.902344,NaN
78,NaN,NaN,10369.902344,NaN
79,NaN,NaN,10369.902344,NaN
80,NaN,NaN,10369.902344,NaN
81,NaN,NaN,10369.902344,NaN
82,NaN,NaN,10369.902344,NaN
83,NaN,NaN,10369.902344,NaN
84,NaN,NaN,10369.902344,NaN
85,NaN,NaN,10369.902344,NaN
86,NaN,NaN,10369.902344,NaN
87,NaN,NaN,10369.902344,NaN
88,NaN,NaN,10369.902344,NaN
89,NaN,NaN,10369.902344,NaN
90,NaN,NaN,10369.902344,NaN
91,NaN,NaN,10369.902344,NaN
92,NaN,NaN,10369.902344,NaN
93,NaN,NaN,10369.902344,NaN
94,NaN,NaN,10369.902344,NaN
95,NaN,NaN,10369.902344,NaN
96,NaN,NaN,10369.902344,NaN
97,NaN,NaN,10369.902344,NaN
98,NaN,NaN,10369.902344,NaN
99,NaN,NaN,10369.902344,NaN
100,NaN,NaN,10369.902344,NaN
101,NaN,NaN,16337.492188,NaN
102,NaN,NaN,16337.492188,NaN
103,NaN,NaN,16337.492188,NaN
104,NaN,NaN,16337.492188,NaN
105,NaN,NaN,16337.492188,NaN
106,NaN,NaN,16337.492188,NaN
107,NaN,NaN,16337.492188,NaN
108,NaN,NaN,16337.492188,NaN

In [12]:
df_performance = collect.add_metadata(df)
df_performance.T

combine on index and column 'phase'

phase,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2
0,9757.070312,10318.0625,9749.792969,10312.445312
1,9757.070312,10318.0625,9749.792969,10312.445312
2,9757.070312,10318.0625,9749.792969,10312.445312
3,9757.070312,10318.0625,9749.792969,10312.445312
4,9757.070312,10318.0625,9749.792969,10312.445312
5,9757.070312,10318.0625,9749.792969,10312.445312
6,9757.070312,10318.0625,9749.792969,10312.445312
7,9757.070312,10318.0625,9838.878906,10312.445312
8,9757.070312,10318.0625,9838.878906,10312.445312
9,9757.070312,10318.0625,9838.878906,10312.445312
10,9757.070312,10318.0625,9838.878906,10312.445312
11,9757.070312,10318.0625,9838.878906,10312.445312
12,9757.070312,10318.0625,9838.878906,10312.445312
13,9757.070312,10318.0625,9838.878906,10312.445312
14,10072.847656,10318.0625,9838.878906,10312.445312
15,10072.847656,10318.0625,9838.878906,10312.445312
16,10072.847656,10318.0625,9838.878906,10312.445312
17,10072.847656,10318.0625,9838.878906,10312.445312
18,10072.847656,10318.0625,9838.878906,10312.445312
19,10072.847656,10318.0625,9838.878906,10312.445312
20,10072.847656,10318.0625,9838.878906,10312.445312
21,10072.847656,10318.0625,9838.878906,10312.445312
22,10072.847656,10532.214844,9838.878906,10312.445312
23,10072.847656,10532.214844,9838.878906,10312.445312
24,10072.847656,10532.214844,9838.878906,10312.445312
25,10072.847656,10532.214844,9838.878906,10312.445312
26,10072.847656,10532.214844,9838.878906,10312.445312
27,10072.847656,10532.214844,9838.878906,10312.445312
28,10072.847656,10532.214844,9838.878906,10312.445312
29,10072.847656,10532.214844,9838.878906,10312.445312
30,10072.847656,10532.214844,9838.878906,10312.445312
31,10072.847656,10532.214844,9838.878906,10470.691406
32,10072.847656,10532.214844,9838.878906,10470.691406
33,10072.847656,10532.214844,9838.878906,10470.691406
34,10072.847656,10532.214844,9838.878906,10470.691406
35,10072.847656,10532.214844,9838.878906,10470.691406
36,10072.847656,10532.214844,9838.878906,10470.691406
37,10072.847656,10532.214844,9838.878906,10470.691406
38,10072.847656,10532.214844,9838.878906,10470.691406
39,10072.847656,10532.214844,9838.878906,10470.691406
40,10072.847656,10532.214844,9838.878906,10470.691406
41,10072.847656,10532.214844,9838.878906,10470.691406
42,10072.847656,10532.214844,9838.878906,10470.691406
43,10072.847656,10532.214844,9838.878906,10470.691406
44,10072.847656,10532.214844,9838.878906,10470.691406
45,10072.847656,10532.214844,9838.878906,10470.691406
46,10072.847656,10532.214844,9838.878906,10470.691406
47,10534.085938,12972.710938,9798.25,10470.691406
48,10534.085938,12972.710938,9798.25,10470.691406
49,10534.085938,12972.710938,9798.25,10470.691406
50,10534.085938,12972.710938,9798.25,10470.691406
51,10534.085938,12972.710938,9798.25,10470.691406
52,10534.085938,12972.710938,9798.25,10470.691406
53,10534.085938,12972.710938,9798.25,10470.691406
54,10534.085938,12972.710938,9798.25,10470.691406
55,10534.085938,12972.710938,9798.25,10470.691406
56,10534.085938,12972.710938,9798.25,10470.691406
57,10534.085938,12972.710938,9798.25,10470.691406
58,10534.085938,12972.710938,9798.25,10470.691406
59,10534.085938,12972.710938,9798.25,10470.691406
60,10534.085938,12972.710938,9798.25,10470.691406
61,10534.085938,12972.710938,9798.25,10470.691406
62,10534.085938,NaN,9798.25,10470.691406
63,10534.085938,NaN,9798.25,NaN
64,NaN,NaN,9798.25,NaN
65,NaN,NaN,9798.25,NaN
66,NaN,NaN,9798.25,NaN
67,NaN,NaN,9798.25,NaN
68,NaN,NaN,9798.25,NaN
69,NaN,NaN,9798.25,NaN
70,NaN,NaN,9798.25,NaN
71,NaN,NaN,9798.25,NaN
72,NaN,NaN,9798.25,NaN
73,NaN,NaN,10369.902344,NaN
74,NaN,NaN,10369.902344,NaN
75,NaN,NaN,10369.902344,NaN
76,NaN,NaN,10369.902344,NaN
77,NaN,NaN,10369.902344,NaN
78,NaN,NaN,10369.902344,NaN
79,NaN,NaN,10369.902344,NaN
80,NaN,NaN,10369.902344,NaN
81,NaN,NaN,10369.902344,NaN
82,NaN,NaN,10369.902344,NaN
83,NaN,NaN,10369.902344,NaN
84,NaN,NaN,10369.902344,NaN
85,NaN,NaN,10369.902344,NaN
86,NaN,NaN,10369.902344,NaN
87,NaN,NaN,10369.902344,NaN
88,NaN,NaN,10369.902344,NaN
89,NaN,NaN,10369.902344,NaN
90,NaN,NaN,10369.902344,NaN
91,NaN,NaN,10369.902344,NaN
92,NaN,NaN,10369.902344,NaN
93,NaN,NaN,10369.902344,NaN
94,NaN,NaN,10369.902344,NaN
95,NaN,NaN,10369.902344,NaN
96,NaN,NaN,10369.902344,NaN
97,NaN,NaN,10369.902344,NaN
98,NaN,NaN,10369.902344,NaN
99,NaN,NaN,10369.902344,NaN
100,NaN,NaN,10369.902344,NaN
101,NaN,NaN,16337.492188,NaN
102,NaN,NaN,16337.492188,NaN
103,NaN,NaN,16337.492188,NaN
104,NaN,NaN,16337.492188,NaN
105,NaN,NaN,16337.492188,NaN
106,NaN,NaN,16337.492188,NaN
107,NaN,NaN,16337.492188,NaN
108,NaN,NaN,16337.492188,NaN
code,1776508434,1776508434,1776508434,1776508434
configuration,,,,
experiment_run,1,1,2,2
client,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,49824.0,49824.0,49824.0,49824.0
time_ingest,22553.0,22553.0,22553.0,22553.0
time_check,27246.0,27246.0,27246.0,27246.0
terminals,0,0,0,0
pods,1,2,1,2
tenant,,,,
num_worker,0,0,0,0
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,0,0,0,0
host_RAM,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,
host_Cores,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151024,151024,151025,151025
host_datadisk,0,0,0,0
host_volume_size,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.1G,8.1G
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3
loading_parameters_PODS_TOTAL,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1
loading_parameters_TPCH_TABLE,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
benchmarking_parameters_SF,3,3,3,3
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2

In [13]:
metric = 'total_cpu_memory'
code = codes[0]
collect.get_monitoring_timeseries_all(metric=metric)

,timestamp,code,phase,experiment_run,client,type_tenants,vol_tenants,num_tenants,metric,component,value
0,0,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
1,0,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
2,0,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9749.792969
3,0,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
4,0,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.460938
5,0,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
6,0,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.609375
7,0,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.621094
8,1,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
9,1,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
10,1,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9749.792969
11,1,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
12,1,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.460938
13,1,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
14,1,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.609375
15,1,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.621094
16,2,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
17,2,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
18,2,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9749.792969
19,2,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
20,2,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
21,2,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
22,2,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.609375
23,2,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.621094
24,3,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
25,3,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
26,3,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9749.792969
27,3,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
28,3,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
29,3,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
30,3,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
31,3,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
32,4,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
33,4,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
34,4,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9749.792969
35,4,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
36,4,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
37,4,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
38,4,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
39,4,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
40,5,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
41,5,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
42,5,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9749.792969
43,5,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
44,5,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
45,5,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
46,5,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
47,5,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
48,6,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
49,6,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
50,6,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9749.792969
51,6,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
52,6,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
53,6,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
54,6,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
55,6,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
56,7,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
57,7,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
58,7,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
59,7,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
60,7,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
61,7,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
62,7,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
63,7,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
64,8,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
65,8,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
66,8,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
67,8,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
68,8,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
69,8,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
70,8,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
71,8,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
72,9,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
73,9,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
74,9,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
75,9,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
76,9,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
77,9,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
78,9,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
79,9,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
80,10,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
81,10,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
82,10,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
83,10,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
84,10,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
85,10,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
86,10,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
87,10,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
88,11,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
89,11,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
90,11,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
91,11,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
92,11,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
93,11,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
94,11,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
95,11,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
96,12,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
97,12,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
98,12,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
99,12,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
100,12,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
101,12,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
102,12,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
103,12,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
104,13,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9757.070312
105,13,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
106,13,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
107,13,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
108,13,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
109,13,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
110,13,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
111,13,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
112,14,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656
113,14,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
114,14,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
115,14,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
116,14,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
117,14,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
118,14,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
119,14,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
120,15,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656
121,15,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
122,15,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
123,15,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
124,15,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
125,15,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
126,15,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
127,15,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
128,16,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656
129,16,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
130,16,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
131,16,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
132,16,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
133,16,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
134,16,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
135,16,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
136,17,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656
137,17,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
138,17,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
139,17,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
140,17,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
141,17,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
142,17,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
143,17,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
144,18,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656
145,18,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
146,18,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
147,18,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
148,18,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
149,18,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
150,18,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
151,18,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14751.382812
152,19,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656
153,19,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
154,19,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
155,19,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
156,19,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
157,19,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
158,19,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
159,19,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14970.675781
160,20,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656
161,20,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
162,20,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
163,20,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
164,20,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
165,20,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
166,20,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
167,20,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14970.675781
168,21,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656
169,21,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10318.062500
170,21,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
171,21,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
172,21,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
173,21,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
174,21,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
175,21,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14970.675781
176,22,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656
177,22,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10532.214844
178,22,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
179,22,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
180,22,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
181,22,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
182,22,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
183,22,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14970.675781
184,23,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656
185,23,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10532.214844
186,23,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
187,23,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
188,23,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
189,23,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
190,23,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
191,23,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14970.675781
192,24,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656
193,24,1776508434,1776508434-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,10532.214844
194,24,1776508434,1776508434-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,9838.878906
195,24,1776508434,1776508434-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,10312.445312
196,24,1776550283,1776550283-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13747.363281
197,24,1776550283,1776550283-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,14869.750000
198,24,1776550283,1776550283-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,5888.425781
199,24,1776550283,1776550283-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,14970.675781
200,25,1776508434,1776508434-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,10072.847656

In [18]:
df_performance = collect.get_performance_per_connection()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)
df_performance.T

,1776508434-PostgreSQL-BHT-8-1-1-1,1776508434-PostgreSQL-BHT-8-1-2-1,1776508434-PostgreSQL-BHT-8-1-2-2,1776508434-PostgreSQL-BHT-8-2-1-1,1776508434-PostgreSQL-BHT-8-2-2-1,1776508434-PostgreSQL-BHT-8-2-2-2,1776550283-PostgreSQL-BHT-8-1-1-1,1776550283-PostgreSQL-BHT-8-1-2-1,1776550283-PostgreSQL-BHT-8-1-2-2,1776550283-PostgreSQL-BHT-8-2-1-1,1776550283-PostgreSQL-BHT-8-2-2-1,1776550283-PostgreSQL-BHT-8-2-2-2
total_timer_execution,1.569886,1.580692,1.547605,2.203745,1.558278,1.561981,3.026814,3.050032,3.053193,4.250588,3.034907,3.074278
Power@Size [~Q/h],6879.478867,6832.452394,6978.523856,4900.749464,6930.729424,6914.296866,7136.215611,7081.892596,7074.561948,5081.650437,7117.18614,7026.038898
Geo Times [s],1.569886,1.580692,1.547605,2.203745,1.558278,1.561981,3.026814,3.050032,3.053193,4.250588,3.034907,3.074278
configuration,1776508434--,1776508434--,1776508434--,1776508434--,1776508434--,1776508434--,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8
connection,1776508434-PostgreSQL-BHT-8-1-1-1,1776508434-PostgreSQL-BHT-8-1-2-1,1776508434-PostgreSQL-BHT-8-1-2-2,1776508434-PostgreSQL-BHT-8-2-1-1,1776508434-PostgreSQL-BHT-8-2-2-1,1776508434-PostgreSQL-BHT-8-2-2-2,1776550283-PostgreSQL-BHT-8-1-1-1,1776550283-PostgreSQL-BHT-8-1-2-1,1776550283-PostgreSQL-BHT-8-1-2-2,1776550283-PostgreSQL-BHT-8-2-1-1,1776550283-PostgreSQL-BHT-8-2-2-1,1776550283-PostgreSQL-BHT-8-2-2-2
phase,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2,1776508434-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-1-1,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-2-1,1776550283-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-2-2
SF,3.0,3.0,3.0,3.0,3.0,3.0,6.0,6.0,6.0,6.0,6.0,6.0
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
time [s],63,61,60,108,60,62,116,122,120,209,118,118
pod_count,1,1,1,1,1,1,1,1,1,1,1,1
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22
Throughput@Size,3771.43,3895.08,3960.0,2200.0,3960.0,3832.26,4096.55,3895.08,3960.0,2273.68,4027.12,4027.12
code,1776508434,1776508434,1776508434,1776508434,1776508434,1776508434,1776550283,1776550283,1776550283,1776550283,1776550283,1776550283

In [15]:
df_performance = collect.get_performance_aggregated_per_phase()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

,1776508434-PostgreSQL-BHT-8-1-1-1,1776508434-PostgreSQL-BHT-8-1-2-1,1776508434-PostgreSQL-BHT-8-1-2-2,1776508434-PostgreSQL-BHT-8-2-1-1,1776508434-PostgreSQL-BHT-8-2-2-1,1776508434-PostgreSQL-BHT-8-2-2-2,1776550283-PostgreSQL-BHT-8-1-1-1,1776550283-PostgreSQL-BHT-8-1-2-1,1776550283-PostgreSQL-BHT-8-1-2-2,1776550283-PostgreSQL-BHT-8-2-1-1,1776550283-PostgreSQL-BHT-8-2-2-1,1776550283-PostgreSQL-BHT-8-2-2-2
configuration,1776508434--,1776508434--,1776508434--,1776508434--,1776508434--,1776508434--,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
phase,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2,1776508434-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-1-1,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-2-1,1776550283-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-2-2
total_timer_execution,1.569886,1.580692,1.547605,2.203745,1.558278,1.561981,3.026814,3.050032,3.053193,4.250588,3.034907,3.074278
Power@Size [~Q/h],6879.478867,6832.452394,6978.523856,4900.749464,6930.729424,6914.296866,7136.215611,7081.892596,7074.561948,5081.650437,7117.18614,7026.038898
code,1776508434,1776508434,1776508434,1776508434,1776508434,1776508434,1776550283,1776550283,1776550283,1776550283,1776550283,1776550283
pod_count,1,1,1,1,1,1,1,1,1,1,1,1
SF,3.0,3.0,3.0,3.0,3.0,3.0,6.0,6.0,6.0,6.0,6.0,6.0
time [s],63,61,60,108,60,62,116,122,120,209,118,118
client,1,2,2,1,2,2,1,2,2,1,2,2
Throughput@Size,3771.43,3895.08,3960.0,2200.0,3960.0,3832.26,4096.55,3895.08,3960.0,2273.68,4027.12,4027.12
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22

In [16]:
df = collect.add_metadata(df_performance)
df.T

combine on columns phase

,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2,1776508434-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-1-1,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-2-1,1776550283-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-2-2
Power@Size [~Q/h],6879.478867,6832.452394,6978.523856,4900.749464,6930.729424,6914.296866,7136.215611,7081.892596,7074.561948,5081.650437,7117.18614,7026.038898
SF,3.0,3.0,3.0,3.0,3.0,3.0,6.0,6.0,6.0,6.0,6.0,6.0
Throughput@Size,3771.43,3895.08,3960.0,2200.0,3960.0,3832.26,4096.55,3895.08,3960.0,2273.68,4027.12,4027.12
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
benchmarking_parameters_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
client,1,2,2,1,2,2,1,2,2,1,2,2
code,1776508434,1776508434,1776508434,1776508434,1776508434,1776508434,1776550283,1776550283,1776550283,1776550283,1776550283,1776550283
configuration,1776508434--,1776508434--,1776508434--,1776508434--,1776508434--,1776508434--,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8,1776550283-PostgreSQL-BHT-8
datadisk,0,0,0,0,0,0,0,0,0,0,0,0
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_Cores,64,64,64,64,64,64,64,64,64,64,64,64
host_GPU,,,,,,,,,,,,
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_cuda,,,,,,,,,,,,
host_datadisk,0,0,0,0,0,0,0,0,0,0,0,0
host_disk,151024,151024,151024,151025,151025,151025,151030,151030,151030,151031,151031,151031
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.1G,8.1G,8.1G,16G,16G,16G,16G,16G,16G
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_TPCH_TABLE,,,,,,,,,,,,
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
phase,1776508434-PostgreSQL-BHT-8-1-1,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-1-2,1776508434-PostgreSQL-BHT-8-2-1,1776508434-PostgreSQL-BHT-8-2-2,1776508434-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-1-1,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-1-2,1776550283-PostgreSQL-BHT-8-2-1,1776550283-PostgreSQL-BHT-8-2-2,1776550283-PostgreSQL-BHT-8-2-2
pod_count,1,1,1,1,1,1,1,1,1,1,1,1
pods,1,2,2,1,2,2,1,2,2,1,2,2
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776508434,bexhoma-sut-postgresql-bht-8-1776550283,bexhoma-sut-postgresql-bht-8-1776550283,bexhoma-sut-postgresql-bht-8-1776550283,bexhoma-sut-postgresql-bht-8-1776550283,bexhoma-sut-postgresql-bht-8-1776550283,bexhoma-sut-postgresql-bht-8-1776550283
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
tenant,,,,,,,,,,,,
terminals,0,0,0,0,0,0,0,0,0,0,0,0
time [s],63,61,60,108,60,62,116,122,120,209,118,118
time_check,27246.0,27246.0,27246.0,27246.0,27246.0,27246.0,62049.0,62049.0,62049.0,62049.0,62049.0,62049.0
time_ingest,22553.0,22553.0,22553.0,22553.0,22553.0,22553.0,52684.0,52684.0,52684.0,52684.0,52684.0,52684.0
time_load,49824.0,49824.0,49824.0,49824.0,49824.0,49824.0,114757.0,114757.0,114757.0,114757.0,114757.0,114757.0
total_timer_execution,1.569886,1.580692,1.547605,2.203745,1.558278,1.561981,3.026814,3.050032,3.053193,4.250588,3.034907,3.074278
type_tenants,,,,,,,,,,,,
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False

# Boxplot of All Metrics for a Single Experiment

In [ ]:
if not b_skip_plots:
    results = []
    code = codes[0]
    for idx, row in collect.df_metrics.iterrows():
        if row["active"] == False:
            continue
        metric_name = idx
        method = 'diff' if row["metric"] == 'counter' else 'mean'
        col_name = row["title"]
        df_monitoring = collect.get_monitoring_timeseries_single(code, metric=metric_name)
        #print(df_monitoring)
        ax = df_monitoring.boxplot()
        ax.set_title(col_name)
        plt.show()

# Boxplot of A Single Metric for a Single Experiment

In [ ]:
metric = 'total_cpu_memory'
code = codes[0]
collect.get_monitoring_timeseries_single(code, metric=metric)

In [ ]:
metric = 'total_cpu_memory'
code = codes[0]
collect.get_monitoring_timeseries_all( metric=metric)

In [ ]:
if not b_skip_plots:
    metric = 'pg_stat_activity_max_tx_duration_active'
    #metric = 'pg_stat_database_blks_reads'
    #metric = 'pg_stat_activity_count_idle_transaction'
    metric = 'total_cpu_memory'
    code = codes[0]
    df_monitoring = collect.get_monitoring_timeseries_single(code, metric=metric)
    ax = df_monitoring.boxplot()
    ax.set_title(collect.df_metrics.loc[metric]['title'])#metric)
    plt.show()
    df_monitoring

# Lineplot of a Single Metric for a Single Experiment

In [ ]:
if not b_skip_plots:
    code = codes[0]
    metric = 'pg_stat_database_blks_hit'
    metric = 'pg_stat_activity_count_idle_transaction'
    metric = 'total_cpu_memory'
    metric = 'total_cpu_util'
    metric = 'total_cpu_util_s'
    metric = 'core_variance'
    df_monitoring = collect.get_monitoring_timeseries_single(code, metric=metric)
    ax = df_monitoring.plot()
    ax.set_title(metric)
    plt.show()
    #df_monitoring

# Boxplot of a Single Metric for all Experiments

In [ ]:
metric = 'pg_stat_database_blks_hit'
metric = 'pg_stat_activity_count_idle_transaction'
metric = 'total_cpu_memory'
metric = 'total_cpu_util'
metric = 'total_cpu_util_s'
metric = 'core_variance'
metric = 'pg_locks_count_exclusivelock'
metric = 'pg_stat_activity_count_active'
df_performance = collect.get_monitoring_timeseries_all(metric)
#df_performance
df_performance_first = df_performance[df_performance['client']=="1"]
#df_performance_first
df_performance_second = df_performance[df_performance['client']=="2"]
#df_performance_second
#df_performance_first['value'].describe()
#df_performance

## First Execution Run

In [ ]:
plot_boxplots(df_performance_first, y='value', title=collect.df_metrics.loc[metric]['title'], b_plot_save=b_plot_save, filename_prefix=filename_prefix)

## Second Execution Run

In [ ]:
plot_boxplots(df_performance_second, y='value', title=collect.df_metrics.loc[metric]['title'], b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Lineplot of a Single Metric for All Experiments

## First Execution Run

In [ ]:
#df = df_performance_first[df_performance_first['type'] == 'None']
#df = df[df['experiment_run'] == '1']
plot_lines(df_performance_first, y='value', title=collect.df_metrics.loc[metric]['title'], b_plot_save=b_plot_save, filename_prefix=filename_prefix)
#df

# Aggregated Metrics for all Connections

In [ ]:
df_performance = collect.get_monitoring_single_all("stream")
df_performance.T

# Monitoring Aggregated Values

In [ ]:
df_performance = collect.get_monitoring_all("stream")

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T#[['Max CPU', 'client', 'type', 'num_tenants']]

## First Execution Run

In [ ]:
plot_bars(df_performance_first, y='Buffer Cache Hit Ratio', title='Cache Hit Ratio [%]', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

## Second Execution Run

In [ ]:
plot_bars(df_performance_second, y='Buffer Cache Hit Ratio', title='Cache Hit Ratio [%]', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Performance Results per Tenant

In [ ]:
df_performance = collect.get_performance_all_single()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

## First Execution Run

In [ ]:
plot_boxplots(df_performance_first, y='Goodput (requests/second)', title='Distribution of Goodput First Run [req/s]', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_boxplots(df_performance_second, y='Goodput (requests/second)', title='Distribution of Goodput Second Run [req/s]', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_boxplots(df_performance_first, y='Latency Distribution.99th Percentile Latency (microseconds)', title=r'Distribution of 99th Latency 1st Run [$\mu s$]', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_boxplots(df_performance_second, y='Latency Distribution.99th Percentile Latency (microseconds)', title=r'Distribution of 99th Latency 2nd Run [$\mu s$]', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Performance Results per Total

In [ ]:
collect.get_performance_single().T

In [ ]:
collect.get_performance_all_single().T

In [ ]:
df_performance = collect.get_performance_all()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)

In [ ]:
df_performance.T

In [ ]:
import seaborn as sns

sns.barplot(data=df_performance, x='experiment_run', y='Goodput (requests/second)', hue='client')
plt.show()

In [ ]:
plot_bars(df_performance, y='Goodput (requests/second)', title='Goodput [req/s]', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='Goodput (requests/second)', title='Goodput First Run [req/s]', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_second, y='Goodput (requests/second)', title='Goodput Second Run [req/s]', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance, y='Latency Distribution.Average Latency (microseconds)', title=r'Average Latency [$\mu s$]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='Latency Distribution.Average Latency (microseconds)', title=r'Average Latency First Run [$\mu s$]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_second, y='Latency Distribution.Average Latency (microseconds)', title=r'Average Latency Second Run [$\mu s$]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance, y='num_errors', title='Deadlocks', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
df_performance = collect.get_loading_time_max_all()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance

In [ ]:
df_performance_first = df_performance[df_performance['client'] == 1]
# Divide datadisk by the count of rows with the same type and num_tenants
df = df_performance_first.copy()
# Create a mask for rows where type is not "container"
mask = df['type'] != 'container'

# Only apply the group count to the relevant rows
group_counts = df[mask].groupby(['type', 'num_tenants'])['datadisk'].transform('count')

# Initialize the column with NaN (or 0, if preferred)
df['datadisk_normalized'] = df['datadisk'] / 1024

# Apply the normalized value only where the mask is True
df.loc[mask, 'datadisk_normalized'] = df.loc[mask, 'datadisk'] / group_counts / 1024

plot_bars(df, y='datadisk_normalized', title='Database Size [GB]', estimator='sum', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='datadisk', title='Database Size [MB]', estimator='sum', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='time_ingest', title='Time for Ingestion [s]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='time_check', title='Time for Vacuum [s]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Hardware Monitoring for Benchmarking Phase

In [ ]:
df_performance = collect.get_monitoring_all(type="stream")

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

In [ ]:
plot_bars(df_performance, y='CPU Utilization Time [s]', title='CPU [CPUs]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='CPU Utilization Time [s]', title='CPU 1st Run [CPUs]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_second, y='CPU Utilization Time [s]', title='CPU 2nd Run [CPUs]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance, y='CPU Utilization', title='CPU Utilization [%]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

## Custom Aggregation

In [ ]:
metric = 'total_cpu_util'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["client", "type", "num_tenants"])["value"]
      .max()
      .reset_index()
)
plot_bars(df_agg, y='value', title='Max CPU Utilization [%]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)
#df_agg

In [ ]:
plot_bars(df_performance, y='CPU Throttle', title='CPU Throttle [%]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

## Custom Aggregation and Scale

In [ ]:
metric = 'total_cpu_memory'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["client", "type", "num_tenants"])["value"]
      .max()
      .reset_index()
)
df_agg['value'] = df_agg['value'] / 1024.
plot_bars(df_agg, y='value', title='Max Memory Usage [GiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

plot_bars(df_performance, y='Memory Usage [MiB]', title='Average Memory Usage [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
metric = 'total_cpu_memory_cached'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["client", "type", "num_tenants"])["value"]
      .max()
      .reset_index()
)
df_agg['value'] = df_agg['value'] / 1024.
plot_bars(df_agg, y='value', title='Max Memory Usage Cached [GiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

plot_bars(df_performance, y='Memory Usage Cached [MiB]', title='Average Memory Usage Cached [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Hardware Monitoring for Loading Phase

In [ ]:
df_performance = collect.get_monitoring_all("loading")

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance_first

In [ ]:
plot_bars(df_performance, y='CPU Utilization Time [s]', title='CPU [CPUs]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance, y='Memory Usage [MiB]', title='Memory Usage [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance, y='Memory Usage Cached [MiB]', title='Memory Usage Cached [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Efficiency

In [ ]:
client = 1

df_performance_monitoring = collect.get_monitoring_all(type="stream")
df_performance_monitoring = df_performance_monitoring[df_performance_monitoring['client'] == client]
df_performance = collect.get_performance_all()
df_performance = df_performance[df_performance['client'] == client]
merged_df = pd.merge(df_performance, df_performance_monitoring, on=['type', 'num_tenants', 'code', 'client'], how='inner')
#merged_df['I_Lat'] = 1./merged_df['E_Lat']
merged_df['E_Tpx'] = merged_df['Goodput (requests/second)'] / merged_df['CPU Utilization Time [s]'] * 600.
merged_df['E_Lat'] = 1./np.sqrt(merged_df['Latency Distribution.Average Latency (microseconds)']*merged_df['CPU Utilization Time [s]']/1E6)
merged_df['E_RAM'] = (merged_df['Goodput (requests/second)']) / merged_df['Memory Usage [MiB]']
merged_df

In [ ]:
plot_bars(merged_df, y='E_Lat', title='1st run - $E_{Lat}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
#plot_bars(merged_df, y='I_Lat', title='1st run - $I_{Lat}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(merged_df, y='E_Tpx', title='1st run - $E_{Tpx}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(merged_df, y='E_RAM', title='1st run - $E_{RAM}$', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
client = 2

df_performance_monitoring = collect.get_monitoring_all(type="stream")
df_performance_monitoring = df_performance_monitoring[df_performance_monitoring['client'] == client]
df_performance = collect.get_performance_all()
df_performance = df_performance[df_performance['client'] == client]
merged_df = pd.merge(df_performance, df_performance_monitoring, on=['type', 'num_tenants', 'code', 'client'], how='inner')
#merged_df['CPUs/Request'] = merged_df['CPU [CPUs]'] / merged_df['Goodput (requests/second)'] / 600.
merged_df['E_Tpx'] = merged_df['Goodput (requests/second)'] / merged_df['CPU Utilization Time [s]'] * 600.
merged_df['E_Lat'] = 1./np.sqrt(merged_df['Latency Distribution.Average Latency (microseconds)']*merged_df['CPU Utilization Time [s]']/1E6)
merged_df['E_RAM'] = (merged_df['Goodput (requests/second)']) / merged_df['Memory Usage [MiB]']

merged_df

In [ ]:
plot_bars(merged_df, y='E_Lat', title='2nd run - $E_{Lat}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(merged_df, y='E_Tpx', title='2nd run - $E_{Tpx}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(merged_df, y='E_RAM', title='2nd run - $E_{RAM}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
#zip_all_results()