# TPC-H Collector Demo

# Missing
* connection data beyond loading
* join to connection data
* join to monitoring_single
* connection and configuration also in monitoring and connection df

## Naming
* There is an experiment having a code, say `1775855486`.
* The experiment inspects a SUT, say `PostgreSQL-A`. This is called a `configuration`.
* The experiment is run several times, say twice. The indicator of the run is called `experiment_run`.
* Each run can have several phases as a sequence. The number of the phase is called `client`. The state of the configuration in a phase is called a `connection`.
* Each client can have several `pods`, that are run in parallel. A pod represents a driver.
* Performance metrics are collected per driver pod.  
    The naming of an instance is `<sut>-<experiment_run>-<client>-<pod>`. It is unique per experiment.
* Monitoring metrics are collected per phase. They are automatically aggregated across parallel pods.  
    The naming of an instance is `<sut>-<experiment_run>-<client>`. It is unique per experiment.

## Aggregation
* Aggregation is complicated. Some metrics are aggregated via count, sum, max or average. Others cannot be aggregated sensibly, like experiment code or latency percentiles.
* There are helper functions to aggregated pods that are certainly run in parallel.  
  So `<sut>-<experiment_run>-<client>-<pod>` are aggregated to `<sut>-<experiment_run>-<client>`.
* An exception is multi-tenancy.

## Class `collector`
* constructor `collectors.benchbase(path, codes)`
* evaluator object `evaluate = collect.get_evaluator()`
* dataframe of connection infos `collect.get_connections()`
  * index is name of client
* **monitoring metrics**
  * dataframe of available metrics `collect.df_metrics`
    * index is key of metric
  * dataframe of monitored components `collect.get_monitored_phases()`
    * index is key of component
  * dataframe of aggregated metrics per connection `collect.get_monitoring_single_all()`
    * index is name of client
    * metrics aggregated per code, experiment_run and client
  * dataframe of aggregated metrics per connection and across tenants `collect.get_monitoring_all()`
    * index just enumerates
    * metrics aggregated per code, experiment_run and client and across tenants
  * dataframe of time series for a metric of a connection in an experiment `collect.get_monitoring_timeseries_single(code, metric)`
    * index is name of connection
    * unstacked (wide format)
  * dataframe of time series for a metric in all experiments `collect.get_monitoring_timeseries_all(metric)`
    * index just enumerates
    * stacked (long format)
* **performance metrics**
  * dataframe of loading metrics `collect.get_loading_time_max_all()`
    * index is name of client
  * dataframe of performance aggregated per parallel client `collect.get_performance_all()`
    * index just enumerates
    * performance aggregated per code, experiment_run and client
  * dataframe of performance for one experiment `collect.get_performance_single()`
    * performance of each single client (driver)
    * index is name of client pod
  * dataframe of performance for all experiments `collect.get_performance_all_single()`
    * performance of each single client (driver)
    * index is name of client pod


[1] [Benchmarking Multi-Tenant Architectures in PostgreSQL](https://doi.org/10.48786/edbt.2026.46)
> Erdelt, P.K., and Rabl T. (2026)
> In: Proceedings 29th International Conference on Extending Database Technology, EDBT 2026
> OpenProceedings.org
> https://doi.org/10.48786/edbt.2026.46

In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option('display.max_colwidth', None)

from bexhoma import collectors

%matplotlib inline

# Functions for Nice Plots

In [2]:
from notebookutils import *

# Collect Results

In [3]:
#path = r"D:\data\benchmarks"
path = r"/data/benchmarks"
filename_prefix = "demo_"
b_plot_save = False
b_skip_plots = True

In [4]:
codes = [
    "1776418956",
    "1776420958"
]

codes

['1776418956', '1776420958']

In [5]:
collect = collectors.default(path, codes)

# Get all Metrics Metadata

## Metrics Names and Types

Metrics that are derived from monitoring

In [6]:
collect.df_metrics

,title,active,type,metric
total_cpu_memory,Memory Usage [MiB],True,cluster,gauge
total_cpu_memory_cached,Memory Usage Cached [MiB],True,cluster,gauge
total_cpu_util,CPU Utilization,True,cluster,gauge
total_cpu_throttled,CPU Throttle,True,cluster,gauge
total_cpu_throttled_s,CPU Throttled Time [s],True,cluster,counter
total_cpu_util_others,CPU Utilization Others,False,cluster,gauge
total_cpu_util_s,CPU Utilization Time [s],True,cluster,counter
total_cpu_util_user_s,CPU User Time [s],True,cluster,counter
total_cpu_util_sys_s,CPU System Time [s],True,cluster,counter
total_cpu_util_others_s,CPU Utilization Time Others [s],False,cluster,counter
total_network_rx,Network Rx Total [MiB],True,cluster,counter
total_network_tx,Network Tx Total [MiB],True,cluster,counter
total_fs_read,Filesystem Read Total [MiB],True,cluster,counter
total_fs_write,Filesystem Write Total [MiB],True,cluster,counter
total_gpu_util,GPU Utilization [%],False,cluster,gauge
total_gpu_power,GPU Power Usage [W],False,cluster,gauge
total_gpu_memory,GPU Memory Usage [MiB],False,cluster,gauge
core_variance,Core Utilization Variance [%],True,cluster,ratio
max_core_util,Max Core Utilization [%],True,cluster,ratio
io_wait_pct,I/O Wait [%],True,cluster,ratio
io_wait_total,Total I/O Wait Time [s],True,cluster,counter
pg_stat_activity_count_idle,Number of Idle Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction,Number of Idle-in-transaction Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction_aborted,Number of Idle-in-transaction Aborted Sessions,True,application,gauge
pg_stat_activity_count_active,Number of Active Sessions,True,application,counter
pg_stat_activity_count_active_app,Number of Active Application Sessions,True,application,counter
pg_stat_activity_max_tx_duration_active,Longest Active Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle,Longest Idle Session (no transaction),True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx,Longest Idle-in-Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx_aborted,Longest Idle-in-Transaction (Aborted),True,application,ratio
pg_stat_activity_count_io,Active Backends Waiting on I/O,True,application,gauge
pg_stat_activity_count_wal,Active Backends Waiting on WAL,True,application,gauge
pg_stat_activity_count_lock,Active Backends Waiting on Locks,True,application,gauge
pg_stat_activity_max_tx_duration_io,Max Transaction Duration (I/O Wait),True,application,ratio
pg_stat_activity_max_tx_duration_wal,Max Transaction Duration (WAL Wait),True,application,ratio
pg_stat_activity_max_tx_duration_lock,Max Transaction Duration (Lock Wait),True,application,ratio
pg_stat_database_blks_read,Disk Blocks Read Count,True,application,counter
pg_stat_database_blks_hit,Buffer Cache Hit Count,True,application,counter
cache_hit_ratio,Buffer Cache Hit Ratio,True,application,ratio
pg_stat_user_tables_idx_scan,Index Scan Count,True,application,counter
pg_stat_user_tables_idx_tup_fetch,Index Tuple Fetch Count,True,application,counter
pg_statio_user_tables_idx_cache_hit_ratio,Index Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_heap_blocks_hit,Table Buffer Hit Count,True,application,counter
pg_statio_user_tables_heap_blocks_read,Table Blocks Read Count,True,application,counter
pg_statio_user_tables_heap_cache_hit_ratio,Table Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_total_cache_hit_ratio,Total Cache Hit Ratio,True,application,ratio
pg_stat_bgwriter_efficiency_ratio,BGWriter Efficiency Ratio (Cleaned / Allocated),True,application,ratio
pg_stat_bgwriter_maxwritten_clean_total,BGWriter Stopped Due to Max Pages,True,application,counter
pg_stat_bgwriter_checkpoint_sync_time_total,Checkpoint Sync Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_total,Checkpoint Write Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_per_sync_time,Time spent writing vs syncing during checkpoints [ratio],False,application,ratio
pg_locks_count,Total Locks Current,True,application,gauge
pg_locks_count_accessexclusivelock,AccessExclusiveLocks Current,True,application,gauge
pg_locks_count_accesssharelock,AccessShareLocks Current,True,application,gauge
pg_locks_count_exclusivelock,ExclusiveLocks Current,True,application,gauge
pg_locks_count_rowexclusivelock,RowExclusiveLocks Current,True,application,gauge
pg_locks_count_rowsharelock,RowShareLocks Current,True,application,gauge
pg_locks_count_sharelock,ShareLocks Current,True,application,gauge
pg_locks_count_sharerowexclusivelock,ShareRowExclusiveLocks Current,True,application,gauge
pg_locks_count_shareupdateexclusivelock,ShareUpdateExclusiveLocks Current,True,application,gauge
pg_locks_count_sireadlock,SIReadLocks Current,True,application,gauge
pg_stat_user_tables_autoanalyze_count,Autoanalyze Run Count,True,application,counter
pg_stat_user_tables_autovacuum_count,Autovacuum Run Count,True,application,counter
pg_stat_bgwriter_checkpoints_timed_per_req,Frequency of checkpoints (timed vs requested) [ratio],False,application,gauge
pg_stat_wal_volume_bytes_sec,Volume of WAL generated [bytes/sec],False,application,counter
pg_stat_bgwriter_buffers_backend_fsync,Backends forced to flush WAL (I/O contention) [fsync/sec],False,application,counter
pg_stat_activity_wait_event_count,Active sessions waiting on any event [count],False,application,gauge
pg_stat_user_tables_dead_tuples_per_vacuum,Dead tuples per vacuum operation [tuples/vacuum],True,application,ratio
pg_wal_segments,Number of WAL Segments,True,application,gauge
pg_wal_size_bytes,Total WAL Size [GiB],True,application,gauge
pg_wal_segments_rate,WAL Segments Growth Rate [segments/s],True,application,gauge
pg_wal_size_rate,WAL Growth Rate [MiB/s],True,application,gauge
pg_wal_avg_segment_size,Average WAL Segment Size [MiB],True,application,gauge
pg_wal_size_per_checkpoint,WAL Size per Checkpoint [bytes/checkpoint],False,application,gauge

## Names of Monitored Phases

Names of components and their phases

In [7]:
collect.get_monitored_phases()

                                           description
loading                  Loading phase: SUT deployment
datagenerator  Loading phase: component data generator
loader                 Loading phase: component loader
stream                 Execution phase: SUT deployment
benchmarker     Execution phase: component benchmarker

# Get Connection Infos

List of states of SUTs, containing loading infos.

In [8]:
df = collect.get_connections()
df.T

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
code,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
connection,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2
time_load,455.0,455.0,455.0,455.0,1256.0,1256.0,1256.0,1256.0
time_ingest,141.0,141.0,141.0,141.0,350.0,350.0,350.0,350.0
time_check,291.0,291.0,291.0,291.0,843.0,843.0,843.0,843.0
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151015,151015,151015,151015,151015,151015,151015,151015
host_datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Get Aggregated Metrics per SUT and per Experiment

In [9]:
df_performance = collect.get_monitoring_aggregated_per_connection("stream")
df_performance.T

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
Memory Usage [MiB],10919.47,12131.24,10392.28,11955.10,17504.07,19192.60,14054.22,16993.59
Memory Usage Cached [MiB],15835.40,17047.17,15288.83,16789.84,27302.43,28990.96,22555.50,26276.44
CPU Utilization,1.66,3.29,0.96,3.39,2.91,5.70,1.60,5.64
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],180.14,320.88,998.63,395.04,381.59,869.22,2263.06,877.07
CPU User Time [s],156.36,281.35,826.53,344.83,331.65,767.27,1928.57,768.57
CPU System Time [s],23.78,39.53,172.10,50.21,49.94,101.95,334.50,108.51
Network Rx Total [MiB],1.72,7.30,3307.36,1.87,1.91,3.74,6644.39,3.68
Network Tx Total [MiB],0.20,1320.29,21.81,3.35,1.96,3.78,39.78,3.66
Filesystem Read Total [MiB],0.00,0.00,0.05,0.00,0.00,0.00,0.04,0.00
Filesystem Write Total [MiB],0.00,0.00,0.03,0.00,0.00,0.00,0.03,0.00
Core Utilization Variance [%],0.05,0.07,0.06,0.13,0.90,0.18,0.11,0.27
Max Core Utilization [%],2.37,1.92,1.02,2.80,58.98,4.78,2.34,5.37
I/O Wait [%],16.96,1.42,45.06,45.14,0.62,0.22,51.57,27.13
Total I/O Wait Time [s],0.17,0.01,378.85,0.01,0.03,2.03,567.05,0.07
Number of Idle Sessions,0.51,0.00,0.50,0.41,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,1.00,6.00,6.00,14.00,6.00,12.00,7.00,9.00
Number of Active Application Sessions,1.00,6.00,7.00,14.00,6.00,12.00,7.00,9.00
Longest Active Transaction,1.39,1.52,3.00,1.05,4.50,3.82,6.29,5.18
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,0.00,1.49,0.00,0.00,0.00,1.24,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,0.00,2.70,0.00,0.00,0.00,3.83,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,68816.00,0.00,561331.00,0.00,141677.00,0.00,1126572.00,0.00
Buffer Cache Hit Count,12007592.00,27863012.00,11519332.00,23979758.00,29738918.00,54165762.00,25971705.00,56259630.00
Buffer Cache Hit Ratio,0.94,0.98,0.99,0.99,0.99,1.00,0.99,0.99
Index Scan Count,1655068.00,3347073.00,1655068.00,3310128.00,3787019.00,7573926.00,3786963.00,7573968.00
Index Tuple Fetch Count,7285353.00,15714468.00,7285353.00,14570698.00,17452007.00,34903566.00,17451783.00,34903734.00
Index Cache Hit Ratio,0.83,0.99,1.00,1.00,1.00,1.00,1.00,1.00
Table Buffer Hit Count,7129428.00,17860713.00,6637087.00,14097214.00,18580301.00,31581658.00,14806307.00,33673975.00
Table Blocks Read Count,0.00,0.00,492339.00,0.00,0.00,0.00,984522.00,0.00
Table Cache Hit Ratio,0.94,0.98,0.98,0.98,0.98,0.99,0.99,0.99
Total Cache Hit Ratio,0.94,0.98,0.99,0.99,0.99,1.00,0.99,0.99
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,4.27,10.39,9.21,27.23,17.79,47.79,15.57,29.68
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,4.27,10.39,9.21,27.23,17.79,47.79,15.57,29.68
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN
Number of WAL Segments,205.00,205.00,205.00,205.00,410.00,410.00,410.00,410.00
Total WAL Size [GiB],3.20,3.20,3.20,3.20,6.41,6.41,6.41,6.41
WAL Segments Growth Rate [segments/s],0.64,0.01,0.00,0.00,0.00,0.00,0.00,0.00
WAL Growth Rate [MiB/s],10.21,0.08,0.00,0.00,0.00,0.00,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00

In [10]:
df_performance = collect.add_metadata(df_performance)
df_performance.T

combine on index

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2
Memory Usage [MiB],10919.47,12131.24,10392.28,11955.1,17504.07,19192.6,14054.22,16993.59
Memory Usage Cached [MiB],15835.4,17047.17,15288.83,16789.84,27302.43,28990.96,22555.5,26276.44
CPU Utilization,1.66,3.29,0.96,3.39,2.91,5.7,1.6,5.64
CPU Throttle,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CPU Throttled Time [s],0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CPU Utilization Time [s],180.14,320.88,998.63,395.04,381.59,869.22,2263.06,877.07
CPU User Time [s],156.36,281.35,826.53,344.83,331.65,767.27,1928.57,768.57
CPU System Time [s],23.78,39.53,172.1,50.21,49.94,101.95,334.5,108.51
Network Rx Total [MiB],1.72,7.3,3307.36,1.87,1.91,3.74,6644.39,3.68
Network Tx Total [MiB],0.2,1320.29,21.81,3.35,1.96,3.78,39.78,3.66
Filesystem Read Total [MiB],0.0,0.0,0.05,0.0,0.0,0.0,0.04,0.0
Filesystem Write Total [MiB],0.0,0.0,0.03,0.0,0.0,0.0,0.03,0.0
Core Utilization Variance [%],0.05,0.07,0.06,0.13,0.9,0.18,0.11,0.27
Max Core Utilization [%],2.37,1.92,1.02,2.8,58.98,4.78,2.34,5.37
I/O Wait [%],16.96,1.42,45.06,45.14,0.62,0.22,51.57,27.13
Total I/O Wait Time [s],0.17,0.01,378.85,0.01,0.03,2.03,567.05,0.07
Number of Idle Sessions,0.51,0.0,0.5,0.41,0.0,0.0,0.0,0.0
Number of Idle-in-transaction Sessions,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Number of Idle-in-transaction Aborted Sessions,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Number of Active Sessions,1.0,6.0,6.0,14.0,6.0,12.0,7.0,9.0
Number of Active Application Sessions,1.0,6.0,7.0,14.0,6.0,12.0,7.0,9.0
Longest Active Transaction,1.39,1.52,3.0,1.05,4.5,3.82,6.29,5.18
Longest Idle Session (no transaction),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Longest Idle-in-Transaction,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Longest Idle-in-Transaction (Aborted),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Active Backends Waiting on I/O,0.0,0.0,1.49,0.0,0.0,0.0,1.24,0.0
Active Backends Waiting on WAL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Active Backends Waiting on Locks,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Max Transaction Duration (I/O Wait),0.0,0.0,2.7,0.0,0.0,0.0,3.83,0.0
Max Transaction Duration (WAL Wait),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Max Transaction Duration (Lock Wait),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Disk Blocks Read Count,68816.0,0.0,561331.0,0.0,141677.0,0.0,1126572.0,0.0
Buffer Cache Hit Count,12007592.0,27863012.0,11519332.0,23979758.0,29738918.0,54165762.0,25971705.0,56259630.0
Buffer Cache Hit Ratio,0.94,0.98,0.99,0.99,0.99,1.0,0.99,0.99
Index Scan Count,1655068.0,3347073.0,1655068.0,3310128.0,3787019.0,7573926.0,3786963.0,7573968.0
Index Tuple Fetch Count,7285353.0,15714468.0,7285353.0,14570698.0,17452007.0,34903566.0,17451783.0,34903734.0
Index Cache Hit Ratio,0.83,0.99,1.0,1.0,1.0,1.0,1.0,1.0
Table Buffer Hit Count,7129428.0,17860713.0,6637087.0,14097214.0,18580301.0,31581658.0,14806307.0,33673975.0
Table Blocks Read Count,0.0,0.0,492339.0,0.0,0.0,0.0,984522.0,0.0
Table Cache Hit Ratio,0.94,0.98,0.98,0.98,0.98,0.99,0.99,0.99
Total Cache Hit Ratio,0.94,0.98,0.99,0.99,0.99,1.0,0.99,0.99
BGWriter Efficiency Ratio (Cleaned / Allocated),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
BGWriter Stopped Due to Max Pages,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Total Locks Current,4.27,10.39,9.21,27.23,17.79,47.79,15.57,29.68
AccessExclusiveLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AccessShareLocks Current,4.27,10.39,9.21,27.23,17.79,47.79,15.57,29.68
ExclusiveLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RowExclusiveLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RowShareLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ShareLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ShareRowExclusiveLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ShareUpdateExclusiveLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
SIReadLocks Current,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Autoanalyze Run Count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Autovacuum Run Count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.0,NaN,NaN,NaN,0.0,NaN
Number of WAL Segments,205.0,205.0,205.0,205.0,410.0,410.0,410.0,410.0
Total WAL Size [GiB],3.2,3.2,3.2,3.2,6.41,6.41,6.41,6.41
WAL Segments Growth Rate [segments/s],0.64,0.01,0.0,0.0,0.0,0.0,0.0,0.0
WAL Growth Rate [MiB/s],10.21,0.08,0.0,0.0,0.0,0.0,0.0,0.0
Average WAL Segment Size [MiB],16.0,16.0,16.0,16.0,16.0,16.0,16.0,16.0
code,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
connection,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2
time_load,455.0,455.0,455.0,455.0,1256.0,1256.0,1256.0,1256.0
time_ingest,141.0,141.0,141.0,141.0,350.0,350.0,350.0,350.0
time_check,291.0,291.0,291.0,291.0,843.0,843.0,843.0,843.0
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151015,151015,151015,151015,151015,151015,151015,151015
host_datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Bar Plots of Aggregated Values per Metric

In [11]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_per_connection(code, metric=metric)
df.T

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2
0,9770.968750,10315.593750,10315.644531,10300.511719
1,9770.968750,10315.593750,10315.644531,10300.511719
2,9770.968750,10315.593750,10315.644531,10300.511719
3,9770.968750,10315.593750,10315.644531,10300.511719
4,9770.968750,10315.593750,10315.644531,10300.511719
5,9838.882812,10315.593750,10315.644531,10300.511719
6,9838.882812,10315.593750,10315.644531,10300.511719
7,9838.882812,10315.593750,10315.644531,10300.511719
8,9838.882812,10315.593750,10315.644531,10300.511719
9,9838.882812,10315.593750,10315.644531,10300.511719
10,9838.882812,10315.593750,10315.644531,10300.511719
11,9838.882812,10315.593750,10315.644531,10300.511719
12,9838.882812,10315.593750,10315.644531,10300.511719
13,9838.882812,10315.593750,10315.644531,10300.511719
14,9838.882812,10315.593750,10315.644531,10300.511719
15,9838.882812,10315.593750,10315.644531,10300.511719
16,9838.882812,10496.984375,10315.644531,10300.511719
17,9838.882812,10496.984375,10315.644531,10300.511719
18,9838.882812,10496.984375,10315.644531,10300.511719
19,9838.882812,10496.984375,10315.644531,10300.511719
20,9838.882812,10496.984375,10315.644531,10300.511719
21,9838.882812,10496.984375,10315.644531,10300.511719
22,9838.882812,10496.984375,10315.644531,10300.511719
23,9838.882812,10496.984375,10315.644531,10300.511719
24,9838.882812,10496.984375,10315.644531,10300.511719
25,9838.882812,10496.984375,10315.644531,10300.511719
26,9838.882812,10496.984375,10315.644531,10300.511719
27,9838.882812,10496.984375,10315.644531,10300.511719
28,9838.882812,10496.984375,10315.644531,10300.511719
29,9838.882812,10496.984375,10315.644531,10300.511719
30,9838.882812,10496.984375,10315.644531,10300.511719
31,9838.882812,10496.984375,10315.644531,10459.210938
32,9838.882812,10496.984375,10315.644531,10459.210938
33,9838.882812,10496.984375,10315.644531,10459.210938
34,9838.882812,10496.984375,10315.644531,10459.210938
35,9838.882812,10496.984375,10315.644531,10459.210938
36,10386.679688,10496.984375,10315.644531,10459.210938
37,10386.679688,10496.984375,10315.644531,10459.210938
38,10386.679688,10496.984375,10315.644531,10459.210938
39,10386.679688,10496.984375,10315.644531,10459.210938
40,10386.679688,10496.984375,10315.644531,10459.210938
41,10386.679688,10496.984375,10315.644531,10459.210938
42,10386.679688,10496.984375,10315.644531,10459.210938
43,10386.679688,10496.984375,10315.644531,10459.210938
44,10386.679688,10496.984375,10315.644531,10459.210938
45,10386.679688,10496.984375,10315.644531,10459.210938
46,10386.679688,10496.984375,10315.644531,10459.210938
47,10386.679688,10496.984375,10315.644531,10459.210938
48,10386.679688,18388.652344,10315.644531,10459.210938
49,10386.679688,18388.652344,10315.644531,10459.210938
50,10386.679688,18388.652344,10315.644531,10459.210938
51,16823.523438,18388.652344,10315.644531,10459.210938
52,16823.523438,18388.652344,10315.644531,10459.210938
53,16823.523438,18388.652344,10315.644531,10459.210938
54,16823.523438,18388.652344,10315.644531,10459.210938
55,16823.523438,18388.652344,10315.644531,26487.359375
56,16823.523438,18388.652344,10315.644531,26487.359375
57,16823.523438,18388.652344,10315.644531,26487.359375
58,16823.523438,18388.652344,10315.644531,26487.359375
59,NaN,18388.652344,10315.644531,26487.359375
60,NaN,18388.652344,10315.644531,26487.359375
61,NaN,NaN,10315.644531,NaN
62,NaN,NaN,10315.644531,NaN
63,NaN,NaN,10315.644531,NaN
64,NaN,NaN,10315.644531,NaN
65,NaN,NaN,10315.644531,NaN
66,NaN,NaN,10315.644531,NaN
67,NaN,NaN,10315.644531,NaN
68,NaN,NaN,10315.644531,NaN
69,NaN,NaN,10315.644531,NaN
70,NaN,NaN,10315.644531,NaN
71,NaN,NaN,10315.644531,NaN
72,NaN,NaN,10315.644531,NaN
73,NaN,NaN,10315.644531,NaN
74,NaN,NaN,10315.644531,NaN
75,NaN,NaN,10315.644531,NaN
76,NaN,NaN,10315.644531,NaN
77,NaN,NaN,10315.644531,NaN
78,NaN,NaN,10315.644531,NaN
79,NaN,NaN,10315.644531,NaN
80,NaN,NaN,10315.644531,NaN
81,NaN,NaN,10315.644531,NaN
82,NaN,NaN,10315.644531,NaN
83,NaN,NaN,10315.644531,NaN
84,NaN,NaN,10315.644531,NaN
85,NaN,NaN,10315.644531,NaN
86,NaN,NaN,10315.644531,NaN
87,NaN,NaN,10315.644531,NaN
88,NaN,NaN,10315.644531,NaN
89,NaN,NaN,10354.878906,NaN
90,NaN,NaN,10354.878906,NaN
91,NaN,NaN,10354.878906,NaN
92,NaN,NaN,10354.878906,NaN
93,NaN,NaN,10354.878906,NaN
94,NaN,NaN,10354.878906,NaN
95,NaN,NaN,10354.878906,NaN
96,NaN,NaN,10354.878906,NaN
97,NaN,NaN,10354.878906,NaN
98,NaN,NaN,10354.878906,NaN
99,NaN,NaN,10354.878906,NaN
100,NaN,NaN,10354.878906,NaN
101,NaN,NaN,10354.878906,NaN
102,NaN,NaN,10354.878906,NaN
103,NaN,NaN,10354.878906,NaN
104,NaN,NaN,10354.878906,NaN
105,NaN,NaN,10354.878906,NaN
106,NaN,NaN,10354.878906,NaN
107,NaN,NaN,10354.878906,NaN
108,NaN,NaN,10354.878906,NaN
109,NaN,NaN,10354.878906,NaN
110,NaN,NaN,10354.878906,NaN
111,NaN,NaN,10354.878906,NaN
112,NaN,NaN,10354.878906,NaN
113,NaN,NaN,10354.878906,NaN
114,NaN,NaN,10354.878906,NaN
115,NaN,NaN,10354.878906,NaN
116,NaN,NaN,10354.878906,NaN
117,NaN,NaN,10354.878906,NaN
118,NaN,NaN,10354.878906,NaN
119,NaN,NaN,10354.878906,NaN
120,NaN,NaN,18372.531250,NaN

In [12]:
df_performance = collect.add_metadata(df)
df_performance.T

combine on index

,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2
0,9770.96875,10315.59375,10315.644531,10300.511719
1,9770.96875,10315.59375,10315.644531,10300.511719
2,9770.96875,10315.59375,10315.644531,10300.511719
3,9770.96875,10315.59375,10315.644531,10300.511719
4,9770.96875,10315.59375,10315.644531,10300.511719
5,9838.882812,10315.59375,10315.644531,10300.511719
6,9838.882812,10315.59375,10315.644531,10300.511719
7,9838.882812,10315.59375,10315.644531,10300.511719
8,9838.882812,10315.59375,10315.644531,10300.511719
9,9838.882812,10315.59375,10315.644531,10300.511719
10,9838.882812,10315.59375,10315.644531,10300.511719
11,9838.882812,10315.59375,10315.644531,10300.511719
12,9838.882812,10315.59375,10315.644531,10300.511719
13,9838.882812,10315.59375,10315.644531,10300.511719
14,9838.882812,10315.59375,10315.644531,10300.511719
15,9838.882812,10315.59375,10315.644531,10300.511719
16,9838.882812,10496.984375,10315.644531,10300.511719
17,9838.882812,10496.984375,10315.644531,10300.511719
18,9838.882812,10496.984375,10315.644531,10300.511719
19,9838.882812,10496.984375,10315.644531,10300.511719
20,9838.882812,10496.984375,10315.644531,10300.511719
21,9838.882812,10496.984375,10315.644531,10300.511719
22,9838.882812,10496.984375,10315.644531,10300.511719
23,9838.882812,10496.984375,10315.644531,10300.511719
24,9838.882812,10496.984375,10315.644531,10300.511719
25,9838.882812,10496.984375,10315.644531,10300.511719
26,9838.882812,10496.984375,10315.644531,10300.511719
27,9838.882812,10496.984375,10315.644531,10300.511719
28,9838.882812,10496.984375,10315.644531,10300.511719
29,9838.882812,10496.984375,10315.644531,10300.511719
30,9838.882812,10496.984375,10315.644531,10300.511719
31,9838.882812,10496.984375,10315.644531,10459.210938
32,9838.882812,10496.984375,10315.644531,10459.210938
33,9838.882812,10496.984375,10315.644531,10459.210938
34,9838.882812,10496.984375,10315.644531,10459.210938
35,9838.882812,10496.984375,10315.644531,10459.210938
36,10386.679688,10496.984375,10315.644531,10459.210938
37,10386.679688,10496.984375,10315.644531,10459.210938
38,10386.679688,10496.984375,10315.644531,10459.210938
39,10386.679688,10496.984375,10315.644531,10459.210938
40,10386.679688,10496.984375,10315.644531,10459.210938
41,10386.679688,10496.984375,10315.644531,10459.210938
42,10386.679688,10496.984375,10315.644531,10459.210938
43,10386.679688,10496.984375,10315.644531,10459.210938
44,10386.679688,10496.984375,10315.644531,10459.210938
45,10386.679688,10496.984375,10315.644531,10459.210938
46,10386.679688,10496.984375,10315.644531,10459.210938
47,10386.679688,10496.984375,10315.644531,10459.210938
48,10386.679688,18388.652344,10315.644531,10459.210938
49,10386.679688,18388.652344,10315.644531,10459.210938
50,10386.679688,18388.652344,10315.644531,10459.210938
51,16823.523438,18388.652344,10315.644531,10459.210938
52,16823.523438,18388.652344,10315.644531,10459.210938
53,16823.523438,18388.652344,10315.644531,10459.210938
54,16823.523438,18388.652344,10315.644531,10459.210938
55,16823.523438,18388.652344,10315.644531,26487.359375
56,16823.523438,18388.652344,10315.644531,26487.359375
57,16823.523438,18388.652344,10315.644531,26487.359375
58,16823.523438,18388.652344,10315.644531,26487.359375
59,NaN,18388.652344,10315.644531,26487.359375
60,NaN,18388.652344,10315.644531,26487.359375
61,NaN,NaN,10315.644531,NaN
62,NaN,NaN,10315.644531,NaN
63,NaN,NaN,10315.644531,NaN
64,NaN,NaN,10315.644531,NaN
65,NaN,NaN,10315.644531,NaN
66,NaN,NaN,10315.644531,NaN
67,NaN,NaN,10315.644531,NaN
68,NaN,NaN,10315.644531,NaN
69,NaN,NaN,10315.644531,NaN
70,NaN,NaN,10315.644531,NaN
71,NaN,NaN,10315.644531,NaN
72,NaN,NaN,10315.644531,NaN
73,NaN,NaN,10315.644531,NaN
74,NaN,NaN,10315.644531,NaN
75,NaN,NaN,10315.644531,NaN
76,NaN,NaN,10315.644531,NaN
77,NaN,NaN,10315.644531,NaN
78,NaN,NaN,10315.644531,NaN
79,NaN,NaN,10315.644531,NaN
80,NaN,NaN,10315.644531,NaN
81,NaN,NaN,10315.644531,NaN
82,NaN,NaN,10315.644531,NaN
83,NaN,NaN,10315.644531,NaN
84,NaN,NaN,10315.644531,NaN
85,NaN,NaN,10315.644531,NaN
86,NaN,NaN,10315.644531,NaN
87,NaN,NaN,10315.644531,NaN
88,NaN,NaN,10315.644531,NaN
89,NaN,NaN,10354.878906,NaN
90,NaN,NaN,10354.878906,NaN
91,NaN,NaN,10354.878906,NaN
92,NaN,NaN,10354.878906,NaN
93,NaN,NaN,10354.878906,NaN
94,NaN,NaN,10354.878906,NaN
95,NaN,NaN,10354.878906,NaN
96,NaN,NaN,10354.878906,NaN
97,NaN,NaN,10354.878906,NaN
98,NaN,NaN,10354.878906,NaN
99,NaN,NaN,10354.878906,NaN
100,NaN,NaN,10354.878906,NaN
101,NaN,NaN,10354.878906,NaN
102,NaN,NaN,10354.878906,NaN
103,NaN,NaN,10354.878906,NaN
104,NaN,NaN,10354.878906,NaN
105,NaN,NaN,10354.878906,NaN
106,NaN,NaN,10354.878906,NaN
107,NaN,NaN,10354.878906,NaN
108,NaN,NaN,10354.878906,NaN
109,NaN,NaN,10354.878906,NaN
110,NaN,NaN,10354.878906,NaN
111,NaN,NaN,10354.878906,NaN
112,NaN,NaN,10354.878906,NaN
113,NaN,NaN,10354.878906,NaN
114,NaN,NaN,10354.878906,NaN
115,NaN,NaN,10354.878906,NaN
116,NaN,NaN,10354.878906,NaN
117,NaN,NaN,10354.878906,NaN
118,NaN,NaN,10354.878906,NaN
119,NaN,NaN,10354.878906,NaN
120,NaN,NaN,18372.53125,NaN
code,1776418956,1776418956,1776418956,1776418956
experiment_run,1,1,2,2
client,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
connection,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2
time_load,455.0,455.0,455.0,455.0
time_ingest,141.0,141.0,141.0,141.0
time_check,291.0,291.0,291.0,291.0
terminals,0,0,0,0
pods,1,2,1,2
tenant,,,,
num_worker,0,0,0,0
host_RAM,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,
host_Cores,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,151015,151015,151015,151015
host_datadisk,8187,8187,8187,8187
host_volume_size,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3
loading_parameters_PODS_TOTAL,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1
loading_parameters_TPCH_TABLE,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
benchmarking_parameters_SF,3,3,3,3
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0

In [13]:
metric = 'total_cpu_memory'
code = codes[0]
collect.get_monitoring_timeseries_all(metric=metric)

,timestamp,code,experiment_run,client,type,vol_tenants,num_tenants,value
0,0,1776418956,1,1,None,False,0,9770.968750
1,0,1776418956,1,2,None,False,0,10315.593750
2,0,1776418956,2,1,None,False,0,10315.644531
3,0,1776418956,2,2,None,False,0,10300.511719
4,1,1776418956,1,1,None,False,0,9770.968750
5,1,1776418956,1,2,None,False,0,10315.593750
6,1,1776418956,2,1,None,False,0,10315.644531
7,1,1776418956,2,2,None,False,0,10300.511719
8,2,1776418956,1,1,None,False,0,9770.968750
9,2,1776418956,1,2,None,False,0,10315.593750
10,2,1776418956,2,1,None,False,0,10315.644531
11,2,1776418956,2,2,None,False,0,10300.511719
12,3,1776418956,1,1,None,False,0,9770.968750
13,3,1776418956,1,2,None,False,0,10315.593750
14,3,1776418956,2,1,None,False,0,10315.644531
15,3,1776418956,2,2,None,False,0,10300.511719
16,4,1776418956,1,1,None,False,0,9770.968750
17,4,1776418956,1,2,None,False,0,10315.593750
18,4,1776418956,2,1,None,False,0,10315.644531
19,4,1776418956,2,2,None,False,0,10300.511719
20,5,1776418956,1,1,None,False,0,9838.882812
21,5,1776418956,1,2,None,False,0,10315.593750
22,5,1776418956,2,1,None,False,0,10315.644531
23,5,1776418956,2,2,None,False,0,10300.511719
24,6,1776418956,1,1,None,False,0,9838.882812
25,6,1776418956,1,2,None,False,0,10315.593750
26,6,1776418956,2,1,None,False,0,10315.644531
27,6,1776418956,2,2,None,False,0,10300.511719
28,7,1776418956,1,1,None,False,0,9838.882812
29,7,1776418956,1,2,None,False,0,10315.593750
30,7,1776418956,2,1,None,False,0,10315.644531
31,7,1776418956,2,2,None,False,0,10300.511719
32,8,1776418956,1,1,None,False,0,9838.882812
33,8,1776418956,1,2,None,False,0,10315.593750
34,8,1776418956,2,1,None,False,0,10315.644531
35,8,1776418956,2,2,None,False,0,10300.511719
36,9,1776418956,1,1,None,False,0,9838.882812
37,9,1776418956,1,2,None,False,0,10315.593750
38,9,1776418956,2,1,None,False,0,10315.644531
39,9,1776418956,2,2,None,False,0,10300.511719
40,10,1776418956,1,1,None,False,0,9838.882812
41,10,1776418956,1,2,None,False,0,10315.593750
42,10,1776418956,2,1,None,False,0,10315.644531
43,10,1776418956,2,2,None,False,0,10300.511719
44,11,1776418956,1,1,None,False,0,9838.882812
45,11,1776418956,1,2,None,False,0,10315.593750
46,11,1776418956,2,1,None,False,0,10315.644531
47,11,1776418956,2,2,None,False,0,10300.511719
48,12,1776418956,1,1,None,False,0,9838.882812
49,12,1776418956,1,2,None,False,0,10315.593750
50,12,1776418956,2,1,None,False,0,10315.644531
51,12,1776418956,2,2,None,False,0,10300.511719
52,13,1776418956,1,1,None,False,0,9838.882812
53,13,1776418956,1,2,None,False,0,10315.593750
54,13,1776418956,2,1,None,False,0,10315.644531
55,13,1776418956,2,2,None,False,0,10300.511719
56,14,1776418956,1,1,None,False,0,9838.882812
57,14,1776418956,1,2,None,False,0,10315.593750
58,14,1776418956,2,1,None,False,0,10315.644531
59,14,1776418956,2,2,None,False,0,10300.511719
60,15,1776418956,1,1,None,False,0,9838.882812
61,15,1776418956,1,2,None,False,0,10315.593750
62,15,1776418956,2,1,None,False,0,10315.644531
63,15,1776418956,2,2,None,False,0,10300.511719
64,16,1776418956,1,1,None,False,0,9838.882812
65,16,1776418956,1,2,None,False,0,10496.984375
66,16,1776418956,2,1,None,False,0,10315.644531
67,16,1776418956,2,2,None,False,0,10300.511719
68,17,1776418956,1,1,None,False,0,9838.882812
69,17,1776418956,1,2,None,False,0,10496.984375
70,17,1776418956,2,1,None,False,0,10315.644531
71,17,1776418956,2,2,None,False,0,10300.511719
72,18,1776418956,1,1,None,False,0,9838.882812
73,18,1776418956,1,2,None,False,0,10496.984375
74,18,1776418956,2,1,None,False,0,10315.644531
75,18,1776418956,2,2,None,False,0,10300.511719
76,19,1776418956,1,1,None,False,0,9838.882812
77,19,1776418956,1,2,None,False,0,10496.984375
78,19,1776418956,2,1,None,False,0,10315.644531
79,19,1776418956,2,2,None,False,0,10300.511719
80,20,1776418956,1,1,None,False,0,9838.882812
81,20,1776418956,1,2,None,False,0,10496.984375
82,20,1776418956,2,1,None,False,0,10315.644531
83,20,1776418956,2,2,None,False,0,10300.511719
84,21,1776418956,1,1,None,False,0,9838.882812
85,21,1776418956,1,2,None,False,0,10496.984375
86,21,1776418956,2,1,None,False,0,10315.644531
87,21,1776418956,2,2,None,False,0,10300.511719
88,22,1776418956,1,1,None,False,0,9838.882812
89,22,1776418956,1,2,None,False,0,10496.984375
90,22,1776418956,2,1,None,False,0,10315.644531
91,22,1776418956,2,2,None,False,0,10300.511719
92,23,1776418956,1,1,None,False,0,9838.882812
93,23,1776418956,1,2,None,False,0,10496.984375
94,23,1776418956,2,1,None,False,0,10315.644531
95,23,1776418956,2,2,None,False,0,10300.511719
96,24,1776418956,1,1,None,False,0,9838.882812
97,24,1776418956,1,2,None,False,0,10496.984375
98,24,1776418956,2,1,None,False,0,10315.644531
99,24,1776418956,2,2,None,False,0,10300.511719
100,25,1776418956,1,1,None,False,0,9838.882812
101,25,1776418956,1,2,None,False,0,10496.984375
102,25,1776418956,2,1,None,False,0,10315.644531
103,25,1776418956,2,2,None,False,0,10300.511719
104,26,1776418956,1,1,None,False,0,9838.882812
105,26,1776418956,1,2,None,False,0,10496.984375
106,26,1776418956,2,1,None,False,0,10315.644531
107,26,1776418956,2,2,None,False,0,10300.511719
108,27,1776418956,1,1,None,False,0,9838.882812
109,27,1776418956,1,2,None,False,0,10496.984375
110,27,1776418956,2,1,None,False,0,10315.644531
111,27,1776418956,2,2,None,False,0,10300.511719
112,28,1776418956,1,1,None,False,0,9838.882812
113,28,1776418956,1,2,None,False,0,10496.984375
114,28,1776418956,2,1,None,False,0,10315.644531
115,28,1776418956,2,2,None,False,0,10300.511719
116,29,1776418956,1,1,None,False,0,9838.882812
117,29,1776418956,1,2,None,False,0,10496.984375
118,29,1776418956,2,1,None,False,0,10315.644531
119,29,1776418956,2,2,None,False,0,10300.511719
120,30,1776418956,1,1,None,False,0,9838.882812
121,30,1776418956,1,2,None,False,0,10496.984375
122,30,1776418956,2,1,None,False,0,10315.644531
123,30,1776418956,2,2,None,False,0,10300.511719
124,31,1776418956,1,1,None,False,0,9838.882812
125,31,1776418956,1,2,None,False,0,10496.984375
126,31,1776418956,2,1,None,False,0,10315.644531
127,31,1776418956,2,2,None,False,0,10459.210938
128,32,1776418956,1,1,None,False,0,9838.882812
129,32,1776418956,1,2,None,False,0,10496.984375
130,32,1776418956,2,1,None,False,0,10315.644531
131,32,1776418956,2,2,None,False,0,10459.210938
132,33,1776418956,1,1,None,False,0,9838.882812
133,33,1776418956,1,2,None,False,0,10496.984375
134,33,1776418956,2,1,None,False,0,10315.644531
135,33,1776418956,2,2,None,False,0,10459.210938
136,34,1776418956,1,1,None,False,0,9838.882812
137,34,1776418956,1,2,None,False,0,10496.984375
138,34,1776418956,2,1,None,False,0,10315.644531
139,34,1776418956,2,2,None,False,0,10459.210938
140,35,1776418956,1,1,None,False,0,9838.882812
141,35,1776418956,1,2,None,False,0,10496.984375
142,35,1776418956,2,1,None,False,0,10315.644531
143,35,1776418956,2,2,None,False,0,10459.210938
144,36,1776418956,1,1,None,False,0,10386.679688
145,36,1776418956,1,2,None,False,0,10496.984375
146,36,1776418956,2,1,None,False,0,10315.644531
147,36,1776418956,2,2,None,False,0,10459.210938
148,37,1776418956,1,1,None,False,0,10386.679688
149,37,1776418956,1,2,None,False,0,10496.984375
150,37,1776418956,2,1,None,False,0,10315.644531
151,37,1776418956,2,2,None,False,0,10459.210938
152,38,1776418956,1,1,None,False,0,10386.679688
153,38,1776418956,1,2,None,False,0,10496.984375
154,38,1776418956,2,1,None,False,0,10315.644531
155,38,1776418956,2,2,None,False,0,10459.210938
156,39,1776418956,1,1,None,False,0,10386.679688
157,39,1776418956,1,2,None,False,0,10496.984375
158,39,1776418956,2,1,None,False,0,10315.644531
159,39,1776418956,2,2,None,False,0,10459.210938
160,40,1776418956,1,1,None,False,0,10386.679688
161,40,1776418956,1,2,None,False,0,10496.984375
162,40,1776418956,2,1,None,False,0,10315.644531
163,40,1776418956,2,2,None,False,0,10459.210938
164,41,1776418956,1,1,None,False,0,10386.679688
165,41,1776418956,1,2,None,False,0,10496.984375
166,41,1776418956,2,1,None,False,0,10315.644531
167,41,1776418956,2,2,None,False,0,10459.210938
168,42,1776418956,1,1,None,False,0,10386.679688
169,42,1776418956,1,2,None,False,0,10496.984375
170,42,1776418956,2,1,None,False,0,10315.644531
171,42,1776418956,2,2,None,False,0,10459.210938
172,43,1776418956,1,1,None,False,0,10386.679688
173,43,1776418956,1,2,None,False,0,10496.984375
174,43,1776418956,2,1,None,False,0,10315.644531
175,43,1776418956,2,2,None,False,0,10459.210938
176,44,1776418956,1,1,None,False,0,10386.679688
177,44,1776418956,1,2,None,False,0,10496.984375
178,44,1776418956,2,1,None,False,0,10315.644531
179,44,1776418956,2,2,None,False,0,10459.210938
180,45,1776418956,1,1,None,False,0,10386.679688
181,45,1776418956,1,2,None,False,0,10496.984375
182,45,1776418956,2,1,None,False,0,10315.644531
183,45,1776418956,2,2,None,False,0,10459.210938
184,46,1776418956,1,1,None,False,0,10386.679688
185,46,1776418956,1,2,None,False,0,10496.984375
186,46,1776418956,2,1,None,False,0,10315.644531
187,46,1776418956,2,2,None,False,0,10459.210938
188,47,1776418956,1,1,None,False,0,10386.679688
189,47,1776418956,1,2,None,False,0,10496.984375
190,47,1776418956,2,1,None,False,0,10315.644531
191,47,1776418956,2,2,None,False,0,10459.210938
192,48,1776418956,1,1,None,False,0,10386.679688
193,48,1776418956,1,2,None,False,0,18388.652344
194,48,1776418956,2,1,None,False,0,10315.644531
195,48,1776418956,2,2,None,False,0,10459.210938
196,49,1776418956,1,1,None,False,0,10386.679688
197,49,1776418956,1,2,None,False,0,18388.652344
198,49,1776418956,2,1,None,False,0,10315.644531
199,49,1776418956,2,2,None,False,0,10459.210938
200,50,1776418956,1,1,None,False,0,10386.679688
201,50,1776418956,1,2,None,False,0,18388.652344
202,50,1776418956,2,1,None,False,0,10315.644531
203,50,1776418956,2,2,None,False,0,10459.210938
204,51,1776418956,1,1,None,False,0,16823.523438
205,51,1776418956,1,2,None,False,0,18388.652344
206,51,1776418956,2,1,None,False,0,10315.644531
207,51,1776418956,2,2,None,False,0,10459.210938
208,52,1776418956,1,1,None,False,0,16823.523438
209,52,1776418956,1,2,None,False,0,18388.652344
210,52,1776418956,2,1,None,False,0,10315.644531
211,52,1776418956,2,2,None,False,0,10459.210938
212,53,1776418956,1,1,None,False,0,16823.523438
213,53,1776418956,1,2,None,False,0,18388.652344
214,53,1776418956,2,1,None,False,0,10315.644531
215,53,1776418956,2,2,None,False,0,10459.210938
216,54,1776418956,1,1,None,False,0,16823.523438
217,54,1776418956,1,2,None,False,0,18388.652344
218,54,1776418956,2,1,None,False,0,10315.644531
219,54,1776418956,2,2,None,False,0,10459.210938
220,55,1776418956,1,1,None,False,0,16823.523438
221,55,1776418956,1,2,None,False,0,18388.652344
222,55,1776418956,2,1,None,False,0,10315.644531
223,55,1776418956,2,2,None,False,0,26487.359375
224,56,1776418956,1,1,None,False,0,16823.523438
225,56,1776418956,1,2,None,False,0,18388.652344
226,56,1776418956,2,1,None,False,0,10315.644531
227,56,1776418956,2,2,None,False,0,26487.359375
228,57,1776418956,1,1,None,False,0,16823.523438
229,57,1776418956,1,2,None,False,0,18388.652344
230,57,1776418956,2,1,None,False,0,10315.644531
231,57,1776418956,2,2,None,False,0,26487.359375
232,58,1776418956,1,1,None,False,0,16823.523438
233,58,1776418956,1,2,None,False,0,18388.652344
234,58,1776418956,2,1,None,False,0,10315.644531
235,58,1776418956,2,2,None,False,0,26487.359375
236,59,1776418956,1,1,None,False,0,0.000000
237,59,1776418956,1,2,None,False,0,18388.652344
238,59,1776418956,2,1,None,False,0,10315.644531
239,59,1776418956,2,2,None,False,0,26487.359375
240,60,1776418956,1,1,None,False,0,0.000000
241,60,1776418956,1,2,None,False,0,18388.652344
242,60,1776418956,2,1,None,False,0,10315.644531
243,60,1776418956,2,2,None,False,0,26487.359375
244,61,1776418956,1,1,None,False,0,0.000000
245,61,1776418956,1,2,None,False,0,0.000000
246,61,1776418956,2,1,None,False,0,10315.644531
247,61,1776418956,2,2,None,False,0,0.000000
248,62,1776418956,1,1,None,False,0,0.000000
249,62,1776418956,1,2,None,False,0,0.000000
250,62,1776418956,2,1,None,False,0,10315.644531
251,62,1776418956,2,2,None,False,0,0.000000
252,63,1776418956,1,1,None,False,0,0.000000
253,63,1776418956,1,2,None,False,0,0.000000
254,63,1776418956,2,1,None,False,0,10315.644531
255,63,1776418956,2,2,None,False,0,0.000000
256,64,1776418956,1,1,None,False,0,0.000000
257,64,1776418956,1,2,None,False,0,0.000000
258,64,1776418956,2,1,None,False,0,10315.644531
259,64,1776418956,2,2,None,False,0,0.000000
260,65,1776418956,1,1,None,False,0,0.000000
261,65,1776418956,1,2,None,False,0,0.000000
262,65,1776418956,2,1,None,False,0,10315.644531
263,65,1776418956,2,2,None,False,0,0.000000
264,66,1776418956,1,1,None,False,0,0.000000
265,66,1776418956,1,2,None,False,0,0.000000
266,66,1776418956,2,1,None,False,0,10315.644531
267,66,1776418956,2,2,None,False,0,0.000000
268,67,1776418956,1,1,None,False,0,0.000000
269,67,1776418956,1,2,None,False,0,0.000000
270,67,1776418956,2,1,None,False,0,10315.644531
271,67,1776418956,2,2,None,False,0,0.000000
272,68,1776418956,1,1,None,False,0,0.000000
273,68,1776418956,1,2,None,False,0,0.000000
274,68,1776418956,2,1,None,False,0,10315.644531
275,68,1776418956,2,2,None,False,0,0.000000
276,69,1776418956,1,1,None,False,0,0.000000
277,69,1776418956,1,2,None,False,0,0.000000
278,69,1776418956,2,1,None,False,0,10315.644531
279,69,1776418956,2,2,None,False,0,0.000000
280,70,1776418956,1,1,None,False,0,0.000000
281,70,1776418956,1,2,None,False,0,0.000000
282,70,1776418956,2,1,None,False,0,10315.644531
283,70,1776418956,2,2,None,False,0,0.000000
284,71,1776418956,1,1,None,False,0,0.000000
285,71,1776418956,1,2,None,False,0,0.000000
286,71,1776418956,2,1,None,False,0,10315.644531
287,71,1776418956,2,2,None,False,0,0.000000
288,72,1776418956,1,1,None,False,0,0.000000
289,72,1776418956,1,2,None,False,0,0.000000
290,72,1776418956,2,1,None,False,0,10315.644531
291,72,1776418956,2,2,None,False,0,0.000000
292,73,1776418956,1,1,None,False,0,0.000000
293,73,1776418956,1,2,None,False,0,0.000000
294,73,1776418956,2,1,None,False,0,10315.644531
295,73,1776418956,2,2,None,False,0,0.000000
296,74,1776418956,1,1,None,False,0,0.000000
297,74,1776418956,1,2,None,False,0,0.000000
298,74,1776418956,2,1,None,False,0,10315.644531
299,74,1776418956,2,2,None,False,0,0.000000
300,75,1776418956,1,1,None,False,0,0.000000
301,75,1776418956,1,2,None,False,0,0.000000
302,75,1776418956,2,1,None,False,0,10315.644531
303,75,1776418956,2,2,None,False,0,0.000000
304,76,1776418956,1,1,None,False,0,0.000000
305,76,1776418956,1,2,None,False,0,0.000000
306,76,1776418956,2,1,None,False,0,10315.644531
307,76,1776418956,2,2,None,False,0,0.000000
308,77,1776418956,1,1,None,False,0,0.000000
309,77,1776418956,1,2,None,False,0,0.000000
310,77,1776418956,2,1,None,False,0,10315.644531
311,77,1776418956,2,2,None,False,0,0.000000
312,78,1776418956,1,1,None,False,0,0.000000
313,78,1776418956,1,2,None,False,0,0.000000
314,78,1776418956,2,1,None,False,0,10315.644531
315,78,1776418956,2,2,None,False,0,0.000000
316,79,1776418956,1,1,None,False,0,0.000000
317,79,1776418956,1,2,None,False,0,0.000000
318,79,1776418956,2,1,None,False,0,10315.644531
319,79,1776418956,2,2,None,False,0,0.000000
320,80,1776418956,1,1,None,False,0,0.000000
321,80,1776418956,1,2,None,False,0,0.000000
322,80,1776418956,2,1,None,False,0,10315.644531
323,80,1776418956,2,2,None,False,0,0.000000
324,81,1776418956,1,1,None,False,0,0.000000
325,81,1776418956,1,2,None,False,0,0.000000
326,81,1776418956,2,1,None,False,0,10315.644531
327,81,1776418956,2,2,None,False,0,0.000000
328,82,1776418956,1,1,None,False,0,0.000000
329,82,1776418956,1,2,None,False,0,0.000000
330,82,1776418956,2,1,None,False,0,10315.644531
331,82,1776418956,2,2,None,False,0,0.000000
332,83,1776418956,1,1,None,False,0,0.000000
333,83,1776418956,1,2,None,False,0,0.000000
334,83,1776418956,2,1,None,False,0,10315.644531
335,83,1776418956,2,2,None,False,0,0.000000
336,84,1776418956,1,1,None,False,0,0.000000
337,84,1776418956,1,2,None,False,0,0.000000
338,84,1776418956,2,1,None,False,0,10315.644531
339,84,1776418956,2,2,None,False,0,0.000000
340,85,1776418956,1,1,None,False,0,0.000000
341,85,1776418956,1,2,None,False,0,0.000000
342,85,1776418956,2,1,None,False,0,10315.644531
343,85,1776418956,2,2,None,False,0,0.000000
344,86,1776418956,1,1,None,False,0,0.000000
345,86,1776418956,1,2,None,False,0,0.000000
346,86,1776418956,2,1,None,False,0,10315.644531
347,86,1776418956,2,2,None,False,0,0.000000
348,87,1776418956,1,1,None,False,0,0.000000
349,87,1776418956,1,2,None,False,0,0.000000
350,87,1776418956,2,1,None,False,0,10315.644531
351,87,1776418956,2,2,None,False,0,0.000000
352,88,1776418956,1,1,None,False,0,0.000000
353,88,1776418956,1,2,None,False,0,0.000000
354,88,1776418956,2,1,None,False,0,10315.644531
355,88,1776418956,2,2,None,False,0,0.000000
356,89,1776418956,1,1,None,False,0,0.000000
357,89,1776418956,1,2,None,False,0,0.000000
358,89,1776418956,2,1,None,False,0,10354.878906
359,89,1776418956,2,2,None,False,0,0.000000
360,90,1776418956,1,1,None,False,0,0.000000
361,90,1776418956,1,2,None,False,0,0.000000
362,90,1776418956,2,1,None,False,0,10354.878906
363,90,1776418956,2,2,None,False,0,0.000000
364,91,1776418956,1,1,None,False,0,0.000000
365,91,1776418956,1,2,None,False,0,0.000000
366,91,1776418956,2,1,None,False,0,10354.878906
367,91,1776418956,2,2,None,False,0,0.000000
368,92,1776418956,1,1,None,False,0,0.000000
369,92,1776418956,1,2,None,False,0,0.000000
370,92,1776418956,2,1,None,False,0,10354.878906
371,92,1776418956,2,2,None,False,0,0.000000
372,93,1776418956,1,1,None,False,0,0.000000
373,93,1776418956,1,2,None,False,0,0.000000
374,93,1776418956,2,1,None,False,0,10354.878906
375,93,1776418956,2,2,None,False,0,0.000000
376,94,1776418956,1,1,None,False,0,0.000000
377,94,1776418956,1,2,None,False,0,0.000000
378,94,1776418956,2,1,None,False,0,10354.878906
379,94,1776418956,2,2,None,False,0,0.000000
380,95,1776418956,1,1,None,False,0,0.000000
381,95,1776418956,1,2,None,False,0,0.000000
382,95,1776418956,2,1,None,False,0,10354.878906
383,95,1776418956,2,2,None,False,0,0.000000
384,96,1776418956,1,1,None,False,0,0.000000
385,96,1776418956,1,2,None,False,0,0.000000
386,96,1776418956,2,1,None,False,0,10354.878906
387,96,1776418956,2,2,None,False,0,0.000000
388,97,1776418956,1,1,None,False,0,0.000000
389,97,1776418956,1,2,None,False,0,0.000000
390,97,1776418956,2,1,None,False,0,10354.878906
391,97,1776418956,2,2,None,False,0,0.000000
392,98,1776418956,1,1,None,False,0,0.000000
393,98,1776418956,1,2,None,False,0,0.000000
394,98,1776418956,2,1,None,False,0,10354.878906
395,98,1776418956,2,2,None,False,0,0.000000
396,99,1776418956,1,1,None,False,0,0.000000
397,99,1776418956,1,2,None,False,0,0.000000
398,99,1776418956,2,1,None,False,0,10354.878906
399,99,1776418956,2,2,None,False,0,0.000000
400,100,1776418956,1,1,None,False,0,0.000000
401,100,1776418956,1,2,None,False,0,0.000000
402,100,1776418956,2,1,None,False,0,10354.878906
403,100,1776418956,2,2,None,False,0,0.000000
404,101,1776418956,1,1,None,False,0,0.000000
405,101,1776418956,1,2,None,False,0,0.000000
406,101,1776418956,2,1,None,False,0,10354.878906
407,101,1776418956,2,2,None,False,0,0.000000
408,102,1776418956,1,1,None,False,0,0.000000
409,102,1776418956,1,2,None,False,0,0.000000
410,102,1776418956,2,1,None,False,0,10354.878906
411,102,1776418956,2,2,None,False,0,0.000000
412,103,1776418956,1,1,None,False,0,0.000000
413,103,1776418956,1,2,None,False,0,0.000000
414,103,1776418956,2,1,None,False,0,10354.878906
415,103,1776418956,2,2,None,False,0,0.000000
416,104,1776418956,1,1,None,False,0,0.000000
417,104,1776418956,1,2,None,False,0,0.000000
418,104,1776418956,2,1,None,False,0,10354.878906
419,104,1776418956,2,2,None,False,0,0.000000
420,105,1776418956,1,1,None,False,0,0.000000
421,105,1776418956,1,2,None,False,0,0.000000
422,105,1776418956,2,1,None,False,0,10354.878906
423,105,1776418956,2,2,None,False,0,0.000000
424,106,1776418956,1,1,None,False,0,0.000000
425,106,1776418956,1,2,None,False,0,0.000000
426,106,1776418956,2,1,None,False,0,10354.878906
427,106,1776418956,2,2,None,False,0,0.000000
428,107,1776418956,1,1,None,False,0,0.000000
429,107,1776418956,1,2,None,False,0,0.000000

In [16]:
df_performance = collect.get_performance_aggregated_per_connection()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)
df_performance

,connection,experiment_run,total_timer_execution,Power@Size [~Q/h],code,orig_name,SF,time [s],count,client,Throughput@Size,num_of_queries
1776418956-PostgreSQL-BHT-8-1-1,PostgreSQL-BHT-8-1-1,1,1.566479,6894.444445,1776418956,PostgreSQL-BHT-8-1-1,3.0,58,1,1,4096.55,22
1776418956-PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-1-2,1,1.573540,6863.507120,1776418956,PostgreSQL-BHT-8-1-2,3.0,60,2,2,7920.00,44
1776418956-PostgreSQL-BHT-8-2-1,PostgreSQL-BHT-8-2-1,2,2.345645,4604.277867,1776418956,PostgreSQL-BHT-8-2-1,3.0,120,1,1,1980.00,22
1776418956-PostgreSQL-BHT-8-2-2,PostgreSQL-BHT-8-2-2,2,1.588448,6799.089476,1776418956,PostgreSQL-BHT-8-2-2,3.0,60,2,2,7920.00,44
1776420958-PostgreSQL-BHT-8-1-1,PostgreSQL-BHT-8-1-1,1,2.913431,7413.940216,1776420958,PostgreSQL-BHT-8-1-1,6.0,113,1,1,4205.31,22
1776420958-PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-1-2,1,2.921044,7394.616680,1776420958,PostgreSQL-BHT-8-1-2,6.0,110,2,2,8640.00,44
1776420958-PostgreSQL-BHT-8-2-1,PostgreSQL-BHT-8-2-1,2,4.244649,5088.759517,1776420958,PostgreSQL-BHT-8-2-1,6.0,210,1,1,2262.86,22
1776420958-PostgreSQL-BHT-8-2-2,PostgreSQL-BHT-8-2-2,2,2.952376,7316.141092,1776420958,PostgreSQL-BHT-8-2-2,6.0,119,2,2,7986.55,44

In [15]:
df_performance = collect.get_performance_per_pod()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

,1776418956-PostgreSQL-BHT-8-1-1-1,1776418956-PostgreSQL-BHT-8-1-2-1,1776418956-PostgreSQL-BHT-8-1-2-2,1776418956-PostgreSQL-BHT-8-2-1-1,1776418956-PostgreSQL-BHT-8-2-2-1,1776418956-PostgreSQL-BHT-8-2-2-2,1776420958-PostgreSQL-BHT-8-1-1-1,1776420958-PostgreSQL-BHT-8-1-2-1,1776420958-PostgreSQL-BHT-8-1-2-2,1776420958-PostgreSQL-BHT-8-2-1-1,1776420958-PostgreSQL-BHT-8-2-2-1,1776420958-PostgreSQL-BHT-8-2-2-2
total_timer_execution,1.566479,1.597086,1.55034,2.345645,1.588409,1.588487,2.913431,2.934896,2.907257,4.244649,2.986872,2.918278
Power@Size [~Q/h],6894.444445,6762.31504,6966.213449,4604.277867,6799.256171,6798.922785,7413.940216,7359.714573,7429.684303,5088.759517,7231.64457,7401.624895
Geo Times [s],1.566479,1.597086,1.55034,2.345645,1.588409,1.588487,2.913431,2.934896,2.907257,4.244649,2.986872,2.918278
orig_name,PostgreSQL-BHT-8-1-1,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-2-1,PostgreSQL-BHT-8-2-2,PostgreSQL-BHT-8-2-2,PostgreSQL-BHT-8-1-1,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-2-1,PostgreSQL-BHT-8-2-2,PostgreSQL-BHT-8-2-2
SF,3.0,3.0,3.0,3.0,3.0,3.0,6.0,6.0,6.0,6.0,6.0,6.0
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
time [s],58,60,57,120,59,60,113,110,110,210,119,116
count,1,1,1,1,1,1,1,1,1,1,1,1
connection,PostgreSQL-BHT-8-1-1,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-2-1,PostgreSQL-BHT-8-2-2,PostgreSQL-BHT-8-2-2,PostgreSQL-BHT-8-1-1,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-2-1,PostgreSQL-BHT-8-2-2,PostgreSQL-BHT-8-2-2
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22
Throughput@Size,4096.55,3960.0,4168.42,1980.0,4027.12,3960.0,4205.31,4320.0,4320.0,2262.86,3993.28,4096.55
code,1776418956,1776418956,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958,1776420958,1776420958

In [17]:
df = collect.add_metadata(df_performance)
df.T

combine on columns
df Duplikate: False
df_connections Duplikate: False

connection_pod,1776418956-PostgreSQL-BHT-8-1-1,1776418956-PostgreSQL-BHT-8-1-2,1776418956-PostgreSQL-BHT-8-2-1,1776418956-PostgreSQL-BHT-8-2-2,NaN,NaN,NaN,NaN,1776420958-PostgreSQL-BHT-8-1-1,1776420958-PostgreSQL-BHT-8-1-2,1776420958-PostgreSQL-BHT-8-2-1,1776420958-PostgreSQL-BHT-8-2-2,NaN,NaN,NaN,NaN
code,1776418956,1776418956,1776418956,1776418956,1776418956,1776418956,1776418956,1776418956,1776420958,1776420958,1776420958,1776420958,1776420958,1776420958,1776420958,1776420958
connection,PostgreSQL-BHT-8-1-1,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-2-1,PostgreSQL-BHT-8-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2,PostgreSQL-BHT-8-1-1,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-2-1,PostgreSQL-BHT-8-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-2
experiment_run,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN
total_timer_execution,1.566479,1.57354,2.345645,1.588448,NaN,NaN,NaN,NaN,2.913431,2.921044,4.244649,2.952376,NaN,NaN,NaN,NaN
Power@Size [~Q/h],6894.444445,6863.50712,4604.277867,6799.089476,NaN,NaN,NaN,NaN,7413.940216,7394.61668,5088.759517,7316.141092,NaN,NaN,NaN,NaN
orig_name,PostgreSQL-BHT-8-1-1,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-2-1,PostgreSQL-BHT-8-2-2,NaN,NaN,NaN,NaN,PostgreSQL-BHT-8-1-1,PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-2-1,PostgreSQL-BHT-8-2-2,NaN,NaN,NaN,NaN
SF,3.0,3.0,3.0,3.0,NaN,NaN,NaN,NaN,6.0,6.0,6.0,6.0,NaN,NaN,NaN,NaN
time [s],58.0,60.0,120.0,60.0,NaN,NaN,NaN,NaN,113.0,110.0,210.0,119.0,NaN,NaN,NaN,NaN
count,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN
client,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN,1.0,2.0,1.0,2.0,NaN,NaN,NaN,NaN
Throughput@Size,4096.55,7920.0,1980.0,7920.0,NaN,NaN,NaN,NaN,4205.31,8640.0,2262.86,7986.55,NaN,NaN,NaN,NaN
num_of_queries,22.0,44.0,22.0,44.0,NaN,NaN,NaN,NaN,22.0,44.0,22.0,44.0,NaN,NaN,NaN,NaN
dockerimage,NaN,NaN,NaN,NaN,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,NaN,NaN,NaN,NaN,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,NaN,NaN,NaN,NaN,455.0,455.0,455.0,455.0,NaN,NaN,NaN,NaN,1256.0,1256.0,1256.0,1256.0
time_ingest,NaN,NaN,NaN,NaN,141.0,141.0,141.0,141.0,NaN,NaN,NaN,NaN,350.0,350.0,350.0,350.0
time_check,NaN,NaN,NaN,NaN,291.0,291.0,291.0,291.0,NaN,NaN,NaN,NaN,843.0,843.0,843.0,843.0
terminals,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0,0,0,0
pods,NaN,NaN,NaN,NaN,1,2,1,2,NaN,NaN,NaN,NaN,1,2,1,2
tenant,NaN,NaN,NaN,NaN,,,,,NaN,NaN,NaN,NaN,,,,
num_worker,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0,0,0,0
host_RAM,NaN,NaN,NaN,NaN,541008474112,541008474112,541008474112,541008474112,NaN,NaN,NaN,NaN,541008474112,541008474112,541008474112,541008474112
host_CPU,NaN,NaN,NaN,NaN,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,NaN,NaN,NaN,NaN,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,NaN,NaN,NaN,NaN,,,,,NaN,NaN,NaN,NaN,,,,
host_Cores,NaN,NaN,NaN,NaN,64,64,64,64,NaN,NaN,NaN,NaN,64,64,64,64
host_host,NaN,NaN,NaN,NaN,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,NaN,NaN,NaN,NaN,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,NaN,NaN,NaN,NaN,cl-worker14,cl-worker14,cl-worker14,cl-worker14,NaN,NaN,NaN,NaN,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,NaN,NaN,NaN,NaN,151015,151015,151015,151015,NaN,NaN,NaN,NaN,151015,151015,151015,151015
host_datadisk,NaN,NaN,NaN,NaN,8187,8187,8187,8187,NaN,NaN,NaN,NaN,16350,16350,16350,16350
host_volume_size,NaN,NaN,NaN,NaN,30G,30G,30G,30G,NaN,NaN,NaN,NaN,30G,30G,30G,30G
host_volume_used,NaN,NaN,NaN,NaN,8.0G,8.0G,8.0G,8.0G,NaN,NaN,NaN,NaN,16G,16G,16G,16G
host_cuda,NaN,NaN,NaN,NaN,,,,,NaN,NaN,NaN,NaN,,,,
host_hugepages_total,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0,0,0,0
host_hugepages_free,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0,0,0,0
host_cpu_list,NaN,NaN,NaN,NaN,0-63,0-63,0-63,0-63,NaN,NaN,NaN,NaN,0-63,0-63,0-63,0-63
host_requests_cpu,NaN,NaN,NaN,NaN,4,4,4,4,NaN,NaN,NaN,NaN,4,4,4,4
host_requests_memory,NaN,NaN,NaN,NaN,64Gi,64Gi,64Gi,64Gi,NaN,NaN,NaN,NaN,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0,0,0,0
host_limits_memory,NaN,NaN,NaN,NaN,64Gi,64Gi,64Gi,64Gi,NaN,NaN,NaN,NaN,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,NaN,NaN,NaN,NaN,3,3,3,3,NaN,NaN,NaN,NaN,6,6,6,6
loading_parameters_PODS_TOTAL,NaN,NaN,NaN,NaN,8,8,8,8,NaN,NaN,NaN,NaN,8,8,8,8
loading_parameters_PODS_PARALLEL,NaN,NaN,NaN,NaN,8,8,8,8,NaN,NaN,NaN,NaN,8,8,8,8
loading_parameters_STORE_RAW_DATA,NaN,NaN,NaN,NaN,1,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,NaN,NaN,NaN,NaN,1,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,NaN,NaN,NaN,NaN,1,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,NaN,NaN,NaN,NaN,1,1,1,1,NaN,NaN,NaN,NaN,1,1,1,1
loading_parameters_TPCH_TABLE,NaN,NaN,NaN,NaN,,,,,NaN,NaN,NaN,NaN,,,,
loading_parameters_BEXHOMA_TENANT_BY,NaN,NaN,NaN,NaN,,,,,NaN,NaN,NaN,NaN,,,,
loading_parameters_BEXHOMA_TENANT_NUM,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0,0,0,0
benchmarking_parameters_SF,NaN,NaN,NaN,NaN,3,3,3,3,NaN,NaN,NaN,NaN,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,NaN,NaN,NaN,NaN,False,False,False,False,NaN,NaN,NaN,NaN,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,NaN,NaN,NaN,NaN,False,False,False,False,NaN,NaN,NaN,NaN,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0,0,0,0
benchmarking_parameters_TENANT_BY,NaN,NaN,NaN,NaN,,,,,NaN,NaN,NaN,NaN,,,,
benchmarking_parameters_TENANT_NUM,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,NaN,NaN,NaN,NaN,,,,,NaN,NaN,NaN,NaN,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,NaN,NaN,NaN,NaN,,,,,NaN,NaN,NaN,NaN,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,NaN,NaN,NaN,NaN,,,,,NaN,NaN,NaN,NaN,,,,
sut_parameters_BEXHOMA_WORKER_NAME,NaN,NaN,NaN,NaN,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,NaN,NaN,NaN,NaN,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,NaN,NaN,NaN,NaN,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,NaN,NaN,NaN,NaN,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,NaN,NaN,NaN,NaN,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,bexhoma-sut-postgresql-bht-8-1776418956,NaN,NaN,NaN,NaN,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958,bexhoma-sut-postgresql-bht-8-1776420958
arg_max_connections,NaN,NaN,NaN,NaN,3000,3000,3000,3000,NaN,NaN,NaN,NaN,3000,3000,3000,3000
arg_max_worker_processes,NaN,NaN,NaN,NaN,64,64,64,64,NaN,NaN,NaN,NaN,64,64,64,64
arg_max_parallel_workers,NaN,NaN,NaN,NaN,64,64,64,64,NaN,NaN,NaN,NaN,64,64,64,64
arg_max_parallel_workers_per_gather,NaN,NaN,NaN,NaN,64,64,64,64,NaN,NaN,NaN,NaN,64,64,64,64
arg_max_parallel_maintenance_workers,NaN,NaN,NaN,NaN,64,64,64,64,NaN,NaN,NaN,NaN,64,64,64,64
arg_effective_io_concurrency,NaN,NaN,NaN,NaN,64,64,64,64,NaN,NaN,NaN,NaN,64,64,64,64
arg_io_method,NaN,NaN,NaN,NaN,worker,worker,worker,worker,NaN,NaN,NaN,NaN,worker,worker,worker,worker
arg_shared_buffers,NaN,NaN,NaN,NaN,256GB,256GB,256GB,256GB,NaN,NaN,NaN,NaN,256GB,256GB,256GB,256GB
arg_effective_cache_size,NaN,NaN,NaN,NaN,256GB,256GB,256GB,256GB,NaN,NaN,NaN,NaN,256GB,256GB,256GB,256GB
arg_work_mem,NaN,NaN,NaN,NaN,32GB,32GB,32GB,32GB,NaN,NaN,NaN,NaN,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,NaN,NaN,NaN,NaN,4GB,4GB,4GB,4GB,NaN,NaN,NaN,NaN,4GB,4GB,4GB,4GB
arg_temp_buffers,NaN,NaN,NaN,NaN,4GB,4GB,4GB,4GB,NaN,NaN,NaN,NaN,4GB,4GB,4GB,4GB
arg_wal_buffers,NaN,NaN,NaN,NaN,1GB,1GB,1GB,1GB,NaN,NaN,NaN,NaN,1GB,1GB,1GB,1GB
arg_autovacuum,NaN,NaN,NaN,NaN,off,off,off,off,NaN,NaN,NaN,NaN,off,off,off,off
arg_wal_level,NaN,NaN,NaN,NaN,minimal,minimal,minimal,minimal,NaN,NaN,NaN,NaN,minimal,minimal,minimal,minimal
arg_max_wal_senders,NaN,NaN,NaN,NaN,0,0,0,0,NaN,NaN,NaN,NaN,0,0,0,0
arg_fsync,NaN,NaN,NaN,NaN,on,on,on,on,NaN,NaN,NaN,NaN,on,on,on,on
arg_wal_compression,NaN,NaN,NaN,NaN,on,on,on,on,NaN,NaN,NaN,NaN,on,on,on,on
arg_synchronous_commit,NaN,NaN,NaN,NaN,on,on,on,on,NaN,NaN,NaN,NaN,on,on,on,on
arg_max_wal_size,NaN,NaN,NaN,NaN,32GB,32GB,32GB,32GB,NaN,NaN,NaN,NaN,32GB,32GB,32GB,32GB
arg_min_wal_size,NaN,NaN,NaN,NaN,32GB,32GB,32GB,32GB,NaN,NaN,NaN,NaN,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,NaN,NaN,NaN,NaN,12h,12h,12h,12h,NaN,NaN,NaN,NaN,12h,12h,12h,12h
arg_checkpoint_completion_target,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0

In [22]:
from scipy.stats import gmean

#df = collect.get_evaluator().evaluation.get_aggregated_query_statistics(type='latency', name='execution', query_aggregate='Mean')
#if not df is None:
#    df = df.sort_index().T.round(2)
#    df.index = df.index.map(map_index_to_queryname)
#    num_of_queries = len(df.index)

num_of_queries=22
df=df_performance.copy()
column = "connection"
df_aggregated = pd.DataFrame()
for key, grp in df.groupby(column):
    #print(key, len(grp.index))
    #print(grp.columns)
    aggregate = {
        'total_timer_execution':gmean,
        'Power@Size [~Q/h]':gmean,
        'code':'max',
        'orig_name':'max',
        'SF':'max',
        'experiment_run':'max',
        'time [s]':'max',
        'count':'count',
        'Throughput@Size':'max',
        'num_of_queries':'mean',
    }
    dict_grp = dict()
    dict_grp['connection'] = key
    #dict_grp['configuration'] = grp['configuration'].iloc[0]
    dict_grp['experiment_run'] = grp['experiment_run'].iloc[0]
    #dict_grp['client'] = grp['client'][0]
    #dict_grp['pod'] = grp['pod'][0]
    #print(dict_grp)
    dict_grp = {**dict_grp, **grp.agg(aggregate)}
    df_grp = pd.DataFrame(dict_grp, index=[key])#columns=list(dict_grp.keys()))
    #df_grp = df_grp.T
    #df_grp.set_index('connection', inplace=True)
    #print(df_grp)
    df_aggregated = pd.concat([df_aggregated, df_grp])

df_aggregated['Throughput@Size'] = (df_aggregated['num_of_queries']*3600.*df_aggregated['count']/df_aggregated['time [s]']*df_aggregated['SF']).round(2)
df_aggregated

,connection,experiment_run,total_timer_execution,Power@Size [~Q/h],code,orig_name,SF,time [s],count,Throughput@Size,num_of_queries
PostgreSQL-BHT-8-1-1,PostgreSQL-BHT-8-1-1,1,2.136311,7149.475431,1776420958,PostgreSQL-BHT-8-1-1,6.0,113,2,8410.62,22.0
PostgreSQL-BHT-8-1-2,PostgreSQL-BHT-8-1-2,1,2.143917,7124.114277,1776420958,PostgreSQL-BHT-8-1-2,6.0,110,4,17280.00,22.0
PostgreSQL-BHT-8-2-1,PostgreSQL-BHT-8-2-1,2,3.155383,4840.461013,1776420958,PostgreSQL-BHT-8-2-1,6.0,210,2,4525.71,22.0
PostgreSQL-BHT-8-2-2,PostgreSQL-BHT-8-2-2,2,2.165571,7052.878696,1776420958,PostgreSQL-BHT-8-2-2,6.0,119,4,15973.11,22.0

In [16]:
cols = ['code', 'connection']
print(df_performance.index.duplicated())
df = df_performance.rename_axis('connection_pod').reset_index()
df = df.set_index(cols)
df

[False False False False False False False False False False False False]

                                                    connection_pod  \
code       connection
1776418956 PostgreSQL-BHT-8-1-1  1776418956-PostgreSQL-BHT-8-1-1-1
           PostgreSQL-BHT-8-1-2  1776418956-PostgreSQL-BHT-8-1-2-1
           PostgreSQL-BHT-8-1-2  1776418956-PostgreSQL-BHT-8-1-2-2
           PostgreSQL-BHT-8-2-1  1776418956-PostgreSQL-BHT-8-2-1-1
           PostgreSQL-BHT-8-2-2  1776418956-PostgreSQL-BHT-8-2-2-1
           PostgreSQL-BHT-8-2-2  1776418956-PostgreSQL-BHT-8-2-2-2
1776420958 PostgreSQL-BHT-8-1-1  1776420958-PostgreSQL-BHT-8-1-1-1
           PostgreSQL-BHT-8-1-2  1776420958-PostgreSQL-BHT-8-1-2-1
           PostgreSQL-BHT-8-1-2  1776420958-PostgreSQL-BHT-8-1-2-2
           PostgreSQL-BHT-8-2-1  1776420958-PostgreSQL-BHT-8-2-1-1
           PostgreSQL-BHT-8-2-2  1776420958-PostgreSQL-BHT-8-2-2-1
           PostgreSQL-BHT-8-2-2  1776420958-PostgreSQL-BHT-8-2-2-2

                                 total_timer_execution  Power@Size [~Q/h]  \
code       connection
1776418956 PostgreSQL-BHT-8-1-1               1.566479        6894.444445
           PostgreSQL-BHT-8-1-2               1.597086        6762.315040
           PostgreSQL-BHT-8-1-2               1.550340        6966.213449
           PostgreSQL-BHT-8-2-1               2.345645        4604.277867
           PostgreSQL-BHT-8-2-2               1.588409        6799.256171
           PostgreSQL-BHT-8-2-2               1.588487        6798.922785
1776420958 PostgreSQL-BHT-8-1-1               2.913431        7413.940216
           PostgreSQL-BHT-8-1-2               2.934896        7359.714573
           PostgreSQL-BHT-8-1-2               2.907257        7429.684303
           PostgreSQL-BHT-8-2-1               4.244649        5088.759517
           PostgreSQL-BHT-8-2-2               2.986872        7231.644570
           PostgreSQL-BHT-8-2-2               2.918278        7401.624895

                                 Geo Times [s]             orig_name   SF  \
code       connection
1776418956 PostgreSQL-BHT-8-1-1       1.566479  PostgreSQL-BHT-8-1-1  3.0
           PostgreSQL-BHT-8-1-2       1.597086  PostgreSQL-BHT-8-1-2  3.0
           PostgreSQL-BHT-8-1-2       1.550340  PostgreSQL-BHT-8-1-2  3.0
           PostgreSQL-BHT-8-2-1       2.345645  PostgreSQL-BHT-8-2-1  3.0
           PostgreSQL-BHT-8-2-2       1.588409  PostgreSQL-BHT-8-2-2  3.0
           PostgreSQL-BHT-8-2-2       1.588487  PostgreSQL-BHT-8-2-2  3.0
1776420958 PostgreSQL-BHT-8-1-1       2.913431  PostgreSQL-BHT-8-1-1  6.0
           PostgreSQL-BHT-8-1-2       2.934896  PostgreSQL-BHT-8-1-2  6.0
           PostgreSQL-BHT-8-1-2       2.907257  PostgreSQL-BHT-8-1-2  6.0
           PostgreSQL-BHT-8-2-1       4.244649  PostgreSQL-BHT-8-2-1  6.0
           PostgreSQL-BHT-8-2-2       2.986872  PostgreSQL-BHT-8-2-2  6.0
           PostgreSQL-BHT-8-2-2       2.918278  PostgreSQL-BHT-8-2-2  6.0

                                 experiment_run  client  time [s]  count  \
code       connection
1776418956 PostgreSQL-BHT-8-1-1               1       1        58      1
           PostgreSQL-BHT-8-1-2               1       2        60      1
           PostgreSQL-BHT-8-1-2               1       2        57      1
           PostgreSQL-BHT-8-2-1               2       1       120      1
           PostgreSQL-BHT-8-2-2               2       2        59      1
           PostgreSQL-BHT-8-2-2               2       2        60      1
1776420958 PostgreSQL-BHT-8-1-1               1       1       113      1
           PostgreSQL-BHT-8-1-2               1       2       110      1
           PostgreSQL-BHT-8-1-2               1       2       110      1
           PostgreSQL-BHT-8-2-1               2       1       210      1
           PostgreSQL-BHT-8-2-2               2       2       119      1
           PostgreSQL-BHT-8-2-2               2       2       116      1

                                 num_of_queries  Throughput@Size
code       connection
1776418956 PostgreSQL-BHT-8-1-1              22          4096.55
           PostgreSQL-BHT-8-1-2              22          3960.00
           PostgreSQL-BHT-8-1-2              22          4168.42
           PostgreSQL-BHT-8-2-1              22          1980.00
           PostgreSQL-BHT-8-2-2              22          4027.12
           PostgreSQL-BHT-8-2-2              22          3960.00
1776420958 PostgreSQL-BHT-8-1-1              22          4205.31
           PostgreSQL-BHT-8-1-2              22          4320.00
           PostgreSQL-BHT-8-1-2              22          4320.00
           PostgreSQL-BHT-8-2-1              22          2262.86
           PostgreSQL-BHT-8-2-2              22          3993.28
           PostgreSQL-BHT-8-2-2              22          4096.55

In [17]:
df_connections = collect.get_connections()
df_connections = df_connections.set_index(cols)
df_connections

                                  experiment_run client    dockerimage  \
code       connection
1776418956 PostgreSQL-BHT-8-1-1-1              1      1  postgres:18.3
           PostgreSQL-BHT-8-1-2-2              1      2  postgres:18.3
           PostgreSQL-BHT-8-2-1-1              2      1  postgres:18.3
           PostgreSQL-BHT-8-2-2-2              2      2  postgres:18.3
1776420958 PostgreSQL-BHT-8-1-1-1              1      1  postgres:18.3
           PostgreSQL-BHT-8-1-2-2              1      2  postgres:18.3
           PostgreSQL-BHT-8-2-1-1              2      1  postgres:18.3
           PostgreSQL-BHT-8-2-2-2              2      2  postgres:18.3

                                  time_load time_ingest time_check terminals  \
code       connection
1776418956 PostgreSQL-BHT-8-1-1-1     455.0       141.0      291.0         0
           PostgreSQL-BHT-8-1-2-2     455.0       141.0      291.0         0
           PostgreSQL-BHT-8-2-1-1     455.0       141.0      291.0         0
           PostgreSQL-BHT-8-2-2-2     455.0       141.0      291.0         0
1776420958 PostgreSQL-BHT-8-1-1-1    1256.0       350.0      843.0         0
           PostgreSQL-BHT-8-1-2-2    1256.0       350.0      843.0         0
           PostgreSQL-BHT-8-2-1-1    1256.0       350.0      843.0         0
           PostgreSQL-BHT-8-2-2-2    1256.0       350.0      843.0         0

                                  pods tenant num_worker  ... arg_autovacuum  \
code       connection                                     ...
1776418956 PostgreSQL-BHT-8-1-1-1    1                 0  ...            off
           PostgreSQL-BHT-8-1-2-2    2                 0  ...            off
           PostgreSQL-BHT-8-2-1-1    1                 0  ...            off
           PostgreSQL-BHT-8-2-2-2    2                 0  ...            off
1776420958 PostgreSQL-BHT-8-1-1-1    1                 0  ...            off
           PostgreSQL-BHT-8-1-2-2    2                 0  ...            off
           PostgreSQL-BHT-8-2-1-1    1                 0  ...            off
           PostgreSQL-BHT-8-2-2-2    2                 0  ...            off

                                  arg_wal_level arg_max_wal_senders arg_fsync  \
code       connection
1776418956 PostgreSQL-BHT-8-1-1-1       minimal                   0        on
           PostgreSQL-BHT-8-1-2-2       minimal                   0        on
           PostgreSQL-BHT-8-2-1-1       minimal                   0        on
           PostgreSQL-BHT-8-2-2-2       minimal                   0        on
1776420958 PostgreSQL-BHT-8-1-1-1       minimal                   0        on
           PostgreSQL-BHT-8-1-2-2       minimal                   0        on
           PostgreSQL-BHT-8-2-1-1       minimal                   0        on
           PostgreSQL-BHT-8-2-2-2       minimal                   0        on

                                  arg_wal_compression arg_synchronous_commit  \
code       connection
1776418956 PostgreSQL-BHT-8-1-1-1                  on                     on
           PostgreSQL-BHT-8-1-2-2                  on                     on
           PostgreSQL-BHT-8-2-1-1                  on                     on
           PostgreSQL-BHT-8-2-2-2                  on                     on
1776420958 PostgreSQL-BHT-8-1-1-1                  on                     on
           PostgreSQL-BHT-8-1-2-2                  on                     on
           PostgreSQL-BHT-8-2-1-1                  on                     on
           PostgreSQL-BHT-8-2-2-2                  on                     on

                                  arg_max_wal_size arg_min_wal_size  \
code       connection
1776418956 PostgreSQL-BHT-8-1-1-1             32GB             32GB
           PostgreSQL-BHT-8-1-2-2             32GB             32GB
           PostgreSQL-BHT-8-2-1-1             32GB             32GB
           PostgreSQL-BHT-8-2-2-2             32GB             32GB
1776420958 PostgreSQL-BHT-8-1-1-1             32GB             32GB
           PostgreSQL-BHT-8-1-2-2             32GB             32GB
           PostgreSQL-BHT-8-2-1-1             32GB             32GB
           PostgreSQL-BHT-8-2-2-2             32GB             32GB

                                  arg_checkpoint_timeout  \
code       connection
1776418956 PostgreSQL-BHT-8-1-1-1                    12h
           PostgreSQL-BHT-8-1-2-2                    12h
           PostgreSQL-BHT-8-2-1-1                    12h
           PostgreSQL-BHT-8-2-2-2                    12h
1776420958 PostgreSQL-BHT-8-1-1-1                    12h
           PostgreSQL-BHT-8-1-2-2                    12h
           PostgreSQL-BHT-8-2-1-1                    12h
           PostgreSQL-BHT-8-2-2-2                    12h

                                  arg_checkpoint_completion_target
code       connection
1776418956 PostgreSQL-BHT-8-1-1-1                              1.0
           PostgreSQL-BHT-8-1-2-2                              1.0
           PostgreSQL-BHT-8-2-1-1                              1.0
           PostgreSQL-BHT-8-2-2-2                              1.0
1776420958 PostgreSQL-BHT-8-1-1-1                              1.0
           PostgreSQL-BHT-8-1-2-2                              1.0
           PostgreSQL-BHT-8-2-1-1                              1.0
           PostgreSQL-BHT-8-2-2-2                              1.0

[8 rows x 75 columns]

In [18]:
cols_to_use = [c for c in df_connections.columns if c not in df.columns]
cols_to_use

['dockerimage',
 'time_load',
 'time_ingest',
 'time_check',
 'terminals',
 'pods',
 'tenant',
 'num_worker',
 'host_RAM',
 'host_CPU',
 'host_GPU',
 'host_Cores',
 'host_host',
 'host_node',
 'host_disk',
 'host_datadisk',
 'host_volume_size',
 'host_volume_used',
 'host_cuda',
 'host_hugepages_total',
 'host_hugepages_free',
 'host_cpu_list',
 'host_requests_cpu',
 'host_requests_memory',
 'host_limits_cpu',
 'host_limits_memory',
 'loading_parameters_SF',
 'loading_parameters_PODS_TOTAL',
 'loading_parameters_PODS_PARALLEL',
 'loading_parameters_STORE_RAW_DATA',
 'loading_parameters_STORE_RAW_DATA_RECREATE',
 'loading_parameters_BEXHOMA_SYNCH_LOAD',
 'loading_parameters_BEXHOMA_SYNCH_GENERATE',
 'loading_parameters_TRANSFORM_RAW_DATA',
 'loading_parameters_TPCH_TABLE',
 'loading_parameters_BEXHOMA_TENANT_BY',
 'loading_parameters_BEXHOMA_TENANT_NUM',
 'benchmarking_parameters_SF',
 'benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER',
 'benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES',
 'benchmarking_parameters_DBMSBENCHMARKER_DEV',
 'benchmarking_parameters_TENANT_BY',
 'benchmarking_parameters_TENANT_NUM',
 'benchmarking_parameters_BEXHOMA_TENANT_BY',
 'benchmarking_parameters_BEXHOMA_TENANT_NUM',
 'sut_parameters_BEXHOMA_WORKER_LIST',
 'sut_parameters_BEXHOMA_WORKER_LIST_SPACE',
 'sut_parameters_BEXHOMA_WORKER_NAME',
 'sut_parameters_BEXHOMA_WORKER_SERVICE',
 'sut_parameters_BEXHOMA_SUT_NAME',
 'arg_max_connections',
 'arg_max_worker_processes',
 'arg_max_parallel_workers',
 'arg_max_parallel_workers_per_gather',
 'arg_max_parallel_maintenance_workers',
 'arg_effective_io_concurrency',
 'arg_io_method',
 'arg_shared_buffers',
 'arg_effective_cache_size',
 'arg_work_mem',
 'arg_maintenance_work_mem',
 'arg_temp_buffers',
 'arg_wal_buffers',
 'arg_autovacuum',
 'arg_wal_level',
 'arg_max_wal_senders',
 'arg_fsync',
 'arg_wal_compression',
 'arg_synchronous_commit',
 'arg_max_wal_size',
 'arg_min_wal_size',
 'arg_checkpoint_timeout',
 'arg_checkpoint_completion_target']

In [19]:
result = pd.concat([df, df_connections[cols_to_use]], axis=1)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [ ]:
df = collect.add_metadata(df_performance)
df.T

In [20]:
df_performance = collect.get_performance_aggregated_per_connection()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)

NameError: name 'collect' is not defined

# Boxplot of All Metrics for a Single Experiment

In [ ]:
if not b_skip_plots:
    results = []
    code = codes[0]
    for idx, row in collect.df_metrics.iterrows():
        if row["active"] == False:
            continue
        metric_name = idx
        method = 'diff' if row["metric"] == 'counter' else 'mean'
        col_name = row["title"]
        df_monitoring = collect.get_monitoring_timeseries_single(code, metric=metric_name)
        #print(df_monitoring)
        ax = df_monitoring.boxplot()
        ax.set_title(col_name)
        plt.show()

# Boxplot of A Single Metric for a Single Experiment

In [ ]:
metric = 'total_cpu_memory'
code = codes[0]
collect.get_monitoring_timeseries_single(code, metric=metric)

In [ ]:
metric = 'total_cpu_memory'
code = codes[0]
collect.get_monitoring_timeseries_all( metric=metric)

In [ ]:
if not b_skip_plots:
    metric = 'pg_stat_activity_max_tx_duration_active'
    #metric = 'pg_stat_database_blks_reads'
    #metric = 'pg_stat_activity_count_idle_transaction'
    metric = 'total_cpu_memory'
    code = codes[0]
    df_monitoring = collect.get_monitoring_timeseries_single(code, metric=metric)
    ax = df_monitoring.boxplot()
    ax.set_title(collect.df_metrics.loc[metric]['title'])#metric)
    plt.show()
    df_monitoring

# Lineplot of a Single Metric for a Single Experiment

In [ ]:
if not b_skip_plots:
    code = codes[0]
    metric = 'pg_stat_database_blks_hit'
    metric = 'pg_stat_activity_count_idle_transaction'
    metric = 'total_cpu_memory'
    metric = 'total_cpu_util'
    metric = 'total_cpu_util_s'
    metric = 'core_variance'
    df_monitoring = collect.get_monitoring_timeseries_single(code, metric=metric)
    ax = df_monitoring.plot()
    ax.set_title(metric)
    plt.show()
    #df_monitoring

# Boxplot of a Single Metric for all Experiments

In [ ]:
metric = 'pg_stat_database_blks_hit'
metric = 'pg_stat_activity_count_idle_transaction'
metric = 'total_cpu_memory'
metric = 'total_cpu_util'
metric = 'total_cpu_util_s'
metric = 'core_variance'
metric = 'pg_locks_count_exclusivelock'
metric = 'pg_stat_activity_count_active'
df_performance = collect.get_monitoring_timeseries_all(metric)
#df_performance
df_performance_first = df_performance[df_performance['client']=="1"]
#df_performance_first
df_performance_second = df_performance[df_performance['client']=="2"]
#df_performance_second
#df_performance_first['value'].describe()
#df_performance

## First Execution Run

In [ ]:
plot_boxplots(df_performance_first, y='value', title=collect.df_metrics.loc[metric]['title'], b_plot_save=b_plot_save, filename_prefix=filename_prefix)

## Second Execution Run

In [ ]:
plot_boxplots(df_performance_second, y='value', title=collect.df_metrics.loc[metric]['title'], b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Lineplot of a Single Metric for All Experiments

## First Execution Run

In [ ]:
#df = df_performance_first[df_performance_first['type'] == 'None']
#df = df[df['experiment_run'] == '1']
plot_lines(df_performance_first, y='value', title=collect.df_metrics.loc[metric]['title'], b_plot_save=b_plot_save, filename_prefix=filename_prefix)
#df

# Aggregated Metrics for all Connections

In [ ]:
df_performance = collect.get_monitoring_single_all("stream")
df_performance.T

# Monitoring Aggregated Values

In [ ]:
df_performance = collect.get_monitoring_all("stream")

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T#[['Max CPU', 'client', 'type', 'num_tenants']]

## First Execution Run

In [ ]:
plot_bars(df_performance_first, y='Buffer Cache Hit Ratio', title='Cache Hit Ratio [%]', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

## Second Execution Run

In [ ]:
plot_bars(df_performance_second, y='Buffer Cache Hit Ratio', title='Cache Hit Ratio [%]', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Performance Results per Tenant

In [ ]:
df_performance = collect.get_performance_all_single()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

## First Execution Run

In [ ]:
plot_boxplots(df_performance_first, y='Goodput (requests/second)', title='Distribution of Goodput First Run [req/s]', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_boxplots(df_performance_second, y='Goodput (requests/second)', title='Distribution of Goodput Second Run [req/s]', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_boxplots(df_performance_first, y='Latency Distribution.99th Percentile Latency (microseconds)', title=r'Distribution of 99th Latency 1st Run [$\mu s$]', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_boxplots(df_performance_second, y='Latency Distribution.99th Percentile Latency (microseconds)', title=r'Distribution of 99th Latency 2nd Run [$\mu s$]', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Performance Results per Total

In [ ]:
collect.get_performance_single().T

In [ ]:
collect.get_performance_all_single().T

In [ ]:
df_performance = collect.get_performance_all()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)

In [ ]:
df_performance.T

In [ ]:
import seaborn as sns

sns.barplot(data=df_performance, x='experiment_run', y='Goodput (requests/second)', hue='client')
plt.show()

In [ ]:
plot_bars(df_performance, y='Goodput (requests/second)', title='Goodput [req/s]', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='Goodput (requests/second)', title='Goodput First Run [req/s]', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_second, y='Goodput (requests/second)', title='Goodput Second Run [req/s]', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance, y='Latency Distribution.Average Latency (microseconds)', title=r'Average Latency [$\mu s$]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='Latency Distribution.Average Latency (microseconds)', title=r'Average Latency First Run [$\mu s$]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_second, y='Latency Distribution.Average Latency (microseconds)', title=r'Average Latency Second Run [$\mu s$]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance, y='num_errors', title='Deadlocks', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
df_performance = collect.get_loading_time_max_all()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance

In [ ]:
df_performance_first = df_performance[df_performance['client'] == 1]
# Divide datadisk by the count of rows with the same type and num_tenants
df = df_performance_first.copy()
# Create a mask for rows where type is not "container"
mask = df['type'] != 'container'

# Only apply the group count to the relevant rows
group_counts = df[mask].groupby(['type', 'num_tenants'])['datadisk'].transform('count')

# Initialize the column with NaN (or 0, if preferred)
df['datadisk_normalized'] = df['datadisk'] / 1024

# Apply the normalized value only where the mask is True
df.loc[mask, 'datadisk_normalized'] = df.loc[mask, 'datadisk'] / group_counts / 1024

plot_bars(df, y='datadisk_normalized', title='Database Size [GB]', estimator='sum', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='datadisk', title='Database Size [MB]', estimator='sum', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='time_ingest', title='Time for Ingestion [s]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='time_check', title='Time for Vacuum [s]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Hardware Monitoring for Benchmarking Phase

In [ ]:
df_performance = collect.get_monitoring_all(type="stream")

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

In [ ]:
plot_bars(df_performance, y='CPU Utilization Time [s]', title='CPU [CPUs]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_first, y='CPU Utilization Time [s]', title='CPU 1st Run [CPUs]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance_second, y='CPU Utilization Time [s]', title='CPU 2nd Run [CPUs]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance, y='CPU Utilization', title='CPU Utilization [%]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

## Custom Aggregation

In [ ]:
metric = 'total_cpu_util'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["client", "type", "num_tenants"])["value"]
      .max()
      .reset_index()
)
plot_bars(df_agg, y='value', title='Max CPU Utilization [%]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)
#df_agg

In [ ]:
plot_bars(df_performance, y='CPU Throttle', title='CPU Throttle [%]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

## Custom Aggregation and Scale

In [ ]:
metric = 'total_cpu_memory'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["client", "type", "num_tenants"])["value"]
      .max()
      .reset_index()
)
df_agg['value'] = df_agg['value'] / 1024.
plot_bars(df_agg, y='value', title='Max Memory Usage [GiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

plot_bars(df_performance, y='Memory Usage [MiB]', title='Average Memory Usage [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
metric = 'total_cpu_memory_cached'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["client", "type", "num_tenants"])["value"]
      .max()
      .reset_index()
)
df_agg['value'] = df_agg['value'] / 1024.
plot_bars(df_agg, y='value', title='Max Memory Usage Cached [GiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

plot_bars(df_performance, y='Memory Usage Cached [MiB]', title='Average Memory Usage Cached [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Hardware Monitoring for Loading Phase

In [ ]:
df_performance = collect.get_monitoring_all("loading")

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance_first

In [ ]:
plot_bars(df_performance, y='CPU Utilization Time [s]', title='CPU [CPUs]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance, y='Memory Usage [MiB]', title='Memory Usage [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(df_performance, y='Memory Usage Cached [MiB]', title='Memory Usage Cached [MiB]', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

# Efficiency

In [ ]:
client = 1

df_performance_monitoring = collect.get_monitoring_all(type="stream")
df_performance_monitoring = df_performance_monitoring[df_performance_monitoring['client'] == client]
df_performance = collect.get_performance_all()
df_performance = df_performance[df_performance['client'] == client]
merged_df = pd.merge(df_performance, df_performance_monitoring, on=['type', 'num_tenants', 'code', 'client'], how='inner')
#merged_df['I_Lat'] = 1./merged_df['E_Lat']
merged_df['E_Tpx'] = merged_df['Goodput (requests/second)'] / merged_df['CPU Utilization Time [s]'] * 600.
merged_df['E_Lat'] = 1./np.sqrt(merged_df['Latency Distribution.Average Latency (microseconds)']*merged_df['CPU Utilization Time [s]']/1E6)
merged_df['E_RAM'] = (merged_df['Goodput (requests/second)']) / merged_df['Memory Usage [MiB]']
merged_df

In [ ]:
plot_bars(merged_df, y='E_Lat', title='1st run - $E_{Lat}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
#plot_bars(merged_df, y='I_Lat', title='1st run - $I_{Lat}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(merged_df, y='E_Tpx', title='1st run - $E_{Tpx}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(merged_df, y='E_RAM', title='1st run - $E_{RAM}$', estimator='min', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
client = 2

df_performance_monitoring = collect.get_monitoring_all(type="stream")
df_performance_monitoring = df_performance_monitoring[df_performance_monitoring['client'] == client]
df_performance = collect.get_performance_all()
df_performance = df_performance[df_performance['client'] == client]
merged_df = pd.merge(df_performance, df_performance_monitoring, on=['type', 'num_tenants', 'code', 'client'], how='inner')
#merged_df['CPUs/Request'] = merged_df['CPU [CPUs]'] / merged_df['Goodput (requests/second)'] / 600.
merged_df['E_Tpx'] = merged_df['Goodput (requests/second)'] / merged_df['CPU Utilization Time [s]'] * 600.
merged_df['E_Lat'] = 1./np.sqrt(merged_df['Latency Distribution.Average Latency (microseconds)']*merged_df['CPU Utilization Time [s]']/1E6)
merged_df['E_RAM'] = (merged_df['Goodput (requests/second)']) / merged_df['Memory Usage [MiB]']

merged_df

In [ ]:
plot_bars(merged_df, y='E_Lat', title='2nd run - $E_{Lat}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(merged_df, y='E_Tpx', title='2nd run - $E_{Tpx}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
plot_bars(merged_df, y='E_RAM', title='2nd run - $E_{RAM}$', estimator='max', b_plot_save=b_plot_save, filename_prefix=filename_prefix)

In [ ]:
#zip_all_results()