# TPC-C Collector Demo

In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option('display.max_colwidth', None)
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.float_format = '{:.2f}'.format

from bexhoma import collectors

%matplotlib inline

## Functions for Nice Plots

In [2]:
from notebookutils import *

# Collect Results

In [3]:
#path = r"D:\data\benchmarks"
path = r"/data/benchmarks"
filename_prefix = "demo_"
b_plot_save = False
b_skip_plots = True

In [4]:
codes = [
    "1777039267",
    "1777041908"
]

codes

['1777039267', '1777041908']

In [5]:
collect = collectors.tpcc(path, codes)

# Get all Metrics Metadata

## Metrics Names and Types

Metrics that are derived from monitoring

In [6]:
collect.get_metrics_metadata()

,title,active,type,metric
total_cpu_memory,Memory Usage [MiB],True,cluster,gauge
total_cpu_memory_cached,Memory Usage Cached [MiB],True,cluster,gauge
total_cpu_util,CPU Utilization,True,cluster,gauge
total_cpu_throttled,CPU Throttle,True,cluster,gauge
total_cpu_throttled_s,CPU Throttled Time [s],True,cluster,counter
total_cpu_util_others,CPU Utilization Others,False,cluster,gauge
total_cpu_util_s,CPU Utilization Time [s],True,cluster,counter
total_cpu_util_user_s,CPU User Time [s],True,cluster,counter
total_cpu_util_sys_s,CPU System Time [s],True,cluster,counter
total_cpu_util_others_s,CPU Utilization Time Others [s],False,cluster,counter
total_network_rx,Network Rx Total [MiB],True,cluster,counter
total_network_tx,Network Tx Total [MiB],True,cluster,counter
total_fs_read,Filesystem Read Total [MiB],True,cluster,counter
total_fs_write,Filesystem Write Total [MiB],True,cluster,counter
total_gpu_util,GPU Utilization [%],False,cluster,gauge
total_gpu_power,GPU Power Usage [W],False,cluster,gauge
total_gpu_memory,GPU Memory Usage [MiB],False,cluster,gauge
core_variance,Core Utilization Variance [%],True,cluster,ratio
max_core_util,Max Core Utilization [%],True,cluster,ratio
io_wait_pct,I/O Wait [%],True,cluster,ratio
io_wait_total,Total I/O Wait Time [s],True,cluster,counter
pg_stat_activity_count_idle,Number of Idle Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction,Number of Idle-in-transaction Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction_aborted,Number of Idle-in-transaction Aborted Sessions,True,application,gauge
pg_stat_activity_count_active,Number of Active Sessions,True,application,counter
pg_stat_activity_count_active_app,Number of Active Application Sessions,True,application,counter
pg_stat_activity_max_tx_duration_active,Longest Active Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle,Longest Idle Session (no transaction),True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx,Longest Idle-in-Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx_aborted,Longest Idle-in-Transaction (Aborted),True,application,ratio
pg_stat_activity_count_io,Active Backends Waiting on I/O,True,application,gauge
pg_stat_activity_count_wal,Active Backends Waiting on WAL,True,application,gauge
pg_stat_activity_count_lock,Active Backends Waiting on Locks,True,application,gauge
pg_stat_activity_max_tx_duration_io,Max Transaction Duration (I/O Wait),True,application,ratio
pg_stat_activity_max_tx_duration_wal,Max Transaction Duration (WAL Wait),True,application,ratio
pg_stat_activity_max_tx_duration_lock,Max Transaction Duration (Lock Wait),True,application,ratio
pg_stat_database_blks_read,Disk Blocks Read Count,True,application,counter
pg_stat_database_blks_hit,Buffer Cache Hit Count,True,application,counter
cache_hit_ratio,Buffer Cache Hit Ratio,True,application,ratio
pg_stat_user_tables_idx_scan,Index Scan Count,True,application,counter
pg_stat_user_tables_idx_tup_fetch,Index Tuple Fetch Count,True,application,counter
pg_statio_user_tables_idx_cache_hit_ratio,Index Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_heap_blocks_hit,Table Buffer Hit Count,True,application,counter
pg_statio_user_tables_heap_blocks_read,Table Blocks Read Count,True,application,counter
pg_statio_user_tables_heap_cache_hit_ratio,Table Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_total_cache_hit_ratio,Total Cache Hit Ratio,True,application,ratio
pg_stat_bgwriter_efficiency_ratio,BGWriter Efficiency Ratio (Cleaned / Allocated),True,application,ratio
pg_stat_bgwriter_maxwritten_clean_total,BGWriter Stopped Due to Max Pages,True,application,counter
pg_stat_bgwriter_checkpoint_sync_time_total,Checkpoint Sync Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_total,Checkpoint Write Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_per_sync_time,Time spent writing vs syncing during checkpoints [ratio],False,application,ratio
pg_locks_count,Total Locks Current,True,application,gauge
pg_locks_count_accessexclusivelock,AccessExclusiveLocks Current,True,application,gauge
pg_locks_count_accesssharelock,AccessShareLocks Current,True,application,gauge
pg_locks_count_exclusivelock,ExclusiveLocks Current,True,application,gauge
pg_locks_count_rowexclusivelock,RowExclusiveLocks Current,True,application,gauge
pg_locks_count_rowsharelock,RowShareLocks Current,True,application,gauge
pg_locks_count_sharelock,ShareLocks Current,True,application,gauge
pg_locks_count_sharerowexclusivelock,ShareRowExclusiveLocks Current,True,application,gauge
pg_locks_count_shareupdateexclusivelock,ShareUpdateExclusiveLocks Current,True,application,gauge
pg_locks_count_sireadlock,SIReadLocks Current,True,application,gauge
pg_stat_user_tables_autoanalyze_count,Autoanalyze Run Count,True,application,counter
pg_stat_user_tables_autovacuum_count,Autovacuum Run Count,True,application,counter
pg_stat_bgwriter_checkpoints_timed_per_req,Frequency of checkpoints (timed vs requested) [ratio],False,application,gauge
pg_stat_wal_volume_bytes_sec,Volume of WAL generated [bytes/sec],False,application,counter
pg_stat_bgwriter_buffers_backend_fsync,Backends forced to flush WAL (I/O contention) [fsync/sec],False,application,counter
pg_stat_activity_wait_event_count,Active sessions waiting on any event [count],False,application,gauge
pg_stat_user_tables_dead_tuples_per_vacuum,Dead tuples per vacuum operation [tuples/vacuum],True,application,ratio
pg_wal_segments,Number of WAL Segments,True,application,gauge
pg_wal_size_bytes,Total WAL Size [GiB],True,application,gauge
pg_wal_segments_rate,WAL Segments Growth Rate [segments/s],True,application,gauge
pg_wal_size_rate,WAL Growth Rate [MiB/s],True,application,gauge
pg_wal_avg_segment_size,Average WAL Segment Size [MiB],True,application,gauge
pg_wal_size_per_checkpoint,WAL Size per Checkpoint [bytes/checkpoint],False,application,gauge

## Names of Monitored Components

Names of components and their phases

In [7]:
collect.get_monitored_components()

                                        description
loading               Loading phase: SUT deployment
loader              Loading phase: component loader
stream              Execution phase: SUT deployment
benchmarker  Execution phase: component benchmarker

# Get Connection Infos

List of states of SUTs, containing loading infos.

In [8]:
df=collect.get_connections()

In [9]:
df.T

,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-2,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-2
code,1777039267,1777039267,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908,1777041908,1777041908
connection,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-2,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-2
configuration,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-2
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,180.00,180.00,180.00,180.00,180.00,180.00,183.00,183.00,183.00,222.00,222.00,222.00
time_ingest,84.00,84.00,84.00,84.00,84.00,84.00,84.00,84.00,84.00,94.00,94.00,94.00
time_check,96.00,96.00,96.00,96.00,96.00,96.00,98.00,98.00,98.00,128.00,128.00,128.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,2,1,2,2,1,2,2,1,2,2
tenant,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,None,None,None,None,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,3298,4482,4482,3299,4031,4031,3298,4846,4846,3282,4642,4642
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,154360,155544,155544,154360,155093,155093,154359,155908,155908,154343,155704,155704
host_datadisk,3298,4482,4482,3299,4031,4031,3298,4846,4846,3282,4642,4642
host_volume_size,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_HAMMERDB_NUM_VU,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_SF,16,16,16,16,16,16,16,16,16,16,16,16
loading_parameters_HAMMERDB_DURATION,5,5,5,5,5,5,5,5,5,5,5,5
loading_parameters_HAMMERDB_RAMPUP,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
loading_parameters_HAMMERDB_VUSERS,16,16,16,16,16,16,16,16,16,16,16,16
loading_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false,false,false,false,false,false,false,false,false
loading_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true,true,true,true,true,true,true,true,true
benchmarking_parameters_HAMMERDB_NUM_VU,1,2,2,1,2,2,1,2,2,1,2,2
benchmarking_parameters_SF,16,16,16,16,16,16,16,16,16,16,16,16
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
benchmarking_parameters_HAMMERDB_DURATION,5,5,5,5,5,5,5,5,5,5,5,5
benchmarking_parameters_HAMMERDB_RAMPUP,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
benchmarking_parameters_HAMMERDB_VUSERS,16,8,8,16,8,8,32,16,16,32,16,16
benchmarking_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false,false,false,false,false,false,false,false,false
benchmarking_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true,true,true,true,true,true,true,true,true
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [10]:
df = collect.get_loading_per_connection()
df.T

,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-2,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-2
code,1777039267,1777039267,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908,1777041908,1777041908
SF,16,16,16,16,16,16,16,16,16,16,16,16
configuration,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1
connection,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-2,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-2
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-2
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
time_load,180.00,180.00,180.00,180.00,180.00,180.00,183.00,183.00,183.00,222.00,222.00,222.00
time_ingest,84.00,84.00,84.00,84.00,84.00,84.00,84.00,84.00,84.00,94.00,94.00,94.00
time_check,96.00,96.00,96.00,96.00,96.00,96.00,98.00,98.00,98.00,128.00,128.00,128.00
pods,1,2,2,1,2,2,1,2,2,1,2,2
type_tenants,None,None,None,None,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
Throughput [SF/h],320.00,320.00,320.00,320.00,320.00,320.00,314.75,314.75,314.75,259.46,259.46,259.46

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [11]:
df[['phase', 'code', 'connection', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-2,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-2
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-2
code,1777039267,1777039267,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908,1777041908,1777041908
connection,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-2,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-2
configuration,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
type_tenants,None,None,None,None,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False

## Get Non-Constant Attributes

These attributes are (most probably) used to analyze performance.

In [12]:
collectors.get_non_constant(df).T

,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-2,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-2
code,1777039267,1777039267,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908,1777041908,1777041908
connection,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-2,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-2
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-2
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
time_load,180.00,180.00,180.00,180.00,180.00,180.00,183.00,183.00,183.00,222.00,222.00,222.00
time_ingest,84.00,84.00,84.00,84.00,84.00,84.00,84.00,84.00,84.00,94.00,94.00,94.00
time_check,96.00,96.00,96.00,96.00,96.00,96.00,98.00,98.00,98.00,128.00,128.00,128.00
pods,1,2,2,1,2,2,1,2,2,1,2,2
Throughput [SF/h],320.00,320.00,320.00,320.00,320.00,320.00,314.75,314.75,314.75,259.46,259.46,259.46

In [13]:
df = collect.get_loading_per_run()
df.T

,1777039267-PostgreSQL-BHT-16-1-1,1777039267-PostgreSQL-BHT-16-1-2,1777041908-PostgreSQL-BHT-16-1-1,1777041908-PostgreSQL-BHT-16-1-2
code,1777039267,1777039267,1777041908,1777041908
configuration,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1
experiment_run,1,2,1,2
SF,16,16,16,16
time_load,180.00,180.00,183.00,222.00
time_ingest,84.00,84.00,84.00,94.00
time_check,96.00,96.00,98.00,128.00
pods,2,2,2,2
type_tenants,None,None,None,None
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
Throughput [SF/h],320.00,320.00,314.75,259.46

# Monitoring Aggregated per Phase

In [14]:
df = collect.get_monitoring_aggregated_per_phase("stream")
df.T

,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2
Memory Usage [MiB],7777.19,8206.33,7558.01,8017.41,7976.66,8706.85,7910.65,8745.89
Memory Usage Cached [MiB],8552.64,9233.82,8309.08,8940.31,8832.62,9845.80,8728.59,9834.09
CPU Utilization,0.87,0.89,0.57,0.74,1.17,1.52,1.28,10.09
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],389.77,415.60,261.09,328.68,538.01,716.95,596.33,4769.16
CPU User Time [s],326.40,346.78,212.53,270.50,436.96,633.26,500.50,4640.84
CPU System Time [s],63.37,68.82,48.56,58.19,101.05,83.68,95.83,128.32
Network Rx Total [MiB],94.19,57.70,61.90,49.10,120.24,70.09,104.97,61.79
Network Tx Total [MiB],1064.29,60.79,936.34,58.98,1066.13,54.56,1079.82,47.12
Filesystem Read Total [MiB],0.04,0.04,0.02,0.02,0.14,0.03,0.02,0.01
Filesystem Write Total [MiB],2373.79,2426.45,1626.95,2072.73,3154.14,2007.15,2712.57,2236.78
Core Utilization Variance [%],0.23,0.21,0.17,0.19,0.20,0.18,0.17,1.72
Max Core Utilization [%],3.26,2.59,2.25,2.44,2.65,2.50,2.71,17.68
I/O Wait [%],35.31,39.40,40.30,43.38,32.68,31.07,31.67,11.52
Total I/O Wait Time [s],412.76,414.37,416.70,418.27,411.15,419.34,393.00,410.38
Number of Idle Sessions,1.33,2.64,1.12,2.28,1.56,2.52,1.60,2.34
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,17.00,16.00,16.00,16.00,32.00,32.00,32.00,32.00
Number of Active Application Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Active Transaction,0.03,0.03,0.08,0.06,0.32,0.41,0.22,0.40
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.99,0.99,1.00,0.97,0.99,0.99,0.96,0.98
Active Backends Waiting on WAL,10.58,11.76,6.61,10.16,13.44,8.03,11.94,8.96
Active Backends Waiting on Locks,3.01,1.87,7.39,4.51,14.69,19.46,16.23,9.59
Max Transaction Duration (I/O Wait),0.01,0.01,0.01,0.02,0.02,0.01,0.01,0.01
Max Transaction Duration (WAL Wait),0.03,0.03,0.07,0.05,0.17,0.15,0.13,0.09
Max Transaction Duration (Lock Wait),0.01,0.01,0.06,0.05,0.29,0.38,0.21,0.17
Disk Blocks Read Count,28399.00,8678.00,15958.00,16589.00,26420.00,12493.00,24432.00,14355.00
Buffer Cache Hit Count,49064412.00,48877544.00,38856965.00,39708346.00,68089848.00,67871263.00,75181391.00,710813686.00
Buffer Cache Hit Ratio,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Index Scan Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Index Tuple Fetch Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Index Cache Hit Ratio,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Table Buffer Hit Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Table Blocks Read Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Table Cache Hit Ratio,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Cache Hit Ratio,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,128.69,148.06,94.19,128.52,188.04,159.52,174.45,189.00
AccessExclusiveLocks Current,0.00,0.02,0.09,0.02,0.00,0.00,0.02,0.02
AccessShareLocks Current,45.61,54.36,28.25,44.05,55.85,44.94,50.67,95.38
ExclusiveLocks Current,2.85,1.64,4.93,3.88,9.93,11.24,10.47,6.64
RowExclusiveLocks Current,80.22,92.03,60.92,80.56,122.26,103.34,113.29,86.96
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of WAL Segments,134.57,189.29,123.89,164.52,143.81,199.60,138.17,193.28
Total WAL Size [GiB],2.10,2.96,1.94,2.57,2.25,3.12,2.16,3.02
WAL Segments Growth Rate [segments/s],0.24,0.11,0.21,0.09,0.27,0.09,0.23,0.10
WAL Growth Rate [MiB/s],3.89,1.76,3.43,1.40,4.26,1.47,3.71,1.64
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00

## With Metadata

Connection infos are added.

In [15]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2
Memory Usage [MiB],7777.19,8206.33,7558.01,8017.41,7976.66,8706.85,7910.65,8745.89
Memory Usage Cached [MiB],8552.64,9233.82,8309.08,8940.31,8832.62,9845.80,8728.59,9834.09
CPU Utilization,0.87,0.89,0.57,0.74,1.17,1.52,1.28,10.09
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],389.77,415.60,261.09,328.68,538.01,716.95,596.33,4769.16
CPU User Time [s],326.40,346.78,212.53,270.50,436.96,633.26,500.50,4640.84
CPU System Time [s],63.37,68.82,48.56,58.19,101.05,83.68,95.83,128.32
Network Rx Total [MiB],94.19,57.70,61.90,49.10,120.24,70.09,104.97,61.79
Network Tx Total [MiB],1064.29,60.79,936.34,58.98,1066.13,54.56,1079.82,47.12
Filesystem Read Total [MiB],0.04,0.04,0.02,0.02,0.14,0.03,0.02,0.01
Filesystem Write Total [MiB],2373.79,2426.45,1626.95,2072.73,3154.14,2007.15,2712.57,2236.78
Core Utilization Variance [%],0.23,0.21,0.17,0.19,0.20,0.18,0.17,1.72
Max Core Utilization [%],3.26,2.59,2.25,2.44,2.65,2.50,2.71,17.68
I/O Wait [%],35.31,39.40,40.30,43.38,32.68,31.07,31.67,11.52
Total I/O Wait Time [s],412.76,414.37,416.70,418.27,411.15,419.34,393.00,410.38
Number of Idle Sessions,1.33,2.64,1.12,2.28,1.56,2.52,1.60,2.34
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,17.00,16.00,16.00,16.00,32.00,32.00,32.00,32.00
Number of Active Application Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Active Transaction,0.03,0.03,0.08,0.06,0.32,0.41,0.22,0.40
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.99,0.99,1.00,0.97,0.99,0.99,0.96,0.98
Active Backends Waiting on WAL,10.58,11.76,6.61,10.16,13.44,8.03,11.94,8.96
Active Backends Waiting on Locks,3.01,1.87,7.39,4.51,14.69,19.46,16.23,9.59
Max Transaction Duration (I/O Wait),0.01,0.01,0.01,0.02,0.02,0.01,0.01,0.01
Max Transaction Duration (WAL Wait),0.03,0.03,0.07,0.05,0.17,0.15,0.13,0.09
Max Transaction Duration (Lock Wait),0.01,0.01,0.06,0.05,0.29,0.38,0.21,0.17
Disk Blocks Read Count,28399.00,8678.00,15958.00,16589.00,26420.00,12493.00,24432.00,14355.00
Buffer Cache Hit Count,49064412.00,48877544.00,38856965.00,39708346.00,68089848.00,67871263.00,75181391.00,710813686.00
Buffer Cache Hit Ratio,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Index Scan Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Index Tuple Fetch Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Index Cache Hit Ratio,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Table Buffer Hit Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Table Blocks Read Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Table Cache Hit Ratio,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Cache Hit Ratio,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,128.69,148.06,94.19,128.52,188.04,159.52,174.45,189.00
AccessExclusiveLocks Current,0.00,0.02,0.09,0.02,0.00,0.00,0.02,0.02
AccessShareLocks Current,45.61,54.36,28.25,44.05,55.85,44.94,50.67,95.38
ExclusiveLocks Current,2.85,1.64,4.93,3.88,9.93,11.24,10.47,6.64
RowExclusiveLocks Current,80.22,92.03,60.92,80.56,122.26,103.34,113.29,86.96
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of WAL Segments,134.57,189.29,123.89,164.52,143.81,199.60,138.17,193.28
Total WAL Size [GiB],2.10,2.96,1.94,2.57,2.25,3.12,2.16,3.02
WAL Segments Growth Rate [segments/s],0.24,0.11,0.21,0.09,0.27,0.09,0.23,0.10
WAL Growth Rate [MiB/s],3.89,1.76,3.43,1.40,4.26,1.47,3.71,1.64
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00
code,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908
configuration,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,180.00,180.00,180.00,180.00,183.00,183.00,222.00,222.00
time_ingest,84.00,84.00,84.00,84.00,84.00,84.00,94.00,94.00
time_check,96.00,96.00,96.00,96.00,98.00,98.00,128.00,128.00
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,3298,4482,3299,4031,3298,4846,3282,4642
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,154360,155544,154360,155093,154359,155908,154343,155704
host_datadisk,3298,4482,3299,4031,3298,4846,3282,4642
host_volume_size,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,0,0,0,0,0,0,0,0
loading_parameters_HAMMERDB_NUM_VU,1,1,1,1,1,1,1,1
loading_parameters_SF,16,16,16,16,16,16,16,16
loading_parameters_HAMMERDB_DURATION,5,5,5,5,5,5,5,5
loading_parameters_HAMMERDB_RAMPUP,2,2,2,2,2,2,2,2
loading_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
loading_parameters_HAMMERDB_VUSERS,16,16,16,16,16,16,16,16
loading_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false,false,false,false,false
loading_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true,true,true,true,true
benchmarking_parameters_HAMMERDB_NUM_VU,1,2,1,2,1,2,1,2
benchmarking_parameters_SF,16,16,16,16,16,16,16,16
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
benchmarking_parameters_HAMMERDB_DURATION,5,5,5,5,5,5,5,5
benchmarking_parameters_HAMMERDB_RAMPUP,2,2,2,2,2,2,2,2
benchmarking_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
benchmarking_parameters_HAMMERDB_VUSERS,16,8,16,8,32,16,32,16
benchmarking_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false,false,false,false,false
benchmarking_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true,true,true,true,true
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [16]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2
code,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908
configuration,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
type_tenants,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False

# Time Series of a Single Metric for a Single Experiment

This is particularly important if you require a customized aggregation or wish to monitor a component over time.

In [17]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_per_phase(code, metric=metric, component='stream')
df.T

,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2
0,7177.68,7800.83,7177.31,7541.44
1,7177.68,7800.83,7177.31,7541.44
2,7177.68,7800.83,7177.31,7541.44
3,7177.68,7800.83,7177.31,7541.44
4,7177.68,7800.83,7177.31,7541.44
5,7177.68,7800.83,7177.31,7541.44
6,7177.68,7800.83,7177.31,7541.44
7,7177.68,7800.83,7177.31,7541.44
8,7378.69,7800.83,7177.31,7758.32
9,7378.69,7800.83,7177.31,7758.32
10,7378.69,7800.83,7177.31,7758.32
11,7378.69,7800.83,7177.31,7758.32
12,7378.69,7800.83,7177.31,7758.32
13,7378.69,7800.83,7177.31,7758.32
14,7378.69,7800.83,7177.31,7758.32
15,7378.69,7800.83,7177.31,7758.32
16,7378.69,7800.83,7177.31,7758.32
17,7378.69,8025.23,7177.31,7758.32
18,7378.69,8025.23,7177.31,7758.32
19,7378.69,8025.23,7177.31,7758.32
20,7378.69,8025.23,7177.31,7758.32
21,7378.69,8025.23,7177.31,7758.32
22,7378.69,8025.23,7177.31,7758.32
23,7378.69,8025.23,7177.31,7758.32
24,7378.69,8025.23,7177.31,7758.32
25,7378.69,8025.23,7177.31,7758.32
26,7378.69,8025.23,7177.31,7758.32
27,7378.69,8025.23,7177.31,7867.18
28,7378.69,8025.23,7444.04,7867.18
29,7378.69,8025.23,7444.04,7867.18
30,7378.69,8025.23,7444.04,7867.18
31,7378.69,8025.23,7444.04,7867.18
32,7378.69,8025.23,7444.04,7867.18
33,7378.69,8025.23,7444.04,7867.18
34,7378.69,8025.23,7444.04,7867.18
35,7378.69,8025.23,7444.04,7867.18
36,7378.69,8025.23,7444.04,7867.18
37,7378.69,8025.23,7444.04,7867.18
38,7378.69,8025.23,7444.04,7867.18
39,7625.29,8025.23,7444.04,7867.18
40,7625.29,8025.23,7444.04,7867.18
41,7625.29,8025.23,7444.04,7867.18
42,7625.29,8025.23,7444.04,7867.18
43,7625.29,8025.23,7444.04,7867.18
44,7625.29,8025.23,7444.04,7867.18
45,7625.29,8025.23,7444.04,7867.18
46,7625.29,8025.23,7444.04,7867.18
47,7625.29,8025.23,7444.04,7867.18
48,7625.29,8025.23,7444.04,7867.18
49,7625.29,8086.74,7444.04,7867.18
50,7625.29,8086.74,7444.04,7867.18
51,7625.29,8086.74,7444.04,7867.18
52,7625.29,8086.74,7444.04,7867.18
53,7625.29,8086.74,7444.04,7867.18
54,7625.29,8086.74,7444.04,7867.18
55,7625.29,8086.74,7444.04,7867.18
56,7625.29,8086.74,7444.04,7867.18
57,7625.29,8086.74,7444.04,7867.18
58,7662.25,8086.74,7444.04,7867.18
59,7662.25,8086.74,7444.04,7867.18
60,7662.25,8086.74,7444.04,7867.18
61,7662.25,8086.74,7444.04,7867.18
62,7662.25,8086.74,7444.04,7867.18
63,7662.25,8086.74,7444.04,7867.18
64,7662.25,8086.74,7490.14,7867.18
65,7662.25,8086.74,7490.14,7867.18
66,7662.25,8086.74,7490.14,7931.63
67,7662.25,8086.74,7490.14,7931.63
68,7662.25,8086.74,7490.14,7931.63
69,7662.25,8086.74,7490.14,7931.63
70,7662.25,8086.74,7490.14,7931.63
71,7662.25,8086.74,7490.14,7931.63
72,7662.25,8086.74,7490.14,7931.63
73,7662.25,8086.74,7490.14,7931.63
74,7662.25,8113.91,7490.14,7931.63
75,7662.25,8113.91,7490.14,7931.63
76,7662.25,8113.91,7490.14,7931.63
77,7662.25,8113.91,7490.14,7931.63
78,7662.25,8113.91,7490.14,7931.63
79,7662.25,8113.91,7490.14,7931.63
80,7662.25,8113.91,7490.14,7931.63
81,7662.25,8113.91,7490.14,7931.63
82,7662.25,8113.91,7490.14,7931.63
83,7694.69,8113.91,7499.85,7931.63
84,7694.69,8113.91,7499.85,7931.63
85,7694.69,8113.91,7499.85,7931.63
86,7694.69,8113.91,7499.85,7931.63
87,7694.69,8113.91,7499.85,7931.63
88,7694.69,8113.91,7499.85,7931.63
89,7694.69,8113.91,7499.85,7931.63
90,7694.69,8113.91,7499.85,7931.63
91,7694.69,8113.91,7499.85,7931.63
92,7694.69,8113.91,7499.85,7931.63
93,7694.69,8113.91,7499.85,7956.00
94,7694.69,8113.91,7499.85,7956.00
95,7694.69,8113.91,7499.85,7956.00
96,7694.69,8113.91,7499.85,7956.00
97,7694.69,8113.91,7499.85,7956.00
98,7694.69,8113.91,7499.85,7956.00
99,7694.69,8113.91,7499.85,7956.00
100,7694.69,8113.91,7499.85,7956.00
101,7694.69,8113.91,7499.85,7956.00
102,7694.69,8113.91,7499.85,7956.00
103,7694.69,8113.91,7499.85,7956.00
104,7694.69,8113.91,7499.85,7956.00
105,7694.69,8113.91,7499.85,7956.00
106,7694.69,8113.91,7499.85,7956.00
107,7694.69,8113.91,7499.85,7956.00
108,7694.69,8113.91,7499.85,7956.00
109,7694.69,8144.05,7499.85,7956.00
110,7694.69,8144.05,7499.85,7956.00
111,7694.69,8144.05,7499.85,7956.00
112,7694.69,8144.05,7499.85,7956.00
113,7694.69,8144.05,7499.85,7956.00
114,7694.69,8144.05,7499.85,7956.00
115,7694.69,8144.05,7499.85,7956.00
116,7694.69,8144.05,7499.85,7956.00
117,7694.69,8144.05,7499.85,7956.00
118,7694.69,8144.05,7499.85,7956.00
119,7694.69,8144.05,7499.85,7956.00
120,7694.69,8144.05,7499.85,7956.00
121,7694.69,8144.05,7499.85,7956.00
122,7694.69,8144.05,7499.85,7956.00
123,7694.69,8144.05,7528.90,7981.62
124,7694.69,8144.05,7528.90,7981.62
125,7694.69,8144.05,7528.90,7981.62
126,7694.69,8144.05,7528.90,7981.62
127,7738.99,8144.05,7528.90,7981.62
128,7738.99,8144.05,7528.90,7981.62
129,7738.99,8144.05,7528.90,7981.62
130,7738.99,8144.05,7528.90,7981.62
131,7738.99,8144.05,7528.90,7981.62
132,7738.99,8144.05,7528.90,7981.62
133,7738.99,8144.05,7528.90,7981.62
134,7738.99,8144.05,7528.90,7981.62
135,7738.99,8144.05,7528.90,7981.62
136,7738.99,8144.05,7528.90,7981.62
137,7738.99,8168.80,7528.90,7981.62
138,7738.99,8168.80,7528.90,7981.62
139,7738.99,8168.80,7528.90,7981.62
140,7738.99,8168.80,7528.90,7981.62
141,7738.99,8168.80,7528.90,7981.62
142,7738.99,8168.80,7528.90,7981.62
143,7738.99,8168.80,7528.90,7981.62
144,7738.99,8168.80,7528.90,7981.62
145,7738.99,8168.80,7528.90,7981.62
146,7738.99,8168.80,7528.90,7981.62
147,7738.99,8168.80,7528.90,7981.62
148,7738.99,8168.80,7528.90,7981.62
149,7738.99,8168.80,7528.90,7981.62
150,7738.99,8168.80,7528.90,7981.62
151,7738.99,8168.80,7528.90,7981.62
152,7759.76,8168.80,7528.90,7981.62
153,7759.76,8168.80,7551.91,7981.62
154,7759.76,8168.80,7551.91,8004.64
155,7759.76,8168.80,7551.91,8004.64
156,7759.76,8168.80,7551.91,8004.64
157,7759.76,8168.80,7551.91,8004.64
158,7759.76,8168.80,7551.91,8004.64
159,7759.76,8168.80,7551.91,8004.64
160,7759.76,8168.80,7551.91,8004.64
161,7759.76,8168.80,7551.91,8004.64
162,7759.76,8168.80,7551.91,8004.64
163,7759.76,8168.80,7551.91,8004.64
164,7759.76,8190.48,7551.91,8004.64
165,7759.76,8190.48,7551.91,8004.64
166,7759.76,8190.48,7551.91,8004.64
167,7759.76,8190.48,7551.91,8004.64
168,7759.76,8190.48,7551.91,8004.64
169,7759.76,8190.48,7551.91,8004.64
170,7759.76,8190.48,7551.91,8004.64
171,7759.76,8190.48,7551.91,8004.64
172,7759.76,8190.48,7551.91,8004.64
173,7759.76,8190.48,7551.91,8004.64
174,7759.76,8190.48,7551.91,8004.64
175,7759.76,8190.48,7551.91,8004.64
176,7759.76,8190.48,7551.91,8004.64
177,7759.76,8190.48,7551.91,8004.64
178,7759.76,8190.48,7551.91,8004.64
179,7782.45,8190.48,7551.91,8004.64
180,7782.45,8190.48,7551.91,8004.64
181,7782.45,8190.48,7551.91,8004.64
182,7782.45,8190.48,7551.91,8004.64
183,7782.45,8190.48,7551.91,8004.64
184,7782.45,8190.48,7574.95,8004.64
185,7782.45,8190.48,7574.95,8004.64
186,7782.45,8190.48,7574.95,8004.64
187,7782.45,8190.48,7574.95,8004.64
188,7782.45,8190.48,7574.95,8004.64
189,7782.45,8190.48,7574.95,8031.09
190,7782.45,8190.48,7574.95,8031.09
191,7782.45,8190.48,7574.95,8031.09
192,7782.45,8190.48,7574.95,8031.09
193,7782.45,8190.48,7574.95,8031.09
194,7782.45,8190.48,7574.95,8031.09
195,7782.45,8190.48,7574.95,8031.09
196,7782.45,8190.48,7574.95,8031.09
197,7782.45,8218.05,7574.95,8031.09
198,7782.45,8218.05,7574.95,8031.09
199,7782.45,8218.05,7574.95,8031.09
200,7782.45,8218.05,7574.95,8031.09
201,7782.45,8218.05,7574.95,8031.09
202,7782.45,8218.05,7574.95,8031.09
203,7782.45,8218.05,7574.95,8031.09
204,7782.45,8218.05,7574.95,8031.09
205,7806.09,8218.05,7574.95,8031.09
206,7806.09,8218.05,7574.95,8031.09
207,7806.09,8218.05,7574.95,8031.09
208,7806.09,8218.05,7574.95,8031.09
209,7806.09,8218.05,7574.95,8031.09
210,7806.09,8218.05,7574.95,8031.09
211,7806.09,8218.05,7574.95,8031.09
212,7806.09,8218.05,7589.09,8031.09
213,7806.09,8218.05,7589.09,8031.09
214,7806.09,8218.05,7589.09,8031.09
215,7806.09,8218.05,7589.09,8031.09
216,7806.09,8218.05,7589.09,8031.09
217,7806.09,8218.05,7589.09,8031.09
218,7806.09,8218.05,7589.09,8031.09
219,7806.09,8218.05,7589.09,8031.09
220,7806.09,8218.05,7589.09,8051.54
221,7806.09,8218.05,7589.09,8051.54
222,7806.09,8218.05,7589.09,8051.54
223,7806.09,8238.18,7589.09,8051.54
224,7806.09,8238.18,7589.09,8051.54
225,7806.09,8238.18,7589.09,8051.54
226,7806.09,8238.18,7589.09,8051.54
227,7806.09,8238.18,7589.09,8051.54
228,7806.09,8238.18,7589.09,8051.54
229,7806.09,8238.18,7589.09,8051.54
230,7806.09,8238.18,7589.09,8051.54
231,7806.09,8238.18,7589.09,8051.54
232,7806.09,8238.18,7589.09,8051.54
233,7806.09,8238.18,7589.09,8051.54
234,7806.09,8238.18,7589.09,8051.54
235,7806.09,8238.18,7589.09,8051.54
236,7806.09,8238.18,7589.09,8051.54
237,7806.09,8238.18,7589.09,8051.54
238,7806.09,8238.18,7589.09,8063.78
239,7806.09,8238.18,7589.09,8063.78
240,7806.09,8238.18,7589.09,8063.78
241,7806.09,8238.18,7606.66,8063.78
242,7806.09,8238.18,7606.66,8063.78
243,7806.09,8238.18,7606.66,8063.78
244,7806.09,8238.18,7606.66,8063.78
245,7806.09,8238.18,7606.66,8063.78
246,7806.09,8238.18,7606.66,8063.78
247,7806.09,8238.18,7606.66,8063.78
248,7806.09,8238.18,7606.66,8063.78
249,7843.71,8238.18,7606.66,8063.78
250,7843.71,8238.18,7606.66,8063.78
251,7843.71,8238.18,7606.66,8063.78
252,7843.71,8238.18,7606.66,8063.78
253,7843.71,8238.18,7606.66,8063.78
254,7843.71,8238.18,7606.66,8063.78
255,7843.71,8238.18,7606.66,8063.78
256,7843.71,8238.18,7606.66,8063.78
257,7843.71,8238.18,7606.66,8063.78
258,7843.71,8238.18,7606.66,8063.78
259,7843.71,8266.32,7606.66,8063.78
260,7843.71,8266.32,7606.66,8063.78
261,7843.71,8266.32,7618.42,8063.78
262,7843.71,8266.32,7618.42,8063.78
263,7843.71,8266.32,7618.42,8081.09
264,7843.71,8266.32,7618.42,8081.09
265,7843.71,8266.32,7618.42,8081.09
266,7843.71,8266.32,7618.42,8081.09
267,7843.71,8266.32,7618.42,8081.09
268,7861.88,8266.32,7618.42,8081.09
269,7861.88,8266.32,7618.42,8081.09
270,7861.88,8266.32,7618.42,8081.09
271,7861.88,8266.32,7618.42,8081.09
272,7861.88,8274.05,7618.42,8081.09
273,7861.88,8274.05,7618.42,8081.09
274,7861.88,8274.05,7618.42,8081.09
275,7861.88,8274.05,7618.42,8081.09
276,7861.88,8274.05,7618.42,8081.09
277,7861.88,8274.05,7618.42,8081.09
278,7861.88,8274.05,7618.42,8081.09
279,7861.88,8274.05,7618.42,8081.09
280,7861.88,8274.05,7618.42,8081.09
281,7861.88,8274.05,7618.42,8081.09
282,7861.88,8274.05,7618.42,8081.09
283,7861.88,8274.05,7618.42,8081.09
284,7861.88,8274.05,7618.42,8081.09
285,7861.88,8274.05,7618.42,8081.09
286,7861.88,8274.05,7618.42,8081.09
287,7861.88,8274.05,7618.42,8081.09
288,7861.88,8274.05,7618.42,8081.09
289,7861.88,8274.05,7618.42,8081.09
290,7861.88,8274.05,7618.42,8081.09
291,7861.88,8274.05,7618.42,8081.09
292,7861.88,8274.05,7618.42,8081.09
293,7861.88,8274.05,7618.42,8081.09
294,7861.88,8274.05,7618.42,8081.09
295,7861.88,8274.05,7618.42,8081.09
296,7861.88,8274.05,7618.42,8081.09
297,7861.88,8274.05,7618.42,8081.09
298,7861.88,8274.05,7618.42,8081.09
299,7861.88,8274.05,7618.42,8081.09
300,7861.88,8274.05,7618.42,8081.09
301,7861.88,8274.05,7618.42,8081.09
302,7861.88,8274.05,7618.42,8081.09
303,7861.88,8274.05,7618.42,8081.09
304,7861.88,8274.05,7618.42,8081.09
305,7861.88,8274.05,7645.18,8081.09
306,7861.88,8274.05,7645.18,8081.09
307,7892.12,8274.05,7645.18,8081.09
308,7892.12,8274.05,7645.18,8081.09
309,7892.12,8274.05,7645.18,8111.70
310,7892.12,8303.09,7645.18,8111.70
311,7892.12,8303.09,7645.18,8111.70
312,7892.12,8303.09,7645.18,8111.70
313,7892.12,8303.09,7645.18,8111.70
314,7892.12,8303.09,7645.18,8111.70
315,7892.12,8303.09,7645.18,8111.70
316,7892.12,8303.09,7645.18,8111.70
317,7892.12,8303.09,7645.18,8111.70
318,7892.12,8303.09,7645.18,8111.70
319,7892.12,8303.09,7645.18,8111.70
320,7892.12,8303.09,7645.18,8111.70
321,7892.12,8303.09,7645.18,8111.70
322,7892.12,8303.09,7645.18,8111.70
323,7892.12,8303.09,7645.18,8111.70
324,7892.12,8303.09,7645.18,8111.70
325,7892.12,8303.09,7645.18,8111.70
326,7892.12,8303.09,7645.18,8111.70
327,7892.12,8303.09,7645.18,8111.70
328,7892.12,8303.09,7645.18,8111.70
329,7892.12,8303.09,7657.89,8111.70
330,7892.12,8303.09,7657.89,8111.70
331,7892.12,8303.09,7657.89,8111.70
332,7892.12,8303.09,7657.89,8111.70
333,7892.12,8303.09,7657.89,8111.70
334,7892.12,8323.08,7657.89,8111.70
335,7892.12,8323.08,7657.89,8111.70
336,7892.12,8323.08,7657.89,8111.70
337,7892.12,8323.08,7657.89,8111.70
338,7892.12,8323.08,7657.89,8131.21
339,7916.83,8323.08,7657.89,8131.21
340,7916.83,8323.08,7657.89,8131.21
341,7916.83,8323.08,7657.89,8131.21
342,7916.83,8323.08,7657.89,8131.21
343,7916.83,8323.08,7657.89,8131.21
344,7916.83,8323.08,7657.89,8131.21
345,7916.83,8323.08,7657.89,8131.21
346,7916.83,8323.08,7657.89,8131.21
347,7916.83,8323.08,7657.89,8131.21
348,7916.83,8323.08,7657.89,8131.21
349,7916.83,8323.08,7657.89,8131.21
350,7916.83,8323.08,7657.89,8131.21
351,7916.83,8323.08,7657.89,8131.21
352,7916.83,8323.08,7670.82,8131.21
353,7916.83,8323.08,7670.82,8131.21
354,7916.83,8323.08,7670.82,8131.21
355,7916.83,8323.08,7670.82,8131.21
356,7916.83,8323.08,7670.82,8131.21
357,7916.83,8323.08,7670.82,8131.21
358,7916.83,8323.08,7670.82,8131.21
359,7916.83,8323.08,7670.82,8131.21
360,7916.83,8323.08,7670.82,8131.21
361,7916.83,8323.08,7670.82,8131.21
362,7916.83,8323.08,7670.82,8131.21
363,7916.83,8323.08,7670.82,8131.21
364,7916.83,8323.08,7670.82,8131.21
365,7916.83,8323.08,7670.82,8131.21
366,7916.83,8323.08,7670.82,8131.21
367,7916.83,8323.08,7670.82,8131.21
368,7941.53,8323.08,7670.82,8131.21
369,7941.53,8323.08,7670.82,8131.21
370,7941.53,8323.08,7670.82,8151.22
371,7941.53,8323.08,7670.82,8151.22
372,7941.53,8323.08,7670.82,8151.22
373,7941.53,8353.85,7670.82,8151.22
374,7941.53,8353.85,7670.82,8151.22
375,7941.53,8353.85,7670.82,8151.22
376,7941.53,8353.85,7670.82,8151.22
377,7941.53,8353.85,7670.82,8151.22
378,7941.53,8353.85,7670.82,8151.22
379,7941.53,8353.85,7670.82,8151.22
380,7941.53,8353.85,7670.82,8151.22
381,7941.53,8353.85,7687.04,8151.22
382,7941.53,8353.85,7687.04,8151.22
383,7941.53,8353.85,7687.04,8151.22
384,7941.53,8353.85,7687.04,8151.22
385,7941.53,8353.85,7687.04,8151.22
386,7941.53,8353.85,7687.04,8151.22
387,7957.46,8353.85,7687.04,8151.22
388,7957.46,8353.85,7687.04,8151.22
389,7957.46,8353.85,7687.04,8151.22
390,7957.46,8353.85,7687.04,8151.22
391,7957.46,8353.85,7687.04,8151.22
392,7957.46,8353.85,7687.04,8151.22
393,7957.46,8353.85,7687.04,8151.22
394,7957.46,8353.85,7687.04,8151.22
395,7957.46,8353.85,7687.04,8151.22
396,7957.46,8353.85,7687.04,8151.22
397,7957.46,8353.85,7687.04,8151.22
398,7957.46,8353.85,7687.04,8151.22
399,7957.46,8353.85,7687.04,8171.26
400,7957.46,8353.85,7687.04,8171.26
401,7957.46,8353.85,7687.04,8171.26
402,7957.46,8353.85,7687.04,8171.26
403,7957.46,8353.85,7687.04,8171.26
404,7957.46,8353.85,7687.04,8171.26
405,7957.46,8353.85,7687.04,8171.26
406,7957.46,8353.85,7687.04,8171.26
407,7957.46,8353.85,7687.04,8171.26
408,7957.46,8353.85,7687.04,8171.26
409,7957.46,8353.85,7687.04,8171.26
410,7957.46,8382.68,7687.04,8171.26
411,7957.46,8382.68,7687.04,8171.26
412,7957.46,8382.68,7687.04,8171.26
413,7957.46,8382.68,7687.04,8171.26
414,7957.46,8382.68,7687.04,8171.26
415,7957.46,8382.68,7687.04,8171.26
416,7957.46,8382.68,7687.04,8171.26
417,7957.46,8382.68,7687.04,8171.26
418,7957.46,8382.68,7687.04,8171.26
419,7983.82,8382.68,7687.04,8171.26
420,7983.82,8382.68,7687.04,8171.26
421,7983.82,8382.68,7687.04,8171.26
422,7983.82,8382.68,7687.04,8171.26
423,7983.82,8382.68,7687.04,8171.26
424,7983.82,8382.68,7687.04,8171.26
425,7983.82,8382.68,7605.62,8068.55
426,7983.82,8382.68,7605.62,8068.55
427,7983.82,8382.68,7605.62,8068.55
428,7983.82,8382.68,7605.62,8068.55
429,7983.82,8382.68,7605.62,8068.55
430,7983.82,8382.68,7605.62,8068.55
431,7983.82,8382.68,7605.62,8068.55
432,7983.82,8382.68,7605.62,8068.55
433,7983.82,8382.68,7605.62,8068.55
434,7983.82,8382.68,7605.62,8068.55
435,7983.82,8382.68,7605.62,8068.55
436,7983.82,8382.68,7605.62,8068.55
437,7983.82,8382.68,7605.62,8068.55
438,7983.82,8382.68,7605.62,8068.55
439,7983.82,8194.39,7605.62,8068.55
440,7983.82,8194.39,7605.62,8068.55
441,7983.82,8194.39,7605.62,8068.55
442,7983.82,8194.39,7605.62,8068.55
443,7983.82,8194.39,7605.62,NaN
444,7983.82,NaN,7605.62,NaN
445,NaN,NaN,7605.62,NaN
446,NaN,NaN,7605.62,NaN
447,NaN,NaN,7605.62,NaN

## With Metadata

Connection infos are added.

In [18]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2
0,7177.68,7800.83,7177.31,7541.44
1,7177.68,7800.83,7177.31,7541.44
2,7177.68,7800.83,7177.31,7541.44
3,7177.68,7800.83,7177.31,7541.44
4,7177.68,7800.83,7177.31,7541.44
5,7177.68,7800.83,7177.31,7541.44
6,7177.68,7800.83,7177.31,7541.44
7,7177.68,7800.83,7177.31,7541.44
8,7378.69,7800.83,7177.31,7758.32
9,7378.69,7800.83,7177.31,7758.32
10,7378.69,7800.83,7177.31,7758.32
11,7378.69,7800.83,7177.31,7758.32
12,7378.69,7800.83,7177.31,7758.32
13,7378.69,7800.83,7177.31,7758.32
14,7378.69,7800.83,7177.31,7758.32
15,7378.69,7800.83,7177.31,7758.32
16,7378.69,7800.83,7177.31,7758.32
17,7378.69,8025.23,7177.31,7758.32
18,7378.69,8025.23,7177.31,7758.32
19,7378.69,8025.23,7177.31,7758.32
20,7378.69,8025.23,7177.31,7758.32
21,7378.69,8025.23,7177.31,7758.32
22,7378.69,8025.23,7177.31,7758.32
23,7378.69,8025.23,7177.31,7758.32
24,7378.69,8025.23,7177.31,7758.32
25,7378.69,8025.23,7177.31,7758.32
26,7378.69,8025.23,7177.31,7758.32
27,7378.69,8025.23,7177.31,7867.18
28,7378.69,8025.23,7444.04,7867.18
29,7378.69,8025.23,7444.04,7867.18
30,7378.69,8025.23,7444.04,7867.18
31,7378.69,8025.23,7444.04,7867.18
32,7378.69,8025.23,7444.04,7867.18
33,7378.69,8025.23,7444.04,7867.18
34,7378.69,8025.23,7444.04,7867.18
35,7378.69,8025.23,7444.04,7867.18
36,7378.69,8025.23,7444.04,7867.18
37,7378.69,8025.23,7444.04,7867.18
38,7378.69,8025.23,7444.04,7867.18
39,7625.29,8025.23,7444.04,7867.18
40,7625.29,8025.23,7444.04,7867.18
41,7625.29,8025.23,7444.04,7867.18
42,7625.29,8025.23,7444.04,7867.18
43,7625.29,8025.23,7444.04,7867.18
44,7625.29,8025.23,7444.04,7867.18
45,7625.29,8025.23,7444.04,7867.18
46,7625.29,8025.23,7444.04,7867.18
47,7625.29,8025.23,7444.04,7867.18
48,7625.29,8025.23,7444.04,7867.18
49,7625.29,8086.74,7444.04,7867.18
50,7625.29,8086.74,7444.04,7867.18
51,7625.29,8086.74,7444.04,7867.18
52,7625.29,8086.74,7444.04,7867.18
53,7625.29,8086.74,7444.04,7867.18
54,7625.29,8086.74,7444.04,7867.18
55,7625.29,8086.74,7444.04,7867.18
56,7625.29,8086.74,7444.04,7867.18
57,7625.29,8086.74,7444.04,7867.18
58,7662.25,8086.74,7444.04,7867.18
59,7662.25,8086.74,7444.04,7867.18
60,7662.25,8086.74,7444.04,7867.18
61,7662.25,8086.74,7444.04,7867.18
62,7662.25,8086.74,7444.04,7867.18
63,7662.25,8086.74,7444.04,7867.18
64,7662.25,8086.74,7490.14,7867.18
65,7662.25,8086.74,7490.14,7867.18
66,7662.25,8086.74,7490.14,7931.63
67,7662.25,8086.74,7490.14,7931.63
68,7662.25,8086.74,7490.14,7931.63
69,7662.25,8086.74,7490.14,7931.63
70,7662.25,8086.74,7490.14,7931.63
71,7662.25,8086.74,7490.14,7931.63
72,7662.25,8086.74,7490.14,7931.63
73,7662.25,8086.74,7490.14,7931.63
74,7662.25,8113.91,7490.14,7931.63
75,7662.25,8113.91,7490.14,7931.63
76,7662.25,8113.91,7490.14,7931.63
77,7662.25,8113.91,7490.14,7931.63
78,7662.25,8113.91,7490.14,7931.63
79,7662.25,8113.91,7490.14,7931.63
80,7662.25,8113.91,7490.14,7931.63
81,7662.25,8113.91,7490.14,7931.63
82,7662.25,8113.91,7490.14,7931.63
83,7694.69,8113.91,7499.85,7931.63
84,7694.69,8113.91,7499.85,7931.63
85,7694.69,8113.91,7499.85,7931.63
86,7694.69,8113.91,7499.85,7931.63
87,7694.69,8113.91,7499.85,7931.63
88,7694.69,8113.91,7499.85,7931.63
89,7694.69,8113.91,7499.85,7931.63
90,7694.69,8113.91,7499.85,7931.63
91,7694.69,8113.91,7499.85,7931.63
92,7694.69,8113.91,7499.85,7931.63
93,7694.69,8113.91,7499.85,7956.00
94,7694.69,8113.91,7499.85,7956.00
95,7694.69,8113.91,7499.85,7956.00
96,7694.69,8113.91,7499.85,7956.00
97,7694.69,8113.91,7499.85,7956.00
98,7694.69,8113.91,7499.85,7956.00
99,7694.69,8113.91,7499.85,7956.00
100,7694.69,8113.91,7499.85,7956.00
101,7694.69,8113.91,7499.85,7956.00
102,7694.69,8113.91,7499.85,7956.00
103,7694.69,8113.91,7499.85,7956.00
104,7694.69,8113.91,7499.85,7956.00
105,7694.69,8113.91,7499.85,7956.00
106,7694.69,8113.91,7499.85,7956.00
107,7694.69,8113.91,7499.85,7956.00
108,7694.69,8113.91,7499.85,7956.00
109,7694.69,8144.05,7499.85,7956.00
110,7694.69,8144.05,7499.85,7956.00
111,7694.69,8144.05,7499.85,7956.00
112,7694.69,8144.05,7499.85,7956.00
113,7694.69,8144.05,7499.85,7956.00
114,7694.69,8144.05,7499.85,7956.00
115,7694.69,8144.05,7499.85,7956.00
116,7694.69,8144.05,7499.85,7956.00
117,7694.69,8144.05,7499.85,7956.00
118,7694.69,8144.05,7499.85,7956.00
119,7694.69,8144.05,7499.85,7956.00
120,7694.69,8144.05,7499.85,7956.00
121,7694.69,8144.05,7499.85,7956.00
122,7694.69,8144.05,7499.85,7956.00
123,7694.69,8144.05,7528.90,7981.62
124,7694.69,8144.05,7528.90,7981.62
125,7694.69,8144.05,7528.90,7981.62
126,7694.69,8144.05,7528.90,7981.62
127,7738.99,8144.05,7528.90,7981.62
128,7738.99,8144.05,7528.90,7981.62
129,7738.99,8144.05,7528.90,7981.62
130,7738.99,8144.05,7528.90,7981.62
131,7738.99,8144.05,7528.90,7981.62
132,7738.99,8144.05,7528.90,7981.62
133,7738.99,8144.05,7528.90,7981.62
134,7738.99,8144.05,7528.90,7981.62
135,7738.99,8144.05,7528.90,7981.62
136,7738.99,8144.05,7528.90,7981.62
137,7738.99,8168.80,7528.90,7981.62
138,7738.99,8168.80,7528.90,7981.62
139,7738.99,8168.80,7528.90,7981.62
140,7738.99,8168.80,7528.90,7981.62
141,7738.99,8168.80,7528.90,7981.62
142,7738.99,8168.80,7528.90,7981.62
143,7738.99,8168.80,7528.90,7981.62
144,7738.99,8168.80,7528.90,7981.62
145,7738.99,8168.80,7528.90,7981.62
146,7738.99,8168.80,7528.90,7981.62
147,7738.99,8168.80,7528.90,7981.62
148,7738.99,8168.80,7528.90,7981.62
149,7738.99,8168.80,7528.90,7981.62
150,7738.99,8168.80,7528.90,7981.62
151,7738.99,8168.80,7528.90,7981.62
152,7759.76,8168.80,7528.90,7981.62
153,7759.76,8168.80,7551.91,7981.62
154,7759.76,8168.80,7551.91,8004.64
155,7759.76,8168.80,7551.91,8004.64
156,7759.76,8168.80,7551.91,8004.64
157,7759.76,8168.80,7551.91,8004.64
158,7759.76,8168.80,7551.91,8004.64
159,7759.76,8168.80,7551.91,8004.64
160,7759.76,8168.80,7551.91,8004.64
161,7759.76,8168.80,7551.91,8004.64
162,7759.76,8168.80,7551.91,8004.64
163,7759.76,8168.80,7551.91,8004.64
164,7759.76,8190.48,7551.91,8004.64
165,7759.76,8190.48,7551.91,8004.64
166,7759.76,8190.48,7551.91,8004.64
167,7759.76,8190.48,7551.91,8004.64
168,7759.76,8190.48,7551.91,8004.64
169,7759.76,8190.48,7551.91,8004.64
170,7759.76,8190.48,7551.91,8004.64
171,7759.76,8190.48,7551.91,8004.64
172,7759.76,8190.48,7551.91,8004.64
173,7759.76,8190.48,7551.91,8004.64
174,7759.76,8190.48,7551.91,8004.64
175,7759.76,8190.48,7551.91,8004.64
176,7759.76,8190.48,7551.91,8004.64
177,7759.76,8190.48,7551.91,8004.64
178,7759.76,8190.48,7551.91,8004.64
179,7782.45,8190.48,7551.91,8004.64
180,7782.45,8190.48,7551.91,8004.64
181,7782.45,8190.48,7551.91,8004.64
182,7782.45,8190.48,7551.91,8004.64
183,7782.45,8190.48,7551.91,8004.64
184,7782.45,8190.48,7574.95,8004.64
185,7782.45,8190.48,7574.95,8004.64
186,7782.45,8190.48,7574.95,8004.64
187,7782.45,8190.48,7574.95,8004.64
188,7782.45,8190.48,7574.95,8004.64
189,7782.45,8190.48,7574.95,8031.09
190,7782.45,8190.48,7574.95,8031.09
191,7782.45,8190.48,7574.95,8031.09
192,7782.45,8190.48,7574.95,8031.09
193,7782.45,8190.48,7574.95,8031.09
194,7782.45,8190.48,7574.95,8031.09
195,7782.45,8190.48,7574.95,8031.09
196,7782.45,8190.48,7574.95,8031.09
197,7782.45,8218.05,7574.95,8031.09
198,7782.45,8218.05,7574.95,8031.09
199,7782.45,8218.05,7574.95,8031.09
200,7782.45,8218.05,7574.95,8031.09
201,7782.45,8218.05,7574.95,8031.09
202,7782.45,8218.05,7574.95,8031.09
203,7782.45,8218.05,7574.95,8031.09
204,7782.45,8218.05,7574.95,8031.09
205,7806.09,8218.05,7574.95,8031.09
206,7806.09,8218.05,7574.95,8031.09
207,7806.09,8218.05,7574.95,8031.09
208,7806.09,8218.05,7574.95,8031.09
209,7806.09,8218.05,7574.95,8031.09
210,7806.09,8218.05,7574.95,8031.09
211,7806.09,8218.05,7574.95,8031.09
212,7806.09,8218.05,7589.09,8031.09
213,7806.09,8218.05,7589.09,8031.09
214,7806.09,8218.05,7589.09,8031.09
215,7806.09,8218.05,7589.09,8031.09
216,7806.09,8218.05,7589.09,8031.09
217,7806.09,8218.05,7589.09,8031.09
218,7806.09,8218.05,7589.09,8031.09
219,7806.09,8218.05,7589.09,8031.09
220,7806.09,8218.05,7589.09,8051.54
221,7806.09,8218.05,7589.09,8051.54
222,7806.09,8218.05,7589.09,8051.54
223,7806.09,8238.18,7589.09,8051.54
224,7806.09,8238.18,7589.09,8051.54
225,7806.09,8238.18,7589.09,8051.54
226,7806.09,8238.18,7589.09,8051.54
227,7806.09,8238.18,7589.09,8051.54
228,7806.09,8238.18,7589.09,8051.54
229,7806.09,8238.18,7589.09,8051.54
230,7806.09,8238.18,7589.09,8051.54
231,7806.09,8238.18,7589.09,8051.54
232,7806.09,8238.18,7589.09,8051.54
233,7806.09,8238.18,7589.09,8051.54
234,7806.09,8238.18,7589.09,8051.54
235,7806.09,8238.18,7589.09,8051.54
236,7806.09,8238.18,7589.09,8051.54
237,7806.09,8238.18,7589.09,8051.54
238,7806.09,8238.18,7589.09,8063.78
239,7806.09,8238.18,7589.09,8063.78
240,7806.09,8238.18,7589.09,8063.78
241,7806.09,8238.18,7606.66,8063.78
242,7806.09,8238.18,7606.66,8063.78
243,7806.09,8238.18,7606.66,8063.78
244,7806.09,8238.18,7606.66,8063.78
245,7806.09,8238.18,7606.66,8063.78
246,7806.09,8238.18,7606.66,8063.78
247,7806.09,8238.18,7606.66,8063.78
248,7806.09,8238.18,7606.66,8063.78
249,7843.71,8238.18,7606.66,8063.78
250,7843.71,8238.18,7606.66,8063.78
251,7843.71,8238.18,7606.66,8063.78
252,7843.71,8238.18,7606.66,8063.78
253,7843.71,8238.18,7606.66,8063.78
254,7843.71,8238.18,7606.66,8063.78
255,7843.71,8238.18,7606.66,8063.78
256,7843.71,8238.18,7606.66,8063.78
257,7843.71,8238.18,7606.66,8063.78
258,7843.71,8238.18,7606.66,8063.78
259,7843.71,8266.32,7606.66,8063.78
260,7843.71,8266.32,7606.66,8063.78
261,7843.71,8266.32,7618.42,8063.78
262,7843.71,8266.32,7618.42,8063.78
263,7843.71,8266.32,7618.42,8081.09
264,7843.71,8266.32,7618.42,8081.09
265,7843.71,8266.32,7618.42,8081.09
266,7843.71,8266.32,7618.42,8081.09
267,7843.71,8266.32,7618.42,8081.09
268,7861.88,8266.32,7618.42,8081.09
269,7861.88,8266.32,7618.42,8081.09
270,7861.88,8266.32,7618.42,8081.09
271,7861.88,8266.32,7618.42,8081.09
272,7861.88,8274.05,7618.42,8081.09
273,7861.88,8274.05,7618.42,8081.09
274,7861.88,8274.05,7618.42,8081.09
275,7861.88,8274.05,7618.42,8081.09
276,7861.88,8274.05,7618.42,8081.09
277,7861.88,8274.05,7618.42,8081.09
278,7861.88,8274.05,7618.42,8081.09
279,7861.88,8274.05,7618.42,8081.09
280,7861.88,8274.05,7618.42,8081.09
281,7861.88,8274.05,7618.42,8081.09
282,7861.88,8274.05,7618.42,8081.09
283,7861.88,8274.05,7618.42,8081.09
284,7861.88,8274.05,7618.42,8081.09
285,7861.88,8274.05,7618.42,8081.09
286,7861.88,8274.05,7618.42,8081.09
287,7861.88,8274.05,7618.42,8081.09
288,7861.88,8274.05,7618.42,8081.09
289,7861.88,8274.05,7618.42,8081.09
290,7861.88,8274.05,7618.42,8081.09
291,7861.88,8274.05,7618.42,8081.09
292,7861.88,8274.05,7618.42,8081.09
293,7861.88,8274.05,7618.42,8081.09
294,7861.88,8274.05,7618.42,8081.09
295,7861.88,8274.05,7618.42,8081.09
296,7861.88,8274.05,7618.42,8081.09
297,7861.88,8274.05,7618.42,8081.09
298,7861.88,8274.05,7618.42,8081.09
299,7861.88,8274.05,7618.42,8081.09
300,7861.88,8274.05,7618.42,8081.09
301,7861.88,8274.05,7618.42,8081.09
302,7861.88,8274.05,7618.42,8081.09
303,7861.88,8274.05,7618.42,8081.09
304,7861.88,8274.05,7618.42,8081.09
305,7861.88,8274.05,7645.18,8081.09
306,7861.88,8274.05,7645.18,8081.09
307,7892.12,8274.05,7645.18,8081.09
308,7892.12,8274.05,7645.18,8081.09
309,7892.12,8274.05,7645.18,8111.70
310,7892.12,8303.09,7645.18,8111.70
311,7892.12,8303.09,7645.18,8111.70
312,7892.12,8303.09,7645.18,8111.70
313,7892.12,8303.09,7645.18,8111.70
314,7892.12,8303.09,7645.18,8111.70
315,7892.12,8303.09,7645.18,8111.70
316,7892.12,8303.09,7645.18,8111.70
317,7892.12,8303.09,7645.18,8111.70
318,7892.12,8303.09,7645.18,8111.70
319,7892.12,8303.09,7645.18,8111.70
320,7892.12,8303.09,7645.18,8111.70
321,7892.12,8303.09,7645.18,8111.70
322,7892.12,8303.09,7645.18,8111.70
323,7892.12,8303.09,7645.18,8111.70
324,7892.12,8303.09,7645.18,8111.70
325,7892.12,8303.09,7645.18,8111.70
326,7892.12,8303.09,7645.18,8111.70
327,7892.12,8303.09,7645.18,8111.70
328,7892.12,8303.09,7645.18,8111.70
329,7892.12,8303.09,7657.89,8111.70
330,7892.12,8303.09,7657.89,8111.70
331,7892.12,8303.09,7657.89,8111.70
332,7892.12,8303.09,7657.89,8111.70
333,7892.12,8303.09,7657.89,8111.70
334,7892.12,8323.08,7657.89,8111.70
335,7892.12,8323.08,7657.89,8111.70
336,7892.12,8323.08,7657.89,8111.70
337,7892.12,8323.08,7657.89,8111.70
338,7892.12,8323.08,7657.89,8131.21
339,7916.83,8323.08,7657.89,8131.21
340,7916.83,8323.08,7657.89,8131.21
341,7916.83,8323.08,7657.89,8131.21
342,7916.83,8323.08,7657.89,8131.21
343,7916.83,8323.08,7657.89,8131.21
344,7916.83,8323.08,7657.89,8131.21
345,7916.83,8323.08,7657.89,8131.21
346,7916.83,8323.08,7657.89,8131.21
347,7916.83,8323.08,7657.89,8131.21
348,7916.83,8323.08,7657.89,8131.21
349,7916.83,8323.08,7657.89,8131.21
350,7916.83,8323.08,7657.89,8131.21
351,7916.83,8323.08,7657.89,8131.21
352,7916.83,8323.08,7670.82,8131.21
353,7916.83,8323.08,7670.82,8131.21
354,7916.83,8323.08,7670.82,8131.21
355,7916.83,8323.08,7670.82,8131.21
356,7916.83,8323.08,7670.82,8131.21
357,7916.83,8323.08,7670.82,8131.21
358,7916.83,8323.08,7670.82,8131.21
359,7916.83,8323.08,7670.82,8131.21
360,7916.83,8323.08,7670.82,8131.21
361,7916.83,8323.08,7670.82,8131.21
362,7916.83,8323.08,7670.82,8131.21
363,7916.83,8323.08,7670.82,8131.21
364,7916.83,8323.08,7670.82,8131.21
365,7916.83,8323.08,7670.82,8131.21
366,7916.83,8323.08,7670.82,8131.21
367,7916.83,8323.08,7670.82,8131.21
368,7941.53,8323.08,7670.82,8131.21
369,7941.53,8323.08,7670.82,8131.21
370,7941.53,8323.08,7670.82,8151.22
371,7941.53,8323.08,7670.82,8151.22
372,7941.53,8323.08,7670.82,8151.22
373,7941.53,8353.85,7670.82,8151.22
374,7941.53,8353.85,7670.82,8151.22
375,7941.53,8353.85,7670.82,8151.22
376,7941.53,8353.85,7670.82,8151.22
377,7941.53,8353.85,7670.82,8151.22
378,7941.53,8353.85,7670.82,8151.22
379,7941.53,8353.85,7670.82,8151.22
380,7941.53,8353.85,7670.82,8151.22
381,7941.53,8353.85,7687.04,8151.22
382,7941.53,8353.85,7687.04,8151.22
383,7941.53,8353.85,7687.04,8151.22
384,7941.53,8353.85,7687.04,8151.22
385,7941.53,8353.85,7687.04,8151.22
386,7941.53,8353.85,7687.04,8151.22
387,7957.46,8353.85,7687.04,8151.22
388,7957.46,8353.85,7687.04,8151.22
389,7957.46,8353.85,7687.04,8151.22
390,7957.46,8353.85,7687.04,8151.22
391,7957.46,8353.85,7687.04,8151.22
392,7957.46,8353.85,7687.04,8151.22
393,7957.46,8353.85,7687.04,8151.22
394,7957.46,8353.85,7687.04,8151.22
395,7957.46,8353.85,7687.04,8151.22
396,7957.46,8353.85,7687.04,8151.22
397,7957.46,8353.85,7687.04,8151.22
398,7957.46,8353.85,7687.04,8151.22
399,7957.46,8353.85,7687.04,8171.26
400,7957.46,8353.85,7687.04,8171.26
401,7957.46,8353.85,7687.04,8171.26
402,7957.46,8353.85,7687.04,8171.26
403,7957.46,8353.85,7687.04,8171.26
404,7957.46,8353.85,7687.04,8171.26
405,7957.46,8353.85,7687.04,8171.26
406,7957.46,8353.85,7687.04,8171.26
407,7957.46,8353.85,7687.04,8171.26
408,7957.46,8353.85,7687.04,8171.26
409,7957.46,8353.85,7687.04,8171.26
410,7957.46,8382.68,7687.04,8171.26
411,7957.46,8382.68,7687.04,8171.26
412,7957.46,8382.68,7687.04,8171.26
413,7957.46,8382.68,7687.04,8171.26
414,7957.46,8382.68,7687.04,8171.26
415,7957.46,8382.68,7687.04,8171.26
416,7957.46,8382.68,7687.04,8171.26
417,7957.46,8382.68,7687.04,8171.26
418,7957.46,8382.68,7687.04,8171.26
419,7983.82,8382.68,7687.04,8171.26
420,7983.82,8382.68,7687.04,8171.26
421,7983.82,8382.68,7687.04,8171.26
422,7983.82,8382.68,7687.04,8171.26
423,7983.82,8382.68,7687.04,8171.26
424,7983.82,8382.68,7687.04,8171.26
425,7983.82,8382.68,7605.62,8068.55
426,7983.82,8382.68,7605.62,8068.55
427,7983.82,8382.68,7605.62,8068.55
428,7983.82,8382.68,7605.62,8068.55
429,7983.82,8382.68,7605.62,8068.55
430,7983.82,8382.68,7605.62,8068.55
431,7983.82,8382.68,7605.62,8068.55
432,7983.82,8382.68,7605.62,8068.55
433,7983.82,8382.68,7605.62,8068.55
434,7983.82,8382.68,7605.62,8068.55
435,7983.82,8382.68,7605.62,8068.55
436,7983.82,8382.68,7605.62,8068.55
437,7983.82,8382.68,7605.62,8068.55
438,7983.82,8382.68,7605.62,8068.55
439,7983.82,8194.39,7605.62,8068.55
440,7983.82,8194.39,7605.62,8068.55
441,7983.82,8194.39,7605.62,8068.55
442,7983.82,8194.39,7605.62,8068.55
443,7983.82,8194.39,7605.62,NaN
444,7983.82,NaN,7605.62,NaN
445,NaN,NaN,7605.62,NaN
446,NaN,NaN,7605.62,NaN
447,NaN,NaN,7605.62,NaN
code,1777039267,1777039267,1777039267,1777039267
configuration,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1
experiment_run,1,1,2,2
client,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,180.00,180.00,180.00,180.00
time_ingest,84.00,84.00,84.00,84.00
time_check,96.00,96.00,96.00,96.00
terminals,0,0,0,0
pods,1,2,1,2
tenant,,,,
num_worker,0,0,0,0
type_tenants,None,None,None,None
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,3298,4482,3299,4031
host_RAM,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,
host_Cores,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,154360,155544,154360,155093
host_datadisk,3298,4482,3299,4031
host_volume_size,0,0,0,0
host_volume_used,0,0,0,0
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0
host_limits_memory,0,0,0,0
loading_parameters_HAMMERDB_NUM_VU,1,1,1,1
loading_parameters_SF,16,16,16,16
loading_parameters_HAMMERDB_DURATION,5,5,5,5
loading_parameters_HAMMERDB_RAMPUP,2,2,2,2
loading_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql
loading_parameters_HAMMERDB_VUSERS,16,16,16,16
loading_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false
loading_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true
benchmarking_parameters_HAMMERDB_NUM_VU,1,2,1,2
benchmarking_parameters_SF,16,16,16,16
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
benchmarking_parameters_HAMMERDB_DURATION,5,5,5,5
benchmarking_parameters_HAMMERDB_RAMPUP,2,2,2,2
benchmarking_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql
benchmarking_parameters_HAMMERDB_VUSERS,16,8,16,8
benchmarking_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false
benchmarking_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [19]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head().T

phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2
code,1777039267,1777039267,1777039267,1777039267
configuration,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1
experiment_run,1,1,2,2
client,1,2,1,2
type_tenants,None,None,None,None
num_tenants,0,0,0,0
vol_tenants,False,False,False,False

# Time Series of a Single Metric for All Experiments

This is particularly important if you require a customized aggregation or wish to monitor a component over time.
Data is stacked here (long format).

In [20]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_all(metric=metric)
df.head()

,timestamp,code,phase,experiment_run,client,type_tenants,vol_tenants,num_tenants,metric,component,value
0,0,1777039267,1777039267-PostgreSQL-BHT-16-1-1-1,1,1,None,False,0,total_cpu_memory,stream,7177.68
1,0,1777039267,1777039267-PostgreSQL-BHT-16-1-1-2,1,2,None,False,0,total_cpu_memory,stream,15601.66
2,0,1777039267,1777039267-PostgreSQL-BHT-16-1-2-1,2,1,None,False,0,total_cpu_memory,stream,7177.31
3,0,1777039267,1777039267-PostgreSQL-BHT-16-1-2-2,2,2,None,False,0,total_cpu_memory,stream,15082.88
4,0,1777041908,1777041908-PostgreSQL-BHT-16-1-1-1,1,1,None,False,0,total_cpu_memory,stream,7176.84

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [21]:
df[['timestamp', 'phase', 'value']].head(8)

   timestamp                               phase    value
0          0  1777039267-PostgreSQL-BHT-16-1-1-1  7177.68
1          0  1777039267-PostgreSQL-BHT-16-1-1-2 15601.66
2          0  1777039267-PostgreSQL-BHT-16-1-2-1  7177.31
3          0  1777039267-PostgreSQL-BHT-16-1-2-2 15082.88
4          0  1777041908-PostgreSQL-BHT-16-1-1-1  7176.84
5          0  1777041908-PostgreSQL-BHT-16-1-1-2 15808.93
6          0  1777041908-PostgreSQL-BHT-16-1-2-1  7176.31
7          0  1777041908-PostgreSQL-BHT-16-1-2-2 15641.20

## With Metadata

Connection infos are added.

In [22]:
df=collect.add_metadata(df)
df = df.sort_values(['timestamp', 'phase'])
df[['timestamp', 'phase', 'value']].head(8)

combine on columns phase

,timestamp,phase,value
1777039267-PostgreSQL-BHT-16-1-1-1,0,1777039267-PostgreSQL-BHT-16-1-1-1,7177.68
1777039267-PostgreSQL-BHT-16-1-1-2,0,1777039267-PostgreSQL-BHT-16-1-1-2,15601.66
1777039267-PostgreSQL-BHT-16-1-2-1,0,1777039267-PostgreSQL-BHT-16-1-2-1,7177.31
1777039267-PostgreSQL-BHT-16-1-2-2,0,1777039267-PostgreSQL-BHT-16-1-2-2,15082.88
1777041908-PostgreSQL-BHT-16-1-1-1,0,1777041908-PostgreSQL-BHT-16-1-1-1,7176.84
1777041908-PostgreSQL-BHT-16-1-1-2,0,1777041908-PostgreSQL-BHT-16-1-1-2,15808.93
1777041908-PostgreSQL-BHT-16-1-2-1,0,1777041908-PostgreSQL-BHT-16-1-2-1,7176.31
1777041908-PostgreSQL-BHT-16-1-2-2,0,1777041908-PostgreSQL-BHT-16-1-2-2,15641.20

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [23]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head().T

,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1
code,1777039267,1777039267,1777039267,1777039267,1777041908
configuration,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1
experiment_run,1,1,2,2,1
client,1,2,1,2,1
type_tenants,None,None,None,None,None
num_tenants,0,0,0,0,0
vol_tenants,False,False,False,False,False

## Custom Aggregation and Scale

We here aggregate CPU utilization by max per phase.

In [24]:
metric = 'total_cpu_util'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["code", "experiment_run", "client", "type_tenants", "num_tenants"])["value"]
      .max()
      .reset_index()
)
df_agg.index.name = 'Max ' + collect.df_metrics.loc[metric]['title']
df_agg

,code,experiment_run,client,type_tenants,num_tenants,value
Max CPU Utilization,,,,,,
0,1777039267,1,1,None,0,1.03
1,1777039267,1,2,None,0,2.01
2,1777039267,2,1,None,0,0.63
3,1777039267,2,2,None,0,1.81
4,1777041908,1,1,None,0,1.34
5,1777041908,1,2,None,0,4.95
6,1777041908,2,1,None,0,1.52
7,1777041908,2,2,None,0,23.74

# Performance Results per Connection

In [25]:
df_performance = collect.get_performance_per_connection()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

connection,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-1
connection,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-1
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-2
configuration,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
pod,gtg6k.dbmsbenchmarker,fp6kd.dbmsbenchmarker,kkbrq.dbmsbenchmarker,8pmhw.dbmsbenchmarker,5j5hd.dbmsbenchmarker,4px6h.dbmsbenchmarker,5xlmf.dbmsbenchmarker,m68zn.dbmsbenchmarker,n4nd8.dbmsbenchmarker,5jd9z.dbmsbenchmarker,77kh4.dbmsbenchmarker,5wtjc.dbmsbenchmarker
pod_count,1,2,2,1,2,2,1,2,2,1,2,2
code,1777039267,1777039267,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908,1777041908,1777041908
iterations,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000
duration,5,5,5,5,5,5,5,5,5,5,5,5
rampup,2,2,2,2,2,2,2,2,2,2,2,2
sf,16,16,16,16,16,16,16,16,16,16,16,16
run,0,0,0,0,0,0,0,0,0,0,0,0
errors,0,0,0,0,0,0,0,0,0,0,0,0
vusers_loading,1,2,2,1,2,2,1,2,2,1,2,2
vusers,16,8,8,16,8,8,32,16,16,32,16,16
efficiency,0,0,0,0,0,0,0,0,0,0,0,0
NOPM,19631,21096,21098,12003,16733,16734,23827,15516,15515,20556,17175,17172
TPM,45290,48611,48637,27756,38837,38806,54912,35819,35828,47326,39768,39774
dbms,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL
CALLS,278150.00,160976.00,138626.00,169786.00,101816.00,136910.00,336188.00,103782.00,113958.00,292300.00,111446.00,130982.00
MIN [ms],5.92,8.13,5.78,6.11,3.50,5.62,6.49,6.04,7.36,6.14,7.16,3.71
AVG [ms],19.17,18.68,19.47,20.79,20.43,19.38,20.09,20.93,20.21,20.44,20.06,19.55
MAX [ms],977.06,368.17,368.15,375.76,1054.16,1022.09,926.28,476.46,476.50,590.02,417.19,400.52
TOTAL [ms],5331340.94,3007841.52,2699234.63,3530130.88,2080109.67,2653536.11,6752879.10,2172074.74,2303580.65,5975128.88,2235465.37,2560647.56
P99 [ms],50.37,50.23,51.44,66.87,66.75,55.81,52.03,66.89,66.52,67.00,67.18,60.77
P95 [ms],33.73,33.51,33.77,34.67,33.86,33.71,34.01,34.65,33.91,33.96,33.90,33.82
P50 [ms],16.86,16.84,16.85,16.77,16.80,16.79,16.93,16.79,16.78,16.87,16.89,16.89
SD,14832.89,13372.61,14240.34,15048.81,16191.41,15752.78,17779.18,15413.85,14991.55,16595.88,17915.49,16507.22
RATIO,39.81,44.78,40.21,26.28,30.97,39.63,25.15,16.30,17.22,22.51,16.71,19.09

## With Metadata

Connection infos are added.

In [26]:
df = collect.add_metadata(df_performance)
df.T

combine on index

connection,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-1
connection,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-1
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-2
configuration,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
pod,gtg6k.dbmsbenchmarker,fp6kd.dbmsbenchmarker,kkbrq.dbmsbenchmarker,8pmhw.dbmsbenchmarker,5j5hd.dbmsbenchmarker,4px6h.dbmsbenchmarker,5xlmf.dbmsbenchmarker,m68zn.dbmsbenchmarker,n4nd8.dbmsbenchmarker,5jd9z.dbmsbenchmarker,77kh4.dbmsbenchmarker,5wtjc.dbmsbenchmarker
pod_count,1,2,2,1,2,2,1,2,2,1,2,2
code,1777039267,1777039267,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908,1777041908,1777041908
iterations,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000
duration,5,5,5,5,5,5,5,5,5,5,5,5
rampup,2,2,2,2,2,2,2,2,2,2,2,2
sf,16,16,16,16,16,16,16,16,16,16,16,16
run,0,0,0,0,0,0,0,0,0,0,0,0
errors,0,0,0,0,0,0,0,0,0,0,0,0
vusers_loading,1,2,2,1,2,2,1,2,2,1,2,2
vusers,16,8,8,16,8,8,32,16,16,32,16,16
efficiency,0,0,0,0,0,0,0,0,0,0,0,0
NOPM,19631,21096,21098,12003,16733,16734,23827,15516,15515,20556,17175,17172
TPM,45290,48611,48637,27756,38837,38806,54912,35819,35828,47326,39768,39774
dbms,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL
CALLS,278150.00,160976.00,138626.00,169786.00,101816.00,136910.00,336188.00,103782.00,113958.00,292300.00,111446.00,130982.00
MIN [ms],5.92,8.13,5.78,6.11,3.50,5.62,6.49,6.04,7.36,6.14,7.16,3.71
AVG [ms],19.17,18.68,19.47,20.79,20.43,19.38,20.09,20.93,20.21,20.44,20.06,19.55
MAX [ms],977.06,368.17,368.15,375.76,1054.16,1022.09,926.28,476.46,476.50,590.02,417.19,400.52
TOTAL [ms],5331340.94,3007841.52,2699234.63,3530130.88,2080109.67,2653536.11,6752879.10,2172074.74,2303580.65,5975128.88,2235465.37,2560647.56
P99 [ms],50.37,50.23,51.44,66.87,66.75,55.81,52.03,66.89,66.52,67.00,67.18,60.77
P95 [ms],33.73,33.51,33.77,34.67,33.86,33.71,34.01,34.65,33.91,33.96,33.90,33.82
P50 [ms],16.86,16.84,16.85,16.77,16.80,16.79,16.93,16.79,16.78,16.87,16.89,16.89
SD,14832.89,13372.61,14240.34,15048.81,16191.41,15752.78,17779.18,15413.85,14991.55,16595.88,17915.49,16507.22
RATIO,39.81,44.78,40.21,26.28,30.97,39.63,25.15,16.30,17.22,22.51,16.71,19.09
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,180.00,180.00,180.00,180.00,180.00,180.00,183.00,183.00,183.00,222.00,222.00,222.00
time_ingest,84.00,84.00,84.00,84.00,84.00,84.00,84.00,84.00,84.00,94.00,94.00,94.00
time_check,96.00,96.00,96.00,96.00,96.00,96.00,98.00,98.00,98.00,128.00,128.00,128.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,2,1,2,2,1,2,2,1,2,2
tenant,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,None,None,None,None,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,3298,4482,4482,3299,4031,4031,3298,4846,4846,3282,4642,4642
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,154360,155544,155544,154360,155093,155093,154359,155908,155908,154343,155704,155704
host_datadisk,3298,4482,4482,3299,4031,4031,3298,4846,4846,3282,4642,4642
host_volume_size,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_HAMMERDB_NUM_VU,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_SF,16,16,16,16,16,16,16,16,16,16,16,16
loading_parameters_HAMMERDB_DURATION,5,5,5,5,5,5,5,5,5,5,5,5
loading_parameters_HAMMERDB_RAMPUP,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
loading_parameters_HAMMERDB_VUSERS,16,16,16,16,16,16,16,16,16,16,16,16
loading_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false,false,false,false,false,false,false,false,false
loading_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true,true,true,true,true,true,true,true,true
benchmarking_parameters_HAMMERDB_NUM_VU,1,2,2,1,2,2,1,2,2,1,2,2
benchmarking_parameters_SF,16,16,16,16,16,16,16,16,16,16,16,16
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
benchmarking_parameters_HAMMERDB_DURATION,5,5,5,5,5,5,5,5,5,5,5,5
benchmarking_parameters_HAMMERDB_RAMPUP,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
benchmarking_parameters_HAMMERDB_VUSERS,16,8,8,16,8,8,32,16,16,32,16,16
benchmarking_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false,false,false,false,false,false,false,false,false
benchmarking_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true,true,true,true,true,true,true,true,true
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Performance Results per Phase

In [27]:
df_performance = collect.get_performance_aggregated_per_phase()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)

In [28]:
df_performance.T

,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2
configuration,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1
experiment_run,1,1,2,2,1,1,2,2
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2
client,1,2,1,2,1,2,1,2
code,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908
pod_count,1,2,1,2,1,2,1,2
iterations,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000
duration,5,5,5,5,5,5,5,5
sf,16,16,16,16,16,16,16,16
run,0,0,0,0,0,0,0,0
errors,0,0,0,0,0,0,0,0
vusers_loading,1,2,1,2,1,2,1,2
vusers,16,16,16,16,32,32,32,32
NOPM,19631.00,21097.00,12003.00,16733.50,23827.00,15515.50,20556.00,17173.50
TPM,45290.00,48624.00,27756.00,38821.50,54912.00,35823.50,47326.00,39771.00
efficiency,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
dbms,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL
CALLS,278150.00,160976.00,169786.00,136910.00,336188.00,113958.00,292300.00,130982.00
MIN [ms],5.92,8.13,6.11,5.62,6.49,7.36,6.14,7.16
AVG [ms],19.17,19.08,20.79,19.91,20.09,20.57,20.44,19.80
MAX [ms],977.06,368.17,375.76,1054.16,926.28,476.50,590.02,417.19
TOTAL [ms],5331340.94,3007841.52,3530130.88,2653536.11,6752879.10,2303580.65,5975128.88,2560647.56
P99 [ms],50.37,51.44,66.87,66.75,52.03,66.89,67.00,67.18
P95 [ms],33.73,33.77,34.67,33.86,34.01,34.65,33.96,33.90
P50 [ms],16.86,16.85,16.77,16.80,16.93,16.79,16.87,16.89

## With Metadata

Connection infos are added.

In [29]:
df = collect.add_metadata(df_performance)
df.T

combine on index and column 'phase'

phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2
configuration,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
code,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908
pod_count,1,2,1,2,1,2,1,2
iterations,10000000,10000000,10000000,10000000,10000000,10000000,10000000,10000000
duration,5,5,5,5,5,5,5,5
sf,16,16,16,16,16,16,16,16
run,0,0,0,0,0,0,0,0
errors,0,0,0,0,0,0,0,0
vusers_loading,1,2,1,2,1,2,1,2
vusers,16,16,16,16,32,32,32,32
NOPM,19631.00,21097.00,12003.00,16733.50,23827.00,15515.50,20556.00,17173.50
TPM,45290.00,48624.00,27756.00,38821.50,54912.00,35823.50,47326.00,39771.00
efficiency,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
dbms,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL
CALLS,278150.00,160976.00,169786.00,136910.00,336188.00,113958.00,292300.00,130982.00
MIN [ms],5.92,8.13,6.11,5.62,6.49,7.36,6.14,7.16
AVG [ms],19.17,19.08,20.79,19.91,20.09,20.57,20.44,19.80
MAX [ms],977.06,368.17,375.76,1054.16,926.28,476.50,590.02,417.19
TOTAL [ms],5331340.94,3007841.52,3530130.88,2653536.11,6752879.10,2303580.65,5975128.88,2560647.56
P99 [ms],50.37,51.44,66.87,66.75,52.03,66.89,67.00,67.18
P95 [ms],33.73,33.77,34.67,33.86,34.01,34.65,33.96,33.90
P50 [ms],16.86,16.85,16.77,16.80,16.93,16.79,16.87,16.89
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,180.00,180.00,180.00,180.00,183.00,183.00,222.00,222.00
time_ingest,84.00,84.00,84.00,84.00,84.00,84.00,94.00,94.00
time_check,96.00,96.00,96.00,96.00,98.00,98.00,128.00,128.00
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,3298,4482,3299,4031,3298,4846,3282,4642
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,154360,155544,154360,155093,154359,155908,154343,155704
host_datadisk,3298,4482,3299,4031,3298,4846,3282,4642
host_volume_size,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,0,0,0,0,0,0,0,0
loading_parameters_HAMMERDB_NUM_VU,1,1,1,1,1,1,1,1
loading_parameters_SF,16,16,16,16,16,16,16,16
loading_parameters_HAMMERDB_DURATION,5,5,5,5,5,5,5,5
loading_parameters_HAMMERDB_RAMPUP,2,2,2,2,2,2,2,2
loading_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
loading_parameters_HAMMERDB_VUSERS,16,16,16,16,16,16,16,16
loading_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false,false,false,false,false
loading_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true,true,true,true,true
benchmarking_parameters_HAMMERDB_NUM_VU,1,2,1,2,1,2,1,2
benchmarking_parameters_SF,16,16,16,16,16,16,16,16
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
benchmarking_parameters_HAMMERDB_DURATION,5,5,5,5,5,5,5,5
benchmarking_parameters_HAMMERDB_RAMPUP,2,2,2,2,2,2,2,2
benchmarking_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
benchmarking_parameters_HAMMERDB_VUSERS,16,8,16,8,32,16,32,16
benchmarking_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false,false,false,false,false
benchmarking_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true,true,true,true,true
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [30]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2
code,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908
configuration,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
type_tenants,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False

## Get Non-Constant Attributes

These attributes are (most probably) used to analyze performance.

In [31]:
collectors.get_non_constant(df).T

phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2
configuration,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
code,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908
pod_count,1,2,1,2,1,2,1,2
vusers_loading,1,2,1,2,1,2,1,2
vusers,16,16,16,16,32,32,32,32
NOPM,19631.00,21097.00,12003.00,16733.50,23827.00,15515.50,20556.00,17173.50
TPM,45290.00,48624.00,27756.00,38821.50,54912.00,35823.50,47326.00,39771.00
CALLS,278150.00,160976.00,169786.00,136910.00,336188.00,113958.00,292300.00,130982.00
MIN [ms],5.92,8.13,6.11,5.62,6.49,7.36,6.14,7.16
AVG [ms],19.17,19.08,20.79,19.91,20.09,20.57,20.44,19.80
MAX [ms],977.06,368.17,375.76,1054.16,926.28,476.50,590.02,417.19
TOTAL [ms],5331340.94,3007841.52,3530130.88,2653536.11,6752879.10,2303580.65,5975128.88,2560647.56
P99 [ms],50.37,51.44,66.87,66.75,52.03,66.89,67.00,67.18
P95 [ms],33.73,33.77,34.67,33.86,34.01,34.65,33.96,33.90
P50 [ms],16.86,16.85,16.77,16.80,16.93,16.79,16.87,16.89
time_load,180.00,180.00,180.00,180.00,183.00,183.00,222.00,222.00
time_ingest,84.00,84.00,84.00,84.00,84.00,84.00,94.00,94.00
time_check,96.00,96.00,96.00,96.00,98.00,98.00,128.00,128.00
pods,1,2,1,2,1,2,1,2
datadisk,3298,4482,3299,4031,3298,4846,3282,4642
host_disk,154360,155544,154360,155093,154359,155908,154343,155704
host_datadisk,3298,4482,3299,4031,3298,4846,3282,4642
benchmarking_parameters_HAMMERDB_NUM_VU,1,2,1,2,1,2,1,2
benchmarking_parameters_HAMMERDB_VUSERS,16,8,16,8,32,16,32,16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2

# Performance at Ingestion

In [32]:
df_performance = collect.get_connections()
#df_performance = collect.get_loading_time_max_all()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-2,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-2
code,1777039267,1777039267,1777039267,1777039267,1777039267,1777039267,1777041908,1777041908,1777041908,1777041908,1777041908,1777041908
connection,1777039267-PostgreSQL-BHT-16-1-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2-1,1777039267-PostgreSQL-BHT-16-1-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-1-1,1777039267-PostgreSQL-BHT-16-1-2-2-1,1777039267-PostgreSQL-BHT-16-1-2-2-2,1777041908-PostgreSQL-BHT-16-1-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-1-1,1777041908-PostgreSQL-BHT-16-1-2-2-1,1777041908-PostgreSQL-BHT-16-1-2-2-2
configuration,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1,PostgreSQL-BHT-16-1
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-1-2,1777039267-PostgreSQL-BHT-16-1-2-1,1777039267-PostgreSQL-BHT-16-1-2-2,1777039267-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-1-2,1777041908-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-2-2,1777041908-PostgreSQL-BHT-16-1-2-2
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,180.00,180.00,180.00,180.00,180.00,180.00,183.00,183.00,183.00,222.00,222.00,222.00
time_ingest,84.00,84.00,84.00,84.00,84.00,84.00,84.00,84.00,84.00,94.00,94.00,94.00
time_check,96.00,96.00,96.00,96.00,96.00,96.00,98.00,98.00,98.00,128.00,128.00,128.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,2,1,2,2,1,2,2,1,2,2
tenant,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,None,None,None,None,None,None,None,None,None,None,None,None
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,3298,4482,4482,3299,4031,4031,3298,4846,4846,3282,4642,4642
host_RAM,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,,,,,,,,,
host_Cores,64,64,64,64,64,64,64,64,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,154360,155544,155544,154360,155093,155093,154359,155908,155908,154343,155704,155704
host_datadisk,3298,4482,4482,3299,4031,4031,3298,4846,4846,3282,4642,4642
host_volume_size,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_HAMMERDB_NUM_VU,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_SF,16,16,16,16,16,16,16,16,16,16,16,16
loading_parameters_HAMMERDB_DURATION,5,5,5,5,5,5,5,5,5,5,5,5
loading_parameters_HAMMERDB_RAMPUP,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
loading_parameters_HAMMERDB_VUSERS,16,16,16,16,16,16,16,16,16,16,16,16
loading_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false,false,false,false,false,false,false,false,false
loading_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true,true,true,true,true,true,true,true,true
benchmarking_parameters_HAMMERDB_NUM_VU,1,2,2,1,2,2,1,2,2,1,2,2
benchmarking_parameters_SF,16,16,16,16,16,16,16,16,16,16,16,16
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
benchmarking_parameters_HAMMERDB_DURATION,5,5,5,5,5,5,5,5,5,5,5,5
benchmarking_parameters_HAMMERDB_RAMPUP,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
benchmarking_parameters_HAMMERDB_VUSERS,16,8,8,16,8,8,32,16,16,32,16,16
benchmarking_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false,false,false,false,false,false,false,false,false
benchmarking_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true,true,true,true,true,true,true,true,true
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Combine Performance and Monitoring

This includes filtering for the first client and incorporating efficiency metrics to track performance relative to resource usage.

In [33]:
client = 1

df_performance_monitoring = collect.get_monitoring_aggregated_per_phase(type="stream")
df_performance = collect.get_performance_aggregated_per_phase()
merged_df = pd.merge(df_performance, df_performance_monitoring, left_index=True, right_index=True, how='left')

merged_df = merged_df[merged_df['client'] == client]

#merged_df['E_Tpx'] = merged_df['Goodput (requests/second)'] / merged_df['CPU Utilization Time [s]'] * 600.
#merged_df['E_Lat'] = 1./np.sqrt(merged_df['Latency Distribution.Average Latency (microseconds)']*merged_df['CPU Utilization Time [s]']/1E6)
#merged_df['E_RAM'] = (merged_df['Goodput (requests/second)']) / merged_df['Memory Usage [MiB]']
merged_df.T

,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-2-1
configuration,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1
experiment_run,1,2,1,2
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-2-1
client,1,1,1,1
code,1777039267,1777039267,1777041908,1777041908
pod_count,1,1,1,1
iterations,10000000,10000000,10000000,10000000
duration,5,5,5,5
sf,16,16,16,16
run,0,0,0,0
errors,0,0,0,0
vusers_loading,1,1,1,1
vusers,16,16,32,32
NOPM,19631.00,12003.00,23827.00,20556.00
TPM,45290.00,27756.00,54912.00,47326.00
efficiency,0.00,0.00,0.00,0.00
dbms,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL
CALLS,278150.00,169786.00,336188.00,292300.00
MIN [ms],5.92,6.11,6.49,6.14
AVG [ms],19.17,20.79,20.09,20.44
MAX [ms],977.06,375.76,926.28,590.02
TOTAL [ms],5331340.94,3530130.88,6752879.10,5975128.88
P99 [ms],50.37,66.87,52.03,67.00
P95 [ms],33.73,34.67,34.01,33.96
P50 [ms],16.86,16.77,16.93,16.87
Memory Usage [MiB],7777.19,7558.01,7976.66,7910.65
Memory Usage Cached [MiB],8552.64,8309.08,8832.62,8728.59
CPU Utilization,0.87,0.57,1.17,1.28
CPU Throttle,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00
CPU Utilization Time [s],389.77,261.09,538.01,596.33
CPU User Time [s],326.40,212.53,436.96,500.50
CPU System Time [s],63.37,48.56,101.05,95.83
Network Rx Total [MiB],94.19,61.90,120.24,104.97
Network Tx Total [MiB],1064.29,936.34,1066.13,1079.82
Filesystem Read Total [MiB],0.04,0.02,0.14,0.02
Filesystem Write Total [MiB],2373.79,1626.95,3154.14,2712.57
Core Utilization Variance [%],0.23,0.17,0.20,0.17
Max Core Utilization [%],3.26,2.25,2.65,2.71
I/O Wait [%],35.31,40.30,32.68,31.67
Total I/O Wait Time [s],412.76,416.70,411.15,393.00
Number of Idle Sessions,1.33,1.12,1.56,1.60
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00
Number of Active Sessions,17.00,16.00,32.00,32.00
Number of Active Application Sessions,0.00,0.00,0.00,0.00
Longest Active Transaction,0.03,0.08,0.32,0.22
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.99,1.00,0.99,0.96
Active Backends Waiting on WAL,10.58,6.61,13.44,11.94
Active Backends Waiting on Locks,3.01,7.39,14.69,16.23
Max Transaction Duration (I/O Wait),0.01,0.01,0.02,0.01
Max Transaction Duration (WAL Wait),0.03,0.07,0.17,0.13
Max Transaction Duration (Lock Wait),0.01,0.06,0.29,0.21
Disk Blocks Read Count,28399.00,15958.00,26420.00,24432.00
Buffer Cache Hit Count,49064412.00,38856965.00,68089848.00,75181391.00
Buffer Cache Hit Ratio,1.00,1.00,1.00,1.00
Index Scan Count,0.00,0.00,0.00,0.00
Index Tuple Fetch Count,0.00,0.00,0.00,0.00
Index Cache Hit Ratio,0.00,0.00,0.00,0.00
Table Buffer Hit Count,0.00,0.00,0.00,0.00
Table Blocks Read Count,0.00,0.00,0.00,0.00
Table Cache Hit Ratio,0.00,0.00,0.00,0.00
Total Cache Hit Ratio,0.00,0.00,0.00,0.00
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00
Total Locks Current,128.69,94.19,188.04,174.45
AccessExclusiveLocks Current,0.00,0.09,0.00,0.02
AccessShareLocks Current,45.61,28.25,55.85,50.67
ExclusiveLocks Current,2.85,4.93,9.93,10.47
RowExclusiveLocks Current,80.22,60.92,122.26,113.29
RowShareLocks Current,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],0.00,0.00,0.00,0.00
Number of WAL Segments,134.57,123.89,143.81,138.17
Total WAL Size [GiB],2.10,1.94,2.25,2.16
WAL Segments Growth Rate [segments/s],0.24,0.21,0.27,0.23
WAL Growth Rate [MiB/s],3.89,3.43,4.26,3.71
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00

## With Metadata

Connection infos are added.

In [34]:
df = collect.add_metadata(merged_df)
df.T

combine on index and column 'phase'

phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-2-1
configuration,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1
experiment_run,1,2,1,2
client,1,1,1,1
code,1777039267,1777039267,1777041908,1777041908
pod_count,1,1,1,1
iterations,10000000,10000000,10000000,10000000
duration,5,5,5,5
sf,16,16,16,16
run,0,0,0,0
errors,0,0,0,0
vusers_loading,1,1,1,1
vusers,16,16,32,32
NOPM,19631.00,12003.00,23827.00,20556.00
TPM,45290.00,27756.00,54912.00,47326.00
efficiency,0.00,0.00,0.00,0.00
dbms,PostgreSQL,PostgreSQL,PostgreSQL,PostgreSQL
CALLS,278150.00,169786.00,336188.00,292300.00
MIN [ms],5.92,6.11,6.49,6.14
AVG [ms],19.17,20.79,20.09,20.44
MAX [ms],977.06,375.76,926.28,590.02
TOTAL [ms],5331340.94,3530130.88,6752879.10,5975128.88
P99 [ms],50.37,66.87,52.03,67.00
P95 [ms],33.73,34.67,34.01,33.96
P50 [ms],16.86,16.77,16.93,16.87
Memory Usage [MiB],7777.19,7558.01,7976.66,7910.65
Memory Usage Cached [MiB],8552.64,8309.08,8832.62,8728.59
CPU Utilization,0.87,0.57,1.17,1.28
CPU Throttle,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00
CPU Utilization Time [s],389.77,261.09,538.01,596.33
CPU User Time [s],326.40,212.53,436.96,500.50
CPU System Time [s],63.37,48.56,101.05,95.83
Network Rx Total [MiB],94.19,61.90,120.24,104.97
Network Tx Total [MiB],1064.29,936.34,1066.13,1079.82
Filesystem Read Total [MiB],0.04,0.02,0.14,0.02
Filesystem Write Total [MiB],2373.79,1626.95,3154.14,2712.57
Core Utilization Variance [%],0.23,0.17,0.20,0.17
Max Core Utilization [%],3.26,2.25,2.65,2.71
I/O Wait [%],35.31,40.30,32.68,31.67
Total I/O Wait Time [s],412.76,416.70,411.15,393.00
Number of Idle Sessions,1.33,1.12,1.56,1.60
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00
Number of Active Sessions,17.00,16.00,32.00,32.00
Number of Active Application Sessions,0.00,0.00,0.00,0.00
Longest Active Transaction,0.03,0.08,0.32,0.22
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.99,1.00,0.99,0.96
Active Backends Waiting on WAL,10.58,6.61,13.44,11.94
Active Backends Waiting on Locks,3.01,7.39,14.69,16.23
Max Transaction Duration (I/O Wait),0.01,0.01,0.02,0.01
Max Transaction Duration (WAL Wait),0.03,0.07,0.17,0.13
Max Transaction Duration (Lock Wait),0.01,0.06,0.29,0.21
Disk Blocks Read Count,28399.00,15958.00,26420.00,24432.00
Buffer Cache Hit Count,49064412.00,38856965.00,68089848.00,75181391.00
Buffer Cache Hit Ratio,1.00,1.00,1.00,1.00
Index Scan Count,0.00,0.00,0.00,0.00
Index Tuple Fetch Count,0.00,0.00,0.00,0.00
Index Cache Hit Ratio,0.00,0.00,0.00,0.00
Table Buffer Hit Count,0.00,0.00,0.00,0.00
Table Blocks Read Count,0.00,0.00,0.00,0.00
Table Cache Hit Ratio,0.00,0.00,0.00,0.00
Total Cache Hit Ratio,0.00,0.00,0.00,0.00
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00
Total Locks Current,128.69,94.19,188.04,174.45
AccessExclusiveLocks Current,0.00,0.09,0.00,0.02
AccessShareLocks Current,45.61,28.25,55.85,50.67
ExclusiveLocks Current,2.85,4.93,9.93,10.47
RowExclusiveLocks Current,80.22,60.92,122.26,113.29
RowShareLocks Current,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],0.00,0.00,0.00,0.00
Number of WAL Segments,134.57,123.89,143.81,138.17
Total WAL Size [GiB],2.10,1.94,2.25,2.16
WAL Segments Growth Rate [segments/s],0.24,0.21,0.27,0.23
WAL Growth Rate [MiB/s],3.89,3.43,4.26,3.71
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,180.00,180.00,183.00,222.00
time_ingest,84.00,84.00,84.00,94.00
time_check,96.00,96.00,98.00,128.00
terminals,0,0,0,0
pods,1,1,1,1
tenant,,,,
num_worker,0,0,0,0
type_tenants,None,None,None,None
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,3298,3299,3298,3282
host_RAM,541008474112,541008474112,541008474112,541008474112
host_CPU,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378,AMD Opteron(tm) Processor 6378
host_GPU,,,,
host_Cores,64,64,64,64
host_host,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic,5.15.0-164-generic
host_node,cl-worker14,cl-worker14,cl-worker14,cl-worker14
host_disk,154360,154360,154359,154343
host_datadisk,3298,3299,3298,3282
host_volume_size,0,0,0,0
host_volume_used,0,0,0,0
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-63,0-63,0-63,0-63
host_requests_cpu,4,4,4,4
host_requests_memory,16Gi,16Gi,16Gi,16Gi
host_limits_cpu,0,0,0,0
host_limits_memory,0,0,0,0
loading_parameters_HAMMERDB_NUM_VU,1,1,1,1
loading_parameters_SF,16,16,16,16
loading_parameters_HAMMERDB_DURATION,5,5,5,5
loading_parameters_HAMMERDB_RAMPUP,2,2,2,2
loading_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql
loading_parameters_HAMMERDB_VUSERS,16,16,16,16
loading_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false
loading_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true
benchmarking_parameters_HAMMERDB_NUM_VU,1,1,1,1
benchmarking_parameters_SF,16,16,16,16
benchmarking_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
benchmarking_parameters_HAMMERDB_DURATION,5,5,5,5
benchmarking_parameters_HAMMERDB_RAMPUP,2,2,2,2
benchmarking_parameters_HAMMERDB_TYPE,postgresql,postgresql,postgresql,postgresql
benchmarking_parameters_HAMMERDB_VUSERS,16,16,32,32
benchmarking_parameters_HAMMERDB_KEYANDTHINK,false,false,false,false
benchmarking_parameters_HAMMERDB_TIMEPROFILE,true,true,true,true
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16,bexhoma-worker-postgresql-hammerdb-16
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777039267,bexhoma-sut-postgresql-bht-16-1-1777041908,bexhoma-sut-postgresql-bht-16-1-1777041908
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-2-1

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [35]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-2-1
phase,1777039267-PostgreSQL-BHT-16-1-1-1,1777039267-PostgreSQL-BHT-16-1-2-1,1777041908-PostgreSQL-BHT-16-1-1-1,1777041908-PostgreSQL-BHT-16-1-2-1
code,1777039267,1777039267,1777041908,1777041908
configuration,1777039267-PostgreSQL-BHT-16-1,1777039267-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1,1777041908-PostgreSQL-BHT-16-1
experiment_run,1,2,1,2
client,1,1,1,1
type_tenants,None,None,None,None
num_tenants,0,0,0,0
vol_tenants,False,False,False,False

In [36]:
zip_all_results(path, codes)

Zipping /data/benchmarks/1777039267 to /data/benchmarks/1777039267.zip...
Zipping /data/benchmarks/1777041908 to /data/benchmarks/1777041908.zip...
✅ Done zipping all folders.