# TPC-H Collector Demo

In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option('display.max_colwidth', None)
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.float_format = '{:.2f}'.format

from bexhoma import collectors

%matplotlib inline

## Functions for Nice Plots

In [2]:
from notebookutils import *

# Collect Results

In [3]:
#path = r"D:\data\benchmarks"
path = r"/data/benchmarks"
filename_prefix = "demo_"
b_plot_save = False
b_skip_plots = True

In [4]:
codes = [
    "1776765494",
    "1776766994"
]

codes

['1776765494', '1776766994']

In [5]:
collect = collectors.dbmsbenchmarker(path, codes)

# Get all Metrics Metadata

## Metrics Names and Types

Metrics that are derived from monitoring

In [6]:
collect.get_metrics_metadata()

,title,active,type,metric
total_cpu_memory,Memory Usage [MiB],True,cluster,gauge
total_cpu_memory_cached,Memory Usage Cached [MiB],True,cluster,gauge
total_cpu_util,CPU Utilization,True,cluster,gauge
total_cpu_throttled,CPU Throttle,True,cluster,gauge
total_cpu_throttled_s,CPU Throttled Time [s],True,cluster,counter
total_cpu_util_others,CPU Utilization Others,False,cluster,gauge
total_cpu_util_s,CPU Utilization Time [s],True,cluster,counter
total_cpu_util_user_s,CPU User Time [s],True,cluster,counter
total_cpu_util_sys_s,CPU System Time [s],True,cluster,counter
total_cpu_util_others_s,CPU Utilization Time Others [s],False,cluster,counter
total_network_rx,Network Rx Total [MiB],True,cluster,counter
total_network_tx,Network Tx Total [MiB],True,cluster,counter
total_fs_read,Filesystem Read Total [MiB],True,cluster,counter
total_fs_write,Filesystem Write Total [MiB],True,cluster,counter
total_gpu_util,GPU Utilization [%],False,cluster,gauge
total_gpu_power,GPU Power Usage [W],False,cluster,gauge
total_gpu_memory,GPU Memory Usage [MiB],False,cluster,gauge
core_variance,Core Utilization Variance [%],True,cluster,ratio
max_core_util,Max Core Utilization [%],True,cluster,ratio
io_wait_pct,I/O Wait [%],True,cluster,ratio
io_wait_total,Total I/O Wait Time [s],True,cluster,counter
pg_stat_activity_count_idle,Number of Idle Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction,Number of Idle-in-transaction Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction_aborted,Number of Idle-in-transaction Aborted Sessions,True,application,gauge
pg_stat_activity_count_active,Number of Active Sessions,True,application,counter
pg_stat_activity_count_active_app,Number of Active Application Sessions,True,application,counter
pg_stat_activity_max_tx_duration_active,Longest Active Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle,Longest Idle Session (no transaction),True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx,Longest Idle-in-Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx_aborted,Longest Idle-in-Transaction (Aborted),True,application,ratio
pg_stat_activity_count_io,Active Backends Waiting on I/O,True,application,gauge
pg_stat_activity_count_wal,Active Backends Waiting on WAL,True,application,gauge
pg_stat_activity_count_lock,Active Backends Waiting on Locks,True,application,gauge
pg_stat_activity_max_tx_duration_io,Max Transaction Duration (I/O Wait),True,application,ratio
pg_stat_activity_max_tx_duration_wal,Max Transaction Duration (WAL Wait),True,application,ratio
pg_stat_activity_max_tx_duration_lock,Max Transaction Duration (Lock Wait),True,application,ratio
pg_stat_database_blks_read,Disk Blocks Read Count,True,application,counter
pg_stat_database_blks_hit,Buffer Cache Hit Count,True,application,counter
cache_hit_ratio,Buffer Cache Hit Ratio,True,application,ratio
pg_stat_user_tables_idx_scan,Index Scan Count,True,application,counter
pg_stat_user_tables_idx_tup_fetch,Index Tuple Fetch Count,True,application,counter
pg_statio_user_tables_idx_cache_hit_ratio,Index Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_heap_blocks_hit,Table Buffer Hit Count,True,application,counter
pg_statio_user_tables_heap_blocks_read,Table Blocks Read Count,True,application,counter
pg_statio_user_tables_heap_cache_hit_ratio,Table Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_total_cache_hit_ratio,Total Cache Hit Ratio,True,application,ratio
pg_stat_bgwriter_efficiency_ratio,BGWriter Efficiency Ratio (Cleaned / Allocated),True,application,ratio
pg_stat_bgwriter_maxwritten_clean_total,BGWriter Stopped Due to Max Pages,True,application,counter
pg_stat_bgwriter_checkpoint_sync_time_total,Checkpoint Sync Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_total,Checkpoint Write Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_per_sync_time,Time spent writing vs syncing during checkpoints [ratio],False,application,ratio
pg_locks_count,Total Locks Current,True,application,gauge
pg_locks_count_accessexclusivelock,AccessExclusiveLocks Current,True,application,gauge
pg_locks_count_accesssharelock,AccessShareLocks Current,True,application,gauge
pg_locks_count_exclusivelock,ExclusiveLocks Current,True,application,gauge
pg_locks_count_rowexclusivelock,RowExclusiveLocks Current,True,application,gauge
pg_locks_count_rowsharelock,RowShareLocks Current,True,application,gauge
pg_locks_count_sharelock,ShareLocks Current,True,application,gauge
pg_locks_count_sharerowexclusivelock,ShareRowExclusiveLocks Current,True,application,gauge
pg_locks_count_shareupdateexclusivelock,ShareUpdateExclusiveLocks Current,True,application,gauge
pg_locks_count_sireadlock,SIReadLocks Current,True,application,gauge
pg_stat_user_tables_autoanalyze_count,Autoanalyze Run Count,True,application,counter
pg_stat_user_tables_autovacuum_count,Autovacuum Run Count,True,application,counter
pg_stat_bgwriter_checkpoints_timed_per_req,Frequency of checkpoints (timed vs requested) [ratio],False,application,gauge
pg_stat_wal_volume_bytes_sec,Volume of WAL generated [bytes/sec],False,application,counter
pg_stat_bgwriter_buffers_backend_fsync,Backends forced to flush WAL (I/O contention) [fsync/sec],False,application,counter
pg_stat_activity_wait_event_count,Active sessions waiting on any event [count],False,application,gauge
pg_stat_user_tables_dead_tuples_per_vacuum,Dead tuples per vacuum operation [tuples/vacuum],True,application,ratio
pg_wal_segments,Number of WAL Segments,True,application,gauge
pg_wal_size_bytes,Total WAL Size [GiB],True,application,gauge
pg_wal_segments_rate,WAL Segments Growth Rate [segments/s],True,application,gauge
pg_wal_size_rate,WAL Growth Rate [MiB/s],True,application,gauge
pg_wal_avg_segment_size,Average WAL Segment Size [MiB],True,application,gauge
pg_wal_size_per_checkpoint,WAL Size per Checkpoint [bytes/checkpoint],False,application,gauge

## Names of Monitored Components

Names of components and their phases

In [7]:
collect.get_monitored_components()

                                           description
loading                  Loading phase: SUT deployment
datagenerator  Loading phase: component data generator
loader                 Loading phase: component loader
stream                 Execution phase: SUT deployment
benchmarker     Execution phase: component benchmarker

# Get Connection Infos

List of states of SUTs, containing loading infos.

In [8]:
df=collect.get_connections()

In [9]:
df.T

,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
code,1776765494,1776765494,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994,1776766994,1776766994
connection,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-1,PostgreSQL-BHT-8-2-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-1,PostgreSQL-BHT-8-2-2-2
configuration,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-2-2
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,490.00,490.00,490.00,490.00,490.00,490.00,916.00,916.00,916.00,916.00,916.00,916.00
time_ingest,182.00,182.00,182.00,182.00,182.00,182.00,326.00,326.00,326.00,326.00,326.00,326.00
time_check,287.00,287.00,287.00,287.00,287.00,287.00,566.00,566.00,566.00,566.00,566.00,566.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,2,1,2,2,1,2,2,1,2,2
tenant,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247624,247624,247624,247625,247625,247625,247626,247627,247627,247627,247627,247627
host_datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G
host_cuda,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [10]:
df[['phase', 'code', 'connection', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-2-2
code,1776765494,1776765494,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994,1776766994,1776766994
connection,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-1,PostgreSQL-BHT-8-2-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-1,PostgreSQL-BHT-8-2-2-2
configuration,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
type_tenants,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False

## Get Non-Constant Attributes

These attributes are (most probably) used to analyze performance.

In [11]:
collectors.get_non_constant(df).T

,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
code,1776765494,1776765494,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994,1776766994,1776766994
connection,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-1,PostgreSQL-BHT-8-2-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-1,PostgreSQL-BHT-8-2-2-2
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-2-2
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
time_load,490.00,490.00,490.00,490.00,490.00,490.00,916.00,916.00,916.00,916.00,916.00,916.00
time_ingest,182.00,182.00,182.00,182.00,182.00,182.00,326.00,326.00,326.00,326.00,326.00,326.00
time_check,287.00,287.00,287.00,287.00,287.00,287.00,566.00,566.00,566.00,566.00,566.00,566.00
pods,1,2,2,1,2,2,1,2,2,1,2,2
datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_disk,247624,247624,247624,247625,247625,247625,247626,247627,247627,247627,247627,247627
host_datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G
loading_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
benchmarking_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994

# Monitoring Aggregated per Phase

In [12]:
df = collect.get_monitoring_aggregated_per_phase("stream")
df.T

,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2
Memory Usage [MiB],9964.58,11069.47,8863.34,10465.23,15519.58,15065.88,14324.21,14953.71
Memory Usage Cached [MiB],15199.53,15991.72,12041.66,14951.36,25325.03,24871.33,23173.83,23872.43
CPU Utilization,0.77,1.25,0.55,1.41,2.45,3.08,1.11,3.29
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],28.32,146.36,503.46,78.27,211.14,220.96,1159.54,223.10
CPU User Time [s],24.50,125.51,408.16,66.48,183.88,192.20,960.20,194.84
CPU System Time [s],3.82,20.84,95.30,11.79,27.26,28.76,199.34,28.27
Network Rx Total [MiB],0.17,0.12,3297.65,3.34,25.98,3.76,6633.34,3.67
Network Tx Total [MiB],1.69,3.39,18.54,0.06,6118.60,3.80,36.02,0.50
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.00,0.03,0.00,0.00,0.00,0.03,0.00
Core Utilization Variance [%],0.02,0.02,0.06,0.11,0.13,0.08,0.07,0.16
Max Core Utilization [%],0.60,1.04,1.92,2.71,16.95,8.00,3.35,5.58
I/O Wait [%],17.29,7.22,21.65,35.08,4.72,1.35,31.68,38.16
Total I/O Wait Time [s],0.08,0.61,388.56,0.48,1.61,1.35,554.48,2.28
Number of Idle Sessions,0.00,0.47,0.00,0.00,0.00,0.00,0.38,0.40
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,5.00,9.00,8.00,0.00,7.00,12.00,8.00,13.00
Number of Active Application Sessions,5.00,8.00,7.00,0.00,7.00,12.00,7.00,12.00
Longest Active Transaction,0.32,0.48,4.86,-0.00,0.70,1.89,13.34,1.66
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,0.00,3.24,0.00,0.00,0.00,3.19,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,0.00,4.74,0.00,0.00,0.00,12.88,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,68984.00,0.00,561627.00,0.00,137906.00,0.00,2181250.00,0.00
Buffer Cache Hit Count,12956982.00,19711402.00,12472471.00,3081.00,25969997.00,52209632.00,286713764.00,52209632.00
Buffer Cache Hit Ratio,0.92,0.98,0.50,0.97,0.99,1.00,0.99,0.99
Index Scan Count,1673169.00,3117120.00,1673169.00,0.00,3373563.00,6747126.00,53146522.00,6747126.00
Index Tuple Fetch Count,7833740.00,13960206.00,7833740.00,0.00,15770780.00,31541560.00,106246548.00,31541560.00
Index Cache Hit Ratio,0.47,0.99,0.46,0.99,1.00,1.00,0.99,1.00
Table Buffer Hit Count,8029090.00,10430416.00,7536844.00,0.00,16054133.00,32108266.00,127702974.00,32108266.00
Table Blocks Read Count,0.00,0.00,492246.00,0.00,0.00,0.00,1885806.00,0.00
Table Cache Hit Ratio,0.92,0.98,0.29,0.96,0.98,0.99,0.98,0.99
Total Cache Hit Ratio,0.92,0.98,0.30,0.97,0.99,1.00,0.99,0.99
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,4.35,28.03,16.91,1.94,16.92,29.33,23.21,17.00
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,4.35,28.03,16.91,1.94,16.92,29.33,23.21,17.00
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN
Number of WAL Segments,205.00,205.00,190.93,205.00,410.00,410.00,407.44,410.00
Total WAL Size [GiB],3.20,3.20,2.98,3.20,6.41,6.41,6.37,6.41
WAL Segments Growth Rate [segments/s],0.68,0.24,0.00,0.00,0.10,0.00,0.00,0.00
WAL Growth Rate [MiB/s],10.93,3.78,0.00,0.00,1.56,0.00,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,14.90,16.00,16.00,16.00,15.90,16.00

## With Metadata

Connection infos are added.

In [13]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2
Memory Usage [MiB],9964.58,11069.47,8863.34,10465.23,15519.58,15065.88,14324.21,14953.71
Memory Usage Cached [MiB],15199.53,15991.72,12041.66,14951.36,25325.03,24871.33,23173.83,23872.43
CPU Utilization,0.77,1.25,0.55,1.41,2.45,3.08,1.11,3.29
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],28.32,146.36,503.46,78.27,211.14,220.96,1159.54,223.10
CPU User Time [s],24.50,125.51,408.16,66.48,183.88,192.20,960.20,194.84
CPU System Time [s],3.82,20.84,95.30,11.79,27.26,28.76,199.34,28.27
Network Rx Total [MiB],0.17,0.12,3297.65,3.34,25.98,3.76,6633.34,3.67
Network Tx Total [MiB],1.69,3.39,18.54,0.06,6118.60,3.80,36.02,0.50
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.00,0.03,0.00,0.00,0.00,0.03,0.00
Core Utilization Variance [%],0.02,0.02,0.06,0.11,0.13,0.08,0.07,0.16
Max Core Utilization [%],0.60,1.04,1.92,2.71,16.95,8.00,3.35,5.58
I/O Wait [%],17.29,7.22,21.65,35.08,4.72,1.35,31.68,38.16
Total I/O Wait Time [s],0.08,0.61,388.56,0.48,1.61,1.35,554.48,2.28
Number of Idle Sessions,0.00,0.47,0.00,0.00,0.00,0.00,0.38,0.40
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,5.00,9.00,8.00,0.00,7.00,12.00,8.00,13.00
Number of Active Application Sessions,5.00,8.00,7.00,0.00,7.00,12.00,7.00,12.00
Longest Active Transaction,0.32,0.48,4.86,-0.00,0.70,1.89,13.34,1.66
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,0.00,3.24,0.00,0.00,0.00,3.19,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,0.00,4.74,0.00,0.00,0.00,12.88,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,68984.00,0.00,561627.00,0.00,137906.00,0.00,2181250.00,0.00
Buffer Cache Hit Count,12956982.00,19711402.00,12472471.00,3081.00,25969997.00,52209632.00,286713764.00,52209632.00
Buffer Cache Hit Ratio,0.92,0.98,0.50,0.97,0.99,1.00,0.99,0.99
Index Scan Count,1673169.00,3117120.00,1673169.00,0.00,3373563.00,6747126.00,53146522.00,6747126.00
Index Tuple Fetch Count,7833740.00,13960206.00,7833740.00,0.00,15770780.00,31541560.00,106246548.00,31541560.00
Index Cache Hit Ratio,0.47,0.99,0.46,0.99,1.00,1.00,0.99,1.00
Table Buffer Hit Count,8029090.00,10430416.00,7536844.00,0.00,16054133.00,32108266.00,127702974.00,32108266.00
Table Blocks Read Count,0.00,0.00,492246.00,0.00,0.00,0.00,1885806.00,0.00
Table Cache Hit Ratio,0.92,0.98,0.29,0.96,0.98,0.99,0.98,0.99
Total Cache Hit Ratio,0.92,0.98,0.30,0.97,0.99,1.00,0.99,0.99
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,4.35,28.03,16.91,1.94,16.92,29.33,23.21,17.00
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,4.35,28.03,16.91,1.94,16.92,29.33,23.21,17.00
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN
Number of WAL Segments,205.00,205.00,190.93,205.00,410.00,410.00,407.44,410.00
Total WAL Size [GiB],3.20,3.20,2.98,3.20,6.41,6.41,6.37,6.41
WAL Segments Growth Rate [segments/s],0.68,0.24,0.00,0.00,0.10,0.00,0.00,0.00
WAL Growth Rate [MiB/s],10.93,3.78,0.00,0.00,1.56,0.00,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,14.90,16.00,16.00,16.00,15.90,16.00
code,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994
configuration,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,490.00,490.00,490.00,490.00,916.00,916.00,916.00,916.00
time_ingest,182.00,182.00,182.00,182.00,326.00,326.00,326.00,326.00
time_check,287.00,287.00,287.00,287.00,566.00,566.00,566.00,566.00
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247624,247624,247625,247625,247626,247627,247627,247627
host_datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [14]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2
code,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994
configuration,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False

# Time Series of a Single Metric for a Single Experiment

This is particularly important if you require a customized aggregation or wish to monitor a component over time.

In [15]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_per_phase(code, metric=metric, component='stream')
df.T

,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2
0,9749.37,10308.81,10308.82,10302.90
1,9749.37,10308.81,10308.82,10302.90
2,9749.37,10308.81,10308.82,10302.90
3,9749.37,10308.81,10308.82,10302.90
4,9749.37,10308.82,10308.82,10302.90
5,9749.37,10308.82,10308.82,10302.90
6,9749.37,10308.82,10308.82,10302.90
7,9749.37,10308.82,10308.82,10302.90
8,9749.37,10308.82,10308.82,10302.90
9,9749.37,10308.82,10308.82,10302.90
10,9749.37,10308.82,10308.82,10302.90
11,9749.37,10308.82,10308.82,10302.90
12,10100.50,10308.82,10308.82,10567.76
13,10100.50,10308.82,10308.82,10567.76
14,10100.50,10308.82,10308.82,10567.76
15,10100.50,10308.82,10308.82,10567.76
16,10100.50,10308.82,10308.82,10567.76
17,10100.50,10308.82,10308.82,10567.76
18,10100.50,10308.82,10308.82,10567.76
19,10100.50,10308.82,10308.82,10567.76
20,10100.50,10308.82,7230.42,10567.76
21,10100.50,10308.82,7230.42,10567.76
22,10100.50,10308.82,7230.42,10567.76
23,10100.50,10308.82,7230.42,10567.76
24,10100.50,10308.82,7230.42,10567.76
25,10100.50,10308.82,7230.42,10567.76
26,10100.50,14365.66,7230.42,10567.76
27,10100.50,14365.66,7230.42,10567.76
28,10100.50,14365.66,7230.42,10567.76
29,10100.50,14365.66,7230.42,10567.76
30,10100.50,14365.66,7230.42,10567.76
31,NaN,14365.66,7230.42,NaN
32,NaN,NaN,7230.42,NaN
33,NaN,NaN,7230.42,NaN
34,NaN,NaN,7230.42,NaN
35,NaN,NaN,7230.42,NaN
36,NaN,NaN,7230.42,NaN
37,NaN,NaN,7230.42,NaN
38,NaN,NaN,7230.42,NaN
39,NaN,NaN,7230.42,NaN
40,NaN,NaN,7230.42,NaN
41,NaN,NaN,7230.42,NaN
42,NaN,NaN,7230.42,NaN
43,NaN,NaN,7230.42,NaN
44,NaN,NaN,7230.42,NaN
45,NaN,NaN,7230.42,NaN
46,NaN,NaN,8639.52,NaN
47,NaN,NaN,8639.52,NaN
48,NaN,NaN,8639.52,NaN
49,NaN,NaN,8639.52,NaN
50,NaN,NaN,8639.52,NaN
51,NaN,NaN,8639.52,NaN
52,NaN,NaN,8639.52,NaN
53,NaN,NaN,8639.52,NaN
54,NaN,NaN,8639.52,NaN
55,NaN,NaN,8639.52,NaN
56,NaN,NaN,8639.52,NaN
57,NaN,NaN,8639.52,NaN
58,NaN,NaN,8639.52,NaN
59,NaN,NaN,8639.52,NaN
60,NaN,NaN,8639.52,NaN
61,NaN,NaN,8639.52,NaN
62,NaN,NaN,8639.52,NaN
63,NaN,NaN,8639.52,NaN
64,NaN,NaN,8639.52,NaN
65,NaN,NaN,8639.52,NaN
66,NaN,NaN,8639.52,NaN
67,NaN,NaN,8639.52,NaN
68,NaN,NaN,8639.52,NaN
69,NaN,NaN,8639.52,NaN
70,NaN,NaN,8639.52,NaN
71,NaN,NaN,8639.52,NaN
72,NaN,NaN,8639.52,NaN
73,NaN,NaN,8639.52,NaN
74,NaN,NaN,8639.52,NaN
75,NaN,NaN,8639.52,NaN
76,NaN,NaN,8639.52,NaN
77,NaN,NaN,8639.52,NaN
78,NaN,NaN,8639.52,NaN
79,NaN,NaN,8639.52,NaN
80,NaN,NaN,8639.52,NaN
81,NaN,NaN,8639.52,NaN
82,NaN,NaN,8639.52,NaN
83,NaN,NaN,8639.52,NaN
84,NaN,NaN,8639.52,NaN
85,NaN,NaN,8639.52,NaN
86,NaN,NaN,8639.52,NaN
87,NaN,NaN,10378.18,NaN
88,NaN,NaN,10378.18,NaN
89,NaN,NaN,10378.18,NaN
90,NaN,NaN,10378.18,NaN
91,NaN,NaN,10378.18,NaN
92,NaN,NaN,10378.18,NaN
93,NaN,NaN,10378.18,NaN
94,NaN,NaN,10378.18,NaN
95,NaN,NaN,10378.18,NaN
96,NaN,NaN,10378.18,NaN
97,NaN,NaN,10378.18,NaN
98,NaN,NaN,10378.18,NaN
99,NaN,NaN,10378.18,NaN
100,NaN,NaN,10378.18,NaN
101,NaN,NaN,10378.18,NaN

## With Metadata

Connection infos are added.

In [16]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2
0,9749.37,10308.81,10308.82,10302.90
1,9749.37,10308.81,10308.82,10302.90
2,9749.37,10308.81,10308.82,10302.90
3,9749.37,10308.81,10308.82,10302.90
4,9749.37,10308.82,10308.82,10302.90
5,9749.37,10308.82,10308.82,10302.90
6,9749.37,10308.82,10308.82,10302.90
7,9749.37,10308.82,10308.82,10302.90
8,9749.37,10308.82,10308.82,10302.90
9,9749.37,10308.82,10308.82,10302.90
10,9749.37,10308.82,10308.82,10302.90
11,9749.37,10308.82,10308.82,10302.90
12,10100.50,10308.82,10308.82,10567.76
13,10100.50,10308.82,10308.82,10567.76
14,10100.50,10308.82,10308.82,10567.76
15,10100.50,10308.82,10308.82,10567.76
16,10100.50,10308.82,10308.82,10567.76
17,10100.50,10308.82,10308.82,10567.76
18,10100.50,10308.82,10308.82,10567.76
19,10100.50,10308.82,10308.82,10567.76
20,10100.50,10308.82,7230.42,10567.76
21,10100.50,10308.82,7230.42,10567.76
22,10100.50,10308.82,7230.42,10567.76
23,10100.50,10308.82,7230.42,10567.76
24,10100.50,10308.82,7230.42,10567.76
25,10100.50,10308.82,7230.42,10567.76
26,10100.50,14365.66,7230.42,10567.76
27,10100.50,14365.66,7230.42,10567.76
28,10100.50,14365.66,7230.42,10567.76
29,10100.50,14365.66,7230.42,10567.76
30,10100.50,14365.66,7230.42,10567.76
31,NaN,14365.66,7230.42,NaN
32,NaN,NaN,7230.42,NaN
33,NaN,NaN,7230.42,NaN
34,NaN,NaN,7230.42,NaN
35,NaN,NaN,7230.42,NaN
36,NaN,NaN,7230.42,NaN
37,NaN,NaN,7230.42,NaN
38,NaN,NaN,7230.42,NaN
39,NaN,NaN,7230.42,NaN
40,NaN,NaN,7230.42,NaN
41,NaN,NaN,7230.42,NaN
42,NaN,NaN,7230.42,NaN
43,NaN,NaN,7230.42,NaN
44,NaN,NaN,7230.42,NaN
45,NaN,NaN,7230.42,NaN
46,NaN,NaN,8639.52,NaN
47,NaN,NaN,8639.52,NaN
48,NaN,NaN,8639.52,NaN
49,NaN,NaN,8639.52,NaN
50,NaN,NaN,8639.52,NaN
51,NaN,NaN,8639.52,NaN
52,NaN,NaN,8639.52,NaN
53,NaN,NaN,8639.52,NaN
54,NaN,NaN,8639.52,NaN
55,NaN,NaN,8639.52,NaN
56,NaN,NaN,8639.52,NaN
57,NaN,NaN,8639.52,NaN
58,NaN,NaN,8639.52,NaN
59,NaN,NaN,8639.52,NaN
60,NaN,NaN,8639.52,NaN
61,NaN,NaN,8639.52,NaN
62,NaN,NaN,8639.52,NaN
63,NaN,NaN,8639.52,NaN
64,NaN,NaN,8639.52,NaN
65,NaN,NaN,8639.52,NaN
66,NaN,NaN,8639.52,NaN
67,NaN,NaN,8639.52,NaN
68,NaN,NaN,8639.52,NaN
69,NaN,NaN,8639.52,NaN
70,NaN,NaN,8639.52,NaN
71,NaN,NaN,8639.52,NaN
72,NaN,NaN,8639.52,NaN
73,NaN,NaN,8639.52,NaN
74,NaN,NaN,8639.52,NaN
75,NaN,NaN,8639.52,NaN
76,NaN,NaN,8639.52,NaN
77,NaN,NaN,8639.52,NaN
78,NaN,NaN,8639.52,NaN
79,NaN,NaN,8639.52,NaN
80,NaN,NaN,8639.52,NaN
81,NaN,NaN,8639.52,NaN
82,NaN,NaN,8639.52,NaN
83,NaN,NaN,8639.52,NaN
84,NaN,NaN,8639.52,NaN
85,NaN,NaN,8639.52,NaN
86,NaN,NaN,8639.52,NaN
87,NaN,NaN,10378.18,NaN
88,NaN,NaN,10378.18,NaN
89,NaN,NaN,10378.18,NaN
90,NaN,NaN,10378.18,NaN
91,NaN,NaN,10378.18,NaN
92,NaN,NaN,10378.18,NaN
93,NaN,NaN,10378.18,NaN
94,NaN,NaN,10378.18,NaN
95,NaN,NaN,10378.18,NaN
96,NaN,NaN,10378.18,NaN
97,NaN,NaN,10378.18,NaN
98,NaN,NaN,10378.18,NaN
99,NaN,NaN,10378.18,NaN
100,NaN,NaN,10378.18,NaN
101,NaN,NaN,10378.18,NaN
code,1776765494,1776765494,1776765494,1776765494
configuration,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8
experiment_run,1,1,2,2
client,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,490.00,490.00,490.00,490.00
time_ingest,182.00,182.00,182.00,182.00
time_check,287.00,287.00,287.00,287.00
terminals,0,0,0,0
pods,1,2,1,2
tenant,,,,
num_worker,0,0,0,0
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,8187,8187,8187,8187
host_RAM,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,
host_Cores,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247624,247624,247625,247625
host_datadisk,8187,8187,8187,8187
host_volume_size,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3
loading_parameters_PODS_TOTAL,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1
loading_parameters_TPCH_TABLE,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
benchmarking_parameters_SF,3,3,3,3
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [17]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head().T

phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2
code,1776765494,1776765494,1776765494,1776765494
configuration,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8
experiment_run,1,1,2,2
client,1,2,1,2
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False

# Time Series of a Single Metric for All Experiments

This is particularly important if you require a customized aggregation or wish to monitor a component over time.
Data is stacked here (long format).

In [18]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_all(metric=metric)
df.head()

,timestamp,code,phase,experiment_run,client,type_tenants,vol_tenants,num_tenants,metric,component,value
0,0,1776765494,1776765494-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,9749.37
1,0,1776765494,1776765494-PostgreSQL-BHT-8-1-2,1,2,,False,0,total_cpu_memory,stream,20617.62
2,0,1776765494,1776765494-PostgreSQL-BHT-8-2-1,2,1,,False,0,total_cpu_memory,stream,10308.82
3,0,1776765494,1776765494-PostgreSQL-BHT-8-2-2,2,2,,False,0,total_cpu_memory,stream,20605.80
4,0,1776766994,1776766994-PostgreSQL-BHT-8-1-1,1,1,,False,0,total_cpu_memory,stream,13740.94

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [19]:
df[['timestamp', 'phase', 'value']].head(8)

   timestamp                            phase    value
0          0  1776765494-PostgreSQL-BHT-8-1-1  9749.37
1          0  1776765494-PostgreSQL-BHT-8-1-2 20617.62
2          0  1776765494-PostgreSQL-BHT-8-2-1 10308.82
3          0  1776765494-PostgreSQL-BHT-8-2-2 20605.80
4          0  1776766994-PostgreSQL-BHT-8-1-1 13740.94
5          0  1776766994-PostgreSQL-BHT-8-1-2 29727.75
6          0  1776766994-PostgreSQL-BHT-8-2-1 14898.21
7          0  1776766994-PostgreSQL-BHT-8-2-2 29472.08

## With Metadata

Connection infos are added.

In [20]:
df=collect.add_metadata(df)
df = df.sort_values(['timestamp', 'phase'])
df[['timestamp', 'phase', 'value']].head(8)

combine on columns phase

,timestamp,phase,value
1776765494-PostgreSQL-BHT-8-1-1,0,1776765494-PostgreSQL-BHT-8-1-1,9749.37
1776765494-PostgreSQL-BHT-8-1-2,0,1776765494-PostgreSQL-BHT-8-1-2,20617.62
1776765494-PostgreSQL-BHT-8-2-1,0,1776765494-PostgreSQL-BHT-8-2-1,10308.82
1776765494-PostgreSQL-BHT-8-2-2,0,1776765494-PostgreSQL-BHT-8-2-2,20605.80
1776766994-PostgreSQL-BHT-8-1-1,0,1776766994-PostgreSQL-BHT-8-1-1,13740.94
1776766994-PostgreSQL-BHT-8-1-2,0,1776766994-PostgreSQL-BHT-8-1-2,29727.75
1776766994-PostgreSQL-BHT-8-2-1,0,1776766994-PostgreSQL-BHT-8-2-1,14898.21
1776766994-PostgreSQL-BHT-8-2-2,0,1776766994-PostgreSQL-BHT-8-2-2,29472.08

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [21]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head().T

,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1
code,1776765494,1776765494,1776765494,1776765494,1776766994
configuration,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8
experiment_run,1,1,2,2,1
client,1,2,1,2,1
type_tenants,,,,,
num_tenants,0,0,0,0,0
vol_tenants,False,False,False,False,False

## Custom Aggregation and Scale

We here aggregate CPU utilization by max per phase.

In [22]:
metric = 'total_cpu_util'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["code", "experiment_run", "client", "type_tenants", "num_tenants"])["value"]
      .max()
      .reset_index()
)
df_agg.index.name = 'Max ' + collect.df_metrics.loc[metric]['title']
df_agg

,code,experiment_run,client,type_tenants,num_tenants,value
Max CPU Utilization,,,,,,
0,1776765494,1,1,,0,0.91
1,1776765494,1,2,,0,13.26
2,1776765494,2,1,,0,0.96
3,1776765494,2,2,,0,4.58
4,1776766994,1,1,,0,3.70
5,1776766994,1,2,,0,14.21
6,1776766994,2,1,,0,2.34
7,1776766994,2,2,,0,15.17

# Performance Results per Connection

In [23]:
df_performance = collect.get_performance_per_connection()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
total_timer_execution,0.75,0.76,0.76,1.40,0.75,0.74,1.50,1.50,1.45,2.49,1.51,1.46
Power@Size [~Q/h],14399.68,14212.16,14261.08,7737.91,14319.35,14623.75,14408.40,14353.32,14915.59,8679.17,14330.12,14808.18
Geo Times [s],0.75,0.76,0.76,1.40,0.75,0.74,1.50,1.50,1.45,2.49,1.51,1.46
configuration,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8
connection,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-2-2
SF,3.00,3.00,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
time [s],30,30,30,101,30,30,61,58,57,159,59,57
pod_count,1,1,1,1,1,1,1,1,1,1,1,1
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22
Throughput@Size,7920.00,7920.00,7920.00,2352.48,7920.00,7920.00,7790.16,8193.10,8336.84,2988.68,8054.24,8336.84
code,1776765494,1776765494,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994,1776766994,1776766994

## With Metadata

Connection infos are added.

In [24]:
df = collect.add_metadata(df_performance)
df.T

combine on index

,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
total_timer_execution,0.75,0.76,0.76,1.40,0.75,0.74,1.50,1.50,1.45,2.49,1.51,1.46
Power@Size [~Q/h],14399.68,14212.16,14261.08,7737.91,14319.35,14623.75,14408.40,14353.32,14915.59,8679.17,14330.12,14808.18
Geo Times [s],0.75,0.76,0.76,1.40,0.75,0.74,1.50,1.50,1.45,2.49,1.51,1.46
configuration,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8
connection,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-2-2
SF,3.00,3.00,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
time [s],30,30,30,101,30,30,61,58,57,159,59,57
pod_count,1,1,1,1,1,1,1,1,1,1,1,1
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22
Throughput@Size,7920.00,7920.00,7920.00,2352.48,7920.00,7920.00,7790.16,8193.10,8336.84,2988.68,8054.24,8336.84
code,1776765494,1776765494,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994,1776766994,1776766994
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,490.00,490.00,490.00,490.00,490.00,490.00,916.00,916.00,916.00,916.00,916.00,916.00
time_ingest,182.00,182.00,182.00,182.00,182.00,182.00,326.00,326.00,326.00,326.00,326.00,326.00
time_check,287.00,287.00,287.00,287.00,287.00,287.00,566.00,566.00,566.00,566.00,566.00,566.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,2,1,2,2,1,2,2,1,2,2
tenant,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247624,247624,247624,247625,247625,247625,247626,247627,247627,247627,247627,247627
host_datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G
host_cuda,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Performance Results per Phase

In [25]:
df_performance = collect.get_performance_aggregated_per_phase()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)

In [26]:
df_performance.T

,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2
configuration,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8
experiment_run,1,1,2,2,1,1,2,2
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2
total_timer_execution,0.75,0.76,1.40,0.75,1.50,1.48,2.49,1.48
Power@Size [~Q/h],14399.68,14236.60,7737.91,14470.75,14408.40,14631.76,8679.17,14567.19
code,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994
pod_count,1,2,1,2,1,2,1,2
SF,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00
time [s],30,30,101,30,61,58,159,59
client,1,2,1,2,1,2,1,2
Throughput@Size,7920.00,15840.00,2352.48,15840.00,7790.16,16386.21,2988.68,16108.47
num_of_queries,22,44,22,44,22,44,22,44

## With Metadata

Connection infos are added.

In [27]:
df = collect.add_metadata(df_performance)
df.T

combine on index and column 'phase'

phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2
configuration,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8
experiment_run,1,1,2,2,1,1,2,2
total_timer_execution,0.75,0.76,1.40,0.75,1.50,1.48,2.49,1.48
Power@Size [~Q/h],14399.68,14236.60,7737.91,14470.75,14408.40,14631.76,8679.17,14567.19
code,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994
pod_count,1,2,1,2,1,2,1,2
SF,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00
time [s],30,30,101,30,61,58,159,59
client,1,2,1,2,1,2,1,2
Throughput@Size,7920.00,15840.00,2352.48,15840.00,7790.16,16386.21,2988.68,16108.47
num_of_queries,22,44,22,44,22,44,22,44
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,490.00,490.00,490.00,490.00,916.00,916.00,916.00,916.00
time_ingest,182.00,182.00,182.00,182.00,326.00,326.00,326.00,326.00
time_check,287.00,287.00,287.00,287.00,566.00,566.00,566.00,566.00
terminals,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2
tenant,,,,,,,,
num_worker,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False
datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247624,247624,247625,247625,247626,247627,247627,247627
host_datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [28]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2
code,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994
configuration,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
type_tenants,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False

## Get Non-Constant Attributes

These attributes are (most probably) used to analyze performance.

In [29]:
collectors.get_non_constant(df).T

phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2
configuration,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8
experiment_run,1,1,2,2,1,1,2,2
total_timer_execution,0.75,0.76,1.40,0.75,1.50,1.48,2.49,1.48
Power@Size [~Q/h],14399.68,14236.60,7737.91,14470.75,14408.40,14631.76,8679.17,14567.19
code,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994
pod_count,1,2,1,2,1,2,1,2
SF,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00
time [s],30,30,101,30,61,58,159,59
client,1,2,1,2,1,2,1,2
Throughput@Size,7920.00,15840.00,2352.48,15840.00,7790.16,16386.21,2988.68,16108.47
num_of_queries,22,44,22,44,22,44,22,44
time_load,490.00,490.00,490.00,490.00,916.00,916.00,916.00,916.00
time_ingest,182.00,182.00,182.00,182.00,326.00,326.00,326.00,326.00
time_check,287.00,287.00,287.00,287.00,566.00,566.00,566.00,566.00
pods,1,2,1,2,1,2,1,2
datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_disk,247624,247624,247625,247625,247626,247627,247627,247627
host_datadisk,8187,8187,8187,8187,16350,16350,16350,16350
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G
loading_parameters_SF,3,3,3,3,6,6,6,6
benchmarking_parameters_SF,3,3,3,3,6,6,6,6
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2

# Performance at Ingestion

In [30]:
df_performance = collect.get_connections()
#df_performance = collect.get_loading_time_max_all()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
code,1776765494,1776765494,1776765494,1776765494,1776765494,1776765494,1776766994,1776766994,1776766994,1776766994,1776766994,1776766994
connection,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-1,PostgreSQL-BHT-8-2-2-2,PostgreSQL-BHT-8-1-1-1,PostgreSQL-BHT-8-1-2-1,PostgreSQL-BHT-8-1-2-2,PostgreSQL-BHT-8-2-1-1,PostgreSQL-BHT-8-2-2-1,PostgreSQL-BHT-8-2-2-2
configuration,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8,PostgreSQL-BHT-8
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-1-2,1776765494-PostgreSQL-BHT-8-2-1,1776765494-PostgreSQL-BHT-8-2-2,1776765494-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-1-2,1776766994-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-2-2,1776766994-PostgreSQL-BHT-8-2-2
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,490.00,490.00,490.00,490.00,490.00,490.00,916.00,916.00,916.00,916.00,916.00,916.00
time_ingest,182.00,182.00,182.00,182.00,182.00,182.00,326.00,326.00,326.00,326.00,326.00,326.00
time_check,287.00,287.00,287.00,287.00,287.00,287.00,566.00,566.00,566.00,566.00,566.00,566.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,2,1,2,2,1,2,2,1,2,2
tenant,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247624,247624,247624,247625,247625,247625,247626,247627,247627,247627,247627,247627
host_datadisk,8187,8187,8187,8187,8187,8187,16350,16350,16350,16350,16350,16350
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G
host_cuda,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Combine Performance and Monitoring

This includes filtering for the first client and incorporating efficiency metrics to track performance relative to resource usage.

In [31]:
client = 1

df_performance_monitoring = collect.get_monitoring_aggregated_per_phase(type="stream")
df_performance = collect.get_performance_aggregated_per_phase()
merged_df = pd.merge(df_performance, df_performance_monitoring, left_index=True, right_index=True, how='left')

merged_df = merged_df[merged_df['client'] == client]

#merged_df['E_Tpx'] = merged_df['Goodput (requests/second)'] / merged_df['CPU Utilization Time [s]'] * 600.
#merged_df['E_Lat'] = 1./np.sqrt(merged_df['Latency Distribution.Average Latency (microseconds)']*merged_df['CPU Utilization Time [s]']/1E6)
#merged_df['E_RAM'] = (merged_df['Goodput (requests/second)']) / merged_df['Memory Usage [MiB]']
merged_df.T

,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-2-1
configuration,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8
experiment_run,1,2,1,2
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-2-1
total_timer_execution,0.75,1.40,1.50,2.49
Power@Size [~Q/h],14399.68,7737.91,14408.40,8679.17
code,1776765494,1776765494,1776766994,1776766994
pod_count,1,1,1,1
SF,3.00,3.00,6.00,6.00
time [s],30,101,61,159
client,1,1,1,1
Throughput@Size,7920.00,2352.48,7790.16,2988.68
num_of_queries,22,22,22,22
Memory Usage [MiB],9964.58,8863.34,15519.58,14324.21
Memory Usage Cached [MiB],15199.53,12041.66,25325.03,23173.83
CPU Utilization,0.77,0.55,2.45,1.11
CPU Throttle,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00
CPU Utilization Time [s],28.32,503.46,211.14,1159.54
CPU User Time [s],24.50,408.16,183.88,960.20
CPU System Time [s],3.82,95.30,27.26,199.34
Network Rx Total [MiB],0.17,3297.65,25.98,6633.34
Network Tx Total [MiB],1.69,18.54,6118.60,36.02
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.03,0.00,0.03
Core Utilization Variance [%],0.02,0.06,0.13,0.07
Max Core Utilization [%],0.60,1.92,16.95,3.35
I/O Wait [%],17.29,21.65,4.72,31.68
Total I/O Wait Time [s],0.08,388.56,1.61,554.48
Number of Idle Sessions,0.00,0.00,0.00,0.38
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00
Number of Active Sessions,5.00,8.00,7.00,8.00
Number of Active Application Sessions,5.00,7.00,7.00,7.00
Longest Active Transaction,0.32,4.86,0.70,13.34
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,3.24,0.00,3.19
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,4.74,0.00,12.88
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00
Disk Blocks Read Count,68984.00,561627.00,137906.00,2181250.00
Buffer Cache Hit Count,12956982.00,12472471.00,25969997.00,286713764.00
Buffer Cache Hit Ratio,0.92,0.50,0.99,0.99
Index Scan Count,1673169.00,1673169.00,3373563.00,53146522.00
Index Tuple Fetch Count,7833740.00,7833740.00,15770780.00,106246548.00
Index Cache Hit Ratio,0.47,0.46,1.00,0.99
Table Buffer Hit Count,8029090.00,7536844.00,16054133.00,127702974.00
Table Blocks Read Count,0.00,492246.00,0.00,1885806.00
Table Cache Hit Ratio,0.92,0.29,0.98,0.98
Total Cache Hit Ratio,0.92,0.30,0.99,0.99
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00
Total Locks Current,4.35,16.91,16.92,23.21
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00
AccessShareLocks Current,4.35,16.91,16.92,23.21
ExclusiveLocks Current,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,0.00,NaN,0.00
Number of WAL Segments,205.00,190.93,410.00,407.44
Total WAL Size [GiB],3.20,2.98,6.41,6.37
WAL Segments Growth Rate [segments/s],0.68,0.00,0.10,0.00
WAL Growth Rate [MiB/s],10.93,0.00,1.56,0.00
Average WAL Segment Size [MiB],16.00,14.90,16.00,15.90

## With Metadata

Connection infos are added.

In [32]:
df = collect.add_metadata(merged_df)
df.T

combine on index and column 'phase'

phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-2-1
configuration,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8
experiment_run,1,2,1,2
total_timer_execution,0.75,1.40,1.50,2.49
Power@Size [~Q/h],14399.68,7737.91,14408.40,8679.17
code,1776765494,1776765494,1776766994,1776766994
pod_count,1,1,1,1
SF,3.00,3.00,6.00,6.00
time [s],30,101,61,159
client,1,1,1,1
Throughput@Size,7920.00,2352.48,7790.16,2988.68
num_of_queries,22,22,22,22
Memory Usage [MiB],9964.58,8863.34,15519.58,14324.21
Memory Usage Cached [MiB],15199.53,12041.66,25325.03,23173.83
CPU Utilization,0.77,0.55,2.45,1.11
CPU Throttle,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00
CPU Utilization Time [s],28.32,503.46,211.14,1159.54
CPU User Time [s],24.50,408.16,183.88,960.20
CPU System Time [s],3.82,95.30,27.26,199.34
Network Rx Total [MiB],0.17,3297.65,25.98,6633.34
Network Tx Total [MiB],1.69,18.54,6118.60,36.02
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.03,0.00,0.03
Core Utilization Variance [%],0.02,0.06,0.13,0.07
Max Core Utilization [%],0.60,1.92,16.95,3.35
I/O Wait [%],17.29,21.65,4.72,31.68
Total I/O Wait Time [s],0.08,388.56,1.61,554.48
Number of Idle Sessions,0.00,0.00,0.00,0.38
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00
Number of Active Sessions,5.00,8.00,7.00,8.00
Number of Active Application Sessions,5.00,7.00,7.00,7.00
Longest Active Transaction,0.32,4.86,0.70,13.34
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,3.24,0.00,3.19
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,4.74,0.00,12.88
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00
Disk Blocks Read Count,68984.00,561627.00,137906.00,2181250.00
Buffer Cache Hit Count,12956982.00,12472471.00,25969997.00,286713764.00
Buffer Cache Hit Ratio,0.92,0.50,0.99,0.99
Index Scan Count,1673169.00,1673169.00,3373563.00,53146522.00
Index Tuple Fetch Count,7833740.00,7833740.00,15770780.00,106246548.00
Index Cache Hit Ratio,0.47,0.46,1.00,0.99
Table Buffer Hit Count,8029090.00,7536844.00,16054133.00,127702974.00
Table Blocks Read Count,0.00,492246.00,0.00,1885806.00
Table Cache Hit Ratio,0.92,0.29,0.98,0.98
Total Cache Hit Ratio,0.92,0.30,0.99,0.99
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00
Total Locks Current,4.35,16.91,16.92,23.21
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00
AccessShareLocks Current,4.35,16.91,16.92,23.21
ExclusiveLocks Current,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,0.00,NaN,0.00
Number of WAL Segments,205.00,190.93,410.00,407.44
Total WAL Size [GiB],3.20,2.98,6.41,6.37
WAL Segments Growth Rate [segments/s],0.68,0.00,0.10,0.00
WAL Growth Rate [MiB/s],10.93,0.00,1.56,0.00
Average WAL Segment Size [MiB],16.00,14.90,16.00,15.90
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,490.00,490.00,916.00,916.00
time_ingest,182.00,182.00,326.00,326.00
time_check,287.00,287.00,566.00,566.00
terminals,0,0,0,0
pods,1,1,1,1
tenant,,,,
num_worker,0,0,0,0
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,8187,8187,16350,16350
host_RAM,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,
host_Cores,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247624,247625,247626,247627
host_datadisk,8187,8187,16350,16350
host_volume_size,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,16G,16G
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,6,6
loading_parameters_PODS_TOTAL,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8
loading_parameters_STORE_RAW_DATA,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1
loading_parameters_TPCH_TABLE,,,,
loading_parameters_BEXHOMA_TENANT_BY,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
benchmarking_parameters_SF,3,3,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776765494,bexhoma-sut-postgresql-bht-8-1776766994,bexhoma-sut-postgresql-bht-8-1776766994
arg_max_connections,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64
arg_max_parallel_workers,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64
arg_effective_io_concurrency,64,64,64,64
arg_io_method,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_fsync,on,on,on,on
arg_wal_compression,on,on,on,on
arg_synchronous_commit,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-2-1

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [33]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-2-1
phase,1776765494-PostgreSQL-BHT-8-1-1,1776765494-PostgreSQL-BHT-8-2-1,1776766994-PostgreSQL-BHT-8-1-1,1776766994-PostgreSQL-BHT-8-2-1
code,1776765494,1776765494,1776766994,1776766994
configuration,1776765494-PostgreSQL-BHT-8,1776765494-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8,1776766994-PostgreSQL-BHT-8
experiment_run,1,2,1,2
client,1,1,1,1
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False

# Show Warnings per Connection

In [34]:
df = collect.get_total_warnings(query_titles=False)
df.T

### Warnings (result mismatch)

,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
Q1,False,False,False,False,False,False,False,False,False,False,False,False
Q2,False,False,False,False,False,False,False,False,False,False,False,False
Q3,False,False,False,False,False,False,False,False,False,False,False,False
Q4,False,False,False,False,False,False,False,False,False,False,False,False
Q5,False,False,False,False,False,False,False,False,False,False,False,False
Q6,False,False,False,False,False,False,False,False,False,False,False,False
Q7,False,False,False,False,False,False,False,False,False,False,False,False
Q8,False,False,False,False,False,False,False,False,False,False,False,False
Q9,False,False,False,False,False,False,False,False,False,False,False,False
Q10,False,False,False,False,False,False,False,False,False,False,False,False
Q11,False,False,False,False,False,False,False,False,False,False,False,False
Q12,False,False,False,False,False,False,False,False,False,False,False,False
Q13,False,False,False,False,False,False,False,False,False,False,False,False
Q14,False,False,False,False,False,False,False,False,False,False,False,False
Q15,False,False,False,False,False,False,False,False,False,False,False,False
Q16,False,False,False,False,False,False,False,False,False,False,False,False
Q17,False,False,False,False,False,False,False,False,False,False,False,False
Q18,False,False,False,False,False,False,False,False,False,False,False,False
Q19,False,False,False,False,False,False,False,False,False,False,False,False
Q20,False,False,False,False,False,False,False,False,False,False,False,False
Q21,False,False,False,False,False,False,False,False,False,False,False,False
Q22,False,False,False,False,False,False,False,False,False,False,False,False

## Show Only Existing Warnings

For demonstration we insert a warning.

In [35]:
df.loc['1776765494-PostgreSQL-BHT-8-1-1-1','Q1'] = True
df.T

,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
Q1,True,False,False,False,False,False,False,False,False,False,False,False
Q2,False,False,False,False,False,False,False,False,False,False,False,False
Q3,False,False,False,False,False,False,False,False,False,False,False,False
Q4,False,False,False,False,False,False,False,False,False,False,False,False
Q5,False,False,False,False,False,False,False,False,False,False,False,False
Q6,False,False,False,False,False,False,False,False,False,False,False,False
Q7,False,False,False,False,False,False,False,False,False,False,False,False
Q8,False,False,False,False,False,False,False,False,False,False,False,False
Q9,False,False,False,False,False,False,False,False,False,False,False,False
Q10,False,False,False,False,False,False,False,False,False,False,False,False
Q11,False,False,False,False,False,False,False,False,False,False,False,False
Q12,False,False,False,False,False,False,False,False,False,False,False,False
Q13,False,False,False,False,False,False,False,False,False,False,False,False
Q14,False,False,False,False,False,False,False,False,False,False,False,False
Q15,False,False,False,False,False,False,False,False,False,False,False,False
Q16,False,False,False,False,False,False,False,False,False,False,False,False
Q17,False,False,False,False,False,False,False,False,False,False,False,False
Q18,False,False,False,False,False,False,False,False,False,False,False,False
Q19,False,False,False,False,False,False,False,False,False,False,False,False
Q20,False,False,False,False,False,False,False,False,False,False,False,False
Q21,False,False,False,False,False,False,False,False,False,False,False,False
Q22,False,False,False,False,False,False,False,False,False,False,False,False

In [36]:
num_warnings = df.sum().sum()
if num_warnings > 0:
    # remove only False rows
    df = df[~(df == False).all(axis=1)]
    print(df.T)
else:
    print("No warnings")

     1776765494-PostgreSQL-BHT-8-1-1-1
Q1                                True
Q2                               False
Q3                               False
Q4                               False
Q5                               False
Q6                               False
Q7                               False
Q8                               False
Q9                               False
Q10                              False
Q11                              False
Q12                              False
Q13                              False
Q14                              False
Q15                              False
Q16                              False
Q17                              False
Q18                              False
Q19                              False
Q20                              False
Q21                              False
Q22                              False

# Show Warnings per Connection with Query Titles

In [37]:
df = collect.get_total_warnings(query_titles=True)
df.T

### Warnings (result mismatch)

,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
Pricing Summary Report (TPC-H Q1),False,False,False,False,False,False,False,False,False,False,False,False
Minimum Cost Supplier Query (TPC-H Q2),False,False,False,False,False,False,False,False,False,False,False,False
Shipping Priority (TPC-H Q3),False,False,False,False,False,False,False,False,False,False,False,False
Order Priority Checking Query (TPC-H Q4),False,False,False,False,False,False,False,False,False,False,False,False
Local Supplier Volume (TPC-H Q5),False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q6),False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q7),False,False,False,False,False,False,False,False,False,False,False,False
National Market Share (TPC-H Q8),False,False,False,False,False,False,False,False,False,False,False,False
Product Type Profit Measure (TPC-H Q9),False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q10),False,False,False,False,False,False,False,False,False,False,False,False
Important Stock Identification (TPC-H Q11),False,False,False,False,False,False,False,False,False,False,False,False
Shipping Modes and Order Priority (TPC-H Q12),False,False,False,False,False,False,False,False,False,False,False,False
Customer Distribution (TPC-H Q13),False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q14),False,False,False,False,False,False,False,False,False,False,False,False
Top Supplier Query (TPC-H Q15),False,False,False,False,False,False,False,False,False,False,False,False
Parts/Supplier Relationship (TPC-H Q16),False,False,False,False,False,False,False,False,False,False,False,False
Small-Quantity-Order Revenue (TPC-H Q17),False,False,False,False,False,False,False,False,False,False,False,False
Large Volume Customer (TPC-H Q18),False,False,False,False,False,False,False,False,False,False,False,False
Discounted Revenue (TPC-H Q19),False,False,False,False,False,False,False,False,False,False,False,False
Potential Part Promotion (TPC-H Q20),False,False,False,False,False,False,False,False,False,False,False,False
Suppliers Who Kept Orders Waiting Query (TPC-H Q21),False,False,False,False,False,False,False,False,False,False,False,False
Global Sales Opportunity Query (TPC-H Q22),False,False,False,False,False,False,False,False,False,False,False,False

In [38]:
num_warnings = df.sum().sum()
if num_warnings > 0:
    # remove only False rows
    df = df[~(df == False).all(axis=1)]
    print(df.T)
else:
    print("No warnings")

No warnings

# Show Errors per Connection with Query Titles

In [39]:
df = collect.get_total_errors(query_titles=True)
df.T

### Errors (failed queries)

,1776765494-PostgreSQL-BHT-8-1-1-1,1776765494-PostgreSQL-BHT-8-1-2-1,1776765494-PostgreSQL-BHT-8-1-2-2,1776765494-PostgreSQL-BHT-8-2-1-1,1776765494-PostgreSQL-BHT-8-2-2-1,1776765494-PostgreSQL-BHT-8-2-2-2,1776766994-PostgreSQL-BHT-8-1-1-1,1776766994-PostgreSQL-BHT-8-1-2-1,1776766994-PostgreSQL-BHT-8-1-2-2,1776766994-PostgreSQL-BHT-8-2-1-1,1776766994-PostgreSQL-BHT-8-2-2-1,1776766994-PostgreSQL-BHT-8-2-2-2
Pricing Summary Report (TPC-H Q1),False,False,False,False,False,False,False,False,False,False,False,False
Minimum Cost Supplier Query (TPC-H Q2),False,False,False,False,False,False,False,False,False,False,False,False
Shipping Priority (TPC-H Q3),False,False,False,False,False,False,False,False,False,False,False,False
Order Priority Checking Query (TPC-H Q4),False,False,False,False,False,False,False,False,False,False,False,False
Local Supplier Volume (TPC-H Q5),False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q6),False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q7),False,False,False,False,False,False,False,False,False,False,False,False
National Market Share (TPC-H Q8),False,False,False,False,False,False,False,False,False,False,False,False
Product Type Profit Measure (TPC-H Q9),False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q10),False,False,False,False,False,False,False,False,False,False,False,False
Important Stock Identification (TPC-H Q11),False,False,False,False,False,False,False,False,False,False,False,False
Shipping Modes and Order Priority (TPC-H Q12),False,False,False,False,False,False,False,False,False,False,False,False
Customer Distribution (TPC-H Q13),False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q14),False,False,False,False,False,False,False,False,False,False,False,False
Top Supplier Query (TPC-H Q15),False,False,False,False,False,False,False,False,False,False,False,False
Parts/Supplier Relationship (TPC-H Q16),False,False,False,False,False,False,False,False,False,False,False,False
Small-Quantity-Order Revenue (TPC-H Q17),False,False,False,False,False,False,False,False,False,False,False,False
Large Volume Customer (TPC-H Q18),False,False,False,False,False,False,False,False,False,False,False,False
Discounted Revenue (TPC-H Q19),False,False,False,False,False,False,False,False,False,False,False,False
Potential Part Promotion (TPC-H Q20),False,False,False,False,False,False,False,False,False,False,False,False
Suppliers Who Kept Orders Waiting Query (TPC-H Q21),False,False,False,False,False,False,False,False,False,False,False,False
Global Sales Opportunity Query (TPC-H Q22),False,False,False,False,False,False,False,False,False,False,False,False

## Show Only Existing Errors

In [42]:
num_errors = df.sum().sum()
if num_errors > 0:
    # remove only False rows
    df = df[~(df == False).all(axis=1)]
    print(df.T)
else:
    print("No errors")

No errors