# TPC-H Collector Demo - Multi-Tenancy

In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option('display.max_colwidth', None)
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.float_format = '{:.2f}'.format

from bexhoma import collectors

%matplotlib inline

## Functions for Nice Plots

In [2]:
from notebookutils import *

# Collect Results

In [3]:
path = r"D:\data\benchmarks"
#path = r"/data/benchmarks"
filename_prefix = "demo_"
b_plot_save = False
b_skip_plots = True

In [4]:
codes = [
    "1776772217",
    "1776770536",
    "1776768855"
]

codes

['1776772217', '1776770536', '1776768855']

In [5]:
collect = collectors.dbmsbenchmarker(path, codes)

# Get all Metrics Metadata

## Metrics Names and Types

Metrics that are derived from monitoring

In [6]:
collect.get_metrics_metadata()

,title,active,type,metric
total_cpu_memory,Memory Usage [MiB],True,cluster,gauge
total_cpu_memory_cached,Memory Usage Cached [MiB],True,cluster,gauge
total_cpu_util,CPU Utilization,True,cluster,gauge
total_cpu_throttled,CPU Throttle,True,cluster,gauge
total_cpu_throttled_s,CPU Throttled Time [s],True,cluster,counter
total_cpu_util_others,CPU Utilization Others,False,cluster,gauge
total_cpu_util_s,CPU Utilization Time [s],True,cluster,counter
total_cpu_util_user_s,CPU User Time [s],True,cluster,counter
total_cpu_util_sys_s,CPU System Time [s],True,cluster,counter
total_cpu_util_others_s,CPU Utilization Time Others [s],False,cluster,counter
total_network_rx,Network Rx Total [MiB],True,cluster,counter
total_network_tx,Network Tx Total [MiB],True,cluster,counter
total_fs_read,Filesystem Read Total [MiB],True,cluster,counter
total_fs_write,Filesystem Write Total [MiB],True,cluster,counter
total_gpu_util,GPU Utilization [%],False,cluster,gauge
total_gpu_power,GPU Power Usage [W],False,cluster,gauge
total_gpu_memory,GPU Memory Usage [MiB],False,cluster,gauge
core_variance,Core Utilization Variance [%],True,cluster,ratio
max_core_util,Max Core Utilization [%],True,cluster,ratio
io_wait_pct,I/O Wait [%],True,cluster,ratio
io_wait_total,Total I/O Wait Time [s],True,cluster,counter
pg_stat_activity_count_idle,Number of Idle Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction,Number of Idle-in-transaction Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction_aborted,Number of Idle-in-transaction Aborted Sessions,True,application,gauge
pg_stat_activity_count_active,Number of Active Sessions,True,application,counter
pg_stat_activity_count_active_app,Number of Active Application Sessions,True,application,counter
pg_stat_activity_max_tx_duration_active,Longest Active Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle,Longest Idle Session (no transaction),True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx,Longest Idle-in-Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx_aborted,Longest Idle-in-Transaction (Aborted),True,application,ratio
pg_stat_activity_count_io,Active Backends Waiting on I/O,True,application,gauge
pg_stat_activity_count_wal,Active Backends Waiting on WAL,True,application,gauge
pg_stat_activity_count_lock,Active Backends Waiting on Locks,True,application,gauge
pg_stat_activity_max_tx_duration_io,Max Transaction Duration (I/O Wait),True,application,ratio
pg_stat_activity_max_tx_duration_wal,Max Transaction Duration (WAL Wait),True,application,ratio
pg_stat_activity_max_tx_duration_lock,Max Transaction Duration (Lock Wait),True,application,ratio
pg_stat_database_blks_read,Disk Blocks Read Count,True,application,counter
pg_stat_database_blks_hit,Buffer Cache Hit Count,True,application,counter
cache_hit_ratio,Buffer Cache Hit Ratio,True,application,ratio
pg_stat_user_tables_idx_scan,Index Scan Count,True,application,counter
pg_stat_user_tables_idx_tup_fetch,Index Tuple Fetch Count,True,application,counter
pg_statio_user_tables_idx_cache_hit_ratio,Index Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_heap_blocks_hit,Table Buffer Hit Count,True,application,counter
pg_statio_user_tables_heap_blocks_read,Table Blocks Read Count,True,application,counter
pg_statio_user_tables_heap_cache_hit_ratio,Table Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_total_cache_hit_ratio,Total Cache Hit Ratio,True,application,ratio
pg_stat_bgwriter_efficiency_ratio,BGWriter Efficiency Ratio (Cleaned / Allocated),True,application,ratio
pg_stat_bgwriter_maxwritten_clean_total,BGWriter Stopped Due to Max Pages,True,application,counter
pg_stat_bgwriter_checkpoint_sync_time_total,Checkpoint Sync Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_total,Checkpoint Write Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_per_sync_time,Time spent writing vs syncing during checkpoints [ratio],False,application,ratio
pg_locks_count,Total Locks Current,True,application,gauge
pg_locks_count_accessexclusivelock,AccessExclusiveLocks Current,True,application,gauge
pg_locks_count_accesssharelock,AccessShareLocks Current,True,application,gauge
pg_locks_count_exclusivelock,ExclusiveLocks Current,True,application,gauge
pg_locks_count_rowexclusivelock,RowExclusiveLocks Current,True,application,gauge
pg_locks_count_rowsharelock,RowShareLocks Current,True,application,gauge
pg_locks_count_sharelock,ShareLocks Current,True,application,gauge
pg_locks_count_sharerowexclusivelock,ShareRowExclusiveLocks Current,True,application,gauge
pg_locks_count_shareupdateexclusivelock,ShareUpdateExclusiveLocks Current,True,application,gauge
pg_locks_count_sireadlock,SIReadLocks Current,True,application,gauge
pg_stat_user_tables_autoanalyze_count,Autoanalyze Run Count,True,application,counter
pg_stat_user_tables_autovacuum_count,Autovacuum Run Count,True,application,counter
pg_stat_bgwriter_checkpoints_timed_per_req,Frequency of checkpoints (timed vs requested) [ratio],False,application,gauge
pg_stat_wal_volume_bytes_sec,Volume of WAL generated [bytes/sec],False,application,counter
pg_stat_bgwriter_buffers_backend_fsync,Backends forced to flush WAL (I/O contention) [fsync/sec],False,application,counter
pg_stat_activity_wait_event_count,Active sessions waiting on any event [count],False,application,gauge
pg_stat_user_tables_dead_tuples_per_vacuum,Dead tuples per vacuum operation [tuples/vacuum],True,application,ratio
pg_wal_segments,Number of WAL Segments,True,application,gauge
pg_wal_size_bytes,Total WAL Size [GiB],True,application,gauge
pg_wal_segments_rate,WAL Segments Growth Rate [segments/s],True,application,gauge
pg_wal_size_rate,WAL Growth Rate [MiB/s],True,application,gauge
pg_wal_avg_segment_size,Average WAL Segment Size [MiB],True,application,gauge
pg_wal_size_per_checkpoint,WAL Size per Checkpoint [bytes/checkpoint],False,application,gauge

## Names of Monitored Components

Names of components and their phases

In [7]:
collect.get_monitored_components()

                                           description
loading                  Loading phase: SUT deployment
datagenerator  Loading phase: component data generator
loader                 Loading phase: component loader
stream                 Execution phase: SUT deployment
benchmarker     Execution phase: component benchmarker

# Get Connection Infos

List of states of SUTs, containing loading infos.

In [8]:
df=collect.get_connections()

In [9]:
df.T

,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-2-2-2
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855
connection,PostgreSQL-BHT-1-0-1-1-1,PostgreSQL-BHT-1-0-1-2-1,PostgreSQL-BHT-1-0-2-1-1,PostgreSQL-BHT-1-0-2-2-1,PostgreSQL-BHT-1-1-1-1-1,PostgreSQL-BHT-1-1-1-2-1,PostgreSQL-BHT-1-1-2-1-1,PostgreSQL-BHT-1-1-2-2-1,PostgreSQL-BHT-2-1-1-1,PostgreSQL-BHT-2-1-1-2,PostgreSQL-BHT-2-1-2-1,PostgreSQL-BHT-2-1-2-2,PostgreSQL-BHT-2-2-1-1,PostgreSQL-BHT-2-2-1-2,PostgreSQL-BHT-2-2-2-1,PostgreSQL-BHT-2-2-2-2,PostgreSQL-BHT-2-1-1-1,PostgreSQL-BHT-2-1-1-2,PostgreSQL-BHT-2-1-2-1,PostgreSQL-BHT-2-1-2-2,PostgreSQL-BHT-2-2-1-1,PostgreSQL-BHT-2-2-1-2,PostgreSQL-BHT-2-2-2-1,PostgreSQL-BHT-2-2-2-2
configuration,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-2-2
experiment_run,1,1,2,2,1,1,2,2,1,1,1,1,2,2,2,2,1,1,1,1,2,2,2,2
client,1,2,1,2,1,2,1,2,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,685.00,685.00,685.00,685.00,683.00,683.00,683.00,683.00,977.00,977.00,977.00,977.00,977.00,977.00,977.00,977.00,979.00,979.00,979.00,979.00,979.00,979.00,979.00,979.00
time_ingest,302.00,302.00,302.00,302.00,300.00,300.00,300.00,300.00,439.00,439.00,439.00,439.00,439.00,439.00,439.00,439.00,440.00,440.00,440.00,440.00,440.00,440.00,440.00,440.00
time_check,379.00,379.00,379.00,379.00,378.00,378.00,378.00,378.00,533.00,533.00,533.00,533.00,533.00,533.00,533.00,533.00,535.00,535.00,535.00,535.00,535.00,535.00,535.00,535.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
tenant,0,0,0,0,1,1,1,1,,,,,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16368,16368,16368,16368,16353,16353,16353,16353,16353,16353,16353,16353
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,,,,,,,,,,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247634,247634,247634,247635,247634,247634,247635,247635,247631,247631,247631,247631,247632,247632,247632,247632,247629,247629,247629,247629,247630,247630,247630,247630
host_datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16368,16368,16368,16368,16353,16353,16353,16353,16353,16353,16353,16353
host_volume_size,15G,15G,15G,15G,15G,15G,15G,15G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G
host_cuda,,,,,,,,,,,,,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
loading_parameters_PODS_TOTAL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_PODS_PARALLEL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
loading_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
benchmarking_parameters_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
benchmarking_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [10]:
df[['phase', 'code', 'connection', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-2-2-2
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-2-2
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855
connection,PostgreSQL-BHT-1-0-1-1-1,PostgreSQL-BHT-1-0-1-2-1,PostgreSQL-BHT-1-0-2-1-1,PostgreSQL-BHT-1-0-2-2-1,PostgreSQL-BHT-1-1-1-1-1,PostgreSQL-BHT-1-1-1-2-1,PostgreSQL-BHT-1-1-2-1-1,PostgreSQL-BHT-1-1-2-2-1,PostgreSQL-BHT-2-1-1-1,PostgreSQL-BHT-2-1-1-2,PostgreSQL-BHT-2-1-2-1,PostgreSQL-BHT-2-1-2-2,PostgreSQL-BHT-2-2-1-1,PostgreSQL-BHT-2-2-1-2,PostgreSQL-BHT-2-2-2-1,PostgreSQL-BHT-2-2-2-2,PostgreSQL-BHT-2-1-1-1,PostgreSQL-BHT-2-1-1-2,PostgreSQL-BHT-2-1-2-1,PostgreSQL-BHT-2-1-2-2,PostgreSQL-BHT-2-2-1-1,PostgreSQL-BHT-2-2-1-2,PostgreSQL-BHT-2-2-2-1,PostgreSQL-BHT-2-2-2-2
configuration,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2
experiment_run,1,1,2,2,1,1,2,2,1,1,1,1,2,2,2,2,1,1,1,1,2,2,2,2
client,1,2,1,2,1,2,1,2,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
type_tenants,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Get Non-Constant Attributes

These attributes are (most probably) used to analyze performance.

In [11]:
collectors.get_non_constant(df).T

,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-2-2-2
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855
connection,PostgreSQL-BHT-1-0-1-1-1,PostgreSQL-BHT-1-0-1-2-1,PostgreSQL-BHT-1-0-2-1-1,PostgreSQL-BHT-1-0-2-2-1,PostgreSQL-BHT-1-1-1-1-1,PostgreSQL-BHT-1-1-1-2-1,PostgreSQL-BHT-1-1-2-1-1,PostgreSQL-BHT-1-1-2-2-1,PostgreSQL-BHT-2-1-1-1,PostgreSQL-BHT-2-1-1-2,PostgreSQL-BHT-2-1-2-1,PostgreSQL-BHT-2-1-2-2,PostgreSQL-BHT-2-2-1-1,PostgreSQL-BHT-2-2-1-2,PostgreSQL-BHT-2-2-2-1,PostgreSQL-BHT-2-2-2-2,PostgreSQL-BHT-2-1-1-1,PostgreSQL-BHT-2-1-1-2,PostgreSQL-BHT-2-1-2-1,PostgreSQL-BHT-2-1-2-2,PostgreSQL-BHT-2-2-1-1,PostgreSQL-BHT-2-2-1-2,PostgreSQL-BHT-2-2-2-1,PostgreSQL-BHT-2-2-2-2
configuration,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-2-2
experiment_run,1,1,2,2,1,1,2,2,1,1,1,1,2,2,2,2,1,1,1,1,2,2,2,2
client,1,2,1,2,1,2,1,2,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
time_load,685.00,685.00,685.00,685.00,683.00,683.00,683.00,683.00,977.00,977.00,977.00,977.00,977.00,977.00,977.00,977.00,979.00,979.00,979.00,979.00,979.00,979.00,979.00,979.00
time_ingest,302.00,302.00,302.00,302.00,300.00,300.00,300.00,300.00,439.00,439.00,439.00,439.00,439.00,439.00,439.00,439.00,440.00,440.00,440.00,440.00,440.00,440.00,440.00,440.00
time_check,379.00,379.00,379.00,379.00,378.00,378.00,378.00,378.00,533.00,533.00,533.00,533.00,533.00,533.00,533.00,533.00,535.00,535.00,535.00,535.00,535.00,535.00,535.00,535.00
pods,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
tenant,0,0,0,0,1,1,1,1,,,,,,,,,,,,,,,,
type_tenants,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16368,16368,16368,16368,16353,16353,16353,16353,16353,16353,16353,16353
host_disk,247634,247634,247634,247635,247634,247634,247635,247635,247631,247631,247631,247631,247632,247632,247632,247632,247629,247629,247629,247629,247630,247630,247630,247630
host_datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16368,16368,16368,16368,16353,16353,16353,16353,16353,16353,16353,16353
host_volume_size,15G,15G,15G,15G,15G,15G,15G,15G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G
loading_parameters_PODS_TOTAL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_PODS_PARALLEL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
benchmarking_parameters_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
benchmarking_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855

# Monitoring Aggregated per Phase and Tenancy

In [12]:
df = collect.get_monitoring_aggregated_per_phase_multitenant("stream")
df.T

combine on index and column 'phase'

,1776768855_1_1_schema_2,1776768855_1_2_schema_2,1776768855_2_1_schema_2,1776768855_2_2_schema_2,1776770536_1_1_database_2,1776770536_1_2_database_2,1776770536_2_1_database_2,1776770536_2_2_database_2,1776772217_1_1_container_2,1776772217_1_2_container_2,1776772217_2_1_container_2,1776772217_2_2_container_2
Memory Usage [MiB],14294.75,14915.17,12942.05,14883.51,13825.50,15339.01,12776.27,14741.79,19947.25,21018.52,17791.72,20647.30
Memory Usage Cached [MiB],25317.07,24723.73,20327.87,23842.79,25466.86,25151.62,20142.09,23713.12,30188.03,30865.82,24155.04,29622.99
CPU Utilization,1.10,0.90,1.03,1.27,0.47,0.94,0.65,0.02,0.47,0.61,1.27,0.55
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],178.14,46.72,791.63,66.18,6.30,137.51,795.93,0.00,66.69,75.17,473.72,131.38
CPU User Time [s],149.49,42.23,639.54,57.98,5.47,116.26,640.68,0.00,56.48,64.05,380.76,113.82
CPU System Time [s],28.65,4.49,152.09,8.19,0.83,21.25,155.24,0.00,10.21,11.12,92.95,17.55
Network Rx Total [MiB],0.19,0.20,6591.16,1.74,0.11,0.06,6599.80,1.78,0.14,26.44,3298.26,0.23
Network Tx Total [MiB],3.26,0.19,31.84,0.11,3.31,3.28,39.36,0.11,1.97,6046.50,17.64,0.06
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.00,0.04,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.03,0.00
Core Utilization Variance [%],0.02,0.02,0.06,0.13,0.02,0.03,0.04,0.13,0.02,0.03,0.05,0.12
Max Core Utilization [%],0.68,1.16,1.67,3.64,1.17,1.65,1.33,4.77,0.80,1.13,1.24,4.31
I/O Wait [%],15.16,5.46,35.95,51.22,14.38,6.28,30.19,46.30,18.55,3.60,32.83,46.37
Total I/O Wait Time [s],3.14,0.57,800.81,0.40,0.46,0.34,653.65,0.65,0.39,1.11,679.24,0.60
Number of Idle Sessions,0.71,0.00,0.00,0.00,1.34,0.00,0.31,1.84,1.00,0.98,0.62,0.42
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,11.00,10.00,14.00,10.00,15.00,11.00,16.00,8.00,7.00,13.00,13.00,9.00
Number of Active Application Sessions,10.00,10.00,14.00,10.00,14.00,11.00,17.00,9.00,7.00,11.00,14.00,10.00
Longest Active Transaction,0.10,0.33,15.49,0.44,0.37,1.35,6.19,0.48,0.27,0.14,9.40,0.80
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,0.00,7.84,0.00,0.00,0.00,5.59,0.00,0.00,0.00,6.27,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,0.00,13.72,0.00,0.00,0.00,5.75,0.00,0.00,0.00,9.33,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,141480.00,0.00,1126841.00,0.00,141562.00,0.00,1058662.00,0.00,70669.00,0.00,1092912.00,0.00
Buffer Cache Hit Count,24831964.00,27077595.00,24964455.00,27077595.00,26903773.00,27045341.00,14268105.00,18118575.00,10477165.00,11845163.00,17804872.00,26002894.00
Buffer Cache Hit Ratio,0.92,0.98,0.60,0.97,0.94,0.98,0.98,0.98,0.93,0.98,0.98,0.98
Index Scan Count,3736462.00,3773734.00,3755098.00,3773734.00,878346.00,3776174.00,2157177.00,2249923.00,1720033.00,1881536.00,2776794.00,3748178.00
Index Tuple Fetch Count,16267390.00,17416794.00,16842092.00,17416794.00,3993638.00,17416366.00,9808542.00,9965419.00,7631973.00,8173972.00,12697816.00,16760062.00
Index Cache Hit Ratio,0.56,0.99,0.55,0.99,0.79,0.99,0.99,0.99,0.68,0.99,0.99,0.99
Table Buffer Hit Count,13814380.00,15800584.00,13875674.00,15800584.00,3094024.00,15753870.00,5881945.00,7012236.00,5418802.00,6225638.00,9624483.00,14804456.00
Table Blocks Read Count,0.00,0.00,984840.00,0.00,0.00,0.00,984776.00,0.00,0.00,0.00,984814.00,0.00
Table Cache Hit Ratio,0.92,0.97,0.36,0.96,0.91,0.97,0.97,0.98,0.92,0.97,0.98,0.97
Total Cache Hit Ratio,0.92,0.98,0.38,0.97,0.92,0.98,0.98,0.98,0.93,0.98,0.98,0.98
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,12.61,7.42,30.47,6.13,21.31,26.09,38.79,37.38,16.00,13.54,24.51,17.07
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,12.61,7.42,30.47,6.13,21.31,26.09,38.79,37.38,16.00,13.54,24.51,17.07
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
Number of WAL Segments,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00
Total WAL Size [GiB],6.41,6.41,6.41,6.41,6.41,6.41,6.41,6.41,6.40,6.40,6.40,6.40
WAL Segments Growth Rate [segments/s],0.60,0.17,0.00,0.00,0.53,0.21,0.00,0.00,0.84,0.06,0.00,0.00
WAL Growth Rate [MiB/s],9.53,2.64,0.00,0.00,8.53,3.41,0.00,0.00,13.42,0.94,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,32.00,32.00,32.00,32.00
code,1776768855,1776768855,1776768855,1776768855,1776770536,1776770536,1776770536,1776770536,1776772217,1776772217,1776772217,1776772217
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2
type_tenants,schema,schema,schema,schema,database,database,database,database,container,container,container,container
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2

## With Metadata

Connection infos are added.

In [13]:
df = collect.add_metadata(df)
df.T

combine on columns code experiment_run client type_tenants num_tenants

,1776768855-1-1-schema-2,1776768855-1-2-schema-2,1776768855-2-1-schema-2,1776768855-2-2-schema-2,1776770536-1-1-database-2,1776770536-1-2-database-2,1776770536-2-1-database-2,1776770536-2-2-database-2,1776772217-1-1-container-2,1776772217-1-2-container-2,1776772217-2-1-container-2,1776772217-2-2-container-2
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,12.61,7.42,30.47,6.13,21.31,26.09,38.79,37.38,16.00,13.54,24.51,17.07
Active Backends Waiting on I/O,0.00,0.00,7.84,0.00,0.00,0.00,5.59,0.00,0.00,0.00,6.27,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,32.00,32.00,32.00,32.00
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Buffer Cache Hit Count,24831964.00,27077595.00,24964455.00,27077595.00,26903773.00,27045341.00,14268105.00,18118575.00,10477165.00,11845163.00,17804872.00,26002894.00
Buffer Cache Hit Ratio,0.92,0.98,0.60,0.97,0.94,0.98,0.98,0.98,0.93,0.98,0.98,0.98
CPU System Time [s],28.65,4.49,152.09,8.19,0.83,21.25,155.24,0.00,10.21,11.12,92.95,17.55
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU User Time [s],149.49,42.23,639.54,57.98,5.47,116.26,640.68,0.00,56.48,64.05,380.76,113.82
CPU Utilization,1.10,0.90,1.03,1.27,0.47,0.94,0.65,0.02,0.47,0.61,1.27,0.55
CPU Utilization Time [s],178.14,46.72,791.63,66.18,6.30,137.51,795.93,0.00,66.69,75.17,473.72,131.38
Core Utilization Variance [%],0.02,0.02,0.06,0.13,0.02,0.03,0.04,0.13,0.02,0.03,0.05,0.12
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
Disk Blocks Read Count,141480.00,0.00,1126841.00,0.00,141562.00,0.00,1058662.00,0.00,70669.00,0.00,1092912.00,0.00
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.00,0.04,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.03,0.00
I/O Wait [%],15.16,5.46,35.95,51.22,14.38,6.28,30.19,46.30,18.55,3.60,32.83,46.37
Index Cache Hit Ratio,0.56,0.99,0.55,0.99,0.79,0.99,0.99,0.99,0.68,0.99,0.99,0.99
Index Scan Count,3736462.00,3773734.00,3755098.00,3773734.00,878346.00,3776174.00,2157177.00,2249923.00,1720033.00,1881536.00,2776794.00,3748178.00
Index Tuple Fetch Count,16267390.00,17416794.00,16842092.00,17416794.00,3993638.00,17416366.00,9808542.00,9965419.00,7631973.00,8173972.00,12697816.00,16760062.00
Longest Active Transaction,0.10,0.33,15.49,0.44,0.37,1.35,6.19,0.48,0.27,0.14,9.40,0.80
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Core Utilization [%],0.68,1.16,1.67,3.64,1.17,1.65,1.33,4.77,0.80,1.13,1.24,4.31
Max Transaction Duration (I/O Wait),0.00,0.00,13.72,0.00,0.00,0.00,5.75,0.00,0.00,0.00,9.33,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Memory Usage Cached [MiB],25317.07,24723.73,20327.87,23842.79,25466.86,25151.62,20142.09,23713.12,30188.03,30865.82,24155.04,29622.99
Memory Usage [MiB],14294.75,14915.17,12942.05,14883.51,13825.50,15339.01,12776.27,14741.79,19947.25,21018.52,17791.72,20647.30
Network Rx Total [MiB],0.19,0.20,6591.16,1.74,0.11,0.06,6599.80,1.78,0.14,26.44,3298.26,0.23
Network Tx Total [MiB],3.26,0.19,31.84,0.11,3.31,3.28,39.36,0.11,1.97,6046.50,17.64,0.06
Number of Active Application Sessions,10.00,10.00,14.00,10.00,14.00,11.00,17.00,9.00,7.00,11.00,14.00,10.00
Number of Active Sessions,11.00,10.00,14.00,10.00,15.00,11.00,16.00,8.00,7.00,13.00,13.00,9.00
Number of Idle Sessions,0.71,0.00,0.00,0.00,1.34,0.00,0.31,1.84,1.00,0.98,0.62,0.42
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of WAL Segments,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Table Blocks Read Count,0.00,0.00,984840.00,0.00,0.00,0.00,984776.00,0.00,0.00,0.00,984814.00,0.00
Table Buffer Hit Count,13814380.00,15800584.00,13875674.00,15800584.00,3094024.00,15753870.00,5881945.00,7012236.00,5418802.00,6225638.00,9624483.00,14804456.00
Table Cache Hit Ratio,0.92,0.97,0.36,0.96,0.91,0.97,0.97,0.98,0.92,0.97,0.98,0.97
Total Cache Hit Ratio,0.92,0.98,0.38,0.97,0.92,0.98,0.98,0.98,0.93,0.98,0.98,0.98
Total I/O Wait Time [s],3.14,0.57,800.81,0.40,0.46,0.34,653.65,0.65,0.39,1.11,679.24,0.60
Total Locks Current,12.61,7.42,30.47,6.13,21.31,26.09,38.79,37.38,16.00,13.54,24.51,17.07
Total WAL Size [GiB],6.41,6.41,6.41,6.41,6.41,6.41,6.41,6.41,6.40,6.40,6.40,6.40
WAL Growth Rate [MiB/s],9.53,2.64,0.00,0.00,8.53,3.41,0.00,0.00,13.42,0.94,0.00,0.00
WAL Segments Growth Rate [segments/s],0.60,0.17,0.00,0.00,0.53,0.21,0.00,0.00,0.84,0.06,0.00,0.00
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
benchmarking_parameters_BEXHOMA_TENANT_BY,schema,schema,schema,schema,database,database,database,database,container,container,container,container
benchmarking_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3
benchmarking_parameters_TENANT_BY,schema,schema,schema,schema,database,database,database,database,container,container,container,container
benchmarking_parameters_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2
code,1776768855,1776768855,1776768855,1776768855,1776770536,1776770536,1776770536,1776770536,1776772217,1776772217,1776772217,1776772217
configuration,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0
datadisk,16353,16353,16353,16353,16368,16368,16368,16368,8188,8188,8188,8188
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128
host_GPU,,,,,,,,,,,,
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_cuda,,,,,,,,,,,,
host_datadisk,16353,16353,16353,16353,16368,16368,16368,16368,8188,8188,8188,8188
host_disk,247629,247629,247630,247630,247631,247631,247632,247632,247634,247634,247634,247635
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G,15G,15G,15G,15G
host_volume_used,16G,16G,16G,16G,16G,16G,16G,16G,8.0G,8.0G,8.0G,8.0G
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_TENANT_BY,schema,schema,schema,schema,database,database,database,database,container,container,container,container
loading_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_PODS_PARALLEL,2,2,2,2,2,2,2,2,1,1,1,1
loading_parameters_PODS_TOTAL,2,2,2,2,2,2,2,2,1,1,1,1
loading_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_TPCH_TABLE,,,,,,,,,,,,
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
phase,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2
pods,2,2,2,2,2,2,2,2,1,1,1,1
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3
tenant,,,,,,,,,0,0,0,0
terminals,0,0,0,0,0,0,0,0,0,0,0,0
time_check,535.00,535.00,535.00,535.00,533.00,533.00,533.00,533.00,379.00,379.00,379.00,379.00
time_ingest,440.00,440.00,440.00,440.00,439.00,439.00,439.00,439.00,302.00,302.00,302.00,302.00
time_load,979.00,979.00,979.00,979.00,977.00,977.00,977.00,977.00,685.00,685.00,685.00,685.00
type_tenants,schema,schema,schema,schema,database,database,database,database,container,container,container,container
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [14]:
df[['phase', 'code', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

,1776768855-1-1-schema-2,1776768855-1-2-schema-2,1776768855-2-1-schema-2,1776768855-2-2-schema-2,1776770536-1-1-database-2,1776770536-1-2-database-2,1776770536-2-1-database-2,1776770536-2-2-database-2,1776772217-1-1-container-2,1776772217-1-2-container-2,1776772217-2-1-container-2,1776772217-2-2-container-2
phase,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2
code,1776768855,1776768855,1776768855,1776768855,1776770536,1776770536,1776770536,1776770536,1776772217,1776772217,1776772217,1776772217
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2
type_tenants,schema,schema,schema,schema,database,database,database,database,container,container,container,container
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False

# Monitoring Aggregated per Phase

In [15]:
df = collect.get_monitoring_aggregated_per_phase("stream")
df.T

,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
Memory Usage [MiB],10194.21,10704.20,7909.78,10307.04,9753.04,10314.32,9881.94,10340.26,13825.50,15339.01,12776.27,14741.79,14294.75,14915.17,12942.05,14883.51
Memory Usage Cached [MiB],15117.85,15627.85,10008.66,14794.89,15070.18,15237.97,14146.38,14828.10,25466.86,25151.62,20142.09,23713.12,25317.07,24723.73,20327.87,23842.79
CPU Utilization,0.46,0.60,0.64,0.11,0.01,0.01,0.63,0.44,0.47,0.94,0.65,0.02,1.10,0.90,1.03,1.27
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],66.69,75.17,79.42,105.36,0.00,0.00,394.30,26.02,6.30,137.51,795.93,0.00,178.14,46.72,791.63,66.18
CPU User Time [s],56.48,64.05,60.41,90.28,0.00,0.00,320.35,23.54,5.47,116.26,640.68,0.00,149.49,42.23,639.54,57.98
CPU System Time [s],10.21,11.12,19.01,15.08,0.00,0.00,73.94,2.47,0.83,21.25,155.24,0.00,28.65,4.49,152.09,8.19
Network Rx Total [MiB],0.04,13.80,1.89,0.05,0.10,12.64,3296.37,0.18,0.11,0.06,6599.80,1.78,0.19,0.20,6591.16,1.74
Network Tx Total [MiB],0.19,3009.48,0.09,0.03,1.78,3037.02,17.55,0.03,3.31,3.28,39.36,0.11,3.26,0.19,31.84,0.11
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.04,0.00
Core Utilization Variance [%],0.02,0.03,0.05,0.12,0.02,0.03,0.04,0.12,0.02,0.03,0.04,0.13,0.02,0.02,0.06,0.13
Max Core Utilization [%],0.80,1.13,1.24,4.31,0.80,1.12,1.14,4.31,1.17,1.65,1.33,4.77,0.68,1.16,1.67,3.64
I/O Wait [%],18.47,3.47,32.83,46.13,18.55,3.60,31.74,46.37,14.38,6.28,30.19,46.30,15.16,5.46,35.95,51.22
Total I/O Wait Time [s],0.39,1.11,679.24,0.60,0.39,1.11,623.77,0.60,0.46,0.34,653.65,0.65,3.14,0.57,800.81,0.40
Number of Idle Sessions,0.00,0.72,0.33,0.42,1.00,0.26,0.29,0.00,1.34,0.00,0.31,1.84,0.71,0.00,0.00,0.00
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,7.00,5.00,6.00,4.00,0.00,8.00,7.00,5.00,15.00,11.00,16.00,8.00,11.00,10.00,14.00,10.00
Number of Active Application Sessions,7.00,4.00,7.00,5.00,0.00,7.00,7.00,5.00,14.00,11.00,17.00,9.00,10.00,10.00,14.00,10.00
Longest Active Transaction,0.27,0.11,7.80,0.16,0.00,0.14,9.40,0.80,0.37,1.35,6.19,0.48,0.10,0.33,15.49,0.44
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,0.00,3.91,0.00,0.00,0.00,2.36,0.00,0.00,0.00,5.59,0.00,0.00,0.00,7.84,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,0.00,7.70,0.00,0.00,0.00,9.33,0.00,0.00,0.00,5.75,0.00,0.00,0.00,13.72,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,70669.00,0.00,563369.00,0.00,0.00,0.00,529543.00,0.00,141562.00,0.00,1058662.00,0.00,141480.00,0.00,1126841.00,0.00
Buffer Cache Hit Count,10477165.00,11842006.00,12992528.00,12533207.00,0.00,3157.00,4812344.00,13469687.00,26903773.00,27045341.00,14268105.00,18118575.00,24831964.00,27077595.00,24964455.00,27077595.00
Buffer Cache Hit Ratio,0.93,0.98,0.85,0.97,0.90,0.98,0.98,0.98,0.94,0.98,0.98,0.98,0.92,0.98,0.60,0.97
Index Scan Count,1720033.00,1881536.00,1899179.00,1881541.00,0.00,0.00,877615.00,1866637.00,878346.00,3776174.00,2157177.00,2249923.00,3736462.00,3773734.00,3755098.00,3773734.00
Index Tuple Fetch Count,7631973.00,8173972.00,8716253.00,8173977.00,0.00,0.00,3981563.00,8586085.00,3993638.00,17416366.00,9808542.00,9965419.00,16267390.00,17416794.00,16842092.00,17416794.00
Index Cache Hit Ratio,0.68,0.99,0.96,0.99,0.39,0.99,0.99,0.99,0.79,0.99,0.99,0.99,0.56,0.99,0.55,0.99
Table Buffer Hit Count,5418802.00,6225638.00,7381297.00,6913083.00,0.00,0.00,2243186.00,7891373.00,3094024.00,15753870.00,5881945.00,7012236.00,13814380.00,15800584.00,13875674.00,15800584.00
Table Blocks Read Count,0.00,0.00,492426.00,0.00,0.00,0.00,492388.00,0.00,0.00,0.00,984776.00,0.00,0.00,0.00,984840.00,0.00
Table Cache Hit Ratio,0.92,0.97,0.61,0.96,0.90,0.97,0.98,0.97,0.91,0.97,0.97,0.98,0.92,0.97,0.36,0.96
Total Cache Hit Ratio,0.93,0.98,0.64,0.97,0.90,0.98,0.98,0.98,0.92,0.98,0.98,0.98,0.92,0.98,0.38,0.97
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,15.00,4.38,15.91,9.48,1.00,9.16,8.60,7.59,21.31,26.09,38.79,37.38,12.61,7.42,30.47,6.13
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,15.00,4.38,15.91,9.48,1.00,9.16,8.60,7.59,21.31,26.09,38.79,37.38,12.61,7.42,30.47,6.13
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
Number of WAL Segments,205.00,205.00,205.00,205.00,205.00,205.00,205.00,205.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00
Total WAL Size [GiB],3.20,3.20,3.20,3.20,3.20,3.20,3.20,3.20,6.41,6.41,6.41,6.41,6.41,6.41,6.41,6.41
WAL Segments Growth Rate [segments/s],0.42,0.04,0.00,0.00,0.42,0.02,0.00,0.00,0.53,0.21,0.00,0.00,0.60,0.17,0.00,0.00
WAL Growth Rate [MiB/s],6.72,0.60,0.00,0.00,6.70,0.34,0.00,0.00,8.53,3.41,0.00,0.00,9.53,2.64,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00

## With Metadata

Connection infos are added.

In [16]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
Memory Usage [MiB],10194.21,10704.20,7909.78,10307.04,9753.04,10314.32,9881.94,10340.26,13825.50,15339.01,12776.27,14741.79,14294.75,14915.17,12942.05,14883.51
Memory Usage Cached [MiB],15117.85,15627.85,10008.66,14794.89,15070.18,15237.97,14146.38,14828.10,25466.86,25151.62,20142.09,23713.12,25317.07,24723.73,20327.87,23842.79
CPU Utilization,0.46,0.60,0.64,0.11,0.01,0.01,0.63,0.44,0.47,0.94,0.65,0.02,1.10,0.90,1.03,1.27
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],66.69,75.17,79.42,105.36,0.00,0.00,394.30,26.02,6.30,137.51,795.93,0.00,178.14,46.72,791.63,66.18
CPU User Time [s],56.48,64.05,60.41,90.28,0.00,0.00,320.35,23.54,5.47,116.26,640.68,0.00,149.49,42.23,639.54,57.98
CPU System Time [s],10.21,11.12,19.01,15.08,0.00,0.00,73.94,2.47,0.83,21.25,155.24,0.00,28.65,4.49,152.09,8.19
Network Rx Total [MiB],0.04,13.80,1.89,0.05,0.10,12.64,3296.37,0.18,0.11,0.06,6599.80,1.78,0.19,0.20,6591.16,1.74
Network Tx Total [MiB],0.19,3009.48,0.09,0.03,1.78,3037.02,17.55,0.03,3.31,3.28,39.36,0.11,3.26,0.19,31.84,0.11
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.03,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.04,0.00
Core Utilization Variance [%],0.02,0.03,0.05,0.12,0.02,0.03,0.04,0.12,0.02,0.03,0.04,0.13,0.02,0.02,0.06,0.13
Max Core Utilization [%],0.80,1.13,1.24,4.31,0.80,1.12,1.14,4.31,1.17,1.65,1.33,4.77,0.68,1.16,1.67,3.64
I/O Wait [%],18.47,3.47,32.83,46.13,18.55,3.60,31.74,46.37,14.38,6.28,30.19,46.30,15.16,5.46,35.95,51.22
Total I/O Wait Time [s],0.39,1.11,679.24,0.60,0.39,1.11,623.77,0.60,0.46,0.34,653.65,0.65,3.14,0.57,800.81,0.40
Number of Idle Sessions,0.00,0.72,0.33,0.42,1.00,0.26,0.29,0.00,1.34,0.00,0.31,1.84,0.71,0.00,0.00,0.00
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,7.00,5.00,6.00,4.00,0.00,8.00,7.00,5.00,15.00,11.00,16.00,8.00,11.00,10.00,14.00,10.00
Number of Active Application Sessions,7.00,4.00,7.00,5.00,0.00,7.00,7.00,5.00,14.00,11.00,17.00,9.00,10.00,10.00,14.00,10.00
Longest Active Transaction,0.27,0.11,7.80,0.16,0.00,0.14,9.40,0.80,0.37,1.35,6.19,0.48,0.10,0.33,15.49,0.44
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,0.00,3.91,0.00,0.00,0.00,2.36,0.00,0.00,0.00,5.59,0.00,0.00,0.00,7.84,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,0.00,7.70,0.00,0.00,0.00,9.33,0.00,0.00,0.00,5.75,0.00,0.00,0.00,13.72,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,70669.00,0.00,563369.00,0.00,0.00,0.00,529543.00,0.00,141562.00,0.00,1058662.00,0.00,141480.00,0.00,1126841.00,0.00
Buffer Cache Hit Count,10477165.00,11842006.00,12992528.00,12533207.00,0.00,3157.00,4812344.00,13469687.00,26903773.00,27045341.00,14268105.00,18118575.00,24831964.00,27077595.00,24964455.00,27077595.00
Buffer Cache Hit Ratio,0.93,0.98,0.85,0.97,0.90,0.98,0.98,0.98,0.94,0.98,0.98,0.98,0.92,0.98,0.60,0.97
Index Scan Count,1720033.00,1881536.00,1899179.00,1881541.00,0.00,0.00,877615.00,1866637.00,878346.00,3776174.00,2157177.00,2249923.00,3736462.00,3773734.00,3755098.00,3773734.00
Index Tuple Fetch Count,7631973.00,8173972.00,8716253.00,8173977.00,0.00,0.00,3981563.00,8586085.00,3993638.00,17416366.00,9808542.00,9965419.00,16267390.00,17416794.00,16842092.00,17416794.00
Index Cache Hit Ratio,0.68,0.99,0.96,0.99,0.39,0.99,0.99,0.99,0.79,0.99,0.99,0.99,0.56,0.99,0.55,0.99
Table Buffer Hit Count,5418802.00,6225638.00,7381297.00,6913083.00,0.00,0.00,2243186.00,7891373.00,3094024.00,15753870.00,5881945.00,7012236.00,13814380.00,15800584.00,13875674.00,15800584.00
Table Blocks Read Count,0.00,0.00,492426.00,0.00,0.00,0.00,492388.00,0.00,0.00,0.00,984776.00,0.00,0.00,0.00,984840.00,0.00
Table Cache Hit Ratio,0.92,0.97,0.61,0.96,0.90,0.97,0.98,0.97,0.91,0.97,0.97,0.98,0.92,0.97,0.36,0.96
Total Cache Hit Ratio,0.93,0.98,0.64,0.97,0.90,0.98,0.98,0.98,0.92,0.98,0.98,0.98,0.92,0.98,0.38,0.97
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,15.00,4.38,15.91,9.48,1.00,9.16,8.60,7.59,21.31,26.09,38.79,37.38,12.61,7.42,30.47,6.13
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,15.00,4.38,15.91,9.48,1.00,9.16,8.60,7.59,21.31,26.09,38.79,37.38,12.61,7.42,30.47,6.13
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
Number of WAL Segments,205.00,205.00,205.00,205.00,205.00,205.00,205.00,205.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00
Total WAL Size [GiB],3.20,3.20,3.20,3.20,3.20,3.20,3.20,3.20,6.41,6.41,6.41,6.41,6.41,6.41,6.41,6.41
WAL Segments Growth Rate [segments/s],0.42,0.04,0.00,0.00,0.42,0.02,0.00,0.00,0.53,0.21,0.00,0.00,0.60,0.17,0.00,0.00
WAL Growth Rate [MiB/s],6.72,0.60,0.00,0.00,6.70,0.34,0.00,0.00,8.53,3.41,0.00,0.00,9.53,2.64,0.00,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855
configuration,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,685.00,685.00,685.00,685.00,683.00,683.00,683.00,683.00,977.00,977.00,977.00,977.00,979.00,979.00,979.00,979.00
time_ingest,302.00,302.00,302.00,302.00,300.00,300.00,300.00,300.00,439.00,439.00,439.00,439.00,440.00,440.00,440.00,440.00
time_check,379.00,379.00,379.00,379.00,378.00,378.00,378.00,378.00,533.00,533.00,533.00,533.00,535.00,535.00,535.00,535.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
tenant,0,0,0,0,1,1,1,1,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247634,247634,247634,247635,247634,247634,247635,247635,247631,247631,247632,247632,247629,247629,247630,247630
host_datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
host_volume_size,15G,15G,15G,15G,15G,15G,15G,15G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G,16G,16G
host_cuda,,,,,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
loading_parameters_PODS_TOTAL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
loading_parameters_PODS_PARALLEL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
loading_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
benchmarking_parameters_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
benchmarking_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [17]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855
configuration,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2
type_tenants,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

# Time Series of a Single Metric for a Single Experiment

This is particularly important if you require a customized aggregation or wish to monitor a component over time.

In [18]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_per_phase(code, metric=metric, component='stream')
df.T

,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2
0,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
1,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
2,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
3,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
4,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
5,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
6,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
7,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
8,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
9,9751.98,10427.98,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
10,9751.98,10427.98,5859.45,10305.46,9753.04,10314.32,10330.17,10358.62
11,9751.98,10427.98,5859.45,10305.46,9753.04,10314.32,10330.17,10358.62
12,9751.98,10427.98,5859.45,10305.46,9753.04,10314.32,10330.17,10358.62
13,9751.98,10427.98,5859.45,10305.46,9753.04,10314.32,10330.17,10358.62
14,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
15,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
16,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
17,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
18,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
19,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
20,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
21,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
22,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
23,11889.42,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
24,11889.42,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
25,11889.42,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
26,11889.42,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
27,11889.42,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
28,11889.42,12889.67,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
29,NaN,12889.67,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
30,NaN,12889.67,6622.16,10305.46,NaN,10314.32,10330.17,10358.62
31,NaN,12889.67,6622.16,10305.46,NaN,NaN,10330.17,10358.62
32,NaN,NaN,6622.16,10357.53,NaN,NaN,10330.17,NaN
33,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
34,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
35,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
36,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
37,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
38,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
39,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
40,NaN,NaN,8638.36,NaN,NaN,NaN,10330.17,NaN
41,NaN,NaN,8638.36,NaN,NaN,NaN,10330.17,NaN
42,NaN,NaN,8638.36,NaN,NaN,NaN,10330.17,NaN
43,NaN,NaN,8638.36,NaN,NaN,NaN,10330.17,NaN
44,NaN,NaN,8638.36,NaN,NaN,NaN,7045.68,NaN
45,NaN,NaN,8638.36,NaN,NaN,NaN,7045.68,NaN
46,NaN,NaN,8638.36,NaN,NaN,NaN,7045.68,NaN
47,NaN,NaN,8638.36,NaN,NaN,NaN,7045.68,NaN
48,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
49,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
50,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
51,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
52,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
53,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
54,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
55,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
56,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
57,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
58,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
59,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
60,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
61,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
62,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
63,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
64,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
65,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
66,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
67,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
68,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
69,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
70,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
71,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
72,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
73,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
74,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
75,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
76,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
77,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
78,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
79,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
80,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
81,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
82,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
83,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
84,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
85,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
86,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
87,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
88,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
89,NaN,NaN,10373.82,NaN,NaN,NaN,NaN,NaN
90,NaN,NaN,10373.82,NaN,NaN,NaN,NaN,NaN
91,NaN,NaN,10373.82,NaN,NaN,NaN,NaN,NaN

## With Metadata

Connection infos are added.

In [19]:
df = collect.add_metadata(df)
df.T

combine on index and column 'phase'

phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2
0,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
1,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
2,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
3,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
4,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
5,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
6,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
7,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
8,9751.98,10316.01,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
9,9751.98,10427.98,5859.45,10305.46,9753.04,10314.32,10330.17,10299.85
10,9751.98,10427.98,5859.45,10305.46,9753.04,10314.32,10330.17,10358.62
11,9751.98,10427.98,5859.45,10305.46,9753.04,10314.32,10330.17,10358.62
12,9751.98,10427.98,5859.45,10305.46,9753.04,10314.32,10330.17,10358.62
13,9751.98,10427.98,5859.45,10305.46,9753.04,10314.32,10330.17,10358.62
14,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
15,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
16,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
17,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
18,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
19,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
20,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
21,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
22,9751.98,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
23,11889.42,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
24,11889.42,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
25,11889.42,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
26,11889.42,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
27,11889.42,10427.98,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
28,11889.42,12889.67,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
29,NaN,12889.67,6622.16,10305.46,9753.04,10314.32,10330.17,10358.62
30,NaN,12889.67,6622.16,10305.46,NaN,10314.32,10330.17,10358.62
31,NaN,12889.67,6622.16,10305.46,NaN,NaN,10330.17,10358.62
32,NaN,NaN,6622.16,10357.53,NaN,NaN,10330.17,NaN
33,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
34,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
35,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
36,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
37,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
38,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
39,NaN,NaN,6622.16,NaN,NaN,NaN,10330.17,NaN
40,NaN,NaN,8638.36,NaN,NaN,NaN,10330.17,NaN
41,NaN,NaN,8638.36,NaN,NaN,NaN,10330.17,NaN
42,NaN,NaN,8638.36,NaN,NaN,NaN,10330.17,NaN
43,NaN,NaN,8638.36,NaN,NaN,NaN,10330.17,NaN
44,NaN,NaN,8638.36,NaN,NaN,NaN,7045.68,NaN
45,NaN,NaN,8638.36,NaN,NaN,NaN,7045.68,NaN
46,NaN,NaN,8638.36,NaN,NaN,NaN,7045.68,NaN
47,NaN,NaN,8638.36,NaN,NaN,NaN,7045.68,NaN
48,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
49,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
50,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
51,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
52,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
53,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
54,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
55,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
56,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
57,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
58,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
59,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
60,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
61,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
62,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
63,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
64,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
65,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
66,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
67,NaN,NaN,8638.36,NaN,NaN,NaN,9080.14,NaN
68,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
69,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
70,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
71,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
72,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
73,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
74,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
75,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
76,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
77,NaN,NaN,8638.36,NaN,NaN,NaN,10246.64,NaN
78,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
79,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
80,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
81,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
82,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
83,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
84,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
85,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
86,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
87,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
88,NaN,NaN,10373.82,NaN,NaN,NaN,10246.64,NaN
89,NaN,NaN,10373.82,NaN,NaN,NaN,NaN,NaN
90,NaN,NaN,10373.82,NaN,NaN,NaN,NaN,NaN
91,NaN,NaN,10373.82,NaN,NaN,NaN,NaN,NaN
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217
configuration,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1
experiment_run,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,685.00,685.00,685.00,685.00,683.00,683.00,683.00,683.00
time_ingest,302.00,302.00,302.00,302.00,300.00,300.00,300.00,300.00
time_check,379.00,379.00,379.00,379.00,378.00,378.00,378.00,378.00
terminals,0,0,0,0,0,0,0,0
pods,1,1,1,1,1,1,1,1
tenant,0,0,0,0,1,1,1,1
num_worker,0,0,0,0,0,0,0,0
type_tenants,container,container,container,container,container,container,container,container
num_tenants,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False
datadisk,8188,8188,8188,8188,8188,8188,8188,8188
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247634,247634,247634,247635,247634,247634,247635,247635
host_datadisk,8188,8188,8188,8188,8188,8188,8188,8188
host_volume_size,15G,15G,15G,15G,15G,15G,15G,15G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G
host_cuda,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,3,3
loading_parameters_PODS_TOTAL,1,1,1,1,1,1,1,1
loading_parameters_PODS_PARALLEL,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container
loading_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2
benchmarking_parameters_SF,3,3,3,3,3,3,3,3
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,container,container,container,container,container,container,container,container
benchmarking_parameters_TENANT_NUM,2,2,2,2,2,2,2,2
benchmarking_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container
benchmarking_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [20]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head().T

phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1
code,1776772217,1776772217,1776772217,1776772217,1776772217
configuration,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-1
experiment_run,1,1,2,2,1
client,1,2,1,2,1
type_tenants,container,container,container,container,container
num_tenants,2,2,2,2,2
vol_tenants,False,False,False,False,False

# Time Series of a Single Metric for All Experiments per Tenancy

This is particularly important if you require a customized aggregation or wish to monitor a component over time.
Data is stacked here (long format).

In [21]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_all_multitenant(metric=metric)
df.head(20)

,timestamp,code,experiment_run,client,type_tenants,vol_tenants,num_tenants,metric,component,value,configuration
0,0,1776768855,1,1,schema,False,2,total_cpu_memory,stream,27294.55,PostgreSQL-BHT-2
1,0,1776768855,1,2,schema,False,2,total_cpu_memory,stream,29542.11,PostgreSQL-BHT-2
2,0,1776768855,2,1,schema,False,2,total_cpu_memory,stream,29602.45,PostgreSQL-BHT-2
3,0,1776768855,2,2,schema,False,2,total_cpu_memory,stream,29486.66,PostgreSQL-BHT-2
4,0,1776770536,1,1,database,False,2,total_cpu_memory,stream,27345.76,PostgreSQL-BHT-2
5,0,1776770536,1,2,database,False,2,total_cpu_memory,stream,29588.70,PostgreSQL-BHT-2
6,0,1776770536,2,1,database,False,2,total_cpu_memory,stream,29638.67,PostgreSQL-BHT-2
7,0,1776770536,2,2,database,False,2,total_cpu_memory,stream,29483.57,PostgreSQL-BHT-2
8,0,1776772217,1,1,container,False,2,total_cpu_memory,stream,19505.01,PostgreSQL-BHT-1-1
9,0,1776772217,1,2,container,False,2,total_cpu_memory,stream,20630.34,PostgreSQL-BHT-1-1
10,0,1776772217,2,1,container,False,2,total_cpu_memory,stream,16189.62,PostgreSQL-BHT-1-1
11,0,1776772217,2,2,container,False,2,total_cpu_memory,stream,20605.31,PostgreSQL-BHT-1-1
12,1,1776768855,1,1,schema,False,2,total_cpu_memory,stream,27294.55,PostgreSQL-BHT-2
13,1,1776768855,1,2,schema,False,2,total_cpu_memory,stream,29542.11,PostgreSQL-BHT-2
14,1,1776768855,2,1,schema,False,2,total_cpu_memory,stream,29602.45,PostgreSQL-BHT-2
15,1,1776768855,2,2,schema,False,2,total_cpu_memory,stream,29486.66,PostgreSQL-BHT-2
16,1,1776770536,1,1,database,False,2,total_cpu_memory,stream,27345.76,PostgreSQL-BHT-2
17,1,1776770536,1,2,database,False,2,total_cpu_memory,stream,29588.70,PostgreSQL-BHT-2
18,1,1776770536,2,1,database,False,2,total_cpu_memory,stream,29638.67,PostgreSQL-BHT-2
19,1,1776770536,2,2,database,False,2,total_cpu_memory,stream,29483.57,PostgreSQL-BHT-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [22]:
df[['timestamp', 'configuration', 'value',  'type_tenants']].head(20)

    timestamp       configuration    value type_tenants
0           0    PostgreSQL-BHT-2 27294.55       schema
1           0    PostgreSQL-BHT-2 29542.11       schema
2           0    PostgreSQL-BHT-2 29602.45       schema
3           0    PostgreSQL-BHT-2 29486.66       schema
4           0    PostgreSQL-BHT-2 27345.76     database
5           0    PostgreSQL-BHT-2 29588.70     database
6           0    PostgreSQL-BHT-2 29638.67     database
7           0    PostgreSQL-BHT-2 29483.57     database
8           0  PostgreSQL-BHT-1-1 19505.01    container
9           0  PostgreSQL-BHT-1-1 20630.34    container
10          0  PostgreSQL-BHT-1-1 16189.62    container
11          0  PostgreSQL-BHT-1-1 20605.31    container
12          1    PostgreSQL-BHT-2 27294.55       schema
13          1    PostgreSQL-BHT-2 29542.11       schema
14          1    PostgreSQL-BHT-2 29602.45       schema
15          1    PostgreSQL-BHT-2 29486.66       schema
16          1    PostgreSQL-BHT-2 27345.76     database
17          1    PostgreSQL-BHT-2 29588.70     database
18          1    PostgreSQL-BHT-2 29638.67     database
19          1    PostgreSQL-BHT-2 29483.57     database

## With Metadata

Connection infos are added.

In [23]:
df=collect.add_metadata(df)
df = df.sort_values(['timestamp'])
df[['timestamp', 'value']].head(8)

combine on columns code experiment_run client type_tenants num_tenants

                            timestamp    value
1776772217-1-1-container-2          0 19505.01
1776770536-1-1-database-2           0 27345.76
1776768855-2-1-schema-2             0 29602.45
1776772217-2-2-container-2          0 20605.31
1776768855-1-2-schema-2             0 29542.11
1776770536-2-2-database-2           0 29483.57
1776772217-2-1-container-2          0 16189.62
1776770536-1-2-database-2           0 29588.70

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [24]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head().T

,1776772217-1-1-container-2,1776770536-1-1-database-2,1776768855-2-1-schema-2,1776772217-2-2-container-2,1776768855-1-2-schema-2
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776770536-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776768855-PostgreSQL-BHT-2-1-2
code,1776772217,1776770536,1776768855,1776772217,1776768855
configuration,PostgreSQL-BHT-1-1,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-1-1,PostgreSQL-BHT-2
experiment_run,1,1,2,2,1
client,1,1,1,2,2
type_tenants,container,database,schema,container,schema
num_tenants,2,2,2,2,2
vol_tenants,False,False,False,False,False

## Custom Aggregation and Scale

We here aggregate CPU utilization by max per phase.

In [25]:
metric = 'total_cpu_util'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["code", "experiment_run", "client", "type_tenants", "num_tenants"])["value"]
      .max()
      .reset_index()
)
df_agg.index.name = 'Max ' + collect.df_metrics.loc[metric]['title']
df_agg

,code,experiment_run,client,type_tenants,num_tenants,value
Max CPU Utilization,,,,,,
0,1776768855,1,1,schema,2,14.25
1,1776768855,1,2,schema,2,2.83
2,1776768855,2,1,schema,2,3.06
3,1776768855,2,2,schema,2,4.15
4,1776770536,1,1,database,2,3.43
5,1776770536,1,2,database,2,7.49
6,1776770536,2,1,database,2,3.18
7,1776770536,2,2,database,2,0.03
8,1776772217,1,1,container,2,2.20
9,1776772217,1,2,container,2,3.13
10,1776772217,2,1,container,2,1.21
11,1776772217,2,2,container,2,3.43

# Performance Results per Connection

In [26]:
df_performance = collect.get_performance_per_connection()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-2-2-2
total_timer_execution,0.71,0.72,0.76,0.73,1.30,1.29,0.75,0.72,0.75,0.76,0.75,0.78,1.33,1.35,0.75,0.72,0.71,0.78,0.75,0.75,1.38,1.40,0.73,0.78
Power@Size [~Q/h],15197.72,14943.38,14211.46,14799.72,8280.05,8352.95,14314.91,15093.65,14375.18,14118.39,14429.86,13761.42,8135.97,7982.87,14495.36,14978.59,15168.62,13825.46,14395.33,14325.80,7804.80,7731.92,14822.92,13928.05
Geo Times [s],0.71,0.72,0.76,0.73,1.30,1.29,0.75,0.72,0.75,0.76,0.75,0.78,1.33,1.35,0.75,0.72,0.71,0.78,0.75,0.75,1.38,1.40,0.73,0.78
configuration,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2
connection,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-2-2-2
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-2-2
SF,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00
experiment_run,1,1,1,1,2,2,2,2,1,1,1,1,2,2,2,2,1,1,1,1,2,2,2,2
client,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
time [s],28,29,31,30,91,88,32,31,30,29,29,31,95,95,31,29,29,30,32,31,103,110,28,30
pod_count,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
Throughput@Size,8485.71,8193.10,7664.52,7920.00,2610.99,2700.00,7425.00,7664.52,7920.00,8193.10,8193.10,7664.52,2501.05,2501.05,7664.52,8193.10,8193.10,7920.00,7425.00,7664.52,2306.80,2160.00,8485.71,7920.00
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855

## With Metadata

Connection infos are added.

In [27]:
df = collect.add_metadata(df_performance)
df.T

combine on index

,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-2-2-2
total_timer_execution,0.71,0.72,0.76,0.73,1.30,1.29,0.75,0.72,0.75,0.76,0.75,0.78,1.33,1.35,0.75,0.72,0.71,0.78,0.75,0.75,1.38,1.40,0.73,0.78
Power@Size [~Q/h],15197.72,14943.38,14211.46,14799.72,8280.05,8352.95,14314.91,15093.65,14375.18,14118.39,14429.86,13761.42,8135.97,7982.87,14495.36,14978.59,15168.62,13825.46,14395.33,14325.80,7804.80,7731.92,14822.92,13928.05
Geo Times [s],0.71,0.72,0.76,0.73,1.30,1.29,0.75,0.72,0.75,0.76,0.75,0.78,1.33,1.35,0.75,0.72,0.71,0.78,0.75,0.75,1.38,1.40,0.73,0.78
configuration,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2
connection,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-2-2-2
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-2-2
SF,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00
experiment_run,1,1,1,1,2,2,2,2,1,1,1,1,2,2,2,2,1,1,1,1,2,2,2,2
client,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
time [s],28,29,31,30,91,88,32,31,30,29,29,31,95,95,31,29,29,30,32,31,103,110,28,30
pod_count,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
Throughput@Size,8485.71,8193.10,7664.52,7920.00,2610.99,2700.00,7425.00,7664.52,7920.00,8193.10,8193.10,7664.52,2501.05,2501.05,7664.52,8193.10,8193.10,7920.00,7425.00,7664.52,2306.80,2160.00,8485.71,7920.00
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855,1776768855
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,685.00,683.00,685.00,683.00,685.00,683.00,685.00,683.00,977.00,977.00,977.00,977.00,977.00,977.00,977.00,977.00,979.00,979.00,979.00,979.00,979.00,979.00,979.00,979.00
time_ingest,302.00,300.00,302.00,300.00,302.00,300.00,302.00,300.00,439.00,439.00,439.00,439.00,439.00,439.00,439.00,439.00,440.00,440.00,440.00,440.00,440.00,440.00,440.00,440.00
time_check,379.00,378.00,379.00,378.00,379.00,378.00,379.00,378.00,533.00,533.00,533.00,533.00,533.00,533.00,533.00,533.00,535.00,535.00,535.00,535.00,535.00,535.00,535.00,535.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
tenant,0,1,0,1,0,1,0,1,,,,,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16368,16368,16368,16368,16353,16353,16353,16353,16353,16353,16353,16353
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,,,,,,,,,,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247634,247634,247634,247634,247634,247635,247635,247635,247631,247631,247631,247631,247632,247632,247632,247632,247629,247629,247629,247629,247630,247630,247630,247630
host_datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16368,16368,16368,16368,16353,16353,16353,16353,16353,16353,16353,16353
host_volume_size,15G,15G,15G,15G,15G,15G,15G,15G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G,16G
host_cuda,,,,,,,,,,,,,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
loading_parameters_PODS_TOTAL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_PODS_PARALLEL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
loading_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
benchmarking_parameters_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,database,database,database,database,schema,schema,schema,schema,schema,schema,schema,schema
benchmarking_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

# Performance Results per Phase

In [28]:
df_performance = collect.get_performance_aggregated_per_phase()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)

In [29]:
df_performance.T

,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
configuration,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
total_timer_execution,0.71,0.76,1.30,0.75,0.72,0.73,1.29,0.72,0.76,0.77,1.34,0.73,0.75,0.75,1.39,0.75
Power@Size [~Q/h],15197.72,14211.46,8280.05,14314.91,14943.38,14799.72,8352.95,15093.65,14246.21,14091.68,8059.06,14734.99,14481.47,14360.52,7768.27,14368.52
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855
pod_count,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
SF,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00
time [s],28,31,91,32,29,30,88,31,30,31,95,31,30,32,110,30
client,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2
Throughput@Size,8485.71,7664.52,2610.99,7425.00,8193.10,7920.00,2700.00,7664.52,15840.00,15329.03,5002.11,15329.03,15840.00,14850.00,4320.00,15840.00
num_of_queries,22,22,22,22,22,22,22,22,44,44,44,44,44,44,44,44

## With Metadata

Connection infos are added.

In [30]:
df = collect.add_metadata(df_performance)
df.T

combine on index and column 'phase'

phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
configuration,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
total_timer_execution,0.71,0.76,1.30,0.75,0.72,0.73,1.29,0.72,0.76,0.77,1.34,0.73,0.75,0.75,1.39,0.75
Power@Size [~Q/h],15197.72,14211.46,8280.05,14314.91,14943.38,14799.72,8352.95,15093.65,14246.21,14091.68,8059.06,14734.99,14481.47,14360.52,7768.27,14368.52
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855
pod_count,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
SF,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00
time [s],28,31,91,32,29,30,88,31,30,31,95,31,30,32,110,30
client,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2
Throughput@Size,8485.71,7664.52,2610.99,7425.00,8193.10,7920.00,2700.00,7664.52,15840.00,15329.03,5002.11,15329.03,15840.00,14850.00,4320.00,15840.00
num_of_queries,22,22,22,22,22,22,22,22,44,44,44,44,44,44,44,44
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,685.00,685.00,685.00,685.00,683.00,683.00,683.00,683.00,977.00,977.00,977.00,977.00,979.00,979.00,979.00,979.00
time_ingest,302.00,302.00,302.00,302.00,300.00,300.00,300.00,300.00,439.00,439.00,439.00,439.00,440.00,440.00,440.00,440.00
time_check,379.00,379.00,379.00,379.00,378.00,378.00,378.00,378.00,533.00,533.00,533.00,533.00,535.00,535.00,535.00,535.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
tenant,0,0,0,0,1,1,1,1,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_GPU,,,,,,,,,,,,,,,,
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_disk,247634,247634,247634,247635,247634,247634,247635,247635,247631,247631,247632,247632,247629,247629,247630,247630
host_datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
host_volume_size,15G,15G,15G,15G,15G,15G,15G,15G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G,16G,16G
host_cuda,,,,,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
loading_parameters_PODS_TOTAL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
loading_parameters_PODS_PARALLEL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
loading_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
benchmarking_parameters_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
benchmarking_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [31]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855
configuration,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2
type_tenants,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Get Non-Constant Attributes

These attributes are (most probably) used to analyze performance.

In [32]:
collectors.get_non_constant(df).T

phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
configuration,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776772217-PostgreSQL-BHT-1-1,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
total_timer_execution,0.71,0.76,1.30,0.75,0.72,0.73,1.29,0.72,0.76,0.77,1.34,0.73,0.75,0.75,1.39,0.75
Power@Size [~Q/h],15197.72,14211.46,8280.05,14314.91,14943.38,14799.72,8352.95,15093.65,14246.21,14091.68,8059.06,14734.99,14481.47,14360.52,7768.27,14368.52
code,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855
pod_count,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
time [s],28,31,91,32,29,30,88,31,30,31,95,31,30,32,110,30
client,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2
Throughput@Size,8485.71,7664.52,2610.99,7425.00,8193.10,7920.00,2700.00,7664.52,15840.00,15329.03,5002.11,15329.03,15840.00,14850.00,4320.00,15840.00
num_of_queries,22,22,22,22,22,22,22,22,44,44,44,44,44,44,44,44
time_load,685.00,685.00,685.00,685.00,683.00,683.00,683.00,683.00,977.00,977.00,977.00,977.00,979.00,979.00,979.00,979.00
time_ingest,302.00,302.00,302.00,302.00,300.00,300.00,300.00,300.00,439.00,439.00,439.00,439.00,440.00,440.00,440.00,440.00
time_check,379.00,379.00,379.00,379.00,378.00,378.00,378.00,378.00,533.00,533.00,533.00,533.00,535.00,535.00,535.00,535.00
pods,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
tenant,0,0,0,0,1,1,1,1,,,,,,,,
type_tenants,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
host_disk,247634,247634,247634,247635,247634,247634,247635,247635,247631,247631,247632,247632,247629,247629,247630,247630
host_datadisk,8188,8188,8188,8188,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
host_volume_size,15G,15G,15G,15G,15G,15G,15G,15G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G,16G,16G
loading_parameters_PODS_TOTAL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
loading_parameters_PODS_PARALLEL,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2
loading_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
benchmarking_parameters_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
benchmarking_parameters_BEXHOMA_TENANT_BY,container,container,container,container,container,container,container,container,database,database,database,database,schema,schema,schema,schema
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2

# Performance per Tenancy

In [33]:
df_performance = collect.get_performance_aggregated_per_phase_multitenant()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)

df_performance.T

,1776772217_1_1_container_2,1776772217_1_2_container_2,1776772217_2_1_container_2,1776772217_2_2_container_2,1776770536_1_1_database_2,1776770536_1_2_database_2,1776770536_2_1_database_2,1776770536_2_2_database_2,1776768855_1_1_schema_2,1776768855_1_2_schema_2,1776768855_2_1_schema_2,1776768855_2_2_schema_2
configuration,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
total_timer_execution,0.72,0.74,1.30,0.73,0.76,0.77,1.34,0.73,0.75,0.75,1.39,0.75
Power@Size [~Q/h],15070.02,14502.61,8316.42,14699.13,14246.21,14091.68,8059.06,14734.99,14481.47,14360.52,7768.27,14368.52
code,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855
pod_count,2,2,2,2,2,2,2,2,2,2,2,2
SF,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00
time [s],29,31,91,32,30,31,95,31,30,32,110,30
client,1,2,1,2,1,2,1,2,1,2,1,2
Throughput@Size,16386.21,15329.03,5221.98,14850.00,15840.00,15329.03,5002.11,15329.03,15840.00,14850.00,4320.00,15840.00
num_of_queries,44,44,44,44,44,44,44,44,44,44,44,44
type_tenants,container,container,container,container,database,database,database,database,schema,schema,schema,schema
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False

## With Metadata

Connection infos are added.

In [34]:
df = collect.add_metadata(df_performance)
df.T

combine on columns code experiment_run client type_tenants num_tenants

,1776772217-1-1-container-2,1776772217-1-2-container-2,1776772217-2-1-container-2,1776772217-2-2-container-2,1776770536-1-1-database-2,1776770536-1-2-database-2,1776770536-2-1-database-2,1776770536-2-2-database-2,1776768855-1-1-schema-2,1776768855-1-2-schema-2,1776768855-2-1-schema-2,1776768855-2-2-schema-2
Power@Size [~Q/h],15070.02,14502.61,8316.42,14699.13,14246.21,14091.68,8059.06,14734.99,14481.47,14360.52,7768.27,14368.52
SF,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00
Throughput@Size,16386.21,15329.03,5221.98,14850.00,15840.00,15329.03,5002.11,15329.03,15840.00,14850.00,4320.00,15840.00
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
benchmarking_parameters_BEXHOMA_TENANT_BY,container,container,container,container,database,database,database,database,schema,schema,schema,schema
benchmarking_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3
benchmarking_parameters_TENANT_BY,container,container,container,container,database,database,database,database,schema,schema,schema,schema
benchmarking_parameters_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2
code,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855
configuration,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2
datadisk,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128
host_GPU,,,,,,,,,,,,
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_cuda,,,,,,,,,,,,
host_datadisk,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
host_disk,247634,247634,247634,247635,247631,247631,247632,247632,247629,247629,247630,247630
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_volume_size,15G,15G,15G,15G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G,16G,16G
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_TENANT_BY,container,container,container,container,database,database,database,database,schema,schema,schema,schema
loading_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_PODS_PARALLEL,1,1,1,1,2,2,2,2,2,2,2,2
loading_parameters_PODS_TOTAL,1,1,1,1,2,2,2,2,2,2,2,2
loading_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_TPCH_TABLE,,,,,,,,,,,,
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
num_of_queries,44,44,44,44,44,44,44,44,44,44,44,44
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
pod_count,2,2,2,2,2,2,2,2,2,2,2,2
pods,1,1,1,1,2,2,2,2,2,2,2,2
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
tenant,0,0,0,0,,,,,,,,
terminals,0,0,0,0,0,0,0,0,0,0,0,0
time [s],29,31,91,32,30,31,95,31,30,32,110,30
time_check,379.00,379.00,379.00,379.00,533.00,533.00,533.00,533.00,535.00,535.00,535.00,535.00
time_ingest,302.00,302.00,302.00,302.00,439.00,439.00,439.00,439.00,440.00,440.00,440.00,440.00
time_load,685.00,685.00,685.00,685.00,977.00,977.00,977.00,977.00,979.00,979.00,979.00,979.00
total_timer_execution,0.72,0.74,1.30,0.73,0.76,0.77,1.34,0.73,0.75,0.75,1.39,0.75
type_tenants,container,container,container,container,database,database,database,database,schema,schema,schema,schema
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [35]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

,1776772217-1-1-container-2,1776772217-1-2-container-2,1776772217-2-1-container-2,1776772217-2-2-container-2,1776770536-1-1-database-2,1776770536-1-2-database-2,1776770536-2-1-database-2,1776770536-2-2-database-2,1776768855-1-1-schema-2,1776768855-1-2-schema-2,1776768855-2-1-schema-2,1776768855-2-2-schema-2
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
code,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855
configuration,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2
type_tenants,container,container,container,container,database,database,database,database,schema,schema,schema,schema
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False

## Get Non-Constant Attributes

These attributes are (most probably) used to analyze performance.

In [36]:
collectors.get_non_constant(df).T

,1776772217-1-1-container-2,1776772217-1-2-container-2,1776772217-2-1-container-2,1776772217-2-2-container-2,1776770536-1-1-database-2,1776770536-1-2-database-2,1776770536-2-1-database-2,1776770536-2-2-database-2,1776768855-1-1-schema-2,1776768855-1-2-schema-2,1776768855-2-1-schema-2,1776768855-2-2-schema-2
Power@Size [~Q/h],15070.02,14502.61,8316.42,14699.13,14246.21,14091.68,8059.06,14734.99,14481.47,14360.52,7768.27,14368.52
Throughput@Size,16386.21,15329.03,5221.98,14850.00,15840.00,15329.03,5002.11,15329.03,15840.00,14850.00,4320.00,15840.00
benchmarking_parameters_BEXHOMA_TENANT_BY,container,container,container,container,database,database,database,database,schema,schema,schema,schema
benchmarking_parameters_TENANT_BY,container,container,container,container,database,database,database,database,schema,schema,schema,schema
client,1,2,1,2,1,2,1,2,1,2,1,2
code,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855
configuration,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2
datadisk,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
host_datadisk,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
host_disk,247634,247634,247634,247635,247631,247631,247632,247632,247629,247629,247630,247630
host_volume_size,15G,15G,15G,15G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G,16G,16G
loading_parameters_BEXHOMA_TENANT_BY,container,container,container,container,database,database,database,database,schema,schema,schema,schema
loading_parameters_PODS_PARALLEL,1,1,1,1,2,2,2,2,2,2,2,2
loading_parameters_PODS_TOTAL,1,1,1,1,2,2,2,2,2,2,2,2
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
pods,1,1,1,1,2,2,2,2,2,2,2,2
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
tenant,0,0,0,0,,,,,,,,
time [s],29,31,91,32,30,31,95,31,30,32,110,30
time_check,379.00,379.00,379.00,379.00,533.00,533.00,533.00,533.00,535.00,535.00,535.00,535.00
time_ingest,302.00,302.00,302.00,302.00,439.00,439.00,439.00,439.00,440.00,440.00,440.00,440.00
time_load,685.00,685.00,685.00,685.00,977.00,977.00,977.00,977.00,979.00,979.00,979.00,979.00
total_timer_execution,0.72,0.74,1.30,0.73,0.76,0.77,1.34,0.73,0.75,0.75,1.39,0.75
type_tenants,container,container,container,container,database,database,database,database,schema,schema,schema,schema

# Performance at Ingestion

In [37]:
df = collect.get_loading_per_run()
df.T

,1776772217-PostgreSQL-BHT-1-0-1,1776772217-PostgreSQL-BHT-1-0-2,1776772217-PostgreSQL-BHT-1-1-1,1776772217-PostgreSQL-BHT-1-1-2,1776770536-PostgreSQL-BHT-2-1,1776770536-PostgreSQL-BHT-2-2,1776768855-PostgreSQL-BHT-2-1,1776768855-PostgreSQL-BHT-2-2
code,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776768855,1776768855
configuration,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2
experiment_run,1,2,1,2,1,2,1,2
SF,3,3,3,3,3,3,3,3
time_load,685.00,685.00,683.00,683.00,977.00,977.00,979.00,979.00
time_ingest,302.00,302.00,300.00,300.00,439.00,439.00,440.00,440.00
time_check,379.00,379.00,378.00,378.00,533.00,533.00,535.00,535.00
pods,1,1,1,1,2,2,2,2
type_tenants,container,container,container,container,database,database,schema,schema
num_tenants,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False
Throughput [SF/h],15.77,15.77,15.81,15.81,11.05,11.05,11.03,11.03

# Performance at Ingestion per Tenancy

In [38]:
df = collect.get_loading_per_run_multitenant()
df.T

,1776772217-PostgreSQL-BHT-1-1-1,1776772217-PostgreSQL-BHT-1-1-2,1776770536-PostgreSQL-BHT-2-1,1776770536-PostgreSQL-BHT-2-2,1776768855-PostgreSQL-BHT-2-1,1776768855-PostgreSQL-BHT-2-2
code,1776772217,1776772217,1776770536,1776770536,1776768855,1776768855
experiment_run,1,2,1,2,1,2
type_tenants,container,container,database,database,schema,schema
vol_tenants,False,False,False,False,False,False
num_tenants,2,2,2,2,2,2
SF,3,3,3,3,3,3
configuration,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2,PostgreSQL-BHT-2
time_load,685.00,685.00,977.00,977.00,979.00,979.00
time_ingest,302.00,302.00,439.00,439.00,440.00,440.00
time_check,379.00,379.00,533.00,533.00,535.00,535.00
pods,1,1,2,2,2,2
Throughput [SF/h],15.77,15.77,11.05,11.05,11.03,11.03

# Combine Performance and Monitoring

This includes filtering for the first client and incorporating efficiency metrics to track performance relative to resource usage.

In [39]:
client = 1

df_performance_monitoring = collect.get_monitoring_aggregated_per_phase_multitenant(type="stream")
df_performance = collect.get_performance_aggregated_per_phase_multitenant()
#merged_df = pd.merge(df_performance, df_performance_monitoring, left_index=True, right_index=True, how='left')
cols_to_use = [c for c in df_performance_monitoring.columns if c not in df_performance.columns]
# 2. Diese Spalten rechts an df hängen
merged_df = df_performance.join(df_performance_monitoring[cols_to_use], how='inner')
merged_df = collect.add_metadata(merged_df).copy()

#merged_df = merged_df[merged_df['client'] == client]

merged_df['RAM/Throughput'] = merged_df['Memory Usage Cached [MiB]'] / (merged_df['Throughput@Size'])
merged_df['CPUs/Throughput'] = merged_df['CPU Utilization'] / (merged_df['Throughput@Size'] / 3600.)
#merged_df['E_RAM'] = (merged_df['Throughput@Size']) / merged_df['Max RAM [Gb]']
#merged_df['E_CPU'] = (merged_df['Throughput@Size'] * 3600.) / merged_df['CPU [CPUs]']
merged_df['E_CPU'] = (10. * merged_df['num_tenants'] * merged_df['num_of_queries'] * merged_df['SF']) / merged_df['CPU Utilization']
merged_df['E_RAM'] = (10. * merged_df['num_tenants'] * merged_df['num_of_queries'] * merged_df['SF']) / merged_df['Memory Usage Cached [MiB]']

merged_df.T

combine on index and column 'phase'
combine on columns code experiment_run client type_tenants num_tenants

,1776772217-1-1-container-2,1776772217-1-2-container-2,1776772217-2-1-container-2,1776772217-2-2-container-2,1776770536-1-1-database-2,1776770536-1-2-database-2,1776770536-2-1-database-2,1776770536-2-2-database-2,1776768855-1-1-schema-2,1776768855-1-2-schema-2,1776768855-2-1-schema-2,1776768855-2-2-schema-2
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,16.00,13.54,24.51,17.07,21.31,26.09,38.79,37.38,12.61,7.42,30.47,6.13
Active Backends Waiting on I/O,0.00,0.00,6.27,0.00,0.00,0.00,5.59,0.00,0.00,0.00,7.84,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Average WAL Segment Size [MiB],32.00,32.00,32.00,32.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Buffer Cache Hit Count,10477165.00,11845163.00,17804872.00,26002894.00,26903773.00,27045341.00,14268105.00,18118575.00,24831964.00,27077595.00,24964455.00,27077595.00
Buffer Cache Hit Ratio,0.93,0.98,0.98,0.98,0.94,0.98,0.98,0.98,0.92,0.98,0.60,0.97
CPU System Time [s],10.21,11.12,92.95,17.55,0.83,21.25,155.24,0.00,28.65,4.49,152.09,8.19
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU User Time [s],56.48,64.05,380.76,113.82,5.47,116.26,640.68,0.00,149.49,42.23,639.54,57.98
CPU Utilization,0.47,0.61,1.27,0.55,0.47,0.94,0.65,0.02,1.10,0.90,1.03,1.27
CPU Utilization Time [s],66.69,75.17,473.72,131.38,6.30,137.51,795.93,0.00,178.14,46.72,791.63,66.18
Core Utilization Variance [%],0.02,0.03,0.05,0.12,0.02,0.03,0.04,0.13,0.02,0.02,0.06,0.13
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN
Disk Blocks Read Count,70669.00,0.00,1092912.00,0.00,141562.00,0.00,1058662.00,0.00,141480.00,0.00,1126841.00,0.00
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.00,0.00,0.03,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.04,0.00
I/O Wait [%],18.55,3.60,32.83,46.37,14.38,6.28,30.19,46.30,15.16,5.46,35.95,51.22
Index Cache Hit Ratio,0.68,0.99,0.99,0.99,0.79,0.99,0.99,0.99,0.56,0.99,0.55,0.99
Index Scan Count,1720033.00,1881536.00,2776794.00,3748178.00,878346.00,3776174.00,2157177.00,2249923.00,3736462.00,3773734.00,3755098.00,3773734.00
Index Tuple Fetch Count,7631973.00,8173972.00,12697816.00,16760062.00,3993638.00,17416366.00,9808542.00,9965419.00,16267390.00,17416794.00,16842092.00,17416794.00
Longest Active Transaction,0.27,0.14,9.40,0.80,0.37,1.35,6.19,0.48,0.10,0.33,15.49,0.44
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Core Utilization [%],0.80,1.13,1.24,4.31,1.17,1.65,1.33,4.77,0.68,1.16,1.67,3.64
Max Transaction Duration (I/O Wait),0.00,0.00,9.33,0.00,0.00,0.00,5.75,0.00,0.00,0.00,13.72,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Memory Usage Cached [MiB],30188.03,30865.82,24155.04,29622.99,25466.86,25151.62,20142.09,23713.12,25317.07,24723.73,20327.87,23842.79
Memory Usage [MiB],19947.25,21018.52,17791.72,20647.30,13825.50,15339.01,12776.27,14741.79,14294.75,14915.17,12942.05,14883.51
Network Rx Total [MiB],0.14,26.44,3298.26,0.23,0.11,0.06,6599.80,1.78,0.19,0.20,6591.16,1.74
Network Tx Total [MiB],1.97,6046.50,17.64,0.06,3.31,3.28,39.36,0.11,3.26,0.19,31.84,0.11
Number of Active Application Sessions,7.00,11.00,14.00,10.00,14.00,11.00,17.00,9.00,10.00,10.00,14.00,10.00
Number of Active Sessions,7.00,13.00,13.00,9.00,15.00,11.00,16.00,8.00,11.00,10.00,14.00,10.00
Number of Idle Sessions,1.00,0.98,0.62,0.42,1.34,0.00,0.31,1.84,0.71,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of WAL Segments,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00
Power@Size [~Q/h],15070.02,14502.61,8316.42,14699.13,14246.21,14091.68,8059.06,14734.99,14481.47,14360.52,7768.27,14368.52
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SF,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Table Blocks Read Count,0.00,0.00,984814.00,0.00,0.00,0.00,984776.00,0.00,0.00,0.00,984840.00,0.00
Table Buffer Hit Count,5418802.00,6225638.00,9624483.00,14804456.00,3094024.00,15753870.00,5881945.00,7012236.00,13814380.00,15800584.00,13875674.00,15800584.00
Table Cache Hit Ratio,0.92,0.97,0.98,0.97,0.91,0.97,0.97,0.98,0.92,0.97,0.36,0.96
Throughput@Size,16386.21,15329.03,5221.98,14850.00,15840.00,15329.03,5002.11,15329.03,15840.00,14850.00,4320.00,15840.00
Total Cache Hit Ratio,0.93,0.98,0.98,0.98,0.92,0.98,0.98,0.98,0.92,0.98,0.38,0.97
Total I/O Wait Time [s],0.39,1.11,679.24,0.60,0.46,0.34,653.65,0.65,3.14,0.57,800.81,0.40
Total Locks Current,16.00,13.54,24.51,17.07,21.31,26.09,38.79,37.38,12.61,7.42,30.47,6.13
Total WAL Size [GiB],6.40,6.40,6.40,6.40,6.41,6.41,6.41,6.41,6.41,6.41,6.41,6.41
WAL Growth Rate [MiB/s],13.42,0.94,0.00,0.00,8.53,3.41,0.00,0.00,9.53,2.64,0.00,0.00
WAL Segments Growth Rate [segments/s],0.84,0.06,0.00,0.00,0.53,0.21,0.00,0.00,0.60,0.17,0.00,0.00
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
benchmarking_parameters_BEXHOMA_TENANT_BY,container,container,container,container,database,database,database,database,schema,schema,schema,schema
benchmarking_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3
benchmarking_parameters_TENANT_BY,container,container,container,container,database,database,database,database,schema,schema,schema,schema
benchmarking_parameters_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2
code,1776772217,1776772217,1776772217,1776772217,1776770536,1776770536,1776770536,1776770536,1776768855,1776768855,1776768855,1776768855
configuration,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2
datadisk,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128
host_GPU,,,,,,,,,,,,
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_cuda,,,,,,,,,,,,
host_datadisk,8188,8188,8188,8188,16368,16368,16368,16368,16353,16353,16353,16353
host_disk,247634,247634,247634,247635,247631,247631,247632,247632,247629,247629,247630,247630
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_volume_size,15G,15G,15G,15G,30G,30G,30G,30G,30G,30G,30G,30G
host_volume_used,8.0G,8.0G,8.0G,8.0G,16G,16G,16G,16G,16G,16G,16G,16G
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_TENANT_BY,container,container,container,container,database,database,database,database,schema,schema,schema,schema
loading_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_PODS_PARALLEL,1,1,1,1,2,2,2,2,2,2,2,2
loading_parameters_PODS_TOTAL,1,1,1,1,2,2,2,2,2,2,2,2
loading_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_TPCH_TABLE,,,,,,,,,,,,
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
num_of_queries,44,44,44,44,44,44,44,44,44,44,44,44
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
phase,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2
pod_count,2,2,2,2,2,2,2,2,2,2,2,2
pods,1,1,1,1,2,2,2,2,2,2,2,2
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3
tenant,0,0,0,0,,,,,,,,
terminals,0,0,0,0,0,0,0,0,0,0,0,0
time [s],29,31,91,32,30,31,95,31,30,32,110,30
time_check,379.00,379.00,379.00,379.00,533.00,533.00,533.00,533.00,535.00,535.00,535.00,535.00
time_ingest,302.00,302.00,302.00,302.00,439.00,439.00,439.00,439.00,440.00,440.00,440.00,440.00
time_load,685.00,685.00,685.00,685.00,977.00,977.00,977.00,977.00,979.00,979.00,979.00,979.00
total_timer_execution,0.72,0.74,1.30,0.73,0.76,0.77,1.34,0.73,0.75,0.75,1.39,0.75
type_tenants,container,container,container,container,database,database,database,database,schema,schema,schema,schema
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
RAM/Throughput,1.84,2.01,4.63,1.99,1.61,1.64,4.03,1.55,1.60,1.66,4.71,1.51
CPUs/Throughput,0.10,0.14,0.88,0.13,0.11,0.22,0.47,0.00,0.25,0.22,0.86,0.29
E_CPU,5617.02,4327.87,2078.74,4800.00,5617.02,2808.51,4061.54,132000.00,2400.00,2933.33,2563.11,2078.74
E_RAM,0.09,0.09,0.11,0.09,0.10,0.10,0.13,0.11,0.10,0.11,0.13,0.11

## With Metadata

Connection infos are added.

In [40]:
df = collect.add_metadata(merged_df)
df.T

combine on columns phase

,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
AccessShareLocks Current,12.61,7.42,30.47,6.13,21.31,26.09,38.79,37.38,16.00,13.54,24.51,17.07,NaN,NaN,NaN,NaN
Active Backends Waiting on I/O,0.00,0.00,7.84,0.00,0.00,0.00,5.59,0.00,0.00,0.00,6.27,0.00,NaN,NaN,NaN,NaN
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,32.00,32.00,32.00,32.00,NaN,NaN,NaN,NaN
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Buffer Cache Hit Count,24831964.00,27077595.00,24964455.00,27077595.00,26903773.00,27045341.00,14268105.00,18118575.00,10477165.00,11845163.00,17804872.00,26002894.00,NaN,NaN,NaN,NaN
Buffer Cache Hit Ratio,0.92,0.98,0.60,0.97,0.94,0.98,0.98,0.98,0.93,0.98,0.98,0.98,NaN,NaN,NaN,NaN
CPU System Time [s],28.65,4.49,152.09,8.19,0.83,21.25,155.24,0.00,10.21,11.12,92.95,17.55,NaN,NaN,NaN,NaN
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
CPU User Time [s],149.49,42.23,639.54,57.98,5.47,116.26,640.68,0.00,56.48,64.05,380.76,113.82,NaN,NaN,NaN,NaN
CPU Utilization,1.10,0.90,1.03,1.27,0.47,0.94,0.65,0.02,0.47,0.61,1.27,0.55,NaN,NaN,NaN,NaN
CPU Utilization Time [s],178.14,46.72,791.63,66.18,6.30,137.51,795.93,0.00,66.69,75.17,473.72,131.38,NaN,NaN,NaN,NaN
CPUs/Throughput,0.25,0.22,0.86,0.29,0.11,0.22,0.47,0.00,0.10,0.14,0.88,0.13,NaN,NaN,NaN,NaN
Core Utilization Variance [%],0.02,0.02,0.06,0.13,0.02,0.03,0.04,0.13,0.02,0.03,0.05,0.12,NaN,NaN,NaN,NaN
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN
Disk Blocks Read Count,141480.00,0.00,1126841.00,0.00,141562.00,0.00,1058662.00,0.00,70669.00,0.00,1092912.00,0.00,NaN,NaN,NaN,NaN
E_CPU,2400.00,2933.33,2563.11,2078.74,5617.02,2808.51,4061.54,132000.00,5617.02,4327.87,2078.74,4800.00,NaN,NaN,NaN,NaN
E_RAM,0.10,0.11,0.13,0.11,0.10,0.10,0.13,0.11,0.09,0.09,0.11,0.09,NaN,NaN,NaN,NaN
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Filesystem Read Total [MiB],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Filesystem Write Total [MiB],0.00,0.00,0.04,0.00,0.00,0.00,0.04,0.00,0.00,0.00,0.03,0.00,NaN,NaN,NaN,NaN
I/O Wait [%],15.16,5.46,35.95,51.22,14.38,6.28,30.19,46.30,18.55,3.60,32.83,46.37,NaN,NaN,NaN,NaN
Index Cache Hit Ratio,0.56,0.99,0.55,0.99,0.79,0.99,0.99,0.99,0.68,0.99,0.99,0.99,NaN,NaN,NaN,NaN
Index Scan Count,3736462.00,3773734.00,3755098.00,3773734.00,878346.00,3776174.00,2157177.00,2249923.00,1720033.00,1881536.00,2776794.00,3748178.00,NaN,NaN,NaN,NaN
Index Tuple Fetch Count,16267390.00,17416794.00,16842092.00,17416794.00,3993638.00,17416366.00,9808542.00,9965419.00,7631973.00,8173972.00,12697816.00,16760062.00,NaN,NaN,NaN,NaN
Longest Active Transaction,0.10,0.33,15.49,0.44,0.37,1.35,6.19,0.48,0.27,0.14,9.40,0.80,NaN,NaN,NaN,NaN
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Max Core Utilization [%],0.68,1.16,1.67,3.64,1.17,1.65,1.33,4.77,0.80,1.13,1.24,4.31,NaN,NaN,NaN,NaN
Max Transaction Duration (I/O Wait),0.00,0.00,13.72,0.00,0.00,0.00,5.75,0.00,0.00,0.00,9.33,0.00,NaN,NaN,NaN,NaN
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Memory Usage Cached [MiB],25317.07,24723.73,20327.87,23842.79,25466.86,25151.62,20142.09,23713.12,30188.03,30865.82,24155.04,29622.99,NaN,NaN,NaN,NaN
Memory Usage [MiB],14294.75,14915.17,12942.05,14883.51,13825.50,15339.01,12776.27,14741.79,19947.25,21018.52,17791.72,20647.30,NaN,NaN,NaN,NaN
Network Rx Total [MiB],0.19,0.20,6591.16,1.74,0.11,0.06,6599.80,1.78,0.14,26.44,3298.26,0.23,NaN,NaN,NaN,NaN
Network Tx Total [MiB],3.26,0.19,31.84,0.11,3.31,3.28,39.36,0.11,1.97,6046.50,17.64,0.06,NaN,NaN,NaN,NaN
Number of Active Application Sessions,10.00,10.00,14.00,10.00,14.00,11.00,17.00,9.00,7.00,11.00,14.00,10.00,NaN,NaN,NaN,NaN
Number of Active Sessions,11.00,10.00,14.00,10.00,15.00,11.00,16.00,8.00,7.00,13.00,13.00,9.00,NaN,NaN,NaN,NaN
Number of Idle Sessions,0.71,0.00,0.00,0.00,1.34,0.00,0.31,1.84,1.00,0.98,0.62,0.42,NaN,NaN,NaN,NaN
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Number of WAL Segments,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,NaN,NaN,NaN,NaN
Power@Size [~Q/h],14481.47,14360.52,7768.27,14368.52,14246.21,14091.68,8059.06,14734.99,15070.02,14502.61,8316.42,14699.13,NaN,NaN,NaN,NaN
RAM/Throughput,1.60,1.66,4.71,1.51,1.61,1.64,4.03,1.55,1.84,2.01,4.63,1.99,NaN,NaN,NaN,NaN
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
SF,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,3.00,NaN,NaN,NaN,NaN
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
Table Blocks Read Count,0.00,0.00,984840.00,0.00,0.00,0.00,984776.00,0.00,0.00,0.00,984814.00,0.00,NaN,NaN,NaN,NaN
Table Buffer Hit Count,13814380.00,15800584.00,13875674.00,15800584.00,3094024.00,15753870.00,5881945.00,7012236.00,5418802.00,6225638.00,9624483.00,14804456.00,NaN,NaN,NaN,NaN
Table Cache Hit Ratio,0.92,0.97,0.36,0.96,0.91,0.97,0.97,0.98,0.92,0.97,0.98,0.97,NaN,NaN,NaN,NaN
Throughput@Size,15840.00,14850.00,4320.00,15840.00,15840.00,15329.03,5002.11,15329.03,16386.21,15329.03,5221.98,14850.00,NaN,NaN,NaN,NaN
Total Cache Hit Ratio,0.92,0.98,0.38,0.97,0.92,0.98,0.98,0.98,0.93,0.98,0.98,0.98,NaN,NaN,NaN,NaN
Total I/O Wait Time [s],3.14,0.57,800.81,0.40,0.46,0.34,653.65,0.65,0.39,1.11,679.24,0.60,NaN,NaN,NaN,NaN
Total Locks Current,12.61,7.42,30.47,6.13,21.31,26.09,38.79,37.38,16.00,13.54,24.51,17.07,NaN,NaN,NaN,NaN
Total WAL Size [GiB],6.41,6.41,6.41,6.41,6.41,6.41,6.41,6.41,6.40,6.40,6.40,6.40,NaN,NaN,NaN,NaN
WAL Growth Rate [MiB/s],9.53,2.64,0.00,0.00,8.53,3.41,0.00,0.00,13.42,0.94,0.00,0.00,NaN,NaN,NaN,NaN
WAL Segments Growth Rate [segments/s],0.60,0.17,0.00,0.00,0.53,0.21,0.00,0.00,0.84,0.06,0.00,0.00,NaN,NaN,NaN,NaN
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
arg_checkpoint_timeout,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h,12h
arg_effective_cache_size,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_effective_io_concurrency,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_fsync,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_io_method,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker,worker
arg_maintenance_work_mem,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_max_connections,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000,3000
arg_max_parallel_maintenance_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_parallel_workers_per_gather,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_max_worker_processes,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
arg_min_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_shared_buffers,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB,256GB
arg_synchronous_commit,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_temp_buffers,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB,4GB
arg_wal_buffers,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB,1GB
arg_wal_compression,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on,on
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_work_mem,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
benchmarking_parameters_BEXHOMA_TENANT_BY,schema,schema,schema,schema,database,database,database,database,container,container,container,container,container,container,container,container
benchmarking_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
benchmarking_parameters_TENANT_BY,schema,schema,schema,schema,database,database,database,database,container,container,container,container,container,container,container,container
benchmarking_parameters_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2
code,1776768855,1776768855,1776768855,1776768855,1776770536,1776770536,1776770536,1776770536,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217
configuration,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1
datadisk,16353,16353,16353,16353,16368,16368,16368,16368,8188,8188,8188,8188,8188,8188,8188,8188
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
host_CPU,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430,Intel(R) Xeon(R) Gold 6430
host_Cores,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128,128
host_GPU,,,,,,,,,,,,,,,,
host_RAM,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016,540493398016
host_cpu_list,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127,0-127
host_cuda,,,,,,,,,,,,,,,,
host_datadisk,16353,16353,16353,16353,16368,16368,16368,16368,8188,8188,8188,8188,8188,8188,8188,8188
host_disk,247629,247629,247630,247630,247631,247631,247632,247632,247634,247634,247634,247635,247634,247634,247635,247635
host_host,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic,6.8.0-106-generic
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_node,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38,cl-worker38
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_volume_size,30G,30G,30G,30G,30G,30G,30G,30G,15G,15G,15G,15G,15G,15G,15G,15G
host_volume_used,16G,16G,16G,16G,16G,16G,16G,16G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G,8.0G
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_TENANT_BY,schema,schema,schema,schema,database,database,database,database,container,container,container,container,container,container,container,container
loading_parameters_BEXHOMA_TENANT_NUM,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
loading_parameters_PODS_PARALLEL,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1
loading_parameters_PODS_TOTAL,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1
loading_parameters_SF,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_TPCH_TABLE,,,,,,,,,,,,,,,,
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
num_of_queries,44.00,44.00,44.00,44.00,44.00,44.00,44.00,44.00,44.00,44.00,44.00,44.00,NaN,NaN,NaN,NaN
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
phase,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2
pod_count,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,2.00,NaN,NaN,NaN,NaN
pods,2,2,2,2,2,2,2,2,1,1,1,1,1,1,1,1
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776768855,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-2-1776770536,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-0-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217,bexhoma-sut-postgresql-bht-1-1-1776772217
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-schema-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-database-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-0-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3,bexhoma-worker-postgresql-1-2-tpch-3
tenant,,,,,,,,,0,0,0,0,1,1,1,1
terminals,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
time [s],30.00,32.00,110.00,30.00,30.00,31.00,95.00,31.00,29.00,31.00,91.00,32.00,NaN,NaN,NaN,NaN
time_check,535.00,535.00,535.00,535.00,533.00,533.00,533.00,533.00,379.00,379.00,379.00,379.00,378.00,378.00,378.00,378.00
time_ingest,440.00,440.00,440.00,440.00,439.00,439.00,439.00,439.00,302.00,302.00,302.00,302.00,300.00,300.00,300.00,300.00
time_load,979.00,979.00,979.00,979.00,977.00,977.00,977.00,977.00,685.00,685.00,685.00,685.00,683.00,683.00,683.00,683.00
total_timer_execution,0.75,0.75,1.39,0.75,0.76,0.77,1.34,0.73,0.72,0.74,1.30,0.73,NaN,NaN,NaN,NaN
type_tenants,schema,schema,schema,schema,database,database,database,database,container,container,container,container,container,container,container,container
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [41]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2
phase,1776768855-PostgreSQL-BHT-2-1-1,1776768855-PostgreSQL-BHT-2-1-2,1776768855-PostgreSQL-BHT-2-2-1,1776768855-PostgreSQL-BHT-2-2-2,1776770536-PostgreSQL-BHT-2-1-1,1776770536-PostgreSQL-BHT-2-1-2,1776770536-PostgreSQL-BHT-2-2-1,1776770536-PostgreSQL-BHT-2-2-2,1776772217-PostgreSQL-BHT-1-0-1-1,1776772217-PostgreSQL-BHT-1-0-1-2,1776772217-PostgreSQL-BHT-1-0-2-1,1776772217-PostgreSQL-BHT-1-0-2-2,1776772217-PostgreSQL-BHT-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2,1776772217-PostgreSQL-BHT-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-2
code,1776768855,1776768855,1776768855,1776768855,1776770536,1776770536,1776770536,1776770536,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217,1776772217
configuration,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776768855-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776770536-PostgreSQL-BHT-2,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,1776772217-PostgreSQL-BHT-1-0,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1,PostgreSQL-BHT-1-1
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2
type_tenants,schema,schema,schema,schema,database,database,database,database,container,container,container,container,container,container,container,container
num_tenants,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

# Show Warnings per Connection

In [42]:
df = collect.get_total_warnings(query_titles=False)
df.T

,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-2-2-2
Q1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Show Only Existing Warnings

For demonstration we insert a warning.

In [43]:
df.loc['1776772217-PostgreSQL-BHT-1-0-1-1-1','Q1'] = True
df.T

,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-2-2-2
Q1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [44]:
num_warnings = df.sum().sum()
if num_warnings > 0:
    # remove only False rows
    df = df[~(df == False).all(axis=1)]
    print(df.T)
else:
    print("No warnings")

     1776772217-PostgreSQL-BHT-1-0-1-1-1
Q1                                  True
Q2                                 False
Q3                                 False
Q4                                 False
Q5                                 False
Q6                                 False
Q7                                 False
Q8                                 False
Q9                                 False
Q10                                False
Q11                                False
Q12                                False
Q13                                False
Q14                                False
Q15                                False
Q16                                False
Q17                                False
Q18                                False
Q19                                False
Q20                                False
Q21                                False
Q22                                False

In [45]:
df = collect.get_total_warnings(query_titles=True)
df.T

,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-2-2-2
Pricing Summary Report (TPC-H Q1),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Minimum Cost Supplier Query (TPC-H Q2),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Shipping Priority (TPC-H Q3),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Order Priority Checking Query (TPC-H Q4),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Local Supplier Volume (TPC-H Q5),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q6),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q7),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
National Market Share (TPC-H Q8),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Product Type Profit Measure (TPC-H Q9),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q10),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Important Stock Identification (TPC-H Q11),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Shipping Modes and Order Priority (TPC-H Q12),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Customer Distribution (TPC-H Q13),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q14),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Top Supplier Query (TPC-H Q15),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Parts/Supplier Relationship (TPC-H Q16),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Small-Quantity-Order Revenue (TPC-H Q17),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Large Volume Customer (TPC-H Q18),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Discounted Revenue (TPC-H Q19),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Potential Part Promotion (TPC-H Q20),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Suppliers Who Kept Orders Waiting Query (TPC-H Q21),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Global Sales Opportunity Query (TPC-H Q22),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [46]:
num_warnings = df.sum().sum()
if num_warnings > 0:
    # remove only False rows
    df = df[~(df == False).all(axis=1)]
    print(df.T)
else:
    print("No warnings")

No warnings

# Show Errors per Connection with Query Titles

In [47]:
df = collect.get_total_errors(query_titles=True)
df.T

,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-2-2-2
Pricing Summary Report (TPC-H Q1),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Minimum Cost Supplier Query (TPC-H Q2),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Shipping Priority (TPC-H Q3),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Order Priority Checking Query (TPC-H Q4),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Local Supplier Volume (TPC-H Q5),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q6),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q7),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
National Market Share (TPC-H Q8),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Product Type Profit Measure (TPC-H Q9),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q10),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Important Stock Identification (TPC-H Q11),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Shipping Modes and Order Priority (TPC-H Q12),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Customer Distribution (TPC-H Q13),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q14),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Top Supplier Query (TPC-H Q15),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Parts/Supplier Relationship (TPC-H Q16),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Small-Quantity-Order Revenue (TPC-H Q17),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Large Volume Customer (TPC-H Q18),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Discounted Revenue (TPC-H Q19),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Potential Part Promotion (TPC-H Q20),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Suppliers Who Kept Orders Waiting Query (TPC-H Q21),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Global Sales Opportunity Query (TPC-H Q22),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Show Only Existing Errors

In [48]:
num_errors = df.sum().sum()
if num_errors > 0:
    # remove only False rows
    df = df[~(df == False).all(axis=1)]
    print(df.T)
else:
    print("No errors")

No errors

# Show Latencies per Query and Connection with Query Titles

In [49]:
df = collect.get_query_latencies(query_titles=True)
df.T

DBMS,1776772217-PostgreSQL-BHT-1-0-2-2-1,1776772217-PostgreSQL-BHT-1-1-2-2-1,1776772217-PostgreSQL-BHT-1-0-1-1-1,1776772217-PostgreSQL-BHT-1-0-1-2-1,1776772217-PostgreSQL-BHT-1-1-1-2-1,1776772217-PostgreSQL-BHT-1-1-1-1-1,1776772217-PostgreSQL-BHT-1-1-2-1-1,1776772217-PostgreSQL-BHT-1-0-2-1-1,1776770536-PostgreSQL-BHT-2-2-2-2,1776770536-PostgreSQL-BHT-2-2-2-1,1776770536-PostgreSQL-BHT-2-1-1-2,1776770536-PostgreSQL-BHT-2-1-1-1,1776770536-PostgreSQL-BHT-2-1-2-2,1776770536-PostgreSQL-BHT-2-1-2-1,1776770536-PostgreSQL-BHT-2-2-1-1,1776770536-PostgreSQL-BHT-2-2-1-2,1776768855-PostgreSQL-BHT-2-2-2-1,1776768855-PostgreSQL-BHT-2-1-2-2,1776768855-PostgreSQL-BHT-2-1-2-1,1776768855-PostgreSQL-BHT-2-1-1-1,1776768855-PostgreSQL-BHT-2-1-1-2,1776768855-PostgreSQL-BHT-2-2-2-2,1776768855-PostgreSQL-BHT-2-2-1-1,1776768855-PostgreSQL-BHT-2-2-1-2
Pricing Summary Report (TPC-H Q1),2476.80,2530.29,2615.95,2661.80,2708.28,2768.79,28363.40,30407.60,2535.28,2609.41,2620.34,2636.12,2638.93,2651.48,29210.01,30645.89,2496.66,2513.28,2521.04,2522.74,2654.45,2716.35,33067.65,38167.95
Minimum Cost Supplier Query (TPC-H Q2),570.94,614.43,664.59,775.55,760.63,672.90,14599.06,16971.50,600.62,823.73,653.60,636.39,664.07,661.30,17255.55,17742.65,650.41,615.24,602.29,653.89,628.14,651.06,16534.87,17004.12
Shipping Priority (TPC-H Q3),988.72,692.16,1090.42,1231.20,779.10,809.83,12567.72,10798.98,661.84,684.59,769.96,808.26,781.91,788.08,16775.57,15738.77,702.79,1135.34,727.88,778.27,1211.69,1098.52,16205.48,20114.29
Order Priority Checking Query (TPC-H Q4),377.14,316.82,322.01,372.92,380.65,349.02,383.53,393.02,325.83,314.02,400.99,366.16,374.72,386.38,433.23,404.39,344.04,382.81,395.66,339.60,370.67,356.42,443.62,405.52
Local Supplier Volume (TPC-H Q5),730.43,766.59,680.50,843.25,754.36,758.14,1127.38,1312.73,747.08,742.68,819.09,800.97,794.86,846.34,1000.64,1127.90,771.50,807.88,808.18,767.35,814.65,792.51,1696.87,1132.73
Forecasting Revenue Change (TPC-H Q6),446.90,428.33,439.26,482.54,427.99,430.29,468.62,509.44,450.66,428.46,434.88,468.86,480.26,440.08,492.03,484.23,447.91,485.67,513.55,445.32,434.47,415.93,494.22,493.71
Forecasting Revenue Change (TPC-H Q7),929.53,900.36,813.32,866.45,979.30,865.47,1022.08,1137.22,975.30,1003.75,1012.00,972.48,982.16,991.70,1085.68,1080.72,989.33,1027.53,1019.62,849.68,963.30,940.18,1102.35,1082.48
National Market Share (TPC-H Q8),500.93,454.83,426.56,488.05,422.15,467.80,6029.45,5849.91,466.41,500.36,541.33,500.17,435.46,453.17,6168.07,5784.37,464.81,455.70,430.64,464.36,509.89,448.22,9307.12,6650.06
Product Type Profit Measure (TPC-H Q9),1386.56,1366.25,1085.26,1373.76,1241.79,1222.72,1516.96,1448.94,1218.38,1283.84,1281.05,1335.07,1272.71,1259.45,1475.89,1338.12,1330.33,1202.95,1243.44,1183.16,1419.73,1409.97,1490.78,1451.05
Forecasting Revenue Change (TPC-H Q10),695.55,705.37,652.58,737.34,686.76,665.01,851.03,874.62,670.81,691.74,626.95,643.07,786.35,689.56,781.99,805.68,582.01,591.87,603.25,598.35,607.82,617.28,708.42,707.05
Important Stock Identification (TPC-H Q11),226.67,231.55,230.79,255.42,263.77,226.28,381.68,304.49,259.94,256.60,249.76,259.93,367.87,303.50,331.76,312.84,262.13,260.33,252.77,246.58,263.74,267.99,342.46,330.29
Shipping Modes and Order Priority (TPC-H Q12),684.88,612.13,687.49,721.15,686.48,641.29,727.07,720.95,676.73,684.11,680.68,677.65,659.92,696.91,754.32,752.68,684.94,726.13,727.97,694.50,727.50,654.91,753.23,758.15
Customer Distribution (TPC-H Q13),2614.63,2610.85,2652.20,2552.38,2650.22,2664.11,3274.26,2949.64,2792.17,2899.69,3189.57,3177.56,3408.27,3106.81,3155.55,3525.59,2961.42,2907.05,2949.80,2922.01,2947.83,3118.53,2722.52,2841.63
Forecasting Revenue Change (TPC-H Q14),704.62,689.75,756.91,728.97,746.27,690.33,717.40,757.14,693.34,758.64,823.23,784.77,712.36,677.61,769.13,754.38,709.67,754.61,764.80,730.99,767.57,827.47,751.87,737.21
Top Supplier Query (TPC-H Q15),592.31,574.24,596.13,597.41,578.72,596.65,583.97,585.48,550.67,605.80,640.43,609.56,624.49,576.07,603.23,589.76,580.87,591.71,611.42,575.00,594.84,652.56,608.69,595.67
Parts/Supplier Relationship (TPC-H Q16),611.36,610.29,552.99,580.60,571.36,600.37,618.38,621.33,589.18,611.31,696.88,604.40,694.06,567.05,637.75,599.53,580.08,588.06,588.23,606.98,602.61,730.56,588.84,600.04
Small-Quantity-Order Revenue (TPC-H Q17),1911.96,2060.81,1898.33,1849.96,1930.16,2016.58,2036.66,2100.80,1951.62,2300.19,2023.72,2004.82,2321.61,2023.74,2065.39,1928.66,2089.05,2006.62,2030.55,1984.47,2406.68,2219.35,2207.01,2175.57
Large Volume Customer (TPC-H Q18),9933.50,8366.63,8641.77,9241.55,8391.47,9212.74,8463.62,9141.97,8535.41,9230.37,8491.50,9670.73,8919.23,8408.32,8536.17,8599.45,8707.43,8586.40,9484.94,8513.01,8773.67,8394.90,8479.83,9071.95
Discounted Revenue (TPC-H Q19),123.67,134.07,131.81,118.70,117.91,128.31,124.29,131.80,112.48,115.35,117.95,119.30,119.73,127.19,124.28,135.38,122.38,116.45,126.15,115.77,129.87,122.00,125.06,144.84
Potential Part Promotion (TPC-H Q20),525.13,424.17,353.56,367.48,373.78,396.10,409.16,408.09,518.08,432.91,512.95,397.06,542.29,420.99,445.81,710.50,408.08,496.01,467.19,380.89,611.85,564.50,458.11,715.74
Suppliers Who Kept Orders Waiting Query (TPC-H Q21),840.62,742.78,742.07,743.50,773.49,749.17,732.91,726.21,746.95,716.10,783.08,798.28,770.74,777.57,740.39,781.54,762.61,737.72,798.45,686.00,732.79,799.67,808.67,795.24
Global Sales Opportunity Query (TPC-H Q22),244.84,220.14,203.97,218.92,214.82,206.49,224.64,209.19,227.73,216.64,204.91,200.57,217.86,213.09,215.89,219.62,221.76,214.59,222.12,209.28,203.24,200.20,216.45,233.80

In [50]:
zip_all_results(path, codes)

Zipping D:\data\benchmarks\1776772217 to D:\data\benchmarks\1776772217.zip...
Zipping D:\data\benchmarks\1776770536 to D:\data\benchmarks\1776770536.zip...
Zipping D:\data\benchmarks\1776768855 to D:\data\benchmarks\1776768855.zip...
✅ Done zipping all folders.