# TPC-H Collector Demo

In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option('display.max_colwidth', None)
pd.options.display.max_columns = None
pd.options.display.max_rows = None
pd.options.display.float_format = '{:.2f}'.format

from bexhoma import collectors

%matplotlib inline

## Functions for Nice Plots

In [2]:
from notebookutils import *

# Collect Results

In [3]:
#path = r"D:\data\benchmarks"
path = r"/data/benchmarks"
filename_prefix = "demo_"
b_plot_save = False
b_skip_plots = True

In [4]:
codes = [
    "1781936763",
    "1781938146",
    "1781939856",
]

codes

['1781936763', '1781938146', '1781939856']

In [5]:
collect = collectors.dbmsbenchmarker(path, codes)

# Get all Metrics Metadata

## Metrics Names and Types

Metrics that are derived from monitoring

In [6]:
collect.get_metrics_metadata()

,title,active,type,metric
total_cpu_memory,Memory Usage [MiB],True,cluster,gauge
total_cpu_memory_cached,Memory Usage Cached [MiB],True,cluster,gauge
total_cpu_util,CPU Utilization,True,cluster,gauge
total_cpu_throttled,CPU Throttle,True,cluster,gauge
total_cpu_throttled_s,CPU Throttled Time [s],True,cluster,counter
total_cpu_util_others,CPU Utilization Others,False,cluster,gauge
total_cpu_util_s,CPU Utilization Time [s],True,cluster,counter
total_cpu_util_user_s,CPU User Time [s],True,cluster,counter
total_cpu_util_sys_s,CPU System Time [s],True,cluster,counter
total_cpu_util_others_s,CPU Utilization Time Others [s],False,cluster,counter
total_network_rx,Network Rx Total [MiB],True,cluster,counter
total_network_tx,Network Tx Total [MiB],True,cluster,counter
total_fs_read,Filesystem Read Total [MiB],True,cluster,counter
total_fs_write,Filesystem Write Total [MiB],True,cluster,counter
total_gpu_util,GPU Utilization [%],False,cluster,gauge
total_gpu_power,GPU Power Usage [W],False,cluster,gauge
total_gpu_memory,GPU Memory Usage [MiB],False,cluster,gauge
core_variance,Core Utilization Variance [%],True,cluster,ratio
max_core_util,Max Core Utilization [%],True,cluster,ratio
io_wait_pct,I/O Wait [%],True,cluster,ratio
io_wait_total,Total I/O Wait Time [s],True,cluster,counter
pg_stat_activity_count_idle,Number of Idle Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction,Number of Idle-in-transaction Sessions,True,application,gauge
pg_stat_activity_count_idle_transaction_aborted,Number of Idle-in-transaction Aborted Sessions,True,application,gauge
pg_stat_activity_count_active,Number of Active Sessions,True,application,counter
pg_stat_activity_count_active_app,Number of Active Application Sessions,True,application,counter
pg_stat_activity_max_tx_duration_active,Longest Active Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle,Longest Idle Session (no transaction),True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx,Longest Idle-in-Transaction,True,application,ratio
pg_stat_activity_max_tx_duration_idle_in_tx_aborted,Longest Idle-in-Transaction (Aborted),True,application,ratio
pg_stat_activity_count_io,Active Backends Waiting on I/O,True,application,gauge
pg_stat_activity_count_wal,Active Backends Waiting on WAL,True,application,gauge
pg_stat_activity_count_lock,Active Backends Waiting on Locks,True,application,gauge
pg_stat_activity_max_tx_duration_io,Max Transaction Duration (I/O Wait),True,application,ratio
pg_stat_activity_max_tx_duration_wal,Max Transaction Duration (WAL Wait),True,application,ratio
pg_stat_activity_max_tx_duration_lock,Max Transaction Duration (Lock Wait),True,application,ratio
pg_stat_database_blks_read,Disk Blocks Read Count,True,application,counter
pg_stat_database_blks_hit,Buffer Cache Hit Count,True,application,counter
cache_hit_ratio,Buffer Cache Hit Ratio,True,application,ratio
pg_stat_user_tables_idx_scan,Index Scan Count,True,application,counter
pg_stat_user_tables_idx_tup_fetch,Index Tuple Fetch Count,True,application,counter
pg_statio_user_tables_idx_cache_hit_ratio,Index Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_heap_blocks_hit,Table Buffer Hit Count,True,application,counter
pg_statio_user_tables_heap_blocks_read,Table Blocks Read Count,True,application,counter
pg_statio_user_tables_heap_cache_hit_ratio,Table Cache Hit Ratio,True,application,ratio
pg_statio_user_tables_total_cache_hit_ratio,Total Cache Hit Ratio,True,application,ratio
pg_stat_bgwriter_efficiency_ratio,BGWriter Efficiency Ratio (Cleaned / Allocated),True,application,ratio
pg_stat_bgwriter_maxwritten_clean_total,BGWriter Stopped Due to Max Pages,True,application,counter
pg_stat_bgwriter_checkpoint_sync_time_total,Checkpoint Sync Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_total,Checkpoint Write Time [ms],False,application,counter
pg_stat_bgwriter_checkpoint_write_time_per_sync_time,Time spent writing vs syncing during checkpoints [ratio],False,application,ratio
pg_locks_count,Total Locks Current,True,application,gauge
pg_locks_count_accessexclusivelock,AccessExclusiveLocks Current,True,application,gauge
pg_locks_count_accesssharelock,AccessShareLocks Current,True,application,gauge
pg_locks_count_exclusivelock,ExclusiveLocks Current,True,application,gauge
pg_locks_count_rowexclusivelock,RowExclusiveLocks Current,True,application,gauge
pg_locks_count_rowsharelock,RowShareLocks Current,True,application,gauge
pg_locks_count_sharelock,ShareLocks Current,True,application,gauge
pg_locks_count_sharerowexclusivelock,ShareRowExclusiveLocks Current,True,application,gauge
pg_locks_count_shareupdateexclusivelock,ShareUpdateExclusiveLocks Current,True,application,gauge
pg_locks_count_sireadlock,SIReadLocks Current,True,application,gauge
pg_stat_user_tables_autoanalyze_count,Autoanalyze Run Count,True,application,counter
pg_stat_user_tables_autovacuum_count,Autovacuum Run Count,True,application,counter
pg_stat_bgwriter_checkpoints_timed_per_req,Frequency of checkpoints (timed vs requested) [ratio],False,application,gauge
pg_stat_wal_volume_bytes_sec,Volume of WAL generated [bytes/sec],False,application,counter
pg_stat_bgwriter_buffers_backend_fsync,Backends forced to flush WAL (I/O contention) [fsync/sec],False,application,counter
pg_stat_activity_wait_event_count,Active sessions waiting on any event [count],False,application,gauge
pg_stat_user_tables_dead_tuples_per_vacuum,Dead tuples per vacuum operation [tuples/vacuum],True,application,ratio
pg_wal_segments,Number of WAL Segments,True,application,gauge
pg_wal_size_bytes,Total WAL Size [GiB],True,application,gauge
pg_wal_segments_rate,WAL Segments Growth Rate [segments/s],True,application,gauge
pg_wal_size_rate,WAL Growth Rate [MiB/s],True,application,gauge
pg_wal_avg_segment_size,Average WAL Segment Size [MiB],True,application,gauge
pg_wal_size_per_checkpoint,WAL Size per Checkpoint [bytes/checkpoint],False,application,gauge

## Names of Monitored Components

Names of components and their phases

In [7]:
collect.get_monitored_components()

                                           description
loading                  Loading phase: SUT deployment
datagenerator  Loading phase: component data generator
loader                 Loading phase: component loader
stream                 Execution phase: SUT deployment
benchmarker     Execution phase: component benchmarker

# Get Connection Infos

List of states of SUTs, containing loading infos.

In [8]:
df=collect.get_connections()

In [9]:
df.T

,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-1-1-1,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-2-2-1-2
code,1781936763,1781936763,1781936763,1781936763,1781936763,1781936763,1781938146,1781938146,1781938146,1781938146,1781938146,1781938146,1781939856,1781939856,1781939856,1781939856,1781939856,1781939856
connection,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2
configuration,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-2-2
job,1781936763-PostgreSQL-1-1-1-1,1781936763-PostgreSQL-1-1-2-1,1781936763-PostgreSQL-1-1-2-1,1781936763-PostgreSQL-1-2-1-1,1781936763-PostgreSQL-1-2-2-1,1781936763-PostgreSQL-1-2-2-1,1781938146-PostgreSQL-1-1-1-1,1781938146-PostgreSQL-1-1-2-1,1781938146-PostgreSQL-1-1-2-1,1781938146-PostgreSQL-1-2-1-1,1781938146-PostgreSQL-1-2-2-1,1781938146-PostgreSQL-1-2-2-1,1781939856-PostgreSQL-1-1-1-1,1781939856-PostgreSQL-1-1-2-1,1781939856-PostgreSQL-1-1-2-1,1781939856-PostgreSQL-1-2-1-1,1781939856-PostgreSQL-1-2-2-1,1781939856-PostgreSQL-1-2-2-1
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2,1,1,1,2,2,2
benchmark_run,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
client,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,325.00,325.00,325.00,325.00,325.00,325.00,627.00,627.00,627.00,627.00,627.00,627.00,342.00,342.00,342.00,336.00,336.00,336.00
time_preload,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,0.00,0.00
time_generate,22.00,22.00,22.00,22.00,22.00,22.00,19.00,19.00,19.00,19.00,19.00,19.00,18.00,18.00,18.00,17.00,17.00,17.00
time_ingest,88.00,88.00,88.00,88.00,88.00,88.00,178.00,178.00,178.00,178.00,178.00,178.00,43.00,43.00,43.00,51.00,51.00,51.00
time_postload,211.00,211.00,211.00,211.00,211.00,211.00,425.00,425.00,425.00,425.00,425.00,425.00,267.00,267.00,267.00,265.00,265.00,265.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2
loading_pods,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
tenant_id,,,,,,,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_RAM,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464
host_CPU,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570
host_GPU,,,,,,,,,,,,,,,,,,
host_Cores,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224
host_host,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic
host_node,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36
host_disk,1297521,1297513,1297513,1297515,1297513,1297513,1297683,1297694,1297694,1298572,1298581,1298581,1314934,1314936,1314936,1314945,1314951,1314951
host_datadisk,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_size,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6,6,6,6,6,6,6
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,,,,,,,
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6,6,6,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,,,,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856
sut_storage_storageClassName,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,None,None,None,None,None,None
sut_storage_storageSize,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,10Gi,10Gi,10Gi,10Gi,10Gi,10Gi
sut_storage_keep,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
sut_storage_storageConfiguration,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
arg_max_connections,640,640,640,640,640,640,640,640,640,640,640,640,640,640,640,640,640,640
arg_max_worker_processes,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
arg_max_parallel_workers,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
arg_max_parallel_workers_per_gather,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
arg_max_parallel_maintenance_workers,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
arg_shared_buffers,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB
arg_effective_cache_size,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB
arg_work_mem,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB
arg_maintenance_work_mem,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
arg_lock_timeout,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s
arg_idle_in_transaction_session_timeout,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000
benchmark_begin,NaN,2026-06-20 08:34:03,2026-06-20 08:34:03,2026-06-20 08:35:56,2026-06-20 08:42:24,2026-06-20 08:42:24,NaN,2026-06-20 08:59:46,2026-06-20 08:59:46,2026-06-20 09:02:20,2026-06-20 09:08:56,2026-06-20 09:08:56,NaN,2026-06-20 09:25:17,2026-06-20 09:25:17,2026-06-20 09:27:51,2026-06-20 09:37:55,2026-06-20 09:37:55
benchmark_end,NaN,2026-06-20 08:34:28,2026-06-20 08:34:28,2026-06-20 08:36:22,2026-06-20 08:44:41,2026-06-20 08:44:41,NaN,2026-06-20 09:00:42,2026-06-20 09:00:42,2026-06-20 09:03:18,2026-06-20 09:12:26,2026-06-20 09:12:26,NaN,2026-06-20 09:26:14,2026-06-20 09:26:14,2026-06-20 09:28:48,2026-06-20 09:38:47,2026-06-20 09:38:47
benchmark_duration,NaN,25,25,26,137,137,NaN,56,56,58,210,210,NaN,57,57,57,52,52

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [10]:
df[['phase', 'code', 'connection', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-1-1-1,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-2-2-1-2
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-2-2
code,1781936763,1781936763,1781936763,1781936763,1781936763,1781936763,1781938146,1781938146,1781938146,1781938146,1781938146,1781938146,1781939856,1781939856,1781939856,1781939856,1781939856,1781939856
connection,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2
configuration,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2
type_tenants,,,,,,,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Get Non-Constant Attributes

These attributes are (most probably) used to analyze performance.

In [11]:
collectors.get_non_constant(df).T

,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-1-1-1,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-2-2-1-2
code,1781936763,1781936763,1781936763,1781936763,1781936763,1781936763,1781938146,1781938146,1781938146,1781938146,1781938146,1781938146,1781939856,1781939856,1781939856,1781939856,1781939856,1781939856
connection,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-2-2
job,1781936763-PostgreSQL-1-1-1-1,1781936763-PostgreSQL-1-1-2-1,1781936763-PostgreSQL-1-1-2-1,1781936763-PostgreSQL-1-2-1-1,1781936763-PostgreSQL-1-2-2-1,1781936763-PostgreSQL-1-2-2-1,1781938146-PostgreSQL-1-1-1-1,1781938146-PostgreSQL-1-1-2-1,1781938146-PostgreSQL-1-1-2-1,1781938146-PostgreSQL-1-2-1-1,1781938146-PostgreSQL-1-2-2-1,1781938146-PostgreSQL-1-2-2-1,1781939856-PostgreSQL-1-1-1-1,1781939856-PostgreSQL-1-1-2-1,1781939856-PostgreSQL-1-1-2-1,1781939856-PostgreSQL-1-2-1-1,1781939856-PostgreSQL-1-2-2-1,1781939856-PostgreSQL-1-2-2-1
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2
time_load,325.00,325.00,325.00,325.00,325.00,325.00,627.00,627.00,627.00,627.00,627.00,627.00,342.00,342.00,342.00,336.00,336.00,336.00
time_preload,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,0.00,0.00
time_generate,22.00,22.00,22.00,22.00,22.00,22.00,19.00,19.00,19.00,19.00,19.00,19.00,18.00,18.00,18.00,17.00,17.00,17.00
time_ingest,88.00,88.00,88.00,88.00,88.00,88.00,178.00,178.00,178.00,178.00,178.00,178.00,43.00,43.00,43.00,51.00,51.00,51.00
time_postload,211.00,211.00,211.00,211.00,211.00,211.00,425.00,425.00,425.00,425.00,425.00,425.00,267.00,267.00,267.00,265.00,265.00,265.00
pods,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2
host_disk,1297521,1297513,1297513,1297515,1297513,1297513,1297683,1297694,1297694,1298572,1298581,1298581,1314934,1314936,1314936,1314945,1314951,1314951
loading_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6,6,6,6,6,6,6
benchmarking_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6,6,6,6,6,6,6
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856
sut_storage_storageClassName,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,None,None,None,None,None,None
sut_storage_storageSize,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,10Gi,10Gi,10Gi,10Gi,10Gi,10Gi
benchmark_begin,NaN,2026-06-20 08:34:03,2026-06-20 08:34:03,2026-06-20 08:35:56,2026-06-20 08:42:24,2026-06-20 08:42:24,NaN,2026-06-20 08:59:46,2026-06-20 08:59:46,2026-06-20 09:02:20,2026-06-20 09:08:56,2026-06-20 09:08:56,NaN,2026-06-20 09:25:17,2026-06-20 09:25:17,2026-06-20 09:27:51,2026-06-20 09:37:55,2026-06-20 09:37:55
benchmark_end,NaN,2026-06-20 08:34:28,2026-06-20 08:34:28,2026-06-20 08:36:22,2026-06-20 08:44:41,2026-06-20 08:44:41,NaN,2026-06-20 09:00:42,2026-06-20 09:00:42,2026-06-20 09:03:18,2026-06-20 09:12:26,2026-06-20 09:12:26,NaN,2026-06-20 09:26:14,2026-06-20 09:26:14,2026-06-20 09:28:48,2026-06-20 09:38:47,2026-06-20 09:38:47
benchmark_duration,NaN,25,25,26,137,137,NaN,56,56,58,210,210,NaN,57,57,57,52,52

# Monitoring Aggregated per Phase

In [12]:
df = collect.get_monitoring_aggregated_per_phase("stream")
df.T

add_metadata: combine on index and column 'job'

,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2
Memory Usage [MiB],4433.55,5053.33,4081.14,4982.36,7511.99,10677.14,5351.83,9410.28,8961.61,12748.76,5840.26,10362.52
Memory Usage Cached [MiB],8787.55,9407.33,7761.44,9446.03,16667.08,20880.24,12408.97,18291.04,19100.86,24048.42,14995.45,20227.65
CPU Utilization,0.32,1.27,0.17,0.80,1.25,2.89,0.55,3.27,2.33,3.66,1.76,3.84
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],11.43,85.24,384.88,34.93,50.35,438.49,1057.12,189.90,186.73,351.61,114.27,446.48
CPU User Time [s],10.67,71.18,311.51,30.83,38.23,366.53,860.76,153.79,149.26,290.41,86.37,370.41
CPU System Time [s],0.77,14.06,73.37,4.10,12.12,71.96,196.36,36.11,37.47,61.20,27.90,76.07
Network Rx Total [MiB],0.00,1.69,3304.33,0.22,31.45,3.68,6636.94,2.06,1.89,3.71,1.89,2.10
Network Tx Total [MiB],0.00,292.46,23.27,1.82,5946.02,3.70,41.41,0.15,1.88,3.71,1.91,0.54
Filesystem Read Total [MiB],0.02,0.00,3779.83,0.00,0.02,0.00,14142.70,5294.84,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.02,0.00,14124.86,0.00,0.02,5616.05,39895.09,0.23,504.00,11639.43,0.00,18251.99
Core Utilization Variance [%],0.63,0.50,0.24,0.23,0.31,0.31,0.31,0.33,0.27,0.25,0.29,0.36
Max Core Utilization [%],39.24,38.09,26.98,14.07,26.27,23.05,19.57,22.29,21.07,20.49,23.25,34.99
I/O Wait [%],11.74,10.30,7.24,11.42,9.15,8.06,7.83,12.28,5.07,4.87,1.99,2.49
Total I/O Wait Time [s],87.99,59.59,712.41,85.07,116.04,171.29,834.26,547.23,170.12,94.74,62.54,94.29
Number of Idle Sessions,0.00,0.00,0.15,0.00,0.00,0.00,0.00,0.00,0.53,0.40,0.00,0.00
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,7.00,5.00,7.00,0.00,6.00,6.00,7.00,12.00,2.00,13.00,7.00,14.00
Number of Active Application Sessions,7.00,5.00,7.00,0.00,6.00,6.00,7.00,12.00,3.00,12.00,7.00,14.00
Longest Active Transaction,1.07,0.51,8.47,-0.00,0.07,2.33,16.42,3.01,1.95,1.86,1.23,2.39
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,0.00,4.13,0.00,0.00,0.00,3.13,0.00,0.00,0.00,0.00,0.10
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,0.00,8.47,0.00,0.00,0.00,16.28,0.00,0.00,0.00,0.00,1.85
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,0.00,0.00,529712.00,0.00,1494449.00,0.00,1850164.00,0.00,1499019.00,0.00,1499348.00,0.00
Buffer Cache Hit Count,3157.00,20830555.00,7072328.00,0.00,30879600.00,73927419.00,28985341.00,68946465.00,35067119.00,68935428.00,25318376.00,53629143.00
Buffer Cache Hit Ratio,0.91,0.98,0.99,0.99,0.97,0.97,0.98,0.98,0.97,0.97,0.97,0.97
Index Scan Count,0.00,3217046.00,1269186.00,0.00,5622186.00,11319969.00,5622177.00,11318122.00,5653812.00,11307564.00,3701997.00,7403994.00
Index Tuple Fetch Count,0.00,14120940.00,5764541.00,0.00,17957255.00,38259120.00,17957246.00,38208448.00,19089599.00,38178958.00,17137685.00,34275370.00
Index Cache Hit Ratio,0.45,0.99,1.00,0.99,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Table Buffer Hit Count,0.00,11243976.00,3322386.00,0.00,14226125.00,40106219.00,12317532.00,35134978.00,18304811.00,35151496.00,14414250.00,31558602.00
Table Blocks Read Count,0.00,0.00,492280.00,0.00,1356899.00,0.00,1712241.00,0.00,1364722.00,0.00,1365051.00,0.00
Table Cache Hit Ratio,0.91,0.98,0.98,0.98,0.90,0.93,0.94,0.95,0.89,0.93,0.89,0.92
Total Cache Hit Ratio,0.91,0.98,0.99,0.99,0.97,0.97,0.98,0.98,0.97,0.97,0.97,0.97
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,10.46,17.59,20.65,2.00,12.42,9.44,16.50,22.86,4.91,23.59,18.21,35.34
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,10.46,17.59,20.65,2.00,12.42,9.44,16.50,22.86,4.91,23.59,18.21,35.34
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN
Number of WAL Segments,205.00,205.00,205.00,205.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00
Total WAL Size [GiB],3.20,3.20,3.20,3.20,6.41,6.41,6.41,6.41,6.41,6.41,6.41,6.41
WAL Segments Growth Rate [segments/s],0.72,0.25,0.00,0.00,0.20,0.00,0.00,0.00,1.43,0.00,1.32,0.00
WAL Growth Rate [MiB/s],11.51,3.98,0.00,0.00,3.22,0.00,0.00,0.00,22.92,0.00,21.19,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2

## With Metadata

Connection infos are added.

In [13]:
df = collect.add_metadata(df)
df.T

add_metadata: combine on index and column 'phase'

phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2
Memory Usage [MiB],4433.55,5053.33,4081.14,4982.36,7511.99,10677.14,5351.83,9410.28,8961.61,12748.76,5840.26,10362.52
Memory Usage Cached [MiB],8787.55,9407.33,7761.44,9446.03,16667.08,20880.24,12408.97,18291.04,19100.86,24048.42,14995.45,20227.65
CPU Utilization,0.32,1.27,0.17,0.80,1.25,2.89,0.55,3.27,2.33,3.66,1.76,3.84
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],11.43,85.24,384.88,34.93,50.35,438.49,1057.12,189.90,186.73,351.61,114.27,446.48
CPU User Time [s],10.67,71.18,311.51,30.83,38.23,366.53,860.76,153.79,149.26,290.41,86.37,370.41
CPU System Time [s],0.77,14.06,73.37,4.10,12.12,71.96,196.36,36.11,37.47,61.20,27.90,76.07
Network Rx Total [MiB],0.00,1.69,3304.33,0.22,31.45,3.68,6636.94,2.06,1.89,3.71,1.89,2.10
Network Tx Total [MiB],0.00,292.46,23.27,1.82,5946.02,3.70,41.41,0.15,1.88,3.71,1.91,0.54
Filesystem Read Total [MiB],0.02,0.00,3779.83,0.00,0.02,0.00,14142.70,5294.84,0.00,0.00,0.00,0.00
Filesystem Write Total [MiB],0.02,0.00,14124.86,0.00,0.02,5616.05,39895.09,0.23,504.00,11639.43,0.00,18251.99
Core Utilization Variance [%],0.63,0.50,0.24,0.23,0.31,0.31,0.31,0.33,0.27,0.25,0.29,0.36
Max Core Utilization [%],39.24,38.09,26.98,14.07,26.27,23.05,19.57,22.29,21.07,20.49,23.25,34.99
I/O Wait [%],11.74,10.30,7.24,11.42,9.15,8.06,7.83,12.28,5.07,4.87,1.99,2.49
Total I/O Wait Time [s],87.99,59.59,712.41,85.07,116.04,171.29,834.26,547.23,170.12,94.74,62.54,94.29
Number of Idle Sessions,0.00,0.00,0.15,0.00,0.00,0.00,0.00,0.00,0.53,0.40,0.00,0.00
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,7.00,5.00,7.00,0.00,6.00,6.00,7.00,12.00,2.00,13.00,7.00,14.00
Number of Active Application Sessions,7.00,5.00,7.00,0.00,6.00,6.00,7.00,12.00,3.00,12.00,7.00,14.00
Longest Active Transaction,1.07,0.51,8.47,-0.00,0.07,2.33,16.42,3.01,1.95,1.86,1.23,2.39
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,0.00,4.13,0.00,0.00,0.00,3.13,0.00,0.00,0.00,0.00,0.10
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,0.00,8.47,0.00,0.00,0.00,16.28,0.00,0.00,0.00,0.00,1.85
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,0.00,0.00,529712.00,0.00,1494449.00,0.00,1850164.00,0.00,1499019.00,0.00,1499348.00,0.00
Buffer Cache Hit Count,3157.00,20830555.00,7072328.00,0.00,30879600.00,73927419.00,28985341.00,68946465.00,35067119.00,68935428.00,25318376.00,53629143.00
Buffer Cache Hit Ratio,0.91,0.98,0.99,0.99,0.97,0.97,0.98,0.98,0.97,0.97,0.97,0.97
Index Scan Count,0.00,3217046.00,1269186.00,0.00,5622186.00,11319969.00,5622177.00,11318122.00,5653812.00,11307564.00,3701997.00,7403994.00
Index Tuple Fetch Count,0.00,14120940.00,5764541.00,0.00,17957255.00,38259120.00,17957246.00,38208448.00,19089599.00,38178958.00,17137685.00,34275370.00
Index Cache Hit Ratio,0.45,0.99,1.00,0.99,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00
Table Buffer Hit Count,0.00,11243976.00,3322386.00,0.00,14226125.00,40106219.00,12317532.00,35134978.00,18304811.00,35151496.00,14414250.00,31558602.00
Table Blocks Read Count,0.00,0.00,492280.00,0.00,1356899.00,0.00,1712241.00,0.00,1364722.00,0.00,1365051.00,0.00
Table Cache Hit Ratio,0.91,0.98,0.98,0.98,0.90,0.93,0.94,0.95,0.89,0.93,0.89,0.92
Total Cache Hit Ratio,0.91,0.98,0.99,0.99,0.97,0.97,0.98,0.98,0.97,0.97,0.97,0.97
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,10.46,17.59,20.65,2.00,12.42,9.44,16.50,22.86,4.91,23.59,18.21,35.34
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,10.46,17.59,20.65,2.00,12.42,9.44,16.50,22.86,4.91,23.59,18.21,35.34
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,NaN,0.00,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN
Number of WAL Segments,205.00,205.00,205.00,205.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00,410.00
Total WAL Size [GiB],3.20,3.20,3.20,3.20,6.41,6.41,6.41,6.41,6.41,6.41,6.41,6.41
WAL Segments Growth Rate [segments/s],0.72,0.25,0.00,0.00,0.20,0.00,0.00,0.00,1.43,0.00,1.32,0.00
WAL Growth Rate [MiB/s],11.51,3.98,0.00,0.00,3.22,0.00,0.00,0.00,22.92,0.00,21.19,0.00
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00,16.00
code,1781936763,1781936763,1781936763,1781936763,1781938146,1781938146,1781938146,1781938146,1781939856,1781939856,1781939856,1781939856
configuration,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1
job,1781936763-PostgreSQL-1-1-1-1,1781936763-PostgreSQL-1-1-2-1,1781936763-PostgreSQL-1-2-1-1,1781936763-PostgreSQL-1-2-2-1,1781938146-PostgreSQL-1-1-1-1,1781938146-PostgreSQL-1-1-2-1,1781938146-PostgreSQL-1-2-1-1,1781938146-PostgreSQL-1-2-2-1,1781939856-PostgreSQL-1-1-1-1,1781939856-PostgreSQL-1-1-2-1,1781939856-PostgreSQL-1-2-1-1,1781939856-PostgreSQL-1-2-2-1
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
benchmark_run,1,1,1,1,1,1,1,1,1,1,1,1
client,1,2,1,2,1,2,1,2,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,325.00,325.00,325.00,325.00,627.00,627.00,627.00,627.00,342.00,342.00,336.00,336.00
time_preload,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,0.00
time_generate,22.00,22.00,22.00,22.00,19.00,19.00,19.00,19.00,18.00,18.00,17.00,17.00
time_ingest,88.00,88.00,88.00,88.00,178.00,178.00,178.00,178.00,43.00,43.00,51.00,51.00
time_postload,211.00,211.00,211.00,211.00,425.00,425.00,425.00,425.00,267.00,267.00,265.00,265.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2,1,2,1,2
loading_pods,8,8,8,8,8,8,8,8,8,8,8,8
tenant_id,,,,,,,,,,,,
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,0,0,0,0,0,0,0,0,0,0,0,0
host_RAM,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464
host_CPU,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570
host_GPU,,,,,,,,,,,,
host_Cores,224,224,224,224,224,224,224,224,224,224,224,224
host_host,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic
host_node,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36
host_disk,1297521,1297513,1297515,1297513,1297683,1297694,1298572,1298581,1314934,1314936,1314945,1314951
host_datadisk,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_size,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6,6,6,6,6
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856
sut_storage_storageClassName,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,None,None,None,None
sut_storage_storageSize,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,10Gi,10Gi,10Gi,10Gi
sut_storage_keep,True,True,True,True,True,True,True,True,True,True,True,True
sut_storage_storageConfiguration,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
arg_max_connections,640,640,640,640,640,640,640,640,640,640,640,640
arg_max_worker_processes,16,16,16,16,16,16,16,16,16,16,16,16
arg_max_parallel_workers,16,16,16,16,16,16,16,16,16,16,16,16
arg_max_parallel_workers_per_gather,8,8,8,8,8,8,8,8,8,8,8,8
arg_max_parallel_maintenance_workers,4,4,4,4,4,4,4,4,4,4,4,4
arg_shared_buffers,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB
arg_effective_cache_size,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB
arg_work_mem,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB
arg_maintenance_work_mem,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
arg_lock_timeout,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s
arg_idle_in_transaction_session_timeout,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000
benchmark_begin,NaN,2026-06-20 08:34:03,2026-06-20 08:35:56,2026-06-20 08:42:24,NaN,2026-06-20 08:59:46,2026-06-20 09:02:20,2026-06-20 09:08:56,NaN,2026-06-20 09:25:17,2026-06-20 09:27:51,2026-06-20 09:37:55
benchmark_end,NaN,2026-06-20 08:34:28,2026-06-20 08:36:22,2026-06-20 08:44:41,NaN,2026-06-20 09:00:42,2026-06-20 09:03:18,2026-06-20 09:12:26,NaN,2026-06-20 09:26:14,2026-06-20 09:28:48,2026-06-20 09:38:47
benchmark_duration,NaN,25,26,137,NaN,56,58,210,NaN,57,57,52
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [14]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2
code,1781936763,1781936763,1781936763,1781936763,1781938146,1781938146,1781938146,1781938146,1781939856,1781939856,1781939856,1781939856
configuration,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2
type_tenants,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False

# Time Series of a Single Metric for a Single Experiment

This is particularly important if you require a customized aggregation or wish to monitor a component over time.

In [15]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_per_phase(code, metric=metric, component='stream')
df.T

,1781936763-PostgreSQL-1-1-1-1,1781936763-PostgreSQL-1-1-2-1,1781936763-PostgreSQL-1-2-1-1,1781936763-PostgreSQL-1-2-2-1
0,4404.96,4979.98,5007.15,4859.38
1,4404.96,4979.98,5007.15,4859.38
2,4404.96,4979.98,5007.15,4859.38
3,4404.96,4979.98,5007.15,4859.38
4,4404.96,4979.98,5007.15,4859.38
5,4404.96,4979.98,5007.15,4859.38
6,4442.12,4979.98,5007.15,4859.38
7,4442.12,4979.98,5007.15,4859.38
8,4442.12,4979.98,5007.15,4859.38
9,4442.12,4979.98,5007.15,5043.85
10,4442.12,4979.98,5007.15,5043.85
11,4442.12,4979.98,5007.15,5043.85
12,4442.12,4979.98,5007.15,5043.85
13,4442.12,4979.98,5007.15,5043.85
14,4442.12,4979.98,5007.15,5043.85
15,4442.12,4979.98,5007.15,5043.85
16,4442.12,5160.01,5007.15,5043.85
17,4442.12,5160.01,5007.15,5043.85
18,4442.12,5160.01,5007.15,5043.85
19,4442.12,5160.01,5007.15,5043.85
20,4442.12,5160.01,5007.15,5043.85
21,4442.12,5160.01,5007.15,5043.85
22,4442.12,5160.01,5007.15,5043.85
23,4442.12,5160.01,5007.15,5043.85
24,4442.12,5160.01,5007.15,5043.85
25,4442.12,5160.01,5007.15,5043.85
26,NaN,5160.01,5007.15,5043.85
27,NaN,NaN,5007.15,NaN
28,NaN,NaN,5007.15,NaN
29,NaN,NaN,5007.15,NaN
30,NaN,NaN,5007.15,NaN
31,NaN,NaN,5007.15,NaN
32,NaN,NaN,5007.15,NaN
33,NaN,NaN,5007.15,NaN
34,NaN,NaN,5007.15,NaN
35,NaN,NaN,5007.15,NaN
36,NaN,NaN,5007.15,NaN
37,NaN,NaN,5007.15,NaN
38,NaN,NaN,5007.15,NaN
39,NaN,NaN,5007.15,NaN
40,NaN,NaN,5007.15,NaN
41,NaN,NaN,5007.15,NaN
42,NaN,NaN,5007.15,NaN
43,NaN,NaN,5007.15,NaN
44,NaN,NaN,5007.15,NaN
45,NaN,NaN,5007.15,NaN
46,NaN,NaN,5007.15,NaN
47,NaN,NaN,5007.15,NaN
48,NaN,NaN,2523.38,NaN
49,NaN,NaN,2523.38,NaN
50,NaN,NaN,2523.38,NaN
51,NaN,NaN,2523.38,NaN
52,NaN,NaN,2523.38,NaN
53,NaN,NaN,2523.38,NaN
54,NaN,NaN,2523.38,NaN
55,NaN,NaN,2523.38,NaN
56,NaN,NaN,2523.38,NaN
57,NaN,NaN,2523.38,NaN
58,NaN,NaN,2523.38,NaN
59,NaN,NaN,2523.38,NaN
60,NaN,NaN,2523.38,NaN
61,NaN,NaN,2523.38,NaN
62,NaN,NaN,2523.38,NaN
63,NaN,NaN,2523.38,NaN
64,NaN,NaN,2523.38,NaN
65,NaN,NaN,2523.38,NaN
66,NaN,NaN,2523.38,NaN
67,NaN,NaN,2523.38,NaN
68,NaN,NaN,2523.38,NaN
69,NaN,NaN,2523.38,NaN
70,NaN,NaN,2523.38,NaN
71,NaN,NaN,2523.38,NaN
72,NaN,NaN,2523.38,NaN
73,NaN,NaN,2523.38,NaN
74,NaN,NaN,2523.38,NaN
75,NaN,NaN,2523.38,NaN
76,NaN,NaN,3565.91,NaN
77,NaN,NaN,3565.91,NaN
78,NaN,NaN,3565.91,NaN
79,NaN,NaN,3565.91,NaN
80,NaN,NaN,3565.91,NaN
81,NaN,NaN,3565.91,NaN
82,NaN,NaN,3565.91,NaN
83,NaN,NaN,3565.91,NaN
84,NaN,NaN,3565.91,NaN
85,NaN,NaN,3565.91,NaN
86,NaN,NaN,3565.91,NaN
87,NaN,NaN,3565.91,NaN
88,NaN,NaN,3565.91,NaN
89,NaN,NaN,3565.91,NaN
90,NaN,NaN,3565.91,NaN
91,NaN,NaN,3565.91,NaN
92,NaN,NaN,3565.91,NaN
93,NaN,NaN,3565.91,NaN
94,NaN,NaN,3565.91,NaN
95,NaN,NaN,3565.91,NaN
96,NaN,NaN,4306.70,NaN
97,NaN,NaN,4306.70,NaN
98,NaN,NaN,4306.70,NaN
99,NaN,NaN,4306.70,NaN
100,NaN,NaN,4306.70,NaN
101,NaN,NaN,4306.70,NaN
102,NaN,NaN,4306.70,NaN
103,NaN,NaN,4306.70,NaN
104,NaN,NaN,4306.70,NaN
105,NaN,NaN,4306.70,NaN
106,NaN,NaN,4306.70,NaN
107,NaN,NaN,4306.70,NaN
108,NaN,NaN,4306.70,NaN
109,NaN,NaN,4306.70,NaN
110,NaN,NaN,4306.70,NaN
111,NaN,NaN,4306.70,NaN
112,NaN,NaN,4306.70,NaN
113,NaN,NaN,4306.70,NaN
114,NaN,NaN,4306.70,NaN
115,NaN,NaN,4306.70,NaN
116,NaN,NaN,4306.70,NaN
117,NaN,NaN,4306.70,NaN
118,NaN,NaN,4306.70,NaN
119,NaN,NaN,4306.70,NaN
120,NaN,NaN,4306.70,NaN
121,NaN,NaN,4306.70,NaN
122,NaN,NaN,4306.70,NaN
123,NaN,NaN,4306.70,NaN
124,NaN,NaN,4306.70,NaN
125,NaN,NaN,4306.70,NaN
126,NaN,NaN,4306.70,NaN
127,NaN,NaN,4306.70,NaN
128,NaN,NaN,4306.70,NaN
129,NaN,NaN,4306.70,NaN
130,NaN,NaN,4306.70,NaN
131,NaN,NaN,4306.70,NaN
132,NaN,NaN,4306.70,NaN
133,NaN,NaN,4306.70,NaN
134,NaN,NaN,4306.70,NaN
135,NaN,NaN,4306.70,NaN
136,NaN,NaN,4306.70,NaN
137,NaN,NaN,4306.70,NaN

## With Metadata

Connection infos are added.

In [16]:
df = collect.add_metadata(df)
df.T

add_metadata: combine on index and column 'job'

job,1781936763-PostgreSQL-1-1-1-1,1781936763-PostgreSQL-1-1-2-1,1781936763-PostgreSQL-1-2-1-1,1781936763-PostgreSQL-1-2-2-1
0,4404.96,4979.98,5007.15,4859.38
1,4404.96,4979.98,5007.15,4859.38
2,4404.96,4979.98,5007.15,4859.38
3,4404.96,4979.98,5007.15,4859.38
4,4404.96,4979.98,5007.15,4859.38
5,4404.96,4979.98,5007.15,4859.38
6,4442.12,4979.98,5007.15,4859.38
7,4442.12,4979.98,5007.15,4859.38
8,4442.12,4979.98,5007.15,4859.38
9,4442.12,4979.98,5007.15,5043.85
10,4442.12,4979.98,5007.15,5043.85
11,4442.12,4979.98,5007.15,5043.85
12,4442.12,4979.98,5007.15,5043.85
13,4442.12,4979.98,5007.15,5043.85
14,4442.12,4979.98,5007.15,5043.85
15,4442.12,4979.98,5007.15,5043.85
16,4442.12,5160.01,5007.15,5043.85
17,4442.12,5160.01,5007.15,5043.85
18,4442.12,5160.01,5007.15,5043.85
19,4442.12,5160.01,5007.15,5043.85
20,4442.12,5160.01,5007.15,5043.85
21,4442.12,5160.01,5007.15,5043.85
22,4442.12,5160.01,5007.15,5043.85
23,4442.12,5160.01,5007.15,5043.85
24,4442.12,5160.01,5007.15,5043.85
25,4442.12,5160.01,5007.15,5043.85
26,NaN,5160.01,5007.15,5043.85
27,NaN,NaN,5007.15,NaN
28,NaN,NaN,5007.15,NaN
29,NaN,NaN,5007.15,NaN
30,NaN,NaN,5007.15,NaN
31,NaN,NaN,5007.15,NaN
32,NaN,NaN,5007.15,NaN
33,NaN,NaN,5007.15,NaN
34,NaN,NaN,5007.15,NaN
35,NaN,NaN,5007.15,NaN
36,NaN,NaN,5007.15,NaN
37,NaN,NaN,5007.15,NaN
38,NaN,NaN,5007.15,NaN
39,NaN,NaN,5007.15,NaN
40,NaN,NaN,5007.15,NaN
41,NaN,NaN,5007.15,NaN
42,NaN,NaN,5007.15,NaN
43,NaN,NaN,5007.15,NaN
44,NaN,NaN,5007.15,NaN
45,NaN,NaN,5007.15,NaN
46,NaN,NaN,5007.15,NaN
47,NaN,NaN,5007.15,NaN
48,NaN,NaN,2523.38,NaN
49,NaN,NaN,2523.38,NaN
50,NaN,NaN,2523.38,NaN
51,NaN,NaN,2523.38,NaN
52,NaN,NaN,2523.38,NaN
53,NaN,NaN,2523.38,NaN
54,NaN,NaN,2523.38,NaN
55,NaN,NaN,2523.38,NaN
56,NaN,NaN,2523.38,NaN
57,NaN,NaN,2523.38,NaN
58,NaN,NaN,2523.38,NaN
59,NaN,NaN,2523.38,NaN
60,NaN,NaN,2523.38,NaN
61,NaN,NaN,2523.38,NaN
62,NaN,NaN,2523.38,NaN
63,NaN,NaN,2523.38,NaN
64,NaN,NaN,2523.38,NaN
65,NaN,NaN,2523.38,NaN
66,NaN,NaN,2523.38,NaN
67,NaN,NaN,2523.38,NaN
68,NaN,NaN,2523.38,NaN
69,NaN,NaN,2523.38,NaN
70,NaN,NaN,2523.38,NaN
71,NaN,NaN,2523.38,NaN
72,NaN,NaN,2523.38,NaN
73,NaN,NaN,2523.38,NaN
74,NaN,NaN,2523.38,NaN
75,NaN,NaN,2523.38,NaN
76,NaN,NaN,3565.91,NaN
77,NaN,NaN,3565.91,NaN
78,NaN,NaN,3565.91,NaN
79,NaN,NaN,3565.91,NaN
80,NaN,NaN,3565.91,NaN
81,NaN,NaN,3565.91,NaN
82,NaN,NaN,3565.91,NaN
83,NaN,NaN,3565.91,NaN
84,NaN,NaN,3565.91,NaN
85,NaN,NaN,3565.91,NaN
86,NaN,NaN,3565.91,NaN
87,NaN,NaN,3565.91,NaN
88,NaN,NaN,3565.91,NaN
89,NaN,NaN,3565.91,NaN
90,NaN,NaN,3565.91,NaN
91,NaN,NaN,3565.91,NaN
92,NaN,NaN,3565.91,NaN
93,NaN,NaN,3565.91,NaN
94,NaN,NaN,3565.91,NaN
95,NaN,NaN,3565.91,NaN
96,NaN,NaN,4306.70,NaN
97,NaN,NaN,4306.70,NaN
98,NaN,NaN,4306.70,NaN
99,NaN,NaN,4306.70,NaN
100,NaN,NaN,4306.70,NaN
101,NaN,NaN,4306.70,NaN
102,NaN,NaN,4306.70,NaN
103,NaN,NaN,4306.70,NaN
104,NaN,NaN,4306.70,NaN
105,NaN,NaN,4306.70,NaN
106,NaN,NaN,4306.70,NaN
107,NaN,NaN,4306.70,NaN
108,NaN,NaN,4306.70,NaN
109,NaN,NaN,4306.70,NaN
110,NaN,NaN,4306.70,NaN
111,NaN,NaN,4306.70,NaN
112,NaN,NaN,4306.70,NaN
113,NaN,NaN,4306.70,NaN
114,NaN,NaN,4306.70,NaN
115,NaN,NaN,4306.70,NaN
116,NaN,NaN,4306.70,NaN
117,NaN,NaN,4306.70,NaN
118,NaN,NaN,4306.70,NaN
119,NaN,NaN,4306.70,NaN
120,NaN,NaN,4306.70,NaN
121,NaN,NaN,4306.70,NaN
122,NaN,NaN,4306.70,NaN
123,NaN,NaN,4306.70,NaN
124,NaN,NaN,4306.70,NaN
125,NaN,NaN,4306.70,NaN
126,NaN,NaN,4306.70,NaN
127,NaN,NaN,4306.70,NaN
128,NaN,NaN,4306.70,NaN
129,NaN,NaN,4306.70,NaN
130,NaN,NaN,4306.70,NaN
131,NaN,NaN,4306.70,NaN
132,NaN,NaN,4306.70,NaN
133,NaN,NaN,4306.70,NaN
134,NaN,NaN,4306.70,NaN
135,NaN,NaN,4306.70,NaN
136,NaN,NaN,4306.70,NaN
137,NaN,NaN,4306.70,NaN
code,1781936763,1781936763,1781936763,1781936763
configuration,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2
experiment_run,1,1,2,2
benchmark_run,1,1,1,1
client,1,2,1,2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,325.00,325.00,325.00,325.00
time_preload,1.00,1.00,1.00,1.00
time_generate,22.00,22.00,22.00,22.00
time_ingest,88.00,88.00,88.00,88.00
time_postload,211.00,211.00,211.00,211.00
terminals,0,0,0,0
pods,1,2,1,2
loading_pods,8,8,8,8
tenant_id,,,,
num_worker,0,0,0,0
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False
datadisk,0,0,0,0
host_RAM,2164173246464,2164173246464,2164173246464,2164173246464
host_CPU,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570
host_GPU,,,,
host_Cores,224,224,224,224
host_host,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic
host_node,cl-worker36,cl-worker36,cl-worker36,cl-worker36
host_disk,1297521,1297513,1297515,1297513
host_datadisk,0,0,0,0
host_volume_size,0,0,0,0
host_volume_used,0,0,0,0
host_cuda,,,,
host_hugepages_total,0,0,0,0
host_hugepages_free,0,0,0,0
host_cpu_list,0-223,0-223,0-223,0-223
host_requests_cpu,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3
loading_parameters_STORE_RAW_DATA,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1
loading_parameters_TPCH_TABLE,,,,
loading_parameters_PODS_TOTAL,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8
loading_parameters_BEXHOMA_TENANT_BY,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
loading_parameters_BEXHOMA_TENANT_ID,0,0,0,0
benchmarking_parameters_SF,3,3,3,3
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_ID,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763
sut_storage_storageClassName,cephcsi,cephcsi,cephcsi,cephcsi
sut_storage_storageSize,30Gi,30Gi,30Gi,30Gi
sut_storage_keep,True,True,True,True
sut_storage_storageConfiguration,postgresql,postgresql,postgresql,postgresql
arg_max_connections,640,640,640,640
arg_max_worker_processes,16,16,16,16
arg_max_parallel_workers,16,16,16,16
arg_max_parallel_workers_per_gather,8,8,8,8
arg_max_parallel_maintenance_workers,4,4,4,4
arg_shared_buffers,16GB,16GB,16GB,16GB
arg_effective_cache_size,40GB,40GB,40GB,40GB
arg_work_mem,512MB,512MB,512MB,512MB
arg_maintenance_work_mem,2GB,2GB,2GB,2GB
arg_autovacuum,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,1h,1h,1h,1h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0
arg_lock_timeout,30s,30s,30s,30s
arg_idle_in_transaction_session_timeout,30000,30000,30000,30000
benchmark_begin,NaN,2026-06-20 08:34:03,2026-06-20 08:35:56,2026-06-20 08:42:24
benchmark_end,NaN,2026-06-20 08:34:28,2026-06-20 08:36:22,2026-06-20 08:44:41
benchmark_duration,NaN,25,26,137
job,1781936763-PostgreSQL-1-1-1-1,1781936763-PostgreSQL-1-1-2-1,1781936763-PostgreSQL-1-2-1-1,1781936763-PostgreSQL-1-2-2-1

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [17]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head().T

job,1781936763-PostgreSQL-1-1-1-1,1781936763-PostgreSQL-1-1-2-1,1781936763-PostgreSQL-1-2-1-1,1781936763-PostgreSQL-1-2-2-1
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2
code,1781936763,1781936763,1781936763,1781936763
configuration,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1
experiment_run,1,1,2,2
client,1,2,1,2
type_tenants,,,,
num_tenants,0,0,0,0
vol_tenants,False,False,False,False

# Time Series of a Single Metric for All Experiments

This is particularly important if you require a customized aggregation or wish to monitor a component over time.
Data is stacked here (long format).

In [18]:
metric = 'total_cpu_memory'
code = codes[0]
df = collect.get_monitoring_timeseries_all(metric=metric)
df.head()

,timestamp,code,phase,job,experiment_run,client,benchmark_run,type_tenants,vol_tenants,num_tenants,metric,component,value
0,0,1781936763,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-1-1,1,1,1,,False,0,total_cpu_memory,stream,4404.96
1,0,1781936763,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-1-2-1,1,2,1,,False,0,total_cpu_memory,stream,9959.97
2,0,1781936763,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-1-1,2,1,1,,False,0,total_cpu_memory,stream,5007.15
3,0,1781936763,1781936763-PostgreSQL-1-2-2,1781936763-PostgreSQL-1-2-2-1,2,2,1,,False,0,total_cpu_memory,stream,9718.76
4,0,1781938146,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-1-1,1,1,1,,False,0,total_cpu_memory,stream,3383.75

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [19]:
df[['timestamp', 'phase', 'value']].head(8)

   timestamp                        phase    value
0          0  1781936763-PostgreSQL-1-1-1  4404.96
1          0  1781936763-PostgreSQL-1-1-2  9959.97
2          0  1781936763-PostgreSQL-1-2-1  5007.15
3          0  1781936763-PostgreSQL-1-2-2  9718.76
4          0  1781938146-PostgreSQL-1-1-1  3383.75
5          0  1781938146-PostgreSQL-1-1-2 19321.84
6          0  1781938146-PostgreSQL-1-2-1  9660.98
7          0  1781938146-PostgreSQL-1-2-2 18630.36

## With Metadata

Connection infos are added.

In [20]:
df=collect.add_metadata(df)
df = df.sort_values(['timestamp', 'phase'])
df[['timestamp', 'phase', 'value']].head(8)

add_metadata: combine on columns phase

                             timestamp                        phase    value
1781936763-PostgreSQL-1-1-1          0  1781936763-PostgreSQL-1-1-1  4404.96
1781936763-PostgreSQL-1-1-2          0  1781936763-PostgreSQL-1-1-2  9959.97
1781936763-PostgreSQL-1-2-1          0  1781936763-PostgreSQL-1-2-1  5007.15
1781936763-PostgreSQL-1-2-2          0  1781936763-PostgreSQL-1-2-2  9718.76
1781938146-PostgreSQL-1-1-1          0  1781938146-PostgreSQL-1-1-1  3383.75
1781938146-PostgreSQL-1-1-2          0  1781938146-PostgreSQL-1-1-2 19321.84
1781938146-PostgreSQL-1-2-1          0  1781938146-PostgreSQL-1-2-1  9660.98
1781938146-PostgreSQL-1-2-2          0  1781938146-PostgreSQL-1-2-2 18630.36

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [21]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].head().T

,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1
code,1781936763,1781936763,1781936763,1781936763,1781938146
configuration,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1
experiment_run,1,1,2,2,1
client,1,2,1,2,1
type_tenants,,,,,
num_tenants,0,0,0,0,0
vol_tenants,False,False,False,False,False

## Custom Aggregation and Scale

We here aggregate CPU utilization by max per phase.

In [22]:
metric = 'total_cpu_util'

df_performance_series = collect.get_monitoring_timeseries_all(metric)

df_agg = (
    df_performance_series.groupby(["code", "experiment_run", "client", "type_tenants", "num_tenants"])["value"]
      .max()
      .reset_index()
)
df_agg.index.name = 'Max ' + collect.df_metrics.loc[metric]['title']
df_agg

,code,experiment_run,client,type_tenants,num_tenants,value
Max CPU Utilization,,,,,,
0,1781936763,1,1,,0,0.36
1,1781936763,1,2,,0,6.21
2,1781936763,2,1,,0,0.35
3,1781936763,2,2,,0,2.39
4,1781938146,1,1,,0,1.66
5,1781938146,1,2,,0,17.01
6,1781938146,2,1,,0,2.77
7,1781938146,2,2,,0,13.08
8,1781939856,1,1,,0,4.19
9,1781939856,1,2,,0,16.13
10,1781939856,2,1,,0,3.82
11,1781939856,2,2,,0,17.96

# Performance Results per Connection

In [23]:
df_performance = collect.get_performance_per_connection()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.T

,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-1-1-1,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-2-2-1-2
code,1781936763,1781936763,1781936763,1781936763,1781936763,1781936763,1781938146,1781938146,1781938146,1781938146,1781938146,1781938146,1781939856,1781939856,1781939856,1781939856,1781939856,1781939856
configuration,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-2-2
job,PostgreSQL-1-1-1-1,PostgreSQL-1-1-2-1,PostgreSQL-1-1-2-1,PostgreSQL-1-2-1-1,PostgreSQL-1-2-2-1,PostgreSQL-1-2-2-1,PostgreSQL-1-1-1-1,PostgreSQL-1-1-2-1,PostgreSQL-1-1-2-1,PostgreSQL-1-2-1-1,PostgreSQL-1-2-2-1,PostgreSQL-1-2-2-1,PostgreSQL-1-1-1-1,PostgreSQL-1-1-2-1,PostgreSQL-1-1-2-1,PostgreSQL-1-2-1-1,PostgreSQL-1-2-2-1,PostgreSQL-1-2-2-1
connection,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-1-1-1,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-2-2-1-2
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2
benchmark_run,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
pod_count,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
SF,3.00,3.00,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
time [s],25,24,25,137,25,25,56,56,58,210,57,57,57,57,55,52,54,57
Geo Times [s],0.63,0.57,0.62,1.37,0.62,0.62,1.45,1.34,1.36,2.50,1.33,1.33,1.31,1.29,1.27,1.30,1.28,1.34
Power@Size [~Q/h],17216.26,19106.25,17414.47,7885.59,17501.71,17434.08,14855.57,16078.96,15896.36,8649.36,16223.16,16188.27,16484.37,16699.13,16952.14,16582.04,16909.16,16133.58
Throughput@Size,9504.00,9900.00,9504.00,1734.31,9504.00,9504.00,8485.71,8485.71,8193.10,2262.86,8336.84,8336.84,8336.84,8336.84,8640.00,9138.46,8800.00,8336.84
tenant_id,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pod,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2

## With Metadata

Connection infos are added.

In [24]:
df = collect.add_metadata(df_performance)
df.T

add_metadata: combine on index

,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-1-1-1,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-2-2-1-2
code,1781936763,1781936763,1781936763,1781936763,1781936763,1781936763,1781938146,1781938146,1781938146,1781938146,1781938146,1781938146,1781939856,1781939856,1781939856,1781939856,1781939856,1781939856
configuration,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-2-2
job,PostgreSQL-1-1-1-1,PostgreSQL-1-1-2-1,PostgreSQL-1-1-2-1,PostgreSQL-1-2-1-1,PostgreSQL-1-2-2-1,PostgreSQL-1-2-2-1,PostgreSQL-1-1-1-1,PostgreSQL-1-1-2-1,PostgreSQL-1-1-2-1,PostgreSQL-1-2-1-1,PostgreSQL-1-2-2-1,PostgreSQL-1-2-2-1,PostgreSQL-1-1-1-1,PostgreSQL-1-1-2-1,PostgreSQL-1-1-2-1,PostgreSQL-1-2-1-1,PostgreSQL-1-2-2-1,PostgreSQL-1-2-2-1
connection,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-1-1-1,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-2-2-1-2
experiment_run,1,1,1,2,2,2,1,1,1,2,2,2,1,1,1,2,2,2
client,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2
benchmark_run,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
pod_count,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
SF,3.00,3.00,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00
num_of_queries,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
time [s],25,24,25,137,25,25,56,56,58,210,57,57,57,57,55,52,54,57
Geo Times [s],0.63,0.57,0.62,1.37,0.62,0.62,1.45,1.34,1.36,2.50,1.33,1.33,1.31,1.29,1.27,1.30,1.28,1.34
Power@Size [~Q/h],17216.26,19106.25,17414.47,7885.59,17501.71,17434.08,14855.57,16078.96,15896.36,8649.36,16223.16,16188.27,16484.37,16699.13,16952.14,16582.04,16909.16,16133.58
Throughput@Size,9504.00,9900.00,9504.00,1734.31,9504.00,9504.00,8485.71,8485.71,8193.10,2262.86,8336.84,8336.84,8336.84,8336.84,8640.00,9138.46,8800.00,8336.84
tenant_id,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pod,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2,PostgreSQL-1-1-1-1-1,PostgreSQL-1-1-2-1-1,PostgreSQL-1-1-2-1-2,PostgreSQL-1-2-1-1-1,PostgreSQL-1-2-2-1-1,PostgreSQL-1-2-2-1-2
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,325.00,325.00,325.00,325.00,325.00,325.00,627.00,627.00,627.00,627.00,627.00,627.00,342.00,342.00,342.00,336.00,336.00,336.00
time_preload,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,0.00,0.00
time_generate,22.00,22.00,22.00,22.00,22.00,22.00,19.00,19.00,19.00,19.00,19.00,19.00,18.00,18.00,18.00,17.00,17.00,17.00
time_ingest,88.00,88.00,88.00,88.00,88.00,88.00,178.00,178.00,178.00,178.00,178.00,178.00,43.00,43.00,43.00,51.00,51.00,51.00
time_postload,211.00,211.00,211.00,211.00,211.00,211.00,425.00,425.00,425.00,425.00,425.00,425.00,267.00,267.00,267.00,265.00,265.00,265.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2,1,2,2
loading_pods,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
num_worker,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_RAM,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464
host_CPU,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570
host_GPU,,,,,,,,,,,,,,,,,,
host_Cores,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224,224
host_host,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic
host_node,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36
host_disk,1297521,1297513,1297513,1297515,1297513,1297513,1297683,1297694,1297694,1298572,1298581,1298581,1314934,1314936,1314936,1314945,1314951,1314951
host_datadisk,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_size,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6,6,6,6,6,6,6
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,,,,,,,
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,3,3,6,6,6,6,6,6,6,6,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,,,,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856
sut_storage_storageClassName,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,None,None,None,None,None,None
sut_storage_storageSize,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,10Gi,10Gi,10Gi,10Gi,10Gi,10Gi
sut_storage_keep,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
sut_storage_storageConfiguration,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
arg_max_connections,640,640,640,640,640,640,640,640,640,640,640,640,640,640,640,640,640,640
arg_max_worker_processes,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
arg_max_parallel_workers,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16,16
arg_max_parallel_workers_per_gather,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8,8
arg_max_parallel_maintenance_workers,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
arg_shared_buffers,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB
arg_effective_cache_size,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB
arg_work_mem,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB
arg_maintenance_work_mem,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
arg_lock_timeout,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s
arg_idle_in_transaction_session_timeout,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000
benchmark_begin,NaN,2026-06-20 08:34:03,2026-06-20 08:34:03,2026-06-20 08:35:56,2026-06-20 08:42:24,2026-06-20 08:42:24,NaN,2026-06-20 08:59:46,2026-06-20 08:59:46,2026-06-20 09:02:20,2026-06-20 09:08:56,2026-06-20 09:08:56,NaN,2026-06-20 09:25:17,2026-06-20 09:25:17,2026-06-20 09:27:51,2026-06-20 09:37:55,2026-06-20 09:37:55
benchmark_end,NaN,2026-06-20 08:34:28,2026-06-20 08:34:28,2026-06-20 08:36:22,2026-06-20 08:44:41,2026-06-20 08:44:41,NaN,2026-06-20 09:00:42,2026-06-20 09:00:42,2026-06-20 09:03:18,2026-06-20 09:12:26,2026-06-20 09:12:26,NaN,2026-06-20 09:26:14,2026-06-20 09:26:14,2026-06-20 09:28:48,2026-06-20 09:38:47,2026-06-20 09:38:47
benchmark_duration,NaN,25,25,26,137,137,NaN,56,56,58,210,210,NaN,57,57,57,52,52

# Performance Results per Phase

In [25]:
df_performance = collect.get_performance_aggregated_per_phase()

df_performance_first = df_performance[df_performance['client']==1]
df_performance_second = df_performance[df_performance['client']==2]

df_performance.dropna(inplace=True)

In [26]:
df_performance.T

,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2
code,1781936763,1781936763,1781936763,1781936763,1781938146,1781938146,1781938146,1781938146,1781939856,1781939856,1781939856,1781939856
configuration,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2
benchmark_run,1,1,1,1,1,1,1,1,1,1,1,1
pod_count,1,2,1,2,1,2,1,2,1,2,1,2
SF,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00
num_of_queries,22,44,22,44,22,44,22,44,22,44,22,44
time [s],25,25,137,25,56,58,210,57,57,57,52,57
Geo Times [s],0.63,0.59,1.37,0.62,1.45,1.35,2.50,1.33,1.31,1.28,1.30,1.31
Power@Size [~Q/h],17216.26,18240.76,7885.59,17467.87,14855.57,15987.40,8649.36,16205.71,16484.37,16825.16,16582.04,16516.82
Throughput@Size,9504.00,19008.00,1734.31,19008.00,8485.71,16386.21,2262.86,16673.68,8336.84,16673.68,9138.46,16673.68
tenant_id,0,0,0,0,0,0,0,0,0,0,0,0

## With Metadata

Connection infos are added.

In [27]:
df = collect.add_metadata(df_performance)
df.T

add_metadata: combine on index and column 'phase'

phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2
code,1781936763,1781936763,1781936763,1781936763,1781938146,1781938146,1781938146,1781938146,1781939856,1781939856,1781939856,1781939856
configuration,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2
benchmark_run,1,1,1,1,1,1,1,1,1,1,1,1
pod_count,1,2,1,2,1,2,1,2,1,2,1,2
SF,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00
num_of_queries,22,44,22,44,22,44,22,44,22,44,22,44
time [s],25,25,137,25,56,58,210,57,57,57,52,57
Geo Times [s],0.63,0.59,1.37,0.62,1.45,1.35,2.50,1.33,1.31,1.28,1.30,1.31
Power@Size [~Q/h],17216.26,18240.76,7885.59,17467.87,14855.57,15987.40,8649.36,16205.71,16484.37,16825.16,16582.04,16516.82
Throughput@Size,9504.00,19008.00,1734.31,19008.00,8485.71,16386.21,2262.86,16673.68,8336.84,16673.68,9138.46,16673.68
tenant_id,0,0,0,0,0,0,0,0,0,0,0,0
job,1781936763-PostgreSQL-1-1-1-1,1781936763-PostgreSQL-1-1-2-1,1781936763-PostgreSQL-1-2-1-1,1781936763-PostgreSQL-1-2-2-1,1781938146-PostgreSQL-1-1-1-1,1781938146-PostgreSQL-1-1-2-1,1781938146-PostgreSQL-1-2-1-1,1781938146-PostgreSQL-1-2-2-1,1781939856-PostgreSQL-1-1-1-1,1781939856-PostgreSQL-1-1-2-1,1781939856-PostgreSQL-1-2-1-1,1781939856-PostgreSQL-1-2-2-1
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,325.00,325.00,325.00,325.00,627.00,627.00,627.00,627.00,342.00,342.00,336.00,336.00
time_preload,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,0.00
time_generate,22.00,22.00,22.00,22.00,19.00,19.00,19.00,19.00,18.00,18.00,17.00,17.00
time_ingest,88.00,88.00,88.00,88.00,178.00,178.00,178.00,178.00,43.00,43.00,51.00,51.00
time_postload,211.00,211.00,211.00,211.00,425.00,425.00,425.00,425.00,267.00,267.00,265.00,265.00
terminals,0,0,0,0,0,0,0,0,0,0,0,0
pods,1,2,1,2,1,2,1,2,1,2,1,2
loading_pods,8,8,8,8,8,8,8,8,8,8,8,8
num_worker,0,0,0,0,0,0,0,0,0,0,0,0
type_tenants,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False
datadisk,0,0,0,0,0,0,0,0,0,0,0,0
host_RAM,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464
host_CPU,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570
host_GPU,,,,,,,,,,,,
host_Cores,224,224,224,224,224,224,224,224,224,224,224,224
host_host,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic
host_node,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36
host_disk,1297521,1297513,1297515,1297513,1297683,1297694,1298572,1298581,1314934,1314936,1314945,1314951
host_datadisk,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_size,0,0,0,0,0,0,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0,0,0,0,0,0,0
host_cuda,,,,,,,,,,,,
host_hugepages_total,0,0,0,0,0,0,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0,0,0,0,0,0,0
host_cpu_list,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223,0-223
host_requests_cpu,4,4,4,4,4,4,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,3,3,6,6,6,6,6,6,6,6
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,,,,,,,
loading_parameters_PODS_TOTAL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8,8,8,8,8,8,8
loading_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
loading_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,3,3,6,6,6,6,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856
sut_storage_storageClassName,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,None,None,None,None
sut_storage_storageSize,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,10Gi,10Gi,10Gi,10Gi
sut_storage_keep,True,True,True,True,True,True,True,True,True,True,True,True
sut_storage_storageConfiguration,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
arg_max_connections,640,640,640,640,640,640,640,640,640,640,640,640
arg_max_worker_processes,16,16,16,16,16,16,16,16,16,16,16,16
arg_max_parallel_workers,16,16,16,16,16,16,16,16,16,16,16,16
arg_max_parallel_workers_per_gather,8,8,8,8,8,8,8,8,8,8,8,8
arg_max_parallel_maintenance_workers,4,4,4,4,4,4,4,4,4,4,4,4
arg_shared_buffers,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB,16GB
arg_effective_cache_size,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB,40GB
arg_work_mem,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB,512MB
arg_maintenance_work_mem,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB,2GB
arg_autovacuum,off,off,off,off,off,off,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0,0,0,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h,1h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
arg_lock_timeout,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s,30s
arg_idle_in_transaction_session_timeout,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000,30000
benchmark_begin,NaN,2026-06-20 08:34:03,2026-06-20 08:35:56,2026-06-20 08:42:24,NaN,2026-06-20 08:59:46,2026-06-20 09:02:20,2026-06-20 09:08:56,NaN,2026-06-20 09:25:17,2026-06-20 09:27:51,2026-06-20 09:37:55
benchmark_end,NaN,2026-06-20 08:34:28,2026-06-20 08:36:22,2026-06-20 08:44:41,NaN,2026-06-20 09:00:42,2026-06-20 09:03:18,2026-06-20 09:12:26,NaN,2026-06-20 09:26:14,2026-06-20 09:28:48,2026-06-20 09:38:47
benchmark_duration,NaN,25,26,137,NaN,56,58,210,NaN,57,57,52
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [28]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2
code,1781936763,1781936763,1781936763,1781936763,1781938146,1781938146,1781938146,1781938146,1781939856,1781939856,1781939856,1781939856
configuration,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2
type_tenants,,,,,,,,,,,,
num_tenants,0,0,0,0,0,0,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False,False,False,False,False,False,False

## Get Non-Constant Attributes

These attributes are (most probably) used to analyze performance.

In [29]:
collectors.get_non_constant(df).T

phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2
code,1781936763,1781936763,1781936763,1781936763,1781938146,1781938146,1781938146,1781938146,1781939856,1781939856,1781939856,1781939856
configuration,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1
experiment_run,1,1,2,2,1,1,2,2,1,1,2,2
client,1,2,1,2,1,2,1,2,1,2,1,2
pod_count,1,2,1,2,1,2,1,2,1,2,1,2
SF,3.00,3.00,3.00,3.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00,6.00
num_of_queries,22,44,22,44,22,44,22,44,22,44,22,44
time [s],25,25,137,25,56,58,210,57,57,57,52,57
Geo Times [s],0.63,0.59,1.37,0.62,1.45,1.35,2.50,1.33,1.31,1.28,1.30,1.31
Power@Size [~Q/h],17216.26,18240.76,7885.59,17467.87,14855.57,15987.40,8649.36,16205.71,16484.37,16825.16,16582.04,16516.82
Throughput@Size,9504.00,19008.00,1734.31,19008.00,8485.71,16386.21,2262.86,16673.68,8336.84,16673.68,9138.46,16673.68
job,1781936763-PostgreSQL-1-1-1-1,1781936763-PostgreSQL-1-1-2-1,1781936763-PostgreSQL-1-2-1-1,1781936763-PostgreSQL-1-2-2-1,1781938146-PostgreSQL-1-1-1-1,1781938146-PostgreSQL-1-1-2-1,1781938146-PostgreSQL-1-2-1-1,1781938146-PostgreSQL-1-2-2-1,1781939856-PostgreSQL-1-1-1-1,1781939856-PostgreSQL-1-1-2-1,1781939856-PostgreSQL-1-2-1-1,1781939856-PostgreSQL-1-2-2-1
time_load,325.00,325.00,325.00,325.00,627.00,627.00,627.00,627.00,342.00,342.00,336.00,336.00
time_preload,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,1.00,0.00,0.00
time_generate,22.00,22.00,22.00,22.00,19.00,19.00,19.00,19.00,18.00,18.00,17.00,17.00
time_ingest,88.00,88.00,88.00,88.00,178.00,178.00,178.00,178.00,43.00,43.00,51.00,51.00
time_postload,211.00,211.00,211.00,211.00,425.00,425.00,425.00,425.00,267.00,267.00,265.00,265.00
pods,1,2,1,2,1,2,1,2,1,2,1,2
host_disk,1297521,1297513,1297515,1297513,1297683,1297694,1298572,1298581,1314934,1314936,1314945,1314951
loading_parameters_SF,3,3,3,3,6,6,6,6,6,6,6,6
benchmarking_parameters_SF,3,3,3,3,6,6,6,6,6,6,6,6
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856
sut_storage_storageClassName,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,cephcsi,None,None,None,None
sut_storage_storageSize,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,30Gi,10Gi,10Gi,10Gi,10Gi
benchmark_begin,NaN,2026-06-20 08:34:03,2026-06-20 08:35:56,2026-06-20 08:42:24,NaN,2026-06-20 08:59:46,2026-06-20 09:02:20,2026-06-20 09:08:56,NaN,2026-06-20 09:25:17,2026-06-20 09:27:51,2026-06-20 09:37:55
benchmark_end,NaN,2026-06-20 08:34:28,2026-06-20 08:36:22,2026-06-20 08:44:41,NaN,2026-06-20 09:00:42,2026-06-20 09:03:18,2026-06-20 09:12:26,NaN,2026-06-20 09:26:14,2026-06-20 09:28:48,2026-06-20 09:38:47
benchmark_duration,NaN,25,26,137,NaN,56,58,210,NaN,57,57,52
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-1-2,1781936763-PostgreSQL-1-2-1,1781936763-PostgreSQL-1-2-2,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-1-2,1781938146-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-2-2,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-1-2,1781939856-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-2-2

# Performance at Ingestion per Run

This shows loading performance per experiment run.

In [30]:
df = collect.get_loading_per_run()
df.T

,1781936763-PostgreSQL-1-1,1781936763-PostgreSQL-1-2,1781938146-PostgreSQL-1-1,1781938146-PostgreSQL-1-2,1781939856-PostgreSQL-1-1,1781939856-PostgreSQL-1-2
code,1781936763,1781936763,1781938146,1781938146,1781939856,1781939856
configuration,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1
experiment_run,1,2,1,2,1,2
SF,3,3,3,3,3,3
time_load,325.00,325.00,627.00,627.00,342.00,336.00
time_preload,1.00,1.00,1.00,1.00,1.00,0.00
time_generate,22.00,22.00,19.00,19.00,18.00,17.00
time_ingest,88.00,88.00,178.00,178.00,43.00,51.00
time_postload,211.00,211.00,425.00,425.00,267.00,265.00
loading_pods,8,8,8,8,8,8
terminals,0,0,0,0,0,0
tenant_id,,,,,,
type_tenants,,,,,,
num_tenants,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False
Throughput [SF/h],33.23,33.23,17.22,17.22,31.58,32.14

## With Metadata

Connection infos are added.

In [31]:
df = collect.add_metadata(df)
df.T

add_metadata: combine on columns code configuration experiment_run

,1781936763-PostgreSQL-1-1,1781936763-PostgreSQL-1-2,1781938146-PostgreSQL-1-1,1781938146-PostgreSQL-1-2,1781939856-PostgreSQL-1-1,1781939856-PostgreSQL-1-2
code,1781936763,1781936763,1781938146,1781938146,1781939856,1781939856
configuration,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1,PostgreSQL-1
experiment_run,1,2,1,2,1,2
SF,3,3,3,3,3,3
time_load,325.00,325.00,627.00,627.00,342.00,336.00
time_preload,1.00,1.00,1.00,1.00,1.00,0.00
time_generate,22.00,22.00,19.00,19.00,18.00,17.00
time_ingest,88.00,88.00,178.00,178.00,43.00,51.00
time_postload,211.00,211.00,425.00,425.00,267.00,265.00
loading_pods,8,8,8,8,8,8
terminals,0,0,0,0,0,0
tenant_id,,,,,,
type_tenants,,,,,,
num_tenants,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False
Throughput [SF/h],33.23,33.23,17.22,17.22,31.58,32.14
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-2-1
job,1781936763-PostgreSQL-1-1-1-1,1781936763-PostgreSQL-1-2-1-1,1781938146-PostgreSQL-1-1-1-1,1781938146-PostgreSQL-1-2-1-1,1781939856-PostgreSQL-1-1-1-1,1781939856-PostgreSQL-1-2-1-1
benchmark_run,1,1,1,1,1,1
client,1,1,1,1,1,1
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
pods,1,1,1,1,1,1
num_worker,0,0,0,0,0,0
datadisk,0,0,0,0,0,0
host_RAM,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464
host_CPU,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570
host_GPU,,,,,,
host_Cores,224,224,224,224,224,224
host_host,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic
host_node,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36
host_disk,1297521,1297515,1297683,1298572,1314934,1314945
host_datadisk,0,0,0,0,0,0
host_volume_size,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0
host_cuda,,,,,,
host_hugepages_total,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0
host_cpu_list,0-223,0-223,0-223,0-223,0-223,0-223
host_requests_cpu,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,6,6,6,6
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,
loading_parameters_PODS_TOTAL,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8
loading_parameters_BEXHOMA_TENANT_BY,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0
loading_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856
sut_storage_storageClassName,cephcsi,cephcsi,cephcsi,cephcsi,NaN,NaN
sut_storage_storageSize,30Gi,30Gi,30Gi,30Gi,10Gi,10Gi
sut_storage_keep,True,True,True,True,True,True
sut_storage_storageConfiguration,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
arg_max_connections,640,640,640,640,640,640
arg_max_worker_processes,16,16,16,16,16,16
arg_max_parallel_workers,16,16,16,16,16,16
arg_max_parallel_workers_per_gather,8,8,8,8,8,8
arg_max_parallel_maintenance_workers,4,4,4,4,4,4
arg_shared_buffers,16GB,16GB,16GB,16GB,16GB,16GB
arg_effective_cache_size,40GB,40GB,40GB,40GB,40GB,40GB
arg_work_mem,512MB,512MB,512MB,512MB,512MB,512MB
arg_maintenance_work_mem,2GB,2GB,2GB,2GB,2GB,2GB
arg_autovacuum,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,1h,1h,1h,1h,1h,1h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0
arg_lock_timeout,30s,30s,30s,30s,30s,30s
arg_idle_in_transaction_session_timeout,30000,30000,30000,30000,30000,30000
benchmark_begin,NaN,2026-06-20 08:35:56,NaN,2026-06-20 09:02:20,NaN,2026-06-20 09:27:51
benchmark_end,NaN,2026-06-20 08:36:22,NaN,2026-06-20 09:03:18,NaN,2026-06-20 09:28:48
benchmark_duration,NaN,26,NaN,58,NaN,57

# Combine Performance and Monitoring

This includes filtering for the first client and incorporating efficiency metrics to track performance relative to resource usage.

In [32]:
client = 1

df_performance_monitoring = collect.get_monitoring_aggregated_per_phase(type="stream")
df_performance = collect.get_performance_aggregated_per_phase()
merged_df = pd.merge(df_performance, df_performance_monitoring, left_index=True, right_index=True, how='left')

merged_df = merged_df[merged_df['client'] == client]

#merged_df['E_Tpx'] = merged_df['Goodput (requests/second)'] / merged_df['CPU Utilization Time [s]'] * 600.
#merged_df['E_Lat'] = 1./np.sqrt(merged_df['Latency Distribution.Average Latency (microseconds)']*merged_df['CPU Utilization Time [s]']/1E6)
#merged_df['E_RAM'] = (merged_df['Goodput (requests/second)']) / merged_df['Memory Usage [MiB]']
merged_df.T

add_metadata: combine on index and column 'job'

,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-2-1
code,1781936763,1781936763,1781938146,1781938146,1781939856,1781939856
configuration,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1
phase_x,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-2-1
experiment_run,1,2,1,2,1,2
client,1,1,1,1,1,1
benchmark_run,1,1,1,1,1,1
pod_count,1,1,1,1,1,1
SF,3.00,3.00,6.00,6.00,6.00,6.00
num_of_queries,22,22,22,22,22,22
time [s],25,137,56,210,57,52
Geo Times [s],0.63,1.37,1.45,2.50,1.31,1.30
Power@Size [~Q/h],17216.26,7885.59,14855.57,8649.36,16484.37,16582.04
Throughput@Size,9504.00,1734.31,8485.71,2262.86,8336.84,9138.46
tenant_id,0,0,0,0,0,0
Memory Usage [MiB],4433.55,4081.14,7511.99,5351.83,8961.61,5840.26
Memory Usage Cached [MiB],8787.55,7761.44,16667.08,12408.97,19100.86,14995.45
CPU Utilization,0.32,0.17,1.25,0.55,2.33,1.76
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],11.43,384.88,50.35,1057.12,186.73,114.27
CPU User Time [s],10.67,311.51,38.23,860.76,149.26,86.37
CPU System Time [s],0.77,73.37,12.12,196.36,37.47,27.90
Network Rx Total [MiB],0.00,3304.33,31.45,6636.94,1.89,1.89
Network Tx Total [MiB],0.00,23.27,5946.02,41.41,1.88,1.91
Filesystem Read Total [MiB],0.02,3779.83,0.02,14142.70,0.00,0.00
Filesystem Write Total [MiB],0.02,14124.86,0.02,39895.09,504.00,0.00
Core Utilization Variance [%],0.63,0.24,0.31,0.31,0.27,0.29
Max Core Utilization [%],39.24,26.98,26.27,19.57,21.07,23.25
I/O Wait [%],11.74,7.24,9.15,7.83,5.07,1.99
Total I/O Wait Time [s],87.99,712.41,116.04,834.26,170.12,62.54
Number of Idle Sessions,0.00,0.15,0.00,0.00,0.53,0.00
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,7.00,7.00,6.00,7.00,2.00,7.00
Number of Active Application Sessions,7.00,7.00,6.00,7.00,3.00,7.00
Longest Active Transaction,1.07,8.47,0.07,16.42,1.95,1.23
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,4.13,0.00,3.13,0.00,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,8.47,0.00,16.28,0.00,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,0.00,529712.00,1494449.00,1850164.00,1499019.00,1499348.00
Buffer Cache Hit Count,3157.00,7072328.00,30879600.00,28985341.00,35067119.00,25318376.00
Buffer Cache Hit Ratio,0.91,0.99,0.97,0.98,0.97,0.97
Index Scan Count,0.00,1269186.00,5622186.00,5622177.00,5653812.00,3701997.00
Index Tuple Fetch Count,0.00,5764541.00,17957255.00,17957246.00,19089599.00,17137685.00
Index Cache Hit Ratio,0.45,1.00,1.00,1.00,1.00,1.00
Table Buffer Hit Count,0.00,3322386.00,14226125.00,12317532.00,18304811.00,14414250.00
Table Blocks Read Count,0.00,492280.00,1356899.00,1712241.00,1364722.00,1365051.00
Table Cache Hit Ratio,0.91,0.98,0.90,0.94,0.89,0.89
Total Cache Hit Ratio,0.91,0.99,0.97,0.98,0.97,0.97
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,10.46,20.65,12.42,16.50,4.91,18.21
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,10.46,20.65,12.42,16.50,4.91,18.21
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,0.00,NaN,0.00,NaN,NaN
Number of WAL Segments,205.00,205.00,410.00,410.00,410.00,410.00
Total WAL Size [GiB],3.20,3.20,6.41,6.41,6.41,6.41
WAL Segments Growth Rate [segments/s],0.72,0.00,0.20,0.00,1.43,1.32
WAL Growth Rate [MiB/s],11.51,0.00,3.22,0.00,22.92,21.19
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00
phase_y,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-2-1

## With Metadata

Connection infos are added.

In [33]:
df = collect.add_metadata(merged_df)
df.T

add_metadata: combine on index and column 'phase'

phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-2-1
code,1781936763,1781936763,1781938146,1781938146,1781939856,1781939856
configuration,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1
phase_x,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-2-1
experiment_run,1,2,1,2,1,2
client,1,1,1,1,1,1
benchmark_run,1,1,1,1,1,1
pod_count,1,1,1,1,1,1
SF,3.00,3.00,6.00,6.00,6.00,6.00
num_of_queries,22,22,22,22,22,22
time [s],25,137,56,210,57,52
Geo Times [s],0.63,1.37,1.45,2.50,1.31,1.30
Power@Size [~Q/h],17216.26,7885.59,14855.57,8649.36,16484.37,16582.04
Throughput@Size,9504.00,1734.31,8485.71,2262.86,8336.84,9138.46
tenant_id,0,0,0,0,0,0
Memory Usage [MiB],4433.55,4081.14,7511.99,5351.83,8961.61,5840.26
Memory Usage Cached [MiB],8787.55,7761.44,16667.08,12408.97,19100.86,14995.45
CPU Utilization,0.32,0.17,1.25,0.55,2.33,1.76
CPU Throttle,0.00,0.00,0.00,0.00,0.00,0.00
CPU Throttled Time [s],0.00,0.00,0.00,0.00,0.00,0.00
CPU Utilization Time [s],11.43,384.88,50.35,1057.12,186.73,114.27
CPU User Time [s],10.67,311.51,38.23,860.76,149.26,86.37
CPU System Time [s],0.77,73.37,12.12,196.36,37.47,27.90
Network Rx Total [MiB],0.00,3304.33,31.45,6636.94,1.89,1.89
Network Tx Total [MiB],0.00,23.27,5946.02,41.41,1.88,1.91
Filesystem Read Total [MiB],0.02,3779.83,0.02,14142.70,0.00,0.00
Filesystem Write Total [MiB],0.02,14124.86,0.02,39895.09,504.00,0.00
Core Utilization Variance [%],0.63,0.24,0.31,0.31,0.27,0.29
Max Core Utilization [%],39.24,26.98,26.27,19.57,21.07,23.25
I/O Wait [%],11.74,7.24,9.15,7.83,5.07,1.99
Total I/O Wait Time [s],87.99,712.41,116.04,834.26,170.12,62.54
Number of Idle Sessions,0.00,0.15,0.00,0.00,0.53,0.00
Number of Idle-in-transaction Sessions,0.00,0.00,0.00,0.00,0.00,0.00
Number of Idle-in-transaction Aborted Sessions,0.00,0.00,0.00,0.00,0.00,0.00
Number of Active Sessions,7.00,7.00,6.00,7.00,2.00,7.00
Number of Active Application Sessions,7.00,7.00,6.00,7.00,3.00,7.00
Longest Active Transaction,1.07,8.47,0.07,16.42,1.95,1.23
Longest Idle Session (no transaction),0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction,0.00,0.00,0.00,0.00,0.00,0.00
Longest Idle-in-Transaction (Aborted),0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on I/O,0.00,4.13,0.00,3.13,0.00,0.00
Active Backends Waiting on WAL,0.00,0.00,0.00,0.00,0.00,0.00
Active Backends Waiting on Locks,0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (I/O Wait),0.00,8.47,0.00,16.28,0.00,0.00
Max Transaction Duration (WAL Wait),0.00,0.00,0.00,0.00,0.00,0.00
Max Transaction Duration (Lock Wait),0.00,0.00,0.00,0.00,0.00,0.00
Disk Blocks Read Count,0.00,529712.00,1494449.00,1850164.00,1499019.00,1499348.00
Buffer Cache Hit Count,3157.00,7072328.00,30879600.00,28985341.00,35067119.00,25318376.00
Buffer Cache Hit Ratio,0.91,0.99,0.97,0.98,0.97,0.97
Index Scan Count,0.00,1269186.00,5622186.00,5622177.00,5653812.00,3701997.00
Index Tuple Fetch Count,0.00,5764541.00,17957255.00,17957246.00,19089599.00,17137685.00
Index Cache Hit Ratio,0.45,1.00,1.00,1.00,1.00,1.00
Table Buffer Hit Count,0.00,3322386.00,14226125.00,12317532.00,18304811.00,14414250.00
Table Blocks Read Count,0.00,492280.00,1356899.00,1712241.00,1364722.00,1365051.00
Table Cache Hit Ratio,0.91,0.98,0.90,0.94,0.89,0.89
Total Cache Hit Ratio,0.91,0.99,0.97,0.98,0.97,0.97
BGWriter Efficiency Ratio (Cleaned / Allocated),0.00,0.00,0.00,0.00,0.00,0.00
BGWriter Stopped Due to Max Pages,0.00,0.00,0.00,0.00,0.00,0.00
Total Locks Current,10.46,20.65,12.42,16.50,4.91,18.21
AccessExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
AccessShareLocks Current,10.46,20.65,12.42,16.50,4.91,18.21
ExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
RowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
RowShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
ShareLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
ShareRowExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
ShareUpdateExclusiveLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
SIReadLocks Current,0.00,0.00,0.00,0.00,0.00,0.00
Autoanalyze Run Count,0.00,0.00,0.00,0.00,0.00,0.00
Autovacuum Run Count,0.00,0.00,0.00,0.00,0.00,0.00
Dead tuples per vacuum operation [tuples/vacuum],NaN,0.00,NaN,0.00,NaN,NaN
Number of WAL Segments,205.00,205.00,410.00,410.00,410.00,410.00
Total WAL Size [GiB],3.20,3.20,6.41,6.41,6.41,6.41
WAL Segments Growth Rate [segments/s],0.72,0.00,0.20,0.00,1.43,1.32
WAL Growth Rate [MiB/s],11.51,0.00,3.22,0.00,22.92,21.19
Average WAL Segment Size [MiB],16.00,16.00,16.00,16.00,16.00,16.00
phase_y,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-2-1
job,1781936763-PostgreSQL-1-1-1-1,1781936763-PostgreSQL-1-2-1-1,1781938146-PostgreSQL-1-1-1-1,1781938146-PostgreSQL-1-2-1-1,1781939856-PostgreSQL-1-1-1-1,1781939856-PostgreSQL-1-2-1-1
dockerimage,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3,postgres:18.3
time_load,325.00,325.00,627.00,627.00,342.00,336.00
time_preload,1.00,1.00,1.00,1.00,1.00,0.00
time_generate,22.00,22.00,19.00,19.00,18.00,17.00
time_ingest,88.00,88.00,178.00,178.00,43.00,51.00
time_postload,211.00,211.00,425.00,425.00,267.00,265.00
terminals,0,0,0,0,0,0
pods,1,1,1,1,1,1
loading_pods,8,8,8,8,8,8
num_worker,0,0,0,0,0,0
type_tenants,,,,,,
num_tenants,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False
datadisk,0,0,0,0,0,0
host_RAM,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464,2164173246464
host_CPU,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570,INTEL(R) XEON(R) PLATINUM 8570
host_GPU,,,,,,
host_Cores,224,224,224,224,224,224
host_host,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic,6.8.0-111-generic
host_node,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36,cl-worker36
host_disk,1297521,1297515,1297683,1298572,1314934,1314945
host_datadisk,0,0,0,0,0,0
host_volume_size,0,0,0,0,0,0
host_volume_used,0,0,0,0,0,0
host_cuda,,,,,,
host_hugepages_total,0,0,0,0,0,0
host_hugepages_free,0,0,0,0,0,0
host_cpu_list,0-223,0-223,0-223,0-223,0-223,0-223
host_requests_cpu,4,4,4,4,4,4
host_requests_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
host_limits_cpu,0,0,0,0,0,0
host_limits_memory,64Gi,64Gi,64Gi,64Gi,64Gi,64Gi
loading_parameters_SF,3,3,6,6,6,6
loading_parameters_STORE_RAW_DATA,1,1,1,1,1,1
loading_parameters_STORE_RAW_DATA_RECREATE,0,0,0,0,0,0
loading_parameters_BEXHOMA_SYNCH_LOAD,1,1,1,1,1,1
loading_parameters_BEXHOMA_SYNCH_GENERATE,1,1,1,1,1,1
loading_parameters_TRANSFORM_RAW_DATA,1,1,1,1,1,1
loading_parameters_TPCH_TABLE,,,,,,
loading_parameters_PODS_TOTAL,8,8,8,8,8,8
loading_parameters_PODS_PARALLEL,8,8,8,8,8,8
loading_parameters_BEXHOMA_TENANT_BY,,,,,,
loading_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0
loading_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0
benchmarking_parameters_SF,3,3,6,6,6,6
benchmarking_parameters_DBMSBENCHMARKER_RECREATE_PARAMETER,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_SHUFFLE_QUERIES,False,False,False,False,False,False
benchmarking_parameters_DBMSBENCHMARKER_DEV,0,0,0,0,0,0
benchmarking_parameters_TENANT_BY,,,,,,
benchmarking_parameters_TENANT_NUM,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_BY,,,,,,
benchmarking_parameters_BEXHOMA_TENANT_NUM,0,0,0,0,0,0
benchmarking_parameters_BEXHOMA_TENANT_ID,0,0,0,0,0,0
sut_parameters_BEXHOMA_WORKER_LIST,,,,,,
sut_parameters_BEXHOMA_WORKER_LIST_SPACE,,,,,,
sut_parameters_BEXHOMA_WORKER_NAME,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_WORKER_SERVICE,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-3,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6,bexhoma-worker-postgresql-tpch-6
sut_parameters_BEXHOMA_SUT_NAME,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781936763,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781938146,bexhoma-sut-postgresql-1-1781939856,bexhoma-sut-postgresql-1-1781939856
sut_storage_storageClassName,cephcsi,cephcsi,cephcsi,cephcsi,None,None
sut_storage_storageSize,30Gi,30Gi,30Gi,30Gi,10Gi,10Gi
sut_storage_keep,True,True,True,True,True,True
sut_storage_storageConfiguration,postgresql,postgresql,postgresql,postgresql,postgresql,postgresql
arg_max_connections,640,640,640,640,640,640
arg_max_worker_processes,16,16,16,16,16,16
arg_max_parallel_workers,16,16,16,16,16,16
arg_max_parallel_workers_per_gather,8,8,8,8,8,8
arg_max_parallel_maintenance_workers,4,4,4,4,4,4
arg_shared_buffers,16GB,16GB,16GB,16GB,16GB,16GB
arg_effective_cache_size,40GB,40GB,40GB,40GB,40GB,40GB
arg_work_mem,512MB,512MB,512MB,512MB,512MB,512MB
arg_maintenance_work_mem,2GB,2GB,2GB,2GB,2GB,2GB
arg_autovacuum,off,off,off,off,off,off
arg_wal_level,minimal,minimal,minimal,minimal,minimal,minimal
arg_max_wal_senders,0,0,0,0,0,0
arg_max_wal_size,32GB,32GB,32GB,32GB,32GB,32GB
arg_checkpoint_timeout,1h,1h,1h,1h,1h,1h
arg_checkpoint_completion_target,1.0,1.0,1.0,1.0,1.0,1.0
arg_lock_timeout,30s,30s,30s,30s,30s,30s
arg_idle_in_transaction_session_timeout,30000,30000,30000,30000,30000,30000
benchmark_begin,NaN,2026-06-20 08:35:56,NaN,2026-06-20 09:02:20,NaN,2026-06-20 09:27:51
benchmark_end,NaN,2026-06-20 08:36:22,NaN,2026-06-20 09:03:18,NaN,2026-06-20 09:28:48
benchmark_duration,NaN,26,NaN,58,NaN,57
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-2-1

## Test for Header Informations

These infos are used to relate connection infos to benchmarking results.

In [34]:
df[['phase', 'code', 'configuration', 'experiment_run', 'client', 'type_tenants', 'num_tenants', 'vol_tenants']].T

phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-2-1
phase,1781936763-PostgreSQL-1-1-1,1781936763-PostgreSQL-1-2-1,1781938146-PostgreSQL-1-1-1,1781938146-PostgreSQL-1-2-1,1781939856-PostgreSQL-1-1-1,1781939856-PostgreSQL-1-2-1
code,1781936763,1781936763,1781938146,1781938146,1781939856,1781939856
configuration,1781936763-PostgreSQL-1,1781936763-PostgreSQL-1,1781938146-PostgreSQL-1,1781938146-PostgreSQL-1,1781939856-PostgreSQL-1,1781939856-PostgreSQL-1
experiment_run,1,2,1,2,1,2
client,1,1,1,1,1,1
type_tenants,,,,,,
num_tenants,0,0,0,0,0,0
vol_tenants,False,False,False,False,False,False

# Show Warnings per Connection

In [35]:
df = collect.get_total_warnings(query_titles=False)
df.T

,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-1-1-1,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-2-2-1-2
Q1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Show Only Existing Warnings

For demonstration we insert a warning.

In [36]:
demo_config_name = "{code}-PostgreSQL-1-1-1-1-1".format(code=codes[0])
df.loc[demo_config_name,'Q1'] = True
df.T

,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-1-1-1,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-2-2-1-2
Q1,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q10,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q12,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q13,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q14,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q15,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q16,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q17,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q18,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q19,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q20,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q21,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Q22,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [37]:
num_warnings = df.sum().sum()
if num_warnings > 0:
    # remove only False rows
    df = df[~(df == False).all(axis=1)]
    print(df.T)
else:
    print("No warnings")

     1781936763-PostgreSQL-1-1-1-1-1
Q1                              True
Q2                             False
Q3                             False
Q4                             False
Q5                             False
Q6                             False
Q7                             False
Q8                             False
Q9                             False
Q10                            False
Q11                            False
Q12                            False
Q13                            False
Q14                            False
Q15                            False
Q16                            False
Q17                            False
Q18                            False
Q19                            False
Q20                            False
Q21                            False
Q22                            False

# Show Warnings per Connection with Query Titles

In [38]:
df = collect.get_total_warnings(query_titles=True)
df.T

,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-1-1-1,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-2-2-1-2
Pricing Summary Report (TPC-H Q1),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Minimum Cost Supplier Query (TPC-H Q2),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Shipping Priority (TPC-H Q3),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Order Priority Checking Query (TPC-H Q4),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Local Supplier Volume (TPC-H Q5),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q6),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q7),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
National Market Share (TPC-H Q8),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Product Type Profit Measure (TPC-H Q9),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q10),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Important Stock Identification (TPC-H Q11),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Shipping Modes and Order Priority (TPC-H Q12),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Customer Distribution (TPC-H Q13),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q14),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Top Supplier Query (TPC-H Q15),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Parts/Supplier Relationship (TPC-H Q16),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Small-Quantity-Order Revenue (TPC-H Q17),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Large Volume Customer (TPC-H Q18),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Discounted Revenue (TPC-H Q19),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Potential Part Promotion (TPC-H Q20),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Suppliers Who Kept Orders Waiting Query (TPC-H Q21),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Global Sales Opportunity Query (TPC-H Q22),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [39]:
num_warnings = df.sum().sum()
if num_warnings > 0:
    # remove only False rows
    df = df[~(df == False).all(axis=1)]
    print(df.T)
else:
    print("No warnings")

No warnings

# Show Errors per Connection with Query Titles

In [40]:
df = collect.get_total_errors(query_titles=True)
df.T

,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-1-1-1,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-2-2-1-2
Pricing Summary Report (TPC-H Q1),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Minimum Cost Supplier Query (TPC-H Q2),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Shipping Priority (TPC-H Q3),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Order Priority Checking Query (TPC-H Q4),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Local Supplier Volume (TPC-H Q5),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q6),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q7),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
National Market Share (TPC-H Q8),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Product Type Profit Measure (TPC-H Q9),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q10),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Important Stock Identification (TPC-H Q11),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Shipping Modes and Order Priority (TPC-H Q12),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Customer Distribution (TPC-H Q13),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Forecasting Revenue Change (TPC-H Q14),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Top Supplier Query (TPC-H Q15),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Parts/Supplier Relationship (TPC-H Q16),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Small-Quantity-Order Revenue (TPC-H Q17),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Large Volume Customer (TPC-H Q18),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Discounted Revenue (TPC-H Q19),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Potential Part Promotion (TPC-H Q20),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Suppliers Who Kept Orders Waiting Query (TPC-H Q21),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
Global Sales Opportunity Query (TPC-H Q22),False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Show Only Existing Errors

In [41]:
num_errors = df.sum().sum()
if num_errors > 0:
    # remove only False rows
    df = df[~(df == False).all(axis=1)]
    print(df.T)
else:
    print("No errors")

No errors

# Show Latencies per Query and Connection with Query Titles

In [42]:
df = collect.get_query_latencies(query_titles=True)
df.T

DBMS,1781936763-PostgreSQL-1-1-1-1-1,1781936763-PostgreSQL-1-1-2-1-1,1781936763-PostgreSQL-1-2-2-1-2,1781936763-PostgreSQL-1-1-2-1-2,1781936763-PostgreSQL-1-2-2-1-1,1781936763-PostgreSQL-1-2-1-1-1,1781938146-PostgreSQL-1-1-1-1-1,1781938146-PostgreSQL-1-2-2-1-1,1781938146-PostgreSQL-1-2-2-1-2,1781938146-PostgreSQL-1-1-2-1-2,1781938146-PostgreSQL-1-1-2-1-1,1781938146-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-1-1-1-1,1781939856-PostgreSQL-1-2-1-1-1,1781939856-PostgreSQL-1-1-2-1-1,1781939856-PostgreSQL-1-2-2-1-1,1781939856-PostgreSQL-1-1-2-1-2,1781939856-PostgreSQL-1-2-2-1-2
Pricing Summary Report (TPC-H Q1),1647.15,1661.82,1730.56,1733.12,1764.28,50884.55,3016.79,3520.24,3571.66,4013.31,4091.84,60828.99,3734.36,3757.55,3796.51,3815.72,4077.52,4110.78
Minimum Cost Supplier Query (TPC-H Q2),551.36,532.51,643.84,559.45,526.40,23309.64,1561.73,1514.80,1548.39,1322.00,1240.14,50708.50,1311.32,1221.77,1494.82,1483.32,1271.72,1368.57
Shipping Priority (TPC-H Q3),578.44,556.64,547.92,561.55,566.39,26269.00,1753.05,1343.78,1263.90,1739.94,1898.66,31297.06,2137.79,1908.49,1171.26,1312.48,1193.35,1277.20
Order Priority Checking Query (TPC-H Q4),244.97,251.67,297.34,272.93,273.97,269.92,559.98,470.57,432.46,677.99,596.29,539.80,656.33,642.89,487.00,541.62,648.74,508.74
Local Supplier Volume (TPC-H Q5),547.38,510.80,782.24,581.81,603.32,1287.31,1476.87,1569.13,1569.43,1458.59,1350.08,2222.72,1538.47,1593.77,1847.99,1359.30,1452.45,1407.47
Forecasting Revenue Change (TPC-H Q6),311.68,314.25,596.46,303.54,306.70,295.46,814.20,718.25,690.46,705.72,737.40,745.00,824.75,849.10,697.08,764.78,711.70,767.60
Forecasting Revenue Change (TPC-H Q7),723.06,708.40,978.48,724.90,896.86,742.00,1817.20,2227.21,2227.66,1773.37,1773.69,1840.41,1780.55,1945.88,1712.09,1883.13,1710.06,2288.79
National Market Share (TPC-H Q8),395.91,350.56,389.34,345.03,585.62,10641.88,1354.38,700.49,699.93,704.58,704.46,17946.89,840.29,801.48,634.50,1045.19,682.96,939.89
Product Type Profit Measure (TPC-H Q9),1002.44,963.96,1115.92,1015.01,1208.46,4833.17,2391.18,2502.37,2502.50,2929.13,3173.32,6498.09,3067.71,1964.39,2448.19,2042.35,2964.64,1823.53
Forecasting Revenue Change (TPC-H Q10),1223.90,1172.77,1259.75,1175.42,1175.16,1245.66,1488.87,1889.91,1721.65,1669.58,1639.54,1582.34,1535.42,1708.74,2232.64,1551.53,1634.64,1556.49
Important Stock Identification (TPC-H Q11),189.39,214.63,182.25,189.66,189.35,192.21,465.53,430.14,470.95,434.02,385.72,375.09,403.45,438.00,408.61,424.93,427.02,438.02
Shipping Modes and Order Priority (TPC-H Q12),481.08,491.66,441.36,489.63,529.13,494.60,1114.34,1010.14,1022.19,1078.53,1145.46,1013.13,1181.11,1129.37,1083.18,1143.18,1073.97,1139.96
Customer Distribution (TPC-H Q13),1983.57,2548.29,2712.02,2445.71,2021.08,2654.36,4774.35,4126.29,4201.57,5655.63,5683.02,3904.57,4711.18,4454.59,5093.10,5180.51,4530.22,5106.16
Forecasting Revenue Change (TPC-H Q14),537.82,545.85,555.57,539.50,1029.95,709.60,1666.58,1713.87,1718.61,1203.65,1120.14,1083.11,905.18,1162.66,827.75,1214.09,808.32,1180.80
Top Supplier Query (TPC-H Q15),419.93,412.79,417.18,418.60,481.13,477.55,1027.90,896.65,884.36,965.63,1057.61,868.89,958.63,1425.90,963.78,994.30,945.00,1241.97
Parts/Supplier Relationship (TPC-H Q16),403.80,394.39,434.73,405.32,441.06,433.49,660.60,707.20,683.10,686.93,703.46,694.69,723.92,660.82,625.20,645.90,623.65,1022.40
Small-Quantity-Order Revenue (TPC-H Q17),1678.46,1626.51,1467.24,1724.15,1512.10,1885.74,4320.87,3520.88,3715.73,3621.78,3645.67,3339.57,4272.48,3544.69,4013.38,3886.81,3767.11,3407.53
Large Volume Customer (TPC-H Q18),8459.44,8765.12,7642.19,9435.53,7944.65,8035.92,20458.67,23183.37,21899.78,21599.11,19819.71,18221.10,22379.34,18846.63,22459.38,21432.63,22248.78,22827.57
Discounted Revenue (TPC-H Q19),237.18,87.19,97.02,160.95,86.10,119.12,194.59,188.53,191.36,189.07,176.46,258.66,175.07,183.97,192.33,182.97,190.75,178.22
Potential Part Promotion (TPC-H Q20),796.92,282.46,323.76,716.77,345.04,965.96,2095.44,2029.31,2360.05,2181.72,2041.92,3592.98,815.25,809.69,861.69,807.99,780.08,806.13
Suppliers Who Kept Orders Waiting Query (TPC-H Q21),736.25,554.57,523.63,582.79,543.17,522.87,2011.98,1244.47,1213.93,1271.14,1308.63,1243.41,1301.04,1343.86,1967.58,1346.95,1322.86,2218.80
Global Sales Opportunity Query (TPC-H Q22),139.57,136.33,144.56,153.00,143.05,196.83,380.67,255.85,276.32,249.04,249.42,277.65,248.52,260.59,351.43,257.24,538.62,268.46

In [43]:
zip_all_results(path, codes)

Zipping /data/benchmarks/1781936763 to /data/benchmarks/1781936763.zip...
Zipping /data/benchmarks/1781938146 to /data/benchmarks/1781938146.zip...
Zipping /data/benchmarks/1781939856 to /data/benchmarks/1781939856.zip...
✅ Done zipping all folders.